### PR TITLE
Bugfix: Empty reshares in Diaspora

### PR DESCRIPTION
**Pull request by annando**
This bugfix was already accepted for the Develop-branch. The bug is very annoying on larger systems. (Single user systems aren't affected by this).

### CODE REVIEW

**Comment by fabrixxm** [comment]
This wasn't expected to be merged in master :-)

**Comment by tugelbend** [comment]
Damn! Sorry, but I thought the request was made to the correct branch. How do we deal with this now?

**Comment by fabrixxm** [comment]
We will manually merge the develop branch into master and deal whit some conflicts, i think..
Nothing big

**Comment by tugelbend** [comment]
I will better keep my hands of the merge buttons here ;-)

**Pull request merged**
