### PR TITLE
Pagecache for frequently fetched pages

### PR DESCRIPTION
**Pull request by annando**
On one of my servers I monitored high loads during times when there had been a lot of page requests for posts on the AP level. With this coding the load should be lowered, since we cache the post for 5 minutes.

### CODE REVIEW

**Comment by nupplaphil** [comment]
Why don't you use the existing cache classes instead of a new table?

**Comment by MrPetovan** [comment]
I'm with @nupplaphil , you can keep the `PageCache` class but use the internal cache instead of DB calls.

**Comment by annando** [comment]
The specialty here is that the lifetime of the cache is renewed with every access. Also the table is really lean. Especially in this use case we need a lot of performance and cannot afford a lot of overhead. The cache is fine for avoiding i/o or network requests. But here we have to really fast since we have to reduce the amount of SQL queries.

**Comment by MrPetovan** [comment]
The cache is faster than the database in any circumstance. You can also renew the expiration on access with the cache. I know you’re a database expert, but not all problems should be solved with databases.

Especially temporary cache.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
