### PR TITLE
The days are getting shorter, like the list of removed notices ...

### PR DESCRIPTION
**Pull request by annando**

### CODE REVIEW

**Comment by MrPetovan** [comment]
Part of #5470

**Comment by MrPetovan** [comment]
The list of removed notice is actually getting longer thanks to you. It's the list of remaining notices that gets shorter.

**Comment by annando** [comment]
@MrPetovan have you already been called "nitpicker" today? 😁

**Comment by MrPetovan** [comment]
Not yet, it's an unusual day.

**Pull request merged**
