### PR TITLE
Add library/ to autoload

### LINKED ISSUE #4116: Move PHP libraries from library to composer
Third part of the code restructuration with #4090 and #3878, this aims at getting rid of the `library` folder in favor of Composer.

The move process is the following for each library:
- Look for the same library name in Packagist, the Composer repository
- If it doesn’t exist, look for the library name in Pear, Composer can import them directly
- If found either way, don’t directly use `composer require` as the version likely changed since it was last updated in `library`. Instead edit `composer.json` to add the package and its target version manually to the list. You can use a star to make Composer import the latest minor version that’s unlikely to break compatibility
- Remove require calls to the library in the code. The Composer autoloader should take care of requiring the imported library.
- **Test the feature**! If you can’t, drop the whole process, clean up any changes you made to composer or the code and move on to the next library. Everything in `library` is currently working so we’d rather not introduce regressions because of a lack of testing.
- Even with minor version increases it’s possible to have breaking changes, make the necessary adjustments in the code and test, *test*, **test**!
- Once you’ve make sure the new library in Composer is working properly, delete the relevant file(s) in `library` and commit the files in `vendor`. Normally the vendor folder is excluded from git, but we don’t have updated our release process to still include them while trusting `develop` users to run `composer install`.
- Celebrate! 🎉

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #4116 (for real this time)

Here they are, the last three, the irredeemable PHP class files, utterly obsolete but crucially required by our project. They are the clay feet our colossus can't walk without, the famous "technical debt" buzzword made code.

I almost turned them into PSR-4 compliant files in a special `Friendica\Legacy` namespace, but I stopped myself short of committing yet more butchery on those venerable libraries from another time. Let them rest.

The final trick has been to make Composer explicitly look for classes in the `library/` folder and add them to the autoloader class maps. This way they can be used even if they don't follow any naming convention (or any convention at all).

Make sure to run `util/composer.phar install` after this PR as the autoload files aren't stored in the composer.lock. But at this point what fool doesn't run it after a pull from `develop`?

### CODE REVIEW

**Comment by annando** [comment]
Could you deprecate the "yourls" addon as well?

**Comment by MrPetovan** [comment]
Indeed, should I create a post-update function to clean the settings/hooks since I can't force uninstall the addon before deleting the files.

Or did you have another deprecation method in mind?

**Comment by annando** [comment]
I just meant that you mark the addon in the header as deprecated. If it is done in a special way then it won't appear on the addon list anymore.

**Comment by MrPetovan** [comment]
Oooh, sneaky. When do we actually remove deprecated addons?

**Comment by annando** [comment]
When we like to :-)

**Comment by MrPetovan** [comment]
Then we definitely should do it now since it isn't doing anything anymore. It's not "Unsupported", it's "Does Nothing" level of deprecation.

**Comment by annando** [comment]
I guess we had to create some "remove addon" function to be sure.

**Comment by tobiasd** [comment]
> Oooh, sneaky. When do we actually remove deprecated addons?

Usually at the 2nd release after the deprecation, so if someone would like to take over the maintenance of the addon they can step forwar. Afterwards they are moved to the repository with tthe deprecated addons to archive them just in case someone needs them.

**Comment by MrPetovan** [comment]
Thanks, it makes sense.

**Comment by annando** [comment]
BTW: I'm not getting this error when trying to post via API:
```
[31-Jan-2018 20:42:33 UTC] PHP Fatal error:  Cannot declare class OAuthConsumer, because the name is already in use in /.../library/OAuth1.php on line 12
```

**Comment by MrPetovan** [comment]
now or now?

**Comment by MrPetovan** [comment]
Is it related to addons?

**Comment by annando** [comment]
It interferes with the class "FKOAuth1". When I disable the FKOAuth part in function "api_login" (in include/api.php) everything works.

**Comment by MrPetovan** [comment]
You can remove the similar bits in `src/Network/FKOAuth1.php` that already are in `library/OAuth1.php` then, or rename them if they aren't the same. Or wait until I get to it tonight. Please submit an issue in the meantime.

**Comment by MrPetovan** [comment]
I wish I had a mobile app good enough to test the Friendica API...

**Comment by annando** [comment]
It isn't related to the addons. I disabled them and it still crashed.

**Comment by MrPetovan** [comment]
At first glance I can't see what would be wrong with our current setup, there aren't any double declaration in the files themselves. To get to the bottom of it someone™️ should debug the Composer autoloader to see where `library/OAuth1.php` can be loaded twice.

**Comment by annando** [comment]
Question is what we do in the meantime. I wouldn't like to have this bug running in the wild for too long as it prevents the API usage.

**Comment by MrPetovan** [comment]
I'm working on it.

**Comment by MrPetovan** [comment]
Triggered #4377

**Pull request merged**
