### PR TITLE
Update to Composer v2

### LINKED ISSUE #8583: Move from fxpio/composer-asset-plugin to fxpio/foxy
Branched from https://github.com/friendica/friendica/issues/8578#issuecomment-623776217

## The current situation

We use the [`fxpio/composer-asset-plugin` Composer plugin](https://github.com/fxpio/composer-asset-plugin) to define front-end dependencies in the `composer.json` file from Bower or npm repository. This enabled us not to have to have a full copy of these libraries in our versioning system and manage upgrades centrally.

## The potential problems

- The Composer plugin is meant to be replaced with [the `fxpio/foxy` Composer plugin](https://github.com/fxpio/foxy), although we haven't had any specific issue with it.
- [Bower is deprecated](https://bower.io/blog/2017/how-to-migrate-away-from-bower/). The repository still is maintained, but who knows how long for.

## The migration challenges

The new Composer plugin seems to be slightly more involved that the current one. I like the separation of dependencies between `composer.json` and `package.json` but it now requires local NodeJs, npm and/or Yarn dependencies. It should be a big deal for admins already dabbling with the `develop` branch but it is a hurdle nonetheless.

It also requires someone™ to go over the list of current Bower dependencies and find the counterpart in either npm or Yarn. I've been satisfied with Bower dependencies because they usually were only comprised of distribution files, e.g. only the library itself, not the sources/tests that we have no use for. I wonder if I can find the same convenience in Yarn or if it requires local compiling/building/bundling that I'm unfamiliar with.

## What are the alternative?

I also found [Asset Packagist](https://asset-packagist.org) which is supposed to be a drop-in replacement for `fxpio/composer-asset-plugin`. It wouldn't alleviate our dependency to Bower and would only remove the Composer plugin inconvenience, which has been minimal so far thanks to our use of `composer.lock`. It also duplicates packages in existing repositories in their repository, which requires us to trust a smaller structure to maintain a separate repository, which I'm uneasy about given that even Bower is on the way out.

### LINKED ISSUE #14519: Support for Composer 1 will be shutdown on August 1st 2025
We have to switch to Composer 2 in one of the coming releases. It would be great to have some support from people who are familiar with this.

### PR DESCRIPTION
**Pull request by Art4**
Fixes #14519.
Closes #8583

This PR updates Composer to 2.8.2 and installs the npm/bower dependencies using https://asset-packagist.org/ instead of the deprecated `fxp/composer-asset-plugin`.

### CODE REVIEW

**Comment by toddy15** [comment]
Hi @Art4,

thanks for this work! I've just checked the (deprecated) Bower assets, and most of them can just switch to npm. Maybe you can amend your PR with a new commit to include these three npm assets instead:

```diff
                "bower-asset/base64": "^1.0",
-               "bower-asset/chart-js": "^2.8",
-               "bower-asset/dompurify": "^1.0",
-               "bower-asset/fork-awesome": "^1.1",
+               "npm-asset/chart.js": "^2.8",
+               "npm-asset/dompurify": "^1.0",
+               "npm-asset/fork-awesome": "^1.1",
```

Please note that chart.js uses a dot instead of the hyphen on npm.

The last Bower dependency (base64) is not yet available on asset-packagist.org for npm (https://asset-packagist.org/package/npm-asset/Base64), although the package is on npm: https://www.npmjs.com/package/Base64.

If this package becomes available, please note the it is spelled with a capital "B" on npm.

Regards,
Tobias

**Comment by toddy15** [comment]
Oh, and as a side note: fork-awesome is deprecated and should ideally be removed entirely. I've not looked at the code of Friendica to see where and how the font is used, but it should be replaced with SVG icons. But I guess that's for another PR. :smile:

**Comment by annando** [comment]
@toddy15 I'm currently working on a PR for SVG icons. Mostly missing is the license part.

**Comment by Art4** [comment]
@toddy15 Thanks for your advise. I replaced the 3 bower dependencies with npm.

> The last Bower dependency (base64) is not yet available on asset-packagist.org for npm (https://asset-packagist.org/package/npm-asset/Base64), although the package is on npm: https://www.npmjs.com/package/Base64.
> 
> If this package becomes available, please note the it is spelled with a capital "B" on npm.

Composer works case-insensitive, so I cannot install `npm-asset/Base64`:

```bash
$ bin/composer.phar require npm-asset/Base64:^1.0
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port).
./composer.json has been updated

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

In RootPackageLoader.php line 174:
                                                                                                                         
  require.npm-asset/Base64 is invalid, it should not contain uppercase characters. Please use npm-asset/base64 instead.  
```

But looking at Base64 it seems to be only a polyfill for `window.btoa()` and `window.atob()`. https://www.npmjs.com/package/Base64

caniuse stated that this functions are widely available across major browsers nowadays. 

https://caniuse.com/atob-btoa

grafik

I think we can safely remove this dependency.

**Comment by toddy15** [comment]
@Art4 Thanks for switching from Bower to npm. There is another issue (#8583) which has some more context on the replacement of the fxp-plugin. Also, see my PR #13300, in which I tried to remove Base64.js -- that polyfill is still needed. :smile:

However, if Friendica wants to remove the Bower dependency completely, it would be an option to just include Base64.js directly in the Friendica source code. There's not much upstream development going on, and it's only about 1.2K minified.

**Comment by Art4** [comment]
> @Art4 Thanks for switching from Bower to npm. There is another issue (#8583) which has some more context on the replacement of the fxp-plugin. Also, see my PR #13300, in which I tried to remove Base64.js -- that polyfill is still needed. 😄
> 
> However, if Friendica wants to remove the Bower dependency completely, it would be an option to just include Base64.js directly in the Friendica source code. There's not much upstream development going on, and it's only about 1.2K minified.

Thanks for pointing this out. :+1: I would suggest to address the Base64.js problem in a separate PR. This PR is only about updating composer to v2.

@annando I think this PR is ready for review. After merge we can close #14519 and #8583.

**Update**: Sorry, I have to take another look into this PR. Addons are broken atm because the file names don't comply with PSR-4. I think we must load them as [classmap](https://getcomposer.org/doc/04-schema.md#classmap) instead.

```
Class MCryptWrapper located in ./addon/securemail/vendor/singpolyma/openpgp-php/lib/openpgp_mcrypt_wrapper.php does not comply with psr-4 autoloading standard (rule: Friendica\Addon\ => ./addon). Skipping.
Class ComposerAutoloaderInitSecuremailAddon located in ./addon/securemail/vendor/composer/autoload_real.php does not comply with psr-4 autoloading standard (rule: Friendica\Addon\ => ./addon). Skipping.
Class Composer\Autoload\ClassLoader located in ./addon/securemail/vendor/composer/ClassLoader.php does not comply with psr-4 autoloading standard (rule: Friendica\Addon\ => ./addon). Skipping.
Class Composer\Autoload\ComposerStaticInitSecuremailAddon located in ./addon/securemail/vendor/composer/autoload_static.php does not comply with psr-4 autoloading standard (rule: Friendica\Addon\ => ./addon). Skipping.
Class Diasphp located in ./addon/diaspora/diasphp.php does not comply with psr-4 autoloading standard (rule: Friendica\Addon\ => ./addon). Skipping.
Class Diaspora_Connection located in ./addon/diaspora/Diaspora_Connection.php does not comply with psr-4 autoloading standard (rule: Friendica\Addon\ => ./addon). Skipping.
```

**Comment by Art4** [comment]
@annando I've fixed the most warnings for autoloading of the addons, but it could have some improvements in a followup PR.

**Comment by annando** [comment]
Thanks for your work! I'm currently waiting for the pipeline to run again. Sorry for the delay.

**Comment by Art4** [comment]
@annando Is there something broken in the pipeline? Should we add an alternative CI system like Github Actions as a backup?

**Comment by annando** [comment]
@Art4 the pipeline is running on systems from people who are engaged with the project. Due to time constraints it wasn't possible by now to fix the pipeline. But I hope that it will run in the next few days again. We had used Github actions before, but there had been the long term plan to move from Github to our own repository. And this of course means that all stuff needs to run on our own systems.

**Review by MrPetovan — APPROVED** [review]
Thank you for your work!

**Comment by MrPetovan** [comment]
> I've just checked the (deprecated) Bower assets, and most of them can just switch to npm. Maybe you can amend your PR with a new commit to include these three npm assets instead:

The reason I chose the Bower dependencies originally is because their footprint was more limited than npm's. In particular, Bower was exposing the distribution files instead of the development files, which we have no use for.

**Comment by annando** [comment]
Since the pipeline still isn't running, I guess that sooner or later we have to risk the merging. But since a lot of productive machines are running on this branch, we have to make sure that the system will continue to work. Have you tested on your productive machine if everything still works, including the addons?

**Comment by Art4** [comment]
@annando Thanks for your trust but I strongly advise against merging this PR without running the CI pipelines and testing it yourself. Hence I'm pretty sure that everything works as before I have to little experience with the code of Friendica. I only tested it on my local machine inside the devcontainer. And I'm already working with this changes in the followup PRs. But I cannot test all addons simply because I don't know the purposes of most of them.

I recommend that you test this PR on your machine. And I can offer to create a new PR for bringing back the Github Actions as an alternative CI for cases like this where the main CI service is not available.

**Comment by annando** [comment]
My development machine is a production server with a bunch of people on it, so I'm very reluctant to run tests on it.

Concerning the Github actions: Yeah, possibly it would be a good idea as a backup. What do you think @tobiasd and @nupplaphil?

**Comment by MrPetovan** [comment]
This is blocking several downstream changes, and it is pretty easy to revert even on a production machine, I'd say let's do it.

**Comment by annando** [comment]
Yeah, I don't like blocking pull requests. Later this day I can test this PR on my machine. If everything works, then I will accept it.

**Comment by Art4** [comment]
See #14538.

**Comment by Art4** [comment]
now the ci pipelines fail :see_no_evil: 

https://ci.friendi.ca/repos/2/pipeline/2460/19

I will investigate this issue.

**Comment by Art4** [comment]
Composer requires the `addon` folder for installation. Can we clone the friendica-addons repo first?

Update: We can simply create an empty addon folder, see #14539.

**Pull request merged**
