### PR TITLE
Move mod/manifest to src/Module/Manifest

### PR DESCRIPTION
**Pull request by nupplaphil**
Part of #4090 

@rudloff Was the additional array-index for the `icons` intended?

I replaced
grafik

with
grafik

Seems cleaner for me

### CODE REVIEW

**Comment by MrPetovan** [comment]
There may be a hint here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json

**Comment by nupplaphil** [comment]
It contains the array index, but the `src` isn't mentioned. Nevertheless I better not replace the template, because it seems to work since 04/2017

**Comment by Rudloff** [comment]
> There may be a hint here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json

This doc is about web extensions. The doc for web app manifests is here: https://developer.mozilla.org/en-US/docs/Web/Manifest
(`icons` must be an array because the app can have different icons with different sizes.)

**Comment by nupplaphil** [comment]
So it should now work as is again :-)

**Comment by nupplaphil** [comment]
@Mrpetovan I think it's mergable. I reverted the manifest output :-)

**Pull request merged**
