### PR TITLE
Fix Broken Profile Links

### PR DESCRIPTION
**Pull request by miqrogroove**
I'll be honest, I have no idea what I'm doing in any Javascript.  However, I did figure out that this fixes the Issue #5205.

Feel free to suggest any better way.

### CODE REVIEW

**Comment by MrPetovan** [comment]
I believe this would remove all hovercards from the frio theme. Hovercards are heavily used to access a contact page from a profile link/picture. There must be a better way to do this.

**Comment by miqrogroove** [comment]
I've tested this patch on Chrome for Windows and Chrome for Android.  I will check some others for you.

**Comment by MrPetovan** [comment]
I fully trust you this patch fixes the mentioned issue, but it also completely removes a prominent feature of the frio theme. As such, I can't accept it unless it only targets the mobile context.

**Comment by miqrogroove** [comment]
When I say I tested it, I mean I saw no such feature before or after I applied the patch.  Everything fixed, nothing broken.

**Comment by miqrogroove** [comment]
The strange thing is that I can see hovercards on other sites, but they never appear on my own site.  So I'm not sure how to test this.

**Comment by miqrogroove** [comment]
In the Edge browser, I can't see hovercards on any site.

**Comment by miqrogroove** [comment]
And according to Chrome dev tools, my site responds status 401 for every hovercard request.

**Comment by miqrogroove** [comment]
Patch needs to be re-written based on new information.

**Pull request closed without merging**
