### PR TITLE
Add check for relationship with remote user for connect display

### LINKED ISSUE #6255: Connect Button appears on always connected forums
### Expected behavior
If i visit a connected forum the button _Connect_ should not appear

### Actual behavior
The button _Verbinden/Connect_ appears, but i am always connected with the forum
friendica-kontakt

### Steps to reproduce the problem
Visit a connected forum page

### Friendica version you encountered the problem
2018.12-rc

### Friendica source (git, zip)
git

### PHP version
7.2.13

### SQL version
10.0.34-MariaDB

### PR DESCRIPTION
**Pull request by MrPetovan**
Should fix #6255

I can't be arsed to test on my own but this should hide the "Connect" button if the remote user is already connected to the visited profile.

### CODE REVIEW

**Comment by annando** [comment]
You could use the function ```isFollower``` that I introduced lately.

**Comment by AndyHee** [comment]
@MrPetovan let me know when it's ready and we can test it across nodes.

**Comment by MrPetovan** [comment]
> @MrPetovan let me know when it's ready and we can test it across nodes.

Done, and I may have had messed up the relationship constants in my original code 😳

**Comment by AndyHee** [comment]
`Done, and I may have had messed up the relationship constants in my original code flushed`

I think this works now (again)! I checked with another node from my own node on that code; my contact's page doesn't show the connect button any more.

**Pull request merged**
