### PR TITLE
Some more "accept" parameters are added

### PR DESCRIPTION
**Pull request by annando**
This PR adds a lot of "accept" parameter values to http requests.

### CODE REVIEW

**Comment by nupplaphil** [comment]
Because this parameter is now an important part of all http calls, shouldn't we add it as a explicit parameter in the methods itself with the default value set?

-> I would prefer it

**Comment by annando** [comment]
Having it an explicit parameter can cause a slight problem at one specific place in the code. There we are using signed headers. And the `accept` header is part of the signed header. So it has to be provided via the parameter with the general header values.

**Comment by nupplaphil** [comment]
We could allow both and the array would overwrite the parameter in case it's set. So we would have a 90percent fit for transparency :)

The reason behind it is that using this class will highlite the importance of this parameter, whereas as an array value, you would have to explicit think about it

**Comment by annando** [comment]
Okay, that sounds fine for me.

**Comment by annando** [comment]
@nupplaphil will you perform this change after this PR was merged?

**Comment by MrPetovan** [comment]
I was expecting you to do it, but I can merge this first.

**Comment by nupplaphil** [comment]
I'll do it :) but I guess not before saturday evening ;-)

**Comment by annando** [comment]
@MrPetovan I was unsure how to do it. There seems to be not only the class with the whole code but also something that is called "interface" (which I guess I have to change as well, although I don't know what is is used for), but I simply don't know if there are even more places that I have to change. So I prefer to keep my hands off there.

**Comment by MrPetovan** [comment]
An Interface dictates the methods that all the classes inheriting from it should implement. So you're right, when adding a new parameter to a method, you should start with the interface, and then update all the classes that inherit from it.

**Pull request merged**
