### PR TITLE
Frontend to set the parent-uid field

### PR DESCRIPTION
**Pull request by annando**
See here: https://github.com/friendica/friendica/issues/4319#issuecomment-366507596

### CODE REVIEW

**Comment by MrPetovan** [comment]
I just checked out your branch, and I believe my delegate page is in some sort of weird transition.

new-delegate-parent-uid

As you can see, there is an existing page manager (me), but I'm still suggested to delegate to another account in the dropdown list.

**Comment by annando** [comment]
You are always your own page manager. And yes, I think this page really needs some redesign to make it usable.

**Comment by annando** [comment]
Additionally the both delegation types are independent to each other. Means: There is a clear "parent - children" relation that doesn't allow chain delegations. But this doesn't interfere with the possibility to grant other accounts limited access.

**Comment by MrPetovan** [comment]
I’m even more confused about delegation now. I’ll merge this to go forward with the release.

**Pull request merged**
