### PR TITLE
2021.09 CHANGELOG

### PR DESCRIPTION
**Pull request by tobiasd**
As usual, let this be the last PR merged into the develop branch before the 2021.09 release.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Review by MrPetovan — APPROVED** [review]

**Review by MrPetovan — APPROVED** [review]

**Review by MrPetovan — APPROVED** [review]

**Comment by nupplaphil** [comment]
@tobiasd - can you rebase this branch? There's a strange error during the Drone exection, which seems to happen because of it .. But I'm not totally sure.

**Comment by MrPetovan** [comment]
Where's the bump to PHP version 7.3?

**Comment by tobiasd** [comment]
@MrPetovan 

> Additional commas in function parameters list is only supported from PHP 7.3 onwards. I'm happy this hasn't been reported before, it means most active Friendica admins are running at least PHP 7.3 which they absolutely should.

Your comment on the PR implies to me, that 7.3 is the minimal requirement.

**Comment by MrPetovan** [comment]
> Your comment on the PR implies to me, that 7.3 is the minimal requirement.

Ah, I see what you mean, but while it was true before the PR, it isn't anymore that I know of. I removed the existing PHP 7.3 exceptions in this PR you are mentioning so we should be back to PHP 7.2 as a minimum version.

**Review by MrPetovan — APPROVED** [review]

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
