### PR TITLE
Move objects to model (redux)

### PR DESCRIPTION
**Pull request by MrPetovan**
Related to #3878 

Redux of #4031

No errors to report anymore.

### CODE REVIEW

**Comment by annando** [comment]
Thanks for the fast reaction. What about the addons? How can we reopen that PR?

**Comment by MrPetovan** [comment]
You just need to revert the revert 😛

**Comment by annando** [comment]
Me and git ...

**Comment by annando** [comment]
For some reason the "scaleDown" commit wasn't merged ...

**Comment by MrPetovan** [comment]
Thanks for all your extra work!

**Pull request merged**
