### PR TITLE
phpunit compat 5.6 vs 7.x

### PR DESCRIPTION
**Pull request by tobiasd**
Testing travis stuff, please don't merge before travis check passes

### CODE REVIEW

**Comment by tobiasd** [comment]
tests looking good now

**Comment by MrPetovan** [comment]
Can't we use `\PHPUnit\Framework\TestCase` in PHP 5.6?

**Comment by MrPetovan** [comment]
Ah, it changes the version of the `phpunit` package pulled by Composer.

**Comment by tobiasd** [comment]
Yes, no we can't. It changed between the versions. We just have to remember for later when we drop the 5.6 support.

**Pull request merged**
