### PR TITLE
Replace Core\Lock wrapper with DI::lock() method

### PR DESCRIPTION
**Pull request by nupplaphil**
I'd like to reduce the ways how we can use classes.
Currently:
- per Dependency Injection
```php
class ClassA
{
      /** @var ILock */
      private $lock;
      
      public function __construct(ILock $lock)
      {
           $this->lock = $lock;
      }

      public function method()
      {
            $this->lock->acquire('lock');
      }
}
```
- per static wrapper:
```php
class ClassA
{
      public function method()
      {
            Lock::acquire('lock');
      }
}
```
- per DI class:
```php
class ClassA
{
      public function method()
      {
            DI::lock()->acquire('lock');
      }
}
```

I'd like to remove the static wrapper in favor of the DI class to reduce the ways from 3 to 2 ways.
=> It has the benefit that IDEs can now search **all** method occurrences of a dynamic class, since there isn't a wrapper inbetween ("man-in-the-middle") anymore.

### CODE REVIEW

**Comment by nupplaphil** [comment]
@annando would that be OK for you? To switch from `StaticClass::method()` to `DI::class()->method()` ? It would help to make the occurrences of the methods more transparent

**Comment by annando** [comment]
Well, for my newly chosen editor this is bad. Visual Studio Code don't seem to work well with this way - in difference with the current way, where auto completion and searching through class methods work well with the editor.

**Comment by nupplaphil** [comment]
oh .. that's bad .. @MrPetovan this will affect #8065 as well, since we use the same kind of annotations!

**Comment by annando** [comment]
In fact this here currently is nice:
Bildschirmfoto von 2020-01-07 00-28-16

Selecting one class:
Bildschirmfoto von 2020-01-07 00-33-09

Listing class methods:
Bildschirmfoto von 2020-01-07 00-43-54

And displaying the description:
Bildschirmfoto von 2020-01-07 00-45-22

It is sad when I'm now loosing this.

There are some reasons why I'm stuck with VSCode. One is that it is free. More important we begin using it at our company as well. And last but not least it has a special SSH mode, where it is split in a frontend part that is running on the local machine and a backend part that is running on the machine where the code currently lies. This allows for working remotely via SSH. But unlike some SSH based file system, I'm able of doing all server stuff like creating branches, merging them, executing shells, connecting to the local database ("local" here stands for the server) and all other stuff. I just got used to this.

**Comment by nupplaphil** [comment]
That's reasonable and you shall not loose the benefits of the IDE.. If I explicit add the method `lock()` in the `DI` class, instead of using the `@method static` annotation functionality, it would work for you the same way...

**Comment by MrPetovan** [comment]
Are you adding concrete methods to `DI` in this PR?

**Comment by nupplaphil** [comment]
Not in this. I already prepared a followup.

**Pull request merged**
