### PR TITLE
Introduce new way of static/dynamic bridge / CleanUp deprecated methods

### PR DESCRIPTION
**Pull request by nupplaphil**
Replacing #7956 

This is the attempt to replace the BaseObject::getClass() method with something easier usable.

I introduce Friendica\DI as a new, static container which returns dynamically loaded classes. Each new class has to be added as /* @method static Class class() */ phpDoc and added to the const array.
That's it, now it's usable as DI::class() and it's typesafe :-) .. So no more object returns and no more getClass() abstract calls.

e.g.: DI::dba() returns a Database instance, DI::cache() returns a ICache instance.

I already replaced a lot of calls and "deprecated" App-methods. It's a little bit of cleanup, so the codebase will get a little bit more readable (currently a lot of code is strikethroug with "deprecated" but without a proper replacement - until now).

@MrPetovan I "just" replaced the way how `Introduction` is fetched, so we can discuss the general without harming this PR. I'd like to close this `BaseObject::getClass()` chapter, because it will make it more easy to use Dependency-Injection, nevertheless of the Repository/Model-discussion :-)

**Merge https://github.com/friendica/friendica-addons/pull/927 too**

### CODE REVIEW

**Comment by annando** [comment]
Shouldn't the functions be named exactly like the classes?

**Comment by nupplaphil** [comment]
However we like it :)

It's a static bridge to dynamic classes. I thought we could reduce the name length for convenience reasons. But we can also name it `DI::introduction()` instead of `DI::intro()`.

**Comment by nupplaphil** [comment]
If you like or find it more readable, we can switch from abstract `DI::*` to the namespace, like

* `App::baseUrl()`
* `Core::Config`

It's already prepared for such a cut

**Comment by annando** [comment]
Will this work with autocompletion for clients like VSCode?

**Comment by nupplaphil** [comment]
Hmmmm tbh I didn't try it out. Every client who can interpret `@method` annotations will understand it. This is the specification: https://docs.phpdoc.org/references/phpdoc/tags/method.html

I think it should, but if not, we can explicit create these methods instead. But than we have to rethink the usage of the `@property` annotations as well. They work similar. @mrpetovan do you know more?

**Comment by MrPetovan** [comment]
I know that PhpStorm uses `@property` and `@method` for autocompletion.

**Comment by MrPetovan** [comment]
First of all, amazing work. I understand using `DI::something` for a single class instance that is supposed to be available globally, but what about `DI::intro()`? Won't it return the same object over and over even then we might want a different one?

For example:
```php
$intro1 = DI::intro()->fetch(['id' => 1]);
$intro2 = DI::intro()->fetch(['id' => 2]);
```
Will `$intro1` be modified by the second call?

**Comment by nupplaphil** [comment]
Nope, the magic is this change:
https://github.com/friendica/friendica/pull/8019/commits/37596114b81aa16a6390de1898a26a13b49d3dc8#diff-2eb196c95fd469e59d36ebfe6f7e808eR81

Everytime you call `fetch()`, it returns a **new** instance of intro. With the `new static()` method, you create a new child (`Introduction`) and not the parent (`BaseModel`)

**Comment by nupplaphil** [comment]
btw. Merge https://github.com/friendica/friendica-addons/pull/927 needed too ;-)

**Comment by MrPetovan** [comment]
> Nope, the magic is this change:
> [3759611#diff-2eb196c95fd469e59d36ebfe6f7e808eR81](https://github.com/friendica/friendica/commit/37596114b81aa16a6390de1898a26a13b49d3dc8#diff-2eb196c95fd469e59d36ebfe6f7e808eR81)

Thanks, I would have missed it in the gigantic diff. I'm starting to warm up to the idea of the global factory for models, as long as the model objects can still be directly interacted with.

**Comment by nupplaphil** [comment]
> > Nope, the magic is this change:
> > [3759611#diff-2eb196c95fd469e59d36ebfe6f7e808eR81](https://github.com/friendica/friendica/commit/37596114b81aa16a6390de1898a26a13b49d3dc8#diff-2eb196c95fd469e59d36ebfe6f7e808eR81)
> 
> Thanks, I would have missed it in the gigantic diff. I'm starting to warm up to the idea of the global factory for models, as long as the model objects can still be directly interacted with.

I tried to commit each replacement so you can check them step by step ;)

**Comment by MrPetovan** [comment]
Merge conflicts.

**Comment by nupplaphil** [comment]
Nope, I didn't touched them :)

**Comment by MrPetovan** [comment]
Sorry, conflicts again after I merged the L10n PR.

**Comment by nupplaphil** [comment]
I'll now hold my hands still until you merged it, because I don't want to rebase the PR over and over again :D

**Comment by annando** [comment]
There are still calls to `getBaseURL` in the code.

**Comment by MrPetovan** [comment]
I'm on it.

**Comment by annando** [comment]
Same is true for the calls to `getApp`

**Comment by MrPetovan** [comment]
Everything has been taken care of.

**Comment by nupplaphil** [comment]
.. Uff.. Too much rebase caused too much pain .. Sorry and thank you @annando and @mrpetovan for helping with this madness ...

**Pull request merged**
