### PR TITLE
Global and Portable Contact

### PR DESCRIPTION
**Pull request by zeroadam**
This is a new PR with a bit cleaner code branched from the current develop. The last PR got unruly and was several commits back compared to current develop.
Related to #3878

### CODE REVIEW

**Comment by zeroadam** [comment]
Given that there were merges to develop and some redirecting mid way through GlobalContact and PortableContact, I had a lot of commits and still some strangeness going on with the branch.

So, I decided to "re-do" the work on a new branch that was started from the current develop on @annando 's most recent code. It is much cleaner and don't contain quite as much "code standards fixing". I have been running it on my node since this morning, and everything is running quite well, including the poller/workerqueue.

**Comment by MrPetovan** [comment]
I'm ready to merge right now if nobody has anything bad to say about it.

**Comment by annando** [comment]
Only thing is, that it seems as if all methods are declared public, but I guess that some of them are only privately used. But this can be solved later.

**Comment by annando** [comment]
@MrPetovan great that you reviewed it as well. I just thought if I should accept it anyway with or without your approval ;-)

**Comment by MrPetovan** [comment]
All those methods were meant as public before, not sure if we gain anything by making some of them private arbitrarily.

**Comment by annando** [comment]
I'm the "as local as possible" guy. The more something is local, the easier are changes.

**Comment by MrPetovan** [comment]
Oh yeah, it makes complete sense if we built a class from the ground up. Here we are migrating library files into static classes, so it is a little different.

**Comment by annando** [comment]
I wrote much of the stuff in that file, so I know which functions were meant for internal stuff only.

**Comment by zeroadam** [comment]
I know what you mean @annando there were several functions in that class that are only called via self:: from elsewhere in that class. As you say, I could clean that up later!

**Pull request merged**
