### PR TITLE
Prevent template generation in media/[photo|attachment]/upload output

### LINKED ISSUE #12888: Return only bb-code link on image-upload
### Is the feature request related to a problem? Please describe.

I built the new image-upload feature. And there i tried the url `/media/photo/upload?response=json&album="` to upload the image.
On  this i get only a "status: ok" or so back... 
When i leave the response-parameter away, i get the whole website-base (headers, scripts... MUCH htmal-code) and as content only the bb-code for the image/url to the just uploaded image, which i can paste bare as it is into the textarea.
I have to parse the html response and grad in the DOM for the right field to get its content... 

### Describe the feature you'd like

I want with `response=json` a second field with the formatted url or another response with `response=url` parameter only the text for the bb-encoded url to the new uploaded image. So the traffic is much less than now. only the few characters.

Something like this:
```
{ status: ok, 
bb: [url=http://...[img]asldklsj[/img]][/url], 
originalfilename: blafoo.jpg, 
album: "Albumname",
deleteLink: "http://....."
...
}
```

### Describe alternatives you've considered

--

### Additional context

### PR DESCRIPTION
**Pull request by MrPetovan**
Untested, should Fix #12888

### CODE REVIEW

**Comment by annando** [comment]
Is it intended against RC or develop?

**Comment by MrPetovan** [comment]
RC, it's a bug. We never intended to show the page template in the response to these modules.

**Comment by annando** [comment]
Only thing is: The `Untested` is something that I think we should avoid in RC.

**Comment by MrPetovan** [comment]
Fiiine.

**Comment by MrPetovan** [comment]
Reportedly tested in https://github.com/friendica/friendica/pull/12883#issuecomment-1473914365

**Comment by xundeenergie** [comment]
The upload of attachments returns just

`[attachment]5[/attachment] `

Is it possible, to return also a bbcode-link to the attachment?
Then i can improve the image-uploader also for other attachments.

**Comment by MrPetovan** [comment]
This would be another issue.

**Comment by annando** [comment]
This `[attachment]5[/attachment]` refers to the attachment with the id `5` in the database.

**Comment by MrPetovan** [comment]
Please move this discussion to https://github.com/friendica/friendica/issues/12902

**Pull request merged**
