### PR TITLE
[frio] Add icons on photo view page.

### PR DESCRIPTION
**Pull request by astifter**
screenshot_2018-08-19 friedrich

There are two issues (IMHO) with the photo view:
- The links are still text and I have changed many of them to icons nowadays.
- The header "just" links back to the album but it looks like it belongs to the photo which I find missleading.

I propose to add icons and move the link back the album there as well:
screenshot_2018-08-19 friedrich 1

@rabuzarus Comments, feedback? Thanks!

### CODE REVIEW

**Comment by MrPetovan** [comment]
@rabuzarus hasn't been consistent replying to GitHub pings, I think we should wait for 24 hours max before going forward with this.

**Comment by rabuzarus** [comment]
I think we should visually separate the normal "photo actions" and  "going backt to the album view". What do you think about left align "going back to album view" and leave the photo actions right aligned?

**Comment by rabuzarus** [comment]
ahh and the album name shouldn't be light gray (even if it is a link) because it presents an important information. So I would suggest using the normal text color.

Further improvement suggestion:
- use awesome font lock icon for `lock` symbol

**Comment by astifter** [comment]
I updated the commit to 
- move the "back link" to the left
- also change the lock. (could not test this since I couldn't get the lock to appear.)

Also, the items change colour depending on the mouse hover (they did this already, just to comment on the color issue):

not hover over frame:
screenshot_2018-08-19 friedrich 3

hovered:
screenshot_2018-08-19 friedrich 4

**Comment by rabuzarus** [comment]
thx

**Pull request merged**
