### PR TITLE
Check null for acl-fields

### LINKED ISSUE #7781: Compose page of frio theme on dev results in blank screen
Compose page results in blank screen.

Friendica Friendica 'Dalmatian Bellflower' 2019.12-dev - 1323 (just updated  but error persist)

Apach error.log:

> [Mon Oct 28 17:19:30.711666 2019] [proxy_fcgi:error] [pid 21828] [client xx.xx.xx.xx:53366] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Friendica\\Util\\ACLFormatter::expand() must be of the type string, null given, called in /path/on/my/server/web/src/Module/Item/Compose.php on line 77 and defined in /path/on/my/server/web/src/Util/ACLFormatter.php:19\nStack trace:\n#0 /path/on/my/server/web/src/Module/Item/Compose.php(77): Friendica\\Util\\ACLFormatter->expand(NULL)\n#1 [internal function]: Friendica\\Module\\Item\\Compose::content()\n#2 /path/on/my/server/web/src/App/Page.php(311): call_user_func(Array)\n#3 /path/on/my/server/web/src/App/Page.php(365): Friendica\\App\\Page->initContent(Object(Friendica\\App\\Module), Object(Friendica\\App\\Mode))\n#4 /path/on/my/server/web/src/App.php(795): Friendica\\App\\Page->run(Object(Friendica\\App), Object(Friendica\\App\\BaseURL), Object(Friendica\\App\\Mode), Object(Friendica\\App\\Module), Object(Friendica\\Core\\L10n\\L10n), Object(Friendica\\Core\\Config\\JitConfiguration), Object...', referer: https://experimental.friendica.hfrc.de/settings/display

### PR DESCRIPTION
**Pull request by nupplaphil**
FollowUp #7765 
Fixes #7781

### CODE REVIEW

**Comment by nupplaphil** [comment]
Merging https://github.com/friendica/friendica-addons/pull/906 too

**Comment by MrPetovan** [comment]
Sorry I didn't check the tests, https://github.com/friendica/friendica/pull/7782/commits/1f535016d473b2e619ff9dc5b45c75b45be92a70 has to be reverted: `ERROR 1101 (42000) at line 79: BLOB, TEXT, GEOMETRY or JSON column 'allow_cid' can't have a default value`

**Comment by annando** [comment]
TEXT fields cannot have a default value in MySQL. See here: https://stackoverflow.com/questions/3466872/why-cant-a-text-column-have-a-default-value-in-mysql

Also "not null" doesn't make sense here, since "NULL" means no permission, while "" means an empty value.

**Comment by nupplaphil** [comment]
fields are reverted with #7784

**Comment by MrPetovan** [comment]
No, it does, since we've considered `null` values as empty string until @nupplaphil added a type-hint to `ACLFormatter::expand()`. Maybe we should just change the parameter to `(string $acl_string = null)` instead.

**Comment by AlfredSK** [comment]
Looks like the dbstructure update is altering the 'item' table. 😱
@nupplaphil Can you tell roughly how long that will take? (my item table is 20GB in size)

**Comment by AlfredSK** [comment]
Ok. Nevermind. I see the other comments now. 😁

**Comment by nupplaphil** [comment]
puh.. you were too quick.. We already reverted the change on the dbstructure since incompatibility :-( .. tbh the update will fail I think, so you've to pull the latest commit again ..

**Comment by AlfredSK** [comment]
All is good. I usually ask first and pull then. :-)

**Pull request merged**
