### PR TITLE
proxy_url: Fix extension extraction for URLs containing a . after a ?

### LINKED ISSUE #3017: Diaspora: Proxyfied images don't play well with Camo
[Camo](https://github.com/atmos/camo) is the image proxy Diaspora chose to circumvent mixed-content warning on HTTPS pods with remote HTTP images. However, it requires that the original URL to be proxyfied correctly set the Content-Type header.

Friendica's `proxy` mod is basically doing the same, except it doesn't keep the Content-Type after the original URL is proxyfied, which leads Camo to refuse to serve it.

Friendica's `proxy` should keep the original Content-Type when serving the requested URL.

Reference thread: https://friendica.mrpetovan.com/display/748ab390a558013435ef52540061b601

### PR DESCRIPTION
**Pull request by Hypolite**
Fixes #3017

### CODE REVIEW

**Comment by Hypolite** [comment]
I don't think it need more comments than what I added, but I can explain a little bit more here.

The code I changed is tasked to guess the extension of a URL probably pointing to a file. Previously, it extracted the string after last dot in the URL, then proceeded to remove any GET parameter starting with a question mark from it. So `https://domain.tld/file.jpg?key=value` would be turned into `jpg?key=value` then `jpg`.

Problem is when the GET parameter contains a dot, it threw off this code. A `https://domain.tld/file.jpg?key=value.2` URL would be turned into `2` without triggering the question mark removal.

My code looks first for a question mark, recording its position. If it doesn't find any, the question mark position simply becomes the end of the string. It then extracts the string between the last dot and the question mark position. So `https://domain.tld/file.jpg?key=value.2` becomes `https://domain.tld/file.jpg` and then `jpg`.

**Comment by annando** [comment]
Question is if a regular expression would be better. The original code is mine - and I'm really bad with RegExps so I solved it differently.

**Comment by Hypolite** [comment]
Ha ha, it's actually trivial with built-in PHp functions: http://php.net/manual/en/function.pathinfo.php#93610

````php
pathinfo(parse_url('URL GOES HERE',PHP_URL_PATH),PATHINFO_EXTENSION)
````

**Comment by annando** [comment]
You have a job :-)

**Comment by Hypolite** [comment]
Job done: #3038

**Pull request merged**
