### PR TITLE
added event icons from frost-mobile to frost

### PR DESCRIPTION
**Pull request by tobiasd**

### CODE REVIEW

**Comment by tobiasd** [comment]
one more for #1953

**Comment by fabrixxm** [comment]
the frost icon were scaled to 16px because the css show them at 16x16 , so bigger images aren't needed...

**Comment by tobiasd** [comment]
but -mobile needs bigger ones? anyhow I'll scale those ASAP

**Comment by fabrixxm** [comment]
you now.. big fingers need big icons....

**Comment by tobiasd** [comment]
resized the icons, small ones are now in as well

**Pull request merged**
