### PR TITLE
move notification to top nav on mobile view

### LINKED ISSUE #7536: [Frio] Show notification icon in mobile view
This is a followup to #6384 somehow, but for Frio. 
I think having the notification icon in the right slide-in menu is unnecessarily complex. Therefore it would be good to have it in the top bar as well. There is enough room to have it.

image 
vs. 
image

The notification dropdown has enough room as well:

image

### PR DESCRIPTION
**Pull request by vinzv**
closes #7536

### CODE REVIEW

**Comment by nupplaphil** [comment]
Please rebase this PR to `friendica:2019.09-rc`, if you want to have this change have an affect to the coming 2019.09 release

**Comment by MrPetovan** [comment]
And after you do that, you'll need to update the target branch of this PR (via the Edit button at the top)

**Comment by MrPetovan** [comment]
Thanks for the rebase, I was able to switch target branch.

**Comment by MrPetovan** [comment]
Why the revert?

**Comment by vinzv** [comment]
Argh, sorry. I never had worked with rebase yet and thought I had made a mistake.

**Comment by MrPetovan** [comment]
You did good actually, you can now reset your branch just before the revert and force-push the branch.

**Pull request merged**
