### PR TITLE
Use a process identifier for logging that contains the pid

### PR DESCRIPTION
**Pull request by annando**
The days I had got problems with workers processes that took a real long time and a high CPU usage. With this change we will now be able to look into the log file and to see what the system is doing right now.

### CODE REVIEW

**Comment by nupplaphil** [comment]
Ha, that's exactly the place where I'm currently trying to use System::createGUID with a prefix either for app or for worker :)

**Comment by nupplaphil** [comment]
@annando @MrPetovan 
I'm sorry I was to late, but isn't 
`System::processID($prefix)` 
the same as 
`System::createGUID(21, $prefix . ':' . str_pad(getmypid() . ':', 8, '0') . ':')` ?

Wouldn't it be better to use System::createGUID in System::processID() to have one kind of unique-generator?

**Comment by annando** [comment]
I don't think that is is needed. Why should we use a function that only will call the same function that is called here? I don't like duplicating of code, but here this isn't the case. And especially both functions are directly together. So people can see them in one glance.

**Comment by nupplaphil** [comment]
Is it really the same function? The createGUID has more checks and logic than just using the uniqid. I thought it's maybe good to use it for the process ID too. But in the end, both will return the same, so for me it's ok :-)

**Comment by nupplaphil** [comment]
One thing is different and maybe it is hard to handle when we want to use the process_id not just for logging:

The length of the ID is not limited and it is depending on the length of the prefix. The createGUID function considers the length of the prefix and creates always an ID with the given length.

**Comment by nupplaphil** [comment]
On thing is different and maybe hard to handle if we want to the process_id not just for logging:

The length of the process id depends on the length of the `$prefix` and is not limited. I think it would be better to use the createGUID because it creates all the time IDs with the same, given length (default = 16)

**Comment by annando** [comment]
This ID is really only meant for logging. The length is defined so that it doesn't interfere with the session identifiers from the frontend. And it does contain the pid that is really only important for the logging, I think.

**Pull request merged**
