### PR TITLE
API: Support for private mails

### PR DESCRIPTION
**Pull request by annando**
We now support some of the API endpoints that are used for private conversations. Direct mails aren't working at the moment with the clients that I tested, although the tests looked fine.

Checking this will be part of a later PR.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Please check the php-cs result to make it happier.

**Review by MrPetovan — APPROVED** [review]

**Comment by annando** [comment]
Done

**Comment by tobiasd** [comment]
Checkst are failing (well only the CS check)

**Comment by nupplaphil** [comment]
> Checkst are failing (well only the CS check) 

Only? :P

**Comment by tobiasd** [comment]
"Only" because it is _only_ one check that is failing, not _checks_ ;-)

**Comment by annando** [comment]
@nupplaphil don't blame me for creating lots of commits *only* with style changes :-)

**Comment by nupplaphil** [comment]
I don't even consider to blame you for your work here :-)

**Pull request merged**
