### PR TITLE
WIP: local oauth #9866

### PR DESCRIPTION
**Pull request by Extarys**
Please don't judge :joy: PHP is mysterious :mage: .
~~See issue #9866~~

[Mastodon OAuth API](https://docs.joinmastodon.org/spec/oauth/)

- I want local oauth to also use php session id, as the template/theme still need it.
- LocalOAuth will extend OAuth.

~~API v2 - Phase 1~~
API OAuth - Phase 1

Side note:
- @MrPetovan told me we need to follow twitter api, so just change the route names and params to fit that as I'm not familiar with it.
- After implementation it may require some tweaking to make it work with existing apps
- This is not a full blown oauth, yet, as clients dont need an app key, etc
- I change variables name throughout the issue. rtok = refresh token. atok = access token.
- I worked hard for this, please don't be mean - I'm not a pro but I did a lot of research. If you spot a mistake please comment.

See: Implement JOSE-type tokens for client-side rendering #9813 
This first phase aim to discuss and implement the following:

- Endpoint to get an access token
- Endpoint to get an access token from a refresh token
- Endpoint to revoke a refresh token
- Endpoint to check which version of the new API is implemented (useful if a client want to see what is implemented or not)

We will also need a way in the user settings to see the list of devices that have a refresh token and easily see last access and a revoke button.

### Mastodon: POST /oauth/token
Required parameters:
Username
Password
Client

- Validate credentials, make sure account isn't suspended, etc
- Generate PASETO token v2.local

Refresh tokens are stored in the database:
**authrefreshtok**

| Field name            | Type                  | Sample                                    |
| --------------------- | --------------------- | ----------------------------------------- |
| user_id               | u integer (ref user) | 916                                       |
| token_id              | varchar(32)           | WlQhpdkP8q7p1eeTNsjg                      |
| expires               | timestamp             | 2021-01-17 10:00:17                       |
| created               | timestamp             | 2021-01-10 10:00:17                       |
| createdByIp           | int(10)?              | 127.0.0.1                                 |
| client                | varchar(30)           | Firefox on Linux                          |
| revoked               | bool                  | false                                     |
| revokedByIp           | int(10)?              | NULL                                      |
| replacedByToken       | string (ref token_id)| dJpMRVmVN4cNN9FVxd26                      |

Side note: PostgreSQL support ip address as a column type.

- On initial request, send an access token and a refresh token.
- After 30 minutes (but before 7 days), client send refresh token
  - Server verify the token was not revoked and was not "replacedByToken"
  - Issue new access token.
  - If the refresh token was revoked or expired, return error 403 { status: 'invalid_rtok', reason: 'replaced' }
  - If everything is alright, generate a new jti/refresh token, update old token in db, add new token in db
- If after 7 days, token has expired, user need to log in again

We need to detect if the request is for mastodon, use the same class and adjust how we proceed.

## GET /api/oath/local/refreshAccessToken
Required parameters:
refresh_token

- Server verify the refresh token was not revoked and was not "replacedByToken"
- Issue new access token - with the jti of the current refresh token.
- If the refresh token was revoked or expired, return error 403 { status: 'invalid_rtok', reason: 'replaced' }

- If refresh token is expired or was replaced:
  - Ask user for credentials (resend alongside the creds the old rtok)

## GET /api/oath/local/replaceRefreshToken
Params:
AccessToken
RefreshToken

- If the token is about to expire (6 days into it's life) - check the jti in the database, find the oldest refresh token.
  - If the first refresh token with that jti was issued more than 6 weeks ago, ask user for credential - start fresh
  - If the original refresh token is younger than 6 weeks old
     - Generate a new jti and refresh token, update old token in db, add new token in db

Both the access token and the refresh token need to be valid/not expired here.

While implementing this, it's important to keep in mind that the end user need some sort of traceability of issued tokens to inspect attempted and successful connections that might not be legitimate.

## GET /api/oath/local/revokeToken
Params:
accessToken
refreshToken

The Access token and refresh roken jti shouldn't be the same. You should not be able to remove the connection of the active device.

I played a little with the PHP library of PASETO:
```php
use ParagonIE\Paseto\Builder;
use ParagonIE\Paseto\Purpose;
use ParagonIE\Paseto\Keys\SymmetricKey;
use ParagonIE\Paseto\Protocol\Version2;

/**
 * Used to make base64 encoding url safe, and remove padding, used for jti
 * We don't care much about base64 here, we just want some random characters to be
 * easily stored in the database
 */
function base64_jtiencode($data) 
{ 
  return rtrim(strtr(base64_encode($data), '+/', '-_'), '='); 
} 

/**
 * Generated on friendica install
 * Allow regenerating this from admin UI - changing this will invalidate ALL tokens
 */
$sharedKey = new SymmetricKey(random_bytes(32));

/**
 * Generated every time a new refresh token is needed
 */
$refresh_jti = base64_jtiencode(openssl_random_pseudo_bytes(15));

$accessToken = Builder::getLocal($sharedKey, new Version2());

$accessToken = (new Builder())
    ->setKey($sharedKey)
    ->setVersion(new Version2())
    ->setPurpose(Purpose::local())
	->setIssuer('friendica.local')
	->setJti($refresh_jti) // The jti of the refresh token
    ->setIssuedAt()
    ->setNotBefore()
    ->setExpiration(
        (new DateTime())->add(new DateInterval('PT20M')) // 20 minutes?
    )
    ->setClaims([
        'uid' => '916',
        'role' => 'user'
	]);
	
$refreshToken = Builder::getLocal($sharedKey, new Version2());

$refreshToken = (new Builder())
    ->setKey($sharedKey)
    ->setVersion(new Version2())
    ->setPurpose(Purpose::local())
	->setIssuer('friendica.local')
	->setJti($refresh_jti)
	->setIssuedAt()
    ->setNotBefore((new DateTime())->add(new DateInterval('PT20M'))) // 20 minutes?)
    ->setExpiration(
        (new DateTime())->add(new DateInterval('P7D')) // 7 days?
	);


$return = [
	'atok'      => $accessToken->toString(),
	'rtok'      => $refreshToken->toString(),
	'user_id'   => 916
];
```

When the object is sent to the client:
- Maybe we should add a 'refresh_access_before' parameter too here so the client knows when to refresh the access token.
- Maybe we should add a 'replace_refresh_before' parameter too here so the client knows when the refresh token is about to expire.

The refresh token should be stored securely on the client. A cookie with HttpOnly and SSL is a good way of doing this from what I read, as LocalStorage might be prone to XSS attacks.
```
(
    [atok] => v2.local.w1XVIm7_k4rNqC5g5se4XBefG7VSdowQw8p9rmqpWsvUsGg16-iea8iwLXqrX3CkgDALIcyUzWjNzstF8jN2GzdETfDGKFpFAwJzos0UUVvWjNjLyli2omRZ8UGITdvBpIOjM4TBxAeSes_sc6i9aBghzY2ao8Q32Yhmc-8PI9AY-qlORD34BWi0PCj00xHYDpDL1eOZ9YbCWG3pSKE2dSRGvflOyxr_bNGdZG1TGXcBw7bxBnOc0krRyouwyzDc5g
    [rtok] => v2.local.8Q-Gm_qcSwjjZPgIaJKjkM_axTS1k98dvQEQMEuZQLlpXIGD6_nLfpHZPvq_mYQTrkfxTRATf4AkLXLEuUD9YRd5OU5MUzbIzyq6ByQhluIUE6UWd6_-uRMWP0iZyGIEovx0hY23YuBAyMu2nyhzZR4kibL-qjIu7Eqfp-0_UIRSOBG5Rzb4NPyjGu0enFQnWzTk3lSOzDaTAilQ854FGm7wrHUnnyPiFjq8K-xuh5zmySMaHw2B3lV-60ewKo8u0Mmcug
    [user_id] => 916
)
```
# Terms

- **Access token** is a token sent with every request, that contains an expiration date, a unique token ID and some other data. The user id is one of them. It has a short expiration time (30 minutes to an hour).
  - The server verify that token for every request and return a `403 unauthorized` if it found an issue (expired, corrupted, etc).
  - That token have the same value as a username and password. Clients (and geek users) should be careful.
- **Refresh token** is sent once, alongside the first access token, after the user logged in. It will be sent back to the server every time the client sees the access token is about to expire. The server should keep track of all refresh tokens and validate it before sending a new access token as the user can remove "devices".
- **ID Token** / Identification token is term used by OpenID that contain data about a user and is signed by the server to prevent tempering. It is safe to distribute to other instances as **it does not contain sensible information**.
- **Token ID** is a unique ID identifying each token (see `jti` property in the access token object)

## Interesting reads

- [Refresh tokens security enhancement](https://mailarchive.ietf.org/arch/msg/oauth/e5iV5x-r8U1iLQPX_zOvHtal2rY/)

- [Storing IPs in MySQL](http://databaseblog.myname.nl/2011/07/working-with-ips-in-mysql-and-mariadb.html)

- [Storing IPs in Postgres](https://www.postgresql.org/docs/12/datatype-net-types.html)

## FAQ

**Q: Why do we need to verify the refresh_token generation? Why not make a 30 days refresh token?**
**A:** With generations, the client will need to "refresh" the refresh token. Database verification will happen more often, tracking the IP address of the client requesting it. It provides better traceability for the user and increase security. It's easier to implement generations than create short-lived and long-lived refresh tokens too.

**Q: Why use a PASETO instead of a UUID for the refresh token?**
**A:** After decoding the token, if it's invalid or expired, we don't have to make any database calls at all. For bigger setups using scalable database, the latency and consistency can be a problem if the uuid/random string was revoked.

## TODO:

- [ ] Create the table in database
- [ ] get access token
- [ ] refresh access token
- [ ] revoke refresh token
- [ ] replace refresh token
- [ ] test, test, test, test
- [ ] Make current api endpoint support tokens
- [ ] make atok and rtok expiration window configurable? (I can make the frio config for that I think)
- [ ] Make admin able to configure the security of the tokens:
  - access token need to be short as they are not validated by the database. 15 minutes increament, top 60 minutes
  - refresh token are always validated with the database, but can be leaked, client can be hacked. Between 3 days and 14 days, 1 day increment. (If client doesn't log in before the token expire, they will need to log in again) Shorter period result in more database activity, and some latency on the client while the token is being refreshed.
  - refresh token generation (how many refresh token you can ask before having to enter password again) should also be considered. 4 generation of 7 days refresh token is a month.

If someone make the routes and basic files calling the required classes, I can implement this. But I do need some foundation.

### CODE REVIEW

**Comment by annando** [comment]
We are in the process of implementing the Mastodon API. It would be great if you could implement the OAuth in a way that is compatible to this. Means: in the future we want to make Mastodon apps work with Friendica.

**Comment by Extarys** [comment]
Yeah I heard but my PHP knowledge is limited. I'll do my best.

The mastodon oauth api doesnt use paseto though, but I guess it will work as the client doesnt really know/care about what the token is.

I'll play with the basic oauth local for now, and then we can expend to support clients, since they require an app token and all.

**Comment by MrPetovan** [comment]
We've talked privately about this so I will copy my remarks for everyone to see.

### Mastodon API compatibility

Ideally, we'd want to implement the same endpoints for OAuth. This means having routes for the following endpoints:
- `oauth/authorize`
- `oauth/token`
- `oauth/revoke`

It doesn't matter which token technology we end up using as long as we adhere to this Mastodon API spec.

### Naming conventions

We talked about shorter names being faster to look up in the databases, but it isn't our current optimization priority. Friendica isn't fast, so this kind of micro-optimization will be completely invisible to users. But it does make the code harder to read.

As a result, I'd prefer `access_token` to `atok`, `refresh_token` to `rtok`, `oauth_refresh_token` to `authrefreshtok`.

A couple more conventions we've been using:
- Class names should use `CamelCase` with a leading capital
- Route paths should be lowercase `snake_case` without any capital letters

### General remarks

- I believe recording the IP address is not a good security proof and may fall under the stricter privacy laws around. I'd like some advice on whether we can lawfully record IP addresses whether we use them for hard security checks or just traceability.
- Why the `local` in the API endpoint paths? What would be the `remote` counterpart?
- What does `jti` stand for? I wasn't able to find an acronym expansion on my own
- Why the `30 minutes` delay to post the refresh token? What if Mastodon API clients don't do it or sooner?

**Comment by annando** [comment]
Recording the IP is no good idea concerning data protection laws. This could even possibly be a violation of the GDPR in Europe.

**Comment by Extarys** [comment]
@annando Is it possible to detect the approximate region of the IP and then store an hash of it? The user can see a connection in another country without the "exact location". My goal was to make a log file compatible with fail2ban or other similar systems, maybe we could remove the last 3 digits (for ipv4 at least). Or an hash, which, yes we won't be able to block by IP but we could detect potential attacks and throttle those hash or block them from within friendica.

When implementing OAuth it's important to throttle and monitor - even if it's not with clear IPs.

EDIT: Thanks I forgot about EU regulations, but we do need a way to monitor attempts, both from a server admin perspective and a user perspective.

**Comment by Extarys** [comment]
@MrPetovan Yes, I'll focus on the local oauth as this is the most basic and easy to implement (as local mean it's issued by that instance for that instance) example: a theme for smarty3..
For mastodon it'll be a matter of adding that class to the mastodon endpoint and detect if the request (not local though) is coming from mastodon and adjust the reply and mechanics to comply with their api.

Side note: the `authorize` mastodon api will require us to define scopes and make a way for applications to register a secret token - eventually.

**Comment by MrPetovan** [comment]
My question about local/remote is whether the API endpoints would be different and if yes why?

As for privacy concern, storing a region isn't good either. Although having an IP address hash sounds better, the small scope of IP addresses strings means that it would be easy to reverse the hash.

**Comment by Extarys** [comment]
@MrPetovan We can easily add a salt to avoid rainbow attacks - of course the server administrator could be able to reverse that but they're main concern won't be to know the ip - if they want the ip they can just check their nginx access log.

My concern is to offer some kind of protection against POST flood/ddos attack where a person send 1000 requests to the get_access_token endpoint with very long username and password. It's trivial to do this kind of attack and we do need to implement some kind of mitigation for this basic scenario. My point is,  a [script kiddie](https://en.wikipedia.org/wiki/Script_kiddie) can do it.

We also need a way to detect if a person always logs in Germany but then one morning there is a session opened in Canada. We need a way to ask the user if that session is them. could be a simple "Last connection from Russia at 11:34".

Screenshot from 2021-01-27 12-31-11

Concerning local/remote, a local connection is believed to be from the same service. A remote/third-party connection require more security. [See here](https://medium.com/identity-beyond-borders/what-the-heck-is-pkce-40662e801a76)

[Another interesting read](https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/)

Hence why I'm implementing local first too - it's way easier. Well, technically we should implement PKCE too for that, but since the token will be sent inside php for the themes to use, I don't see why we need to rush that implementation either.

While writing this I found this amazing article [Common OAuth2 Vulnerabilities and Mitigation Techniques](https://leastprivilege.com/2013/03/15/common-oauth2-vulnerabilities-and-mitigation-techniques/) from 2013, but the concepts still applies.

**Comment by annando** [comment]
What are the differences between this OAuth and the one that Mastodon apps use? And what can we use our OAuth later on?

**Comment by MrPetovan** [comment]
> Concerning local/remote, a local connection is believed to be from the same service. A remote/third-party connection require more security. [See here](https://medium.com/identity-beyond-borders/what-the-heck-is-pkce-40662e801a76)

Why not treating Friendica as yet another app for API purposes and have only one auth flow? What would prevent "remote" apps from using the less-secure "local" auth?

**Comment by Extarys** [comment]
I'll let you both work on this then, I don't have the energy.

**Comment by MrPetovan** [comment]
It's okay, thank you for starting the process!

**Comment by Extarys** [comment]
Closing, looks like #10380 took care of a login process through the api.

**Comment by annando** [comment]
@Extarys my approach to OAuth in that PR had been a "robust" one. It seems as if you have got a deeper understandment of this topic. So it would be great if you could have a look at my current implementation.

**Pull request closed without merging**
