### PR TITLE
Set the picture accesibility separate from the permissions

### PR DESCRIPTION
**Pull request by annando**
This possibly fixes https://github.com/friendica/friendica/issues/8371#issuecomment-597258823 - when the accessibility is selected.

### CODE REVIEW

**Comment by MrPetovan** [comment]
What does this have to do with NULL permissions? Is it actually a problem to have these values?

**Comment by annando** [comment]
It is a partly a test to separate the update calls - and a workaround for situations with pictures that are reloaded with different permissions. I tried to upload pictures in different ways to get this `null` stuff - but failed doing so.

**Comment by AlfredSK** [comment]
Create a public post.
Start writing a comment on that post.
Click on the insert image button in the comment editor.
Your photos are displayed.
Click on Upload button.
Select a photo from your device.
The photo is uploading...
Select it from your photos to insert it in your comment.

-> image has NULL permissions.

**Comment by annando** [comment]
@AlfredSK When I work this way, then everything is looking fine as well.

**Comment by AlfredSK** [comment]
You can see that Image in the comment when not authenticated?
And permissions in 'photo' are not NULL?

**Comment by annando** [comment]
The permissions are totally correct, yes.

**Comment by AlfredSK** [comment]
Hmm. Is there a setting that has an impact on setting the permissions in 'photo'?

**Comment by annando** [comment]
Which theme are you using?

**Comment by AlfredSK** [comment]
frio

**Comment by annando** [comment]
I just had a look at my database. Out of a total of more than 1,14 million entries in the photo table there are 14 entries with `null` permissions. They belong to 6 comments from 2 users. And they all had been between February and March this year.

I added some additional check when saving photos.

**Comment by AlfredSK** [comment]
Interesting. I'll check that too when I'm home again.

**Comment by annando** [comment]
@AlfredSK BTW: Could you then comment on this in the corresponding issue and not in this PR?

**Pull request merged**
