### PR TITLE
Fix infinite content ajax call parameters

### LINKED ISSUE #9432: /network endless scrolling problem
- [X] I have searched open and closed issues for duplicates

### Bug Description
The endless scrolling will load endlessly. 

### Steps to Reproduce

1. Got to /network, switch to "Latest posts" in the top. 
2. Go to /network by the link in the top menu of Frio. 
3. Scroll down all the way to the bottom, " Loading more entries... " will be shown forever. 
4. Scroll up, switch from "Latest posts" to "Latest activity" (does not matter, other work too).
5. Scroll down to the bottom, new posts should load. 
6. Switch to "Latest posts" again, scroll down, new posts should load. 
7. Click on the /network link again in the top of the Frio theme. 
8. Scroll down to the bottom, load will take forever.

**It seems it is also working, when you're in /network and then change the selection to the same selection again, ie. you're in "Latest posts" and click on "Latest posts" again. This will change the URL from "/network" to "/network?order=received".** 

Actual Result:
Loading takes forever. 

Expected Result:
Loads new posts in less than 1 sec. 

### Screenshots
Not needed. 

### Platform Info

Friendica Version:
Latest development, "git pull" said "Already up to date."

Friendica Source: git

PHP version: PHP 7.4.11

SQL version: mariadb  Ver 15.1 Distrib 10.5.6-MariaDB

### PR DESCRIPTION
**Pull request by MrPetovan**
- Ajax request could end up in a 404 if the page URL didn't have at least a query string parameter

Probably fixes #9432

### CODE REVIEW

**Comment by utzer** [comment]
It is not merged yet, is it?

**Comment by MrPetovan** [comment]
No it isn't, but you can replace your `main.js` file with [the patched version](https://github.com/friendica/friendica/blob/481925c353e52c039a2305d50974cfe960514d4a/view/js/main.js) and test the fix on your node.

**Comment by utzer** [comment]
> No it isn't, but you can replace your `main.js` file with [the patched version](https://github.com/friendica/friendica/blob/481925c353e52c039a2305d50974cfe960514d4a/view/js/main.js) and test the fix on your node.

Edit:

New main.js work, had a caching problem on the server. Infinite scrolling works.

**Comment by MrPetovan** [comment]
Awesome, glad to hear it.

**Comment by annando** [comment]
Will this solution work with additional parameters as well?

**Comment by MrPetovan** [comment]
It does, I was able to verify with a base query string as `/network?order=active`. jQuery correctly appends the extra parameters to the Ajax call.

**Pull request merged**
