### PR TITLE
Replace "dbclean" with new expiry functionality

### PR DESCRIPTION
**Pull request by annando**
The existing "DBClean" functionality was unreliable, slow and caused database problems.

The new functionality now relies upon the (now existing) foreign keys. It is much faster, although the first call will most likely block the database for some minutes. But the following calls shouldn't cause any interferences.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by AlfredSK** [comment]
It's much worse now. I activated the DBClean setting. Within 10 minutes the node was killed and is still dead. Service temporarily not available.

This query ``DELETE FROM `item-uri` WHERE `id` IN (SELECT `uri-id` FROM `thread` INNER JOIN `contact` ON `id` = `contact-id` AND NOT `notify_new_posts` WHERE `received` < UTC_TIMESTAMP() - INTERVAL '180' DAY AND NOT `mention` AN.......`` runs for several minutes. At the moment more than 18 minutes. ALL other queries trying to update the item or contact table have to wait for that ONE very long running query. The DB is hitting the max DB processes. And tons of PHP-FPM processes are piling up until no more processes are possible. Node quits service. All dead.

**Comment by AlfredSK** [comment]
I had to delete all DBClean related tasks from the workerqueue and kill (restart) MariaDB to make the node available again.

**Comment by annando** [comment]
@AlfredSK according to my tests this should only occur once, because afterwards the data amount should be so low that it should work flawlessly.

**Comment by AlfredSK** [comment]
@annando I am thinking about putting the node in maintenance mode and run that query by hand. Do you think that will work?

**Comment by annando** [comment]
After the process started, you should be able setting the system in maintenance. This is a single SQL call, so there shouldn't be any problems with that.

I had a look at my system. I hadn't got severe problems by now. But I haven't tested with squeet.me by now.

**Comment by AlfredSK** [comment]
I take that for a 'yes'. :-)

The plan is to first enable maintenance mode and then run the query from mysql command line...

``
DELETE FROM `item-uri` WHERE `id` IN (SELECT `uri-id` FROM `thread` INNER JOIN `contact` ON `id` = `contact-id` AND NOT `notify_new_posts` WHERE `received` < UTC_TIMESTAMP() - INTERVAL '180' DAY AND NOT `mention` AND NOT `starred` AND NOT `wall` AND NOT `origin` AND `thread`.`uid` != 0 AND NOT `iid` IN (SELECT `parent` FROM `item` WHERE (`item`.`starred` OR (`item`.`resource-id` != '') OR (`item`.`event-id` != '') OR (`item`.`attach` != '') OR `item`.`wall` OR `item`.`origin` OR `uri-id` IN (SELECT `uri-id` FROM `post-category` WHERE `uri-id` = `item`.`uri-id`)) AND `item`.`parent` = `thread`.`iid`));
``

**Comment by AlfredSK** [comment]
The first run took 2:20 hours. The second run took 15 minutes.

**Comment by AlfredSK** [comment]
25 GB were deleted from the database.

**Comment by MrPetovan** [comment]
Oof.

**Comment by annando** [comment]
2:20 is intense, but 15 minutes really long as well. Question is if the system was blocked in that 15 minutes as well.

**Comment by AlfredSK** [comment]
> Question is if the system was blocked in that 15 minutes as well.

Cannot tell that. Maintenance mode prevented any possible issues.

**Comment by MrPetovan** [comment]
This same query is awful for my node, it makes my node unresponsive for several minutes at a time, multiple times a day. I don't mind the "Node overloaded" nor "Node in maintenance" pages, but this is different, no page actually loads since all the processes are waiting for this specific query to complete. And since the node isn't disabled, SQL queries pile up, shooting my server load in the stratosphere once that single query clears.

I'd like to disable the dbclean settings, but the admin page won't load either, ha ha.

**Comment by annando** [comment]
@MrPetovan especially since your node is a single user node, you could define a time frame, in which the calls are done where you aren't active on the system.

**Comment by MrPetovan** [comment]
The problem is that is seems to freeze my whole database, which makes other websites on the same server become unresponsive as well. It isn't sustainable because I receive email alerts when any of these websites are unresponsive.

**Comment by annando** [comment]
That's so weird, since I don't have any problems at all on my both machines. I will have to check the exact lock behaviour, so that I can improve it.

**Comment by MrPetovan** [comment]
I don't think the lock is a problem, it wouldn't lock the entire database, the query is just too intensive it seems.

**Comment by annando** [comment]
"too intensive" sounds like your database server has got issues.

**Comment by MrPetovan** [comment]
It is at capacity, and this query is apparently pushing it over. I was able to use Friendica along other websites on my server before this query was introduced, and I don't expect it to change drastically with the addition of a single SQL query.

**Pull request merged**
