### PR TITLE
Move the 'authenticate' hook deeper into the authentication flow so t…

### PR DESCRIPTION
**Pull request by very-ape**
…hat password authentication addons are consulted whenever a user's password needs confirming.

I prioritized minimizing edits. Please let me know if you'd rather I find another way to do this.

Also, I'm passing the user's nickname field to the authentication addons, but I'm a bit fuzzy on the difference here between the username field and the nickname field. Should I be using the username field instead?

### CODE REVIEW

**Comment by MrPetovan** [comment]
We have a description of the database fields per table in the `/doc/database` folder, see for the `user` table: https://github.com/friendica/friendica/blob/develop/doc/database/db_user.md

- `username`: The display name.
- `nickname`: The, huh, user name in the Webfinger format `user@domain`.

I know it is confusing.

**Review by MrPetovan — APPROVED** [review]
This looks good to me, have you tested locally, with and without addons enabled?

**Comment by very-ape** [comment]
Yes, I've tried it with my Keycloak password addon disabled to confirm the password field on the two factor page does fail to authenticate, and I've tried it with that addon enabled to confirm the password field *does* authenticate in that case.

**Comment by MrPetovan** [comment]
What about the regular password login, was it altered by your changes?

**Comment by very-ape** [comment]
I have confirmed that regular password login works as before.

**Pull request merged**
