### PR TITLE
Add "on their post" label to notifications

### PR DESCRIPTION
**Pull request by MrPetovan**
This PR adds another variation to notifications messages if the actor interacts on a thread they started themselves.

Additionally, it adds the same variations to mention notifications.

See some examples:
friendica-notifications-improvements

Addon pendant: https://github.com/friendica/friendica-addons/pull/789

### CODE REVIEW

**Comment by MrPetovan** [comment]
This is so good, I can't wait for the release so that it will reliably by on the develop branch. Right now it just is a stray modified file on my RC-branch server.

**Comment by annando** [comment]
Is "their" the gender neutral version of "his/hers"?

**Comment by tobiasd** [comment]
I think so, and the translation will be a cruelty. I don't see a good way for German at the moment.

**Comment by annando** [comment]
"... kommentierte den eigenen Beitrag"?

**Comment by JeroenED** [comment]
In Dutch the rule is that if you don't know the gender, always take the male form. In the sight of gender equality it's still a long road

**Comment by JeroenED** [comment]
Or you make yourself uncomfortable and use brackets  and slashes to have both forms.

**Comment by MrPetovan** [comment]
In French the possessive pronoun agrees with the following noun, so no significant problem there. Sorry about that.

**Pull request merged**
