### PR TITLE
Frio: login button opens a modal

### PR DESCRIPTION
**Pull request by fabrixxm**

### CODE REVIEW

**Comment by rabuzarus** [comment]
Cool I wanted to something like this, just haven't the time for it.

There is one thing I want to highlight.
Can you make some experiments with `<a onclick="addToMotdal('login')">` (js code is frio/js/modal.php)
If we would get implemented in this way it would be cleaner because we don't need to have that much modal code in the templates. It would be better to use the generic modal template which is provided through frio/modes/default.php.

At the present state there is one issue with this solution. It is problematic that `?mode=none` (frio/php/modes/none.php) is frio specific. But the login page is provided through the system theme. If it's not frio there would be no `?mode=none` (because of the missing page template none.php).

It would be really good to have frio's `none.php` as a page template in core (next the possibility to give themes the possibility to have their own specific page templates if they want to)

This would really the better solution than to have much specific modal code in the templates.

@fabrixxm @annando 
Do you maybe want to have a look how we could implement `none.php` in friendica core?

**Comment by fabrixxm** [comment]
`none.php` in core could be very usefull.
as a side note, hook `'page_end'` should not be called for `mode=none` (think about buglink addon)

I didn't see `frio/js/modal.php`, I'll take a look and I'll update this PR

**Comment by rabuzarus** [comment]
> as a side note, hook 'page_end' should not be called for mode=none (think about buglink addon)

Do you mean the the actual placement of the modal template in the `<footer>` of the page template default.php?

**Comment by fabrixxm** [comment]
> Do you mean the the actual placement of the modal template in the <footer> of the page template default.php?

No, i'm talinkg about the "buglink" addon that uses the "page_end" hook to inject html into the page, in this case the small image of a ladybug with a link to friendica issues page.
The hook is called always before a page is sent to the browser, so when a page with mode=none is loaded into the modal, the ladybug is show also inside the modal...

**Pull request merged**
