### PR TITLE
Frio: Bugfix for linebreaks in location

### PR DESCRIPTION
**Pull request by annando**
I had to remove the brackets to fix the bug is described here: https://github.com/friendica/friendica/issues/2537

### CODE REVIEW

**Comment by rabuzarus** [comment]
Ok you you have removed the brackets. But why do you have removed the dash?

**Comment by annando** [comment]
See the screenshot in the linked issue. The location can be really long so that linebreaks happen. And then the dash really looks bad.

**Comment by rabuzarus** [comment]
But when it is in one line there will be no seperator. Wouldn't it be a solution to have it in one line and having for location a ellipsis effect (http://www.w3schools.com/cssref/css3_pr_text-overflow.asp) ?

**Comment by annando** [comment]
I would like to always have it in a separate line. I think this is more consistent in comparison to the location output in the other occasions.

**Comment by rabuzarus** [comment]
hmm the idea was to have comments as compact as possible thats why it is for top level posts in a seperate line and for comments in the same line. Comments in my view shouldn't have the same visual importance like a top level post.

**Comment by annando** [comment]
Yeah, I understand. But then - depending on the length of the location - the location would be sometimes in the same and sometimes in a separate line. This isn't consistent.

**Comment by rabuzarus** [comment]
No it should be in the same line if it's a comment (if it's to long it will be cutoff with dottes - ellipsis) and for top-level posts it would be in seperate lines

**Comment by rabuzarus** [comment]
@annando can you provide me some data so that I experiment with it. I tried it with the mobile, but the line break is ok in my case (not like in your picture).
Can you give me the html of the case of the picture? Or something so that I have such a comment

**Comment by rabuzarus** [comment]
@annando 
can you please triy the orignal version and change https://github.com/friendica/friendica/blob/develop/view/theme/frio/css/style.css#L1209
into
```
.media .media-body .addional-info a, .media .media-body h5.media-heading > a {
    display: block;
}
```

**Comment by annando** [comment]
You can try it with this thread: https://pirati.ca/display/a3b4cfebda6e469c62de188831839df5ba831c7f

**Comment by annando** [comment]
Okay, changed.

**Pull request merged**
