### PR TITLE
Update default log location

### LINKED ISSUE #2209: /friendica url is a 404
There's an 'Information' link in the menu accessible at the top-right corner of Vier theme.
The second entry ("Information") points to /friendica, which is a 404 here.
The other two entries ("Help" and "Guide") work fine.
This is as of version 3.4.3.

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #2209

### CODE REVIEW

**Comment by AlfredSK** [comment]
Will that path throw a git error? The log/ path isn't in `.gitignore`. I don't know if `*.log` will also cover a logfile at log/friendica.log.

**Comment by MrPetovan** [comment]
Good question. I don't think it will though, because it will just be an untracked folder/file.

**Comment by nupplaphil** [comment]
What about adding the `log/` directory to the codebase with the right chmod. So we can trust the default setting per se

**Comment by MrPetovan** [comment]
Done.

**Comment by annando** [comment]
I would suggest putting it in https://github.com/friendica/friendica/blob/develop/.gitignore

Not everyone does want the logs in the web root (in fact I consider this a possibly security issue when the web server isn't configured to not serve log files).

**Comment by MrPetovan** [comment]
Sensible.

**Pull request merged**
