### PR TITLE
lang info in HTML header

### PR DESCRIPTION
**Pull request by tobiasd**
added ''''lang'''' information to ''''html'''' element ([see AX_HTML_01](https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_html_01)).

something along the way for #1743

### CODE REVIEW

**Comment by rabuzarus** [comment]
One stupid Question comes to my mind.
Isn't the used language in friendica not the one of the browser?

**Comment by fabrixxm** [comment]
not anymore, see https://github.com/friendica/friendica/pull/2044

**Comment by annando** [comment]
Just a question: Is there a reason why we haven't accepted this pull request by now?

**Comment by fabrixxm** [comment]
well.. no..

**Pull request merged**
