### PR TITLE
Update vagrant_provision.sh

### PR DESCRIPTION
**Pull request by casperrutten**
Line 20-27 -> add slash at the end of every entry and removed empty entries.
Caused error in creating .csr file (with openssl version 1.1.1)
PS. the virtualbox-guest-x11 is not in the given debian repository. Better take an Ubuntu repository
Also inserted:
sudo apt-get install -y ubuntu-desktop
sudo systemctl set-default graphical.target
to install a desktop environment

### CODE REVIEW

**Comment by MrPetovan** [comment]
Thank you for your submission, I'll let @tobiasd review it as I'm not using Vagrant.

**Comment by tobiasd** [comment]
The problem I had using the Ubuntu images we used before was, that the networking between guest and host system did not work anymore which made the Vagrant VM unusable for developing at all.

**Comment by casperrutten** [comment]
@tobiasd I use the /generic/ubuntu1804 box on my ubuntu 19.10 laptop without any problem.

**Comment by tobiasd** [comment]
Could well be that I had chosen the wrong image for 18.04 when I updated the Vagrant config. I had no networking at all and found no solution other then switching to the Debian image as that still had networking working.

The box you suggest seems to be working on the 1st glance, so feel free to make a pull request for it. :-)

**Pull request merged**
