### PR TITLE
[frio] Changes to shared post display (width, base font size)

### PR DESCRIPTION
**Pull request by Hypolite**
Lately, I've been frustrated with a couple of width-related points on the frio theme:
- There is a large blank space on the right of the screen
- Shared items have large left and right margins which compresses the shared content

This PR aims at solving both those issues. The changes aren't groundbreaking, but they saves a few scrolls when going through the stream.

Before:
screen shot 2016-09-28 at 11 17 48 am

After:
screen shot 2016-09-28 at 11 18 56 am

A couple of notes regarding the increased width of the center column:
- The bootstrap grid has 12 divisions, however so far on desktop frio only used 10 of them (3 left + 10 center), and the right space wasn't preserved for the right aside, which is displayed on the left column under the left aside. I just reclaimed the missing 2 divisions.
- Even when resizing the browser to extreme width, the content doesn't become unreadable with the change because the parent container has a fixed width.

### CODE REVIEW

**Comment by rabuzarus** [comment]
@Hypolite as author of frio I would not accept this PR. I have chosen the width of the network stream for a particular reason. Readability. Because of being unsatisfied with to much width wich makes it hard for me to read longer posts (because I always slip on the line) was one of the many reason to start a new theme. The width of the stream based on the width what twitter uses as stream width. I'm very interest to leave the stream and aside width how they are. I experimented a lot to have a good balance between the elements (stream, aside, font size) to have a good readability (under the premise not to change too much in the bootstrap framework)

Some notes for other PR's :
To avoid much work wich wouldn't accepted I would suggest to discuss fundamental changes in the friendica developer forum. So we avoid wasting develop time (which can be very frustrating).

Another motivation for Frio is to have a beautiful theme with a good UX. Many parts are missing in the Frio theme. On the one hand it is because of the lack of time but on the other hand it is also because I have no good I idea how to implement it in a real good looking way with a good UX (e.g. the single photo view - ). The philosophy behind Frio is to implement something because it fits the whole Frio/UX concept.
This is something I recognized as a mistake at some other friendica themes. We add something because we have it in the core but we have no real idea about the UX as a whole. But we implement it nonetheless. Someone could fix it later.
I would avoid this for Frio

**Comment by Hypolite** [comment]
@rabuzarus, I followed your advice on the center column and reverted the proposed change. I fiddled some more with the shared content margins/paddings, let me know what you think about it.

**Comment by rabuzarus** [comment]
@Hypolite 
I wrote some general explanation on the other closed PR. (Lets use this PR if we need possible further communication)

>I fiddled some more with the shared content margins/paddings, let me know what you think about it.

Can you send me a screenshot? Because at the moment I have no possibility to test it.

**Comment by Hypolite** [comment]
Shared content margins, before:

screen shot 2016-09-28 at 1 47 30 pm

After:

screen shot 2016-09-28 at 1 47 13 pm

(Don't mind the color change, it's stream post vs single page post)

**Comment by rabuzarus** [comment]
I would accept it with a note to everyone who is interested in this topic that we need a better solution in the future for presenting shared posts, shared links and events (for shared posts as a whole or at least for presenting the contact header of the person we share from)

**Comment by Hypolite** [comment]
> We need some good (-looking) solution how to we present this. Of how we make it distinguishable that the one is the post and the other the the shared content. Something which is a pleasure for the eyes without being annoying. I'm very open for new ideas and new concepts.
I'm no fundamentalist if you want lower the margins. But this shouldn't be the end of ideas which we have for presenting shared post in Frio.

I'm sorry I can't help you more with coming up with good ideas. I'm no frontend developer, and while I can spot UX pain points on an existing design and fiddle with CSS, I cannot for the life of me come up with clever design ideas.

What I can say is that, despite not covering all the screens and features yet, the frio theme is by far the most accessible one from the list of supported themes. Please do not take those proposed changes as a negative feedback, on the contrary. I'm so happy with the theme that I'm readily spending time to make it even better.

**Comment by Hypolite** [comment]
I added another small change that fixes the font size for text-based shared posts. The base `<blockquote>` style assumes an increase in size (which is debatable, but it's the bootstrap base, and I don't want to touch it), and the shared content are embedded in a `<blockquote>` tag. This change keeps the original font size while not affecting the eventual quotes inside the shared post.

**Comment by rabuzarus** [comment]
> Please do not take those proposed changes as a negative feedback, on the contrary.

I don't do this ;-) I'm also no good frontend developer. But we don't have anyone else who would like do the job so I have to do it :-D  Often I  try to look on many other projects (not only social projects) to get inspiration of what we can do/solve our GUI problems and try to find a way which fits our needs.
And sometime it's also hard for me to express it in a good manner (in english)  my thoughts why I have chosen this way and not another.
And the general problem will always exist. Friendica does have many features and can be used in many ways. You won't be able to get a GUI which does make everyone happy. You have to make decisions because you want to reach a certain group of users

**Comment by rabuzarus** [comment]
> I added another small change that fixes the font size for text-based shared posts

Yes blockquotes are too big (also in the network stream).

Do you want some more time to polish, polish, polish (what I would support) or should I merge it?

**Comment by Hypolite** [comment]
> Yes blockquotes are too big (also in the network stream).

Alright, this is a done deal.

> Do you want some more time to polish, polish, polish (what I would support) or should I merge it?

The latter doesn't prevent the former, I'd say merge it, so that it's readily available in the next minor release. I'm sticking around anyway, we'll have time to think more about stuff.

> Friendica does have many features and can be used in many ways.

Would it help if we had feature-specific classes so that we can finetune depending on the displayed content?

**Pull request merged**
