### PR TITLE
Update compose files

### PR DESCRIPTION
**Pull request by nupplaphil**
- Update composer.phar to 1.8.5
- Update latest PHP5.6 compatible composer libraries

I tried it on my node (but with 7.1 running) which doesn't harm anything, the dependencies were updated without errors.

### CODE REVIEW

**Comment by MrPetovan** [comment]
I know this isn't the most fun part of this, but please check for each dependency the diff between the version we used and the selected new version. Using Composer doesn't mean we can absolutely trust upstream libraries.

Additionally, the alternative choice is in your own hands. Adding Dice to Friendica is a big deal and can justify bumping the minimum version Friendica can run on, and if you decide to go forward with it we don't really have a choice.

On the other hand, if you don't add Dice, then we don't need to bump the minimum version at all.

**Comment by nupplaphil** [comment]
Is there a common way how to check the diff? Do you mean code-line by code-line each vendor package? Or the usage inside the Friendica codebase?

**Comment by MrPetovan** [comment]
I did it on GitHub on each project with the browser compare tool. You can compare two named tags.

For example, to compare v2.5.3 and v.2.8.0 of `DivineOmega/password_exposed`, you would use this URL:

https://github.com/DivineOmega/password_exposed/compare/v2.5.3...v2.8.0

The tricky parts are:
- finding the correct repository for each updated dependency
- correctly spelling the tags

**Comment by MrPetovan** [comment]
Made obsolete by #7138

**Comment by nupplaphil** [comment]
Ah, OK .. Thank you!

**Pull request closed without merging**
