### PR TITLE
Re-enable DRONE

### PR DESCRIPTION
**Pull request by nupplaphil**
FollowUp #8267 #7643

Just have a look what's working and what's not working :)
pinging @utzer to keep an eye on https://drone.friendi.ca

- Starting with the easy "transifex" workflow

### CODE REVIEW

**Comment by nupplaphil** [comment]
https://drone.friendi.ca/nupplaphil/friendica/147 <-- enabled on my "develop" branch again, just have a look what's happening ;-)

**Comment by nupplaphil** [comment]
I'd say let's try it :-)
=> I don't really know if the "transifex" check from the drone config is now "automatically" replaces the github check for transifex
=> but at least we do need the `.drone.yml` file back at the root directory of the `develop` branch to re-enable drone for the checks :-)

So I think we just take a look and revert it in case it doesn't fit

The last commit is tested here: https://drone.friendi.ca/nupplaphil/friendica/161

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
> https://drone.friendi.ca/nupplaphil/friendica/147 <-- enabled on my "develop" branch again, just have a look what's happening ;-)

6 hours later it still is running?

**Comment by nupplaphil** [comment]
Yes the first run without adapting the drone file, I'll cancel it.

I'm now starting with smaller steps. "Just" including the transifex check. Afterwards the lint check and so on

**Comment by utzer** [comment]
@nupplaphil just wanted to say I read your messages, if you need me to do something I should have more time in a few days, next week I think. But anyway ping me there is any help needed.

**Pull request merged**
