### PR TITLE
Adding Connection retries to 'dba::connected()'

### PR DESCRIPTION
**Pull request by nupplaphil**
Sometimes the DB-check is faster than the DB initialization in Friendica and the automatic installation failed.

Therefore I added a "retry" loop with a constant variable how often we retry.

### CODE REVIEW

**Comment by MrPetovan** [comment]
How can the DB checker be faster than the DB connection? Isn’t it a better practice to try to open the connection instead in `connected()`?

**Comment by nupplaphil** [comment]
I found it when I'm starting the db parallel to Friendica (Docker environments ;-) ).

The database initialized itself (setting up parameters, creating a database, making some db-optimizing stuff) and meanwhile Friendica executes "console autoinstall" at startup and failed with "cannot connect to mysql database".

I first thought about creating a delay in the shell scripts at startup, but isn't that a workaround? I thought it would be better to have such feature native in Friendica that it "retries" if it lost connection or never had it.

**Comment by nupplaphil** [comment]
@annando for me a "delay" feels more like a workaround than a solution. But it would work too I think.

**Comment by nupplaphil** [comment]
Should the retry and sleep value be configurable? like `$a->config['system']['conn_retry']` and $a->config['system']['conn_retry_sleep']` ? If so, where is the best place to define the "standard" values for them? I know you don't want to have any additional constants in `boot.php` so I'm searching for a better place :-)

**Comment by annando** [comment]
I have the feeling that it would be better to have some script in the docker startup that checks for the database being ready - before friendica is executed.

I don't think that this scenario can occur outside of docker.

**Comment by nupplaphil** [comment]
Hm .. ok :-) Thought it's more like a hardening for Friendica setups (loosing/delayed db-connection)
I will add it at the startup script ;-)

**Pull request closed without merging**
