### PR TITLE
Move div#pause to view/default.php

### LINKED ISSUE #2320: Move div#pause to default.php
I noticed [the following line](https://github.com/friendica/friendica/blob/master/index.php#L416) inside of **/index.php**:

`$a->page['content'] .=  '<div id="pause"></div>';`

Is there a reason this div can't be put into **/view/default.php**?

I stumbled upon this when thinking about a theme adding Ajax content that would always have this _pause div_, a rather undesired effect. What is it for, anyway?

### PR DESCRIPTION
**Pull request by stieben**
This closes #2320.

There's an additional commit included (_merge upstream/develop_). Is there a way to avoid this? How do you sync with upstream branches?

### CODE REVIEW

**Comment by tobiasd** [comment]
can you check the default.php files of the supported themes (those not having a file called "unsupported" in their directory) to include the changes as well. I think these are the frost, frost-mobile and smoothy themes.

**Comment by rabuzarus** [comment]
You have to insert this code also in the default.php of the supported themes which have their own default.php. This would be frost, frost-mobile and smoothly

**Comment by rabuzarus** [comment]
@tobiasd :-D at the same time

**Comment by tobiasd** [comment]
:-D

**Pull request merged**
