### PR TITLE
update javascript cropper library

### PR DESCRIPTION
**Pull request by rabuzarus**
Switch cropper library to https://github.com/fengyuanchen/cropperjs

Fixes https://github.com/friendica/friendica/issues/4572

Note:
`php bin/composer.phar install` is needed

### CODE REVIEW

**Comment by MrPetovan** [comment]
I'm noticing many other dependencies' version has been changed in the `composer.lock`, but we haven't checked for regressions for each one.

If you don't want to check every single dependency version changelog ech time you add a new dependency, you can use the following command to update only a single dependency: `composer update npm-asset/cropperjs`. This will prevent Composer from checking new versions for all the dependencies.

If you want to go with this now, you have to do this in order:
1. Revert `composer.lock` to `develop` version
2. Run `composer install`
3. Run `composer update npm-asset/cropperjs`
4. Commit new `composer.lock`

**Comment by MrPetovan** [comment]
Part of #4265 ! \o/

**Comment by rabuzarus** [comment]
`php bin/composer.phar update npm-asset/cropperjs` says:
```
[Composer\Downloader\TransportException]                                                                                            
  The "https://api.github.com/repos/pear/Text_Highlighter" file could not be downloaded: failed to open stream: Connection timed out
```

**Comment by MrPetovan** [comment]
Ok, I’ll look into it tonight.

**Comment by rabuzarus** [comment]
OK the dependencies should be fixed in composer.lock

**Pull request merged**
