### PR TITLE
Like posts from Twidere

### PR DESCRIPTION
**Pull request by zeroadam**
like and unlike from twidere client
Relates to #5708

### CODE REVIEW

**Comment by annando** [comment]
We should either mark them or like them - but not both.

**Comment by zeroadam** [comment]
I thought perhaps marking starred served some other purpose/client, so I didn't modify that behavior

**Comment by tobiasd** [comment]
Starring something is your private action for whatever you want to use it. For me it is mostly a "read this later" action but can also act as a reminder from the mobile client to sort that posting into an appropriate folder later. Liking and unliking are public actions.

My guess is most Twidere users would expect a "like" to happen and not a "starred". But the API should provide both actions.

**Comment by annando** [comment]
We could add some additional parameter that would control the behaviour. This could be used by our own application. And when this parameter isn't provided, we could decide upon a user config what to do.

**Comment by tobiasd** [comment]
friendly offers starring and un-/liking already so I think it is already supported @fabrixxm should know.

Question is more what non-native app user expect to happen when they use the action button in their client software.

**Comment by zeroadam** [comment]
So, what would you all like me to do here? I would love to get this in, as I was the one who "complained" about liking from Twidere not actually liking on the nodes.

In any case, I have starring disabled on my node, so never saw this behavior when liking from twidere.

**Comment by annando** [comment]
Problem is: When Twitter added this possibility, it had been used to bookmark a post - and had later been changed to "like" a post.

**Comment by MrPetovan** [comment]
Then we should follow the change since third-party apps have changed their display as well. It only is a problem because we are piggy-backing off the Twitter app signatures and we lagged behind the changes.

**Comment by AlfredSK** [comment]
I have always intuitively considered this function in Twidere to be a "like".

**Comment by zeroadam** [comment]
OK, so it sounds like the consensus is to remove the "starring" from this method and just do performLike. @annando, your thoughts?

**Comment by annando** [comment]
Sadly this is not that easy. Have a look at the code. We have our own API call for that: api/friendica/activity/like. And I guess that our Friendica apps will use the "favorites" API calls as bookmark calls.

And to make it even more complicated: We have several places in the core where we looked for the "starred" value as well. All these places would need to be changed as well.

**Comment by zeroadam** [comment]
I discovered some more about this last night. If you don't also "star" the item, Twidere does not recognize it as something you liked in the future, i.e. after you refresh or open the app next time. There is also a Likes menu item in the side bar that will give you a list of everything you've liked. If we do not "star" as the original code does, anything you like will not show up in that listing.

At the core, all I wanted when requesting a change here, was for my likes from the Twidere app to show up as if I had clicked like on the web interface (basically Item::performLike).

As far as the existing API endpoint for liking, this is not something that Twidere is using, so it does not produce the desired effect.

**Comment by zeroadam** [comment]
@annando you had mentioned not doing both (starring and liking), but I'm not sure how to achieve the desired effect without doing both.

**Comment by MrPetovan** [comment]
This is because all the other like-related API endpoints still query the starred items and have to be switched to Likes as well. And we should have Friendica-specific endpoints for starred items for Friendiqa.

**Pull request closed without merging**
