### PR TITLE
Update copyright

### PR DESCRIPTION
**Pull request by urbalazs**

### CODE REVIEW

**Review by MrPetovan — CHANGES_REQUESTED** [review]
Thank for your work, please keep the copyright as a single year as this project didn't start in 2020.

**Comment by urbalazs** [comment]
As I see, the project started in July 2010. You are right, not all files were created in this this time. Additionally, there are some files with copyright date 2010-2015 or 2010-2020, but most of the files have only 2020.

There are many other project which uses the whole range for copyright dates for all files, even for new ones. So, what do prefer?

1. Copyright (C) 2021, Friendica
2. Copyright (C) 2010-2021, Friendica

I think, the second one would fit better, but this is only my opinion.

And we have now the possibility to change the copyright holder name, because it is also not the same for all files:

1. Copyright (C) 2021, the Friendica project
2. Copyright (C) 2010-2021, the Friendica project

Again, I vote for the second one.

**Comment by MrPetovan** [comment]
Thank you for the suggestions, I do not have a favorite way of formatting the copyright notice, I just didn't want `2020-2021` because it is less accurate than just `2021`. So knock yourself out, all of the suggestions are fine as long as they are applied consistently.

**Comment by annando** [comment]
I really prefer `Copyright (C) 2010-2021, the Friendica project` since that shows how long this project already exists.

**Comment by MrPetovan** [comment]
Then let's do this.

**Comment by urbalazs** [comment]
Copyright changed as requested.

I noticed, that there are torrent magnet URL in [some JavaScript files](https://github.com/friendica/friendica/search?l=JavaScript&q=magnet). What is the purpose of these magnet URLs? I suggest to change them to static copyright notice like in other files (with another PR).

**Comment by tobiasd** [comment]
These are license hints for systems like [libreJS](https://www.gnu.org/software/librejs/). They should be in all of our JS files.

**Comment by tobiasd** [comment]
Who will be update all the year numbers in the future? AFAIK the usual way is to mark the year a file was created and which license it has once and not change that every year.

**Comment by urbalazs** [comment]
Many projects are changing its copyright date in every year. It is an easy task with a shell script:

```
for FILE in `grep -lr 'Copyright (C) 2010-2021, the Friendica project'`
do
    sed -i 's/2010-2021, the Friendica project/2010-2022, the Friendica project/' $FILE
done
```

This can be improved by searching for a regex (`2010-\d{4}`) and change to `2010-$(date '+%Y')` to use it in any time in the future.

**Comment by tobiasd** [comment]
The question was more aimed at the problem, that $somebody will have to _actually_ do this.

**Comment by nupplaphil** [comment]
We can add a periodic, yearly auto-check which will execute every kind of script we want :-)
So if there's a script, there's a solution too ;-)

**Comment by MrPetovan** [comment]
The fact that @urbalazs found out about the obsolete copyrights and updated them under three months into the new year makes me hopeful that someone™️ will do it every year relatively timely. It isn't a big deal anyway.

**Review by MrPetovan — APPROVED** [review]
Thank you for your work!

**Pull request merged**
