### PR TITLE
"Contact\User" class created 

### PR DESCRIPTION
**Pull request by annando**
Some functionality from `Contact` moved to `Contact\User` and `Contact\Relation`.

This PR is marked as draft since the PR with the fatal error has to be merged first.

### CODE REVIEW

**Comment by annando** [comment]
We should discuss which functions to split next. What about creating a spreadsheet?

**Comment by MrPetovan** [comment]
I believe you got the right idea with this PR: all the methods that deal with an intermediary table (user-contact, contact-relation) should be moved to separate classes.

**Comment by AlfredSK** [comment]
> What about creating a spreadsheet?

Famous last words. :-)

**Comment by annando** [comment]
We possibly could move some user related functions there as well that don't use these tables? For example `getByURLForUser`? And what should we do with function like `addRelationship`, `removeFollower` and `removeSharer`? I would like to move them to the `Relation` class as well, although they don't use the `contact-relation` table (by now), but they handle the relation between contacts.

**Comment by MrPetovan** [comment]
Sounds like a spreadsheet is in order. Do you want to create it?

**Comment by annando** [comment]
Not really :-)

**Comment by MrPetovan** [comment]
I figured. I'm a little busy with the `/common` module rewriting but I guess I can do it after.

**Pull request merged**
