### PR TITLE
Added true to json_decode

### PR DESCRIPTION
**Pull request by JeroenED**
Fix for #5469 

Don't approve if you know it won't fix. I couldn't get a hang on the issue as I didn't have the issue on my node.

The solution I wrote, I'm not sure at all as I had to figure it out by doing a search. My reference is in the comment.

### CODE REVIEW

**Comment by MrPetovan** [comment]
What version of PHP are you running?

**Comment by JeroenED** [comment]
@MrPetovan 7.2 checking changelogs already

**Comment by MrPetovan** [comment]
The reported error was on PHP 7.0, this may explain the discrepancy.

**Comment by JeroenED** [comment]
The only possibly relevant change.

7.1.0: An empty JSON key ("") can be encoded to the empty object property instead of using a key with value _empty_. 

http://php.net/manual/en/function.json-decode.php

**Pull request merged**
