### PR TITLE
fix typo: Independant --> Independent

### PR DESCRIPTION
**Pull request by haheute**
Found a typo.. must something  (messages.po) be "regenerated"? How?

### CODE REVIEW

**Comment by MrPetovan** [comment]
You have to run the command `bin/run_xgettext.sh` from the Friendica folder and commit the changes to `messages.po` to this PR.

**Comment by MrPetovan** [comment]
Congratulations, you managed to wipe out the `messages.po` file 😅

Not sure what happened, but the file wasn't correctly regenerated.

**Comment by haheute** [comment]
Thanks for your help. must I add some flag? It looks as if something did not work:

```
friendica@boerdi /var/www/localhost/friendica % bin/run_xgettext.sh
Friendica version 2024.06-dev
Extract strings to /var/www/localhost/friendica/bin/../view/lang/C/messages.po..
sort: unrecognized option: stable
BusyBox v1.36.1 (2023-11-07 18:53:09 UTC) multi-call binary.

Usage: sort [-nrughMcszbdfiokt] [-o FILE] [-k START[.OFS][OPTS][,END[.OFS][OPTS]] [-t CHAR] [FILE]...

Sort lines of text

	-o FILE	Output to FILE
	-c	Check whether input is sorted
	-b	Ignore leading blanks
	-f	Ignore case
	-i	Ignore unprintable characters
	-d	Dictionary order (blank or alphanumeric only)
	-n	Sort numbers
	-g	General numerical sort
	-h	Sort human readable numbers (2K 1G)
	-M	Sort month
	-V	Sort version
	-t CHAR	Field separator
	-k N[,M] Sort by Nth field
	-r	Reverse sort order
	-s	Stable (don't sort ties alphabetically)
	-u	Suppress duplicate lines
	-z	NUL terminated input and output

```

**Comment by haheute** [comment]
On my PC, `sort` has the option `-s, --stable` . On the Vserver, where I have run the command for `messages.po`,  `sort` only has the option `-s` , that could be the problem.

**Comment by MrPetovan** [comment]
Indeed, please edit the `bin/run_xgettext.sh` file to replace `--stable` with `-s` and run it again.

**Comment by haheute** [comment]
VServer (Alpine Linux) and PC (Void Linux), both say: `xgettext: command not found`.
Both don't seem to offer `xgettext`. I tried and installed `gettext` on the Server, but then it said: 
`Reading file 1/1071...gettext: invalid option -- 'k'` ...

edit: now something runs...  (I had made the mistake to change `xgettext` to `gettext` in the `run_xgettext.sh` file. But the `xgettext`command was available. so changed back. ...)

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
