### PR TITLE
Fix bug with ACL and contact network page

### PR DESCRIPTION
**Pull request by MrPetovan**
While working for a workaround for #5615, I found an ACL issue with the contact network page preventing the JOT from opening.

### CODE REVIEW

**Comment by annando** [comment]
This change has a huge downside: You will only see postings from contacts that you follow. The other view instead shows all posts and comments that are available on the server. I would suggest that we don't replace the one with the other but are adding a second link.

**Comment by rabuzarus** [comment]
I really don't know which view is better but I'm against just adding another link. Because it would be a against the logic of the other links which don't present "another view" for the same content but different content

**Comment by rabuzarus** [comment]
BTW: from my point of view the best opinion would be to wait until we have a threaded view for post of all contact (even when the user doesn't follow the contact)

**Comment by MrPetovan** [comment]
I’m with @rabuzarus, I didn’t expect the content would be specific to the viewing user, the goal is to have a community network page but for a specific account.

I don’t think I’m going to add another link in the hovercard as it would be hard to convey the difference with `/contacts/XYZ/posts` with just an icon.

**Comment by annando** [comment]
So the contacts page should get another tab. Making it more like the community page will be a little bit more work.

**Comment by rabuzarus** [comment]
> So the contacts page should get another tab

Here the problem is similar to the hovercard. We need to make sure that the tabs have the same logic. At the moment the logic is to present different content of a contact (Posts (Status), Profile, Contacts, Settings (Advanced)). If we add another contact post view to the tabs it has nothing to do with different content about the contact. If we want to keep the actual logic it would also belong to Status (Posts).

**Comment by annando** [comment]
(For me) it is very important to be able to see the comments that a contact is writing. This helps me for example to judge if I want to block that contact. So I personally really need a way to see the postings and comments.

**Comment by rabuzarus** [comment]
I would say we have 2 possibilities.

1.) replace the current contact `Status` page with a threaded view (but an enhanced version which also works for contacts the user doesn't follow).
or
2.) a widget for the contacts `Status` page for switching the view

**Comment by MrPetovan** [comment]
My suggestion for tab names:
- “Threads”  or “Wall” (New default interactive top-level posts view)
- “Posts and replies” (Current “Status” tab as an additional tab)

**Comment by MrPetovan** [comment]
I reduced the scope of this PR to the bugfix.

**Comment by annando** [comment]
This PR caused notices:
```
[17-Aug-2018 15:58:36 Europe/Berlin] PHP Notice:  Undefined index: allow_gid in /path/to/friendica/src/Core/ACL.php on line 300
[17-Aug-2018 15:58:36 Europe/Berlin] PHP Notice:  Undefined index: deny_cid in /path/to/friendica/src/Core/ACL.php on line 301
[17-Aug-2018 15:58:36 Europe/Berlin] PHP Notice:  Undefined index: deny_gid in /path/to/friendica/src/Core/ACL.php on line 302
[17-Aug-2018 18:13:40 Europe/Berlin] PHP Notice:  Undefined index: allow_gid in /path/to/friendica/src/Core/ACL.php on line 300
[17-Aug-2018 18:13:40 Europe/Berlin] PHP Notice:  Undefined index: deny_cid in /path/to/friendica/src/Core/ACL.php on line 301
[17-Aug-2018 18:13:40 Europe/Berlin] PHP Notice:  Undefined index: deny_gid in /path/to/friendica/src/Core/ACL.php on line 302
[17-Aug-2018 18:13:41 Europe/Berlin] PHP Notice:  Undefined index: allow_gid in /path/to/friendica/src/Core/ACL.php on line 300
[17-Aug-2018 18:13:41 Europe/Berlin] PHP Notice:  Undefined index: deny_cid in /path/to/friendica/src/Core/ACL.php on line 301
[17-Aug-2018 18:13:41 Europe/Berlin] PHP Notice:  Undefined index: deny_gid in /path/to/friendica/src/Core/ACL.php on line 302
[17-Aug-2018 18:13:41 Europe/Berlin] PHP Notice:  Undefined index: allow_gid in /path/to/friendica/src/Core/ACL.php on line 300
[17-Aug-2018 18:13:41 Europe/Berlin] PHP Notice:  Undefined index: deny_cid in /path/to/friendica/src/Core/ACL.php on line 301
[17-Aug-2018 18:13:41 Europe/Berlin] PHP Notice:  Undefined index: deny_gid in /path/to/friendica/src/Core/ACL.php on line 302
```

**Comment by MrPetovan** [comment]
Without traces or specific use cases it's unworkable since we were using random array structures as user and/or permission structures.

**Comment by annando** [comment]
I don't know. Do you have these notices as well, have you looked?

**Comment by MrPetovan** [comment]
No but it definitely a case that could happen since with the former function calls, a user/permission array could interchangeably be passed as first parameter, and the existence of the `uid`, `allow_uid`, `deny_uid`, `allow_gid` and `deny_gid` weren't checked either. I fixed a critical error for the display of the jot but I didn't touch the underlying logic which was faulty as well before.

**Comment by MrPetovan** [comment]
I found a recent one: 
```
Notice:  Undefined index: uid in src/Core/ACL.php on line 313
Stack trace:
  1. {main}() index.php:0
  2. network_content() index.php:387
  3. networkThreadedView() mod/network.php:382
  4. Friendica\Core\ACL::getFullSelectorHTML() mod/network.php:579
```

**Pull request merged**
