### PR TITLE
Remove poke feature

### PR DESCRIPTION
**Pull request by MrPetovan**
It's time.

Addon pendant: https://github.com/friendica/friendica-addons/pull/1278

### CODE REVIEW

**Review by Quix0r — APPROVED** [review]
Looking fine.

**Comment by annando** [comment]
I suggest that we have got a discussion in the support forum about this. I think it is fair to tell about it prior to the removal. In this discussion one should then point out the reasons for the removal.

**Comment by MrPetovan** [comment]
Discussion is here: https://friendica.mrpetovan.com/display/735a2029-1962-f40c-1f9e-092116008352

**Comment by MrPetovan** [comment]
A day in, everybody seems to be happy with this removal, I'm not used to this kind of plebiscite in open source software.

**Comment by nupplaphil** [comment]
Aaaaaaand it's gone :-)

**Pull request merged**
