### PR TITLE
Issue 9165:  Make pager work for search

### LINKED ISSUE #9165: Sometimes the pager isn't available on hashtag searches although there are more pages of search results
### Expected behavior
Always show a pager for hashtag search if there are more than one page of search results

### Actual behavior
If you search for an hashtag (or if you visit your saved hashtag searches) sometimes the pager isn't shown at the bottom of the page although there is are more results. If you manually add the parameter '&page=2' to the url you will get the other results. Unfortunately I can't say in which cases this behavior is reproducible.

### Friendica version you encountered the problem
2020.09-rc

### PHP version
PHP 7.4

### SQL version
MariaDB 10.3

### PR DESCRIPTION
**Pull request by annando**
Fixes https://github.com/friendica/friendica/issues/9165

### CODE REVIEW

**Comment by MrPetovan** [comment]
What about the case where the number of items returned by `Item::getforUser` is lower than the number of URI Ids returned by `Tag::getURIIdListByTag`?

**Comment by annando** [comment]
The only thing that will happen then is that on the last page there is still a "next page" pager. This is a small inconvenience compared to the current situation where you cannot even go to the next page, I think.

The rest can be done, once we use views in the `item` class.

**Comment by MrPetovan** [comment]
So no results are lost between pages?

**Comment by annando** [comment]
I guess this could happen. But in this stage of the PR I only wanted to make small changes.

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
So, the easy part, then. I'll take it.

**Pull request merged**
