### PR TITLE
Update version constraint for password_exposed

### PR DESCRIPTION
**Pull request by DivineOmega**
A new major release of the `password_exposed` package has just been released. This PR simply updates the version constraint.

### CODE REVIEW

**Comment by DivineOmega** [comment]
In fact, this probably will not work as is.

Are you planning on dropping support for older versions of PHP (< 7.1) in the next version?

**Comment by MrPetovan** [comment]
We’re doing a « soft drop », meaning that we only enforce a hard minimum of PHP version when we actually use a specific language feature, we just don’t offer official support for people running end-of-life PHP versions.

So technically Friendica runs on PHP 5.6+ but we only offer support from 7.1 onwards.

**Comment by MrPetovan** [comment]
Thanks for the version update. At the moment we are publishing the `composer.lock` as it was generated on the lowest possible PHP version Friendica technically supports. However, adventurous admins can run `composer update` on their own to take advantage of the more recent dependency versions.

**Comment by DivineOmega** [comment]
Thanks for the info. In that case, it might be better if you stay on version 2 of this package for now. I'll close this PR.

Out of curiosity, when do you plan on fully dropping PHP 5.6 & 7.0?

**Comment by MrPetovan** [comment]
@DivineOmega Like I said, when we'll start using PHP7.1+ specific features, which doesn't look like anytime soon from the look of it.

**Pull request closed without merging**
