### PR TITLE
[Scrutinizer] Fix formatting in dfrn_confirm and a few other files

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #4176

This is completely untested, I'd like to know what I need to do to test both `dfrn_confirm` scenarios so that I can at least give the impression that those changes have been somewhat covered.

We really need unit tests.

### CODE REVIEW

**Comment by annando** [comment]
To test this you should try to connect to another Friendica user. One scenario is to do this from your site (possibly via "/contacts" and entering the profile there). The other scenario is to go to the remote profile page and to add you there - and then vice versa.

**Comment by annando** [comment]
If you don't have a second Friendica account, you could set up one on squeet.me. Since this is my server, I could have a look at the log file in case of an error.

**Comment by MrPetovan** [comment]
I can make as many accounts as I want, but I probably need one on a different server to test either scenarios.

**Comment by MrPetovan** [comment]
* on my node.

Thanks for the offer!

**Comment by MrPetovan** [comment]
I created an account on squeet.me and successfully created both contact direction, once from the contacts page, the other from the "Connect" button on my node from squeet.me. I believe it should cover both scenarios.

**Pull request merged**
