### PR TITLE
Fix #2814

### LINKED ISSUE #2814: [frio] Opening notifications in new tabs
Currently, clicking on notifications items opens it in the same window, regardless of the clicking method (left, center, Ctrl+click). I'd like to let the users (me included) to choose how I want to open the notifications. I usually open all unseen notifications in separate tabs to save some time but in the current state, I can't do that.

I can't seem to find where this behavior is located in the code, but it seems like a trivial change to me, pretty much transparent for anyone that wasn't trying to open the notifications in a new tab.

### PR DESCRIPTION
**Pull request by Hypolite**
- [frio] Add a wrapping `a` tag around the notification text
- Add an event listener preventing popup menus to close when they are themselves clicked

### CODE REVIEW

**Comment by rabuzarus** [comment]
can you please reimplement the former behavior of linked author profile url?

**Comment by Hypolite** [comment]
What was it exactly? I thought we agreed only the author profile picture should lead to the profile URL?

**Comment by rabuzarus** [comment]
> On the other side it was a decision for consistency. At other places in friendica we always link the author  name with his/her profile url

> (if it's possible can try to keep the link to the author url)?

We could have a hardcoded notification text (with linked author name)

**Comment by Hypolite** [comment]
It is an either/or situation. Either we add a working link to the profile on the Author's name and then the notification as a whole cannot be a native link anymore, or the notification is a native link and there can't be no link on the Author's name.

I checked Facebook and Diaspora's notification dropdown:
- Facebook: the whole notification is a link, and no interaction is possible with any other elements (author's name or picture)
- Diaspora: the link to the notification is limited to the described item, while the author's name and picture are independent links (and hovercard shows up)

The current PR is a middle-of-the-road approach:
- The author's profile picture is actionable, but the rest of the notification (whole text + timestamp) is a native link to the notification item

These are the three main way of having notifications as native links. I for one don't think that author's name behavior consistency should be enforced in this specific context because it's a notification dropdown. I don't like Diaspora's way because the resulting link to the notification item isn't standardized across notifications, it depends on the size of the item description. The hovercard showing up over an already open dropdown menu feels like overkill to me. When I'm opening the menu, I just want to go to the new items pages, then I can decide if I want to go to the author's profile page or send a friend request. But maybe that's just me.

**Comment by fabrixxm** [comment]
> The hovercard showing up over an already open dropdown menu feels like overkill to me. When I'm opening the menu, I just want to go to the new items pages, then I can decide if I want to go to the author's profile page or send a friend request

:+1:

**Pull request merged**
