### PR TITLE
Remove x()

### PR DESCRIPTION
**Pull request by MrPetovan**
The prank where we had a custom global function that did the same as a PHP native function but worse is now over.

I'm running this branch, so far so good.

Due to the fact that this PR removes a function used by addons, https://github.com/friendica/friendica-addons/pull/779 should be merge BEFORE this one to prevent border case fatal errors.

Ideally, addons should also be pulled before the core as well.

### CODE REVIEW

**Comment by annando** [comment]
Can you have a look at the failed tests?

**Comment by MrPetovan** [comment]
Bless @nupplaphil.

**Comment by MrPetovan** [comment]
Given its extensiveness, this PR blocks me for further development.

**Comment by annando** [comment]
I had been on our companies Christmas party yesterday, so I had been blocked in some way as well :-) I will have a look at it today, but hopefully some second (or third) pair of eyes could have a look as well.

**Pull request merged**
