### PR TITLE
port of red matrix geotag feature

### PR DESCRIPTION
**Pull request by rabuzarus**
corresponding red commits: https://github.com/friendica/red/commit/7c194c37b891f122740de52d154db0af612e0074, https://github.com/friendica/red/commit/bc22df9057198018f9cc490d0e3e013692f52b90, https://github.com/friendica/red/commit/fab8209ebd4a052f8af5918de8603fd21a4bc7a6 and https://github.com/friendica/red/commit/6b3afb5eecca2964222e8dc09ddfae86e802c2f4

I would leave it to the theme developers to implement it in their themes

All credits going to Mike Macgirvin

### CODE REVIEW

**Comment by fabrixxm** [comment]
could you fix merge conflicts?

**Comment by rabuzarus** [comment]
does it solve the merge conflicts???? I don't know if you have clearer view on it. I tried to merge the developer branch back in my branch and now annados old commits are also listed. Is there any better procedure?

**Comment by annando** [comment]
It's looking really strange now. @fabrixxm could you have a look how to repair that pull request?

**Comment by annando** [comment]
@rabuzarus Are you on the develop branch or on the master branch?

**Comment by rabuzarus** [comment]
I should be on the develop branch (if I have done no mistake)

**Comment by rabuzarus** [comment]
I don't understand this. When I visit my repository in github and compare it with friendica master then there are exact the same old commits included. When I compare it with the developer branch of friendica then only my commit appears. But this pull request based on the developer branch and is send against the developer branch.

How to going on? Delete this pull request and start a new one?

**Comment by ddorian1** [comment]
This should be easily fixable by running ```git rebase origin/develop``` (replacing origin with whatever you called the upstream friendica repo).
Afterwards, you will need to force-push your changes.

**Pull request merged**
