### PR TITLE
Issue #3878 hotfix

### PR DESCRIPTION
**Pull request by MrPetovan**
There was a "Class Crypto not found" error after the last PR on #3878, this fixes it by moving the defuse/php-encryption library to vendor dependencies.

The library is upgraded from version 1.2.1 to version 2.1.0 in the process.

As usual with Composer PR, please review only specific commits, in this case https://github.com/friendica/friendica/pull/3888/commits/acd65aade17c2e8db1dcb012b6d14a732bc87244

### CODE REVIEW

**Comment by MrPetovan** [comment]
This won't cut it, we have to revert to version 1.2.1 as all the keys should be migrated to version 2 at the same time...

**Comment by annando** [comment]
:-( I wanted to ask, if you had checked if the libraries was compatible to the old one ...

**Comment by MrPetovan** [comment]
The problem is that I have to wait for something to happen with the worker/poller to see if my changes worked. There is a migration function that can update all 1.2 keys to 2.* keys, however this would need to be run on all Friendica instances at the same time.

**Comment by annando** [comment]
Is it used for Rhino or for which places?

**Comment by MrPetovan** [comment]
In `mod/dfrn_notify.php:186` and `src/Protocol/DFRN.php:1308`, RINO mode = 2.

**Comment by annando** [comment]
So we deprecate that RINO version?

**Comment by MrPetovan** [comment]
We could add a mode = 3, but what about the compatibility between different modes? I’m not sure I understand how RINO works.

And there’s the quirk of requiring the same library in two different versions, not sure how Composer would handle that. Both libraries can safely be used next to each other thanks to namespaces introduced in version 2, but we would need custom folder names in `vendor/`.

**Pull request merged**
