### PR TITLE
Combine Accept header values in Magic module

### LINKED ISSUE #13174: Accept header as array not functional with nginx
- [x] I have searched open and closed issues for duplicates

### Bug Description

In https://github.com/friendica/friendica/blob/70674f2ecc9d34ba7eabbd15c06f85b469b27d0e/src/Module/Magic.php#L122 the accept header is set as an array. If the receiving server is nginx (in its default config), only the last entry of the array will appear under accept and thus make it impossible to verify the HTTP signature. I can confirm that apache handles this differently and the accept header looks like expected there.

Actual Result:
`$_SERVER[HTTP_ACCEPT] => 'application/x-zot+json'`

Expected Result:
`$_SERVER[HTTP_ACCEPT] => 'application/x-dfrn+json, application/x-zot+json'
`

Fix: 
According to RFC9110 headers with multiple values should be set in separate lines like
```
Accept: application/x-dfrn+json
Accept: application/x-zot+json
```
or combined
`Accept: application/x-dfrn+json, application/x-zot+json`

I can confirm that the latter works for nginx and i suppose also for apache. Have not tested the first though.

### Platform Info

Friendica Version:
2023.05

### PR DESCRIPTION
**Pull request by git-marijus**
Fix #13174

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]
Thank you for your work!

**Comment by nupplaphil** [comment]
I know we had some discussion about this. Having arrays as header have had bricked an addon, the phpmailer afaik, because we have to send multiple header instead of an array.

I'll have a look tomorrow on it

**Comment by MrPetovan** [comment]
I checked the line of calls to the GuzzleHttp Client to make sure that both types were supported. We could restore the arrays while keeping the single comma-separated Accept value in the Magic module.

**Comment by nupplaphil** [comment]
yep you're right. It was a different issue, everything fine, thank you :)

**Pull request merged**
