### PR TITLE
[Vier] Add plus icon to profile view for follow

### LINKED ISSUE #9315: No Connect below Profile Picture
- [ x] I have searched open and closed issues for duplicates

I tried to but the URL above did not work.

### Bug Description

There is no "Connect" word or button below the profile image that friendica instructions says should be there.
### Steps to Reproduce

Select another friendica user on your friendica site, go to their profile, look at the picture, no "Connect" below it.
1.  step one
2.  step two
3.  step three

Actual Result:

No Connect
Expected Result:

Expect to see a Connect word or button so I can friend them.

### Screenshots

Screenshot at 2020-09-28 15-09-06

### Platform Info

Friendica Version:

This is Friendica, version 2020.12-dev that is running at the web location https://friendica.eskimo.com. The database version is 1369/1369, the post update version is 1341. 

The instructions for finding version didn't work either, I found this under Help -> Information.  There is no About This Site
in my help menu.
Friendica Source: 
Git Hub Develop
PHP version:
'PHP 7.4.10 (cli) (built: Sep  9 2020 06:36:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies

SQL version:
mysql  Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### PR DESCRIPTION
**Pull request by vinzv**
I'm trying to fix #9315 but `{{$follow_link}}` does not generate a link like `follow?url=https%3A%2F%2F…`.
Could someone please point me in the right direction?

### CODE REVIEW

**Comment by MrPetovan** [comment]
The follow link (if any) is already displayed in this template on line 57.

Let's trace back this variable:
- It is passed to the template in `src/Model/Profile.php:439`
- It is set on lines `321` and `327` of the same file, but it is conditional on `$show_connect` being set to `true`.
- `$show_connect` is defined as a function paraeter in line `261` of the same file.
- It is directly passed from the `$show_connect` function parameter on line `146` of the same file.
- Now, `Model\Profile::load` is called in many places, including in `mod/display.php` on line `129` which is the case that interests us.
- The `$show_connect` parameter isn't provided which means it is supposed to be set to `true` by default so it isn't that.
- The other variables to check their values to enable follow links are the following in `src/Model/Profile.php`:
    - `$local_user_is_self` should be false
    - `$visitor_is_authenticated` should be false or `$profile_is_native` should be true
        - if `$profile_is_native` is true then `$visitor_is_following` should be false

**Comment by MrPetovan** [comment]
Is it really a theme-specific issue?

**Comment by AlfredSK** [comment]
~~In frio the buttons for follow/unfollow (and sending a message (PM)) are also missing when you are on a /display/... page.~~

Sorry. I'm surprised. There is a follow button. ;-)

**Comment by vinzv** [comment]
> Sorry. I'm surprised. There is a follow button. ;-)

Yes, on /display… and /contact/… there is one. But not on /profile/…

@MrPetovan Doh! I just checked with Frio and there's no follow button as well.

**Comment by vinzv** [comment]
> The follow link (if any) is already displayed in this template on line 57.
> 

Yes, but the whole `profile-extra-links` block is empty which makes no sense to me.

image

> Let's trace back this variable:
> …

Understood so far. But looking at that it should be visible, right?

**Comment by MrPetovan** [comment]
Yes, so we have to dig deeper into the value of the variables I listed. I was busy with the languagefilter addon but now I can look into it.

**Comment by MrPetovan** [comment]
I've curtailed the problem to the vcard of a profile on the same node that you aren't following. Otherwise it works for remote profiles in frio and vier.

**Comment by MrPetovan** [comment]
I now found the culprit, it was [the definition of `$local_user_is_self`](https://github.com/friendica/friendica/pull/9357). Thank you for your work, this PR is now obsolete.

**Pull request closed without merging**
