### PR TITLE
Add PHP CS-Fixer

### PR DESCRIPTION
**Pull request by nupplaphil**
See https://github.com/FriendsOfPHP/PHP-CS-Fixer

This will add a "PHP Coding Standard Fixer" to the CI pipeline :)
The goal is to support @MrPetovan finding non-standard PRs. I know he's doing his job well finding things like "missing line at EOF", but I think having an automatism for it will make it homogeneous and transparent for all :)

This is just a Draft PR, because it will reformat working Friendica code and I think I'll better rebase it onto the `develop` branch after the release

### CODE REVIEW

**Comment by MrPetovan** [comment]
Yeah, I considered using PHP CS Fixer initially, but it was going to impact so many files that I opted for manual and gradual instead of automatic and total. However now might be a good time to revisit this choice since I estimate about 70% of the code has been reformatted.

Edit: Oof, still 1,000 violations...

**Comment by nupplaphil** [comment]
What about linting just new files instead of the overall code-base? 
=> explained here https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.18/doc/usage.rst#using-php-cs-fixer-on-ci

Or removing the whole `addons`, `mod` and `include` directory? I think this should reduce the files

And tbh you should check my `.php_cs.dist` file because I don't know if everything is configured as needed.

**Comment by MrPetovan** [comment]
> And tbh you should check my `.php_cs.dist` file because I don't know if everything is configured as needed.

See, this is why I'm not a fan of enabling an automated code style fixer. I have a personal view of what the format should look like, mostly PSR-2 with tabs, and I'm able to exercise my own judgment when I looking through files. I may miss some violations, but it isn't a big deal.

With an automated tool, I suddenly have to be extremely literal with the code style definition and in the current state it still will result in hundreds of violations in old files, so it feels like a massive hammer that needs to be finely-tuned and I don't feel like going into the intricacies of PHP CS Fixer right now for a low perceived gain given the absence of control I have over every single run of PHP CS Fixer.

**Comment by nupplaphil** [comment]
For me, automation is used to shift time from "repetitive" tasks to creative tasks. So searching in PRs for formating errors is - for me - is repetitive.

And two other reasons, I'm not 100% with you:
- For the overall codebase, the judgement of formatting is up to you, which isn't per se bad, but we tend to see things different at different cases, and so we create in-homogeneous formats.
- If your absent for some days, it's unlikely that others will have the same personal view or it wouldn't be checked at all

So I see such things as investment for the future. Like every quality task tends to be :D

I'll change the setup for "new files only" and so we could adapt the rules case by case without "hammering" onto 100s of files :-)

Edit: And I'll add the `continue-on-error` flag, so this check is an advice instead of a requirement :)

**Comment by MrPetovan** [comment]
I review all the PR's code, not specifically for formatting but it is just part of the normal review process. I note that it's been a while since I had to tell anyone else to change something formatting-related, so my initial constant nagging seems to have worked, and having an automated process nagging us over the rest of the files we never touch is a self-inflicted curse I could do without.

This is why I like this idea better if it only checks new files, thanks.

**Review by MrPetovan — APPROVED** [review]

**Comment by nupplaphil** [comment]
Now it works as expected. Just scan changed files and the test outputs a diff what it would expect :-)
And merging is still possible even if this check failed

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
