### PR TITLE
Revert pull request #13463

### LINKED ISSUE #13467: WSOD after importing pull request #13463
Some time after git pull from https://github.com/friendica/friendica/commit/dd7bea4bd146acf52086d303fce34a83d52f2516 I have a WSOD and the following error message in the log.

```
2023-09-24T14:34:31Z ERROR app Uncaught Exception DivisionByZeroError: "Division by zero" at /var/www/html/src/Model/Post/Media.php line 1181

DivisionByZeroError: Division by zero at /var/www/html/src/Model/Post/Media.php:1181
Stack trace:
#0 /var/www/html/src/Model/Item.php(3539): Friendica\Model\Post\Media::getAllocatedHeightByMedia()
#1 /var/www/html/src/Model/Item.php(3246): Friendica\Model\Item::addVisualAttachments().
#2 /var/www/html/src/Object/Post.php(431): Friendica\Model\Item::prepareBody()
#3 /var/www/html/src/Object/Thread.php(204): Friendica\Object\Post->getTemplateData().
#4 /var/www/html/src/Content/Conversation.php(685): Friendica\Object\Post->getTemplateData()
#5 /var/www/html/src/Content/Conversation.php(583): Friendica\Object\Conversation->getThreadList()
#6 /var/www/html/src/Module/Conversation/Network.php(239): Friendica\Content\Conversation->render()
#7 /var/www/html/src/BaseModule.php(244): Friendica\Module\Conversation\Network->content().
#8 /var/www/html/src/App.php(710): Friendica\BaseModule->run()
#9 /var/www/html/index.php(59): Friendica\App->runFrontend()
#10 {main}
```

by a 
`git checkout ce16cd12ec46413581f5ade6487387f56723e3`
I was able to fix the WSOD 

### Platform Info

Friendica Version:

Friendica Source: 2023.09-dev - 1534

PHP version: 8.1.2

SQL version: 10.6.12

### PR DESCRIPTION
**Pull request by MrPetovan**
Revert #13463
Fix #13467 
Replace #13468

No other fix will reliably satisfy this error and at the same time keep providing the intended feature since we don't have reliable dimensions for post images which my work naively assumed.

In the future we might be able to use a two-pronged approach where we first check we can use my solution by verifying the existence of dimensions.

### CODE REVIEW

**Comment by annando** [comment]
Why should we revert the whole functionality, when we only find a way to handle the case with some missing data? I suggest to accept my PR, since this will be a quick fix for the division by zero. And then we can have a look at the situations, where the width/height values are missing.

**Comment by MrPetovan** [comment]
Thank you, I appreciate it but like I wrote my feature is based on the necessary expectations that all images have their dimensions supplied. There is no workaround to guess the image aspect ratio that’s needed for the placeholder to work and there’s no default value that won’t break the display in some interesting albeit upsetting ways.

Same for the image grid, if just one image in a row doesn’t have dimensions, I can’t predict how the display will look like since it’s entirely relying on these dimensions.

It’s one of those cases where we can’t be lax in what we accept. Either all the images in `post-media` have dimensions and we can enable my feature, or at least one doesn’t and we can’t, because of the random hilarious display breakages that would ensue.

However, these dimensions are known by the origin system, so we could supply them alongside posts which would save us the trouble of retrieving the remote image ourselves, but we have to do this for all supported protocols. It isn’t something I feel like diving into at the moment, so it will have to wait.

**Comment by annando** [comment]
I guess that the only situation where we don't have got dimensions is when there had been a problem fetching them. I just had a look at my database. There are currently 1,075,817 images in the `post-media` table. And 3,956 of them don't have got dimensions. So this feature will mostly work fine, since the data is only missing at around 4 per thousand of the images at all.

**Comment by MrPetovan** [comment]
I didn’t look at the full table count, but I have 80,000 dimension-less `post-media` records, probably on a smaller total table than yours.

So it isn’t that insignificant, and more importantly it’s painfully obvious when such an attachment is displayed with my feature, even with your fix, while it is currently transparent for users when dimensions are missing.

**Comment by MrPetovan** [comment]
Ran the following queries on my production node:
```
MariaDB [friendica]> SELECT COUNT(*) FROM `post-media`;
+----------+
| COUNT(*) |
+----------+
|   193795 |
+----------+
1 row in set (0.540 sec)

MariaDB [friendica]> SELECT COUNT(*) FROM `post-media` WHERE `width` IS NULL AND `height` IS NULL AND `preview-width` IS NULL AND `preview-height` IS NULL;
+----------+
| COUNT(*) |
+----------+
|    42195 |
+----------+
1 row in set (0.259 sec)
```
This gives a staggering 21% of dimension-less `post-media` record. Not something we can overlook.

**Comment by annando** [comment]
You have to only count the type `1`. There are a lot of types out there that don't have got dimensions:
```
> SELECT COUNT(*), `type` FROM `post-media` WHERE `width` IS NULL AND `height` IS NULL AND `preview-width` IS NULL AND `preview-height` IS NULL GROUP BY `type`;
+----------+------+
| COUNT(*) | type |
+----------+------+
|   164038 |    0 |
|     3949 |    1 |
|    15705 |    2 |
|     9532 |    3 |
|      230 |    4 |
|    11597 |    5 |
|       58 |   16 |
|   303039 |   17 |
|      627 |   18 |
|     1224 |   19 |
|    33267 |   20 |
|     5767 |   21 |
|       31 |  128 |
+----------+------+
```
And here the totals:
```
> SELECT COUNT(*), `type` FROM `post-media` GROUP BY `type`;
+----------+------+
| COUNT(*) | type |
+----------+------+
|   220414 |    0 |
|  1072641 |    1 |
|    83749 |    2 |
|     9579 |    3 |
|      230 |    4 |
|    11597 |    5 |
|     8999 |   16 |
|  1376839 |   17 |
|      627 |   18 |
|     1224 |   19 |
|    33267 |   20 |
|     5767 |   21 |
|       34 |  128 |
+----------+------+
```

**Comment by MrPetovan** [comment]
For the sake of accuracy I ran the following queries:
```
MariaDB [friendica]> SELECT COUNT(*) FROM `post-media` WHERE `type` = 1;
+----------+
| COUNT(*) |
+----------+
|   112198 |
+----------+
1 row in set (0.193 sec)

MariaDB [friendica]> SELECT COUNT(*) FROM `post-media` WHERE `width` IS NULL AND `height` IS NULL AND `preview-width` IS NULL AND `preview-height` IS NULL AND type = 1;
+----------+
| COUNT(*) |
+----------+
|      618 |
+----------+
1 row in set (0.277 sec)
```
That's closer to your ratio, but that's besides the point. Even if it is unlikely, it is random and it will visually break stuff even if we work around the division by 0 issue, and users will notice. Despite a 4-5 per thousand chance, a Fatal Error was reported about a missing dimension image within just 4 hours of the PR being merged just on `develop`. Imagine the frequency of support requests with evidence screenshots after a stable release to ten- or hundredfold more users.

I'd rather not half-measure it, so either we improve the dimension collection to a point where we don't have any dimension-less images anymore, or we keep the current stable behavior however imperfect it is, at least it's consistent. And since the former is possible but hard, I'd rather we do the latter first.

**Comment by annando** [comment]
I suggest to merge the quick fix and then to have got a look at how to catch these cases. For example we could have a look if we have got all data - and if this is the case, we could proceed. And if this wasn't the case, we could use the old mechanism.

**Comment by MrPetovan** [comment]
Problem is the new mechanism replaced the old one, so it would be some work to bring it back in parallel. I’d prefer if we started this work from the current stable version. Even with the revert, my work wouldn’t be lost, it would live on in the git history.

Your fix is well-meaning, but assuming all dimensionless images are square-shaped isn’t a solution.

**Comment by annando** [comment]
I find it funny that I fight for keeping your coding that you want to abolish 😬 

I think that it is the best to use the time until the release to both collect some experience of this new feature and to find a way to handle missing picture data.

**Comment by MrPetovan** [comment]
I don't want to abolish it forever, we just need more time to make it right, and while it helps averting the fatal error, I don't think your quick fix is right.

**Comment by MrPetovan** [comment]
Alright, enough talk, I submitted my PR, I can damn well revert it myself.

**Pull request merged**
