### PR TITLE
Issue 2199: Diaspora doesn't interpret size elements

### PR DESCRIPTION
**Pull request by annando**
Fixes https://github.com/friendica/friendica/issues/2199

### CODE REVIEW

**Comment by nupplaphil** [comment]
Plz add an assertion of your change here:
https://github.com/friendica/friendica/blob/878d8a506d5de562ad873b336824ff07179078e2/tests/src/Content/Text/BBCodeTest.php#L178

You just need to define new input/expectations for this type of convert and the test will check it

**Comment by MrPetovan** [comment]
But there's no test for `$simpleHtml = 3`?

**Comment by nupplaphil** [comment]
Wouldn't it be possible to add it as a additional parameter in the dataset here:
https://github.com/friendica/friendica/blob/878d8a506d5de562ad873b336824ff07179078e2/tests/src/Content/Text/BBCodeTest.php#L188
?

**Comment by nupplaphil** [comment]
This tests should check it, the first is working even without the PR, the second test has to be adapted the way, how this PR changes the output (tbh I don't really know what different output it should be now ..)

```php
'bug-2199-no-diaspora-size-elements' => [
	'expectedHtml' => '<strong><span style="font-size: xx-large; line-height: initial;">Test text</span></strong>',
	'text' => '[b][size=xx-large]Test text[/size][/b]',
	'simpleHtml' => 0,
],
'bug-2199-diaspora-size-elements' => [
	'expectedHtml' => '<strong><span style="font-size: xx-large; line-height: initial;">Test text</span></strong>',
	'text' => '[b][size=xx-large]Test text[/size][/b]',
	// Triggers the diaspora compatible output
	'simpleHtml' => 3,
],
```

**Comment by MrPetovan** [comment]
Update with new behavior:
```php
'bug-2199-named-size' => [
	'expectedHtml' => '<span style="font-size: xx-large; line-height: initial;">Test text</span>',
	'text' => '[size=xx-large]Test text[/size]',
	'simpleHtml' => 0,
],
'bug-2199-numeric-size' => [
	'expectedHtml' => '<span style="font-size: 24px; line-height: initial;">Test text</span>',
	'text' => '[size=24]Test text[/size]',
	'simpleHtml' => 0,
],
'bug-2199-diaspora-no-named-size' => [
	'expectedHtml' => 'Test text',
	'text' => '[size=xx-large]Test text[/size]',
	// Triggers the diaspora compatible output
	'simpleHtml' => 3,
],
'bug-2199-diaspora-no-numeric-size' => [
	'expectedHtml' => 'Test text',
	'text' => '[size=24]Test text[/size]',
	// Triggers the diaspora compatible output
	'simpleHtml' => 3,
],
```

**Comment by annando** [comment]
@MrPetovan I couldn't believe that either :-)

**Pull request merged**
