### PR TITLE
Rework profile, profile settings and remove multi profiles

### PR DESCRIPTION
**Pull request by MrPetovan**
This PR, huh, addresses https://github.com/friendica/friendica/issues/7676#issuecomment-538666825 among other things.

The other things:
- Moves profile settings in src/Module/Settings
- Moves profile statuses to own module (removes the need for a specific tab parameter for the profile itself)
- Reworks profile picture settings, in particular we don't create a new picture every time we enter the cropping page.
- Moves profile-related templates to a dedicated sub-folder
- Removes unused profile-related templates
- Removes the multi profiles extra feature but all the data is kept which leaves room to restore it or give read-only access to them in an upcoming PR before the release.

This PR doesn't implement the image uniqueness test because it was a quagmire and this PR is big enough.

Addon PR: https://github.com/friendica/friendica-addons/pull/909

### CODE REVIEW

**Comment by annando** [comment]
Although I'm not a big fan of the multiple profiles, I would prefer having a solution for this prior before removing it. We do have our hackathon on the next weekend. I hope that there we will find something that will make us all happy. But before this I would prefer not merging this PR.

**Comment by MrPetovan** [comment]
I'm ready to implement the custom profile fields with ACL you suggested, although I'm not sure how I'm going to handle the ACL selection for themes other than frio, I guess it's going to be nicely tied with #7308

**Comment by annando** [comment]
A possibly easier way would be to mostly use the existing data model, but to synchronize some of the fields while editing. For example: The name and the avatar could be identical between all versions of the profile. And one could define more fields as synchronized. Then you could have some drop down list at the top of the profile editor switching between the profiles.

Or - and this has to be discussed this week - one could have a selection per field on which profile this should appear.

I have the fear that a complete free format profile structure with individual permissions would have a bad impact on performance when displaying the profile page. So at first defining the "aspects" of your profile and then assigning the different fields to these aspects could be an idea.

We have several options and I would like to speak about them this week. After this had been done we can start working on it.

**Comment by MrPetovan** [comment]
I've thought about the performance issue, and I think it can be solved by having a custom profile field cache field with the expanded ACL that can be easily compared to a given contact ID. If this isn't enough we can have a n:m table with `field_id`, `contact_id` fields for faster lookup.

**Comment by annando** [comment]
When it would come to single field permissions, I do suggest the permissionset method that is already used for the items. This prevents us from having these "allow_cid", ... fields everywhere.

But we will see what the weekend will bring.

**Comment by annando** [comment]
BTW: Have you seen that the tests had been failed? There is at least an issue with the images.

**Comment by MrPetovan** [comment]
I don't get it, this test should have failed for all previous PRs since at least August 2018 ???

**Comment by MrPetovan** [comment]
Ah, no, I get it, I moved `supportedTypes` from `Object\Image` to `Util\Images` so the mocked `Object\Image` doesn't work anymore.

**Comment by nupplaphil** [comment]
> 
> 
> Ah, no, I get it, I moved `supportedTypes` from `Object\Image` to `Util\Images` so the mocked `Object\Image` doesn't work anymore.

If you like, you can write an issue for fixing this test, add a `$this->markTestIncomplete('needs adapted class_exists() mock`);` and assign the issue to me. I think this test-pain is because of the global function-mocking, which is a lot of pain. It's not that important that it's blocking you from other things ... :-/

**Comment by MrPetovan** [comment]
Ooooh, that's because there a namespaced `class_exists` call, got it now.

**Comment by MrPetovan** [comment]
> When it would come to single field permissions, I do suggest the permissionset method that is already used for the items. This prevents us from having these "allow_cid", ... fields everywhere.

Thanks for the heads-up, I forgot about it.

**Comment by MrPetovan** [comment]
> Although I'm not a big fan of the multiple profiles, I would prefer having a solution for this prior before removing it. We do have our hackathon on the next weekend. I hope that there we will find something that will make us all happy. But before this I would prefer not merging this PR.

Can this please be a priority?

**Comment by annando** [comment]
We just discussed about it. We came to the following solution:
We have a set of fixed fields. These fields are the ones that are already distributed (like avatar, name, about, location, ...).

Additionally we have dynamically definable fields. We can define as many fields as we want to and we can name them as we want to. But when typing in the field description, the system will (if possible) make some suggestions. For every field we can define the audience (Public, family, friend, ...). The audience has to be defined before. We can have an unlimited number of different audiences and we can apply the ACL to them.

We can assign the same field to multiple audiences and we can assign fields with the same name (but different content) to different audiences. For example you could define a field "e-mail" with your private mail address that you assign to your friends and your family. And you can create another field "e-mail" with your work mail address that you assign to your "public" audience.

Another important thing is, that we do new some automatic migration that will transfer all existing multiple profiles into this scheme.

Do you think that this is a working solution?

**Comment by AlfredSK** [comment]
This sounds very interesting. I like it. But it sounds also like a lot of work.

**Comment by MrPetovan** [comment]
@annando This is exactly what I was thinking about. We don't even need to create an "audience" concept since we already have contact groups.

> Another important thing is, that we do new some automatic migration that will transfer all existing multiple profiles into this scheme.

It is easy, since current profiles have ACL, it will able to be converted to custom profile fields with ACL as well.

I'll start working on it once this PR is merged, I don't want to make it even bigger than it already is.

**Comment by annando** [comment]
I would like to have it as different audiences, since this could - but needn't - be the same.

**Comment by MrPetovan** [comment]
I have to put my foot down here, it is the same exact feature as groups and adding an "audience" concept would be even more confusing.

**Comment by tobiasd** [comment]
i think this needs to e done in one PR, else there cannot be an automatic migration between the current multi-profiles and the new was.

**Comment by MrPetovan** [comment]
Like I said, this PR only removes the front-end for multiple profiles, but the data is kept in the database, which means it can be migrated in a further PR. Code and data are completely separate.

**Comment by annando** [comment]
Do you think that it could be possible to split this PR into the image stuff and the profile stuff? This would reduce the amount of changes in the PR.

**Comment by MrPetovan** [comment]
Both aren't independent and would need to be merged one after the other, but it's possible.

**Comment by annando** [comment]
If the needed work to split these tasks is doable with not too much effort, I really would love to see it.

Concerning the profile PR and the then upcoming profile fields PR: I guess that i would be better to cover this in a single PR, since we do have production servers on the "develop" branch - and I guess that (to not confuse the users), these servers would most likely pause the updating during these two PR.

Also the administrators had to be informed prior to accepting this first PR, so that they could decide what to do. Since - when they would continue updating, they had to inform their users that for some time it wasn't possible to access this data.

So having the image stuff in one PR and having the profile stuff (including the new multiple fields) in another PR would be the best idea.

And: We do have to make sure that there is an automatic conversion from the current profile data to the new system. This would also means that we had to possibly create new groups based upon the profile ACL.

**Comment by MrPetovan** [comment]
> If the needed work to split these tasks is doable with not too much effort, I really would love to see it.

It didn't require any specific work, it just means that merging this present PR would also merge the commits in #7798.

> And: We do have to make sure that there is an automatic conversion from the current profile data to the new system. This would also means that we had to possibly create new groups based upon the profile ACL.

Why? Existing ACL are based on existing groups, worst case scenario if the group doesn't exist anymore (how do we handle this anyway?) every single affected contact will be listed in the `contact_allow` field.

**Comment by AlfredSK** [comment]
> I guess that (to not confuse the users), these servers would most likely pause the updating during these two PR.

I did a reality check on my DB. Out of 1050 users 52 have enabled the feature and 23 have more than 1 profile.

**Comment by annando** [comment]
We really do need an automatic conversion of the current profile fields into the new format. Question is, how this can be done automatically without any hiccups. For this reason I thought of using the audiences. But I'm completely open to any other way, as long as the users don't have to manually take some action.

**Comment by MrPetovan** [comment]
I heard both @tobiasd and your repeated plea about the automatic migration procedure of a feature that concerns less than 3% of our users. I'm confident I can do it without hiccups because it isn't that complicated. The profile table will stay as is until the next release for insurance purposes.

**Comment by MrPetovan** [comment]
> We have a set of fixed fields. These fields are the ones that are already distributed (like avatar, name, about, location, ...).

Can you give me the precise list of fields that are distributed and therefore present by default?

> And: We do have to make sure that there is an automatic conversion from the current profile data to the new system. This would also means that we had to possibly create new groups based upon the profile ACL.

The current multiple profile system is only based on individual contacts. Furthermore, a single contact couldn't be shown multiple profiles, so the migrated fields will only have permission sets with `allow_cid` and they will not overlap each other.

**Comment by annando** [comment]
I think all profile fields are fixed that are editable when you are in the simple profile view. Means:
* Name
* Gender
* Birthday
* About
* Homepage
* XMPP address
* All address fields
* public and private keywords

Concerning the fields and the ACL: I'm looking forward seeing your solution.

**Comment by MrPetovan** [comment]
> I think all profile fields are fixed that are editable when you are in the simple profile view. Means:
> 
> * Name
> * Gender
> * Birthday
> * About
> * Homepage
> * XMPP address
> * All address fields

Thanks. I will use my executive decision and remove `Gender` from this list. Name and About are mandatory of course, and all the others have special display treatment that cannot be easily transformed into generic custom fields.

But `Gender` is the outcast here.

**Comment by MrPetovan** [comment]
Also what is the difference between the `hometown` field and the numerous address fields? We don't seem to distribute either.

**Comment by annando** [comment]
I had the feeling as if the gender is used in the directory as well. But if this isn't the case, you totally have got my support (and the support of @hoergen and @tobiasd as well).

**Comment by AlfredSK** [comment]
Yep. We have an address (with city/town) and a hometown field. I guess the first is your current resident location the second is meant as your place of origin.

**Comment by MrPetovan** [comment]
I'm tempted to nix the complicated address fields for basic profile.

**Comment by AlfredSK** [comment]
Also, we have a filed "title/description" and "about" which is kind of redundant. And I never know which is used in what places or which one is distributed to other nodes. I know that one of those two fileds doesn't exist on forum accounts. What makes it even weirder. :-)

**Comment by MrPetovan** [comment]
Ah wait we need the complicated fields for directory filtering. So the Hometown field leaves the basic profile.

**Comment by annando** [comment]
We do have a function that generates a "location" string out of these address fields.

**Comment by MrPetovan** [comment]
I've only seen it in the frio template so far, do you happen to remember the name of the function?

**Comment by annando** [comment]
See here: https://github.com/friendica/friendica/blob/develop/src/Model/Profile.php#L86

**Comment by MrPetovan** [comment]
The import part is ready. It reads all profiles for a single user, keeping the basic fields for the default profile and transforming all the others into custom profile fields, optionally assorted of a permission set if a specific visibility was selected. No need to create groups or audience since profiles could only be shown to specific contacts.

A caveat though: if no visibility had been set for the profile, I'm not sure what to do with the created custom fields, should they be public, with possible duplicates, or can I can create a permission set with the user's own contact?

**Comment by annando** [comment]
When no visibility is set and it isn't the default profile, then the data shouldn't be public.

**Comment by MrPetovan** [comment]
Agreed, so I should use the self contact ID for those.

**Comment by annando** [comment]
BTW: I don't see a problem with multiple identically named fields. One could have (for example) a telephone number field for friends and family and an additional one only for the family with different numbers in it.

I wouldn't invest any time in any duplicate check or merging of these data fields. The most important thing for me would be that the ACL settings can be done very easy. (That's why I had suggested the additional "audience" layer)

**Comment by MrPetovan** [comment]
The ACL will be done the same way it is done in the Compose page with an autocompleted "tags" field. I didn't bother with duplicates either.

**Comment by MrPetovan** [comment]
Closing this as I don't expect being able to release the full feature for this milestone.

**Pull request closed without merging**
