### PR TITLE
Enable Travis

### PR DESCRIPTION
**Pull request by Rudloff**
Hello,

I'm working on phpunit tests for the API functions and having a way to run them automatically after each commit would be nice (and it would help spot PRs that introduce regressions).

This PR adds a `.travis.yml` file needed to enable [Travis](https://travis-ci.org/) (as suggested in https://github.com/friendica/friendica/issues/2721).
[I enabled Travis for my fork](https://travis-ci.org/Rudloff/friendica) but if this PR is merged, it would of course need to be enabled for this repository too.

I also added a `phpunit.xml` that allows to run the test by just calling `phpunit` without any argument (which is what Travis does by default).
I had to disable two test files because they were failing.

### CODE REVIEW

**Comment by MrPetovan** [comment]
The current tests files should be removed as they are bogus and not even used right now. Please remove them and simplify your config file.

**Comment by MrPetovan** [comment]
I'm not sure I have the permission to enable Travis on the friendica repository. @annando , @tobiasd  , @fabrixxm ?

**Comment by Rudloff** [comment]
I removed the old tests and created a test for the smallest class I could find in order to still have something to run on Travis.

**Comment by MrPetovan** [comment]
Oh, I didn't expect any test to actually work, do you think we should keep the ones that still work?

**Comment by Rudloff** [comment]
I think we could regroup tests that work into a `TextTest` class. I can try to clean them up a bit and update the PR.

**Comment by MrPetovan** [comment]
That would be great, thanks!

**Comment by tobiasd** [comment]
Does Travis work without github? If the upload filter are implemented the way they are planned it could mean, that github is not an option anymore to host the repos.

Putting that aside, IIRC I once tried some time back and failed because I did not understand what needed to be setup in particular. The documentation lacked the key stuff for me back then and I lost interest.

**Comment by Rudloff** [comment]
Travis only works with GitHub. I you host the code elsewhere, there are alternatives like [Jenkins](https://jenkins.io/) (works with any Git repository) or [Gitlab CI](https://about.gitlab.com/features/gitlab-ci-cd/) (if the code is hosted on Gitlab).

Once you have a `.travis.yml` file in your repository, enabling Travis is pretty straightforward. You just need to: 
1. Create a Travis account.
1. Link it with you GitHub account.
1. Enable the repository in Travis console.
Travis then takes care of setting up the correct post-push hooks on GitHub.

**Comment by tobiasd** [comment]
> Travis only works with GitHub. I you host the code elsewhere, there
> are alternatives like [Jenkins](https://jenkins.io/) (works with any
> Git repository) or [Gitlab CI]
> (https://about.gitlab.com/features/gitlab-ci-cd/) (if the code is
> hosted on Gitlab).

Sounds like Jenkins is better then, as it does not force one to use a specific service.

> Once you have a `.travis.yml` file in your repository, enabling
> Travis is pretty straightforward. You just need to: 

Maybe that was the problem then. That I could not figure out how to fill the yaml file with the needed information. But I don't really remember ;-)

**Comment by Rudloff** [comment]
Jenkins is a self-hosted tool so you have to host it on your server. If someone in the Friendica team has time to do this, I would be totally OK with using it but it is a lot more work than creating a Travis account.

**Comment by tobiasd** [comment]
Ah, I see. I though Jenkins was a local program not some web-app. Then I'll have a look for Travis, now that you provided some config file. And should we have to move away from github we can investigate further.

**Comment by Rudloff** [comment]
Another solution is to have a pre-commit [hook](https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks) that runs phpunit locally before each commit but it can be annoying to have to wait for the tests to complete before you can commit so it is easier to run the tests on a server.

**Comment by tobiasd** [comment]
Travis needs to be setup with the friendica account right? Not my private one.

**Comment by Rudloff** [comment]
It depends on what rights your account has; it needs an account that can create new webhooks for the repository.

**Comment by tobiasd** [comment]
Could we add the phpunit tests to the console @MrPetovan ?

**Comment by tobiasd** [comment]
So, now we wait for Travis to pick up a new  commit/PR or do I have to configure something more then activating the repository

**Comment by Rudloff** [comment]
It seems to be correctly enabled :+1: Now it will run the tests for each new commit or pull request (and display an error if the tests fail).

**Comment by tobiasd** [comment]
Mmh... looks like it does not work anymore. At least there is no feedback in the github UI.

**Comment by annando** [comment]
Yeah, it doesn't work. My PR I just submitted failed the check for all PHP versions except 5.6

**Comment by tobiasd** [comment]
I think it is working now. From 5.6 to 7 the phpuni classes changed a bit.

**Pull request merged**
