### PR TITLE
Wrap each addon settings form in their own form tag

### LINKED ISSUE #10314: Cat Avatar Generator usable for administrators only
- [ x ] I have searched open and closed issues for duplicates

### Bug Description

User can not generate random cat, only as admin the function works. I have also tried it on another instance there I have the same problem.

### Steps to Reproduce

1.  enable Cat Avatar Generator - 1.1
2.  got to Settings -> Addons -> Cat Profile Picture Settings
3.  click on random cat

Actual Result:

No error is displayed, not even in the console

Expected Result:

When you click on the button a new cat should appear

### Platform Info

Friendica Version:

Friendica Source: 'Siberian Iris' 2021.04 - 1413

PHP version: 7.4.18

SQL version: 10.5.10-MariaDB-1:10.5.10+maria~buster

### LINKED ISSUE #10439: Side-Effects at Addon settings page
- [x] I have searched open and closed issues for duplicates

### Bug Description

Based on https://github.com/friendica/friendica/issues/10314#issuecomment-869060328

If one addon is using a required field, every other setting in the addon page depends on this required field.
This is a design flaw inside the addon settings page, because we're using one form for the whole setting page instead, which causes this effect.

### Steps to Reproduce

1.  Activate Cat Avatar
2.  Before https://github.com/friendica/friendica-addons/pull/1140 - Activate SecureMail
3.  Got to Settings > Addon and try to recreate a cat avatar

Actual Result:

The button is blocked because of the required field at Secure Mail

Expected Result:

Each section should have it's own fields and therefore one Addon setting shouldn't harm another addon setting

### Screenshots

grafik

### Platform Info

Friendica Version: 2021.06-tc

Friendica Source: git

PHP version: php7.5

SQL version:

### PR DESCRIPTION
**Pull request by MrPetovan**
- The single form tag was preventing a given addon settings to be saved if another addon had an empty required field.
- Instead of concatenating the addon form HTML through `Hook::callAll`, we loop manually through the hooks, appending the HTML snippets to an array.

Depends on https://github.com/friendica/friendica-addons/pull/1141, please merge the addon PR first.

Closes #10314
Closes #10439

### CODE REVIEW

**Comment by tobiasd** [comment]
After merging this, I have **no addon settings** at all on my node. All themes are affected. Cleaning the SMARTY3 cache did not help.

In the PHP error log I see

```
PHP Notice:  Trying to access array offset on value of type null in /mod/settings.php on line 509
```

**Comment by tobiasd** [comment]
In the HTML source of the addon settings page I only see the wrapping HTML blocks

```
<form action="settings/addon" method="post" autocomplete="off">
	<input type="hidden" name="form_security_token" value="123456789">
	
</form>
```

**Comment by MrPetovan** [comment]
@tobiasd It looks like the `select()` on line 507 returns `false` when it really shouldn't. Can you test directly its return value?

**Comment by tobiasd** [comment]
The _old_ ``SELECT * FROM `hook` WHERE `hook` = 'addon_settings';`` is returning the expected results in the MySQL console I think. It lists 8 addons that look like the once I have enabled with user settings.

**Comment by MrPetovan** [comment]
It's odd that it's working on other people's node but not yours, so I'd be really curious to test the exact statement on your node.

**Comment by tobiasd** [comment]
So, what would be _the exact statement_ be? Tell me and I'll throw it into the MariaDB console.

**Comment by MrPetovan** [comment]
I meant the PHP statement `DI::dba()->select('hook', ['file', 'function'], ['hook' => 'addon_settings'])`, but the generated SQL statement should be ``SELECT `file`, `function` FROM `hook` WHERE `hook` = 'addon_settings'``.

**Comment by tobiasd** [comment]
That yields to the same listing of addons.

**Comment by MrPetovan** [comment]
Is the blank display systematic? If so you might have to dig into the log for SQL errors.

**Comment by tobiasd** [comment]
It is systematic in that all users are affected yes. But the display is not blank - the Friendica UI around the listing is there. It is "just" the missing listing of the addons.

The MySQL error log is empty. I've increased the Friendica log level, but it looks like the log for the time when I visit the settings page does not hold any relevant information.

I have disabled all the addons that are returned by the query. From my understanding now there should be the info that no addons are configurable by the user right? This is not the case.

**Comment by MrPetovan** [comment]
Disabling the addons won't change anything, the PHP statement isn't returning an expected array so the `foreach` runs once with a `null` value no matter the contents of the `hook` table. I'm still puzzled as of why only your node (so far) is stumbling on this basic select statement.

Thanks for looking in the log, we still need to figure out the actual return value of the PHP statement.

**Comment by AlfredSK** [comment]
> I'm still puzzled as of why only your node (so far)

I have checked it here. It looks like expected.

**Comment by tobiasd** [comment]
A `print_r` around the `DBA->select` yields

```mysqli_stmt Object
(
    [affected_rows] => 8
    [insert_id] => 0
    [num_rows] => 8
    [param_count] => 1
    [field_count] => 2
    [errno] => 0
    [error] => 
    [error_list] => Array
        (
        )

    [sqlstate] => 00000
    [id] => 108435
)```

And for those 8 rows the HTML form blocks are then inserted. But the `hook` information remains empty.

**Comment by tobiasd** [comment]
```print_r(q("SELECT `file`, `function` FROM `hook` WHERE `hook` = 'addon_settings'"))```

gives the expected array.

**Comment by MrPetovan** [comment]
Thank you, it looks like I should have used `selectToArray()` instead of `select()`, but I'm utterly puzzled about why it works for several nodes including mine and @AlfredSK 's but not yours.

**Comment by tobiasd** [comment]
Indeed, with `selectToArray` I see the correct listing of the addon forms. And the settings seem to work (I can save changes)

**Pull request merged**
