### PR TITLE
Fix for issue #13710 - [frio] long handles prevent a clean display of common contacts

### LINKED ISSUE #13710: [frio] Long handles prevent a clean display of common contacts
- [x] I have searched open and closed issues for duplicates

### Bug Description
If two profiles are on the same server, an icon list of the shared contacts is displayed when the URL https://domain.ltd/profile/[USERNAME]/conversations is called. The name of the user is listed under the UserIcon. 
For handles with more than 10-12 characters, the adjacent UserIcon is moved. 
The result is an unsightly patchwork of differently arranged icons.

In my opinion, the name is not relevant. This is already displayed as a mouseover. The name of the user under the UserIcon should therefore be removed

Actual Result:

The icons are arranged inconsistently

Expected Result:

The icons are displayed uniformly. The name of the user is no longer displayed.

### Platform Info

Friendica Version: 2023.09-rc

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

### PR DESCRIPTION
**Pull request by Raroun**
This fixes Issue #13710.

I first tried to display the username beside the user-picture, but that looked strange.
So i used the command display-methid with the username under the user-picture realized with a css grid.
Tested on vier and frio, Desktop and mobile.

before:
image

after:
image

### CODE REVIEW

**Comment by Raroun** [comment]
i adjusted the background color to white, which looks better in my oppinion but i can remove the white background if unwanted.

**Comment by annando** [comment]
Concerning the background for the common contacts, please have got a look at how the background for the birthday reminders is set and replicate it. Simply setting it to white would cause a problem with other colour themes.

**Comment by Raroun** [comment]
Thanks for the advise! :)

**Comment by annando** [comment]
Have got a look at the section `/* Birthday and Event Reminders  */` in the `style.css`. I guess it would be the best to add your element there.
image

Update: it would be totally great, if you could make it collapsible just like the birthday reminder. This would be some optical consistency.

**Comment by Raroun** [comment]
frio:
image
-----------
image

-----------

vier:
image
-----------
image

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
