### PR TITLE
Deprecated profile fields cleanup

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #7817 

What made this task tricky is that we record remote contacts gender and about field, but we don't have them for local profiles anymore.

Don't forget about https://github.com/friendica/friendica-addons/pull/951

### CODE REVIEW

**Comment by nupplaphil** [comment]
There are various predefined gender fields, so in the future, everybody is able to create an own gender field with his own value, isn't it? Just to be sure..

Sadly we don't support localization for dynamic values, so we could provide localization for custom profile fields... Maybe a feature request for the next release? ;)

**Comment by MrPetovan** [comment]
I don't think I got how you wanted to localize a free-form field.

**Comment by nupplaphil** [comment]
you're probably right ..

**Comment by MrPetovan** [comment]
Don't forget about https://github.com/friendica/friendica-addons/pull/951

**Pull request merged**
