### PR TITLE
FR, RU translation updates

### PR DESCRIPTION
**Pull request by tobiasd**

### CODE REVIEW

**Comment by SpcCw** [comment]
Hi, @tobiasd!

I don't want to create another issue too early so I decided to ask first. I am getting non-translated notifications again and am not sure if something is wrong with my end or translation. After I saw this PR I updated the code, cleared cache and even though I see some newly translated parts I recently added I still get some notifications untranslated:

image

However if I check messages.po file I see strings in place! For example both "commented in the thread" strings are translated both in git and the file on my server.

I tried creating completely new post and still new notifications come untranslated. Do I need to kick some tires or check something else?

**Comment by tobiasd** [comment]
@annando are the notification strings cached?

**Comment by SpcCw** [comment]
Seems to be so. Clearing browser history, temp files on server, etc didn't help but I forgot about Friendica internal cache.

After running `console cache clear` it works as expected. I guess I need to add this to my Friendica update procedure.

Thanks for the pointers :)

**Comment by tobiasd** [comment]
Glad to hear that!

**Comment by SpcCw** [comment]
Turns out there indeed are some glitches with caching so I created an issue https://github.com/friendica/friendica/issues/11594

**Pull request merged**
