### PR TITLE
 Fix for post update 

### PR DESCRIPTION
**Pull request by annando**
P.S.: Something at my git is wrong. I don't know why all commits since July 18th are listed here. Can someone tell me how to fix this?

### CODE REVIEW

**Comment by MrPetovan** [comment]
What are the commits that should actually be in this PR?

Can you try rebasing your branch `postupdate2` against `upstream/develop`:

```git rebase upstream/develop postupdate2```

**Comment by annando** [comment]
Now I got stuck at:
```
Wende an: Removed some more type
Keine Änderungen - haben Sie vergessen 'git add' zu benutzen?
Wenn keine Änderungen mehr zum Commit vorzumerken sind, könnten
diese bereits anderweitig eingefügt worden sein; Sie könnten diesen Patch
auslassen.

Wenn Sie das Problem aufgelöst haben, führen Sie "git rebase --continue" aus.
Falls Sie diesen Patch auslassen möchten, führen Sie stattdessen "git rebase --skip" aus.
Um den ursprünglichen Branch wiederherzustellen und den Rebase abzubrechen,
führen Sie "git rebase --abort" aus.
```

I don't understand this f*** git.

**Comment by annando** [comment]
I got masses of conflicts. After solving them I got masses of conflicts. After this I got masses of conflicts, ...

I'm giving up with this sh**.

Is there something else I can do?

**Comment by MrPetovan** [comment]
Once you created your new branch, `git cherry-pick <commit-id>`.

**Comment by annando** [comment]
There is now this PR: https://github.com/friendica/friendica/pull/5516

This seems to be the result of my "rebase" attempt. And don't ask me why there are so many commits in it. Have I told already that I hate git?

**Comment by MrPetovan** [comment]
Thanks to squash & merge this will only be a single commit in the develop branch history.

**Comment by annando** [comment]
Can it be that this "squash & merge" started 11 days ago? my "develop" branch still shows additional commits when I try a PR from "develop" to "develop".

**Comment by MrPetovan** [comment]
Did you try

`git fetch —all`
`git rebase upstream/develop develop`
`git push —force-with-lease`

?

**Comment by annando** [comment]
No. I didn't knew these commands.

**Comment by annando** [comment]
```
$ git fetch —all
fatal: '—all' does not appear to be a git repository
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
$  git rebase upstream/develop develop
Aktueller Branch develop ist auf dem neuesten Stand.
ike@manitu:~/pirati.ca/htdocs$  git push —force-with-lease
fatal: '—force-with-lease' does not appear to be a git repository
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
$ 
```

**Comment by MrPetovan** [comment]
The leading — character should be replaced with two minys `-` signs. iOS automatically replaces two consecutive minus signs with a larger bar.

**Comment by annando** [comment]
I now tried these commands. They don't change anything. I don't know if accepting https://github.com/friendica/friendica/pull/5518 will solve the problem, but I hope.

**Pull request merged**
