### PR TITLE
Preload adapter fix

### PR DESCRIPTION
**Pull request by nupplaphil**
Fixing https://github.com/friendica/friendica/pull/6682#issuecomment-464702823

The preload adapter for PConfig used a "whole" boolean flag for every user. So let's say user with "0" was loaded, a load for "1" was impossible.

I changed it to a bool-array for each uid and now it worked.

Bugfix #6641 

Tested both JIT and Preload on my node.

### CODE REVIEW

**Comment by AlfredSK** [comment]
Question: After switching back from headless state to develop I have an entry for the base path in my admin panel now. That was empty before.
Can I leave the path in that field or should I remove it again?

The description of the base path field:
> If the system cannot detect the correct path to your installation, enter the correct path here. This setting should only be set if you are using a restricted system and symbolic links to your webroot.

"setting should only be set if..." - I don't use symbolic links to my webroot and I don't have a restricted system. So, what is the recommended setting?

Thank you.

**Comment by MrPetovan** [comment]
This entry is coincidentally generated by the App, it is shown because the form calls `Configuration->get('system', 'basepath')`, but this config key is artificially set in `ConfigCacheLoader.php:41` which isn't ideal. I'm glad it is working now, but I wish this manual call wasn't necessary.

**Comment by AlfredSK** [comment]
Thanks. So, I leave it like it is now?

**Comment by MrPetovan** [comment]
If you empty it and save it, it's going to show up again on page reload. Just leave it as is if it isn't the wrong path.

**Comment by nupplaphil** [comment]
Ahh, damn.. There's this circle reference between the DB and the Cache which is really hard to handle.. I'll rethink about it..

**Comment by AlfredSK** [comment]
Take your time. Server is working at the moment. No need to hurry.

**Comment by tobiasd** [comment]
Could you please update the help text in the admin page accordingly. As a general rule we should establish that the developer who changes such behaviour should also update these help texts accordingly to reflect the changes in behaviour of the system. And yes, I know, developers don't touch documentation, they avoid it with a passion.

**Comment by nupplaphil** [comment]
I think I'll rewrite the Config/-Adapter just a little bit so it won't be necessary to adapt the admin help text.

**Pull request merged**
