### PR TITLE
frio: some hover-card css fixes

### PR DESCRIPTION
**Pull request by rabuzarus**
The color handling of hover-card links wasn't unique.

This should fix this. It's a little bit hacky. I had to insert some hover-card overwriting in the style.css (but it should go into hovercard.css). But since personal color variables are only available for style.css I didn't found any other solution.

If anyone finds a better solution he/she is very welcome to change this.

### CODE REVIEW

**Comment by tobiasd** [comment]
you can use a style.php file (PCSS it's called I think) which loads the style.css file and emit it but can do some conditional changes. I'm using it in [clean](https://bitbucket.org/tobiasd/clean/src/9fcba68f253b8752cfeb04c8c1f00e2076ee5a12/style.php?at=default) for user changes.

**Comment by rabuzarus** [comment]
@tobiasd 
I already make heavy use of style.php. Frio style.php gives the functionality to inject personal color variables into style.css. Sure I could extend it to other css files. But I didn't found a good solution so the style.php wouldn't get bloated and messy

**Comment by tobiasd** [comment]
The other way to reorganize would be, prepare the CSS file with lessc, compile it with changes and then have the style.php overwriting the values with user settings. But why not allow theme devs to overwrite CSS files in general with PCSS files, not only for the style.css?

**Comment by rabuzarus** [comment]
> But why not allow theme devs to overwrite CSS files in general with PCSS files,

Maybe it is possible. Here it's the way how it's done in frio https://github.com/friendica/friendica/blob/develop/view/theme/frio/style.php#L131

We would to get a list of all css files which belongs to to the theme (something like all files in `THEMENAME/css/`). But we would need to have the possibility to have something like an ordered list (because the order does have impact of how styles are applied or overwritten).

Additional we could not cache (local) the css files  because they css files don't change but the injected variables.

I won't say it's not possible but it will not that easy. It have to be well thought and planed

**Comment by tobiasd** [comment]
Maybe I understood the PCSS stuff wrong, but I thought when the CSS file is loaded, instead the PHP file gets interpreted. So the default.php lays down the ground of the theme, calling for `style.css` and `hcard.css` for example and in this order. Then `style.php` should be interpreted first and `hcard.php` second. Each starting with reading in the corresponding CSS file and then applying dynamic changes for the users settings. So if the order is correct for the unmodified CSS files, it should be correct for the modifies one as well.

**Comment by rabuzarus** [comment]
@tobiasd I don't know. Do you know where/when this happen? Can link to some piece of code?

**Comment by tobiasd** [comment]
you mean the place in the code where the PCSS stuff happens?

**Comment by rabuzarus** [comment]
yes

**Comment by tobiasd** [comment]
not really, in boot.php are most of the references to style.css and [here](https://github.com/friendica/friendica/blob/develop/boot.php#L1824) is the only mention of pcss itself.

**Comment by rabuzarus** [comment]
I don't find much more than your link and `mod/view.php` and as far as I understand it this only works with style.php and style.css (style.pcss) and not with other css files.

So from my understand we only could integrate the other css files in the style.pcss (through the style.php). But this would mean complex debugging. I also don't really know how to solve the problem of caching.

**Pull request merged**
