### PR TITLE
Don't fail during installation because of a missing theme configuration

### PR DESCRIPTION
**Pull request by annando**
Fixes https://github.com/friendica/friendica/issues/4956

### CODE REVIEW

**Comment by tobiasd** [comment]
Have you made a test installation? If not I'll test it later.

**Comment by annando** [comment]
I did, but a second view is of course always better.

**Comment by tobiasd** [comment]
> I did, but a second view is of course always better.

Ok, what system (Linux distro) had you tested?

**Comment by annando** [comment]
Debian.

**Comment by MrPetovan** [comment]
Not bad, I didn't think this could have worked.

**Comment by annando** [comment]
Yeah, this had been really easy.

**Comment by tobiasd** [comment]
I'll test it with Debian Jessie (PHP 5.6) and Ubuntu 18.04 (PHP 7.2)

**Pull request merged**
