### PR TITLE
Updated database.sql header with new version name

### PR DESCRIPTION
**Pull request by MrPetovan**

### CODE REVIEW

**Comment by MrPetovan** [comment]
Ah, damn, the release is already tagged...

**Comment by annando** [comment]
The version number in the file doesn't really matter. It is mostly not on the right version. Only the structure has to fit.

**Comment by MrPetovan** [comment]
I know, it was just a cosmetic change, but since the release is already tagged, we would need to issue a new release to make it public.

**Comment by annando** [comment]
I wanted to ask in this second, what to do, then you closed it :-)

**Comment by MrPetovan** [comment]
It's too much trouble for such an insignificant cosmetic issue. Otherwise I read your mind.

**Pull request closed without merging**
