### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by jlamothe**
s/peiple/people/

### CODE REVIEW

**Comment by MrPetovan** [comment]
Thank you for your work! However for small typos in long-standing translations strings, we prefer fixing it in the `en-US` translation in Transifex not to force tens of translators for other languages to have to translate the fixed version of the translation string.

**Comment by MrPetovan** [comment]
You can see here that it has already been fixed in the American English translation:
https://github.com/friendica/friendica/blob/268593a97922bfecec6b147a93cd67dd96d96020/view/lang/en-us/messages.po#L1213
This means that "peiple" won't appear unless the string hasn't been translated at all for the current language.

**Comment by jlamothe** [comment]
I don't use en_US.  I use en_CA with a fallback to en-GB (I believe).  Would it he reasonable to resubmit with at least the en_GB fixed?

**Comment by MrPetovan** [comment]
Sure, the only way to do this is to go over at Transifex (https://transifex.com/friendica/friendica) and translate this string in `en_CA` and `en_GB` if they aren't already.

If we accept a PR modifiying the translation files, they will be overwritten the next time we export the translations from Transifex.

**Comment by jlamothe** [comment]
I've signed up for Transifex, and am trying to figure out the interface.  It's very non-intuitive.  :(

**Comment by jlamothe** [comment]
...though if I'm reading it right, it *looks* like this fixes it?
https://app.transifex.com/Friendica/friendica/viewstrings/#en_GB/messagespo/456037200?q=text%3Apeiple

**Comment by MrPetovan** [comment]
Thank you for checking out Transifex, it takes some used-to indeed. You're also correct the typo has been fixed in `en_GB`. For a more formal proof, see this extract of the `en_GB` PO file:
https://github.com/friendica/friendica/blob/44344af0550c883c1bd5f04d08d1b3928e9ea51a/view/lang/en-gb/messages.po#L1208-L1213

The `msgid` and `msig_plural` are used to identify the translation string, and the `msgstr` array contains the actual translations.

**Comment by jlamothe** [comment]
In that case, I shall happily close my PR.  :)

**Pull request closed without merging**
