### PR TITLE
Ensure public forum posts are public

### PR DESCRIPTION
**Pull request by annando**
Fixes https://forum.friendi.ca/display/0b6b25a8-2160-cbb6-6658-d40821128500

### CODE REVIEW

**Comment by AlfredSK** [comment]
I have implemented the changes manually on my nodes and the Community Forum node. 

Indeed, when I create a forum post via forum widget the permissions look like this:

grafik

**Comment by AlfredSK** [comment]
Also, test successful. The fix seems to work. Thanks!

**Comment by annando** [comment]
@AlfredSK The change is at a later stage, when the post is sent. This PR should ensure that the system now works as expected. At a later time we can make it more beautiful. But my current time for the next few days is slightly limited.

**Comment by AlfredSK** [comment]
Yep. See my other comment. :-)

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
