### PR TITLE
Bugfix to PR 4046: Repaired query

### PR DESCRIPTION
**Pull request by annando**
This repairs the query in the function ```getByContactIdForUserId``` of PR https://github.com/friendica/friendica/pull/4046

### CODE REVIEW

**Comment by MrPetovan** [comment]
Ok, the reason why I changed the query is because I want to get rid of the `uid` column in the `group_member` table. It's a redundant piece of information present both in the `group` table and the `contact` table each row is referring to.

This is valid but it could even be simplified by getting rid of the `$uid` function parameter, which reduces the function to `getByContactId`.

**Comment by annando** [comment]
Currently the database contains these values, so we can use it, I think.

But I mostly changed this query, since it had generated an SQL error and additionally had returned the wrong parameter.

**Comment by MrPetovan** [comment]
I know why you changed it, I'm just saying it can be changed further.

**Comment by annando** [comment]
Yeah there is much where we can simplify the database structure.

**Comment by annando** [comment]
BTW: Additionally we are having several unneeded "id" fields (as auto increment) in many tables.

**Comment by MrPetovan** [comment]
Indeed, I'm not done with my database assessment, but it definitely is on the list.

**Comment by annando** [comment]
This is complicated since we have to replace the primary fields which will sometimes make problems since we will have duplicated data - and Oracle's MySQL is a little bit hypersensitive concerning this. (MariaDB is more insensitive)

**Comment by MrPetovan** [comment]
Duly noted, we'll have to dedupe the tables first, then move the primary key, then remove the columns.

**Comment by annando** [comment]
We already are having a function that replaces duplicates - but it does work only well with older MySQL and MariaDB.

**Pull request merged**
