### PR TITLE
Move mod/notice to src/Module/Notice

### PR DESCRIPTION
**Pull request by nupplaphil**
Part of #4090 

The code works "as designed", but I don't know, if it is really used. Because all it does is redirecting to `display/$nick/$itemId`

I don't find a valid path in display for such pattern.

### CODE REVIEW

**Comment by MrPetovan** [comment]
You're right, it doesn't exist anymore, it should be `/display/{item_guid}`.

**Comment by MrPetovan** [comment]
Conflict.

**Comment by annando** [comment]
I just had a quick check. It seems as if this endpoint isn't used at all. We don't refer to it in the OStatus part, nor do I see any hits in the access log of my servers. We possibly should get rid of it.

**Comment by nupplaphil** [comment]
Removed with #7172

**Pull request merged**
