### PR TITLE
Plugins to src

### PR DESCRIPTION
**Pull request by zeroadam**
New PR from github interface

### CODE REVIEW

**Comment by zeroadam** [comment]
@MrPetovan did that help?

**Comment by MrPetovan** [comment]
Yep, much better!

**Comment by MrPetovan** [comment]
Did you run `util/typo.php` ?

**Comment by zeroadam** [comment]
Yes, I had run it before each of the last few review changes.

**Comment by MrPetovan** [comment]
I see `plugin` instances in `mod/admin.php` and `mod/settings.php`, in `view/templates/admin/`, in `src/Core/Addon.php`, in the comment of the `addon` table, in comments in theme CSS ( `/* Plugin settings */`).

**Comment by zeroadam** [comment]
The references in mod/admin mod/settings and Core/Addons are because all of the function names in the most all of the addons are still named this way.

**Comment by MrPetovan** [comment]
I left a similar comment on your addon PR 😄

**Comment by MrPetovan** [comment]
You can mention the PR to be merged at the same time as this one.

**Comment by zeroadam** [comment]
I pulled the friendica-addon PR and am doing so again here. To rebase on the current develop and after the vendor folder was dropped from git.

**Pull request closed without merging**
