### PR TITLE
Zot was never really supported, so it is now removed completely

### PR DESCRIPTION
**Pull request by annando**
This is one part of issue https://github.com/friendica/friendica/issues/3995

### CODE REVIEW

**Comment by annando** [comment]
I would like to treat it like other currently unsupported networks.

**Comment by annando** [comment]
"Zot" is the protocol that is used for Hubzilla. Maybe at some time we will support it as well. So I want to keep it as a placeholder. I just wanted to get rid of half working code.

**Comment by annando** [comment]
I removed the ```NETWORK_MAIL2``` as well, since this was a coding that was never finished as well.

**Comment by MrPetovan** [comment]
> "Zot" is the protocol that is used for Hubzilla. Maybe at some time we will support it as well. So I want to keep it as a placeholder. I just wanted to get rid of half working code.

In that case, can you please mention next to the constant that it is unsupported at the moment?

**Comment by annando** [comment]
Okay, I also renamed some network links.

**Pull request merged**
