### PR TITLE
Don't create lock files if the process is called from the poller

### PR DESCRIPTION
**Pull request by annando**
The lock files were created in the past to prevent that multiple instances of the same process ran at the same time. This check isn't needed when the worker is used, since the worker does this check on its own.

Accidentally there is a little fix for the OStatus thread completion included.

### CODE REVIEW

**Comment by rabuzarus** [comment]
since it is nearly the same code on different places, wouldn't it be better to have a own function for this?

**Comment by annando** [comment]
Yeah, it would. Since it is old code that I only "enhanced" with a new condition I haven't moved it to an own function.

**Comment by annando** [comment]
@rabuzarus Is it okay now?

**Comment by rabuzarus** [comment]
Seems  OK to me  ;-)

I have a question out of interest.
Why does it make sense to have the both functions/methods in the App class and not in an other class? One which would deal with processes and system balance

**Comment by annando** [comment]
I guess it could be fine to have such a class. I thought about it yesterday as well. But I haven't done it.

**Pull request merged**
