### PR TITLE
Add Arguments & Module class (again)

### PR DESCRIPTION
**Pull request by nupplaphil**
Functional version of #7500  ...
Sorry @MrPetovan I oversaw the removage of this method ... Seems like the daemon was still running on the old code .. Now I double checked the log on "debug" logelevel and got log-entries about daemon/worker -.-*

### CODE REVIEW

**Comment by MrPetovan** [comment]
You gotta be careful when you remove any method. It isn't like a typo that can easily be fixed, there was no easily accessible alternative in the case that was errorring.

Again, please leave any method you want to remove until the next release, just mark it as deprecated, and then we'll come around to remove it for the following release.

**Comment by MrPetovan** [comment]
Tests are still failing.

**Comment by nupplaphil** [comment]
.. Travis seems like to changed the way 7.3 is loaded so redis test fail now.. Strange.. I'll investigate it -.-

**Comment by nupplaphil** [comment]
Found something, closing till fixed

**Comment by MrPetovan** [comment]
All good now?

**Comment by nupplaphil** [comment]
Yes :)

**Comment by JeroenED** [comment]
@nupplaphil The body-tag in the frio theme currently has no module and appears as mod- without anything.

    <body id="top" class="mod- is-not-singleuser desktop-view">

**Comment by MrPetovan** [comment]
Thanks for the report!

**Comment by nupplaphil** [comment]
Will fix it :) thanks for the report

**Pull request merged**
