### PR TITLE
 Add relationship filter to api_friends_ids and api_followers_ids

### PR DESCRIPTION
**Pull request by MrPetovan**
Addresses #7920

Untested but it should work.

### CODE REVIEW

**Comment by annando** [comment]
You can test it directly in the web browser by entering the API path.

**Comment by MrPetovan** [comment]
I know how to test my code when I can update it on my server. Currently I can't, hence the "untested".

**Comment by annando** [comment]
The test is failing at the moment.

**Comment by MrPetovan** [comment]
Indeed.

**Pull request merged**
