### PR TITLE
DE, RU translation updates

### PR DESCRIPTION
**Pull request by tobiasd**
THX to Alexander An the RU translation saw some more updates :)

### CODE REVIEW

**Comment by MrPetovan** [comment]
Translation question: I've recently translated a bunch of strings in French, but I haven't seen them come up in a PR so far, do I need to do anything else for them to be included in your workflow?

**Comment by tobiasd** [comment]
Can you tell me when "recently" was? Could well be that I've overlooked the changes at the Transifex timeline of the project. But I don't see updates to the French translation within the last 4 month on their summary.

PR with the French translation is done #10703

**Comment by SpcCw** [comment]
Added some more RU translation on new scheduled posts function :)

**Comment by tobiasd** [comment]
I'll push them before the weekend, having a failing HDD on my home computer just delays things a bit ;-)

**Pull request merged**
