### PR TITLE
Process unprocessed queue entries in a separate worker process

### PR DESCRIPTION
**Pull request by annando**
The processing of unprocessed queue entries can take some time. So it now has got its own worker process.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Do we ever process already processed entries? Wondering about the repetition in « process unprocessed »

**Comment by annando** [comment]
I hadn't found any better word for processing queue entries that aren't processed by now. These are all entries that aren't processed at the first time.

**Comment by MrPetovan** [comment]
So, failed entries?

**Comment by annando** [comment]
Mostly these are entries that couldn't be processed the first time, since they relied upon other posts (their parents) that couldn't be fetched at that point in time.

**Pull request merged**
