### PR TITLE
q() may return FALSE on error, causing count() to issue E_WARNING

### PR DESCRIPTION
**Pull request by Quix0r**
If q() returns FALSE (due to an error/crashed database/what ever reason) mostly the value is directly handled over to count() which causes a E_WARNING. My commits prevent this from happening by checking with is_array($foo) if $foo is really an array and then it is safe to use count($foo) on it.

I have encapsulated this into a new function is_filled_array() to reduce duplicating code (DRY).

### CODE REVIEW

**Comment by fabrixxm** [comment]
that's nice. have you replaced all the `count()`s on a query result?

**Comment by Quix0r** [comment]
Not all is replaced. I now look more deeper into it and add more commits to this ticket.

**Comment by fabrixxm** [comment]
:+1:

**Comment by annando** [comment]
I would suggest to not use "count" at all to check whether a query had a result. We mostly simply check like: ````if ($q) ... ```` that should be enough, shouldn't it?

**Comment by Quix0r** [comment]
@annando not always:
`$foo = q("SELECT bla FROM foo");
if (!$foo)
  killme();`

It looks "okay", but it is not so clean, better is:
`$foo = q("SELECT bla FROM foo");
if (!is_filled_array($foo))
  killme();`

**Comment by Quix0r** [comment]
`if ($r)` only tests on the variable, but not if it is an array and filled with at least one entry.

**Comment by annando** [comment]
The "q" function should only be able to return an array or a boolean parameter. I don't see this "if ($q)" as some kind of "ugly code". I see it differently. I like to simplify the code. Means: If we move the "is_filled_array" check into the dba.php then we really don't have to do it in hundreds of places in the code. (And we are safe that the function really only returns a valid data type)

And I'm the kind of programmer who likes to write functions for every action that is called multiple times at different places.

**Comment by Quix0r** [comment]
Still you may want to use is_filled_array() in many places where you need to know if there are entries or not.

Adding it to q() may also help, sure.

**Comment by redmatrix** [comment]
There was a long discussion about this in redmatrix (now hubzilla) in 2012. We now use 

if($r)

globally. This avoids an extra check for a successful call with no returned elements before running through a foreach loop (for instance). One can provide more specific tests to see if it was successful but didn't return anything - however we only found one place in the code where this distinction was necessary. As a result this makes the code and flow much cleaner. A query with a SELECT either returns results or not. Regardless of the reason why, we don't usually require any more detail than this at the application level. A SELECT (or indeed any database query) that returned false will have logged an error and reason with the appropriate alarms at the DB layer.

**Comment by Quix0r** [comment]
Okay, so maybe refacture all finding towards this? We need a plan here. :-)

**Comment by Quix0r** [comment]
The following code causes a E_WARNING, if $r somehow is not an array:
````
  if(count($r)) {
    foreach($r as $rr){
````
Now you want ```if ($r)``` here?! Then the E_WARNING remains (because it is simply no clear code, period).

**Comment by Quix0r** [comment]
Just try this:
````
<?php
$r = FALSE;
if (count($r)) {
print 'BAD!' . PHP_EOL;
} else {
print 'GOOD!' . PHP_EOL;
}
````
It will output "BAD!"

**Comment by annando** [comment]
I'm not so happy about this - one reason is that the function name is really long. We have to use it really often, so it should be easy to type.

Since we are switching to static classes instead of the old way, I would suggest having something like this:

````
$r = dba::q("SELECT `blah` FROM `blubb` WHERE `ping` = '%s'", dba::esc($value));
if (dba::is_result($r)) {
   do_something();
}
````

What do you think?

**Comment by Quix0r** [comment]
I like that idea more. Okay, I rewrite my patch.

**Comment by Quix0r** [comment]
Hmm, I duplicated it into both dba classes. How about a class AbstractDba which is expanded by both classes to avoid duplicate code? DRY! :-)

**Comment by Quix0r** [comment]
Opps, all commits show up here. :-( F**k

**Comment by annando** [comment]
The "dba_pdo.php" isn't in use at the moment since we had an strange issue with it in the past. It was planned to replace the dba.php - so there is much duplicated functionality. The new functionality was planned to be more flexible and to support multiple database types in the future. I wouldn't like to throw away that code.

I'm totally unsure what to do.

**Comment by redmatrix** [comment]
> Oh, removing count() gives "GOOD!". Na, that is super-ugly code to me, I won't accept such crappy code in my projects, especially in my OOP-ed projects.

 As always, beauty is in the eye of the beholder. For some people, beauty and elegance is in clear logic and functional simplicity. No matter how much text and punctuation you add to this statement, ultimately you are making a database query where you expect a result set and determining if you have a populated result set. Nothing more. You are free to enumerate the distinction between an empty result set and a driver failure (boolean false) if the application requires this level of detail. But the result is the same - if there isn't a populated result set (for whatever reason), you can't stick it into a foreach loop. "if($results)" is the most elegant way in my opinion of expressing this statement.  

But this is no longer my project so the way forward needs to be determined to the community. We openly discussed this in a different community and I was on the other side, voting for something much like "is_filled_array($r)" and I was voted down by the rest of the community who preferred the simple elegance of "if($r)". My comments in this thread were intended to save you from rehashing the same arguments, but it appears you just have to have that discussion and take a vote and see who has the most allies. When you get to these kinds of semantic decisions, there is no right or wrong. The code and logic can be correct either way. You merely need to make a decision one way or another so you can carry on.

The original code "if(count($r))" is my fault and I take full responsibility. It is only a question of how best to fix it and move on.

**Comment by annando** [comment]
@Quix0r I would suggest the following: You could create a new file that contains the database class. It will then use the code in the dba.php or dba_pdo.php. In a later step we can add more and more functionality to this class.

**Comment by Quix0r** [comment]
I'm a bit confused? Maybe because of I have some very light cold (a bit dizzy) but maybe you can explain it more? Should I re-create the branch from scratch better? Now there are a lot other commits in.

**Comment by annando** [comment]
I don't see a problem in adding some more commits to this. I would suggest the following:

- create a file /include/db.php and add a static class "db" there
- this class contains the function "is_result"
- change the calls to "dba::" to "db::"

In the future we can then add more static functions to the class like "esc" (which would be a reworked version of the "dbesc" function) or "q" which would replace the function call "q".

I would like to replace the code in dba.php and dba_pdo.php somewhere in the future. In the moment we are rewriting many parts of the code to make it more readable and serviceable. I guess that there is much potential in the database class as well.

@rabuzarus @fabrixxm @tobiasd do you agree to make it that way?

**Comment by rabuzarus** [comment]
I agree with most of @annando points. But there is one point which I want to discuss.
Is the name "db" a really good decision for the class? I think the class name should be something with more than two letters to make it really unique and good searchable (sure we would use it very often and that's why it should be also short).

BTW: If someone wants to restructure the db part it's always worth to have a look at hubzilla code (To have something like dba_driver.php is interesting)

**Comment by annando** [comment]
We have so much database calls so I don't like to have it too long. And since you would search for "db::" to find class calls, you would find them easily, won't you?

**Comment by annando** [comment]
Concerning the different database drivers I guess at first we should make this "db" class as a kind of skeleton. After this we can think of working with inheritance to create database independent implementations - but I really would like to have function calls there that would replace typing in the database query. We could have a look at projects like MyBB for that.

**Comment by rabuzarus** [comment]
> We have so much database calls so I don't like to have it too long. And since you would search for "db::" to find class calls, you would find them easily, won't you?

I have thought about it. It wouldn't be a "NoGo" from my side and it's nothing I would like to struggle about. I really understand that we need something short because it would be used very often.

My only concerns are, that we could have some corner cases (in the future) where searching for `db::` wouldn't give all results and some really easy things (like renaming the class) would be a really big task (which otherwise could be done automatically in 10sec).
It's more like a gut feeling and the fear that I haven't thought about all the case where this could happen because they don't come to my mind at the present state of development.

**Comment by annando** [comment]
Which name would you suggest instead?

**Comment by rabuzarus** [comment]
something with 3 letters (`db` would be the first two).
I just did some searching through the code. Searching through /mod and /include gives no results for e.g. `dbm`, `dbx`, `dbj`, `dbi`, `dbk`, `dbt`, `dbr`, `dbw`, `dby` and `dbx`.
Maybe we can find a good explanation for what one of this last letters could stand for.
I'm not really creative but something like `dbm` = database methods :-)

**Comment by annando** [comment]
Three letters sound fine as well. So @Quix0r if you want to, you could start. Since @rabuzarus (our unofficial master of code quality) agreed to it, everything should be okay.

**Comment by annando** [comment]
@Quix0r How are your plans concerning this pull request? I just was thinking about some more changes to the database part. Currently the result set is packed into an array - which makes problems with lager result sets. We could however - additionally - use a way were we would return a class variable so that we needn't had to keep the whole result set in memory.

So it could be some kind like:

````
$result = dbm::qc("SELECT brownie FROM cookies WHERE content = '%s'", dbm:esc($content));
while ($row = $result->row()) {
  // Do some stuff
}
$result->close();
````

I would like to have some way where we could work nearly identically like before - but with reduced memory footprint.

**Comment by Quix0r** [comment]
Not much planed here. What if `$result` is a non-object because of an error in dbm:qc()? Then you will get such (ugly looking) error message. If you in addition suppress the error with @ then it becomes even more harder to debug.

And that is what I want to prevent, making code more ugly and harder to debug (= harder for developers to fix it).

**Comment by annando** [comment]
It was just a suggestion - I guess you can find a way to make it good readable and usable.

**Comment by annando** [comment]
What do we do with this pull request? I really like the idea of having a unified method to check if there is data. The only thing that bothers me is the code redundancy. We shouldn't have the same function in two places.

I suggest that we create a new static database class that can be extended in the future. At first it contains only this single function but later it should contain the query function and the whole other database stuff as well.

Like @rabuzarus suggested we could name it "dbm".

@Quix0r Would you like to make this change to the pull request? Otherwise I would suggest to accept the pull request and to let the changes applied to it in a following step. What do you mean?

**Comment by annando** [comment]
The pull request https://github.com/friendica/friendica/pull/2655 should fix this conflict.

**Comment by Quix0r** [comment]
Removed no longer needed branch.

**Pull request merged**
