### PR TITLE
[frio] Remove legacy schemes

### LINKED ISSUE #12420: Remove legacy schemes from Settings > Display > Theme customization > Color Scheme (Blue, Koyu-dark, Love-music, Plusminus, Red)
One aspect making user interaction with themes very hard is the overwhelming amount of schemes which are mostly not used.

The legacy schemes are not maintained or tested against. Removing them will help making theme settings more usable.

### LINKED ISSUE #13632: [Discussion] Default theme for new users
I seem to remember that the "Blue" theme was the first theme in Frio. Even today, the "Blue" theme is the default for new users when they create a new account. 
The admin of an instance has the option of specifying a different theme, but this is rarely used.

---

When I compare this theme "Blue" with other available trio themes, I immediately notice the low contrast between the background and the links. 

grafik

It takes a certain amount of concentration to distinguish the background from an embedded link, which I personally find very tiring.

I would therefore be interested to know whether it would not be time to offer a new or accentuated theme as standard for new users? My personal favourite is "Light accentuated".

Blue
Screenshot 2023-11-12 at 07-40-00 ˈloma Matthias ✔ @ ˈloma

Hell akzentuiert
Screenshot 2023-11-12 at 07-40-40 ˈloma Network

Dunkel akzentuiert
Screenshot 2023-11-12 at 07-41-10 ˈloma Network

Schwarz akzentuiert
Screenshot 2023-11-12 at 07-41-40 ˈloma Network
 
All of these current themes have a much better contrast distance between the background and a link. This makes reading in Friendica much more pleasant and less tiring.

### LINKED ISSUE #13947: Simplify Display Settings > Custom Theme Settings
https://github.com/friendica/friendica/issues/12420 follow-up

## Currently

- Select color scheme
   - Custom
   - Accented
       - Light (Accented)
       - Dark (Accented)
       - Black (Accented)
    - Legacy
        - Legacy Themes (to be removed as per https://github.com/friendica/friendica/issues/12420)

Select scheme accent

## Expected

- Appearance (replaces `Select color scheme`)
   - Light
   - Dark
   - Black
   - Custom

Accent color (replaces `Select scheme accent`)

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #12420 
Closes #13947
Closes #13632

image
image

### CODE REVIEW

**Comment by MrPetovan** [comment]
License check is failing because I changed the frio scheme files that never have a proper license header.

**Comment by MrPetovan** [comment]
Converted to draft to reinstate support for custom schemes.

**Comment by MrPetovan** [comment]
Custom scheme files support has been restored.

**Comment by foss-** [comment]
@haheute can you elaborate on your eyes emoji - without words it is rather hard to make something of your reaction. If you have feedback would be great to share it, so it can be recognized.

**Comment by haheute** [comment]
@foss-  I'm not sure what I can say, because I don't even know what the eyes emoji means and when I am supposed to use it.. I just wanted to give some reaction, so that @MrPetovan knows, that I see his work and appreciate it. 

When it then works well I use to give this one:  :+1:  and when I don't have yet tested it, I am a bit more cautious and just show that I am looking :eyes:

**Review by annando — APPROVED** [review]

**Pull request merged**
