### PR TITLE
Display a symbol when a post had been reshared

### PR DESCRIPTION
**Pull request by annando**
There is now a small symbol left of the date when post had been in your stream because of a reshare (and not because you follow that author).

### CODE REVIEW

**Comment by tobiasd** [comment]
Can we please have the avatar of the contact back who shared the posting (the last/first time) the current only display the alien profile picture of a non-contact is horrible.

**Comment by annando** [comment]
I implemented the new symbols as a replacement since they are more verbose. You can see several reasons why a post had landed in your timeline (reshared, some following contact commented, hashtag subscription) instead of only the resharer.

When you hover over the new symbol then you see who reshared it first.

**Comment by tobiasd** [comment]
With the profile picture of the sharer displayed, that information was available at the first glance. So now there are posts of alien persons in the stream and one has to search for the reason why they arrived.

**Comment by annando** [comment]
You have seen the new symbol? I personally - find it more subtle but not necessarily invisible:
grafik

Hovering over the symbol shows the details:
grafik

With Frio it looks like this:
grafik
grafik

If this isn't enough, I can think of adding a user configuration that changes the owner in the conversation for reshared posts. But the default would be the new way, since this does reveal much more details:
grafik
grafik

**Comment by MrPetovan** [comment]
If we don't show the sharer avatar anymore, do we still need the micro avatar size?

**Comment by tobiasd** [comment]
The information is hidden behind the "you have to hover over the icon". Before the change it was clear on the 1st view of a posting who shared it with you.

**Comment by annando** [comment]
@MrPetovan The micro avatar is used for the forums.

**Pull request merged**
