### PR TITLE
Github Action: Merge to develop

### PR DESCRIPTION
**Pull request by nupplaphil**
With this github action, we can label a PR with "merged in develop" (or any other label we want to define) and a Github Action automatically merges the changes of this PR into our `develop` branch.

This is maybe usefull for our `RC` phase, so @MrPetovan doesn't need to merge the whole RC changes into the develop after the release.

Because this would change the way how we use the `develop` branch during the `RC` stage, it's currently only a Draft - PR

Pinging @annando @MrPetovan @tobiasd to approve this behavior or reject/discuss it.

The documentation about this action: https://github.com/marketplace/actions/merge-branch

### CODE REVIEW

**Comment by MrPetovan** [comment]
So if understand correctly, the workflow would be:
1. Manually merge PR into RC branch.
2. Label the PR “Merge to develop”
3. PR gets automatically merged into `develop`.

?

**Comment by nupplaphil** [comment]
Yep

**Comment by MrPetovan** [comment]
It sounds good to me, even if we move away from GitHub we can always revert to the current system.

**Comment by annando** [comment]
What happens in the case of a merge conflict?

**Comment by tobiasd** [comment]
TBH I don't see a benefit ;-) At least not for our situation with less then a handful of devs and only 14 days of RC phase disrupting continuous updates in develop.

During the RC phase the development branch *is not supposed* to see commits, as the plan is to focus on ironing out the release and not push new features to the develop branch. So there *should* not be any merge conflicts after the release anyhow. And as @annando already mentioned, there is no hint how merge conflicts are handled by the hook.

**Comment by annando** [comment]
I could imagine a different github action that would be helpful (if possible). Is there the possibility of something like a build counter? It would be great if every commit could increase automatically some counter.

**Comment by nupplaphil** [comment]
> 
> 
> I could imagine a different github action that would be helpful (if possible). Is there the possibility of something like a build counter? It would be great if every commit could increase automatically some counter.

Do you mean something like this: https://github.com/einaregilsson/build-number ?

**Comment by nupplaphil** [comment]
> 
> 
> TBH I don't see a benefit ;-) At least not for our situation with less then a handful of devs and only 14 days of RC phase disrupting continuous updates in develop.
> 
> During the RC phase the development branch _is not supposed_ to see commits, as the plan is to focus on ironing out the release and not push new features to the develop branch. So there _should_ not be any merge conflicts after the release anyhow. And as @annando already mentioned, there is no hint how merge conflicts are handled by the hook.

I understand and I think you're right.
tbh I do have to take a deeper look about merge conflicts, it seems they're normally resolveable with this action, but I'm not sure.

I close this PR since it isn't helpfull (enough)

**Comment by annando** [comment]
@nupplaphil I would like to have some serial counter that increases automatically for every commit (or PR), so that we can include it in the version number (or as some additional value). Then we qould be able to better detect the version that someone is running (especially when on dev or rc)

**Comment by nupplaphil** [comment]
> 
> 
> @nupplaphil I would like to have some serial counter that increases automatically for every commit (or PR), so that we can include it in the version number (or as some additional value). Then we qould be able to better detect the version that someone is running (especially when on dev or rc)

I think I understood, I'll have a look

**Pull request closed without merging**
