### PR TITLE
Adding Dependency Injection for logging

### PR DESCRIPTION
**Pull request by nupplaphil**
alternative way for #6396 

I tried to add the way, https://github.com/friendica/friendica-directory is using dependency injection and reduce it in a way, Friendica could possibly use it.

Therefore I used the base-DI-container framework of https://github.com/slimphp/Slim (the framework behind friendica-directory) -> https://github.com/silexphp/Pimple container and the "standard" interface (PSR\ContainerInterface).

It's maybe a base, how we can set a path to DI in Friendica without completely change everything.
-> I'm not bad if you say if you all don't want this. As I said it's just a guess how it could work and I want your feedback ;-).

Changes:
- Adding DI container (PSR\ContainerInterface with Pimple)
- Default dependencies in production and test for logging
- Merge `settings.conf.php` and `local.conf.php` in `src/settings.php` (like friendica-directory does)

ToDos:
- [ ] Making tests work again (`DBA::connected()` is using `App` before `App´ is loading in ´ApiTests.php`)
- [ ] Add a way how `Config::get()` and `Config::set()` may overwrite the default-settings

### CODE REVIEW

**Comment by MrPetovan** [comment]
For what it's worth, I don't like how Slim does the dependency injection by requiring files that are expecting a specific global variable to be set. It trips static code analyzers and is overall a liability. Friendica Directory is my first full-featured Slim project and I now know better what I'd like for upcoming projects.

Instead of a require file, I'd rather have an autoloadable static class doing the same using the container as a method parameter.

**Comment by nupplaphil** [comment]
OK I thought friendica-directory was a good way for DI.

What do you think about https://php-di.org ?

**Comment by nupplaphil** [comment]
I see. But it isn't necessary reflecting all the time:
http://php-di.org/doc/performances.html#compiling-the-container
But I understand your concerns. The overall goal for DI here is f.e. that for tiny environments (f.e. RaspPI), you can switch to a syslog only version, which will boost the performance but comes with lack of stream support f.e.

**Comment by MrPetovan** [comment]
If PHP DI can have a static container declaration, it fits my bill. If you want to have a go at it, be my guest.

**Comment by nupplaphil** [comment]
Not this way ...

**Pull request closed without merging**
