### PR TITLE
Replace explicit php logical operators

### PR DESCRIPTION
**Pull request by Hypolite**
This PR replaces all `AND` and `OR` in PHP conditions by `&&` and `||`. See [this post](https://friendica.mrpetovan.com/display/735a2029455936b97c677a0809576252) for an explanation.

There was 3 cases where there could have been an ambiguity between both logical operators styles, but they already were correctly protected by parentheses.

This means that this PR introduces absolutely no functional change, it only allows developers not to add extra parenthesis in boolean variable assignments in the future. It doesn't change anything for `if` conditions.

Additionally, it corrects two SQL queries using the `&&` operators (which is exactly equivalent to `AND` in SQL)

### CODE REVIEW

**Comment by annando** [comment]
84 files? That is really intense. Will it interfere with PR https://github.com/friendica/friendica/pull/3473 from @Quix0r?

BTW: Concerning parenthesis: I still will use them and I will add them especially at places where it increases the comprehensibility of the code.

**Comment by tobiasd** [comment]
I've read over the replacements and they are looking ok. Might have skipped something, as there where that many changes ;-)

**Comment by annando** [comment]
I'm away for the weekend and won't have much time to look at the changes.

**Comment by Hypolite** [comment]
> BTW: Concerning parenthesis: I still will use them and I will add them especially at places where it increases the comprehensibility of the code.

That's fine by me even if I can't stand them personally because I can't think of a good general reason to remove them, unlike other coding standards (like mandatory braces, wrapping operators with spaces and single quotes).

**Comment by Hypolite** [comment]
Of course I forgot about lowercase operators because I assumed that all operators would be uppercase.

**Comment by Quix0r** [comment]
I found one more somewhere and changed it then.

**Pull request merged**
