### PR TITLE
Remove item query limit when using file param in mod/network

### LINKED ISSUE #6823: Saved Folders: Display of filed items broken
### Expected behavior
When I click on a saved folder all filed items should be accessible.

### Actual behavior
When I click on a saved folder only one page of filed items is shown. If the number of 'items to display per page' is set to X I get exactly X filed items. That's it. The end.

### Steps to reproduce the problem
I'm using frio **with infinite scroll** option. My setting for 'number of items to display per page' is 20.
When I click on a folder to display the filed items I get exactly 20 items. But when I scroll down there is a line saying 'The end'. It doesn't load the next items.
When I change my setting to show e.g. 40 items per page I get 40 filed items and again 'The end' is displayed as if there are no more items. But that's not true.
**Without infinite scroll** I get an empty page (no items) when I click on the 'next' button.

Discussion: https://forum.friendi.ca/display/0b6b25a8-105c-8193-e81f-078987484912

### Friendica version you encountered the problem
2019.03-rc

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
10.1.38 MariaDB

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #6823 

The problem came from the way we handle filer pagination. Instead of paginating on the item query, we paginate on the term search, and then provide the relevant item ids to the item query.

Of course, if you're still paginating the item query at this point, it doesn't work as expected. If you take maximum 10 item ids starting from the 11th from the term table and then you're querying at most 10 items starting from the 11th by providing those 10 item ids, it expectedly returns nothing.

### CODE REVIEW

**Comment by AlfredSK** [comment]
Would it be possible to have a pagination logic (method, class, whatever...) and use that at all places where pagination is used. I'm thinking of this because there is another pagination issue with the community pages.

**Comment by MrPetovan** [comment]
Oh it exists, and it was used, except it was used twice when you selected a Saved Folder. This had no consequence on the first page, but would make all the subsequent pages blank.

What's this other issue?

**Comment by AlfredSK** [comment]
The other issue is #5562 
See also comment https://github.com/friendica/friendica/issues/5562#issuecomment-471233196

**Comment by MrPetovan** [comment]
Thanks, I left a big blurb for anyone to grab it.

**Pull request merged**
