### PR TITLE
Update autolinker regular expression in Text\BBCode

### LINKED ISSUE #2487: Umlaut containing links will not be recognized
A link such as https://friendica.wäckerlin.ch/friendica is not correctly recognized, it will show up as a link up to https://friendica.w and from there on as normal text. 

See in the thread here: https://friendica.wäckerlin.ch/display/51a50594105720f23c0cb2c239587447

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #2487, #5795 and #6095 for the last time.

Thanks to https://daringfireball.net/2010/07/improved_regex_for_matching_urls

### CODE REVIEW

**Comment by nupplaphil** [comment]
This sounds like a great example of some tests :)

- take all the messages of the bugs
- create a test for each (or a dataset)
- run the new code

This should prevent regressions at this part of the code.

-> maybe I've a little bit time to create a followup

**Comment by MrPetovan** [comment]
Ha, I started writing tests for the `BBCode::convert` method a while ago (to prepare switching to the lexer), but it covers so many cases that I haven't been able to complete it yet.

**Comment by MrPetovan** [comment]
> Fixes #2487, #5795 and #6095 for the last time.

Ha ha ha, nope, see:
- #6841
- #6845
- #6857
- #6904

**Comment by MrPetovan** [comment]
Fixes #6030 too

**Pull request merged**
