### PR TITLE
generate addr for new registered users

### PR DESCRIPTION
**Pull request by rabuzarus**
With the registration the self contact is getting a address in the contact table.

Question: Do we need a sql update routine for the already existent self contacts or is this also done by poco?

### CODE REVIEW

**Comment by rabuzarus** [comment]
shit, the second commit should be an own PR but I think it's not that problematic.

Regarding the commit "include friendica address in hcard":
* Can you have a look at the variable and css class names? (faddr is meant as friendica-address but maybe there would be an more understandable name for this)
* I have tried to do some basic template/css work. Theme developers should have a look if they want to display it more beautiful

**Comment by annando** [comment]
@rabuzarus Is there a reason why you have changed the "$a->get_baseurl()" to "z_root()"? I know, these two functions are doing the same. But I would like to have it unified across the whole system. I guess this is something for the coding styles as well :)

**Comment by rabuzarus** [comment]
@annando 
yes this is something for coding style. I just thought, there is a reason for the function z_root() and wanted to start to convert from $a->get_baseurl() to z_root() piece by piece.

Should I revert it?

**Comment by annando** [comment]
Pull request is done.

**Comment by annando** [comment]
I would say: Leave it that way, but please note for the coding documentation that we need a list of deprecated functions. I would say that you have the documentation job :-)

**Comment by redmatrix** [comment]
For point of reference, z_root() (e.g. "zot_root") was created soon after I started work on building zot. It was meant to avoid requiring $a for every function that generates a URL (which caused "global $a;" to be added to a large number of discrete functions), or the clumsy get_app()->get_baseurl(); and z_root was intended to eventually replace all of these. It's just one of those menial editing tasks that never got finished - in either project. In Friendica get_baseurl has an additional parameter to deal with self-signed certs and I don't remember if it was added to z_root but that would be the only reason to stick with get_baseurl. One could (and probably should) add that parameter to z_root if it isn't there already.

**Pull request merged**
