### PR TITLE
Explicit methods in DI Registry

### PR DESCRIPTION
**Pull request by nupplaphil**
Replaces #8088

- Replaces all `@method static` annotations with concrete methods
- Split the methods based on their namespace in different Registry (sub-)classes for better finding
- Rework some tests, which weren't working the "right way"
- Fixing some places in the code where Cache namespace was missing

I searched per regex and patterns and PHPStorm native functionallity for every occurrence of DI and tested it locally and on my friendica node ..

Needs friendica/friendica-addons#941 as well

@annando with this PR, VSC should be working with DI::app() or Core::config() methods again and show the right hints. Would it be possible to pull this branch and check if I'm right?

### CODE REVIEW

**Comment by annando** [comment]
Tests are failing.

**Comment by nupplaphil** [comment]
@annando but now .. now pulled the last version to my friendica node as well for checks. The last PR-state ran for the last 24hours without an error noticed.

**Comment by nupplaphil** [comment]
Found a bug, reopen it soon

**Comment by MrPetovan** [comment]
Is there a specific reason you are working on a branch directly in the repository and not in your fork like the usual workflow?

**Comment by nupplaphil** [comment]
> Is there a specific reason you are working on a branch directly in the repository and not in your fork like the usual workflow?

yes, because I have to improve my PHPStorm skills and though "Creating PR" automatically creates a branch on **my** repo.. Nope it doesn't .. :-(

**Pull request closed without merging**
