### PR TITLE
Prevent DeliveryData update if uri-id field is NULL in Model\Item

### PR DESCRIPTION
**Pull request by MrPetovan**
- Address https://github.com/friendica/friendica/issues/9250#issuecomment-696294754

Edit: Replaced by #9265

### CODE REVIEW

**Comment by annando** [comment]
I would like to have a look why this situation can happen at all. This situation shouldn't happen at all and could be an indicator for a different problem.

**Comment by SpcCw** [comment]
> I would like to have a look why this situation can happen at all. This situation shouldn't happen at all and could be an indicator for a different problem.

I have one account with 300+ followers where it used to pop up more often when viewing Network feed (and it usually ended up as white screen). It always took A LOT of time to load too and timed out often. After applying this fix it started loading fast and without errors and what is weird after I reverted the code back it remained fast.

The problematic account is a bot with automatic approval of followers so I thought maybe it added back something weird.

**Comment by annando** [comment]
I have several accounts with 1,000+ followers (I'm hosting many bot accounts). I can confirm that it sometimes takes some time, maybe 10 seconds. But I never get this error. Which version are you on and what is the system reporting under `/friendica` about the post update version?

Please execute this query and report the results:

```
select count(*) from item; select count(`uri-id`) from item; select count(*) from item where `uri-id` is null;
```
This should return three numbers. On my system it is:
```
MariaDB > select count(*) from item; select count(`uri-id`) from item; select count(*) from item where `uri-id` is null;
+----------+
| count(*) |
+----------+
|  5157275 |
+----------+
1 row in set (1.61 sec)

+-----------------+
| count(`uri-id`) |
+-----------------+
|         5157275 |
+-----------------+
1 row in set (1.88 sec)

+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)
```

Problem is: This value mustn't be empty. When it is empty and it is some really old data, then the post update hadn't worked. When it is some newer data then you have a serious problem with your database.

**Comment by SpcCw** [comment]
> I have several accounts with 1,000+ followers (I'm hosting many bot accounts). I can confirm that it sometimes takes some time, maybe 10 seconds. But I never get this error. Which version are you on?

It was this way for a while and lasted across two latest stable versions at least. I assumed I just had inadequate system because I have two small bots and it was very present with 300 followers one, appeared less often with 200 followers one. So it looked like it was scaling problem.

Currently it is 2020.09 at which it was present today and disappeared after I applied this patch. Now it works fine even without it, I am going to see if this behavior returns.

**Comment by annando** [comment]
@SpcCw please try the query from above and have a look at the post update version. I really would like to see how old the invalid data is.

@MrPetovan I'm currently thinking about leaving this as an indicator.

**Comment by SpcCw** [comment]
> @SpcCw please try the query from above and have a look at the post update version.

The database version is 1368/1368, the post update version is 1350.
```
+----------++-----------------++----------+
| count(*) || count(`uri-id`) || count(*) |
+----------++-----------------++----------+
|  2435851 ||         2435839 ||       12 |
+----------++-----------------++----------+
```

All of them have similar creation time.
```
+---------------------+
| created             |
+---------------------+
| 2020-05-30 11:49:05 |
| 2020-05-30 12:21:10 |
| 2020-05-30 12:24:23 |
| 2020-05-30 12:24:23 |
| 2020-05-30 10:27:17 |
| 2020-05-30 10:27:17 |
| 2020-05-30 12:26:00 |
| 2020-05-30 12:26:00 |
| 2020-05-30 12:28:00 |
| 2020-05-30 12:28:00 |
| 2020-05-30 12:28:18 |
| 2020-05-30 12:28:18 |
+---------------------+
```

**Comment by annando** [comment]
Great, this is no general problem. How good are you in database stuff? Could you have a look at the field `uri` for these lines as well? When these are not empty, you could have a look if the table `item-uri` does contain entries with a matching `uri`.

Since more and more stuff is being done with the `uri-id` field, I have the feeling that these 12 items could cause additional problems somewhere else as well.

**Comment by SpcCw** [comment]
> Great, this is no general problem. How good are you in database stuff? Could you have a look at the field `uri` for these lines as well? When these are not empty, you could have a look if the table `item-uri` does contain entries with a matching `uri`.

If I understood you right and did it right then it seems that not every one of them has matching entry:


```
select uri from item where `uri-id` is null;
+----------------------------------------------------------------------+
| uri                                                                  |
+----------------------------------------------------------------------+
| https://pl.smuglo.li/objects/e79669ab-96b9-4b70-b381-4040adb5383e    |
| https://princess.cat/objects/967e491e-68a7-42f0-974d-1d1c49eb2051    |
| https://princess.cat/objects/4e98dedf-b48a-49a1-ae88-4c252e5232df    |
| https://princess.cat/objects/4e98dedf-b48a-49a1-ae88-4c252e5232df    |
| https://neckbeard.xyz/objects/325248c5-1eea-4391-a1cf-ca7f147cc854   |
| https://neckbeard.xyz/objects/325248c5-1eea-4391-a1cf-ca7f147cc854   |
| https://princess.cat/activities/4f664e35-6f38-4f80-a4b6-088288265376 |
| https://princess.cat/activities/4f664e35-6f38-4f80-a4b6-088288265376 |
| https://pl.ohno.host/objects/f669fe09-86aa-42ca-baf5-d84c9269c9d8    |
| https://pl.ohno.host/objects/f669fe09-86aa-42ca-baf5-d84c9269c9d8    |
| https://princess.cat/activities/5995b488-66f5-4e2c-acb6-be3e47b77561 |
| https://princess.cat/activities/5995b488-66f5-4e2c-acb6-be3e47b77561 |
+----------------------------------------------------------------------+

select `item-uri`.* from `item-uri` inner join `item` on `item-uri`.uri = item.uri where item.`uri-id` is null;
+--------+-------------------------------------------------------------------+------+
| id     | uri                                                               | guid |
+--------+-------------------------------------------------------------------+------+
| 996058 | https://pl.smuglo.li/objects/e79669ab-96b9-4b70-b381-4040adb5383e | NULL |
| 996273 | https://princess.cat/objects/4e98dedf-b48a-49a1-ae88-4c252e5232df | NULL |
| 996273 | https://princess.cat/objects/4e98dedf-b48a-49a1-ae88-4c252e5232df | NULL |
+--------+-------------------------------------------------------------------+------+
```

**Comment by annando** [comment]
So only two uri-id are missing. Do you think that you can add these two to the `item-uri` table by hand and fix the missing data?

**Comment by SpcCw** [comment]
> So only two uri-id are missing. Do you think that you can add these two to the `item-uri` table by hand and fix the missing data?

Yes, I can do it. Do I have to fill `guid` field too? I see it is NULL for these existing entries but very few entries in this table have NULL `guid`. Is it normal?
```

select * from `item-uri`  where guid is null;
+---------+----------------------------------------------------------------------+------+
| id      | uri                                                                  | guid |
+---------+----------------------------------------------------------------------+------+
|  121413 | https://diaspora.koehn.com/objects/0b2dab5030a9013867090242ac180004  | NULL |
|  996058 | https://pl.smuglo.li/objects/e79669ab-96b9-4b70-b381-4040adb5383e    | NULL |
|  996273 | https://princess.cat/objects/4e98dedf-b48a-49a1-ae88-4c252e5232df    | NULL |
|  996296 | https://diasp.org/objects/f813b5e0849e0138abb2047d7b62795e           | NULL |
|  996330 | https://diasp.eu/objects/f330c450849e0138c79b101b0efced44            | NULL |
|  996348 | https://diasp.de/objects/c75cb690849e01385867101b0e91c357            | NULL |
|  997054 | https://diaspora.psyco.fr/objects/245ec3d0849f0138876f38607759d42b   | NULL |
|  997060 | https://diaspora.psyco.fr/objects/f811a2e0849e0138876f38607759d42b   | NULL |
|  997074 | https://diaspora.psyco.fr/objects/699eb150849e0138876938607759d42b   | NULL |
|  997082 | https://diaspora.psyco.fr/objects/5d6f0580849e0138876f38607759d42b   | NULL |
| 1006377 | https://diaspora.1312.media/objects/d40f9870849601389f640242ac120002 | NULL |
| 1057266 | https://framasphere.org/objects/95530a6080340138e0702a0000053625     | NULL |
| 1906999 | tag:mastodon.club,2020-09-07:objectId=1350:objectType=Block          | NULL |
+---------+----------------------------------------------------------------------+------+
13 rows in set (0.759 sec)
```

**Comment by annando** [comment]
No, the `guid` field is not that important.

**Comment by SpcCw** [comment]
Thanks for your help, @annando, I added the missing data. So far it works fine.

Could it be that similar inconsistency causes the mysterious tag problem from #8896?

**Comment by annando** [comment]
@SpcCw I think that the tag problems are caused by something else.

Concerning this PR: I would prefer a post update script that addes missing `uri-id` values, since this field is so crucial.

**Comment by MrPetovan** [comment]
> I would like to have a look why this situation can happen at all.

It happens because we let it. The `uri-id` field in the `item` table isn't set to `NOT NULL`, so we have to account for this possibility.

**Comment by annando** [comment]
It isn't set to `NOT NULL` because that wasn't possible, since the field had been introduced at a later time. This error here is a great indicator for invalid data. Adding the test from this PR is like putting a sticker on the oil warning light on your car. That's because I want to add a job that cleans the data.

**Comment by MrPetovan** [comment]
I agree but until this field is actually set to `NOT NULL` we simply can't guarantee it will have a value.

**Comment by annando** [comment]
That's why I want to create that functionality that fixes it. We have to ensure that field is not empty for the conversion to the item table replacement.

**Comment by MrPetovan** [comment]
And both can live at the same time until such a time when we can ensure in the database schema that this field always holds a value.

**Comment by annando** [comment]
When we add the check here, we have to add some exception somewhere else to check for the situation.

**Comment by MrPetovan** [comment]
This would be the ideal, but I will not seek them myself until someone complains about it.

**Comment by annando** [comment]
Since my code base is now cleared again, I can do the changes today.

**Comment by annando** [comment]
Have a look here: https://github.com/friendica/friendica/pull/9265

**Comment by MrPetovan** [comment]
Replaced by #9265

**Pull request closed without merging**
