### PR TITLE
Fix parenthesis encoding in admin.php

### PR DESCRIPTION
**Pull request by AlfredSK**
Parenthesis in admin, site, worker, frontend worker have wrong encoding.

### CODE REVIEW

**Comment by AlfredSK** [comment]
Hmm. Now that I think about it... someone has to create a new messages.po by running some script. Unfortunately, I'm not familiar with that translation workflow.

**Comment by nupplaphil** [comment]
ping @tobiasd ;)

**Comment by AlfredSK** [comment]
Nevermind. I just pulled the changed code. It works, obviously.

**Comment by AlfredSK** [comment]
But when I switch the UI to German that paragraph is displayed in English. So, ... sorry. I don't know. :-)

**Comment by MrPetovan** [comment]
Next time, please convert the special characters `\x28` and `\x29` to actual parentheses. They are artifacts of a previous manual gettext implementation that was choking on actual parentheses.

**Pull request merged**
