### PR TITLE
Fix Password Reset Token Security

### PR DESCRIPTION
**Pull request by lynn-stephenson**
Currently password reset tokens are not nearly as safe as they should be:
1. The random name is predictable.
2. The last 4-digits are brute forcible but not predictable.
3. Easily available for nefarious purposes if an adversary has read access to the DB, or they are leaked through SQL injection.

I fixed all of these issues in this PR.

The password reset tokens are now generated with a CSPRNG, specifically 16 bytes in length (32 ASCII hexadecimal encoded output).

The password reset tokens are stored in a hashed form, which means adversaries can't use them when obtained through read access via SQL injection, or read access to DB. And the received password reset token is hashed before the look up to make timing attacks impractical. Although this isn't the ideal solution since it's being indexed by a secret value, it is a bandaid that works.

### CODE REVIEW

**Comment by MrPetovan** [comment]
This PR will make all previously issued tokens invalid, however new ones can easily be requested.

**Comment by annando** [comment]
I don't know that functionality very much. But: When does the token really comes to effect? Isn't it that someone presses that button, then the token is generated and send to the user via mail? So problems could only occur when the update had been done in the short time between pressing the reminder button and entering the token?

**Comment by MrPetovan** [comment]
Absolutely. The token also expires in an hour wich makes the feature break window pretty short, but it still would be a feature break.

**Comment by lynn-stephenson** [comment]
> This PR will make all previously issued password reset tokens invalid, however new ones can easily be requested. We could also hash all the existing tokens in the DB and maintain validity, which would make it a better candidate for a master hotfix since it's a security improvement.
> 
> What do you think @annando @tobiasd ?

I think it'd be best to purge all password reset tokens when the application is updated instead of having weak hashed password reset tokens lingering in the DB.

**Comment by MrPetovan** [comment]
Why, since they can't be used after an hour has passed anyway?

**Comment by lynn-stephenson** [comment]
> Why, since they can't be used after an hour has passed anyway?

It doesn't matter too much, but it increases the complexity of your code base by hashing the old password reset tokens.

I recommend 15 minutes for account recovery related requests, and you should let users know how long they have to use the account recovery request. (I thought about changing this, but I wanted to keep this PR minimal and only fix what was necessary.)

**Comment by MrPetovan** [comment]
Got it, thank you for your work!

**Comment by annando** [comment]
15 minutes is a very short window. When a mail server is performing greylisting, then 15 minutes could be too short.

**Pull request merged**
