### PR TITLE
Updated dependencies to latest stable versions.

### PR DESCRIPTION
**Pull request by Quix0r**
This small change updates the `composer.lock` file to latest stable versions (`composer update` was run).

### CODE REVIEW

**Comment by MrPetovan** [comment]
Have you checked the diff for each of these upgrades to make sure they are legit?

**Comment by Quix0r** [comment]
I get now this error message:
`Fatal error: Uncaught Error: Call to undefined method ReflectionType::getName() in /var/www/../vendor/level-2/dice/Dice.php:249`

No, I guess this is not required?

**Comment by Quix0r** [comment]
Reference to https://github.com/phpstan/phpstan/issues/1133

**Comment by Quix0r** [comment]
So `Dice` is broken?

**Comment by MrPetovan** [comment]
Possibly? That's why updating dependencies isn't trivial.

**Comment by Quix0r** [comment]
Wanna close this or keep it open until `Dice` has been fixed? Or can I blacklist the 4.0.2 version somehow?

**Comment by MrPetovan** [comment]
We can't accept this PR until you can at least run your node and only after you've manually checked all the diffs of all the version updates.

**Pull request closed without merging**
