### PR TITLE
Small fix for the global directory that delivers wrong picture paths.

### PR DESCRIPTION
**Pull request by annando**

### CODE REVIEW

**Comment by fabrixxm** [comment]
Shouldn't this fixed on dir?

**Comment by annando** [comment]
Yeah, it would be better. Is anyone working at the directory at the moment?

**Comment by fabrixxm** [comment]
@Beanow ?

**Comment by annando** [comment]
@Beanow is inactive since several months. I have no free resources to have a look at the directory as well.

**Comment by redmatrix** [comment]
There are about 5400 incorrect entries (over half the directory) and there are a few other incorrect domains present (such as dir.dfrn.org) which even pre-date friendika.com. Repairing all these names is going to be a daunting task. I think the best option is to do this client side as this pull request does. However, I wouldn't try and translate specific names since there are so many incorrect ones. I would just ignore everything but the basename and append that onto a string constant "http://dir.friendica.com/photo/". The advantage of doing it client side is that you can then move the directory to another url and just change the constant and not have to change the directory entries themselves from any prior directory server.

**Comment by redmatrix** [comment]
fixed on directory server (using the same method I mentioned except server side), please test and if working you can close this.

**Comment by annando** [comment]
@redmatrix Thanks! I will test it this evening.

**Comment by annando** [comment]
@redmatrix It works great. So I will close my pull request. Thanks!

**Pull request closed without merging**
