### PR TITLE
Reorganize Login to Fix #4878

### LINKED ISSUE #4878: Login Dialog is Confusing
As discussed in [the forums](https://forum.friendi.ca/display/e18176ef375ad770f8ca3c8135838652) the login page is quite confusing.

I have rearranged the login dialogs for vier and frio: https://github.com/astifter/friendica/tree/reorganize_login.

Enjoy.

### PR DESCRIPTION
**Pull request by astifter**
@MrPetovan There you go.

Rearranged the login screens in vier and frio to distinguish between logging in and going to registry page. Have to work on the mobile layouts still.

### CODE REVIEW

**Comment by astifter** [comment]
Okay, I'm happy now.

**Comment by MrPetovan** [comment]
Looks okay code-wise but I'm going to wait on @rabuzarus, he usually has things to say about theme changes.

**Comment by rabuzarus** [comment]
I have two things to say:

1.) I think to have a separator `OR` isn't a good solution. Either we take a whole sentence - e.g. "Don't have an account? Sign up now" (with "Sign up now" as link) or we remove the `OR` and use some `margin-top` for the visual separation. Maybe we should have a look how the other platforms solve the visual distinction.

2.) I didn't test it but maybe there is a little bit horizontal space in the line with "Forgotten password?" "Remember me" and "Login" because other languages could need more space. E.g.
login-form.
In addition I think that having 3 different kind of elements (a link, a checkbox and a button) in one line isn't a good ui solution

**Comment by MrPetovan** [comment]
Thanks!

**Comment by astifter** [comment]
Okay guys and gals, take 2. Attached screenshots of vier/frio with regular/mobile.
screenshot-2018-4-23 my friend network home 4
screenshot-2018-4-23 my friend network home
screenshot-2018-4-23 my friend network home 3
screenshot-2018-4-23 my friend network home 2

**Comment by MrPetovan** [comment]
> Okay guys and gals

I suggest you to use “folks” instead, it’s more inclusive. 🙂

Great work otherwise. I’ll wait for our resident UI experts reviews.

**Comment by MrPetovan** [comment]
Only @rabuzarus 's seal of approval is needed now.

**Comment by rabuzarus** [comment]
1.) I find the big 'sign up' button with the thick green border a little bit too dominant. Sure the 'sign up' button should be visually recognizable, but registration is something a user is doing only at the first time. After he/she has signed up, he/she will always use the login button. Therefore the big green 'sign up' button is to prominent. This is better solved in your login form for vier. I would vote for having something slim lined. From my point of view hubzilla is doing it the right way (https://hubzilla.kommune4.de/login)

2.)  In the current version of the login form there are some (I don't know how to call it - maybe) light shadows behind the login form (https://github.com/friendica/friendica/blob/develop/view/theme/frio/css/style.css#L3200 and https://github.com/friendica/friendica/blob/develop/view/theme/frio/css/style.css#L3213). I would like to keep them.

**Comment by astifter** [comment]
I have made the login-button less obtrusive (the color matches the color form the guy in the shirt and gives a nice balance, methinks).
screenshot-2018-4-24 my friend network home
Also fixed the missing tiles.

**Comment by astifter** [comment]
Thanks for all the feedback and help on this one.

**Comment by MrPetovan** [comment]
Thank you for your work!

**Pull request merged**
