### PR TITLE
More GNU Social compatibility for the API

### PR DESCRIPTION
**Pull request by annando**
This small pull request just adds two API calls that are currently missing.

### CODE REVIEW

**Comment by Quix0r** [comment]
Oh, better rebase :-) to much merges make the GIT history complex to handle/merge later on.

**Comment by Quix0r** [comment]
````
git checkout 1601-api-statuses-lookup
git rebase -S origin/develop
````
-S only if you have GNU Privacy Guard in use and which do sign your commits. :-)

**Comment by Hypolite** [comment]
@Quix0r I don't get it, besides a few extra lines in the commit list, what is the downside of the merges? I mean the actual merges always go smoothly, there aren't any technical issues because of those merges that are way safer/accessible than rebase that I still don't understand.

**Comment by Quix0r** [comment]
Yes, github makes rebases unsafe. :-( Maybe this explains it better: http://blog.mwaysolutions.com/2015/07/23/git-merge-and-rebase-part-2-of-3/

**Pull request merged**
