### PR TITLE
Address several deprecation notices

### PR DESCRIPTION
**Pull request by MrPetovan**
Address most of https://github.com/friendica/friendica/issues/12011#issuecomment-1826792949

### CODE REVIEW

**Comment by MrPetovan** [comment]
Paging @gudzpoz to verify I didn't break feature in  `Content\Smilies`.

**Comment by gudzpoz** [comment]
I see the tests are passing, and it all looks good to me. :+1:

**Comment by annando** [comment]
Can you check why the 7.4 test is failing?

**Comment by MrPetovan** [comment]
Pushed a commit unrelated to the tests, it went ok.

**Pull request merged**
