### PR TITLE
OStatus improvements (Mastodon) and new SQL functions

### PR DESCRIPTION
**Pull request by annando**
The XML for OStatus looks more like the ones from GNU Social and Mastodon. Especially the conversation data should be now be standard conform. We distribute the conversation data via DFRN as well.

Additionally there is a new table "conversation" which contains the thread information and the raw data.

And finally there are two new sql functions to insert data into a table and to fetch only the first row of a query.

### CODE REVIEW

**Comment by Hypolite** [comment]
Does it solve any of the ongoing communication issues between Friendica and Mastodon that you know of?

**Comment by annando** [comment]
My last test salmons went through. I hope that it wasn't just coincidence. 

I just added one more commit. This is a small improvement to the new "insert" function that will help other (upcoming) database functions as well.

**Comment by annando** [comment]
Sorry for the (now hopefully) final changes to this PR. I changed the unique index in the "conversation" table back to a better value - and I introduced a new database function to update rows.

I'm still having the issue that sometimes OStatus conversations are stored with "protocol = 0". These new lines should take care for this, since it seemed that the "0" rows always had a companion with an assigned protocol.

**Comment by rabuzarus** [comment]
Please add a db table description to the friendica help docu

**Comment by annando** [comment]
@rabuzarus this is done here: https://github.com/friendica/friendica/pull/3408

I guess I really should improve the dbstructure.php so that it could fill this documentation automatically.

**Comment by Hypolite** [comment]
Typical developer:
- Please do a teeny-weeny amount of work
- I should spend a huge amount of work so that I don't have to do the teeny amount

😜

**Pull request merged**
