### PR TITLE
Config to enable the optimizing of all tables

### PR DESCRIPTION
**Pull request by annando**
Folow up to https://github.com/friendica/friendica/pull/12819

We only should optimize all tables if this is really wanted.

### CODE REVIEW

**Comment by HankG** [comment]
These aren't all the tables though. I'm fine with there being a flag like that to toggle the two modes but if that's the case we should probably add all the tables to the list. Is there a SQL shortcut for doing that instead of the big listing way I did it?

**Comment by annando** [comment]
In the DBStructure-Class we have got a function to fetch all tables. I guess that this would be the best solution. This PR here is a quick fix to avoid massive problems with larger instances, thus it isn't refined.

**Comment by HankG** [comment]
It cleaned up literally 12 GB of disk space on my system. Leaving the other tables without optimization is not a trivial amount of storage saved. I could see why you don't want to run it once a week, or whatever frequency that optimization is run at though.

**Comment by annando** [comment]
Since this can cause long downtimes on large systems, I wouldn't do this automatically, but under the control of the admin. Such an optimize call should be performed at some day and time with only a few active users, for example. Because of this, I prefer to perform such calls outside of the system.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
