### PR TITLE
API add events_show

### PR DESCRIPTION
**Pull request by tobiasd**
This PR is pripared via proxy by Marco R.
See [this thread in the Developers forum](https://forum.friendi.ca/display/3e98eba8-215e-45b9-c311-c93505586413).

### CODE REVIEW

**Comment by MrPetovan** [comment]
This needs to be ported to `src/Module/Friendica/Events/Show.php` with a corresponding route in `statis/routes.config.php`, the `include/api.php` file is deprecated.

**Comment by nupplaphil** [comment]
If you like I can help you with porting it (I should have time at Sunday).

**Comment by tobiasd** [comment]
On Fri, 14 Feb 2020 05:57:39 -0800
Philipp <notifications@github.com> wrote:

> If you like I can help you with porting it (I should have time at
> Sunday).

Please join the linked discussion in the Friendica Developers forum to help Marco.

**Comment by MrPetovan** [comment]
Overridden by #8297

**Pull request closed without merging**
