### PR TITLE
Reducing network request, increasing page performance

### PR DESCRIPTION
**Pull request by annando**
A user reported a problem. One of the sites he is posting very much reported him that his server would generate much traffic on their system. At the same time I saw that the system often had to parse the BBCode of an item again. (Which resulted in low performance when searching for content)

While searching for the problem I did several changes:

* The "rendertime" addon now has the ability to print the callstack so that the performance bottlenecks can be named (Pull request for the addon will follow)
* oembed- and parse_url-requests are now stored for one year in two new tables.
* The style.pcss is now using some http magic ("not modified header") to reduce the data amount and loading time.
* The community page always was send twice. One normal and one in the "update" mode - but it doesn't support that at the moment.
* in "get_contact_details_by_url" the number of needed queries are reduced
* The function "get_cached_avatar_image" is deactivated. It doesn't seem to have much use and it slows down the page creation.
* Some problems were fixed that prevented the system from caching rendered html in Diaspora posts with pictures and shadow copies.
* Some code of the cron.php was moved in new functions.

### CODE REVIEW

**Comment by rabuzarus** [comment]
Because you asked. From my side it looks OK.

The only thing I'm worrying about is the fact that it seems that more and more php code comes into the vier theme. We should think about if there are some possibilities to move some of this code back to core

**Comment by annando** [comment]
Yeah, we have to see if we can move this cache thing out of the "vier" code when we find out how to do that. I would like to have this functionality on several places where the content is (nearly) static. (Like the documentation)

When I find out a good way then I will move it. (In an upcoming pull request)

**Comment by annando** [comment]
@tobiasd @fabrixxm Is something missing on this pull request? @rabuzarus looked on it and hod nothing to complain :-)

**Comment by fabrixxm** [comment]
You should do smaller PRs :-P

**Pull request merged**
