### PR TITLE
Fix for MySQL 5.7+ NO_ZERO_DATE

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/friendica/friendica/issues/2786

Only tested on Ubuntu 16.10 with MySQL 5.7.17.

https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html

https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_date
As of MySQL 5.7.4, NO_ZERO_DATE is deprecated.

Patch based on the following search & replace (and then reverting some changes in libraries):

```sh
grep -l '= "0000-00-00"' -r . | \
xargs sed -i -e "s/= \"0000-00-00\"/= '0000-00-00'/g"

grep -l "0000-00-00" -r . | \
xargs sed -i -e "s/0000-00-00/0001-01-01/g"

grep -l "!= '0001-01-01'" -r . | \
xargs sed -i -e "s/!= '0001-01-01'/> '0001-01-01'/g"

grep -l " === '0001-01-01'" -r . | \
xargs sed -i -e "s/ === '0001-01-01'/ <= '0001-01-01'/g"

grep -l " == '0001-01-01'" -r . | \
xargs sed -i -e "s/ == '0001-01-01'/ <= '0001-01-01'/g"

grep -l "strpos(\$dob, '0000-') === 0" -r . | \
xargs sed -i -e "s/strpos(\$dob, '0000-') === 0/strpos(\$dob, '0000-') === 0 || strpos(\$dob, '0001-') === 0/g"

grep -l 'array("", "0001-01-01")' -r . | \
xargs sed -i -e 's/array("", "0001-01-01")/array("", "0000-00-00", "0001-01-01")/g'

grep -l "\$dob = '0000-'" -r . | \
xargs sed -i -e "s/\$dob = '0000-'/\$dob = '0001-'/g"
```

### CODE REVIEW

**Comment by Alkarex** [comment]
Related https://github.com/friendica/friendica/issues/2883

**Comment by Alkarex** [comment]
Ah, damn, I did not see https://github.com/friendica/friendica/issues/3172 and your pull request https://github.com/friendica/friendica/pull/3243 :-(

**Comment by Hypolite** [comment]
Thank you so much for your PR, sorry it's a duplicate!

**Comment by Alkarex** [comment]
It might still be useful for a quick comparison, as I can see that a bunch of changes are missing https://github.com/friendica/friendica/pull/3243

**Comment by Hypolite** [comment]
Definitely, please compare your changes with `develop`.

**Comment by Alkarex** [comment]
My changes compared to /develop are just there https://github.com/friendica/friendica/pull/3321/files :-)

**Comment by Alkarex** [comment]
Ah, right, it looks like my changes are already on top of #3243 , which had so forgotten plenty of lines :-P

**Comment by Alkarex** [comment]
For the record, /develop from today was crashing first on the contact table, which was:
```sql
`bd` date NOT NULL DEFAULT '0000-00-00',
```

**Comment by annando** [comment]
Thanks for your work. We really forgot the field "bd". But the other fields ("birthday" and "dob") are varchar fields and so they needn't to be changed. Because of this, there is no need to change something in the code concerning these fields.

However, we have to have a look at the treatment of the "bd" field that you found. Could you adjust your PR concerning this?

**Comment by Alkarex** [comment]
The reason I changed the `varchar` fields too is to be coherent, for instance to avoid having multiple logics in the PHP code, and not more easily spot any '0000'
I can gladly change the PR as you want, but I suggest using the same default for all dates, whichever type is used (date, timestamp, varchar, integers...). As you can see for instance in `friendica_test_data.sql`, there is a bunch of '0000' which would require a manual processing to find out whether they relate to a varchar or another type.

**Comment by Alkarex** [comment]
Let me know, and I will edit accordingly.

**Comment by Hypolite** [comment]
I just reviewed the PR, changes are sound, and the consistency it brings is welcome.

**Comment by Alkarex** [comment]
Regarding the varchar logic, is there a risk that the data is not in the '8888-88-88 ...' format?

**Comment by Hypolite** [comment]
The short answer is yes (https://github.com/friendica/friendica/blob/develop/mod/profiles.php#L196)

The long answer is yes, but it was already broken anyway, so your changes won't affect the state the code is in.

**Comment by annando** [comment]
@Alkarex you don't need to manually change the database.sql.

Just call ```php include/dbstructure.php dumpsql > database.sql``` from the command line.

**Comment by Alkarex** [comment]
@Hypolite Here you are, new version number https://github.com/friendica/friendica/pull/3321/commits/62768a1bb44176183a058bba9aec89ac2202310e

**Comment by Alkarex** [comment]
Minor change for the cases when 0000 might still be used https://github.com/friendica/friendica/pull/3321/commits/c35eef625acb253a64ba7938ab96084c42096327

**Comment by Hypolite** [comment]
@Alkarex Do you feel you're done with your changes?

**Comment by Alkarex** [comment]
Yes

**Pull request merged**
