### PR TITLE
Phpstan level 0 in addons

### PR DESCRIPTION
**Pull request by Art4**
This PR will analyze the addon folder with PHPStan. With level 0 there were found 78 errors. This errors has to be fixed in the friendica-addon repository.

<details><summary>Details</summary>

```bash
 ------- ---------------------------------------------------------------- 
  Line    bluesky/bluesky.php                                             
 ------- ---------------------------------------------------------------- 
  :1067   Array has 2 duplicate keys with value 'verb' ('verb', 'verb').  
          🪪  array.duplicateKey                                          
 ------- ---------------------------------------------------------------- 

 ------ --------------------------------------------------------------------- 
  Line   cld/cld.php                                                          
 ------ --------------------------------------------------------------------- 
  :25    Instantiated class CLD2Detector not found.                           
         🪪  class.notFound                                                   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  :27    Access to constant UTF8 on an unknown class CLD2Encoding.            
         🪪  class.notFound                                                   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ --------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------- 
  Line   convert/convert.php                                                  
 ------ --------------------------------------------------------------------- 
  :46    Access to property $bases on an unknown class TP_Converter.          
         🪪  class.notFound                                                   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  :59    Call to method findBaseUnit() on an unknown class TP_Converter.      
         🪪  class.notFound                                                   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  :61    Call to method convert() on an unknown class TP_Converter.           
         🪪  class.notFound                                                   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  :66    Access to property $bases on an unknown class TP_Converter.          
         🪪  class.notFound                                                   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  :67    Call to method convert() on an unknown class TP_Converter.           
         🪪  class.notFound                                                   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  :91    Instantiated class TP_Converter not found.                           
         🪪  class.notFound                                                   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ --------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------- 
  Line   diaspora/diasphp.php                                                      
 ------ -------------------------------------------------------------------------- 
  :14    Access to an undefined property Diasphp::$token_regex.                    
         🪪  property.notFound                                                     
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  :16    Access to an undefined property Diasphp::$pod.                            
         🪪  property.notFound                                                     
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  :28    Access to an undefined property Diasphp::$pod.                            
         🪪  property.notFound                                                     
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  :38    Access to an undefined property Diasphp::$token_regex.                    
         🪪  property.notFound                                                     
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  :54    Access to an undefined property Diasphp::$pod.                            
         🪪  property.notFound                                                     
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  :92    Access to an undefined property Diasphp::$pod.                            
         🪪  property.notFound                                                     
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
 ------ -------------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------- 
  Line   libravatar/Services/Libravatar.php                                    
 ------ ---------------------------------------------------------------------- 
  :164   Result of method Services_Libravatar::checkOptionsArray() (void) is   
         used.                                                                 
         🪪  method.void                                                       
  :460   Method Services_Libravatar::srvGet() should return string but return  
         statement is missing.                                                 
         🪪  return.missing                                                    
 ------ ---------------------------------------------------------------------- 

 ------ ------------------------------------------------------------ 
  Line   mailstream/mailstream.php                                   
 ------ ------------------------------------------------------------ 
  :381   Class PHPMailer referenced with incorrect case: PHPmailer.  
         🪪  class.nameCase                                          
 ------ ------------------------------------------------------------ 

 ------- ------------------------------------------------------- 
  Line    mailstream/phpmailer/class.phpmailer.php               
 ------- ------------------------------------------------------- 
  :1522   Instantiated class SMTP not found.                     
          🪪  class.notFound                                     
          💡 Learn more at                                       
             https://phpstan.org/user-guide/discovering-symbols  
  :2696   Function set_magic_quotes_runtime not found.           
          🪪  function.notFound                                  
          💡 Learn more at                                       
             https://phpstan.org/user-guide/discovering-symbols  
  :2708   Function set_magic_quotes_runtime not found.           
          🪪  function.notFound                                  
          💡 Learn more at                                       
             https://phpstan.org/user-guide/discovering-symbols  
 ------- ------------------------------------------------------- 

 ------- -------------------------------------------------------------------------- 
  Line    pnut/lib/phpnut.php                                                       
 ------- -------------------------------------------------------------------------- 
  :128    Access to an undefined property phpnut\phpnut::$_clientId.                
          🪪  property.notFound                                                     
          💡 Learn more:                                                            
             https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  :129    Access to an undefined property phpnut\phpnut::$_clientSecret.            
          🪪  property.notFound                                                     
          💡 Learn more:                                                            
             https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  :165    Method phpnut\phpnut::getAuthUrl() uses native union types but            
          they're supported only on PHP 8.0 and later.                              
  :165    Parameter $scope of method phpnut\phpnut::getAuthUrl() has invalid        
          type phpnut\null.                                                         
          🪪  class.notFound                                                        
  :260    Method phpnut\phpnut::checkScopes() uses native union types but           
          they're supported only on PHP 8.0 and later.                              
  :454    Method phpnut\phpnut::httpReq() uses native union types but they're       
          supported only on PHP 8.0 and later.                                      
  :790    Method phpnut\phpnut::getUserPosts() uses native union types but          
          they're supported only on PHP 8.0 and later.                              
  :808    Method phpnut\phpnut::getUserMentions() uses native union types but       
          they're supported only on PHP 8.0 and later.                              
  :922    Method phpnut\phpnut::getBookmarked() uses native union types but         
          they're supported only on PHP 8.0 and later.                              
  :1106   Method phpnut\phpnut::getUser() uses native union types but they're       
          supported only on PHP 8.0 and later.                                      
  :1137   Method phpnut\phpnut::followUser() uses native union types but            
          they're supported only on PHP 8.0 and later.                              
  :1151   Method phpnut\phpnut::unfollowUser() uses native union types but          
          they're supported only on PHP 8.0 and later.                              
  :1167   Method phpnut\phpnut::getFollowing() uses native union types but          
          they're supported only on PHP 8.0 and later.                              
  :1183   Method phpnut\phpnut::getFollowingIDs() uses native union types but       
          they're supported only on PHP 8.0 and later.                              
  :1199   Method phpnut\phpnut::getFollowers() uses native union types but          
          they're supported only on PHP 8.0 and later.                              
  :1215   Method phpnut\phpnut::getFollowersIDs() uses native union types but       
          they're supported only on PHP 8.0 and later.                              
  :1241   Method phpnut\phpnut::muteUser() uses native union types but they're      
          supported only on PHP 8.0 and later.                                      
  :1253   Method phpnut\phpnut::unmuteUser() uses native union types but            
          they're supported only on PHP 8.0 and later.                              
  :1336   Instantiated class phpnut\CurlFile not found.                             
          🪪  class.notFound                                                        
          💡 Learn more at                                                          
             https://phpstan.org/user-guide/discovering-symbols                     
  :1451   Method phpnut\phpnut::getExistingPM() uses native union types but         
          they're supported only on PHP 8.0 and later.                              
  :1692   Method phpnut\phpnut::createMessage() uses native union types but         
          they're supported only on PHP 8.0 and later.                              
  :1805   Class phpnut\phpnutException referenced with incorrect case:              
          phpnut\PhpnutException.                                                   
          🪪  class.nameCase                                                        
  :1808   Class phpnut\phpnutException referenced with incorrect case:              
          phpnut\PhpnutException.                                                   
          🪪  class.nameCase                                                        
  :1811   Class phpnut\phpnutException referenced with incorrect case:              
          phpnut\PhpnutException.                                                   
          🪪  class.nameCase                                                        
  :1814   Class phpnut\phpnutException referenced with incorrect case:              
          phpnut\PhpnutException.                                                   
          🪪  class.nameCase                                                        
  :1826   Undefined variable: $path                                                 
          🪪  variable.undefined                                                    
  :1843   Class phpnut\phpnutException referenced with incorrect case:              
          phpnut\PhpnutException.                                                   
          🪪  class.nameCase                                                        
 ------- -------------------------------------------------------------------------- 

 ------- -------------------------------------------------------------------------- 
  Line    pumpio/oauth/http.php                                                     
 ------- -------------------------------------------------------------------------- 
  :365    Access to an undefined property http_class::$content_length_set.          
          🪪  property.notFound                                                     
          💡 Learn more:                                                            
             https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  :994    Undefined variable: $php_errormsg                                         
          🪪  variable.undefined                                                    
  :995    Undefined variable: $php_errormsg                                         
          🪪  variable.undefined                                                    
  :1536   Access to an undefined property http_class::$content_length_set.          
          🪪  property.notFound                                                     
          💡 Learn more:                                                            
             https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  :1722   Instantiated class sasl_client_class not found.                           
          🪪  class.notFound                                                        
          💡 Learn more at                                                          
             https://phpstan.org/user-guide/discovering-symbols                     
  :1736   Undefined variable: $interactions                                         
          🪪  variable.undefined                                                    
  :1736   Undefined variable: $message                                              
          🪪  variable.undefined                                                    
  :1758   Undefined variable: $message                                              
          🪪  variable.undefined                                                    
  :1758   Undefined variable: $message                                              
          🪪  variable.undefined                                                    
  :1828   Undefined variable: $interactions                                         
          🪪  variable.undefined                                                    
  :1828   Undefined variable: $message                                              
          🪪  variable.undefined                                                    
  :1834   Undefined variable: $message                                              
          🪪  variable.undefined                                                    
  :1834   Undefined variable: $message                                              
          🪪  variable.undefined                                                    
  :1965   Access to an undefined property http_class::$content_length_set.          
          🪪  property.notFound                                                     
          💡 Learn more:                                                            
             https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
 ------- -------------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------- 
  Line   s3_storage/src/S3Client.php                                           
 ------ ---------------------------------------------------------------------- 
  :28    Parameter $config of method                                           
         Friendica\Addon\s3_storage\src\S3Client::__construct() has invalid    
         type Akeeba\Engine\Postproc\Connector\S3v4\Configuration.             
         🪪  class.notFound                                                    
  :30    Instantiated class Akeeba\Engine\Postproc\Connector\S3v4\Connector    
         not found.                                                            
         🪪  class.notFound                                                    
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols   
  :84    Call to static method createFromData() on an unknown class            
         Akeeba\Engine\Postproc\Connector\S3v4\Input.                          
         🪪  class.notFound                                                    
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols   
  :97    Caught class                                                          
         Akeeba\Engine\Postproc\Connector\S3v4\Exception\CannotDeleteFile not  
         found.                                                                
         🪪  class.notFound                                                    
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols   
 ------ ---------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------- 
  Line   s3_storage/src/S3Config.php                                          
 ------ --------------------------------------------------------------------- 
  :76    Method Friendica\Addon\s3_storage\src\S3Config::getConfig() has      
         invalid return type                                                  
         Akeeba\Engine\Postproc\Connector\S3v4\Configuration.                 
         🪪  class.notFound                                                   
  :78    Instantiated class                                                   
         Akeeba\Engine\Postproc\Connector\S3v4\Configuration not found.       
         🪪  class.notFound                                                   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  :179   Instantiated class                                                   
         Akeeba\Engine\Postproc\Connector\S3v4\Configuration not found.       
         🪪  class.notFound                                                   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  :218   Instantiated class Akeeba\Engine\Postproc\Connector\S3v4\Connector   
         not found.                                                           
         🪪  class.notFound                                                   
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ --------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------- 
  Line   statusnet/library/codebirdsn.php                                     
 ------ --------------------------------------------------------------------- 
  :901   Result of method CodebirdSN\CodebirdSN::_buildMultipart() (void) is  
         used.                                                                
         🪪  method.void                                                      
 ------ --------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------- 
  Line   tictac/tictac.php                                                         
 ------ -------------------------------------------------------------------------- 
  :167   Access to an undefined property tictac::$mefirst.                         
         🪪  property.notFound                                                     
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  :181   Undefined variable: $o                                                    
         🪪  variable.undefined                                                    
  :182   Access to an undefined property tictac::$mefirst.                         
         🪪  property.notFound                                                     
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  :186   Undefined variable: $o                                                    
         🪪  variable.undefined                                                    
  :187   Access to an undefined property tictac::$mefirst.                         
         🪪  property.notFound                                                     
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  :632   Access to an undefined property tictac::$mefirst.                         
         🪪  property.notFound                                                     
         💡 Learn more:                                                            
            https://phpstan.org/blog/solving-phpstan-access-to-undefined-property  
  :632   Undefined variable: $o                                                    
         🪪  variable.undefined                                                    
 ------ -------------------------------------------------------------------------- 

 [ERROR] Found 78 errors                                                        
```

</details> 

To fix this errors I will create PRs at the https://github.com/friendica/friendica-addons repository. If I have an activated account at git.friendi.ca I could fix the errors there.

Required PRs:

- [x] https://github.com/friendica/friendica-addons/pull/1364
- [x] https://github.com/friendica/friendica-addons/pull/1365
- [x] https://github.com/friendica/friendica-addons/pull/1366
- [x] https://github.com/friendica/friendica-addons/pull/1367
- [x] https://github.com/friendica/friendica-addons/pull/1368
- [x] https://github.com/friendica/friendica-addons/pull/1369

### CODE REVIEW

**Comment by MrPetovan** [comment]
What I'll do is pull your GitHub addons remote, create branches and submit it on the Gitea repository.

**Comment by Art4** [comment]
@MrPetovan May I ask what the point is behind the addon repo being saparated from the Friendica repo? If I have understood correctly, the addon folder should be completely optional. Nevertheless, the addon folder has a lot of dependencies on the Friendica repo, which makes changes in the Friendica repo difficult because you have to pay attention to external dependencies that you can't easily check.

In my opinion, the addon repo code should be in the Friendica repo and could be split while a release build or even mirrored in sub-repos.

Alternatively, there should be contracts in the Friendica repo for which BC is guaranteed. The addons can then only access these interfaces.

In general, an EventDispatcher ([PSR-14](https://www.php-fig.org/psr/psr-14/)) would be suitable for communication between Friendica and add-ons.

**Comment by MrPetovan** [comment]
The Addons repo is separated because it is optional. You can run Friendica without any addons. The addons repo has dependency on the base Friendica repository for obvious reasons, but the opposite isn't true, the base repository doesn't have dependencies on the addons.

This means that the addons need to be changed every time the underlying API changes, but fortunately it doesn't happen too often.

**Comment by nupplaphil** [comment]
Decoupling stands on my list as well. @Art4 have a look at `Monolog` plugin. And the Core can be found at `Core\Hook` folder. I tried to introduce different Strategies for decoupling Add-ons from the core. 

Mostly, the add-ons are alternating output in serval ways, so the `EventDispatcher` isn't applicable for everything. For example,  I introduced the Strategy pattern. I have to search, but I think I described the functionality somewhere in the docs :D

**Comment by nupplaphil** [comment]
And the overall goal a few years ago, was to move as much as possible to `git.friendi.ca` .. That's why the codebases are now separated

**Comment by Art4** [comment]
> Decoupling stands on my list as well. @Art4 have a look at `Monolog` plugin. And the Core can be found at `Core\Hook` folder. I tried to introduce different Strategies for decoupling Add-ons from the core.

I would abstract more and more tools behind PSRs if possible. So instead of explicit calling Monolog, we should work with PSR-3: Logger Interface, instead of Dice we should use PSR-11: Container interface and instead of Core\Hook we should use PSR-14: Event Dispatcher.

> Mostly, the add-ons are alternating output in serval ways, so the `EventDispatcher` isn't applicable for everything. For example, I introduced the Strategy pattern. I have to search, but I think I described the functionality somewhere in the docs :D

Alternating output through EventDispatcher is not a problem. See the [approaches for PSR-14](https://www.php-fig.org/psr/psr-14/meta/#4-approaches):

> **4.1 Use cases considered**
> 
> The Working Group identified four possible workflows for event passing, based on use cases seen in the wild in various systems.
> 
>    - One-way notification. ("I did a thing, if you care.")
>    - Object enhancement. ("Here's a thing, please modify it before I do something with it.")
>    - Collection. ("Give me all your things, that I may do something with that list.")
>    - Alternative chain. ("Here's a thing; the first one of you that can handle it do so, then stop.")
> 

So this is only a question of the Event objects. At the moment the `Hook::callAll()` method requires a parameter by reference.

```php
$appMenu = [];

$arr = ['app_menu' => $appMenu];

// Call the hook so addons can add entries for the app_menu
Hook::callAll('app_menu', $arr);

$appMenu = $arr['app_menu'];
```

Instead of this reference we should create an event class for every hook (it is also possible to use generic event classes for different hooks). If we give the events methods to change the content data then addons can change the data and the event dispatcher will give us the modified event back.

```php
class AppMenuEvent implements Event()
{
    public function __construct(
        private array $data,
    ) {}

    public function addEntry(string $name): void
    {
        $this->data[] = $name;
    }

    public function replaceEntries(array $data): void
    {
        $this->data = $data;
    }

    public function getEntries(): array
    {
        return $this->data;
    }
}

$appMenu = [];

// Call the dispatcher so addons can add entries for the app_menu
// $appMenuEvent is the AppMenuEvent object.
$appMenuEvent = $eventDispatcher->dispatch(
    new \Friendia\Core\Event\AppMenuEvent($appMenu),
);

$appMenu = $appMenuEvent->getEntries();
```

**Comment by nupplaphil** [comment]
I know what you mean. But some addons are not just events, they are alternatives and can be set (like e.g. LoggerInterface, or the [StorageBackend.md](https://github.com/friendica/friendica/blob/2024.09-rc/doc/AddonStorageBackend.md). Therefor I designed the [StrategyHooks](https://github.com/friendica/friendica/blob/2024.09-rc/doc/StrategyHooks.md)

Other addons are processing data like a pipeline, whereas an specific addon must be the last one (like the encryption-addon for mailing).

I found my braindump: https://github.com/friendica/friendica/pull/12680 :)
It was still an idea, but the parts of `src/Core/Hooks` already represent parts of it

**Comment by Art4** [comment]
@nupplaphil Thank you very much for pointing this out. I will need to take a deeper look into this but at first glance it should everything possible with PSR-14. Alternatives could be provided by addons by creating something like an `RegisterDependencyEvent` and we can extend PSR-14 so a listener could be registered with a numeric priority order like in `Hook::register()` and/or work with stoppable events.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
