### PR TITLE
Add phpinfo page only accessible to admins

### PR DESCRIPTION
**Pull request by MrPetovan**
A quickie because I needed it and I assume other admin may need it too.

### CODE REVIEW

**Comment by tobiasd** [comment]
I would like it more, when the page navigation etc. would keep intact.

**Comment by annando** [comment]
We could possibly do this with an ```<iframe>...</iframe>``` thing?

**Comment by MrPetovan** [comment]
@annando I tried, but the phpinfo sets the the info table width at 934px wide, which doesn't sit well in the 622px wide of the frio interface.

**Comment by tobiasd** [comment]
> @annando I tried, but the phpinfo sets the the info table width at
> 934px wide, which doesn't sit well in the 622px wide of the frio
> interface.

Sad. But ok then.

**Pull request merged**
