### PR TITLE
Update Conversation.php

### PR DESCRIPTION
**Pull request by foss-**
typo: people not peiple

### CODE REVIEW

**Comment by Raroun** [comment]
this should better be done on transifex - changing source strings are forcing the translators to start all over :)

**Comment by AlfredSK** [comment]
> this should better be done on transifex - changing source strings are forcing the translators to start all over :)

I see it differently. Spelling errors in the original EN language cannot be corrected on Transifex. But you can select EN as language in Friendica. For people who like to use EN - like me :-) - the error would never disappear. Or am I wrong?

**Comment by Raroun** [comment]
English is the source yes, But translations are done to `en_us` and `en_gb` as far as i know.

Unbenannt1

`en_us` and `en_gb` seems to be translated correct already (see screenshot).
I am not in the english translation team so i can´t see who did the translation :(

**Comment by foss-** [comment]
@MrPetovan did the translation. I am still slightly confused however since friendica offers `English (Default)` in the language settings, meaning users using that language would still see the string with the typo. Maybe that language should be remove from the user facing selection?

**Comment by Raroun** [comment]
I am still learning too and this is also confusing to me.

**Comment by MrPetovan** [comment]
@Raroun Thank you for your inputs, they are correct.

@foss- Thank you for the PR but it won't be accepted as is, I made sure to fix the translations for en-US and en-GB just before @Raroun took a screenshot but they haven't been integrated in Friendica yet.

I agree we should remove "English (Default)".

**Comment by Raroun** [comment]
@MrPetovan thanks for the clarification on "English (Default)".

**Pull request closed without merging**
