### PR TITLE
ConfigFileSave Hardening

### LINKED ISSUE #6941: Failure during config-file changing without a ',' at the end
```Parse error: syntax error, unexpected ''basepath'' (T_CONSTANT_ENCAPSED_STRING), expecting ']' in /path/to/friendica/config/local.config.php on line 96```

My config entry before this had no ```,```:

```
                'pidfile' => '/tmp/daemon.pid'
                'basepath' => '/path/to/friendica',
```

_Originally posted by @annando in https://github.com/friendica/friendica/pull/6935#issuecomment-476860496_

### PR DESCRIPTION
**Pull request by nupplaphil**
Alternative to #6961 
Fixes #6941 
FollowUp #6920 

This time I'm using the whole `ConfigCache` for generating the new config file.
=> This is still draft, because I need to add a method to find comments for the *.htconfig.php and *.config.php* file format.

But the rest of the logic is now much less complex than the idea before :-)
=> And all tests would work (if I don't have to manage comments ;-) )

### CODE REVIEW

**Comment by nupplaphil** [comment]
I think we can live with the fact that we don't migrate comments in case of the upgrade path.
The old comments are still inside the `local.config.php.old` file, which can get retrieved from there.

I tried different ways to preserve comments during the upgrade path, but after the third way and 100s of code lines, I think it's not worth for it..

What do you think?
=> This method shouldn'/isn't get used on a regular base.

**Comment by tobiasd** [comment]
I usually add comments to config files to remind myself when looking again at the config file in a week about why I changed something and what the original value was before. Or just when experimenting with configuration values.

So personally I would react rather harsh on a piece of software rewriting a config file and stripping off my comments.

**Comment by MrPetovan** [comment]
I wouldn't be happy with this either. I wouldn't mind if the extraneous line feeds were removed but the comments should stay. Maybe you need to use a php file lexer for that?

**Comment by nupplaphil** [comment]
Further investigations -> close ..

**Comment by MrPetovan** [comment]
Maybe this needs to be a line in the documentation to prompt the admin for a manual edit?

**Pull request closed without merging**
