### PR TITLE
Custom PHPCS ruleset

### PR DESCRIPTION
**Pull request by Rudloff**
Hello,

[Developer doc](https://github.com/friendica/friendica/blob/develop/doc/Developers-Intro.md#coding-standards) says to follow the PSR2 spec.
However PSR2 recommends spaces for indentation but Friendica uses tabs.

So when running `phpcs --standard=PSR2`, it outputs this error a lot of times:
```
Spaces must be used for alignment; tabs are not allowed
```

In order to avoid this, I created a custom ruleset that uses every rule from PSR2 except the no tabs rule.
It can be used like this: `phpcs --standard=ruleset.xml`

### CODE REVIEW

**Comment by zeroadam** [comment]
@Rudloff I know it's obscure, but there was an existing ruleset in the /vendor/pear/language_detect folder phpcs.xml that I had modified a while back, it has a few more rules/exclusions in it. I'm all for it living somewhere else, but I suggest incorporating it with yours.

**Comment by Rudloff** [comment]
Oh I didn't find this one. I guess we can use but it should really be mentioned in Developers-Intro.md.

**Comment by MrPetovan** [comment]
I don’t think we should use the Text_LanguageDetect phpcs.xml file, instead whatever relevant is inside should be pulled where you created it and the doc shpuld be updated as you did.

**Comment by MrPetovan** [comment]
I found myself needing this file to configure the NetBeans PHPCodeSniffer plugin, can you please resubmit it?

**Comment by MrPetovan** [comment]
Thanks!

**Comment by zeroadam** [comment]
@MrPetovan is this single exclude enough to satisfy our current coding standards? The file I mentioned, that I have been using included other things we do "different" than standard PSR2. Also if that is the case, the phpcs.xml could then be deleted?

**Comment by MrPetovan** [comment]
It's enough for my display not to light up like a Christmas tree because of the tabs, but I see what you mean, and the specific phpcs.xml content probably should be moved to ruleset.xml just because we shouldn't manually add anything in the vendor subfolders.

**Comment by MrPetovan** [comment]
Part of #2103

**Pull request merged**
