### PR TITLE
Filter contact search by blocked remote domains

### LINKED ISSUE #12555: Accounts on blocked servers shouldn't appear in the search results
### Is the feature request related to a problem? Please describe.

If a server is locked on an instance, there should be no communication with a server. This also includes connecting to new contacts. It would not make sense to connect to a contact if no communication can take place afterwards.

### Describe the feature you'd like

If a person search is started and pontential hits are returned, then the hits that are locked for this instance should be filtered out.

### PR DESCRIPTION
**Pull request by MrPetovan**
Fix #12555

### CODE REVIEW

**Comment by annando** [comment]
I would prefer to extend the `account-view` with the `blocked` field from the `gserver` table. Then we just have to perform the contact search on that view instead of the contact table and can filter for that field.

**Comment by MrPetovan** [comment]
It's a slightly larger task that I'm not sure fits in 2023.03-rc. And my changes can be reused for the number of filtered accounts.

**Comment by annando** [comment]
My PR #12956 will improve the local search. Your PR will be helpful when the search is configured to be done via the global directory.

**Comment by annando** [comment]
@MrPetovan do you have got a look at this PR? AFAIK the plan was to display the blocked contact as well but with a hint?

**Comment by MrPetovan** [comment]
Yes, and I was waiting for your changes, but I haven’t taken the time since your PR was merged.

**Comment by MrPetovan** [comment]
This branch has now been rebased on top of @annando 's changes.

**Pull request merged**
