### PR TITLE
frio: a short contact informations will be provided at the second nav…

### PR DESCRIPTION
**Pull request by rabuzarus**
… bar by scrolling down (on pages where vcard is available)

### CODE REVIEW

**Comment by annando** [comment]
There are currently merge conflicts. Can you solve them?

**Comment by rabuzarus** [comment]
I will solve this, but maybe you have to wait till evening

**Comment by rabuzarus** [comment]
Ahhh, I always get in trouble with the .gitignore after merge develop in the actual branch

**Comment by rabuzarus** [comment]
I hope that nothing got lost

**Comment by rabuzarus** [comment]
I think it's ready now :-)

**Pull request merged**
