### PR TITLE
Delete cached avatar data from storage

### PR DESCRIPTION
**Pull request by annando**
Free storage space by deleting the avatar cache data.

### CODE REVIEW

**Comment by SpcCw** [comment]
Do I understand correctly that this removes all cached avatars for all contacts so they can be refetched and cached again?

**Comment by annando** [comment]
@SpcCw that command does make sense in combination with the setting to not cache avatars.

**Comment by SpcCw** [comment]
> @SpcCw that command does make sense in combination with the setting to not cache avatars.

Yes, I understand the main purpose. I wanted to ask something else but phrased it poorly :) If I like avatar caching for performance reasons can I run this to prune the cache so it removes all avatars and then ones that are actually used are refetched or this isn't a good idea?

My server runs for five years and I have a lot of cached avatars some of which are likely old and belong to missing or abandoned accounts.

**Comment by annando** [comment]
Yes, this should work for that purpose as well, although the automatic clean up should do this already.

**Pull request merged**
