### PR TITLE
Add expected method MailBuilder->withHeaders

### PR DESCRIPTION
**Pull request by MrPetovan**
Address https://github.com/friendica/friendica/issues/9250#issuecomment-696055412
Follow-up to #9242

### CODE REVIEW

**Comment by annando** [comment]
I don't need to understand this, I guess? :-) Have you checked if mails are now sent? BTW: Does this mean that with the stable version no mails cannot be sent at all?

**Comment by AlfredSK** [comment]
I get notification mails when I use the test via 'notifyall'.
I get admin mails about ~~registrations and~~ deletions.

So, some mails do work apparently.

Edit: It is worse than expected.

**Comment by MrPetovan** [comment]
There used to be a method `MailBuilder->addHeaders` that was removed in #9242 but not the corresponding call. To maintain the ability for addons to modify the headers, I restored it using the same naming convention `with*`. This will ensure mails are sent, but it will break any current unofficial addon that was adding additional string headers.

**Comment by AlfredSK** [comment]
Ok. I have to correct myself.

I don't get any notification mails about new PMs, new comments, about mentions etc.
A new user will never get a mail about the registration. After submitting the registration form a white page of death happens. So the user will not know the password.
On the other hand password reset mails do work.


**So, apart from a couple of admin info mails (like a user deleted an account) and password reset mails the mail creation and transmission seems to be dead.**

When this is fixed we should do a _bugfix release_, I guess.

**Comment by MrPetovan** [comment]
Yup.

**Comment by AlfredSK** [comment]
I applied your changes manually. Fatal error gone. I did a test registration. Worked. I got the registration email with my password.
Then I enabled all notification settings and commented with an explicit mention. I got a notification mail about it.
Seems ok now.

**Comment by AlfredSK** [comment]
Regression! The double Message-ID header is back.

```
Date: Mon, 21 Sep 2020 17:02:02 +0000
To: alfred@libranet.de
From: "LIBRANET.de" <admin@libranet.de>
Reply-To: "LIBRANET.de" <admin@libranet.de>
Subject: =?UTF-8?Q?[Friendica:Notify]_Venera_One_=F0=9F=8D=80_tagged_you_(alfred@libranet.de)?=
Message-ID: <3I7fIJ4HKygsePQcGM2S5Yxwoht79oBlP8ps40cma0@libranet.de>
X-Mailer: PHPMailer 6.1.4 (https://github.com/PHPMailer/PHPMailer)
Precedence: list
X-Friendica-Host: libranet.de
X-Friendica-Platform: Friendica
X-Friendica-Version: 2020.09
List-ID: <notification.libranet.de>
List-Archive: <https://libranet.de/notifications/system>
X-Friendica-Account: <alfred@libranet.de>
Message-ID: <0b6b25a8-795f-65da-65da-283524829766@librabox2.libranet.de>
MIME-Version: 1.0
Content-Type: multipart/alternative;
```

**Comment by nupplaphil** [comment]
.... But how.... I'm confused and sorry for the regression in the stable now :( ...

**Comment by MrPetovan** [comment]
But at least you have some time to work on it.

**Comment by SpcCw** [comment]
Applied this manually as well and noticed that Sender Name is www-data now. Is this related to this work in progress or is it separate issue?

Now and before:
image

Headers are ok for Reply-To but not From:
image

**Pull request merged**
