### PR TITLE
[WIP] #8374: Limit post content by rendered height instead of number of characters

### PR DESCRIPTION
**Pull request by wiwie**
Initial implementation hard-coded into core friendica resources

### CODE REVIEW

**Comment by MrPetovan** [comment]
I thought about something else: we have a mechanism to automatically collapse post content based on multiple user-defined rules, this height limiting system shouldn't apply to collapsed posts.

**Comment by wiwie** [comment]
yes, ignoring asynchronous changes to the posts, such as deferred image loading or twitter widgets and others, makes it definitely easier.

How would you change the structure of this into an add-on?

I'm not sure whether I get your point regarding collapsed posts. Are you talking about the fact that my version also affects some of the comments?

**Comment by MrPetovan** [comment]
I think your version would apply the height limit once someone expands a collapsed post (because it would be tagged as NSFW for example), requiring another click to expand it again because of the height limit.

The way of making this into an addon is to move the "Show more..." toggle to the javascript, adding it dynamically to posts instead of changing the template for this.

**Comment by wiwie** [comment]
Yes okay, good point with the collapsed posts. Will look into it.

But otherwise, the principle is that I wrap all my css & JavaScript in the add-on, and the changes that I introduced in the template file I need to somehow inject via JavaScript? Or is there a way that an add-on can modify such templates?

**Comment by MrPetovan** [comment]
No, no addon can modify a core template. But you can manipulate the DOM in Javascript without a template change.

**Comment by wiwie** [comment]
What is the easiest way of detecting whether a post is collapsible, i.e. contains a CW ? Does such a post get a specific css class or do I need to check for a specific class/tag in the post's content?

**Comment by MrPetovan** [comment]
Example of `wall-item-body` tag of a collapsed post:
```html
<div class="wall-item-body e-content p-name" id="wall-item-body-2800060">
    <p>
        Filtered language: German
        <button type="button" id="content-filter-wrap-07cae1e4" class="btn btn-default btn-xs content-filter-button" onclick="openClose('content-filter-07cae1e4');">
            <i class="glyphicon glyphicon-eye-open"></i> Reveal/hide
        </button>
    </p>
    <div id="content-filter-07cae1e4" class="content-filter-content" style="display: none;">
        Ich liebe es ja mir Sicherheitskonzepte auszudenken.
        <br>
        <br>Da frage ich mich doch glatt ob es eine Möglichkeit gibt das entschlüsseln einer Festplatte unter Linux abhängig von zwei USB Sticks mit Keyfiles drauf oder ähnlichem zu machen. Das wäre wohl dann mal eine Wochenend Recherche Arbeit.
    </div>
</div>
```

**Pull request closed without merging**
