### PR TITLE
Make the tests work again with PHP 7.2

### PR DESCRIPTION
**Pull request by annando**
This PR includes stuff to make the tests running again with PHP 7.2 by deactivating PDO.

### CODE REVIEW

**Comment by annando** [comment]
As expected, this will last a little bit longer :-)

**Comment by MrPetovan** [comment]
Why's that?

**Comment by annando** [comment]
I'm not completely familiar with how the tests are working, I can't test them on my machine and I also do have still some problems with this class stuff :-)

**Comment by annando** [comment]
I possibly should have marked this as draft PR :-) I wanted to clean up the code a little bit and only do this PDO disabling when really needed.

**Comment by MrPetovan** [comment]
Not sure tests are ran with draft PRs?

**Comment by annando** [comment]
I'm not sure either.

**Pull request merged**
