### PR TITLE
Frio: Hovercard is now a core function

### PR DESCRIPTION
**Pull request by annando**
Like discussed here: https://github.com/friendica/friendica/issues/2537

Additionally it is changed so that it now contains these actions:
bildschirmfoto 2016-05-29 um 16 01 26

The space between the actions is reduced. And instead of deleting there is now an option for the posts.

For testing purposes the page mode for html is set to "minimal".

### CODE REVIEW

**Comment by rabuzarus** [comment]
@annando 
short question:
why is function hovercard_init() needed?

**Comment by annando** [comment]
It is for setting the mode variable so that one can test the html output. It has to be done in the "init" part.

**Comment by rabuzarus** [comment]
As far as I can see it's correct. But I have written it :-) So I would leave it to someone else to merge this

**Comment by annando** [comment]
I jut have copied it :-)

**Pull request merged**
