### PR TITLE
Display the languages in the post

### PR DESCRIPTION
**Pull request by annando**
For having the ability to adjust the language filters we can now display the detected languages in the post.

### CODE REVIEW

**Comment by tobiasd** [comment]
Reverting to the state when the language was just displayed in the footer of the postings would be to much like a circle right ;-)

**Comment by annando** [comment]
Oh yeah, that rings a bell ...

**Comment by MrPetovan** [comment]
But why `javascript:alert()`? And why show the languages at all?

**Comment by tobiasd** [comment]
So that you can make educated guesses what value is a good value for e.g. the language filter. For the postings I've checked, the new detection system seems to have higher probability values then the old one had, so the setting might be adopted to get better results.

**Comment by annando** [comment]
@tobiasd in fact when I changed that language detection stuff I realized that people have to put values in the langfilter addon - not knowing what good values look alike. Also currently I'm working on cleaning the body from content that could distract the detection.

**Comment by annando** [comment]
@MrPetovan I would like to move the composer package for fetching the real name out of the ISO codes into the core. Can I just remove all the stuff from the langfilter addon and add the package to the core composer?

**Comment by MrPetovan** [comment]
Absolutely. Make sure to remove the `require` call as well in `addon/langfilter/langfilter.php`.

**Pull request merged**
