### PR TITLE
Remove email subject encoding from ItemCCEmail constructor

### LINKED ISSUE #11666: Email subject is double-encoded when including Unicode emojis
> The subject of the received email looks weird. Is this normal/expected? 
> 
> Thunderbird UI:
> `Subject: =?UTF-8?B?W0ZyaWVuZGljYV0gVmVuZXJhIE9uZSDwn42AIHBvc3RlZCBhbiB1cGRhdGUu?=`
> 
> Source text of the email:
> `Subject: =?us-ascii?Q?=3D=3FUTF-8=3FB=3FW0ZyaWVuZGljYV0gVmVuZXJhIE9uZ?=  =?us-ascii?Q?SDwn42AIHBvc3RlZCBhbiB1cGRhdGUu=3F=3D?=`

_Originally posted by @AlfredSK in https://github.com/friendica/friendica/issues/11661#issuecomment-1160749018_

### PR DESCRIPTION
**Pull request by MrPetovan**
- It was wrongly re-encoded in Emailer::send

Fixes #11666 

I wasn't able to actually test my change, I'm counting on you @AlfredSK !

### CODE REVIEW

**Review by Quix0r — APPROVED** [review]
Looks fine to me.

**Comment by AlfredSK** [comment]
Merged before testing. But it works. :-)

GUI:
[Friendica] Venera One 🍀 posted an update.

Mail header:
`Subject: =?UTF-8?Q?[Friendica]_Venera_One_=F0=9F=8D=80_posted_an_upda?=  =?UTF-8?Q?te.?=`

Fixed. Thank you!

**Comment by MrPetovan** [comment]
Another satisfied customer!

**Comment by AlfredSK** [comment]
Indeed.

**Pull request merged**
