### PR TITLE
Remove App dependency from Hook::callSingle

### LINKED ISSUE #12665: Monolog führt zur Nichterreichbarkeit der Instanz
I stupidly activated the addon "Monolog", which unfortunately leads to an error and the start page only loads as a white wall.

Running bin/console dbstructure update
gives an error

```
bin/console dbstructure update
PHP Fatal error:  Uncaught TypeError: Argument 5 passed to Friendica\Core\Cache\Factory\Cache::__construct() must implement interface Psr\Log\LoggerInterface, instance of Friendica\Core\Logger\Factory\Logger given in /var/www/html/friendica/src/Core/Cache/Factory/Cache.php:74
Stack trace:
#0 [internal function]: Friendica\Core\Cache\Factory\Cache->__construct()
#1 /var/www/html/friendica/vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs()
#2 /var/www/html/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#3 /var/www/html/friendica/vendor/level-2/dice/Dice.php(247): Dice\Dice->create()
#4 /var/www/html/friendica/vendor/level-2/dice/Dice.php(149): Dice\Dice->Dice\{closure}()
#5 /var/www/html/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#6 /var/www/html/friendica/vendor/level-2/dice/Dice.php(247): Dice\Dice->create()
#7 /var/www/html/friendica/vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}()
#8 /var/www/html/friendica/vendor/level-2/dice/Dice.php(96): Di in /var/www/html/friendica/src/Core/Cache/Factory/Cache.php on line 74
root@xxx:/var/www/html/friendica# 
```

Question: how can I deactivate the addon again without access to the admin area?

PHP: 7.4
SQL: 10.3
Friendica: Stable

### PR DESCRIPTION
**Pull request by MrPetovan**
- This was causing a circular dependency with the `logger_instance` hook

Fix #12665 

Requires https://github.com/friendica/friendica-addons/pull/1351

I'm sorry, there was no other way.

### CODE REVIEW

**Comment by MrPetovan** [comment]
PHPUnit failed because it couldn't find `github.com` 🤷‍♂️

**Comment by annando** [comment]
The errors that I saw in the unit test had been stuff like `TypeError: Argument 1 passed to create_instance() must be an instance of Friendica\App, array given, called in /woodpecker/src/github.com/friendica/friendica/src/Core/Hook.php on line 222` or `ArgumentCountError: Too few arguments to function authtest_authenticate(), 1 passed in /woodpecker/src/github.com/friendica/friendica/src/Core/Hook.php on line 222 and exactly 2 expected`. This sounds to me like if the tests need to be adapted to the change in the hooks.

**Comment by MrPetovan** [comment]
Great, the error for the PHPUnit pipeline version PHP 8.0 covered for actual errors, thanks for checking!

**Comment by MrPetovan** [comment]
Great, so the PHPUnit pipeline chokes again on DNS resolution, and the license check fails on `tests/Util/authtest/authtest.php` because it has an addon-looking license header. 😓

**Pull request merged**
