### PR TITLE
Move DBA to src/ part 3.2: Remove DBM class

### PR DESCRIPTION
**Pull request by MrPetovan**
Part 3.2 of #5410
Follow-up to #5431 (commits are duplicated until it's merged)

This was a long time coming, the DBM class outlived its usefulness. Now all the database methods are conveniently available in DBA.

Addon pendant: https://github.com/friendica/friendica-addons/pull/658

### CODE REVIEW

**Comment by Quix0r** [comment]
Conflicts have been found.

**Comment by MrPetovan** [comment]
Conflicts fixed.

**Comment by annando** [comment]
One more to go :-)

**Comment by MrPetovan** [comment]
One more conflict? One more PR?

This doesn't show any conflict at the moment.

**Comment by annando** [comment]
I meant PR https://github.com/friendica/friendica/pull/5439

**Comment by MrPetovan** [comment]
Oh yeah, I'm waiting for this PR to be merged, I couldn't rebase an unmerged branch off another unmerged branch without it failing spectacularly.

**Comment by annando** [comment]
BTW: Are you currently running on this branch? :-)

**Pull request merged**
