### PR TITLE
Disable richtext editor for frio - followup for #2938

### PR DESCRIPTION
**Pull request by annando**
This is a different implementation of pull request https://github.com/friendica/friendica/pull/2938 which solves issues https://github.com/friendica/friendica/issues/2915 and https://github.com/friendica/friendica/issues/2918

It doesn't change user settings like the other pull request.

### CODE REVIEW

**Comment by rabuzarus** [comment]
wouldn't it be better to be more future proof to have an array where we could store multiple features (like `public $theme_disabled_features = array()`) ?

We could loop through this array and set `$x = false` if `$feature` is in this array

**Comment by Hypolite** [comment]
Can't we just add a `features_enabled` and `get_feature` hook to the frio theme or is it only available to addons?

**Comment by annando** [comment]
@Hypolite I did it that way because it is done before in that way as well: https://github.com/friendica/friendica/blob/develop/view/theme/frost-mobile/theme.php#L12-L19

@rabuzarus there could be use cases where some features are disabled for a theme - but maybe there could be use cases where features are always enabled for a theme. I could go in that direction. The current solution is a quick fix because my time in the next week is a little bit limited and I don't want to delay the release.

**Comment by rabuzarus** [comment]
yes to use the hook would be also a possibility

**Comment by rabuzarus** [comment]
>  I did it that way because it is done before in that way as well

Yes but allow threading is a admin setting `Config::get()` with the category `system`. We should be very carefully about what a theme could could change.
But this isn't the case for normal user features which we can address directly through the category `feature` in pconfig.

My suggestestion would be: frio should use the hook for this for a simple reason. To disable a feature or to add a feature (by addons or themes) is exactly the reason for the existence of this hook. So why don't use it?
(Sorry I wasn't aware of the existence of this hook at hackathon).

If we need to disable a feature where we can't use the hook we could add code at this time.
To do it this way does have the advantage:
* we use the infrastructure (code) we already have in place
* we clearer code because we don't insert code for features which could be done nearly the same way some lines below

I really understand that you don't have much time at the moment (really I do). So my question: Should I try to commit another PR this evening?

**Comment by Hypolite** [comment]
@rabuzarus: If you know how to do it with hooks, I'd say yes.

**Comment by rabuzarus** [comment]
@Hypolite yes but I want to wait what @annando says about it since it is his patch

To be honest there is one disadvantage with using hooks. After the update the admin of an instance have to disable frio and have to enable it again so the new hooks get registered in the db

Maybe in the future we can have a way to something like this automatically

**Comment by annando** [comment]
I really would prefer a solution without hooks. Hooks are something for addons where addon code and core code cannot be changed at the same time.

**Comment by annando** [comment]
I - personally - think that these three config variables work great together: https://github.com/annando/friendica/blob/d49325d177cf03b97df250ca3cb081421c541049/boot.php#L532-L534

So I would prefer the current solution

**Pull request merged**
