### PR TITLE
frio - fixed bug in admin users with table sorting #6529

### PR DESCRIPTION
**Pull request by Ixiter**
The block and delete buttons were part of the table's parent element but didnt get replaced.
The table needs to be in a separate container since the ajax finds the table and then replaces its parent element content with the new table.

### CODE REVIEW

**Comment by MrPetovan** [comment]
You sir are a godsend. Thank you for your work!

**Comment by MrPetovan** [comment]
Fixes #6529

**Comment by Ixiter** [comment]
Tahnk you. My very pleasue @MrPetovan. But I am far away from being a "Sir" :D
I love the software and I feel good with the team. 
Sure, I cannot handle the "deeper" core stuff yet, but i can remove these little annoying itchy scratchy things.

**Comment by MrPetovan** [comment]
This is how I started contributing to Friendica as well, lured by the charms of @annando .

**Comment by Ixiter** [comment]
Haha, great. He was the first one I got introduced to by Stefan Münz. And beside Stefan, Michael was the first contact I added followed by more or less other developies. Its funny .. I read about friendica, launched my first fediverse box ever, read some dev stuff, wrote an addon, fixed bugs, discussed dev and support stuff .. but ... I didnt post any public post yet.

**Comment by copiis** [comment]
Yeah @annando is a pirate. He locates the prey, pursues it, separates the weakest member from the pack, and incorporates it into his own pack.

**Comment by Ixiter** [comment]
So his pack is full of weakest members?! Sounds like a plan ... not

**Comment by copiis** [comment]
> So his pack is full of weakest members?! Sounds like a plan ... not

Yes, those who were too weak to resist his charm.

**Pull request merged**
