### PR TITLE
Frio: add admin summary template

### PR DESCRIPTION
**Pull request by rabuzarus**
Frio does now have an own template for the admin summary page

### CODE REVIEW

**Comment by rabuzarus** [comment]
I changed two things
1.)  I corrected some indents
2.) I added/fixed an adminpage div container for the admin page
Many of the other admin template files already contained this adminpage div container. So I added it to some few templates where it was missing. Now the admin templates are consistent on this point.

**Comment by MrPetovan** [comment]
I'm always reluctant to make such changes to base templates because it needs to be tested with many themes I'd rather not have to spend time checking on. 😅

**Comment by rabuzarus** [comment]
I know, I know.
For this PR I hope that it doesn't have a big impact, since it was used before in other templates

**Comment by MrPetovan** [comment]
You hope? 😱

**Comment by annando** [comment]
I guess the hope to not break _too much_ stuff is what drives us, isn't it?

**Pull request merged**
