### PR TITLE
Hotfix for missing Exception class

### PR DESCRIPTION
**Pull request by Hypolite**
Fixes #3423

### CODE REVIEW

**Comment by tobiasd** [comment]
sadly not ;-)

> PHP Fatal error:  Uncaught exception 'Exception' with message 'Basepath /var/www/social.diekershoff.de isn't usable.' in /.../src/App.php:195

**Comment by Hypolite** [comment]
This is a different error, please check the permissions of this folder, it should be readable and writeable by the web server user.

**Comment by tobiasd** [comment]
:+1: it was only rx for the www-data user. Thanks a lot for the quick fix!

**Comment by Hypolite** [comment]
You're welcome!

**Comment by Quix0r** [comment]
I would use `use \Exception;` instead of direct black-slash. That keeps all "imports" in one place only. :-)

**Comment by Hypolite** [comment]
This is a good idea, when I submitted this PR I was in panic because `develop` was completely broken and I forgot about it, but you're right.

**Comment by Quix0r** [comment]
Thank you for opening another PR. :-)

**Comment by Hypolite** [comment]
Well, this was a hotfix, after all.

**Pull request merged**
