### PR TITLE
removed some superfluous spaces in doctype tags

### PR DESCRIPTION
**Pull request by haheute**
I hope this is okay.. I have removed some superfluous spaces, found in `<!DOCTYPE html>` tags .

Discovered this, because of the error message in the screenshot.
After the changes, the error does not disappear.  Maybe it's some other problem with the `friendica.webmanifest`.

doctype-html

### CODE REVIEW

**Comment by haheute** [comment]
sorry . I tried to update my PR to the latest changes in 2024.06-rc
maybe it's all messed up now.. 
Is there something I can do ?

**Comment by annando** [comment]
Have you tried a rebase against the current rc branch?

**Comment by haheute** [comment]
Yes, I tried. . 

From the `2024.06-rc`  branch, I did this: ` git rebase 2024.06-rc remove-spaces-in-doctype `.
Then I did  `git checkout remove-spaces-in-doctype` and did a `git push origin remove-spaces-in-doctype`. That gave me an error message, (can't remember right now), that I googled and found the advice, that I should `git pull` from my branch, first. 
That's what I did, I only had to add a `--rebase` to get it working: `git pull origin remove-spaces-in-doctype --rebase`. At last I pushed again, then it worked.

I don't know if the PR is okay now as it is. Tried that for the 1st time.

I'm sorry for the confusion. When you can't see if the PR is okay, I could also create a new one. It consisted only of some removed whitespaces, should be no problem. Don't want to mess up anything.

**Comment by annando** [comment]
Normally you are in the branch that should be rebased.

**Comment by haheute** [comment]
I have read there are different options, you can rebase while in "master", or while you have the "feature" branch checked out:

> In order to achieve standard rebasing, we follow the following command:
> 
> **git rebase master branch_x**
> where branch_x is the branch we want to rebase

https://www.geeksforgeeks.org/rebasing-of-branches-in-git/

The rebase did not throw an error when I did it. But maybe it is easier and more safe when I just create a new PR .

**Comment by annando** [comment]
I always do my rebases in my development environment, so I'm unsure about the correct command line syntax.

**Comment by haheute** [comment]
I don't feel this is good, this PR. Will now close it.

**Comment by ne20002** [comment]
Hi @haheute. 
We all had this experience with Github's update branch mechanism. Will you create a new PR?

**Comment by haheute** [comment]
Hi @ne20002 .. Thanks for your comment.  I must learn what to do when a PR is already old. How to updated it, or so..

Yes, I want to create a new PR, but maybe not today or tomorrow. It was anyway not very important, just some whitespaces. But I intend to, yes.

**Pull request closed without merging**
