### PR TITLE
Disallow mail addresses for registration

### PR DESCRIPTION
**Pull request by annando**
You can now create a list of domains that are not allowed to register.

### CODE REVIEW

**Comment by tobiasd** [comment]
This will deal with #895 right?

**Comment by annando** [comment]
@tobiasd partially. That issue additionally describes a possibility to control the approval behaviour.

**Comment by tobiasd** [comment]
So with this new setting it is not the case that

* approval required by default
* own TLD is allowed by the allow list
* example.com is blocked by block list

**Comment by annando** [comment]
Correct. This is no domain related change of the approval policy.

**Pull request merged**
