### PR TITLE
update MF2 and vcard data for issue #2629

### PR DESCRIPTION
**Pull request by dissolve**
This adds mf2 and vcard4 corrections and updates to wall_threads and vcard templates

### CODE REVIEW

**Comment by fabrixxm** [comment]
isn't vcard in profile page used by Diaspora to fetch user info?
Are we sure that changes to `diaspora_vcard.tpl` aren't breaking Diaspora protocol?

_moved this comment from issue to pull request..._

**Comment by dissolve** [comment]
the only changes to diaspora_vcard.tpl were to add classes (which should make no difference) with one exception. the removal of class="url" rel="me" , which wrong because the link points to the pod, not an individual user account.   As it stands now it would it implies that one all users on that domain are the same person.

**Comment by dissolve** [comment]
Attempting to contact someone in diaspora who can speak to this .

**Comment by fabrixxm** [comment]
> with one exception. the removal of class="url" rel="me" , which wrong because the link points to the pod, not an individual user account. As it stands now it would it implies that one all users on that domain are the same person.

I understand this, I just want to be sure that Diaspora code don't rely on something like ".entity_url .url" to find the pod url from vcard.

**Comment by annando** [comment]
@SuperTux88 Can you have a look at it?

**Comment by SuperTux88** [comment]
Yes, you can remove the `class="url" rel="me"`, diaspora doesn't use it.

**Comment by tobiasd** [comment]
I think the `rel=me` stuff was part of #1260 and supporting IndieAuth I think it should be put back in place actually.

**Comment by dissolve** [comment]
The problem is that, from what I could tell, the link always pointed to the base domain.  Rel me on the homepage URL is more appropriate. 

Known (withknown.com) uses a single user mode flag to say such behaviour is fine.

Honestly, i think it's rather moot since there is no login mechanism (that i know of) for friendica directly. I can ask @aaronpk to review.  Unless there is something I am missing.  But I would love to get cleaner indieauth login.

**Comment by tobiasd** [comment]
well obviously as the Feature Request is still open, it is work in progress. But as I don't use such services myself it was just my memory telling me those fields had a purpose. Cant say anything about the state of the work ;-)

**Pull request merged**
