### PR TITLE
[develop] Performance: Add memcached support/Improve database cache (redux)

### LINKED ISSUE #4518: Performance: Add Memcached support
See https://friendica.mrpetovan.com/display/735a2029145a96e3a87f168339059262, although this issue is only remotely linked with the initial discussion, I got severely carried away.

### PR DESCRIPTION
**Pull request by MrPetovan**
Redux of #4519
Closes #4518

Kids, don't do this at home.

At heart, it was only about removing the current awful cache clearing mechanism (see https://friendica.mrpetovan.com/display/735a2029145a96e3a87f168339059262).

And then I realized that we only supported Memcache, but not Memcached for caching. So I created an Interface for cache drivers, but then I realized the Session was using the obsolete Memcache mechanism, so I created a new cache session handler, but then I realized that the config values were undocumented, so I created new ones.

It ended up being a 4-in-1 monster PR, and I apologize in advance.

But look at how good the new code looks! And no more random cache clearing on page load!

Removed config values:
- system.memcache
- system.disable_database_session (undocumented)

Added config values:
- system.cache_driver: **database**, memcache, memcached
- system.session_handler: **database**, cache, native
- system.memcached_hosts

Edit: Added multiple Memcached servers support

### CODE REVIEW

**Comment by annando** [comment]
BTW: Concerning these large changes, I would prefer that it was tested for some time. Means: It would be great if you could work with this branch for 1-2 days and had a look into the PHP error log and possibly the friendica logfile for dba related stuff and other strange behaviors. Then I had a better feeling merging it.

**Comment by MrPetovan** [comment]
Alright, this branch is now checked out on my server as of this morning. This means I can't check #4543 at the same time.

**Comment by annando** [comment]
Thanks! I prefer having stable PRs. In the past we had some PRs that failed at very obvious places. I really would like to avoid that in the future.

**Comment by MrPetovan** [comment]
No errors so far, memcached is humming. Although there's no specific debug about cache hits or misses, so I'm not sure what could show in the Friendica log.

**Comment by annando** [comment]
I thought more about things like you couldn't log in or log out, posts not being processed, ...

**Comment by annando** [comment]
Could you add a job to remove outdated cache entries from the database?

**Comment by MrPetovan** [comment]
> I thought more about things like you couldn't log in or log out, posts not being processed, ...

Nothing of the sort so far.

> Could you add a job to remove outdated cache entries from the database?

There already is a Cronjob clearing cache, what do you mean?

https://github.com/friendica/friendica/blob/c181f234a99787a17e5cc3481b4579eb84787c3b/src/Worker/CronJobs.php#L68-L71

**Comment by annando** [comment]
Oops, sorry. It was too early in the morning to see this. :-)

**Pull request merged**
