### PR TITLE
Add expected type-hint to BoundariesPager::renderFull

### PR DESCRIPTION
**Pull request by MrPetovan**
Follow-up to #11665 

- Address https://github.com/friendica/friendica/issues/11630#issuecomment-1162634199

### CODE REVIEW

**Comment by MrPetovan** [comment]
Tested working on my dev node.

**Comment by MrPetovan** [comment]
Tested working on my production node.

**Review by Quix0r — APPROVED** [review]
Looks fine with me.

**Comment by Quix0r** [comment]
If you can merge this before my changes, I can rebase mine against yours (I mean #11670 ).

**Comment by tobiasd** [comment]
Looks as if it is working :)

**Pull request merged**
