### PR TITLE
[Scrutinizer] Fix undeclared variables part 6: src/ (except Protocol/)

### LINKED ISSUE #4452: php7.2 include/poller.php
hi guys when php7.2 is activated it comment this error.:
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in include/poller.php on line 721
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in
include/poller.php on line 733
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in
include/poller.php on line 748

But it is currious when, php7.1 is activated it just work with php7.1, but if php7.2 is activated and only use php7.1 for cron it again comment: Parameter must be an array or an object that implements Countable in

but if php7.1 is acivated and use cron php7.1 it works. Please guys repair it, php7.2 is more fast, include i use production version but it is old, if it install development version and git pull when new things are avaible is it gonna work in production machine.

And is there some facebook api.

Thanks guys

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #4176
Follow-up to #4454
Fixes #4452

- Use dba::selectFirst to remove intermediate variables `$r`
- Remove unused variable `$url_recipients` in Worker\Dellivery

### CODE REVIEW

**Comment by MrPetovan** [comment]
@annando Is there a specific reason you skipped this PR when you merged the other 2 in the series?

**Comment by annando** [comment]
I hadn't got that much time at the morning. The other two had been shorter.

**Comment by MrPetovan** [comment]
Gotcha, I expected the Protocol part to be longer to review. I ordered the three part by descending difficulty to review, so I was surprised you skipped the middle one.

**Comment by annando** [comment]
The middle part had got most files. And since I already was late for the shower, I took the one with the fewer files. I will have a look at it this evening. Additionally it seems as if my cold is now about to disappear, so I'm possibly able to do some work again.

**Pull request merged**
