### PR TITLE
Fetch profile data from different contact tables

### PR DESCRIPTION
**Pull request by annando**
This is done when we won't or can't probe via network.

There are situations where need an entry in the contact table but we don't want to probe via network, since this can take several seconds. This is normally done in frontend situations.

Then we are searching several contact tables ("contact" for all users, gcontact, apcontact and fcontact) for that profile.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Tests are failing because `updated` column doesn't exist. I think you need to update the SQL script.

**Comment by annando** [comment]
What do you mean with "the SQL script"? Something in the tests?

**Comment by annando** [comment]
Ah, so it was the "database.sql" that was needed. Now the tests had been running.

**Comment by annando** [comment]
I currently do experience weird problems with Twitter contacts. So please don't merge it at the moment.

**Comment by annando** [comment]
Does work now.

**Pull request merged**
