### PR TITLE
UserSession class [6] - Refactor src/Module/ files without DI

### PR DESCRIPTION
**Pull request by nupplaphil**
FollowUp #12021

### CODE REVIEW

**Review by MrPetovan — COMMENTED** [review]
Given the ubiquity, shouldn't the `UserSession` dependency be moved to the `BaseModule` class?

**Comment by nupplaphil** [comment]
Puh, I already thought about the massive dependencies at BaseModule.
Because it's that much growing (and for the inheritance, it's much to do)

--> what about a creating a Container class like `DI`, but dynamically so the call would be
```php
class ModuleDependencies {
	public function userSession(): IHandleUserSessions { [...] };
}
```
and
```php
class BaseModule {
	public function __construct(ModuleDependencies $dep) [...]
}
 ```
That would have the advantage of small constructors for Modules and the dynamic injection for testing

**Comment by MrPetovan** [comment]
So we would only have to grow the `ModuleDependencies` constructor, and all the module classes could just start using the method? Sounds good to me. I'm always weary about dynamic containers that are antithetical to Dependency Injection, but explicitly declared containers are fine with me.

**Comment by nupplaphil** [comment]
Can I rework this change with another PR? I do want to finish the `Session` work first

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
