### PR TITLE
Fix: Use correct condition to update the avatar

### PR DESCRIPTION
**Pull request by annando**
See https://github.com/friendica/friendica/issues/10755#issuecomment-948968271

### CODE REVIEW

**Comment by nupplaphil** [comment]
plz rebase to the dev branch to fix the check :)

**Comment by AlfredSK** [comment]
@annando You said tomorrow! 😉

**Comment by nupplaphil** [comment]
We could wait 42 minutes, so it would be tomorrow if you like ;-) ;-)

**Comment by MrPetovan** [comment]
Rebased myself.

**Comment by nupplaphil** [comment]
I totally forgot about this possibility ^^ .. Helpful ^^

**Pull request merged**
