### PR TITLE
Remove pagination when empty, move new Member Tips and use common widget to find people.

### PR DESCRIPTION
**Pull request by astifter**
The commit messages tell the actual story:
- 4683356 and ac2b515  (the first two) are bugfixes.
- fd5131e moves the New Member Tips link around.
- caaac3a uses the same widget for adding people. 

This last one has to be review'ed properly, so I didn't do anything stupid.

### CODE REVIEW

**Comment by MrPetovan** [comment]
I’m not using the vier theme, I’ll leave another review this PR for the aesthetics part. Codewise, it’s OK.

**Comment by MrPetovan** [comment]
Please rename your PR about the things you changed.

**Comment by astifter** [comment]
Better?

**Comment by astifter** [comment]
I came about missing code changes in the frio theme. (@MrPetovan is that the one to go forward?) Closing this request and reopening with fix.

**Comment by MrPetovan** [comment]
It's okay if you change only one specific theme, if you change base templates please make sure it shows correctly with all the currently supported templates (at least frio and vier).

**Pull request closed without merging**
