### PR TITLE
Refurbished contact settings/contact posts

### PR DESCRIPTION
**Pull request by annando**
The contact settings are improved. There is now a new page that shows all posts of a contact. Additionally the standard contact page now contains more contact data. And the navigation tabs are now consistent between the contact pages.

### CODE REVIEW

**Comment by rabuzarus** [comment]
can we now rename "network content" into something other since it isn't anymore a filtered network stream

**Comment by rabuzarus** [comment]
ahh I would drop the title because the contact info is already on the left sidebar

**Comment by annando** [comment]
Concerning the title: Yes, it is partly redundant. But it also contains the address and the network.

**Comment by fabrixxm** [comment]
Can't we move address and nework info in sidebar?
And maybe have the same info in sidebar with /display/ and elsewhere is used the same way?

**Comment by annando** [comment]
@fabrixxm Not totally. The contact profile page has the group configuration under the profile image. So we shouldn't have too much additionally information there.

**Comment by fabrixxm** [comment]
Yes, of course. I was talking about "/contact/<id>/posts" page ..

**Comment by annando** [comment]
But: "/contact/(number)", "/contact/(number)/posts" and "/crepair/(number)" have to have the similar design.

**Comment by fabrixxm** [comment]
And something like this ?
zzz
small details under the contact name in sidebar

Anyway, this could be in another PR...

**Comment by annando** [comment]
@fabrixxm Yeah, exactly. I think this is great and could be unified across all occurrences. And yes: I think this should be done in a separate pull request.

**Comment by rabuzarus** [comment]
@annando
Yes there shouldn't be too much information in the sidebar But i think at the point where we present a contact (hcard/vcard/ and contact-search/contact-presentation) should at least present 4 things. 
1.) contact image, 2.) contact name 3). faddr 4.) Account-Type (at the time this is only if it's a forum or not).
Other information should be optional depending on the sub page and if it would make sense in this context. 
We should have a look to make this as uniform/consistence as possible

**Comment by annando** [comment]
@rabuzarus I would say: You have the job to unify all contact pages. :-) Would you like to do it?

**Comment by rabuzarus** [comment]
What do you think what I'm doing right now? :-P

**Comment by tobiasd** [comment]
:+1:

**Pull request merged**
