### PR TITLE
Added a PDO check in the install routine and cleaned it up

### PR DESCRIPTION
**Pull request by annando**
I just realised that we are now using PDO but haven't checked for its existence. Additionally I cleaned up the install.php file a little bit.

### CODE REVIEW

**Comment by tobiasd** [comment]
Is this already mentioned in the requirement section of the INSTALL documentation?

**Comment by annando** [comment]
I haven't checked that. You know my relation concerning documentations? :-)

**Comment by tobiasd** [comment]
Could you please have a look ;-)

**Comment by annando** [comment]
I totally forgot to push my last changes.

**Pull request merged**
