### PR TITLE
Issue 4200: Adding new contacts not possible

### PR DESCRIPTION
**Pull request by annando**
This fixes issue https://github.com/friendica/friendica/issues/4200

### CODE REVIEW

**Comment by zeroadam** [comment]
Wow, how did that happen?

**Comment by MrPetovan** [comment]
I know right? And why some but not all the fields?

**Comment by annando** [comment]
Someone™ had replaced the old insert command with the new function and hadn't replaced all backticks with single quotes. Strangely enough the PHP parser hadn't noticed this.

**Comment by MrPetovan** [comment]
`` `expression` `` = `eval('expression')` in PHP.

It isn't even a replacement issue, there was no backticks before.

**Pull request merged**
