### PR TITLE
(Re)Implement Twitter contact API endpoints

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #8220

- Implement `/followers/list`
- Implement `/friends/list`
- Reimplement `/followers/ids` with the correct output with pagination
- Reimplement `/friends/ids` with the correct output with pagination
- Update API reference
- Remove obsolete tests

This is an API breaking change to match Twitter's API output. If existing Friendica-specific apps were using the reimplemented endpoints, they will need to be updated from version 2020.06 onward.

The implementation of deprecated Twitter endpoints `/statuses/followers` and `/statuses/friends` haven't been changed.

cc @stom79

### CODE REVIEW

**Comment by MrPetovan** [comment]
With the way I implemented these endpoints, it should be fairly easy to write tests from them since I extracted the parameter gathering and the System::exit call from the logic itself. So the Module classes aren't testable, but the base class `ContactEndpoint` definitely is.

**Comment by MrPetovan** [comment]
I've found a way to fully support the `cursor` parameter, I'll submit a patch in the AM EDT.

**Comment by MrPetovan** [comment]
Added full support for `cursor` and `max_id` parameters.

**Comment by annando** [comment]
What about the tests? Can they be reimplemented?

**Comment by MrPetovan** [comment]
Yes, but I don't have a working setup to run database-related tests locally, so it is painstaking beyond just writing tests.

**Comment by annando** [comment]
Should we call @nupplaphil to the rescue?

**Comment by MrPetovan** [comment]
I have to figure out how to easily pass my local dev database credentials to phpunit on Windows, maybe he can help.

**Comment by annando** [comment]
Do you want to try it out?

**Comment by MrPetovan** [comment]
Yes, because tests are important, but without the connection to the local database, I have to push my WIP changes and wait or the Travis build to finish, which is incredibly wasteful.

**Comment by MrPetovan** [comment]
Ugh, I'm out of my depth, mocking database + testing protected function, I have no idea what I'm doing. I may also have betrayed the programming designs @nupplaphil set up with Repositories, Entities, etc... with this PR.

I'd definitely like his input and guidance on my work.

**Comment by MrPetovan** [comment]
Adding the "Tests Needed" label to complete the @nupplaphil summoning ritual.

**Comment by nupplaphil** [comment]
I'll have a look :-) But I'm a little bit busy the next 2 days, so it could take some days for my respond.

**Comment by MrPetovan** [comment]
IT WORKED, IT WORKED! Take your time, it isn't critical.

**Comment by MrPetovan** [comment]
Are you okay @nupplaphil ? This PR still isn't pressing but it is somewhat blocking me for future API developments, so if you just forgot about it, it's okay, this just is a polite reminder.

**Comment by nupplaphil** [comment]
@MrPetovan I really forgot it, sorry :-(

Tbh the API testing was a problem I didn't solve yet. One (fast) idea would be to create a `MockedAPI` class, which extends the  `ContactEndpoint` class and adds a method `mockedCall(string functionName)` to call the protected methods. Maybe this could be a blueprint for other API tests

**Comment by MrPetovan** [comment]
I successfully established a working database test environment, tests are coming.

**Comment by MrPetovan** [comment]
Refactored test case classes to use the fixtures without having to run all 250 unrelated API tests because of inheritance 😅

**Comment by MrPetovan** [comment]
Hit a snag: My local test rig on Windows 10/PHP 7.2.10/PDO/mysqlnd/MariaDB doesn't accurately populate numeric columns with numeric data in result rows. However Twitter API results have typed properties which I want to test against. But because all the values are strings, the tests trip for the wrong reason.

I'm not sure what to do, I'm scoured the web and [the popular answer on StackOverflow](https://stackoverflow.com/a/20123337) mentions the mysqlnd that is currently used on my local install of PHP.

**Comment by annando** [comment]
I guess the problems are all over the place and not only in the tests? I'm just thinking that we possibly (on a long term) could cast the database results in the database driver. This would also help with this "emulate prepares" configuration.

BTW: Have you tried disabling PDO?

**Comment by MrPetovan** [comment]
Using mysqli worked even though it was a pain to set up since we assumed PDO until now.

**Comment by MrPetovan** [comment]
I didn't add my code to switch between PDO and mysqli, it is mostly hardcoded and I didn't add support for transaction, which makes most tests fail.

**Comment by MrPetovan** [comment]
And the tests pass! 🎉

**Comment by nupplaphil** [comment]
Nice! Looks good!!!

**Pull request merged**
