### PR TITLE
SQL unseen is tinyint, not bool

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/friendica/friendica/issues/3645

### CODE REVIEW

**Comment by Alkarex** [comment]
If this is a good fix, then the other examples of bool instead of int should be addressed as well

**Comment by Alkarex** [comment]
Commit changing more booleans to integers, which is what is used in the SQL database https://github.com/friendica/friendica/pull/3646/commits/dd6bf7621cfa5d9c6160f89c334a0de703a05b21

**Comment by annando** [comment]
MySQL doesn't know a dedicated "boolean" type - see here: https://stackoverflow.com/questions/11167793/boolean-or-tinyint-confusion

But for better readability we are addressing it as boolean. This is not a bad hack, but an expected way of working with it.

**Comment by annando** [comment]
I create an alternate solution: https://github.com/friendica/friendica/pull/3648

This is a more general solution that will reliably allow the use of boolean values as parameters.

**Pull request closed without merging**
