### PR TITLE
Make profile settings available in the user settings

### PR DESCRIPTION
**Pull request by tobiasd**
With this PR a link to the side menu in the user settings is added to reach the profile settings. Adresses #1391

### CODE REVIEW

**Comment by annando** [comment]
Shouldn't we probably remove the other ways to reach the profile then?

**Comment by tobiasd** [comment]
No. Why? You can switch of the computer as well over more then just one way.

**Comment by annando** [comment]
It does make the support easier, having only a single way.

**Comment by tobiasd** [comment]
For me both ways reaching the profiles settings make sense. I could not say which one makes more sense. Also removing the old one, adds unnecessary clicks to reach the editor and I expect the editor from my profile as well.

**Pull request merged**
