### PR TITLE
add the profile url to the settings pages as alternative to the webfi…

### PR DESCRIPTION
**Pull request by tobiasd**
…nger. See issue #1621

### CODE REVIEW

**Comment by annando** [comment]
Wouldn't it be better to have a text "%s or %s" instead of the "or"? Maybe there are languages where an "or" doesn't simply consists of a single word but with a prefix or suffix?

**Comment by tobiasd** [comment]
Yes, problem might be with installations in a subdir...

**Comment by annando** [comment]
Why you don't just add the subdirectory in the template as well?

**Comment by tobiasd** [comment]
do we have a get_subdir() function?

**Comment by annando** [comment]
It's the get_path() function.

**Pull request merged**
