### PR TITLE
Issue 12522 typo

### LINKED ISSUE #12522: Typo found, in the help portion
in /help/tools from the menu, under the fail2ban info. for 3rd party tools, there is a typo, that breaks fail2ban, if you just copy paste.
 
 In /etc/fail2ban/jail.local create a section for Friendica:
 
 -logpath = /var/log/friend.log
 +logpath = /var/log/friendica.log
 
 everything else, points to friendica.log

### PR DESCRIPTION
**Pull request by haheute**
it's my first pull request. hope all is okay

Fix #12522

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]
It is perfect, thanks!

**Comment by tek-aevl** [comment]
Perfect indeed. Didn't know how simple that would be.

**Comment by haheute** [comment]
to be honest -- i only did what you proposed...

**Comment by MrPetovan** [comment]
Teamwork! 🙌

**Pull request merged**
