### PR TITLE
Fix "Item couldn't be fetched."

### PR DESCRIPTION
**Pull request by annando**
Another fix for PR https://github.com/friendica/friendica/pull/9807

This fixes the problem that the error above hat been created because the system hadn't found the parent item. This was due to the fact that the `parent` wasn't filled at that time. So we now use different fields for that.

### CODE REVIEW

**Comment by MrPetovan** [comment]
PHP 7.4 test fails with
```
1) Friendica\Test\legacy\ApiTest::testApiConversationShowWithId
Friendica\Network\HTTPException\BadRequestException: There is no status with id 2.

/home/runner/work/friendica/friendica/include/api.php:1991
/home/runner/work/friendica/friendica/tests/legacy/ApiTest.php:1852
```

**Comment by annando** [comment]
@MrPetovan yeah, that's weird. Sometimes it fails and sometimes not.

**Comment by annando** [comment]
@MrPetovan and now it is working again. I will leave it that way :-)

**Review by MrPetovan — APPROVED** [review]

**Comment by AlfredSK** [comment]
@annando I pulled and now I notice all comments under forum posts are gone. Any idea?
See also: https://forum.friendi.ca/display/0b6b25a8-1060-0483-9d48-d03082985467

**Comment by AlfredSK** [comment]
Another user reported he 'liked' a post - and all of a sudden all comments vanished. It wasn't a forum post.
https://libranet.de/display/0b6b25a8-1160-0499-c317-588532546420

**Comment by annando** [comment]
Please have a look for log file entries with "DB Error" in it and for any PHP errors/warnings.

**Comment by AlfredSK** [comment]
I have hundreds of `PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/libranet/src/Database/Database.php on line 927` - every couple of seeconds.

And this...
https://github.com/friendica/friendica/issues/9814

Also a lot of these DB errors.

**Comment by AlfredSK** [comment]
Ok. I raised the PHP memory bar to 512MB. The error flood about the exhausted memory has stopped. But comments are still not displayed.

**Comment by AlfredSK** [comment]
I see 18000 queries per second in mytop at the moment.

**Comment by annando** [comment]
@AlfredSK that DB Error is fixed with my new PR - to make it more interesting, this PR is changing many places in the code, so it adds some possible new interesting behaviours :grinning: 

P.S.: Sorry for the inconvenience. This should be done, once all `item` queries are changed.

**Comment by AlfredSK** [comment]
I hope the comments reappear. I'm really distracted from watching anime on Netflix at the moment. :-)

**Comment by annando** [comment]
You could pause that. I'm binge watching quiz shows while coding :-)

**Comment by AlfredSK** [comment]
Yeah. I already jumped back 4 episodes because I missed the plot completely.

**Pull request merged**
