### PR TITLE
We now send a summary via AP

### PR DESCRIPTION
**Pull request by annando**
This partially fixes the problem with Mastodon and Articles. Mastodon decided to not display the content of "Article" posts. But they display the content of the "summary" field. So we now transmit our "Article" posts (posts with title) with a "summary" field that contains a shortened version of the post.

When the "abstract" BBCode element is set, we transmit it in any case.

When importing feeds we now add this "abstract" BBCode element. This will improve the readability from mirrored feed items with Mastodon.

This PR addresses https://github.com/friendica/friendica/issues/6813

### CODE REVIEW

**Comment by AlfredSK** [comment]
Is this related to this PR? 
https://libranet.de/display/59e215f1c372051d369366948e8140b79e2e094d
https://social.tchncs.de/@meldrian/101760960518646555
Looks like the BBCode is transmitted to Mastodon.

**Comment by MrPetovan** [comment]
If you pulled less than four hours ago, probably.

**Comment by AlfredSK** [comment]
`If you pulled less than four hours ago`
Of cause I pulled less than 4 hours ago. We're in the RC testing phase, right? :-)

**Comment by tobiasd** [comment]
I got that posting via "Friendica (AP)" and for me the display is screwed up as well.

**Comment by annando** [comment]
Oops :-)

**Comment by tobiasd** [comment]
Here is another case were things cone wrong https://forum.friendi.ca/display/0b6b25a8-185c-8e2b-08c0-132751537133 - A CW for a forum posting with a title.

**Comment by lostinlight** [comment]
There's a small issue. The text and the immediately following link to source have no white space inbetween, which makes the source link jumbled and unclickable. Issue present only in AP (Mastodon).

**Comment by MrPetovan** [comment]
I wasn't able to find where a newline has to be added at a glance, any idea @annando ?

**Comment by annando** [comment]
Can you show an example?

**Comment by lostinlight** [comment]
@annando That's how it arrives to Mastodon:
screenshot

Notice that the link to source is lost in text.

**Comment by MrPetovan** [comment]
So the problem isn't the link to the source post on Friendica, that is correct at the bottom. The link you're talking about is a part of the RSS post body that is incorrectly imported, see also the date just next to "Fixed" and "Invalid" that would need to be separated as well. See source RSS post feed entry:

```xml
<entry>
  <id>https://git.pleroma.social/pleroma/pleroma/-/tags/v1.0.4</id>
  <link href="https://git.pleroma.social/pleroma/pleroma/-/tags/v1.0.4"/>
  <title>v1.0.4</title>
  <summary></summary>
  <content type="html">&lt;h2 data-sourcepos="1:1-1:23" dir="auto"&gt;&amp;#x000A;&lt;a id="user-content-104-2019-08-01" class="anchor" href="#104-2019-08-01" aria-hidden="true"&gt;&lt;/a&gt;[1.0.4] - 2019-08-01&lt;/h2&gt;&amp;#x000A;&lt;h3 data-sourcepos="2:1-2:9" dir="auto"&gt;&amp;#x000A;&lt;a id="user-content-fixed" class="anchor" href="#fixed" aria-hidden="true"&gt;&lt;/a&gt;Fixed&lt;/h3&gt;&amp;#x000A;&lt;ul data-sourcepos="3:1-3:116" dir="auto"&gt;&amp;#x000A;&lt;li data-sourcepos="3:1-3:116"&gt;Invalid SemVer version generation, when the current branch does not have commits ahead of tag/checked out on a tag&lt;/li&gt;&amp;#x000A;&lt;/ul&gt;</content>
  <updated>2019-08-01T16:41:53Z</updated>
  <media:thumbnail width="40" height="40" url="https://git.pleroma.social/uploads/-/system/user/avatar/76/avatar.png"/>
  <author>
    <name>kaniini</name>
    <email>ariadne@dereferenced.org</email>
  </author>
</entry>
```

**Comment by annando** [comment]
Sounds like a problem with the html2plain function.

**Pull request merged**
