### PR TITLE
2022.02 CHANGELOG

### PR DESCRIPTION
**Pull request by tobiasd**
CHANGELOG for the 2021.12 release.

This shall be the last PR merged into the codebase before the release.

### CODE REVIEW

**Comment by nupplaphil** [comment]
This PR should include a "last" commit for `messages.po` and `database.sql` with changing the version in their header from `2021.12-rc` to `2021.12`

**Comment by tobiasd** [comment]
TBH tests are great, but for changes in _a text file_ that is part of the documentation, I will not start including database definitions and translation files.

**Comment by nupplaphil** [comment]
OK, alternative way would be to exclude "tagging" from the database / messages.po check. It's possible as well.
But --> in the stable releases, we will include these files with the wrong version (from the RC, not from the official version) in their header

**Comment by tobiasd** [comment]
If I understand you correctly, then the headers of these two files you mentioned, need to be adopted like the other version strings in the `VERSION` and `boot.php` files during the release (e.g. https://github.com/friendica/friendica/commit/1adbdfb8d1d0a476fb416ffaf3012a7a0f13deb1) or am I mistaken?

The changes in the `CHANGELOG` are not tested anyway (spellchecking would be nice, then I don't need to look at the red lines in Geany), so when I merge this PR as last input for the RC branch, I can simply ignore the failing warning.

**Review by MrPetovan — APPROVED** [review]

**Comment by nupplaphil** [comment]
> If I understand you correctly, then the headers of these two files you mentioned, need to be adopted like the other version strings in the `VERSION` and `boot.php` files during the release (e.g. [1adbdfb](https://github.com/friendica/friendica/commit/1adbdfb8d1d0a476fb416ffaf3012a7a0f13deb1)) or am I mistaken?

Yes you're right

> The changes in the `CHANGELOG` are not tested anyway (spellchecking would be nice, then I don't need to look at the red lines in Geany), so when I merge this PR as last input for the RC branch, I can simply ignore the failing warning.

I excluded the specific version checks for the event "TAG" so creating a stable tag won't brick the continuous deployment process.
<strike>And for spellchecking - I think we could add https://hub.docker.com/r/webspellchecker/wproofreader as an additional check ;-)</strike> paid license :-(

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
Thank you for updating the Changelog, should we start referring to the `2022.02` version instead of `2021.12`?

**Comment by tobiasd** [comment]
The release will have the 2022-02 version (likely ;-) could be 04 as well) but changing all the path and repository names would be overkill I think.

**Comment by MrPetovan** [comment]
I've changed the version labels on the GitHub side to `2022.02`, let me know if you'd like me to change the mentions in the code.

**Pull request merged**
