### PR TITLE
Making Friendica compatible to Nextcloud Social

### PR DESCRIPTION
**Pull request by annando**
These changes enable the communication between Friendica and Nextcloud Social.

### CODE REVIEW

**Comment by AlfredSK** [comment]
Great! Btw. yesterday I managed to get a Friendica post on NC Social but not the other way around.
Looking forward to test this. Thank you!

**Comment by jasoncheng** [comment]
Good Job 👍

**Comment by AlfredSK** [comment]
Works! 👍😃🎈🎉
I had to unfollow/follow the NC contact but now sending and receiving posts on both sides is working.

**Comment by AlfredSK** [comment]
I think there is an issue with JasonLD.php now:
````
13-Jan-2019 13:36:23 UTC] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/html/libranet/src/Util/JsonLD.php:98
````

**Comment by AlfredSK** [comment]
Here is the stack trace:

`````
PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/html/libranet/src/Util/JsonLD.php:98
Stack trace:
#0 /var/www/html/libranet/src/Protocol/ActivityPub/Receiver.php(77): Friendica\Util\JsonLD::compact(Array)
#1 /var/www/html/libranet/src/Module/Inbox.php(52): Friendica\Protocol\ActivityPub\Receiver::processInbox('{"@context":"ht...', Array, 0)
#2 [internal function]: Friendica\Module\Inbox::rawContent()
#3 /var/www/html/libranet/src/App.php(1735): call_user_func(Array)
#4 /var/www/html/libranet/index.php(13): Friendica\App->runFrontend()
#5 {main}
  thrown in /var/www/html/libranet/src/Util/JsonLD.php on line 98
````

**Comment by AlfredSK** [comment]
I opened an issue #6438

**Comment by annando** [comment]
I opened a PR https://github.com/friendica/friendica/pull/6439

**Pull request merged**
