### PR TITLE
Friendica code blocks aren't rendered in Diaspora

### LINKED ISSUE #3274: Friendica code blocks aren't rendered in Diaspora
This is the flip side of #3189

Friendica's code blocks gets added HTML tags breaking the whitespace structure when viewed in Diaspora. It might be something we can fix on our end the same way #3189 was fixed, by removing code blocks before any whitespace management, and then re-adding them to the resulting message afterwards.

Friendica code block

Diaspora code block

Reference post: https://friendica.mrpetovan.com/display/1860bc0e6158d14834e95d6899168678

Thanks Rebeka for the report!

### PR DESCRIPTION
**Pull request by Hypolite**
Fixes #3274.

The only interesting stuff is here: https://github.com/friendica/friendica/pull/3295/commits/b0accf4d4c674799ae210fce012dd0f31834717e

### CODE REVIEW

**Comment by annando** [comment]
Is there a bug in the library so that you have to do this workaround?

**Comment by Hypolite** [comment]
Not in the library, more like in the way we translate BBCode code blocks to HTML, which isn't the format HTML To Markdown is expecting (for good reasons, we're making a mess).

Instead of trying to fix the BBCode part that Friendica uses, it's a mess but it visually works, the solution I found was to stash the verbatim blocks that aren't supposed to be parsed either by the BBCode converter nor the Syntax Highlighter before being sent to Diaspora.

By the way, I used the same exact trick when importing verbatim blocks from Diaspora because it was getting converted to HTML we didn't recognize when converting to BBCodes.

**Comment by annando** [comment]
So this is some intermediate step before totally changing the BBCode engine?

**Comment by Hypolite** [comment]
Indeed, and since it's not a critical issue, it will wait the tens of others more pressing ones.

**Pull request merged**
