### PR TITLE
Issue 14102: Display "channels only" contacts in circles

### LINKED ISSUE #14102: Display posts only in the respective circle
In the channels there is the option to display posts only in the corresponding channel.
I would like to see this function for the Circles as well. Could this be implemented?

### PR DESCRIPTION
**Pull request by annando**
Fixes #14102

### CODE REVIEW

**Comment by ghost** [comment]
Is the solution to this problem still in the works?

**Comment by annando** [comment]
It's closed, since it is coded.

**Comment by ghost** [comment]
What does that mean in concrete terms? I can't find a corresponding function.

**Comment by tobiasd** [comment]
In the contact settings (develop branch and 2024.06-rc branch) you can select "Show this contact only in Channels" and then the contacts postings will only be displayed in channels and circles but not the general network stream.

**Comment by ghost** [comment]
I am not talking about displaying the corresponding contacts (and here I mean the feeds) in an assigned channel, but in the corresponding Circle. And that doesn't work cleanly.

**Comment by tobiasd** [comment]
For me it works. I have a circle for news outlets I'm following, the postings don't appear in the general timeline but only when I open the circle "News".

What version of Friendica are you using?

**Comment by ghost** [comment]
In the meantime, I have decided in favour of the following solution: I have set up an account with anonsys.net, which I use exclusively as a feed reader. Only I myself can read the feed entries. 

The administrator is aware of this and agrees to it.

**Pull request merged**
