### PR TITLE
 New scheduler mechanism - now to the correct branch

### PR DESCRIPTION
**Pull request by annando**

### CODE REVIEW

**Comment by AlfredSK** [comment]
Hmm. Maybe it's just me or pure coincidence but since I pulled this morning the load of the server has increased significantly.
Avg. load before merging this one: 3.1
Avg. load since I pulled: 5.3

**Comment by tobiasd** [comment]
Is the DB structure update still running?

**Comment by AlfredSK** [comment]
No. To be sure I just ran the dbstructure command manually. No output. Seems fine.

**Comment by tobiasd** [comment]
> No. To be sure I just ran the dbstructure command manually. No
> output. Seems fine.

When I got home I checked my node. The LOAD is approx 3 times higher then usual at the moment.

**Comment by MrPetovan** [comment]
Copy of #6681

**Comment by MrPetovan** [comment]
This PR was about the speed of the worker, not about reducing the load, can you verify the jpm has increased?

**Comment by AlfredSK** [comment]
I'd love to verify the number of jpm. But I have no clue what to grep for since the new logger has been introduced. :-/
Btw. my workerqueue is nearly empty. But the fork rate of system processes has increased dramatically.

grafik

I think you can spot the time when I pulled this PR. :-)

**Comment by AlfredSK** [comment]
For a test I checked out the commit before this PR.

````
checking out '08d92d7ad'.
...
HEAD is now at 08d92d7ad Automatically adding mentions in the network stream hadn't really worked
````

Load went down to **3.2**. Process fork rate down from ~30 to ~10.

**Comment by annando** [comment]
I can imagine where the problem is - the worker is now massively faster, it needs much less time between the tasks.

Please execute this command in the shell of your system:
```
tail -f friendica.log | grep -a "done in".*Worker.php
```
It should like this:
```
2019-02-22 21:59:24 worker [INFO]: Process 8979 - Prio 40 - ID 106747311: Delivery - done in 0.1691 seconds.
```
Question is, which priorities occur the most and which processes are called (in this case "Delivery").

**Comment by AlfredSK** [comment]
**20 minutes logged before this PR:**
`'Prio 0.*done in.*Worker.php'` 0
`'Prio 10.*done in.*Worker.php'` 0
`'Prio 20.*done in.*Worker.php'` 538
`'Prio 30.*done in.*Worker.php'` 486
`'Prio 40.*done in.*Worker.php'` 247
`'Prio 50.*done in.*Worker.php'` 163

HEAD is now at 08d92d7ad
Total number of workers: 1434
Average load: 3

**20 minutes logged after this PR:**
`'Prio 0.*done in.*Worker.php'` 0
`'Prio 10.*done in.*Worker.php'` 0
`'Prio 20.*done in.*Worker.php'` 1370
`'Prio 30.*done in.*Worker.php'` 490
`'Prio 40.*done in.*Worker.php'` 310
`'Prio 50.*done in.*Worker.php'` 287

On current 2019.03-rc
Total number of workers: 2457
Average load: 5

**Comment by MrPetovan** [comment]
There is a surprising correlation (p=0.1) between the number of workers tasks done and the average server load. 1434 is to 2457 what 3 is to 5. This confirms the increase in worker speed, at the cost of load for very active servers.

**Comment by AlfredSK** [comment]
> This confirms the increase in worker speed

Yep. Maybe that's true. But there is no real improvement, no gain for the pain. The delivery and everything else has worked perfectly fine before and it still works. But now I have to deal with a constant overload of the server.

**Comment by AlfredSK** [comment]
I'll see what happens when I reduce the 'Maximum Load Average' from 30 to 20. This should change the calculation for the number of workers.

**Comment by tobiasd** [comment]
Does the worker still care about the limitations set in the admin panel? I lowered the values (max workers, max load) but they seem to have no effect even with low numbers.

**Comment by tobiasd** [comment]
At the moment the LOAD values are 20 times higher then before this change was merged. And the limitations from the admin panel seem to be entirely ignored.

**Comment by AlfredSK** [comment]
@tobiasd Are you using the JIT or the preload config_adapter? I'm on 'preload' and I see a change when I lower the values in admin panel. But the change isn't as substantial as expected.

**Comment by annando** [comment]
@tobiasd The limitations from the admin panel are respected. But please consider that the config settings are only loaded at the start of the worker. Every worker has got a lifespan of 5 minutes (or the length of a single task if this took longer than 5 minutes). Only then the new settings are loaded.

@AlfredSK my server squeet.me had fought with over 1.6 million entries in the workerqueue with several ten thousands at priority 50 and over a million entries with priority 40. The changes in the workerqueue lead to the situation that now the tasks are processed faster than they are created. The JPM number jumped from around 100 to now partially over 1,000.

BTW: There is a config setting "worker_cooldown". This defines the number of seconds between every worker task. Setting this to "1" would delay the processing of task by a second - and reduces the I/O stuff.

**Comment by tobiasd** [comment]
As I am not aware that any configuration about preload adapters is necessary I don't have configured any such thing.

**Comment by tobiasd** [comment]
> BTW: There is a config setting "worker_cooldown". This defines the number of seconds between every worker task. Setting this to "1" would delay the processing of task by a second - and reduces the I/O stuff.

I never removed that setting from my config file. It is in place and soundly ignored it seems.

**Comment by annando** [comment]
Have a look in the config for "in cooldown for" in the function "execFunction". There should be an entry.

**Comment by tobiasd** [comment]
Yes, the setting is there and a line about it in the execFunction of the worker as well. But the note about it is not written to the log file. Could it be that the config rework is now taking the default value as granted instead of the actual value from the database?

I've set the Friendica in maintenance mode and stopped the worker. Within the expected lifetime of the worker process the system cooled down to a LOAD of 0.2 from the value around the 15 before.  So it is definitively Friendica that is causing the LOAD.

My settings are currently max_load=4, which is the number of cores the system provides. Before that the limit had been 8 for month. So an entire civilisation of workers should have known that a LOAD of 15 is way above the limitation of the settings.

**Comment by annando** [comment]
Have a look for lines like this:
```
2019-02-23 09:58:29 worker [INFO]: Load: 3.9/20 - processes: 10791/16/1162868 - jpm: 274 (0:0, 30:25, 40:4, 50:1) - maximum: 16/30 [] {"file":"Worker.php","line":795,"function":"tooMuchWorkers","uid":"d9fbd97","process_id":27994}
```
This tells us that the current load is 3.9 (maximum is 20). There are currently 10791 deferred jobs, 16 running tasks and 1162868 jobs are in the pipeline. And at the end of the line the systems tells that currently 16 tasks out of a maximum number of 30 tasks are allowed. So this setting is really respected.

Concerning the cooldown: Have a look into the config table. Possibly there is some entry in it that overrides the setting in the config file.

**Comment by tobiasd** [comment]
After revoking the maintenance mode the system seems to be back to only 3 times the value of the system load then it was before.

The config table does not contain an entry about the cooldown as far as I could see.

**Comment by tobiasd** [comment]
Oh, sorry, we have to wait a bit. I was still on the "known good" commit checkout @AlfredSK mentioned above ;-)

**Comment by annando** [comment]
I just played with the "cooldown" value. It is respected on my system.

**Comment by tobiasd** [comment]
Yes, looks like. Seems that I was on the wrong log level before for this line to be printed out. But then, the cooldown time of 1 second was insufficient for the system to actually cool down.

**Comment by AlfredSK** [comment]
I managed to reduce the load by setting maximum load average to 15 (6 core machine).
Before this PR a value of 30 was working well. I'm back on a load average around 3-4.

`Load: 3.44/15 - processes: 283/9/452 (0:0, 20:6/379, 30:2/59, 40:1/14) - maximum: 10/20 [] {"file":"Worker.php"`

I didn't set the cooldown option until now.

**Comment by annando** [comment]
I wouldn't recommend the "cooldown" for systems with several users since it drastically reduces the worker speed. Normally a delivery task to a regular server is executed in around 0.1 to 0.3 seconds - with a cooldown of a second the delivery will run 1.1 to 1.3 seconds. Instead playing with the load and the maximum number of workers is better.

The cooldown is more like an "ultima ratio" when nothing else helps. (Especially for really extreme small systems)

**Comment by AlfredSK** [comment]
It's not that easy to find a good and balanced setting for the workers now. But I can confirm the processing is pretty fast after this change. :-)

I found a good setting with `'worker_load_exponent' => 1` (linear approach). I started by setting the desired max load and then adjusted the number of max workers step by step until the balance between load and speed was okay.

**Comment by annando** [comment]
BTW: If you dare, you could also set "worker_fetch_limit" to some value of "5". (Normally it is "1")

If this value is larger than "1" it assigns several tasks with high and medium priority to the same worker. So then the worker hadn't to look for a new job after each single job. This can double the speed as well. (and could possibly affect your performance settings again)

**Comment by AlfredSK** [comment]
I just found a working setup after playing with the options for several hours and now you're telling me I should start from scratch with even more options/values to adjust? :-)
I will consider that.

**Pull request merged**
