### PR TITLE
use boolval instead of !empty for exclude_replies

### PR DESCRIPTION
**Pull request by m4sk1n**
I don't think why it works like this, hope it doesn't break compatibility

### CODE REVIEW

**Comment by MrPetovan** [comment]
We use `empty()` because it covers the case where the query string parameter is missing and the `exclude_replies` key doesn't exist in the `$_REQUEST` array. That's why the Travis CI build failed: a PHP Notice is emitted since `boolval` is trying to access a non-existing index of an array.

What was your intention? Was something not working?

**Comment by m4sk1n** [comment]
Ok, so then the API documentation page is misleading, as what is presented as a default value is in fact not a default value…

**Comment by MrPetovan** [comment]
Can you please point me to the relevant API documentation for eventual update or clarification?

**Comment by m4sk1n** [comment]
It says that default value of `exclude_replies` is `false`, so it suggests that `false` value would make it not exclude the replies

**Comment by MrPetovan** [comment]
Except in the case where the `exclude_replies` index doesn't exist, `!empty()` and `boolval()` are functionally identical. I'm not sure what you're getting at?

**Comment by m4sk1n** [comment]
I'm not experienced with PHP, I even forgot the basics, so excuse me… So, then I can't understand how api/statuses/home_timeline?page=1&exclude_replies=false doesn't return the same as api/statuses/home_timeline?page=1&exclude_replies=true…
Well, just realized it takes it as a string, so, nevermind…

**Comment by MrPetovan** [comment]
Yes, it should be `exclude_replies=1` or simply nothing for the opposite. Even `boolval()` doesn't convert `"false"` (the string) to `false` (the boolean).

**Comment by annando** [comment]
This is a standard parameter that is used by the Twitter API, so we have to look there.

**Comment by MrPetovan** [comment]
It seems like they're using *true* but it isn't clear if it's a string or the JSON boolean. See https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline.html

**Pull request closed without merging**
