### PR TITLE
Preparation for being able to fetch AP posts by proving the URL

### PR DESCRIPTION
**Pull request by annando**
This is just a preparation. The frontend work still needs to be done. But since I now want to have a look at some other stuff I would like to have it accepted now to continue work later.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Is it this feature where you provide the URL of a random AP post and it imports it for you to interact on? Aaaw yiiis!

**Comment by MrPetovan** [comment]
Also tests are now lightning-fast, thanks to @nupplaphil

**Comment by annando** [comment]
@MrPetovan indeed it is. You can provide a link and the post will be imported. And not only that single post. When you provide some comment url the whole thread will be fetched. What's missing is the frontend stuff. This will ask for the url, then fetch it and then display it.

I thought of just adding this to the search window at the top. Entering an URL there could start the whole process. When the post does exist already, it - of course - won't be fetched again, but only displayed.

**Comment by MrPetovan** [comment]
Yes, search window it should be.

**Pull request merged**
