### PR TITLE
Frio: open links to source in a new browser tab

### PR DESCRIPTION
**Pull request by Raroun**
fix Issue #13457

### CODE REVIEW

**Review by MrPetovan — COMMENTED** [review]
This would also open links to local posts in a new browser tab, is it intended?

Also `$item.plink` is referenced more times in the frio theme, please verify whether they need the same treatment:
image

**Comment by Raroun** [comment]
`This would also open links to local posts in a new browser tab, is this intentional?`

Well, yes and no.

My thought was that when someone presses the button for the "external" link, a new tab opens. Whether this is actually external or local is rather secondary.

This makes sense, at least in my opinion, because the reading flow is disturbed, as the position I am in is usually lost otherwise.
If I want to see the original post and it opens in a new tab, I can easily return to where I was.
The back button in the browser does not always work reliably in this case.

`fa-external-link` exists only once with this button. I therefore assumed that this is the only place that needs to be changed.

Since I have to teach myself all this from scratch, I'm grateful for any tips :)

**Comment by MrPetovan** [comment]
We use the post plink in post titles as well. Should these open in a new window as well?

**Comment by Raroun** [comment]
You're right, it also makes sense with the headlines. Especially because the behaviour is more consistent that way.

**Review by MrPetovan — APPROVED** [review]

**Comment by AndyHee** [comment]
Thanks @Raroun That's great!

**Pull request merged**
