### PR TITLE
Update Composer dependencies ahead of release

### PR DESCRIPTION
**Pull request by MrPetovan**
- Updating ezyang/htmlpurifier (v4.16.0 => v4.17.0)
- Updating mobiledetect/mobiledetectlib (2.8.41 => 3.74.3)
- Updating patrickschur/language-detection (v5.1.0 => v5.3.0)
- Updating phpseclib/phpseclib (3.0.19 => 3.0.34)
- Updating psr/container (1.1.1 => 2.0.2)
- Updating smarty/smarty (v4.3.1 => v4.3.4)
- Updating bower-asset/base64 (1.2.0 => 1.3.0)
- Updating mockery/mockery (1.5.1 => 1.6.7)
- Updating sebastian/global-state (5.0.5 => 5.0.6)
- Updating sebastian/diff (4.0.4 => 4.0.5)
- Updating theseer/tokenizer (1.2.1 => 1.2.2)
- Updating nikic/php-parser (v4.15.4 => v4.18.0)
- Updating phpunit/php-code-coverage (9.2.26 => 9.2.29)
- Updating phpunit/phpunit (9.6.7 => 9.6.15)
- Updating dasprid/enum (1.0.4 => 1.0.5)
- Updating guzzlehttp/promises (1.5.2 => 1.5.3)
- Updating symfony/polyfill-php72 (v1.27.0 => v1.28.0)
- Updating symfony/polyfill-intl-normalizer (v1.27.0 => v1.28.0)
- Updating symfony/polyfill-intl-idn (v1.27.0 => v1.28.0)
- Updating paragonie/sodium_compat (v1.19.0 => v1.20.0)
- Updating psr/http-client (1.0.2 => 1.0.3)
- Updating composer/ca-bundle (1.3.5 => 1.4.0)

Address

### CODE REVIEW

**Comment by annando** [comment]
The test for PHP 7.3 does fail at the moment. Does it mean that we should now skip 7.3?

**Comment by MrPetovan** [comment]
Yes, I forgot to add in the note that the minimum PHP version to run Friendica is now 7.4

**Comment by foss-** [comment]
@MrPetovan when you find some time, could you update https://friendi.ca/resources/requirements/ to say PHP 7.4+?

**Comment by MrPetovan** [comment]
It would more accurate to update around release day, but with no visibility about the when I might just do it now to get it out of the way.

**Pull request merged**
