### PR TITLE
Add gd locale to language selection

### PR DESCRIPTION
**Pull request by gunchleoc**

### CODE REVIEW

**Comment by MrPetovan** [comment]
Hi, we don't seem to have a Gaelic translation available for Friendica yet, which makes this change moot as the interface wouldn't be translated at all even if the locale was selected.

Please head over to Transifex at https://transifex.com/friendica/friendica to start contributing to the Gaelic translation so that it can eventually be added to the list of supported locales in Friendica. The Gaelic translation is currently 23% complete and we require a threshold of 50% to include it in the software.

Thank you for your interest in Friendica, we'll happily revisit this PR once the threshold is reached for the Gaelic translation!

**Comment by gunchleoc** [comment]
Translation is now at 50.27%

@MrPetovan Can you reopen or shall I create a new PR?

**Comment by MrPetovan** [comment]
@tobiasd needs to import the translation strings in the repository and the language will be added to the array at that time, thank you for your work!

**Comment by tobiasd** [comment]
I'll add the translation later today :)

**Pull request closed without merging**
