### PR TITLE
Properly readd CSS changes from PR #5345 in quattro.

### PR DESCRIPTION
**Pull request by astifter**
I wrongly added CSS to generated files in PR #5345, now adding changes to less as is good and proper.

And sorry for PR #5356. @tobiasd can you please check this if its done right?

### CODE REVIEW

**Comment by tobiasd** [comment]
I'll have a look later today.

**Comment by tobiasd** [comment]
I got some PHP errors/warnings from the vagrant VM from your branch on the network stream. But the changes in quattro styling of the additional features are looking fine. So I'll merge this.

**Comment by tobiasd** [comment]
Errors are gone after the merge testing in the same vagrant instance :-) I assume it is a missing DB structure conversion in the VM.

**Comment by astifter** [comment]
@tobiasd Thanks! I guess it would make sense to have a "WARNING: autogenerated, do not edit" at the start of the CSS files, I'll try to come up with something

**Pull request merged**
