### PR TITLE
[frio] Add double curly brace

### PR DESCRIPTION
**Pull request by paperbag**
And I think there are some typos:
`{$id}` --> `{{$contact.id}}`
`{$thumb}` --> `{{$contact.thumb}}`
`{$name}` --> `{{$contact.name}}`

### CODE REVIEW

**Comment by annando** [comment]
Have you tested this on your installation?

**Comment by paperbag** [comment]
Yes. It work for me.

**Comment by rabuzarus** [comment]
No this aren't typos. This part is a template for javascript (have a look here https://github.com/friendica/friendica/blob/develop/view/theme/frio/js/theme.js#L498). This does mean that it shouldn't be processed by php smarty. So single curly braces are used here.

Sorry, I have to close your PR

**Comment by annando** [comment]
@rabuzarus thanks for the clarification. I already was confused about this.

**Comment by paperbag** [comment]
Sorry.

When I use frio theme, and on contacts page(`example.com/contacts`), I found the request like `example.com/{$thumb}`, and get a 404 page. So I thought this problem is about this `contact_template.tpl` file:/

**Comment by rabuzarus** [comment]
Mhhh strange. I don't any other place where `example.com/{$thumb}` could be requested. But the html in https://github.com/friendica/friendica/blob/develop/view/theme/frio/templates/contact_template.tpl#L128 shouldn't start a request, since it is just a template. It is used for the javascript contact filter of the `contacts` module.

The problem is, that I can't reproduce your issue. So I can't say something about it :-/

**Pull request closed without merging**
