### PR TITLE
some work on poke template

### PR DESCRIPTION
**Pull request by rabuzarus**
* remove `<br>` tag from poke_content.tpl and use css instead
* move javascript from poke.php to poke_head.tpl
* file description for poke.php
* some minor cleanup for sql to fit the general coding style

### CODE REVIEW

**Comment by annando** [comment]
If you want to set CSS values that are valid for all themes please define in "view/global.css". Could you do this for this pull request?

**Comment by rabuzarus** [comment]
OK, I change it

**Comment by rabuzarus** [comment]
done. but frost/frost-mobile don't make use of global.css. So I didn't change it in this both themes

**Comment by annando** [comment]
Thanks. I think we have to consider adding the global.css to "frost" as well.

**Pull request merged**
