### PR TITLE
bugfix #1307

### PR DESCRIPTION
**Pull request by tugelbend**
Fixes the issue. Can someone (Michael?) check to make sure that this fix doesn't reintroduce the issue fixed by https://github.com/friendica/friendica/commit/bf147ca9d96df6e3ab38001b34349dae0e74ed45#diff-f228b89ec4b9c9ef9457ec748c08cbb2

### CODE REVIEW

**Comment by annando** [comment]
@fabrixxm @Beanow Should we accept this pull request for the "develop" branch or for the 3.4?

**Comment by Beanow** [comment]
I think 3.3.4 as hotfix.

Michael Vogel <notifications@github.com> schreef op 22 maart 2015 02:12:35 CET:

**Comment by fabrixxm** [comment]
I'll merge this in "develop" and merge develop back in release-3.4, so the change will be in release..

**Comment by Beanow** [comment]
@fabrixxm that's absolutely not right. If anything it should be the other way around.

**Comment by Beanow** [comment]
Ok so I was not able to revert this anymore and merged 3.4 back to develop. But an unknown number of commits now made it in to 3.4 that were targeted for develop.

@fabrixxm can you check that you have fast-forwards off for merging? https://stackoverflow.com/questions/5519007/how-do-i-make-git-merges-default-be-no-ff-no-commit I was unable to figure out the state of the 3.4 branch before the merge because of ff.

**Comment by Beanow** [comment]
Wait a minute. There shouldn't even be a branch for release-3.4 yet. o.o

**Pull request merged**
