### PR TITLE
identity selector use now the profile pics

### PR DESCRIPTION
**Pull request by rabuzarus**
@annando : can you have a look at the sql request? Can it be done this way or did I miss something.

There are some minor gui glitches  where I don't know how to solve it:
* there is a little bottom padding of 3px between profile-pic and button (you will notice it when you are select the profile - have a look at the blue border)
* at duepuntozero (easterbunny color scheme) the background doesn't cover identity-selector-wrapper

At some later point I would like to expand it with displaying pending connections and unread mails.

### CODE REVIEW

**Comment by annando** [comment]
You should only query for the "self" parameter - not the other one. And then you should use the uid field. Hopefully this could match with the $id variable.

**Comment by annando** [comment]
I just had a look. The "identities" array contains the "uid". This you could use.

**Comment by rabuzarus** [comment]
OK I changed it.

I have a question. In my first attempt I tried to respect the logic of contact connections. I mean by this that I took the uid of the present user and look in the contact table for his entries which were filtered by nick $ name of the contact. If nothing found than it should respect self because it could be the "self" entry of the present user.

In the end to look only for uid and self does the same for this scope. But isn't it something like a workaround? What is if someone wants to change something at an other place in the code and don't get the expected result? Sure it's just one query but if you have more of this parts it could get really frustrating. In bad cases there even might be security risks.

Note: this should be no critique. It's meant as a serious question
It's meant to be an serious question

**Comment by annando** [comment]
It isn't a workaround. It is the correct way to only take the contacts that are marked as "self". This functionality is meant to switch between different users. This means that you have to use data that is connected to the user. So the first place to look would be the user table. But: The user table has no field for the avatar picture. So you need a table that is connected with the user table. This could be the profile table (with "is-default") or the contact table (with "self").

**Pull request merged**
