### PR TITLE
Add support for relative URL in HTML documents

### LINKED ISSUE #8623: Cant fetch Atom link from Hugo website generator
### Expected behavior

I pass the root of a Hugo generated website to the `Add New Contact` field in `/contact` page and get to see the Atom feed in there

### Actual behavior

An error message says: 
> The network type couldn't be detected. Contact can't be added.

### Friendica version you encountered the problem

2020.03 Red Hot Poker

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #8623

And improve performances by removing a duplicate curl call!

And increase RFC compliance!

And adds TESTS!

And smells good!

### CODE REVIEW

**Comment by MrPetovan** [comment]
This PR is inaccurate, RFC 1808 has been obsoleted by [RFC 3986](https://tools.ietf.org/html/rfc3986)!

**Comment by annando** [comment]
Means what? When systems are doing stuff like this, we should support it, no matter if the corresponding RFC tells us to not do this anymore, shouldn't we?

**Comment by MrPetovan** [comment]
Meaning that the reference to RFC 1808 in the method comment is wrong and should be updated with a reference to RFC 3986. The latter describes roughly the same behavior, but we don't have to update the method's code because we weren't following RFC 1808 to the letter exactly either.

**Comment by annando** [comment]
Ah okay.

**Pull request merged**
