### PR TITLE
Remove RINO altogether

### LINKED ISSUE #4272: [Urgent] Upgrade defuse/php-encryption to version 2 to ditch mcrypt requirement
#4259 reintroduced an regression dependency to `mcrypt` : https://github.com/friendica/friendica/pull/4259#issuecomment-358521690

This is because we manually edited the `defuse/php-encryption:1.21` library files before moving them to Composer.

Version 2 fixes this dependency: https://github.com/defuse/php-encryption/blob/master/docs/UpgradingFromV1.2.md

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #4272

Self-excludes with #4276

I'm only doing it because @fabrixxm [suggested it](https://github.com/friendica/friendica/pull/4276#issuecomment-359032528)!

### CODE REVIEW

**Comment by annando** [comment]
Now I'm totally confused, since there are concurrent PRs.

**Comment by MrPetovan** [comment]
If we decide to merge this one, we’ll close the other one. If we decide to merge the other one, I’ll close this one.

Both solve the unecessary mcrypt requirement regression, it just is a matter of philosophy.

**Comment by MrPetovan** [comment]
Closed by #4276

**Comment by annando** [comment]
But we really should discuss about it.

**Comment by MrPetovan** [comment]
Let’s open an issue then.

**Comment by tobiasd** [comment]
On Fri, 19 Jan 2018 22:55:49 +0000 (UTC)
Hypolite Petovan <notifications@github.com> wrote:

> Let’s open an issue then.

It always saddens me when a discussion about such a thing targeting a communication tool is done outside of the communication tool. For me the developers forum is a much better place then some thread at github *nobody* reads.

**Comment by annando** [comment]
I would prefer a discussion in the developer forum as well.

**Pull request closed without merging**
