### PR TITLE
Add manifest module to backend module list

### LINKED ISSUE #6927: `/manifest` generates an user session on each page load
### Expected behavior
Manifest page not to require nor generate a session in DB.

### Actual behavior
Each page load contains a call to `/manifest` and that, in turn, generates one log entry `index [NOTICE]: no data for session` and a new row in DB.

### Steps to reproduce the problem
Load any page. (e.g. "Home")

### Friendica version you encountered the problem
854cc3e47296d4a1b01b893376064cf254d84f79

### Friendica source (git, zip)
git

### PHP version
7.3.3

### SQL version
MySQL 5.7, structure update 1304.

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #6927

### CODE REVIEW

**Comment by lapo-luchini** [comment]
BTW: I tried (manually) back-porting this simple patch to my 95a16c8017360957aea130633d2f0e335bd66245 installation but it doesn't fix #6927 there, but I guess this depends on other feature that are currently in the development branch. I'll wait. ;)

**Comment by MrPetovan** [comment]
I don't think it depends on other features, what are you still witnessing?

**Comment by lapo-luchini** [comment]
```diff
diff --git a/src/App.php b/src/App.php
index b5ad68321..008988c56 100644
--- a/src/App.php
+++ b/src/App.php
@@ -742,6 +742,7 @@ class App
                        'fetch',
                        'hcard',
                        'hostxrd',
+                       'manifest',
                        'nodeinfo',
                        'noscrape',
                        'p',
diff --git a/src/Core/Session/DatabaseSessionHandler.php b/src/Core/Session/DatabaseSessionHandler.php
index 9bb1180ec..aa665db36 100644
--- a/src/Core/Session/DatabaseSessionHandler.php
+++ b/src/Core/Session/DatabaseSessionHandler.php
@@ -31,7 +31,7 @@ class DatabaseSessionHandler extends BaseObject implements SessionHandlerInterfa
                        Session::$exists = true;
                        return $session['data'];
                }
-               Logger::log("no data for session $session_id", Logger::TRACE);
+               Logger::log("no data for session $session_id in $_SERVER[REQUEST_URI]", Logger::TRACE);

                return '';
        }
```

```bash
$ tail -n1 -F friendica.log
2019-04-06 19:29:01 index [NOTICE]: no data for session brr7eb00j057svo71eg4fra9uu in /manifest [] {"file":"DatabaseSessionHandler.php","line":34,"function":"read","uid":"679b263","process_id":54873}
```

**Comment by MrPetovan** [comment]
Thanks for the elaboration.

**Comment by MrPetovan** [comment]
I can reproduce this for `/manifest` and a bunch of other modules supposed to be in the backend list.

**Comment by MrPetovan** [comment]
Found the issue, thanks for the follow-up! https://github.com/friendica/friendica/pull/6995

**Pull request merged**
