### PR TITLE
Move mod/manage to src/Module/Delegation

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #4090 

This PR also introduces a new module routing error: Method Not Allowed. This error should only show during development when the route settings aren't completely set yet. It is useful to distinguish an existing route with the wrong allowed methods rather than a missing/incorrect route altogether.

Addon pendant: https://github.com/friendica/friendica-addons/pull/900

### CODE REVIEW

**Comment by nupplaphil** [comment]
@mrpetovan there are 'real' failed tests in this PR, just in case you didn't see it because of the drone noise ...

**Comment by AlfredSK** [comment]
Interesting. This PR introduces a new route error 'Method not allowed' and the tests are failing because of an error 'Method not allowed'.

**Comment by MrPetovan** [comment]
> @MrPetovan there are 'real' failed tests in this PR, just in case you didn't see it because of the drone noise ...

Ah, thanks, I've tried to blindly edit the tests as much as possible as I can't run database tests locally but yeah I've been glossing over failed tests because of Drone.

**Comment by MrPetovan** [comment]
Let's see how it goes.

**Comment by MrPetovan** [comment]
And now it passes.

**Pull request merged**
