### PR TITLE
Event preview

### PR DESCRIPTION
**Pull request by rabuzarus**
This is a port of red's event preview for the event creation. It only works if the Web-Editor (TinyMCE) is switched off.

### CODE REVIEW

**Comment by tobiasd** [comment]
What does it change? I see no effect, but I might just be to sleep drunken and need more coffee noticing it ;-) Or is it a theme dependent effect?

**Comment by rabuzarus** [comment]
It's not theme dependet. 
It creates a preview button on /events/new   . After pressing you will get a colorbox popup with a preview of the event.

**Comment by tobiasd** [comment]
Ok, that I see :-) but what does not work when the editor is enabled?

**Comment by rabuzarus** [comment]
If the WebEditor is enabled you will not see the event description and the place in the colorbox popup (only title, start and end date)

**Pull request merged**
