### PR TITLE
Introduce new way of static/dynamic bridge / CleanUp deprecated methods

### PR DESCRIPTION
**Pull request by nupplaphil**
This is the attempt to replace the `BaseObject::getClass()` method with something easier usable.

I introduce `Friendica\DI` as a new, static container which returns dynamically loaded classes. Each new class has to be added as `/* @method static Class class() */` phpDoc and added to the const array.
That's it, now it's usable as `DI::class()` and it's typesafe :-) .. So no more `object` returns and no more `getClass()` abstract calls.

e.g.: `DI::dba()` returns a `Database` instance, `DI::cache()` returns a `ICache` instance.

I already replaced a lot of calls and I'm currently replacing all "deprecated" `App`-methods as well. It's a little bit of cleanup, so the codebase will get a little bit more readable (currently a lot of code is strikethroug with "deprecated" but without a proper replacement - until now).

Draft because I'm not finished ;-)

### CODE REVIEW

**Comment by MrPetovan** [comment]
Oooh, I like but it's going to be a pain to fix the tests 😅

**Comment by MrPetovan** [comment]
So, what about model classes like the one I introduced for introductions? Do they still have to be instantiated with `getClass`?

**Comment by nupplaphil** [comment]
Almost there.. Interesting to see that I accidentally reused the Dependency instances of predecessors.. So I think this will the tests more deterministic I guess..

**Comment by nupplaphil** [comment]
> So, what about model classes like the one I introduced for introductions? Do they still have to be instantiated with `getClass`?

I have to take a deeper look..
- If there's just one instance of this model class, then yes
- If there' s one instance per model entity, I'll rather say not directly.. Maybe indirectly because of another model/factory class which will then be the instance per DI :)

I'd say we wait for the merge of this PR after the release so I can rebase it onto the model changes from you and I make a guess how I think it should work ( easily).

**Comment by nupplaphil** [comment]
Yeah.. Tests are fixed :) localy everything is working so far, next step is rebasing after the release and adding the missing calls because of the RC phase :)

**Comment by MrPetovan** [comment]
There should be one object per entity so `getClass` wouldn’t be appropriate.

I get I’ll have to create a factory like this:
```php
public static function createById($id) {
    return new self(DI::db(), ..., $id);
}
```

**Comment by nupplaphil** [comment]
Or we create a common `ModelFactory` class and add a `getAccountById()` Method, so we don't have to overload the class itself with functionallity and have a straight blueprint for future models.

**Comment by MrPetovan** [comment]
I kinda like having the static factory method inside the model class. I’m not sure I like the dictionary class you’re suggesting, since it needs separate attention each time we create a new Model class.

The dictionary for global instances makes sense to me, but I’m against it for model classes.

**Comment by nupplaphil** [comment]
Mhm .. maybe you got me wrong, sorry. What I mean was:

```php
class \Friendica\ModelFactory 
{
      /** @return Account */
      public function getAccountById(int $id) {
           [...]
           return new \Friendica\Model\Account(...);
      }
}

// calling it per
$account = DI::modelFactory()->getAccountById($id);
```

Introduced by the newest Dice-version, we don't need to add all Model-dependencies as a "courier" because it now supporta self-injetction (and we don't need to add one dependency-entry inside `dependencies.conf.php` for it ^^):

```php
class \Friendica\ModelFactory
{
    /** @var Dice */
    private $dice;

    public function __construct(Dice $dice)
    {
        $this->dice = $dice;
    }

    public function getAccountById(int $id);
    {
        [...]
        return $dice->create(Account::class, $data);
    }
}

// calling it per
$account = DI::modelFactory()->getAccountById($id);
```

**Comment by nupplaphil** [comment]
> Why the choice of ordering by namespaced class names rather than dictionary key name?

Because on a long run, we maybe have to split the `DI` class in smaller classes for App, Core, Util, ... For example "Item" will be inside 2-3 different namespaces and I think it's more intuitive to have `Content::Item`, `Model::Item`, ... than `DI::contentItem` and `DI::modelItem`. But that's a followup just in case of.

And so I sorted it to see how the different namespaces are growing

**Comment by nupplaphil** [comment]
So.. I moved the entity-core functionality to a own class "entity". These entities are now fetchable through the model itself and are not bound to **any** dependency. The model itself can be called straight forward with `DI::intro()` (as prommissed without any config ;) ). This patterns should be easy usable now and adaptable for further models.

**Comment by nupplaphil** [comment]
temporary close .. I think I got a straighter idea..

**Comment by MrPetovan** [comment]
I must admit I’m not a fan of `DI::intro()->reject($intro);`. What’s wrong with the factory setting up dependencies?

**Comment by nupplaphil** [comment]
We should differ between entities (plain types of our domain model) and the repository/service layer.

If we would use the current model and create f.e. during a worker-run 1.000 of entities or update them, we would call 1.000 times a update statement (and instance the whole model logic 1.000 timea). If we separate these two types of classes, we can take an array of entities and create one single update call for all of them. And we can optimize the way we create new entities (like with the Prototype pattern).

**Comment by MrPetovan** [comment]
It’s true, but then I’d say we need collections object classes. I’d rather we move away from static classes and methods especially if they take an object as first argument.

**Comment by nupplaphil** [comment]
hm .. We mix two different types of classes, we should really let the entity classes be as independent as possible. I see them as a alternative to arrays.. We wouldn't overload arrays with business logic, we build it around them. That's how entities are working too with the difference that they are type-safe, bound to a persitance-layer and have a defined set of attributes.

I took my ideas from here:
* https://designpatternsphp.readthedocs.io/en/latest/More/Repository/README.html
* https://designpatternsphp.readthedocs.io/en/latest/Creational/Prototype/README.html

**Comment by nupplaphil** [comment]
Hmm.. Maybe we can load the model into the entities not the other way.. I'll give it a try..

**Comment by MrPetovan** [comment]
I created Mastodon API entity classes because we need them to transform our local data model into a well-defined data structure, but we don't mean to interact with them. On the contrary, why limit ourselves to glorified arrays for our own entity classes when we can directly add meaningful methods like the ones I added to the Introduction class?

**Pull request closed without merging**
