### PR TITLE
Restore expected implementation of JsonLD::fetchElementArray

### LINKED ISSUE #9465: Mastodon's custom emojis don't show anymore
Mastodon's custom emojis used to be shown in individual posts. They didn't in display names and profile description because the emojis weren't shipped with the profile information like they used to be with the posts. Did anything change in Mastodon's AP post structure?

Do we have to store the custom emojis per remote server for posts as we needed to do anyway for display names/profile description?

### LINKED ISSUE #9525: [Mastodon] Emojis aren't replaced in incoming messages
For quite a while now I've noticed Mastodon emojis aren't replaced in individual posts.

Today I found the issue: the emojis have been moved to the AP `tag` key instead of being stored in a separate object key.

### PR DESCRIPTION
**Pull request by MrPetovan**
Fix #9525 (and fixes #9465)

### CODE REVIEW

**Comment by annando** [comment]
Is this some partly revert of the JsonLD functionality?

**Comment by MrPetovan** [comment]
No, more like fixing a regression and making `fetchElementArray` consistent with `fetchElement`.

**Comment by annando** [comment]
Since that function is really crucial, I would suggest that you work with it until we know that not only emojis are niw processed as well, but also the other data is still fetched correctly.

**Comment by MrPetovan** [comment]
As you can see, I only added parameters to the method, and all the existing tests are successful. Maybe the tests aren't complete, though, but my real-world test shows that messages are still received correctly.

**Comment by MrPetovan** [comment]
Emojis aren't replaced multiple times now thanks to `strstr` over `str_replace`.

**Comment by annando** [comment]
Did my test post arrive?

**Comment by MrPetovan** [comment]
The test post arrived but my dev node was on the other branch so the emojis weren't replaced.

See this one instead: https://dev-friendica.mrpetovan.com/display/52acf9cd-c7664bb793b3d4be-910562d8

**Pull request merged**
