### PR TITLE
The "summary" field seems to be interpreted as plain text only

### PR DESCRIPTION
**Pull request by annando**
See here: https://mastodon.social/@Gargron/101773986084943145

### CODE REVIEW

**Comment by MrPetovan** [comment]
Is it for all ActivityPub targets or just Mastodon?

**Comment by annando** [comment]
It is for the whole AP world.

**Comment by tobiasd** [comment]
Which also means, that Friendica contacts will get an summary, which is displayed as CW depending on the title right?

**Comment by nupplaphil** [comment]
Hm.. I was interested how AP defines such things. I found a reference at https://www.w3.org/TR/activitystreams-vocabulary/#dfn-summary 

> ... object encoded as HTML

So shouldn't the HTML encoded text have worked? Or am I on a compleley wrong place? :D

**Comment by tobiasd** [comment]
Then I'd say stick with the definition and point out the bug at the receivers and.

**Comment by annando** [comment]
@tobiasd Friendica contacts don't get the "CW" stuff. For "Friendica => Friendica" we are skipping this field, since we do have the BBCode content in the "source" field.

@nupplaphil this field had been added just for the convenience of Mastodon users. So we can file an issue but should stick to serving plain text by now.

**Comment by nupplaphil** [comment]
Ok, so I'd like to create an issue at the mastodon repo and linking this PR.

**Comment by tobiasd** [comment]
The CW was displayed [in the Friendica Support forum](https://forum.friendi.ca/display/0b6b25a8-185c-8e2b-08c0-132751537133) from a summary field that was coming from a Friendica (AP) source. I just wanted to make sure that this is not any longer the case.

**Comment by annando** [comment]
@tobiasd this is fixed with the current RC. But: Users with Friendica in the develop or stable branch will currently see these "CW" things.

**Pull request merged**
