### PR TITLE
Statistics Sheets

### PR DESCRIPTION
**Pull request by StefOfficiel**
Create statistics sheet : 
screenshot

No design in basic template. The page design is not because I do not have time to do so. I just built the parsing json. Once I have a few minutes, I will do a visually cleaner space, with a real simple design.

I now begin the design with Bootstrap to my theme, I will inspire for the default theme.
My statistics.tpl : 
screenshot

### CODE REVIEW

**Comment by fabrixxm** [comment]
I'm sorry, but there are some problems with this patch:

1.
the module isn't following the structure of a module. A friendica module must have one of the three functions
```php
function modulename_init(&$a){ ... }
function modulename_post(&$a){ ... }
function modulename_content(&$a){ ... }
```
where `modulename` is the name of your module. The function are called 

- on module init (after the core found that the request url is handled by that module and it loads it),

- when the module is called by a POST request

- to get the html content. must be returned by the function as a string

take a look at any existing module to see how it works.

2.
Your module depends on the activation of a plugin. Core modules must not depend on plugins to operate.

But, anyway...
3.
You module loads via an http request data that are available directly to the code.
Why? [here](https://github.com/friendica/friendica-addons/blob/8c96978e2c47dbb656eb20931f118d048afe18fc/statistics_json/statistics_json.php) is the code that generate the statistics.json file.

But anyway...
4.
It's almost the same info you can get at [/friendica url](http://diaspored.s-pichard.fr/friendica)
Maybe you want to style and/or extend that page. (starting with movin html from php to a proper template.. hint hint ;-) 

I'm closing this pull request

**Comment by StefOfficiel** [comment]
Sorry, false branch, good branch here : https://github.com/friendica/friendica/pull/1532

**Comment by StefOfficiel** [comment]
I'm holliday, I re-read it it quietly in my TGV tonight! Thank you for that. By cons I did not understand the last sentence (the one that ends with "hint hint")!

**Comment by tobiasd** [comment]
There is already a page in friendica (yourhos.tld/friendica) displaying some informations about your node. Maybe you could enhance this page, not making a new, was what Fabio hinted for I guess.

**Comment by StefOfficiel** [comment]
Indeed, it is a plugin, I had to activate the installation of my POD and I remembered more.
Yes indeed, I wanted to give a style to statistics. Therefore, I think it might make more sense that statistics are publicly accessible to everyone.
I will think again about all that with your information.
Thank you ;-)

**Pull request closed without merging**
