### PR TITLE
Fix delivery counter for poking / unify delivery commands

### PR DESCRIPTION
**Pull request by annando**
The delivery counter hadn't worked for the poking. While fixing this, I had a look at all the delivery commands and unified them. Now only constant values are used. All the constants had been checked and are reduced to only the really needed values.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Nice work!

**Comment by annando** [comment]
I'm currently thinking if ```Delivery``` is the correct class for the constants, but changing that shouldn't be part of the RC phase.

**Comment by annando** [comment]
This is weird. Github says "Some checks haven’t completed yet" although clicking on that link reveals that all checks had been completed.

**Comment by MrPetovan** [comment]
Thanks for looking out.

**Comment by nupplaphil** [comment]
> This is weird. Github says "Some checks haven’t completed yet" although clicking on that link reveals that all checks had been completed.

This could happen in case the PR got merged before completing the travis check. But doesn't matter for the overall tests :-)

**Comment by annando** [comment]
In this case it wasn't committed. That's what I find weird :-)

**Pull request merged**
