### PR TITLE
Update develop from master-2019.09

### PR DESCRIPTION
**Pull request by MrPetovan**

### CODE REVIEW

**Comment by MrPetovan** [comment]
No conflict, self-merging.

**Comment by AlfredSK** [comment]
What about the addon repo? 🤔

**Comment by tobiasd** [comment]
It just got an update

**Comment by MrPetovan** [comment]
The last commit on both develop and master in the addons is showing to be 7 days ago, what did you do exactly?

**Comment by tobiasd** [comment]
I merged master into develop before I deleted the RC branch on the addons repository.

**Pull request merged**
