### PR TITLE
Add term_type index to term table

### LINKED ISSUE #6319: tag completion painfully slow
### Expected behavior
When you add a tag while composing a new post or comment in Frio (don't know about other themes) the system tries to display some suggestions for the tag completion. These suggestions must be displayed instantly to be of any use.

### Actual behavior
When your database is huge as mine the tag completion/suggestion takes around 20 seconds. This makes this function not only useless but even looking like a bug.

Imagine you type a tag and then you continue to write your text or some other tags and all of a sudden the tag completion popup shows up around 20 seconds after you typed the tag. 😂

So my suggestion is to add some index for the corresponding query to speed up the tag completion (or whatever works) or remove this function completely.
Another possibility would be to make the tag completion configurable for the node admin. So it could be deactivated on larger nodes (with a small database it works well).

### Friendica version you encountered the problem
2018.12-rc

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #6319

Thanks @AlfredSK for his valuable input.

### CODE REVIEW

**Comment by MrPetovan** [comment]
I forgot to update the CHANGELOG 🙊

**Comment by annando** [comment]
This could lead to some SQL error on some MySQL installation, because of index length restrictions. Instead we should use some prefix: https://dev.mysql.com/doc/refman/5.6/en/create-index.html#create-index-column-prefixes

**Comment by MrPetovan** [comment]
Which installation? On MariaDB I believe have the index length restriction and adding the index went fine.

**Comment by AlfredSK** [comment]
Yeah. Could be a problem. It's the old max index length issue with some MySQL configurations.

The term field is a varchar 255 field. Combined with utf8mb4 (4byte charset) this can lead to an index length of 1023 (?) bytes. However, the max index length for some MySQL configs is 767 bytes.
This can be mitigated by reducing varchar fields to 191 characters or by limiting the indices (what Michael said).

I always recommend to configure MySQL/MatiaDB in a way that eliminates that annoying issue with index lengths.

**Comment by annando** [comment]
We should restrict the index length to something around 64 characters.

**Comment by AlfredSK** [comment]
Yeah. I think 64 should be ok. It covers the term #Rindfleisch­etikettierungs­überwachungs­aufgaben­übertragungs­gesetz (63 characters). 😆

**Comment by MrPetovan** [comment]
Fair enough, I'll submit a correction.

**Comment by MrPetovan** [comment]
There, happy? #6934

**Pull request merged**
