### PR TITLE
[frio] Improve thread display

### PR DESCRIPTION
**Pull request by MrPetovan**
Last step of #6552

My initial goal was to fix the comment box behavior when explicit mentions were enabled, but I ended up redesigning the whole thread display in frio and touching other themes in the process because unfortunately, we are generating HTML in the common PHP files.

Here's the (almost) final display on frio:
friendica_thread_redesign_final_1
friendica_thread_redesign_final_2
(I restored the margin between submit buttons after taking the screenshots)

### CODE REVIEW

**Comment by tobiasd** [comment]
> and touching other themes

Is their look & feel suffering by these touches?

**Comment by MrPetovan** [comment]
I don't know if it's suffering. The main behavior difference so far is that hidden comment now slide up and down when clicking on "Show more" and "Show less", and the label keeps showing the number of comment whether additional comments are hidden or shown.

**Comment by MrPetovan** [comment]
Oh, and the double ` - - ` comes from an unfortunate translation in Transifex.

**Comment by AlfredSK** [comment]
Is this ready for merging? I'm looking forward to see this one live in action. :-)

**Comment by rabuzarus** [comment]
There is one thing. @MrPetovan is running this already on his server. Am I right. If I visit his profile I have several issues.
1.) I don't get authenticated
2.) Even though I'm not authenticated I can see a comment box at the bottom of posts which does have already comments (this should be the standard behavior if the user is authenticated)
3.) if I click into the comment box to write something, the comment box disappears

Example Post: https://friendica.mrpetovan.com/display/735a2029-205c-645f-d54e-ff8517707254

**Comment by MrPetovan** [comment]
Ha, good catch, I'll look into it this afternoon.

**Comment by AlfredSK** [comment]
And maybe there should be a margin between the preview/submit buttons and the preview area.

commentbox-margin

**Comment by MrPetovan** [comment]
@AlfredSK Done.

**Comment by MrPetovan** [comment]
@rabuzarus Done.

**Pull request merged**
