### PR TITLE
Move mod/common.php to src/ Part 3: Add Module\Contact\Contacts class

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #8918
Part of #4090
Follow-up to #8975

This is it, the one stone that kills two birds. I've added to contacts the same contacts display that we were using for local profiles with the relationship filter, which makes both the `mod/common` and the `Module\Allfriends` modules obsolete.

I've developed this feature on a system that didn't have any contact discovery enabled, so as with #8975 please tell me whether or not it works on your system.

This PR also fixes a potential privacy/security issue where the session wasn't actually destroyed on logout. 😨

### CODE REVIEW

**Comment by annando** [comment]
Are you only displaying contact relations with `follows`? I think on systems with deactivated contact discovery and with contacts that aren't AP or DFRN we should automatically switch to interactions instead.

**Comment by AlfredSK** [comment]
> issue where the session wasn't actually destroyed on logout.

Oh! Could this explain why I sometimes had been thrown back into the previous session after switching accounts via 'manage accounts'?

**Comment by MrPetovan** [comment]
> > issue where the session wasn't actually destroyed on logout.
> 
> Oh! Could this explain why I sometimes had been thrown back into the previous session after switching accounts via 'manage accounts'?

I don't exactly know, I witnessed this with the Logout module in remote visit context but it is probable. The problem is that we don't store empty session data, which means that just emptying the `$_SESSION` superglobal like we did wasn't enough to clear the session.

**Comment by MrPetovan** [comment]
> Are you only displaying contact relations with `follows`? I think on systems with deactivated contact discovery and with contacts that aren't AP or DFRN we should automatically switch to interactions instead.

I'm not sure about this, it's counter-intuitive to me because it isn't the same information at all. I have added a message saying "No known contacts" when there is nothing to fetch and I'll leave it at that.

**Comment by annando** [comment]
The group of contacts someone follows and the group of contacts someone interacts on are mostly similar. And since the discovery is optional and not available for all contacts, this whould be a good compromise. I see the list of followed/interacted contacts as some sugegstion whom to follow. So I would like to have content in it. To avoid confusion the link description could be different for the different purposes.

**Comment by MrPetovan** [comment]
Good on you for having a similar group of people you follow and interact with. However, this is far from being the universal case. I angrily reply to many accounts I would never follow, and I do not want them to be shown in this screen. It's fine for the common tab because it's an intersection of interactions, so negative interactions are less likely to show up (unless someone I disagree with is checking our common interactions but it's irrelevant).

**Comment by annando** [comment]
I think it is the best just to ask the users if they see a benefit in it. I guess I will make a forum post about this.

**Comment by MrPetovan** [comment]
Closes #8918

**Pull request merged**
