### PR TITLE
Missing "use" in boot.php

### PR DESCRIPTION
**Pull request by annando**
See here: https://forum.friendi.ca/display/174591b4135a02f50f6a578731360597

### CODE REVIEW

**Comment by AndyHee** [comment]
Thanks for the quick response.

Sorry but the issue persists somehow. This is the error I'm getting now.


```
[error] 27237#27237: *3262 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function get_config() in /var/www/friendica/addon/pageheader/pageheader.php:79
Stack trace:
#0 /var/www/friendica/include/plugin.php(223): pageheader_fetch(Object(Friendica\App), '')
#1 /var/www/friendica/include/plugin.php(205): call_single_hook(Object(Friendica\App), 'page_content_to...', Array, '')
#2 /var/www/friendica/index.php(327): call_hooks('page_content_to...', '')
```

**Comment by zeroadam** [comment]
@AndyHee it would appear that you are not on the most current version of the master branch of the addons repo. Try updating and let us know if that fixes it for you!

**Comment by AndyHee** [comment]
Thanks! That was exactly the problem.

Works like a charm now!

**Comment by zeroadam** [comment]
Great!

**Pull request merged**
