### PR TITLE
[php7] Remove PHP code highlighting

### PR DESCRIPTION
**Pull request by MrPetovan**
This is a long-standing issue with the pear text highlighter.

There has been an outstanding fatal error with text highlighting which prevented all text highlighted posts to be saved/displayed.

A PR (https://github.com/pear/Text_Highlighter/pull/5) has been submitted 6 months ago but nobody has merged it into the library.

Beyond that, PHP text highlighting was messing up conversion from/to HTML/BBCode/Markdown.

It will optionally be done instead by highlight.js in a new addon: https://github.com/friendica/friendica-addons/pull/737

### CODE REVIEW

**Comment by annando** [comment]
Do we really have to do this for the current RC? When this had been some bug for several months, than we could move this to the next release and could test it there extensively.

What does @tobiasd, @fabrixxm or @rabuzarus think of this?

**Comment by fabrixxm** [comment]
As this PR is only for remove the highlighter code, to me it's ok to merge it.

**Comment by MrPetovan** [comment]
I can finally receive posts with highlighted code from Diaspora!

**Comment by MrPetovan** [comment]
Coincidentally, this also fixes URL being wrongly turned into link in code blocks.

**Comment by MrPetovan** [comment]
> As this PR is only for remove 

My favorite kind of PR!

**Comment by annando** [comment]
It does not only remove the highlighting, but also adds some stuff whose consequences I can't simply see. When merging this, we possibly had to wait another week for the release. Or we should be prepared for some bugfixing release in the case that something went terribly wrong.

**Comment by MrPetovan** [comment]
What can be more wrong than Friendica rejecting all code blocks from Diaspora? This PR is confined to code blocks and the babel module, that's really all there is to it.

**Comment by MrPetovan** [comment]
Ha, I found a display issue on Diaspora side:
Friendica: https://friendica.mrpetovan.com/display/735a2029185b9fdf9582d4f561708038
Diaspora: https://framasphere.org/posts/5647511#735a2029185b9fdf9582d4f561708038

The language appears in the actual code block.

Where can I actually test what's sent to Diaspora other than `mod/babel`?

**Comment by MrPetovan** [comment]
I found an issue with single-line language code blocks in the underlying HTML to Mardown library, I [opened an issue](https://github.com/thephpleague/html-to-markdown/issues/161) and [submitted a PR](https://github.com/thephpleague/html-to-markdown/pull/162).

**Comment by annando** [comment]
What does mean this issue to this PR?

**Comment by MrPetovan** [comment]
It fixes the issue I self-reported in https://github.com/friendica/friendica/pull/5765#issuecomment-422097903

**Comment by MrPetovan** [comment]
Alright, this PR is now complete.

**Comment by MrPetovan** [comment]
Fixes #4496

**Pull request merged**
