### PR TITLE
ping.php: Ensure data structure consistency

### LINKED ISSUE #2968: js errors with new json ping.php
When visiting a remote profile on a foreign server (through redir) I can see empty notify badges (while there shouldn't be any notify badges)
The js console gives the error message `main.js:219 - Uncaught TypeError: Cannot read property 'length' of null(…)`

empty_notify_badges

### PR DESCRIPTION
**Pull request by Hypolite**
Fixes #2968

- Moved declaration of data structure at the top of ping_init
- Formatting
- Documentation

### CODE REVIEW

**Comment by rabuzarus** [comment]
I wouldn't remove all the js debug messages since they don't leak privacy informations and aren't that much messages. They are rather an informative character what is going (and do help to identify bugs if we change code in php and haven't think about the js part)

**Comment by Hypolite** [comment]
If we don't think about the JS part, there's no reason to clog everyone else's log with such messages. It's not about privacy or security, just about housekeeping. Not having console.log lying around just is a habit I have. Sure it doesn't hurt, but it doesn't serve any real purpose either, hence they shouldn't be part of the committed code.

**Comment by rabuzarus** [comment]
Mhhh, I agree only partially. The js logs often help me to identify how some features are solved in friendica (js vs php). Whats wrong with such information like `Loading page 2` ? It is no complex debug info. It is rather a very simple information what is going on which doesn't hurt and which don't disturb.

I'm very pleased if other projects do it the same way so I don't have to study their whole code to understand the simple logic what is going on.

For the php part we have several debug levels. We can set it according to our needs. In our js part we don't have this possibility. So we should provide at least some simple information which doesn't float the debug log and doesn't leak privacy information.

**Comment by Hypolite** [comment]
I understand your point, and if there was a consistent logging system throughout the JS files, I wouldn't have touched it. At the moment, there just are a few calls randomly placed, which made me think that removing them wouldn't do much. Like I said, this was mainly a cosmetics change. Since you can't fully debug the JS part solely with the current `console.log` occurences, you will have to add some debug during your dev work anyway. Might as well make the production code clean.

**Comment by annando** [comment]
@rabuzarus I haven't had a look at the PR because you already responded to it. Is it mergeable from your point of view or are there changes needed?

**Comment by rabuzarus** [comment]
Yes can be merged (but I'm a little bit sad about the removed js logs)

**Pull request merged**
