### PR TITLE
Stop generating photo URLs with contact IDs in favor of guids

### LINKED ISSUE #13935: switch to new photo scheme for all user avatars (not only local user avatars)
Objective: Prevent enumeration attacks on both local users **and** remote contacts known by the node.

Feature: Friendica should switch to the new photo scheme for all user avatars. Currently this is only supported for local user avatars.

Background: This got attention when https://github.com/friendica/friendica/pull/13931 was created to resolve a problem with low resolution image previews over Mastodon API.
While the code has remarks about a new photo scheme being used and to disable `Contact Id Fallback after 2021.12`, it turned out, the new mechanism is only used for local user avatars.

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #13935

- This prevents an enumeration attack against avatar pictures
- Replace several DB calls to `contact` table with `account-view` or `account-user-view`
- Remove unused parameter photo_size from Directory::formatEntry

### CODE REVIEW

**Comment by MrPetovan** [comment]
Phew, this PR has unearthed various issues with the API fixture data. Different base host name, user-specific contact IDs used in place of public contact IDs, all were fixed thanks to the new code that's more strict than before.

**Comment by annando** [comment]
I guess I won't be able to check such a huge PR today, since I will be away today. Are we postponing the release? I would had a bad feeling when we wouldn't wait for at least two weeks with a release after this PR had been merged.

**Comment by MrPetovan** [comment]
This PR can wait for further review/testing. In particular the API part that I can’t test in real conditions, just with the unit tests. Desktop is fine and doesn’t show any slowdown but my server is overpowered so it isn’t a good yardstick.

**Comment by MrPetovan** [comment]
This branch is now running on my main node.

**Comment by annando** [comment]
The contact guid is not always set. It is missing for example for the connector accounts like Bluesky or Tumblr. Execute `select network, count(*) from `account-view` where guid is null and not failed group by network;` on your system to see on your system. Question is, if `uri-id` would be enough. Although this is enumerated, that field is used all over the place for everything with an URL, means not only contacts, but also posts.

**Comment by MrPetovan** [comment]
```
MariaDB [friendica]> select network, count(*) from `account-view` where guid is null and not failed group by network;
+---------+----------+
| network | count(*) |
+---------+----------+
|         |        1 |
| apub    |     1711 |
| dfrn    |      823 |
| dspr    |     1176 |
| feed    |      340 |
| mail    |        2 |
| pump    |        1 |
| stat    |        5 |
| twit    |    12635 |
+---------+----------+
9 rows in set (2.096 sec)
```
Hmmm.


> Question is, if `uri-id` would be enough. Although this is enumerated, that field is used all over the place for everything with an URL, means not only contacts, but also posts.

It doesn't matter, you can still run a script that generate avatar picture URLs and you keep the ones that aren't ending in 404 errors.

Does it mean I have to go back to my original idea to assign a unique identifier to every public contact?

**Comment by annando** [comment]
We could use the function to create a guid out of an uri that we have got in the item class. We are normally using that function to create our guids for the posts.

**Comment by MrPetovan** [comment]
Unfortunately I can’t use `System::createGUID` because it’s based off the current timestamp and the initial generation for all existing contacts would create contact GUID too close to each other. Are contact URLs unique for each contact, including connector contacts?

**Comment by annando** [comment]
I meant the function `Item::guidFromUri`, that creates a "dummy" GUID. But: This wouldn't work for Bluesky, since their URI doesn't contain a hostname at all and the function currently relies on this. But of course you could create some function just for the contacts that does something similar. Only thing is: I suggest to use some scheme that looks similar but not identical to GUIDs, so that we can see which ones are real GUIDs and which one are ours.

**Comment by MrPetovan** [comment]
What do you mean by "scheme"?

**Comment by MrPetovan** [comment]
This PR is going nowhere with the `guid` field.

**Comment by annando** [comment]
Can you isolate your work at the API fixtures? I guess this is unrelated to the rest of the work?

**Comment by MrPetovan** [comment]
It is unrelated but also it doesn't fail in the base branch?

Created a reduced PR: https://github.com/friendica/friendica/pull/13942

**Pull request closed without merging**
