### PR TITLE
Reduce page size in contacts pages

### PR DESCRIPTION
**Pull request by MrPetovan**
I realized after pulling that the default page limit of 50 is too much for contact lists.

### CODE REVIEW

**Comment by annando** [comment]
Wouldn't it be better having a general setting for all pages that show contacts?

**Comment by MrPetovan** [comment]
No, it isn't as resource intensive as the item pages, so it doesn't warrant a specific setting. I would argue for limiting all pages to 30 items by default in the Page itself though.

**Comment by annando** [comment]
I can imagine two separate settings for items per page and contacts per page. This should be identical on all pages of the system.

**Comment by MrPetovan** [comment]
What about the mobile page limit?

**Comment by annando** [comment]
If a shorter contact page limit for mobile devices does make sense, then possibly we would need this setting as well.

**Pull request merged**
