### PR TITLE
Improve bin/run_xgettext and regenerate master messages.po

### PR DESCRIPTION
**Pull request by MrPetovan**
Addresses the root cause of https://github.com/friendica/friendica/issues/8475#issuecomment-609410910
Follow-up to #8501

### CODE REVIEW

**Comment by tobiasd** [comment]
Wasn't the root cause, that @annando had the call to `l10n::t(` copy and pasted twice into the string that that when the strings got extracted the doubled call was added to the string extracted. See #8439

Though I'm not sure were the doubled call came from in the French translation.

**Comment by annando** [comment]
@tobiasd I guess so. I feel myself unable to proofread shell scripts. So the question is if the result from the previous version and that version here differs. And if, where.

**Comment by MrPetovan** [comment]
The root cause of the presence of `l10n::t(` in the french `strings.php` was that `l10n::t(` was also present in the master `messages.po` file, which would have made @annando 's manual change to the French `strings.php` moot the next time we would have imported French translations from Transifex.

So yeah, when he fixed the PHP file, we should have regenerated the master `messages.po` file.

The improvements to `bin/run_xgettext,sh` are only tangential. I remember @tobiasd saying that the script was still parsing the `addon` folder even though it shouldn't have, so I set out to fix it, and as usual one thing led to another, I added a progress ratio.

**Comment by annando** [comment]
Is it possible to still run this script *inside* the addon folder?

**Comment by tobiasd** [comment]
You never did. For the addons you generate the `messages.po` file with the `single` parameter (IIRC it was the `single` parameter)

**Comment by MrPetovan** [comment]
Yes, the problem was when the script was run in the main folder, it used to wrongly scan addons as well.

**Pull request merged**
