### PR TITLE
Post permissions are now copied from the thread parent

### PR DESCRIPTION
**Pull request by annando**
This fixes the issue that comments on non public posts weren't distributed anymore. This was caused by the fact that comments in AP have their own permissions that can be different to the post they are referring to.

When creating comments, we now copy the permissions from the thread parent.

### CODE REVIEW

**Comment by tobiasd** [comment]
Does this also solve the problem of not distributed comments in non-public conversations?

**Comment by annando** [comment]
I had exactly this in mind, when coding this.

**Comment by tobiasd** [comment]
What happens with replies from Friendica to non-public comments in threads?

**Comment by annando** [comment]
It is all up to the sender to determine the permissions. So with this coding we use the permissions from the thread parent - except when using the Mastodon style API and you don't select "private". The server will store these permissions. And since the sender copied the permissions, the sender also distributes the comment directly to all receivers.

The receiver doesn't distribute the comment to anyone who isn't addressed in the comment, since we cannot be sure if this could be some post that was meant only for the receiver.

**Pull request merged**
