### PR TITLE
Removed some unused tables and functions

### PR DESCRIPTION
**Pull request by annando**
I guess we have to go through some more tables to see if they are in use.

### CODE REVIEW

**Comment by annando** [comment]
No, the version only needs to be updated when there are changes that require a database update (added or changed fields, added, removed or changed indexes).

**Comment by MrPetovan** [comment]
So this means the relevant tables won't be removed on existing installs, only on new installs?

**Comment by MrPetovan** [comment]
Is there anything else or can I merge right away?

**Comment by annando** [comment]
We never remove tables nor fields because they could have been created by addons or whatever.

You can merge it, if you want to.

**Comment by rabuzarus** [comment]
Just a little hint. The db entries in the documentation must also be removed

**Pull request merged**
