### PR TITLE
active response

### PR DESCRIPTION
**Pull request by tobiasd**
cherry-picket some of the *active response* commits from @Hypolite that accidentally went into the wrong branch

### CODE REVIEW

**Comment by Hypolite** [comment]
Sweet, thanks!

**Comment by Hypolite** [comment]
Does it cover completely #2827?

**Comment by tobiasd** [comment]
I think it covers the non-conflicting commits.

**Comment by annando** [comment]
I delegate the job to @Hypolite to check this pull request :)

**Comment by Hypolite** [comment]
Actually, here are the missing commits:
- https://github.com/friendica/friendica/pull/2827/commits/b9468df1e6bc6dd3c07ad780a9ec89dd1706789a
- https://github.com/friendica/friendica/pull/2827/commits/3321e36dd5bd8a530bfb2094f8e35040bf8dcf00

**Comment by tobiasd** [comment]
frost is not supported anymore. I'll make a restart of cherry-picking with the other commit you mentioned, could be I overlooked it due another conflicting commit.

**Comment by Hypolite** [comment]
I know frost isn't supported anymore, but this isn't a usual cherry pick, the commit already is on `master` and just needs to be ported to `develop` for consistency.

**Comment by tobiasd** [comment]
ok, then it is there as well

**Comment by Hypolite** [comment]
@tobiasd Are you planning on cherry picking [the commit fixing the pending registration issue](https://github.com/friendica/friendica/pull/2827/commits/fac2d9a880a1e10a613bbbc7bddd7e461c5d9dbf) in a separate PR?

**Comment by tobiasd** [comment]
It is conflicting and now my local repository is in a broken state again, hope you don't find any other commits

**Comment by Hypolite** [comment]
Should be the last one. The others were translation commits that can be overwritten by an import from Transifex.

**Comment by annando** [comment]
@Hypolite is it mergeable from your point of view?

**Comment by Hypolite** [comment]
Yep, fire away!

**Pull request merged**
