### PR TITLE
API Support "friendica_html"

### PR DESCRIPTION
**Pull request by annando**
This is an alternate solution for https://github.com/friendica/friendica/pull/7345

### CODE REVIEW

**Comment by nupplaphil** [comment]
Can you check if there are tests which are testing this function? I think there are assertions on the formatted api text, which can get adapted so the new fields of this PR will be included too.

But I've to check it at home.

**Comment by annando** [comment]
I'm not sure how to check or test this. The ```/tests``` folder is a huge white spot on my map.

**Comment by nupplaphil** [comment]
OK, there is no explicit test for formatting of items. So from my side, the PR is OK.

**Comment by annando** [comment]
@MrPetovan the other PR had got this new field even in the retweeted or quoted parts. My change only has got this new field in the root part. I do argue that this is enough, since this is the original HTML (without the OEmbed part) that shows the quoted or retweeted part like on the web page.

**Pull request merged**
