### PR TITLE
adding new brown color frio scheme "autumn"

### PR DESCRIPTION
**Pull request by vinzv**
as seen on [less.re](https://less.re)

### CODE REVIEW

**Comment by MrPetovan** [comment]
We have been having a conversation about how many pre-made color schemes we should provide, especially if they only are palette changes without additional custom styles.

See #5782

And https://forum.friendi.ca/display/0b6b25a8855ba74cc1c124a503688251

**Comment by vinzv** [comment]
The thread seems to have no final decision but I understand that adding some color-only scheme is not wanted by everyone. So maybe I'll extend the scheme to some more features.

**Comment by MrPetovan** [comment]
Theming always has been @rabuzarus 's private garden so we kind of tiptoe around it, but on the other hand he's not been consistently active to timely decide on these questions either, so it's a hard one.

**Comment by rabuzarus** [comment]
You are right. At the moment my time is very limited. I'll try to make my thoughts clear if I can, but at the moment I don't have the time and the energy to have very long discussions.

**Comment by JeroenED** [comment]
When #6722 is merged following string can be used to set this theme.
```JSON
{"nav_bg":"#655a4a","nav_icon_color":"#ffffff","link_color":"#777777","background_color":"#ededed","background_image":"","contentbg_transp":"100","login_bg_image":"https://downloads.jeroened.be/autumn.jpg","login_bg_color":"#655a4a"}
```

**Comment by MrPetovan** [comment]
Superseded by #6722

**Pull request closed without merging**
