### PR TITLE
Fix composer notices

### PR DESCRIPTION
**Pull request by nupplaphil**
fixes notice like:
> Deprecation Notice: Class Friendica\Util\PidFile located in ./src/Util/Pidfile.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/src/friendica/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

> Deprecation Notice: Class Friendica\Worker\CleanWorkerQueue located in ./src/Worker/CleanWorkerqueue.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/src/friendica/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

> Deprecation Notice: Class Friendica\Test\src\Util\JsonLDTest located in ./tests/src/Util/JSonLDTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///vagrant/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by nupplaphil** [comment]
interessting .. on my local node the API tests went well .. Seems like the github action tests doesn't like global variables ..

**Comment by MrPetovan** [comment]
Interesting new test errors.

**Comment by nupplaphil** [comment]
There were some type mismatching. I fixed almost every case by type-casting, but `$this->self`has as default parameter a boolean value, so I casted the value of the array as a boolean too => therefore I had to alter the test.

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
Part of #8796

**Pull request merged**
