### PR TITLE
Avoid an error in OnePoll when the contact was "null".

### PR DESCRIPTION
**Pull request by annando**
This is done to avoid this error:
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Friendica\Model\Contact::unmarkForArchival() must be of the type array, null given, called in /path/to/friendica/src/Worker/OnePoll.php on line 624 and defined in /path/to/friendica/src/Model/Contact.php:249
```

### CODE REVIEW

**Comment by MrPetovan** [comment]
I'm glad the type hints are doing their job, but wouldn't it be more effective to remove the reference in the parameter list?

**Comment by annando** [comment]
I wouldn't wanted to dig deeper where the reference might be in use.

**Comment by MrPetovan** [comment]
I looked into it, you can safely remove it in `consume_feeds`, I wouldn't go further yet.

**Comment by annando** [comment]
In a second step we can remove the last two parameters of ```consume_feed``` since this isn't needed anymore.

**Comment by MrPetovan** [comment]
Even better!

**Pull request merged**
