### PR TITLE
template-rework: let common friends and allfriends use viewcontact_te…

### PR DESCRIPTION
**Pull request by rabuzarus**
…mplate.tpl

common.php and allfriends.php do now also use the viewcontact_template.tpl.

* I don't now if a photo_menu is needed at this pages. If it would useful I would add it.
* Should 'url' => $rr['url'] better be 'url' => zrl($rr['url']) ?

### CODE REVIEW

**Comment by annando** [comment]
From where are these pages called? Are they called from logged in users or non logged in users? Depending on that we should add a menu or not.

**Comment by rabuzarus** [comment]
these pages where called from logged in users. Contact edit page -> common friends (or show all friends)

BTW I think there is a security issue with common friends. If you have the the uid and cid you can request it from the outside (not logged in) through the url. Is this behavior intended?

**Comment by annando** [comment]
I think it should contain all menu entries like the search page. Can you check if the page is called from somewhere else? if not then you should add a check for a local user.

**Comment by rabuzarus** [comment]
How do I check something like this?

**Comment by rabuzarus** [comment]
At least if let search through the code for "common/loc" I find it only in contacts_content() .

**Comment by annando** [comment]
There is another place where common profiles are shown: When you are visiting a remote profile. Then there shouldn't be a menu I think.

**Comment by rabuzarus** [comment]
I guess for visiting remote profiles another piece of code is used than this one. But I will have a look at this in the evening.

**Comment by rabuzarus** [comment]
@annando 
Only to get it right. With place where common profiles is shown you mean if someone visit a profile and above of the stream of posts is an area with common contacts. Am I right?

If I get you right, then I would say that both use the same function common_friends( )   (socgraph.php) but for profile pages it is requested from common_friends_visitor_widget( )  (contact_widgets.php) and the page which you reach from the contact edit page is constructed by common_content( ) (common.php)

**Comment by annando** [comment]
@rabuzarus you are right. When showing the common contacts from /common then it should have the regular menu. (And it should only be viewable by a local user). When showing the common contacts from the profile then there shouldn't be a menu.

**Comment by rabuzarus** [comment]
OK this is no problem since other code does the common contacts on the profile page is another one.
Common Contacts (the one we are talking about :-)   ) should have the menu from the contacts page or something else?

Which menu does make for allfriends sense?

**Comment by annando** [comment]
I haven't checked. But: Isn't it always the same menu? (Of course depending if we are connected to this contact or not). You could have a look at "mod/dirfind".

**Comment by rabuzarus** [comment]
in the contact page it's generated with contact_photo_menu( ) . On the other contact relating pages it is always written new ($photo_menu = array(....    ).
In dirfind the photo_menu contains "Show Profile" and "Connect". I think this doesn't make not too much sense for common friends. Since you already connected to this contacts you don't need "Connect". Then there would be only "Show Profile" left. It's a little bit strange that the only menu point which is inside the menu have the same effect as if you would simply click on the profile picture. But maybe we should do it for consistency.

**Comment by annando** [comment]
Have a look here: https://github.com/friendica/friendica/blob/develop/mod/dirfind.php#L136

This part of the code is called when we know the contact.

**Comment by rabuzarus** [comment]
we don't get the CID from common_friends() (socgraph.php) and from common_friends_zcid( ) for the array in which each contact (with its information) is written. Can you as 'master of sql' have a look at common_friends( ) if it's possible to extend the function. The connection between gcontact, glink and contacts is a mystery to me. Especially the glink table (would be nice to have some description for the keys cid, uid, gcid, zcid).

**Comment by annando** [comment]
I will have a look this evening.

**Comment by annando** [comment]
@rabuzarus I just did a pull request for the functions "all_friends" and "common_contacts": https://github.com/friendica/friendica/pull/2002

Now these functions return the value "cid" (which is the contact id). On "all_friends" the "cid" value is null if this contact isn't a common one.

**Comment by annando** [comment]
Addition: Please send the avatar pictures through the proxy function:
````thumb' => proxy_url($rr['photo'], false, PROXY_SIZE_THUMB),````

**Comment by rabuzarus** [comment]
Thanks a lot for all your work.
Today I have no time to look at it. Maybe I find some time this week but I can't promise it. Just leave the PR open. Finishing this is on my list and I will do it as soon as I find some time to work on it.

**Comment by annando** [comment]
No problem. If you need some more support functions, just let me know. If you haven't got time until the hackathon then I maybe would continue your work there if you don't mind.

**Comment by rabuzarus** [comment]
:+1:

**Comment by rabuzarus** [comment]
I just have a short look into this. Three points come to my mind.
1.) you wrote that the pictures should go through the image proxy. Isn't this already done in get_contact_details_by_url() ?
2.) would it be a good idea to replace the already available information (e.g. name, url, photo and so on) with the one of get_contact_details_by_url()  or should the one of the original query be used ?
3.) could we extend get_contact_details_by_url() to have the `addr` generated if it doesn't exist?

Concerning 3.)
I'm not sure if it is a good idea. I would rather have that all contacts which could be presented in the way username@node.com have an entry `addr` in the contact table. I don't know why this isn't done but maybe there are other reasons why only a small part of my entries of the contact table have a value for `addr`.

**Comment by rabuzarus** [comment]
Mhh, in my contact table only `self` entries have the correct location and keywords. For the contact connection entries the these values are empty.

**Comment by annando** [comment]
Concerning the proxy: The "$rr['photo']" is a result of the SQL query. It is not passed through the proxy function. So it has to be done before the data is pushed into the profile.

Concerning the "addr" field: I want to extend the discover function that is used to generate this data. Then it will be filled automatically.

And: In my tests I have discovered that sometimes (often?) the gcontact entry contains better data than the contact table entry. I have to check that. But I think we shouldn't use the "get_contact_details_by_url" if we can avoid it. If we can avoid making SQL queries, I guess we should.

**Comment by rabuzarus** [comment]
OK, I have done some work on it. 
This needs some further polishing. But this have do be done together with the other contact related pages.
E.g. `about` is yet not implemented on template side. This must be discussed together. Also I'm not really satisfied with the way how it looks at the present state. But since it won't make things worse I would like to move this point to another time.

**Pull request merged**
