### PR TITLE
Added forgotten DBA::close

### PR DESCRIPTION
**Pull request by annando**
Possibly this helps with https://github.com/friendica/friendica/issues/8546 - possibly not.

But we forgot to close the database connection at two places. And one of them is called very often.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Just two places, huh?

Since we don't support unbuffered queries anyway, should we still use this tricky fetch form?

**Comment by annando** [comment]
I don't think that `fetch` and `close` are that tricky. And I don't believe that we really load the whole result set into the memory. Currently I'm performing several tests where I creates queries that return more than a million lines. I don't think that this would work with arrays.

**Comment by MrPetovan** [comment]
I did the test last year where I compared the memory footprint of `selectToArray` VS `select + fetch + close` and they were the same. I looked into unbuffered queries and saw that we would have to change the way we currently execute queries. Worse, we would have to change in two different places depending on the database driver used, PDO or mysqli. As a result I dropped my efforts and that's where we are right now.

**Comment by annando** [comment]
I would prefer not chaning this until we are using resultset objects. I really would go into that direction. I also defined the views so that in the future we could create resultset classes from them.

But this is some very different task :-)

**Comment by MrPetovan** [comment]
I completely agree, that's why I stopped my efforts, I'm just saying there currently is no benefit to using `select + fetch + close` over `select + toArray`.

**Pull request merged**
