### PR TITLE
 vier: replace hard coded style paths

### PR DESCRIPTION
**Pull request by Andi-K**
The Style "Shadow" works now as intended and don't produce "file_get_contents(): Filename cannot be empty" warnings.

I am not sure how to report intercepted errors.   The logger does not seem to be designed for this purpose.

### CODE REVIEW

**Comment by MrPetovan** [comment]
What do you mean by "report intercepted errors"?

**Comment by MrPetovan** [comment]
Ah, I see now. The logger really isn't designed for a specific purpose, it is a firehose of messages not all relevant to anything. So I'd say it's perfectly suited for yet another message.

**Comment by annando** [comment]
I would like to have added a call for ```basename(...)``` to ensure that there is no chance of a directory traversal.

**Comment by Andi-K** [comment]
If we make use of basename(), not in the theme itself.
mod/view.php sets `$THEMEPATH = "view/theme/$theme";` and this since 2012.
Don't see the need of it but hey it's faster done then disputed.

**Comment by annando** [comment]
We should do checks on every place where we fetch data. If you see additional places, it would be great to change that places as well.

**Comment by Andi-K** [comment]
Oh, I haven't slept enough. 
I confused basename() with basepath to avoid traversing directories through a changed current working directory. A issue I had to deal with some time ago.
Of course, I shouldn't trust the data from the database either.

**Pull request merged**
