### PR TITLE
Avoid warning "Failed to write session data"

### PR DESCRIPTION
**Pull request by annando**
Hopefully this solves the warnings.

### CODE REVIEW

**Comment by AlfredSK** [comment]
Hey! Great. I'll test it as soon as it is merged. :-)

**Comment by annando** [comment]
@AlfredSK Test it :-)

**Comment by zeroadam** [comment]
I'm not sure if this merge was the cause, but I am now unable to login to
my node. No error, just redirects me to the /network# page, which displays
login inputs.

**Comment by AlfredSK** [comment]
The warnings are gone. Good, but...

````[NORMAL]:dba.php:578:e  DB Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE `sid` = '36roj5qt7u2esm4heios6tb422' AND (`data` != 'sysmsg|a:0:{}sysmsg_i' at line 1
UPDATE `session` SET `data` = 'sysmsg|a:0:{}sysmsg_info|a:0:{}last_updated|a:1:{s:11:\"profile:3::\";i:1509475839;}', `expire` = 1509655839 WHERE WHERE `sid` = '36roj5qt7u2esm4heios6tb422' AND (`data` != 'sysmsg|a:0:{}sysmsg_info|a:0:{}last_updated|a:1:{s:11:\"profile:3::\";i:1509475839;}' OR `expire` != 1509655839)````
Looks like an SQL problem. Some messages are about "...AND (`data` != 'sysmsg..." and some about "...AND (`data` != 'remember...".

**Comment by AlfredSK** [comment]
Is there simply a double WHERE in that query?

**Comment by AlfredSK** [comment]
One WHERE is coming from $condition in session.php, I guess. But where does the second WHERE come from?

**Comment by annando** [comment]
From some stupid programmer.

**Comment by AlfredSK** [comment]
@zeroadam You should clear your browser cache and cookies! Worked for me. Maybe you have to wait until the fix is merged.

**Comment by zeroadam** [comment]
I did do a crtl+F5 but not a full "clear cache", but I figured I might have
to wait for the next merge. Thanks!

**Comment by annando** [comment]
The PR is accepted, please update urgently.

**Comment by zeroadam** [comment]
Excellent, gentlemen! I have just successfully logged into my node. Fix
confirmed! Thanks for the quick work :)

**Pull request merged**
