### PR TITLE
Remove unused contacts

### PR DESCRIPTION
**Pull request by annando**
There is now a config option to remove all inactive contacts. This is a feature that needs testing, that's why there isn't any frontend settings for that. Important: I haven't executed it on my system, so I can't tell about performance or any problems.

### CODE REVIEW

**Comment by tobiasd** [comment]
After which time are contacts archived again?

**Comment by annando** [comment]
The archival is done, when a contact failed for some time (by default 32 days), see this function: https://github.com/friendica/friendica/blob/develop/src/Model/Contact.php#L1090

**Comment by tobiasd** [comment]
So the deletion would be after 32 days (put into archive) + 30 days (from this PR)?

I just stumbled over that [@todo](https://github.com/friendica/friendica/blob/develop/src/Model/Contact.php#L1113) note in the archiving process. Especially in combination with the automatic removal this would be nice to have. Maybe also one letting the user know that the contact is now archived and that it will be automatically deleted if that option is set on the node.

**Comment by annando** [comment]
This PR doesn't delete any contact that is connected with a user on this system. It only deletes contacts that have no local connection and no posts on this system. And depending on the setting of the new variable, either the contact will be deleted only when archived (this is the default) or every time when this condition is true.

The default behaviour is something that we do now for a long time. But until this PR we waited for an additional year to remove an archived contact. We now don't wait for that time any more.

**Comment by tobiasd** [comment]
I see :)

**Pull request merged**
