### PR TITLE
[Hotfix] Fix #2816 - [Admin] Unable to save config items present in .htconfig.php but not in DB

### LINKED ISSUE #2816: [Admin] Unable to save config items present in .htconfig.php but not in DB
I was trying to set the default system theme in the Admin when I noticed that my selection was not remembered, while I could see other config changes being correctly saved.

It turns out the admin save action checks for the existence of a config value before trying to insert or update a row in the database. However, if a default value is defined in the `.htconfig.php` file, the config value will be considered to exist in the database, but the resulting `UPDATE` query will be unsuccessful because the record doesn't exist.

This issue can be averted by using the `REPLACE` query statement which create a record if it doesn't already exist in the table, or update the row if it exists. However, it relies on a `PRIMARY` or `UNIQUE` key, which would be on the couple of fields `config.cat` and `config.k`. There already is an index on those fields, but it's not set as `UNIQUE`.

I don't know how complicated it is to push a database migration change, and depending on the difficulty, I can propose an alternative fix which wouldn't rely on such a key by adding a simple existence check query before the `INSERT` or `UPDATE` query. Please note this wouldn't be ideal because it would significantly slow down the admin settings save action.

As a side note, the `.htconfig` header stating:

    /* *********************************************************************
     *  The configuration below will be overruled by the admin panel.
     *  Changes made below will only have an effect if the database does
     *  not contain any configuration for the friendica system.
     * *********************************************************************/

Is not exactly true at the moment, since any value present in the file but not in the DB cannot in fact be updated through the Admin Panel.

### PR DESCRIPTION
**Pull request by Hypolite**
This is an emergency PR to fix a broken feature (see #2816). Please merge as soon as possible.

### CODE REVIEW

**Comment by tobiasd** [comment]
no need for calling this "hotfix" I think ;-)

**Comment by Hypolite** [comment]
Why not? It is quickly fixing a bug that's preventing certain Admin settings from being saved without any hint about what's going on.

Moreover, to me it is not the best long term solution to check a DB setting existence, but it's the easiest fix that can be shipped ASAP.

**Comment by tobiasd** [comment]
It is a fix. It may not be the ideal one and you might want to dive into the problem deeper later, but for now it is the best fix available. Usually fixes for issues are being accepted ASAP no need to make extra pressure there.

**Comment by Hypolite** [comment]
Alright, I don't what the release schedule is yet so if we were using hotfix releases, I think this would have been a good candidate. I'm just using industry-standard terms when something important is broken on production, can be easily fixed and skip the usual release schedule.

I've seen that PRs are reviewed within a day which is very enjoyable, however I still wanted to set a sort of priority order between other uncritical PRs.

**Comment by tobiasd** [comment]
Well, there are Milestones which have targeted release dates. But if there is something urgent we may to release faster and if the Milestone has problems, during RC phase e.g., the date can be postponed. The numbers for these Milestones are also not set into stone, so that what is now called 3.5.1 will most likely 3.5.2 I think. We try to have a release per quarter more or less..

**Comment by Hypolite** [comment]
Gotcha, then it definitely applies for hotfix to me if we aren't releasing soon, but you are the judge of that, sorry for the unwarranted pressure.

**Comment by tobiasd** [comment]
Well see the discussion at the developers forum ;-)

**Pull request merged**
