### PR TITLE
See issue 3157: Fulltext is now disabled

### PR DESCRIPTION
**Pull request by annando**
See https://github.com/friendica/friendica/issues/3157

In the 3.5.2 we can then decide how to proceed with this.

### CODE REVIEW

**Comment by tobiasd** [comment]
In this case the issue should be moved then to the next milestone.

**Comment by rabuzarus** [comment]
There is another usage of fulltext engine in `mod/content.php` which you should comment out

**Comment by annando** [comment]
mod/content.php is not in use. It was some trial that started years ago and was never finished.

**Comment by rabuzarus** [comment]
Then we should delete or uncomment it

**Comment by annando** [comment]
It already starts with this comment:
````
// This is a purely experimental module and is not yet generally useful.
````
I would like to do the clean up in the next version. Then we can also go through all libraries and could remove all unused ones.

**Pull request merged**
