### PR TITLE
The "term" table is removed

### PR DESCRIPTION
**Pull request by annando**
Due to moving to the new tables for the tag and categories we don't need this table anymore.

### CODE REVIEW

**Comment by annando** [comment]
I'm currently experiencing test problems. I guess that our test data violates the foreign key rules.

**Comment by nupplaphil** [comment]
yep .. It does only load the item-data, which was needed for the expected output. I think we have to add all necessary foreign keys now.
The items, defined here
https://github.com/friendica/friendica/blob/bf8bb47d7de5b653a128a96ca703c58aa8b90a4a/tests/datasets/api.fixture.php#L103
do need the expected values for `item-uri` and the other tables, which are now bound with forein keys.
So for each added item, we need a corresponding entry, like
```php
	'item-uri'    => [
		[
			'id'          => 1,
			'uri-id'      => 1,
			...
		],
		...
	],
	'...'
```

**Comment by annando** [comment]
@nupplaphil I guess that's the problem. I just changed something in the database so that database errors thow an exception when in test mode. Then we should see better.

**Comment by annando** [comment]
I think that a mode that directly throws an exception on a database error should be interesting for the tests. I'm sure that the missing "uri-id" fields are the problem. But I guess that there will be more to come. Then such things should help.

**Comment by MrPetovan** [comment]
The logger is already logging an error, isn't it just about making sure the logger outputs error-level messages during tests?

**Comment by annando** [comment]
We also could throw an exception whenever we log an error. This would be a good thing for the future. I'm currently just fixing database errors directly in the test that would need to be fixed anyway.

**Comment by annando** [comment]
There are some more side tables that now have to be filled.

**Comment by annando** [comment]
And now I found a basic problem that will affect any new installation that is based upon the current develop branch. We have to manually insert the "dummy" records for the permissionset and the contact with the id "0" (like we do it in the update function) during the installation process.

**Comment by annando** [comment]
There are three errors in the tests that I don't understand.

**Comment by nupplaphil** [comment]
hm .. You cannot call the tests local, can you? Because it would be interessting, if the three errors occurs if you test them separately. If not, it's maybe a cleanup problem.

You could add the following anotiations before the tests (in the phpDoc) to ensure that they are using a clean start:
```php
/**
 * @runInSeparateProcess
 * @preserveGlobalState disabled
  */
```

**Comment by annando** [comment]
@nupplaphil I don't have some local test possibility.

**Comment by nupplaphil** [comment]
> @nupplaphil I don't have any local test possibility.

I cloned your branch and the three tests are failing separately too. So there is a mistake in the calls. I'm debugging it, what is happening

**Comment by nupplaphil** [comment]
OK I found the reason for the StorageManagerTest fails, but I'm unable to get the root cause.
The DB-Fixture for these tests aren't loaded correctly.

 It seems like every row of https://github.com/friendica/friendica/blob/develop/tests/datasets/storage/database.fixture.php is loaded correctly, **except** this line:
https://github.com/friendica/friendica/blob/bf8bb47d7de5b653a128a96ca703c58aa8b90a4a/tests/datasets/storage/database.fixture.php#L43

At the `develop` branch, the DB-field `data` for this particular photo-item is filled correctly, at the `no-term` branch, only this specific entry is empty (all the other photo-items - including their data-fields - are loaded correctly)


Additionally, during the debugging, I found that this call:
https://github.com/friendica/friendica/blob/ec3290da3b11fd9ff243b77b5de5246478b1325a/src/Database/Database.php#L985
is adding the whole parameters of each select **again**, so the `$params[]` array contains all parameters twice with the same key, and the same values. This doubles each loop of `$params[]` in the latter calls

Could that be a regression or is this an expected behavior? Could this result in strange inserting-problems?

**Comment by annando** [comment]
The `array_merge_recursive` call is correct. This is due to the "on duplicate ..." call. But I could remove the parameter i added to the "insert" call in the test that I added.

**Comment by nupplaphil** [comment]
Ah OK

I found the root cause of at least the StorageTest problem.
Plz replace 
https://github.com/friendica/friendica/blob/bf8bb47d7de5b653a128a96ca703c58aa8b90a4a/tests/datasets/storage/database.fixture.php#L45-L51
with
```php
// @todo Check failing test because of this (never loaded) fixture
//		[
//			'id'            => 4,
//			'backend-class' => 'invalid!',
//			'backend-ref'   => 'unimported',
//			'data'          => '',
//		],
```
I accidentally re-used the id `3` for two test-sets, but because of the "update On duplicate" flag, in the develop branch, the update for the second test-set didn't work (don't know why), but with the `no-term` branch, it now got (correctly) replaced.

Nevertheless, the fourth test-set is failing even on the develop branch, meaning that there is a problem with it. But I do need more time to investigate, so for now you can comment it out

**Comment by nupplaphil** [comment]
The `DBStrcuture::rename()` fails with:
`Cannot drop index 'PRIMARY': needed in a foreign key constraint`
So `clients.client_id` is now used for a foreign key constraint of another table, means that it isn't now possible to "just" rename it anymore ..

**Comment by annando** [comment]
I thought about this - and now used a different table.

**Comment by nupplaphil** [comment]
`poll.id` is an autoincrement, which isn't supported yet to rename .. In fact I think this method for renaming primary keys isn't currently really useful ... Maybe we should deactivate it with "todo - rename primary key with autoincrement and foreign key support"

**Comment by annando** [comment]
Yeah ...

**Pull request merged**
