### PR TITLE
Changing Friendica\App\Mode from static methods to public methods

### PR DESCRIPTION
**Pull request by nupplaphil**
- Changing from static methods to public methods
- Adding dev-composer-dependency Mockery for static method mocking (f.e. Config, DBA)
- Adding ModeTest with Mocking
- removing bootstrap from phpunit.xml because of double loading tests\bootstrap.php

I believe this is a more smooth way to use the mode (and to test it). And @MrPetovan you're right, it always depends on Friendica\App so for me it must not be a static class if there is a dependency...

with `composer require --dev` it also includes some new require-dev in the composer.lock. For me, they are sounding right so I leaved it in the PR.

### CODE REVIEW

**Comment by nupplaphil** [comment]
@rudloff I rewrote the basic test engine (`bootstrap.php` , `DatabaseTest.php`), because they automatically include too much code at startup (f.e. calling `new App()`). So we cannot mock anymore because almost every core class was called afterwards.

Am I right with my changes?

**Comment by nupplaphil** [comment]
btw. there was a potential Bug in App\Mode::has() because `return $this->mode & $mode` returns an integer and not an boolean value!

**Comment by nupplaphil** [comment]
btw https://friendica.philipp.info is now running with `nupplaphil/mode_followup` so this time there shouldn't be a surprise like the last time (sorry for that!)

**Comment by nupplaphil** [comment]
btw FollowUp to #5828

**Comment by MrPetovan** [comment]
> with `composer require --dev` it also includes some new require-dev in the composer.lock. For me, they are sounding right so I leaved it in the PR.

It's fine, I used `composer update --no-dev` when I updated the dependencies, which would explain why all the `require-dev` blocks were removed.

**Pull request merged**
