### PR TITLE
Fix desktop notification

### PR DESCRIPTION
**Pull request by fabrixxm**
use on/off field for enable/disable desktop notification
show only new notifications after enable
use localstorage to save enabled/disalbed and last notification id
hide settings on browsers without desktop notification

related to issue #1642

### CODE REVIEW

**Comment by annando** [comment]
Are the changes in the CSS for the notifications? If yes: Would it be possible to apply them to the global.css so that all themes would be changed?

**Comment by fabrixxm** [comment]
is for the help text of yes/no widget. but yest, global.css could be a nice place to put them

**Comment by fabrixxm** [comment]
This seems to work, only new notifications from last time are shown, user can enable/disable desktop notifications in settings.
Click on notification bring user to notification url, if onclick is supported.
It works on chrome, is hidden on IE (and any browsers without Notificaion api support), and should work on firefox. (it should because it worked, then stopped and I don't know why.. but if I launch a notification from console, they are shown...)

**Comment by fabrixxm** [comment]
bof. it doesn't work.

**Pull request closed without merging**
