### PR TITLE
Update additional features

### LINKED ISSUE #5742: Make additional features core/remove them
The Additional Features panel makes the Friendica experience inconsistent between servers. We have to decide, for each one, if we should make it standalone or remove it entirely.

Vote here: https://ethercalc.org/9zi4o5sh2yvg

Voting is free-form, however there are a few predefined words you can choose from:
- Keep: Leave the setting as an additional feature admin can lock and user can disable (when unlocked and enabled).
- Core: Force-enable the feature on all servers.
- Remove: Discard the entire feature from the project.

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #5742 

Turns out many of the discussed additional features already had been made core by executive decision, rendering the vote obsolete.

I've acted upon the remaining features that were still up for deliberation, and this is the last you'll hear from me about additional features.

I updated the spreadsheet to represent the final state.

### CODE REVIEW

**Comment by tobiasd** [comment]
As far as I remember the features got merged into core based on your first voting result.

**Comment by MrPetovan** [comment]
I've been surprised because no mention of the issue has been made but I assume the changes have been done earnestly.

**Comment by tobiasd** [comment]
IIRC it was on one of the Hackathons in Berlin or shortly after. Most likely we just forgot the issue ;)

**Comment by MrPetovan** [comment]
I realized that the people/nodes that disabled "Export public calendar" will have it enabled from next version on. It's only for public events so it shouldn't be a privacy issue, but it may be a surprise for users.

**Comment by annando** [comment]
it is something we should note in the release notes.

**Pull request merged**
