### PR TITLE
Bugfix: The message list always showed "x and you"

### PR DESCRIPTION
**Pull request by annando**

### CODE REVIEW

**Comment by rabuzarus** [comment]
Hmm one side note:
We have places in the code where we have removed baseurl, then there are places where we remove the baseurl afterwards (forgot the name of the function and don't find it now) and then there are places, like this one, where we add the baseurl.

For me as developer I don't know at the first view, which of the 3 possibilities I have to use. I think it is even harder for people who are not familiar with friendica. We should provide a system which would it make easier/clearer for developers

**Comment by annando** [comment]
There is a simple rule for removing or not removing the baseurl: The baseurl should be removed for every front end stuff where we return content for the web site. The baseurl mustn't be removed for protocol stuff.

**Comment by annando** [comment]
@rabuzarus I guess this just was a general note and no blocker for this pull request?

**Comment by rabuzarus** [comment]
Just a general not. This can't be a blocker :-)

**Pull request merged**
