### PR TITLE
Issue 8371: Alternate Solution

### LINKED ISSUE #8371: Photos uploaded in comments get no permissions
### Expected behavior

- I make a public comment to a public post.
- I attach a photo.
- The photo is public.

### Actual behavior

- The photo has no permissions.

If I go to the photo and click Permissions, it says it is public, and if I submit at that point, it becomes actually public.

> Looks like the image does not get any permission set - not even the public one. It looks like 'public' but in fact it is somehow set to 'none'.

https://libranet.de/display/0b6b25a8-125e-5f4d-0f94-670912314070

### Friendica version you encountered the problem

`Friendica, version 2020.03-dev that is running at the web location https://libranet.de. The database version is 1335, the post update version is 1329.`

### PR DESCRIPTION
**Pull request by annando**
Another way to fix #8371

### CODE REVIEW

**Comment by MrPetovan** [comment]
Thanks you, I appreciate you making the efforts to do what I think is right.

**Comment by MrPetovan** [comment]
Replace #8430 and #8431

**Comment by annando** [comment]
I don't like this workaround - but it is a compromise.

**Comment by MrPetovan** [comment]
There will be a day where we will able to remove this workaround cleanly.

**Comment by AlfredSK** [comment]
Unfortunately, the solution doesn't work. The issue is still there. No image.
https://libranet.de/display/0b6b25a8-565e-7711-0728-346911037118

**Pull request merged**
