### PR TITLE
 frio - fix image upload for prv messages

### PR DESCRIPTION
**Pull request by rabuzarus**
The ajax upload button didn't work in some modals. This should fix it.

Fixes https://github.com/friendica/friendica/issues/4868

### CODE REVIEW

**Comment by tobiasd** [comment]
Does this also fix the problem in vier?

**Comment by rabuzarus** [comment]
I did some testing with vier and I didn't recognize a problem with uploading of images in prv-messages

**Comment by tobiasd** [comment]
I can click on the button and select an image, but it is not uploaded into the posting. Using Firefox.

**Comment by rabuzarus** [comment]
Hm this seems to be another issue. In frio the problem was that the `ajaxupload.js` wasn't loaded and so the upload button wasn't working

**Pull request merged**
