### PR TITLE
Changed type from varbinary to varchar

### PR DESCRIPTION
**Pull request by Quix0r**
Changed:
- type from `varbinary` to `varchar` as Adminer and Co. wraps it around a `HEX()` making it impossible to view/edit

### CODE REVIEW

**Comment by annando** [comment]
Using `varchar` for these fields can lead to problems because of the collation. With `varchar` for example the value `ö` can (depending on the collation) be treated equally to `oe` or `o`. This is okay (and wanted) for fields like the contact name, but not for any key fields with a more technical purpose.

**Comment by Quix0r** [comment]
The columns changed by me should never contain such characters, why would I want to have a `config.cat` entry that has no alpha-numerical characters in it? And same with `cache.k` and `config.k`.

**Comment by MrPetovan** [comment]
`VARCHAR` is better for actual text intended to be indexed and loosely searched by users. `VARBINARY` is better for exact comparison which is what we're trying to do when querying config categories and keys. Beware of "should never" statements, they tend to backfire spectacularly in programming.

**Comment by Quix0r** [comment]
> `VARCHAR` is better for actual text intended to be indexed and loosely searched by users. `VARBINARY` is better for exact comparison which is what we're trying to do when querying config categories and keys. Beware of "should never" statements, they tend to backfire spectacularly in programming.

Okay, I get your point here. Hmm, then from now on I cannot use Adminer anymore to search for settings. :-(

**Comment by MrPetovan** [comment]
I'm sorry, it does remove some convenience in database display frontend, but you can still use the Query tab to get configuration values.

**Pull request closed without merging**
