### PR TITLE
frio - fixed bug in user menu for remote user - see issue #6495 

### PR DESCRIPTION
**Pull request by Ixiter**
the remote user is not stored in `$a->user`. Used the remote user nickname.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Fixes #6495

**Comment by rabuzarus** [comment]
Have you tested your PR when the remote user is a visitor. I guess the visitor (condition `elseif (Model\Profile::getMyURL())`) would also need `$remoteUser = $r[0];`

In addition the variable `$remoteUser` should be initialized at the beginning of the function.

**Comment by rabuzarus** [comment]
> How can I browse a site as visitor?

There two modes `guest` and `visitor`
`guest` means your came through remote authentication to a foreign profile (on a foreign instance) and you have an established connection with this contact

`visitor` means you came through remote authentication (or the `zrl` parameter) to a foreign profile (on a foreign instance) and you **don't** have an established connection with this contact.

Try to to search  `@rabuzarus@friendica.kommune4.de` (internal contact search should be enabled) in the nav bar search and visit my profile. You should be `visitor`

**Comment by rabuzarus** [comment]
OK. Tested it with my own account. There seems to be a bug since we implemented remote authentification through OpenWebAuth. Contacts which are authenticated through OpenWebAuth (which should be all friendica contacts who use the actual friendica release) are authentificated as `guests`.
But can you add `$remoteUser = $r[0];` for the visitors (the condition with `elseif Model\Profile::getMyURL())`) so that the bug is also fixed when users from old friendica releases visit the actual develop version?

**Comment by Ixiter** [comment]
Yes, you are right. It should be fixed as long as we have this visitors case in code..

**Pull request merged**
