### PR TITLE
[develop] Browser caching/loading improvements

### PR DESCRIPTION
**Pull request by MrPetovan**
I ran a Friendica public status page through the google PageSpeed analyzer, and it suggested a number of improvements to increase the loading speed of Friendica.

This PR adds public asset caching for Apache, and asynchronous Javascript load for frio only until I make sure everything is working properly.

Additionally, this PR requires a `composer install` to move the Composer assets from `vendor/asset` to `view/asset`.

### CODE REVIEW

**Comment by tobiasd** [comment]
Why the movement of the assets directory?

**Comment by MrPetovan** [comment]
Short answer: Because Apache doesn't allow `<Directory>` in `.htaccess`.

Long answer: I wanted to enable public caching, but only for public assets. If I put the `Expire` directives in the `.htaccess` file in the root Friendica folder,  this would also cache images from `proxy` and `photo`, although some images might be private and shouldn't be in cache. So we have to be more precise, but we can't specify directories in `.htaccess`.

The public assets used to be in `view/...` and `vendor/asset/...` so we can put a `.htaccess` file in `view/` but not in `vendor/` because it is outside of versioning. However the `vendor/asset` folder exists because we decided on it, so we can just move it to `view/asset`, and the `.htaccess` file in `view/` will enable public caching as well for the imported Javascript libraries.

**Comment by annando** [comment]
In which way will this collide with my own "expire" rules?

**Comment by MrPetovan** [comment]
AFAIK, `.htaccess` settings take precedence over virtual host config which takes precedence over server config.

**Pull request merged**
