### PR TITLE
send on ctrl+enter - resolves #13039

### LINKED ISSUE #13039: Shortcut for sharing/sending a post
### Is the feature request related to a problem? Please describe.

I do not always want to grab my mouse for sending a post.

### Describe the feature you'd like

I'd love a shortcut like "Strg-Enter" for sending/sharing. See how Mastodon/Hubzille handle that...

### PR DESCRIPTION
**Pull request by xundeenergie**
in
* comments
* prv_messages
* composer
* jot
resolves #13039

### CODE REVIEW

**Comment by tobiasd** [comment]
I think the `messages.po` check is failing for different line break positions in the generated files.

**Comment by nupplaphil** [comment]
> I think the `messages.po` check is failing for different line break positions in the generated files.

@tobiasd @xundeenergie - we use a specific version --> https://github.com/friendica/friendica/blob/develop/doc/translations.md#supported-gettext-version

The message.po check will now fail until somebody uses the right version :-)

I will add a hint in the check to use a specific version

**Comment by xundeenergie** [comment]
> > I think the `messages.po` check is failing for different line break positions in the generated files.
> 
> @tobiasd @xundeenergie - we use a specific version --> https://github.com/friendica/friendica/blob/develop/doc/translations.md#supported-gettext-version
> 
> The message.po check will now fail until somebody uses the right version :-)
> 
> I will add a hint in the check to use a specific version

I need definitely a good hint... i don't understand, what i have to do now... :)

**Comment by tobiasd** [comment]
Nothing @xundeenergie :)

The test fails probably because you are not using the exact same version of xgettext as we do on the testing machine.

**Comment by xundeenergie** [comment]
One user told me, it does not work on macOS... 

I have no mac to test it.

Can someone please help?

**Comment by MrPetovan** [comment]
I haven't updated my node yet, I'll try tonight EST.

**Pull request merged**
