### PR TITLE
Remove leading space in displayed public tags in profile page

### LINKED ISSUE #9854: Tags and tag URLs in user's profile have a leading space
- [X] I have searched open and closed issues for duplicates

### Bug Description
It has been discovered that the user defined tags in the users profile have a leading space character now. The first tag is ok - doesn't have the space character. But all following tags have that space character in the displayed tag and in the linked URL.

I also tried to edit my profile to remove the spaces between the configured tags. But it doesn't remove the spaces in the tags after saving profile (submitting the changes).

Edit: Ha! I cannot remove the spaces. `friendica, linux, fahrrad` changed to `friendica,linux,fahrrad`. Saved changes to profile. Looking again into the profile (edit mode)... spaces are still there: `friendica, linux, fahrrad`.

Example profile:
https://libranet.de/profile/alfred/profile

Example tag:
`https://libranet.de/search?tag=%20linux`

Discussion:
https://forum.friendi.ca/display/39663759-1760-0c38-f911-960433424921

### Steps to Reproduce

1.  add tags to your profile
2.  look at the tags displayed after saving the changes
3.  look at the linked URLs

Actual Result:
`https://libranet.de/search?tag=%20linux`

Expected Result:
`https://libranet.de/search?tag=linux`

### Platform Info

Friendica Version:
2021.03-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.3

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #9854

### CODE REVIEW

**Comment by annando** [comment]
Wouldn't it be better to leave the split but to trim the parameters?

**Comment by MrPetovan** [comment]
No, the `cleanKeywords` ensures the specific separator, so we can use it as is to split the string again. However, the use of this specific separator in a non-display context is debatable.

**Comment by annando** [comment]
`cleanKeywords` is only called when storing the data. So we cannot guarantee that (for example on older systems) the data could be different. I like to follow the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle).

**Comment by MrPetovan** [comment]
And before `Profile::cleanKeywords()` it was `profile_clean_keywords()`  in `mod/profile.php`, we didn't just introduce the input sanitization method. As a result I kept my changes simple because we've had complete control over input, unlike messages we accept from remote servers, for examples.

Of course I'd rather not have this particular separator for a CSV string, but I don't want to hear that this string is used as is for the display somewhere and that it became unsightly because I changed the separator. So a small and sweet change it was to address the specific issue that was reported. I know I haven't always been that tidy, often changing the whole baby with the bathwater, but it doesn't mean I can't be chirurgically precise.

**Pull request merged**
