### PR TITLE
Merge frio-specific share block template into the base template

### LINKED ISSUE #9378: Merge frio-specific share block template into the base template
See https://github.com/friendica/friendica/issues/9377#issuecomment-704632217 for a description of the issue.

Task list:
- [ ] Investigate [this interesting CSS situation](https://github.com/friendica/friendica/blob/a78b9caa3f6c05b61ce99cdd00fc8e1ee8ef8788/view/theme/frio/css/style.css#L1814-L1830) I introduced in https://github.com/friendica/friendica/pull/8740.
- [x] Replace/Merge the base `share_content.tpl` template file with the frio-specific one.
- Update/Fix display on:
    - [x] vier
    - [ ] smoothly
    - [ ] duepuntozero
    - [ ] quattro

### LINKED ISSUE #10469: Shared block displays incorrectly with RTL display names
_Originally posted by @AlfredSK in https://github.com/friendica/friendica/issues/8262#issuecomment-873558147_
> Ha! Found one. :-)
> 
> grafik
> 
> Username and date of post are inserted on the right side. But it should be on the left side.
>  
> Steps to reproduce:
> 1. Import this post on your node https://venera.social/display/67851619-983298e32d387710-a32197cb
> 2. Or use the original https://persadon.com/@danialbehzadi/106521529502265000
> 3. Click on 'Quote Share'
> 4. Look at the preview
> 
> I only used the preview function to reproduce the issue. But the same happens with the submitted share.

### PR DESCRIPTION
**Pull request by MrPetovan**
- Add BIDI support for share blocks (thanks to @ahangarha for the tip about `margin-inline-(start/end)`)
- Remove redundant share block styles

Closes #9378 
Closes #10469

### CODE REVIEW

**Comment by AlfredSK** [comment]
@MrPetovan this seems to produce some weird side effects.

See here https://forum.friendi.ca/display/0b6b25a8-1660-ede7-d5bf-96e220906019

**Comment by annando** [comment]
Most likely we should change the BBCode constant to trigger a new BBCode generation.

**Comment by annando** [comment]
The new BBCode version is now part of this PR: https://github.com/friendica/friendica/pull/10493

**Comment by MrPetovan** [comment]
> @MrPetovan this seems to produce some weird side effects.
> 
> See here https://forum.friendi.ca/display/0b6b25a8-1660-ede7-d5bf-96e220906019

Sorry about that, I should have thought about the BBCode constant.

**Comment by AlfredSK** [comment]
Works now! :-)

**Pull request merged**
