### PR TITLE
Remove vendor from git

### LINKED ISSUE #4161: Drop support for PHP < 5.6
The PHP Group doesn't support 5.4-5.5 versions anymore for 1 year and a half already: http://php.net/supported-versions.php

Shared hosting overwhelmingly provides support for PHP 5.6: http://phpversions.info/shared-hosting/

The [upcoming changes to password hashing using `password_hash()`](https://github.com/friendica/friendica/issues/3942) will bump the minimum version requirement to 5.5.

Do we have any statistics about PHP version usage among Friendica nodes?

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #4116

Redux of #4248

Closes #4161 (https://github.com/friendica/friendica/pull/4248#issuecomment-358324213)

This is it, folks, we did it, we got rid of all the PHP dependencies from the main friendica repository!

Almost 2 years after @fabrixxm first added Composer (#2334) and almost a year after I added the `vendor` folder (#3279), it is finally out of the git versioning again!

This requires an extra step for installs from the repo and an extra step for each release but it is way better manageable now.

### CODE REVIEW

**Comment by annando** [comment]
There are several admins who are doing a daily ```git pull```. Please document, what these admins have to do.

What is needed to create archives that not only do contain our coding but also the stuff under "vendor"? Think of users who simply want to download the zip and upload it to their servers via ftp. (Without PHP access).

When this is checked, we will do an announcement so that admins will know, when they have to change their workflow.

**Comment by MrPetovan** [comment]
For your first question:
```
git pull
php util/composer.phar install
```

For your second question:
```
php util/composer.phar archive
```

We still have to figure the options best suited for our need, like outputing a zip archive, but the feature is there.

**Comment by annando** [comment]
Could you update the documentation for this?

**Comment by MrPetovan** [comment]
For the git pull or the archive? I haven’t seen a relevant page in the doc for the former and the latter is for the project maintainers, so it probably shouldn’t be in the user documentation.

**Comment by annando** [comment]
I guess that @tobiasd will know a good place.

**Comment by MrPetovan** [comment]
Turns out the `composer install` part was already there : https://github.com/friendica/friendica/blob/master/doc/Composer.md

I added it back to the Install pages as well

**Comment by tobiasd** [comment]
Well, start a new file in `/doc` and add it to the `Home.md` file (and the `Readme.md` and  `de/Home.md` ones) in the Admin section. Maybe right below the Installation instructions, something like *Updating your node* or so. Don't forget to update the webpage as well. And mention it in the release notes.

Keep the documentation as simple as possible. There are many non-programmers using git directly to manage their installation.

**Comment by MrPetovan** [comment]
`composer install` has been added in all the relevant documentation pages.

`composer archive` has no place in the user/admin documentation as it will only be used by us on release days.

**Comment by annando** [comment]
Would be great, having a document that is named "update.md" (or something similar) that would tell what to do to keep the system on a current state.

And since we had a problem with this (because we changed the addons a lot), we should document there this magic git command where you can download stuff from a specific version code as well. @tobiasd knows, which command I mean.

This really should be in a separate (and short) document with a speaking name. Otherwise people won't find it, won't read it and will trash their servers and so on.

As long as we don't have some built in update functionality, it is the best - even for regular users - to use git for updates. Downloading and extracting some archive is problematic, since this won't remove obsolete files from your installation.

**Comment by MrPetovan** [comment]
Is it supposed to be in `doc`? I don’t think it should be in the root folder like `INSTALL.txt` is.

**Comment by MrPetovan** [comment]
Also, I think we should have the same master/develop branch difference on friendica-addons to reduce confusion.

**Comment by annando** [comment]
I would like to have this in /doc. Concerning the "master/develop" thing: for me it doesn't matter - as long as we and the users can handle it.

**Comment by MrPetovan** [comment]
Can you please create a develop branch that we will start to merge into from now on, and the master branch will only be updated on release days?

**Comment by annando** [comment]
I delete this task to @fabrixxm or @tobiasd - I still don't understand git.

**Comment by zeroadam** [comment]
@MrPetovan you are thinking to change the branching scheme?

**Comment by MrPetovan** [comment]
@annando Of the top of my head, on the main friendica/friendica-addons repository:
```
git checkout master
git branch develop
git push origin
```

I may even be able to do it, now that I think about it. I'll try.

**Comment by MrPetovan** [comment]
@annando Is that enough for you? I have a couple of branches in store whose PRs are blocked by this one 😄

**Comment by annando** [comment]
We should not only write a notice about that in the support forum but also on the homepage. We have to be prepared for people who are doing automatic updates every day. (from the develop branch - without being a developer) These people need to know and to be prepared.

**Comment by MrPetovan** [comment]
Can I mention multiple forums at once with @ ? I will write a simple blurb at once.

**Comment by annando** [comment]
Mentioning multiple forums doesn't work.

**Comment by MrPetovan** [comment]
Thanks! 😉

**Comment by zeroadam** [comment]
Did we already mention that php-mcrypt is required for composer? Or at least when I tried to run util/composer.phar install I got the following
`  Problem 1
    - defuse/php-encryption v1.2.1 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - defuse/php-encryption v1.2.1 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - Installation request for defuse/php-encryption v1.2.1 -> satisfiable by defuse/php-encryption[v1.2.1].
`

**Comment by MrPetovan** [comment]
Apparently we manually changed the library at some point: https://github.com/friendica/friendica/commit/f6d7ee278116c5d9d6ba77606087ecbd8a379e7d#diff-48d1bc6644af8a5b129735ddf46363c4

**Comment by MrPetovan** [comment]
I found this upgrade doc to finally switch to php-encryption 2.0 : https://github.com/defuse/php-encryption/blob/master/docs/UpgradingFromV1.2.md

**Comment by tobiasd** [comment]
The installation documentation is in `/doc` as well,

**Comment by zeroadam** [comment]
OK, so I'm currently unsure. Is this something that a PR will fix, or is there something I have to do manually? If manual, why isn't it something everyone on develop had to do?

**Comment by fabrixxm** [comment]
> I found this upgrade doc to finally switch to php-encryption 2.0 : https://github.com/defuse/php-encryption/blob/master/docs/UpgradingFromV1.2.md

Yes, and last time I checked I didn't found a way to update seamless from version we are using.
But I don't remember the details...

**Comment by zeroadam** [comment]
OK, so I'll have to wait to update my node to the current develop branch then.

**Comment by annando** [comment]
I haven't done it by now as well.

**Comment by zeroadam** [comment]
@annando I thought it was strange, it seems some other users have successfully updated. Which caused me to think "why only me who is having a problem?".

**Comment by MrPetovan** [comment]
Did you try to run `install` or `update` with Composer?

If you tried both, you have to install the `mcrypt` extension until I get around to update defuse/php-encryption.

**Comment by zeroadam** [comment]
I have only tried install so far.

**Comment by MrPetovan** [comment]
Then update will fail as well, please install mcrypt until tonight.

**Comment by annando** [comment]
A user contacted me via Twitter - he had that issue with mcrypt as well. I guess we really have to solve this with some priority.

**Comment by zeroadam** [comment]
I can just wait. I'm on arch linux and the mcrypt package is in a php71 set that conflicts with the main php packages (which is also an issue with my Nextcloud, waiting for php7.2).

My node is in a fine state to be up and running, so no worries (for me anyway)!

**Comment by MrPetovan** [comment]
Like I said, I'll look at it tonight. I had the mcrypt lib installed locally since we needed it at some point, so Composer didn't barf on me.

**Pull request merged**
