### PR TITLE
Display announces identical for starting posts and comments

### PR DESCRIPTION
**Pull request by annando**
We now display reshared comments like we display reshared starting posts.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
What sparked this change?

**Comment by annando** [comment]
Reshares are happening on the comment level as well. And sometimes they are a trigger for fetching the whole thread. So this makes it more clear. This is one step. Another step will be to allow different permissions in a single thread. This is possible in AP. By now we simply reject those messages.

**Comment by MrPetovan** [comment]
Shouldn't we show the comment reshares the same way we show comments in search results, with a "view context" link?

**Comment by annando** [comment]
With "comment reshares" I mean this one:
grafik

**Comment by MrPetovan** [comment]
Ah, you moved the label from the bottom of the post to the top!

**Comment by annando** [comment]
Only for the first one and only if it is a follower (same rule as in the starting post).

**Pull request merged**
