### PR TITLE
RU translation updates THX Alexander An

### PR DESCRIPTION
**Pull request by tobiasd**

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by SpcCw** [comment]
Just updated to stable and I notice that some translation is now missing in the notifications. I think it was translated before and also when I search Transifex by "in the thread" I see the translation is there.

Did something went wrong or these are just new strings and I need to open an issue?

image

**Comment by tobiasd** [comment]
They should be translated. See [ru/messages.po line 4703](https://github.com/friendica/friendica/blob/stable/view/lang/ru/messages.po#L4703) and more importantly the [ru/strings.php line 983](https://github.com/friendica/friendica/blob/develop/view/lang/ru/strings.php#L983). The lines are for the translation of "commented in the thread" but the other strings are around there as well.

Could you check if the translations are there in the `view/lang/ru/strings.php` file on your system?

**Comment by annando** [comment]
The translation for notifications will only come to effect on new notifications.

**Comment by SpcCw** [comment]
@annando - thanks for clarification! Yes, new notifications after the update are translated correctly.

**Pull request merged**
