### PR TITLE
hide profile help text clarification

### PR DESCRIPTION
**Pull request by tobiasd**

### CODE REVIEW

**Comment by MrPetovan** [comment]
What are those "technical reasons"? Can't we overcome them?

**Comment by annando** [comment]
We need to poll the feed addresses. This means that this whole profile hiding is more or less snake oil.

I personally see two possible ways:

1. We remove this profile hiding
2. When someone hides a profile then this person isn't allowed to post public posts or to comment on public posts or to post to public forums.

I would like to simplify this whole privacy stuff to make it more understandable and to lower false expectations.

**Comment by MrPetovan** [comment]
Can't we leave the public feed pollable with no items inside?

**Comment by annando** [comment]
Of course you can - but anyway you could always had a look at another server for the public posts of this user. And public comments would be available on the feeds of the thread owners anyway. And name and avatar had to be available via webfinger probing as well.

This profile hiding is giving you a false feeling of privacy.

**Comment by MrPetovan** [comment]
Let's remove the option then.

**Comment by tobiasd** [comment]
So that all that use the option are forced out of it? Nope.

**Comment by MrPetovan** [comment]
Like @annando said, "this whole profile hiding is more or less snake oil". Removing snake oil doesn't make anything worse. I don't like the alternative where we leave the snake oil and we clearly say it's snake oil.

**Comment by tobiasd** [comment]
It is no snake oil. The setting has a simple purpose, hiding details from the profile page. If a user then does public things, it is their choice.

**Comment by tobiasd** [comment]
If you know a better wording, please provide one. For me it is for technical reasons.

**Comment by MrPetovan** [comment]
"Anonymous visitors will only see your profile picture, your display name and the nickname you are using on your profile page. Disables posting public messages to Diaspora and other networks. Your public posts will still be accessible by other means."

**Comment by annando** [comment]
Or: "When hiding your profile, you should also refrain from creating public posts, answers to public posts or posts into public forums, since this will be visible by other means."

**Comment by tobiasd** [comment]
Thanks, will change the text this evening.

**Comment by annando** [comment]
This setting currently does not disable the posting to Diaspora or other networks.

**Comment by MrPetovan** [comment]
Updated.

**Pull request merged**
