### PR TITLE
"parent = id" is replaced with gravity check

### PR DESCRIPTION
**Pull request by annando**
Just some more places.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Test failed.

**Comment by AlfredSK** [comment]
https://git.friendi.ca/ is down.

**Comment by MrPetovan** [comment]
@ben-utzer ?

**Comment by ben-utzer** [comment]
> @ben-utzer ?

I need some help of @nupplaphil to get the docker thing running, I wasn't aware it wouldn't start automatically after a reboot.

**Comment by MrPetovan** [comment]
The tests are independent from drone.friendi.ca for now, but Travis needs access to git.friendi.ca.

**Pull request merged**
