### PR TITLE
Added usort() to the saved folders widget

### LINKED ISSUE #5048: Sort saved folders alphabetically
Could you please sort the saved folders alphabetically, so that the left side widget (frio)  and the select dialog them shows  alphabetically,  when you save an article in your folders.

### PR DESCRIPTION
**Pull request by AlfredSK**
I'm pretty sure this PR is very amateurish. :-) That's because I am a bloody amateur. But I checked it locally on my node and surprisingly it does work.

Please give me some advice if I need to do better.

Fixes #5048

### CODE REVIEW

**Comment by MrPetovan** [comment]
Did you test it on your server?

The problem I see is that `asort90` works on one-dimensional associative arrays, for example:
```php
$assoc = [
  'a' => 2,
  'b' => 3,
  'c' => 1,
],

asort($assoc);

// array(3) {
//  ["c"]=> int(1)
//  ["a"]=> int(2)
//  ["b"]=> int(3)
//}
```
But here we have a list of associative arrays like this:
```php
$list = [
  ['ref' => 1, 'name' => 'c'],
  ['ref' => 2, 'name' => 'a'],
  ['ref' => 3, 'name' => 'b'],
];
```
That `asort()` won't be able to sort because it doesn't know how to compare associative arrays between themselves.

You actually need `usort()` in this case with a callback that explicitely sorts on the relevant key.

Like this:
```
$list = [
  ['ref' => 1, 'name' => 'c'],
  ['ref' => 2, 'name' => 'a'],
  ['ref' => 3, 'name' => 'b'],
];

usort($list, function ($a, $b) {
    return strcmp($a['name'], $b['name']);
});

// array(3) {
//   [0]=> array(2) {
//     ["ref"]=> int(2)
//     ["name"]=> string(1) "a"
//   }
//   [1]=> array(2) {
//     ["ref"]=> int(3)
//     ["name"]=> string(1) "b"
//   }
//   [2]=> array(2) {
//     ["ref"]=> int(1)
//     ["name"]=> string(1) "c"
//   }
// }
```
The keys of the base array aren't relevant, only the association between the `ref` and the `name` in the list elements, which this function keeps.

**Comment by AlfredSK** [comment]
> Did you test it on your server?

Yes. It seems to work. The list of saved folders is sorted alphabetically now.

For the other part of your comment about the usort() function I need to learn more about the topic first.

**Comment by MrPetovan** [comment]
I can confirm this works, but probably not for good reasons. I believe the reason it works is that the naive comparison `asort()` performs works because both the `name` and `ref` keys of the underlying elements both have the same value, which may break in the future when we use different values for both keys.

**Comment by AlfredSK** [comment]
I have a question...

```
usort($list, function ($a, $b) {
    return strcmp($a['name'], $b['name']);
});
```

Is the word 'function' actually allowed/wanted at this place or do I need to create my own name there?

I literally replaced the asort line with the following code and it seems to work:

```
usort($terms, function ($a, $b) {
    return strcmp($a['name'], $b['name']);
});
```

Is this what you were trying to tell me? Is this ok?

It seems to work. :-) Jeez. I'm feeling like a blind man driving a car on the highway with 200 km/h. :-)

**Comment by MrPetovan** [comment]
> Is the word 'function' actually allowed/wanted at this place or do I need to create my own name there?

Yes, Introduced in PHP 5.3, closures are anonymous functions that don't need a name and can be passed as a parameter for functions requiring a callback, like `usort()`.

The replacement you did is correct and future-proof. 🙂

**Comment by AlfredSK** [comment]
Thank you! I will push the commit then...

**Comment by MrPetovan** [comment]
Thank you for your work!

**Comment by AlfredSK** [comment]
You're welcome!

**Pull request merged**
