### PR TITLE
CHANGELOG for 2024.08

### PR DESCRIPTION
**Pull request by tobiasd**
Last PR to be merged into the 2024.06-rc branch

### CODE REVIEW

**Comment by ne20002** [comment]
@tobiasd 
line 371, typo, double t

**Comment by ne20002** [comment]
@tobiasd 
I'm prepared to do the docker image tomorrow.

**Comment by tobiasd** [comment]
Does docker work without the archive files? As I understand the [update script](https://github.com/friendica/docker/blob/stable/update.sh#L114) the docker build process involves downloading the archives, which are currently not build.

**Comment by ne20002** [comment]
It does involve some preparation but yes, I have to wait for the archives.

**Pull request merged**
