### PR TITLE
A "Create New Forum" Button on the button widget 

### PR DESCRIPTION
**Pull request by anubis2814**
https://friendica.myportal.social/photos/anubis2814/image/3337502781647bf95ddc57b157281809

It goes directly to register/.

### CODE REVIEW

**Comment by MrPetovan** [comment]
It looks like you force pushed your branch into oblivion by resetting it to the current Friendica develop.

**Comment by anubis2814** [comment]
Yes, I didn't update my fork before trying to commit and that was the worst time to do it because of the massive change you guys did so I had to purge everything and reset everything, and then change the new files to match the old ones I had.

**Comment by MrPetovan** [comment]
Yeah, sorry about that, we're moving fast and breaking things.

**Comment by anubis2814** [comment]
Lol its all good, its really cool this is happening, it will teach me to make sure everything is up to date before I make any commits. Live and learn

**Pull request closed without merging**
