### PR TITLE
Installation better start with master and eventially switch to develop

### PR DESCRIPTION
**Pull request by tobiasd**
Some comments mentioned it would be nicer to start with the stable version of Friendica. The INSTALL docs got updated accordingly.

### CODE REVIEW

**Comment by miqrogroove** [comment]
Why do you have one branch as "clone" and the other as "checkout"?

**Comment by miqrogroove** [comment]
I think it would be helpful to briefly explain git commands such as "git pull" on the dev branch.  Also, when exactly is it necessary to run composer.phar?  The instructions imply that it needs to be run once when installing the master branch, and once more when switching to the dev branch?

**Comment by MrPetovan** [comment]
> Why do you have one branch as "clone" and the other as "checkout"?

```
git clone https://github.com/friendica/friendica -b master [folder]
```
is equivalent to 
```
git clone https://github.com/friendica/friendica [folder]
git checkout master
```
> Also, when exactly is it necessary to run `bin/composer.phar install`?

Anytime the `composer.lock` has been modified. This can happen when switching branch (`git checkout`) but also when pulling new changes (`git pull`)

**Comment by tobiasd** [comment]
> Why do you have one branch as "clone" and the other as "checkout"?

I'm assuming the general audience sticks to the text and copy and pastes commands. Then you clone Friendica master in the initial step and arrive at the point of _Oh there is a development version as well that I might use_ and then you need only to checkout develop.

You can [automate the composer](https://github.com/friendica/friendica/blob/develop/doc/Developers-Intro.md#composer) decision process with a git-hook.

**Pull request merged**
