### PR TITLE
Replace deprecated Logger calls

### PR DESCRIPTION
**Pull request by annando**
Some fewer deprecation messages.

### CODE REVIEW

**Comment by annando** [comment]
I guess replacing all deprecated stuff will be a little bit too much for this PR.

**Comment by MrPetovan** [comment]
How many lines total?

**Comment by annando** [comment]
It would be more than 400 hundred places.

**Comment by MrPetovan** [comment]
Please split them in four separate PRs of close size.

**Comment by annando** [comment]
I'm not planning it for this release.

**Comment by MrPetovan** [comment]
Can you still change the `error` logger call in `CurlResult`? It fills the log with useless info when the `error` level is selected.

**Comment by MrPetovan** [comment]
Are you done with this PR?

**Comment by annando** [comment]
I guess that it is ready to be merged.

**Pull request merged**
