### PR TITLE
boot.php - code cleanup + doxygen

### PR DESCRIPTION
**Pull request by rabuzarus**
I removed unneeded `if(! function_exists` and added some  doxygen docu to boot php

Most of the doxygen is taken from red

### CODE REVIEW

**Comment by fabrixxm** [comment]
There is a small not really needed `/` on line 1410

**Comment by rabuzarus** [comment]
@fabrixxm 
big thanks. It's no easy to see such small thinks.
I hate it to touch such big pieces of codes because it mostly means that there will be some mistakes in it. Even if it seems to be only much docu stuff it's important to have a good review.

Thank you and I wish a wonderful Christmas eve to all of you

**Comment by rabuzarus** [comment]
Have done the same for identity.php

Note: Some functions in identiy.php are still undocumented. Feel free to add the missing docu

**Comment by rabuzarus** [comment]
the last commit groups constants. If anyone knows how to get the inline comments of the Network and protocol family types into doxygen, please let me know

**Pull request merged**
