### PR TITLE
Improved help text, issue 1349.

### PR DESCRIPTION
**Pull request by silke**
Added more information to help text for approving contacts.

### CODE REVIEW

**Comment by annando** [comment]
I do not really understand "To start sharing with a Diaspora contact, choose "Fan"". This sounds to me like: "If there is a connection request from Diaspora, always choose 'Fan'". I find this confusing.

**Comment by fabrixxm** [comment]
I would create two separate strings for Friendica and Diaspora contacts

(anyway, if is "always choose 'Fan'" for Diaspora, why we show the option?)

**Comment by annando** [comment]
I think that the text is misleading. The option is important since it decides whether you just allow others to read you - or if you want to read their stuff as well. This behaviour doesn't differ between Friendica and Diaspora.

**Comment by fabrixxm** [comment]
So, what about something like
https://github.com/friendica/friendica/pull/1474 ?

**Pull request merged**
