### PR TITLE
Automatic Install Tests & Doku

### PR DESCRIPTION
**Pull request by nupplaphil**
- New dev-library "mikey179/vfsStream"
- created "reload" method for App-Reloads
- ConsoleTest now using virtual directory
- Adding Automatic Installation Tests
- Fixing some probable install-failures
- Adding Readme for Auto-Install

Follow Up #5565

### CODE REVIEW

**Comment by MrPetovan** [comment]
Are you running this on your server?

**Comment by nupplaphil** [comment]
What do you mean? I checked the installation at local instances (like #5565), but I changed - except of the `App::reload()` - nothing during then "normal" Friendica usage with this PR.

But I can change my node to this PR and check it nevertheless if you want :-)

I'm currently on the way to update the docker instances to use the new auto install methods.

**Comment by nupplaphil** [comment]
My friendica node is now running with this PR branch :-)

**Comment by MrPetovan** [comment]
I was asking because you touched the App constructor, and it is used in every single request, install or not. Thanks for complying!

**Pull request merged**
