### PR TITLE
Improved logging for local probing, avoid worker fork

### PR DESCRIPTION
**Pull request by annando**
See the discussion here: https://forum.friendi.ca/display/0b6b25a8-2760-b1fd-2960-924040875447

Local requests are avoided - but this doesn't seem to work for every case.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by AlfredSK** [comment]
The self-DoS-sing just happened again. And again the more than 2000 requests were related to a new local user account.

Here is the part of the Apache access log of venera.social's virtual host. The two IPs (IPv4 and IPv6) are the IPs of the local server.
I don't want to throw the log in here. So I created a share for it: https://oc.libranet.de/s/bZNBiKP6xYTEdDw

I grep-ed for the log entries you created here with this PR in my Friendica log. But nothing has been logged. (grep -Ei 'Fetch the followers|Contact seems to be local' log/venera.log).

Could it be that we simply don't detect that this is a local user (the isLocal doesn't work)?

**Comment by annando** [comment]
Does some `cat friendica.log | grep -a venera.social.*Relation.php.*discoverByUrl`return anything?

**Comment by AlfredSK** [comment]
Do you mean `grep -a 'venera.social.*Relation.php.*discoverByUrl' friendica.log`? ;-)

Wait a minute...

**Comment by AlfredSK** [comment]
No. Nothing.

**Comment by annando** [comment]
Do you have the `info` log level?

**Comment by AlfredSK** [comment]
Yes. But I switched to 'info' after this PR. Before this I was on 'warning'.

**Comment by AlfredSK** [comment]
I don't have a single line with 'discoverByUrl' in the log.

**Comment by annando** [comment]
Does worker activities are logged at all?

**Comment by AlfredSK** [comment]
Btw. my setting for 'Discover followers/followings from contacts' was 'Local contacts'. At the moment I have set it to 'None' because of the issue.

**Comment by AlfredSK** [comment]
> Does worker activities are logged at all?

Yes.

```
2021-05-29T14:57:04Z worker [INFO]: Process done. {"priority":50,"id":48744290,"duration":1.364} - {"file":"Worker.php","line":502,"function":"execFunction","uid":"5e02e8","process_id":2700196}
2021-05-29T14:57:04Z worker [INFO]: ID 48744290: Delivery {"action":"profiling","database_read":0,"database_write":0,"cache_read":0,"cache_write":0,"network_io":0,"file_io":0,"other_io":1.36,"total":1.36} - {"file":"Worker.php","line":504,"function":"execFunction","uid":"5e02e8","process_id":2700196}
2021-05-29T14:57:04Z worker [INFO]: Connection usage (system values) {"used":10,"max":320} - {"file":"Worker.php","line":584,"function":"maxConnectionsReached","uid":"5e02e8","process_id":2700196}
2021-05-29T14:57:04Z worker [INFO]: Process start. {"priority":50,"id":48758600,"worker_id":"81cecb6","worker_cmd":"Delivery"} - {"file":"Worker.php","line":436,"function":"execFunction","uid":"5e02e8","process_id":2700196}
2021-05-29T14:57:04Z worker [INFO]: Invoked {"cmd":"drop","target":6019565,"sender_uid":681,"contact":212450,"worker_id":"81cecb6","worker_cmd":"Delivery"} - {"file":"Delivery.php","line":54,"function":"execute","uid":"5e02e8","process_id":2700196}
```

**Comment by annando** [comment]
What happens when you only search for `ContactDiscovery`?

**Comment by AlfredSK** [comment]
This...

```
2021-05-29T13:59:02Z worker [INFO]: Process runtime is okay {"duration":"0.233","max":180,"id":49115187,"pid":2589759,"command":"ContactDiscovery"} - {"file":"Worker.php","line":670,"function":"killStaleWorkers","uid":"b73d24","process_id":2590781}
2021-05-29T14:01:04Z worker [INFO]: Process runtime is okay {"duration":"1.083","max":180,"id":49115187,"pid":2589759,"command":"ContactDiscovery"} - {"file":"Worker.php","line":670,"function":"killStaleWorkers","uid":"43481f","process_id":2595887}
2021-05-29T14:01:12Z worker [INFO]: Process start. {"priority":40,"id":49115187,"worker_id":"5213968","worker_cmd":"ContactDiscovery"} - {"file":"Worker.php","line":436,"function":"execFunction","uid":"e8a7d7","process_id":2595959}
2021-05-29T14:01:12Z worker [INFO]: ID 49115187: ContactDiscovery {"action":"profiling","database_read":0,"database_write":0,"cache_read":0,"cache_write":0,"network_io":0,"file_io":0,"other_io":0,"total":0} - {"file":"Worker.php","line":504,"function":"execFunction","uid":"e8a7d7","process_id":2595959}
```

That's all from today's log. The issue happend at 13:55 UTC.

**Comment by annando** [comment]
Okay, so here will be some more logging: https://github.com/friendica/friendica/pull/10333

**Comment by AlfredSK** [comment]
I just had it again. Unfortunately, before I could pull the new PR. This time it happened on libranet.de.

**Clearly, this happens when a new account has been created on the node.** 

The last two times on venera.social all requests were related to the new user accounts. This time on libranet.de it was also related to a new user account that just had been created and approved by me. 

Important! I had disabled the discovery of followers/follows when it happend this time. And there were hundreds of local to local requests to the followers/follows collection of the new user account (plus webfinger and outbox).

**It really seems that this happens every time a new user is creating an account.** To be more precise: it doesn't happen when the user registers the account, it doesn't happen when I approve the registration. It probably happens when the new user logs in for the first time. I just got a new registration and approved it. Waiting for the first login of the new user....

**Comment by AlfredSK** [comment]
That user never logs in. :-) Damn. But I have a new registration request...

**Comment by AlfredSK** [comment]
So. The user logged in for the first time and bamm! node has dossed itself.

WARNING: [pool www] server reached pm.max_children setting (300), consider raising it

That's what I see...
## 864 times in 3 minutes

```
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
....
....
~860 more lines of this
....
```

The process IDs and UIDs are changing at the end - for the last 10-12 lines. All other lines (~850) are mostly identical.

Do you need something more?

**Comment by AlfredSK** [comment]
After those lines above tons of this happens...

```
2021-05-30T09:23:41Z index [INFO]: Redirecting with magic {"target":"https:\/\/f.freinetz.ch\/profile\/yyyyyyy?zrl=https%3A%2F%2Fvenera.social%2Fprofile%2Fxxxx&addr=https%3A%2F%2Ff.freinetz.ch%2Fprofile%2Fyyyyyyy","visitor":"https:\/\/venera.social\/profile\/xxxx","contact":"https:\/\/f.freinetz.ch\/profile\/yyyyyyyy"} - {"file":"redir.php","line":178,"function":"redir_magic","uid":"050e4b","process_id":1043701}
2021-05-30T09:23:42Z index [INFO]: Fetched for user 0 from https://venera.social/profile/xxxx returned 200 [] - {"file":"HTTPSignature.php","line":459,"function":"fetchRaw","uid":"fb2a8d","process_id":670878}
2021-05-30T09:23:43Z index [INFO]: Fetched for user 0 from https://venera.social/following/xxxx returned 200 [] - {"file":"HTTPSignature.php","line":459,"function":"fetchRaw","uid":"fb2a8d","process_id":670878}
2021-05-30T09:23:43Z index [INFO]: Fetched for user 0 from https://venera.social/followers/xxxx returned 200 [] - {"file":"HTTPSignature.php","line":459,"function":"fetchRaw","uid":"fb2a8d","process_id":670878}
2021-05-30T09:23:43Z index [INFO]: Fetched for user 0 from https://venera.social/profile/xxxx returned 200 [] - {"file":"HTTPSignature.php","line":459,"function":"fetchRaw","uid":"2d0d21","process_id":670899}
2021-05-30T09:23:43Z index [NOTICE]: Multiple requests for the address {"url":"https:\/\/venera.social\/profile\/xxxx","update":true,"callstack":"ActivityPub::probeProfile, Probe::uri, Contact::getIdForURL, Transmitter::getOutbox, Outbox::rawContent, call_user_func, Module::run, App::runFrontend","result":"ActivityPub::probeProfile, Probe::uri, Contact::getIdForURL, Transmitter::getOutbox, Outbox::rawContent, call_user_func, Module::run, App::runFrontend"} - {"file":"APContact.php","line":179,"function":"getByURL","uid":"2d0d21","process_id":670899}
2021-05-30T09:23:43Z index [INFO]: Fetched for user 0 from https://venera.social/following/xxxx returned 200 [] - {"file":"HTTPSignature.php","line":459,"function":"fetchRaw","uid":"2d0d21","process_id":670899}
2021-05-30T09:23:43Z index [INFO]: Fetched for user 0 from https://venera.social/followers/xxxx returned 200 [] - {"file":"HTTPSignature.php","line":459,"function":"fetchRaw","uid":"2d0d21","process_id":670899}
2021-05-30T09:23:43Z index [INFO]: Fetched for user 0 from https://venera.social/profile/xxxx returned 200 [] - {"file":"HTTPSignature.php","line":459,"function":"fetchRaw","uid":"408330","process_id":670880}
2021-05-30T09:23:43Z index [NOTICE]: Multiple requests for the address {"url":"https:\/\/venera.social\/profile\/xxxx","update":true,"callstack":"ActivityPub::probeProfile, Probe::uri, Contact::getIdForURL, Transmitter::getOutbox, Outbox::rawContent, call_user_func, Module::run, App::runFrontend","result":"ActivityPub::probeProfile, Probe::uri, Contact::getIdForURL, Transmitter::getOutbox, Outbox::rawContent, call_user_func, Module::run, App::runFrontend"} - {"file":"APContact.php","line":179,"function":"getByURL","uid":"408330","process_id":670880}
2021-05-30T09:23:43Z index [INFO]: Fetched for user 0 from https://venera.social/following/xxxx returned 200 [] - {"file":"HTTPSignature.php","line":459,"function":"fetchRaw","uid":"408330","process_id":670880}
2021-05-30T09:23:43Z index [INFO]: Fetched for user 0 from https://venera.social/followers/xxxx returned 200 [] - {"file":"HTTPSignature.php","line":459,"function":"fetchRaw","uid":"408330","process_id":670880}
2021-05-30T09:23:43Z index [INFO]: Fetched for user 0 from https://venera.social/profile/xxxx returned 200 [] - {"file":"HTTPSignature.php","line":459,"function":"fetchRaw","uid":"261c88","process_id":617694}
2021-05-30T09:23:43Z index [NOTICE]: Multiple requests for the address {"url":"https:\/\/venera.social\/profile\/xxxx","update":true,"callstack":"ActivityPub::probeProfile, Probe::uri, Contact::getIdForURL, Transmitter::getOutbox, Outbox::rawContent, call_user_func, Module::run, App::runFrontend","result":"ActivityPub::probeProfile, Probe::uri, Contact::getIdForURL, Transmitter::getOutbox, Outbox::rawContent, call_user_func, Module::run, App::runFrontend"} - {"file":"APContact.php","line":179,"function":"getByURL","uid":"261c88","process_id":617694}
2021-05-30T09:23:43Z index [INFO]: Fetched for user 0 from https://venera.social/following/xxxx returned 200 [] - {"file":"HTTPSignature.php","line":459,"function":"fetchRaw","uid":"261c88","process_id":617694}
2021-05-30T09:23:43Z index [INFO]: Fetched for user 0 from https://venera.social/followers/xxxx returned 200 [] - {"file":"HTTPSignature.php","line":459,"function":"fetchRaw","uid":"261c88","process_id":617694}
2021-05-30T09:23:43Z index [INFO]: Fetched for user 0 from https://venera.social/profile/xxxx returned 200 [] - {"file":"HTTPSignature.php","line":459,"function":"fetchRaw","uid":"e80ac7","process_id":609093}
2021-05-30T09:23:43Z index [NOTICE]: Multiple requests for the address {"url":"https:\/\/venera.social\/profile\/xxxx","update":true,"callstack":"ActivityPub::probeProfile, Probe::uri, Contact::getIdForURL, Transmitter::getOutbox, Outbox::rawContent, call_user_func, Module::run, App::runFrontend","result":"ActivityPub::probeProfile, Probe::uri, Contact::getIdForURL, Transmitter::getOutbox, Outbox::rawContent, call_user_func, Module::run, App::runFrontend"} - {"file":"APContact.php","line":179,"function":"getByURL","uid":"e80ac7","process_id":609093}
.....
.....
```

**Comment by AlfredSK** [comment]
And after this the following happens a lot! Like hundreds of those lines - all in the same second!

```
2021-05-30T09:24:41Z index [INFO]: Contact will be updated {"url":"https:\/\/venera.social\/profile\/xxxx","uid":0,"update":null,"cid":585945} - {"file":"Contact.php","line":1167,"function":"getIdForURL","uid":"e18a71","process_id":1132092}
2021-05-30T09:24:41Z index [NOTICE]: http error {"url":"https:\/\/venera.social\/noscrape\/xxxx","code":404,"error":"","callstack":"CurlResult::__construct, HTTPRequest::get, Probe::pollNoscrape, Probe::dfrn, Probe::detect, Probe::uri, Contact::getIdForURL, Transmitter::getOutbox, Outbox::rawContent, call_user_func, Module::run, App::runFrontend"} - {"file":"CurlResult.php","line":170,"function":"checkSuccess","uid":"5b997a","process_id":1132246}
2021-05-30T09:24:41Z index [INFO]: No json data {"url":"https:\/\/venera.social\/noscrape\/xxxx"} - {"file":"Probe.php","line":1029,"function":"pollNoscrape","uid":"5b997a","process_id":1132246}
2021-05-30T09:24:41Z index [INFO]: Updated profile {"url":"https:\/\/venera.social\/profile\/xxxx"} - {"file":"APContact.php","line":362,"function":"getByURL","uid":"5ff1d0","process_id":1132235}
2021-05-30T09:24:41Z index [INFO]: Probing start {"uri":"https:\/\/venera.social\/profile\/xxxx"} - {"file":"Probe.php","line":718,"function":"detect","uid":"5ff1d0","process_id":1132235}
2021-05-30T09:24:41Z index [NOTICE]: http error {"url":"https:\/\/venera.social\/outbox\/xxxx","code":0,"error":"Operation timed out after 42001 milliseconds with 0 bytes received","callstack":"CurlResult::__construct, HTTPRequest::get, HTTPSignature::fetchRaw, HTTPSignature::fetch, ActivityPub::fetchContent, APContact::getByURL, ActivityPub::probeProfile, Probe::uri, Contact::getIdForURL, Transmitter::getOutbox, Outbox::rawContent, call_user_func, Module::run, App::runFrontend"} - {"file":"CurlResult.php","line":170,"function":"checkSuccess","uid":"958bb8","process_id":1132238}
2021-05-30T09:24:41Z index [INFO]: Fetched for user 0 from https://venera.social/outbox/xxxx returned 0 [] - {"file":"HTTPSignature.php","line":459,"function":"fetchRaw","uid":"958bb8","process_id":1132238}
2021-05-30T09:24:41Z index [INFO]: Probing done {"uri":"https:\/\/venera.social\/profile\xxxx","network":"unkn"} - {"file":"Probe.php","line":788,"function":"detect","uid":"5b997a","process_id":1132246}
2021-05-30T09:24:41Z index [NOTICE]: no data for session {"session_id":"l22aqafh63i0rpja76qt1a38n8","uri":"\/profile\/xxxx"} - {"file":"Cache.php","line":65,"function":"read","uid":"30bcef","process_id":1135798}
2021-05-30T09:24:41Z index [INFO]: Updated profile {"url":"https:\/\/venera.social\/profile\/xxxx"} - {"file":"APContact.php","line":362,"function":"getByURL","uid":"958bb8","process_id":1132238}
2021-05-30T09:24:41Z index [INFO]: Probing start {"uri":"https:\/\/venera.social\/profile\/xxxx"} - {"file":"Probe.php","line":718,"function":"detect","uid":"958bb8","process_id":1132238}
2021-05-30T09:24:41Z index [NOTICE]: http error {"url":"https:\/\/venera.social\/noscrape\/xxxx","code":404,"error":"","callstack":"CurlResult::__construct, HTTPRequest::get, Probe::pollNoscrape, Probe::dfrn, Probe::detect, Probe::uri, Contact::getIdForURL, Transmitter::getOutbox, Outbox::rawContent, call_user_func, Module::run, App::runFrontend"} - {"file":"CurlResult.php","line":170,"function":"checkSuccess","uid":"5ff1d0","process_id":1132235}
2021-05-30T09:24:41Z index [INFO]: Fetched id by url {"cid":585945,"uid":0,"url":"https:\/\/venera.social\/profile\/xxxx","data":{"name":"xxxxx xxxxx","nick":"xxxx","guid":"85a863ed-1260-b340-df32-f08638211989","url":"https:\/\/venera.social\/profile\/xxxxx","addr":"xxxx@venera.social","alias":"","photo":"https:\/\/venera.social\/photo\/204322657560b340df5c341691060705-4.jpg?ts=1622360287","account-type":0,"community":false,"keywords":"","location":"","about":"","hide":1,"batch":"https:\/\/venera.social\/inbox","notify":"https:\/\/venera.social\/inbox\/xxxx","poll":"https:\/\/venera.social\/outbox\/xxxx","request":"","confirm":"","subscribe":"https:\/\/venera.social\/follow?url={uri}","poco":"","following":"https:\/\/venera.social\/following\/xxxx","followers":"https:\/\/venera.social\/followers\/xxxx","inbox":"https:\/\/venera.social\/inbox\/xxxx","outbox":"https:\/\/venera.social\/outbox\/xxxx","sharedinbox":"https:\/\/venera.social\/inbox","priority":0,"network":"dfrn","pubkey":"-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAuOjXPY8OYkE2E+52+GYC\n\/to3Ghjxx8GrJ+mA4kdfXgyNFZarR7OZr1s+qJxc3pNgx6D99Wmib77yHJwKUs3r\nFND6HkPMpLCGwokvS9DVOk1nB81RqdHjpYVmaoS1Uj5PWPTYKnFCsZ+9GxREBV2q\n73U7Hgeb05b3RF+GH4xYfRQ1h4KJ9MHnyDAOGBclfVr\/wxGDaTmHKfvcBpzuBNaZ\nKi+y7AG0De0jDEiRb36SeaZzjW0VWwiKLdpIT\/tm93s6yRF7FZ7I6JsT2RcYfHbu\nCnvspQVkbPVHS1+T3yy54JNNOPG49WH2i1ojAi5n9ZF7dj1gitiRy2WMfeKmkP0z\n5+XH2lVAHDo68qLt8Z8MBySXi+DlUrkY7Ifmw50Aw7zG7UNXVkvTpZGAy5wcdpSf\nrziT13QyXDVvrN8Un6H6R\/04YcRnYFCwqP7FtjoaFBd7sIjw7+9MUbOU7GxxxC+U\nIdI6n\/6UaEeNkROucGMA1kUx9wYT3Wf1h5WKfShuNIKy8hMu\/1gZUIVs77vuBD8r\nzfbjPZVaiZVMzIP3IAa+hwItk+yfjHJ04p\/u9\/2GxDvDFi0U0V5VVDfm7ogfiPgd\nh2mdgCYrNb+PI4Tx3mvliGLanbeF2hb9U9AD4RUxAubWFlRbYL9RWGsl2AVhQdLf\n5SDNzFgnpCPoOE7Lx28Uts0CAwEAAQ==\n-----END PUBLIC KEY-----","manually-approve":1,"baseurl":"https:\/\/venera.social","gsid":16}} - {"file":"Contact.php","line":1124,"function":"getIdForURL","uid":"5b997a","process_id":1132246}
....
....
....
```

**Comment by AlfredSK** [comment]
All in all there are more than 4800 lines created in the Friendica log right after the user logged in for the first time. And all of those 4800 lines are related to the new user.

**Comment by annando** [comment]
Can you have a look at the log for all entries with the `uid` value `e2b2d6` in it? I need to know what exactly is happening right before the first `Contact not found, update not desired `.

**Comment by AlfredSK** [comment]
This.

```
2021-05-30T09:18:49Z index [INFO]: No HTTP_SIGNATURE header [] - {"file":"HTTPSignature.php","line":476,"function":"getSigner","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
2021-05-30T09:18:49Z index [INFO]: Contact not found, update not desired {"url":"xxxx@venera.social","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"e2b2d6","process_id":616785}
....
....
```

**Comment by AlfredSK** [comment]
Hmm. I saw the other PR and I was thinking why this happens to me ;-) but not on your node(s).

I am using registration policy 'by approval'. Is the new account blocked somehow until I approve it? This could be an explanation why something is missing later when the user logs in for the first time. It's just a guess but I have no other idea.

Edit: I'll switch to 'open' and register a test account. I'll see what happens...

**Comment by AlfredSK** [comment]
Ok. That's it! With registration policy 'OPEN' nothing bad happens. The user registers the account and logs in. Everything is good! No huge amounts of requests, no errors, no PHP pool issues, no timeouts. Nothing. Everything smooth and perfect.

**Comment by annando** [comment]
Looks like some more stuff to fix ... gnarf ...

**Comment by AlfredSK** [comment]
I have to correct myself in one respect. There are the same log lines with "Contact not found..." and the line with "No HTTP_SIGNATURE header". 
But it is correct that the self-DOS-ing didn't happen, the Apache access log doesn't show those huge amounts of local to local requests and the Friendica log doesn't have the many requests to the profile, outbox and so on of the new user.

```
2021-05-30T13:19:39Z index [INFO]: No HTTP_SIGNATURE header [] - {"file":"HTTPSignature.php","line":476,"function":"getSigner","uid":"80ad36","process_id":1451138}
2021-05-30T13:19:39Z index [INFO]: Contact not found, update not desired {"url":"antonaaa123@libranet.de","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"80ad36","process_id":1451138}
2021-05-30T13:19:39Z index [INFO]: Contact not found, update not desired {"url":"antonaaa123@libranet.de","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"80ad36","process_id":1451138}
2021-05-30T13:19:39Z index [INFO]: Contact not found, update not desired {"url":"antonaaa123@libranet.de","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"80ad36","process_id":1451138}
2021-05-30T13:19:39Z index [INFO]: Contact not found, update not desired {"url":"antonaaa123@libranet.de","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"80ad36","process_id":1451138}
2021-05-30T13:19:39Z index [INFO]: Contact not found, update not desired {"url":"antonaaa123@libranet.de","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"80ad36","process_id":1451138}
2021-05-30T13:19:39Z index [INFO]: Contact not found, update not desired {"url":"antonaaa123@libranet.de","uid":0,"update":false} - {"file":"Contact.php","line":1070,"function":"getIdForURL","uid":"80ad36","process_id":1451138}
....
....
```

**Comment by annando** [comment]
So my changes helped a bit?

**Comment by AlfredSK** [comment]
My last comment was made before I pulled your latest changes. It just reflects what happens with policy 'OPEN'.

I didn't switch back to 'BY APPROVAL' yet. Will do it soon. But first some ice cream 🍨.

Update: ice cream done and registration policy switch done.

**Comment by AlfredSK** [comment]
New test user. Registered, approved, logged in. Watched the logs. Everything is ok. :-)

**Pull request merged**
