### PR TITLE
Fix broken credits box

### PR DESCRIPTION
**Pull request by vinzv**
Otherwise the content is exceeding the box, both on desktop and mobile.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Can you please add links or screenshots showing the issue and your solution?

**Comment by vinzv** [comment]
Sure thing! Sorry, should've made the description more detailed.
It's regarding the credits page, e.g https://less.re/credits, https://squeet.me/credits or https://squeet.me/credits
You can try for yourself to see the fix adding this class in e.g. Firefox Webdev Inspector:

`.credits-content-wrapper {
    overflow: hidden;
}`

Before:
screenshot_20181019_103051

After:
screenshot_20181019_103139
screenshot_20181019_103155

**Comment by annando** [comment]
Could you check, whether this also happens on other themes?

**Comment by rabuzarus** [comment]
I would prefer another solution.
Take https://github.com/friendica/friendica/blob/develop/view/templates/credits.tpl and copy it to `view/theme/frio/templates` with following content:
```
<div id="credits" class="generic-page-wrapper">
        {{include file="section_title.tpl"}}
        <p>{{$thanks}}</p>

        <ul class="credits">
                {{foreach $names as $name}}
                 <li>{{$name}}</li>
                {{/foreach}}
        </ul>
        <div class="clear"></div>
</div>
```

and remove `.credits-content-wrapper,` from https://github.com/friendica/friendica/blob/develop/view/theme/frio/css/style.css#L2187

**Comment by vinzv** [comment]
> Could you check, whether this also happens on other themes?

@annando I checked at https://snarl.de/credits where the problem doesn't occur as there is no such bordered box around the content.

**Comment by vinzv** [comment]
@AlfredSK Can't confirm. When I look at my /credits page logged in the visual error exists as well.

**Comment by vinzv** [comment]
@rabuzarus My solution was just the first quick shot at getting the issue fixed. So I'm totally fine with any other, maybe more decent solution. Could you eventually explain how and why your's is better?

**Comment by AlfredSK** [comment]
@vinzv Weird. :-) Here's a screenshot...

bildschirmfoto von 2018-10-21 14-47-23

**Comment by AlfredSK** [comment]
Maybe the 'rendertime' line fixes the issue. It is only displayed if I'm logged in.

**Comment by vinzv** [comment]
@AlfredSK Yep, rendertime adds a div which obviously pulls down the <section> element down to enclose the whole page content.

**Comment by MrPetovan** [comment]
> @rabuzarus My solution was just the first quick shot at getting the issue fixed. So I'm totally fine with any other, maybe more decent solution. Could you eventually explain how and why your's is better?

The mentioned `.generic-page-wrapper` class already does what you added and an additional class is then superfluous.

**Comment by vinzv** [comment]
Alright, sounds more sane to me as well.

**Comment by MrPetovan** [comment]
Thank you for your work!

**Pull request merged**
