### PR TITLE
[frio] Add local post link to share block when guid attribute is present

### LINKED ISSUE #8785: Links to reshared posts not there anymore
### Expected behavior
The date/time of the reshared post should be linked to the local copy of the reshared post, as it was before, until some days ago. 

### Actual behavior
No link whatsoever, so it is not possible to find the original post anymore. 

### Steps to reproduce the problem
Look for some reshared post in your timeline, i.e. this one [here](https://social.yl.ms/display/f897a1e09286013889d5005056264835). 

### Friendica version you encountered the problem
06.2020-RC

### Friendica source (git, zip)
git

### PHP version
PHP 7.4.6 

### SQL version
same as before.

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #8785
Add-on counterpart: https://github.com/friendica/friendica-addons/pull/990

### CODE REVIEW

**Comment by annando** [comment]
@MrPetovan do you have a look at the failed test?

**Comment by MrPetovan** [comment]
Nope, good catch.

**Comment by annando** [comment]
Yeah, I'm just back from a short vacation (as you could see from my posts) and I'm working through the issues.

**Comment by MrPetovan** [comment]
All good.

**Pull request merged**
