### PR TITLE
Remove contact drop feature

### LINKED ISSUE #10729: Trouble when trying to drop contact
### Bug Description

Error messages, faulty UI and action never proceeding when trying to drop contact.

### Steps to Reproduce

1.  Open contacts list
2.  Tick checkbox in bottom right of contact in the list
3.  Click `Drop Contact` icon

Actual Result:

Error message shows multiple times: "The form security token was not correct. This probably happened because the form has been opened for too long (>3 hours) before submitting it."

Friendica UI shows second friendica overlay over existing UI.

Expected Result:

Contact should be dropped.

### Screenshots
error
double UI

### Platform Info

Friendica Version:

This is Friendica, version 2021.09-rc that is running at the web location https://pirati.ca. The database version is 1435/1435, the post update version is 1427/1427.

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #10729 

Additionally, this PR adds contact relationship termination to block action to be more consistent with other social media platforms.

### CODE REVIEW

**Comment by annando** [comment]
I would like to have it solved differently. We can't look at other systems here since they don't support that feature. So we should have it this way:

- We are only following the contact but the contact doesn't follow us => "Unfollow" button (and it will remove the contact when activated)
- The contact is following us but we don't follow => Button to revoke the subscription (it will also remove the contact as well)
- We have got a bidirectional connection => Both buttons are separately available

**Comment by MrPetovan** [comment]
I've never seen any "Revoke follow" in any other system (except "Stop sharing with" in Diaspora but their model is different) so we would be trail blazers in that regard. That said, it isn't incompatible with this PR. Besides, I'm not sure all networks support "Revoke Follow" anyway, so even "Drop Contact" wasn't reliable in that regard. Please advise on the network compatibility.

I'll open a new separate issue for this.

Additionally, I don't think we should drop a contact when we just unfollow either way. Maybe we left a personal note on the contact we want or expect to keep.

**Comment by annando** [comment]
In ActivityPub this method is supported. In the Diaspora protocol this would be possibly supported - but the Diaspora software doesn't support this at the moment.

But: Besides these networks we do have feeds and mail contacts. I'm not sure if it is even supported hitting "unfollow" there. So possibly we do need some more changes to not depend upon the deletion button.

**Comment by tobiasd** [comment]
This PR was closed, when the 2021.09-rc branch was deleted, is that correct? Or should it be re-opened and pointing towards develop?

**Pull request closed without merging**
