### PR TITLE
Contact array can be empty in Model\Contact::getAvatarPath

### PR DESCRIPTION
**Pull request by MrPetovan**
- Address https://github.com/friendica/friendica/issues/11630#issuecomment-1274195844

### CODE REVIEW

**Comment by tek-aevl** [comment]
How do I fix this, to check my messages?

**Comment by MrPetovan** [comment]
@pehden Until we publish the new release, you have to pull the `2022.09-rc` branch manually with Git from your server command line. Let me know if you need assistance with any part of this process.

You can also manually edit the `src/Model/Contact.php` file directly and add the `?? 0` on line 1714 (hopefully). This may interfere with the upgrade to the upcoming release depending on your method.

**Comment by tobiasd** [comment]
> Until we publish the new release, you have to pull the 2022.09-rc branch manually

Or wait hopefully only till this evening ;-)

**Comment by tek-aevl** [comment]
I saw that, this today, but saw the update that night, lol. Thanks, that was perfect timing.

**Pull request merged**
