### PR TITLE
Remove extraneous relation on item-activity.id

### LINKED ISSUE #7134: Local posts get deleted.
I have set the database cleanup to 30 days.

### Expected behavior
Local posts should not be affected. 
### Actual behavior
Local posts get deleted, too. 
### Steps to reproduce the problem
No idea. 
### Friendica version you encountered the problem
2019.3

Is it somehow possible, that I misconfigured something, so friendicas database cleanup "thinks" its own posts are from a foreign node? 
I can't find a pattern in what gets deleted or not from my own posts... 

Screenshot from the-federation.info... You can see the drop twice:

Screenshot_20190512-225626

### PR DESCRIPTION
**Pull request by MrPetovan**
Should fix #7134

Since it's a change in the relations, I don't believe there will be any database structure change and as such doesn't require a bum in the schema version number.

Thanks a ton to @SpcCw who single-handedly spearheaded the debugging effort for this hard to track issue.

### CODE REVIEW

**Comment by annando** [comment]
WTF? BTW: There is another weird relation for `item-content`.

**Comment by MrPetovan** [comment]
Removed as well.

**Comment by annando** [comment]
Okay. I looked a little bit further. I guess I have to point the blaming finger to myself :-) This is most likely a "copy & paste" problem. I copied the structure for these two tables from the `item` table. There is this relation as well - but there is does make sense, since the thread id is the item id of the first post of a thread. And deleting the one or the other is expected to invoke the cascade.

**Comment by MrPetovan** [comment]
It's okay. Everybody makes mistakes. Thank you for being gracious pursuing fixes.

**Pull request merged**
