### PR TITLE
[Needs OpenID testing] Add token to register

### PR DESCRIPTION
**Pull request by tobiasd**

### CODE REVIEW

**Comment by tobiasd** [comment]
Eventually this breaks OpenID registration ;-) could not be tested as I don't have openod

**Comment by Hypolite** [comment]
I don't have OpenID either, maybe @strk?

**Comment by annando** [comment]
Has someone now tested it with OpenID? or should we accept this PR and would see then?

**Comment by strk** [comment]
My node is down (disk failure) and I dunno when I'll have time to
bring it back up (btw, will need to re-do all my connections, as
I didn't take any backup).

**Comment by annando** [comment]
When you don't have any backups, please consider that you mustn't use the same handle again.

**Comment by strk** [comment]
Why is it so ?

**Comment by annando** [comment]
Every handle has got a unique private and public key pair. The private one is stored only on your machine, the public one is stored at every of your communication partners. When you now want to contact anyone that has contacted you before, the public key will not fit to your new private one. So the communication will fail.

It's a pity that you don't have any backup.

The solution is to use another subdomain and/or nickname.

**Comment by strk** [comment]
Wow, this is really unfortunate. A liberating technology should also free us from annoyances, and this is a HUGE one :)

For comparison: Kontalk warns your contacts about you having changed your key and gives them a way to (1) avoid encryption (2) confirm new key.

Yes, it's a pity I didn't take backup, but even bigger pity that loosing my keys makes my global handle unavailable forever. One day all handlers will be taken forever :P

**Comment by fabrixxm** [comment]
The handles aren't taken forever. You can reuse it, but you must inform all your contact to remove you via some other communication channels, before reconnect to them.
If you have a different handle, you can start a new connection process without any problem.

**Comment by annando** [comment]
You do have a huge problem with Diaspora. You won't be able to communicate with your handle over Diaspora again.

**Comment by tobiasd** [comment]
On Mon, 15 May 2017 09:44:04 -0700
Sandro Santilli <notifications@github.com> wrote:

> Yes, it's a pity I didn't take backup, but even bigger pity that
> loosing my keys makes my global handle unavailable forever. One day
> all handlers will be taken forever :P

Isn't this only a problem for communication over the Diaspora protocol?

**Comment by Quix0r** [comment]
@strk I let database backups run automatically by cronjob. Really easy to accomplish. :-)

**Comment by strk** [comment]
I also had backups... on the same disk which burned

**Comment by Hypolite** [comment]
> I also had backups... on the same disk which burned
Now you're scaring me, I don't have offsite backups either :/

**Comment by annando** [comment]
Can we now accept this PR? Since this is now an early development stage we should habe enough time to see if something breaks, don't you think so?

**Comment by strk** [comment]
Go ahead, I cannot test anyway. I've been set off by the identity-burn bug

**Pull request merged**
