### PR TITLE
Stopped using deprecated constants NETWORK_*

### PR DESCRIPTION
**Pull request by Quix0r**
Rewrite:
- stopped using deprecated NETWORK_* constants, now Protocol::* should be used
- still left them intact for slow/lazy developers ...

### CODE REVIEW

**Comment by MrPetovan** [comment]
I didn't see you removing the constant declarations in `boot.php`?

**Comment by Quix0r** [comment]
No, I did not remove them to keep backwards-compatiblity.

**Comment by Quix0r** [comment]
Done.

**Comment by MrPetovan** [comment]
> No, I did not remove them to keep backwards-compatiblity.

Please remove them completely and convert them in addons as well. Otherwise it feels like this PR is only going half the distance.

**Comment by Quix0r** [comment]
Yes, I was busy with OpenStreetMap. :-) Will come back to this.

**Comment by Quix0r** [comment]
I have rebased my changes against latest `develop`.

**Comment by Quix0r** [comment]
I have searched for `NETWORK_` and found nothing anywhere. So it is clean now.

**Pull request merged**
