### PR TITLE
content: make experimental mod/content.php work again

### PR DESCRIPTION
**Pull request by rabuzarus**
content.php wasn't working anymore. I tried to fix it and added some stuff which is also in friendicas html view. Beside this content.php is far away from being really usable

### CODE REVIEW

**Comment by annando** [comment]
I had planned to delete it since it contains many redundancies and isn't in use.

**Comment by redmatrix** [comment]
The original intention was to have a single unified content query function which consolidates all of the separate places where content is fetched. If this *was* done, it would ultimately reduce the redundancies and lower the possibility of regressions caused by localised changes to any of the dozens of different item SQL queries. In hubzilla we have turned this into a generalised function (but not as a module) and it is being used in a number of places; although we haven't yet removed all of the duplicated code. Anyway that's where I was going with that when it was created.

**Comment by rabuzarus** [comment]
Yes the redundancies are very high. But the idea of getting items/stream in json is a really good one and shouldn't be abolished

**Comment by annando** [comment]
I would like to have this functionality moved into one or several classes so that the data could be outputted either as JSON or with templates. Like Mike said, the idea of having a centralized place is very good.

I have no problem, accepting this pull request - but would like to have a separate class for functionality like this.

**Pull request merged**
