### PR TITLE
Issue 14055: Set link to group server for group posts

### LINKED ISSUE #14055: Forums - "Link to Source" URL should link to the forum server
Writing a post to a forum means, that the forum takes over the ownership of the post (not the content) and redistribute it. 

Friendica Forum

But if you click on the "Link to Source" button on the right side you are lead to the original posters server, instead to the forum server. This is illogical and wrong, because the technical owner should be as well the content provider.

One very natural reason is, that instances come and go and then it is a very hard task to follow a conversation for a normal user.

So the "Link to source" should always point to the post on the forums server.

### PR DESCRIPTION
**Pull request by annando**
Fixes #14055

### CODE REVIEW

**Comment by MrPetovan** [comment]
Ha, you ended up fudging with the GUID, even though we don't have any for posts coming from non-Friendica platforms?

**Comment by annando** [comment]
Yeah, we *should* calculate the guid for these posts always in the same way. But of course this also means that we shouldn't change the method for that from now on.

**Comment by MrPetovan** [comment]
I'm glad it's documented _somewhere_ 😄

**Comment by annando** [comment]
The source code is the documentation :grimacing:

**Pull request merged**
