### PR TITLE
Fix missing closing tag + updated links.

### PR DESCRIPTION
**Pull request by AndyHee**

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
Please update the related German translation of this same page in `doc/de/FAQ-admin.md`

**Comment by AndyHee** [comment]
Done.

(Sorry about the branch merge mess)

**Review by MrPetovan — CHANGES_REQUESTED** [review]
Thanks for the translation, I see an unclosed `<a>` tag on line 48 of the `doc/de/FAQ-admin.md` file. Can you please close it like you did for the English page?

**Comment by AndyHee** [comment]
That slipped my attention. Done, now.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
