### PR TITLE
Enable OAEP padding

### LINKED ISSUE #4442: Drop unsecure OPENSSL_PKCS1_PADDING from openssl_private_decrypt()
On a suggestion from @paragonie-scott, there's a known vulnerability in the standard PKCS1 padding and he is recommending to use OPENSSL_PKCS1_OAEP_PADDING instead. However, this isn't a backwards-compatible change, so we can only use it for internal communication (Diaspora is using the default padding as well but we can't change their side).

He offered to add a comment here detailing the best migration/fallback strategy.

I believe I have to say his name three times.
@paragonie-scott!
@paragonie-scott!
@paragonie-scott!

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #4442

Enabling OAEP was easy.

Making sure that Friendica nodes would stay compatible before and after the update (and with Diaspora!) was not.

Thankfully @paragonie-scott came to the rescue with a padding-agnostic `openssl_private_decrypt` function.

### CODE REVIEW

**Comment by MrPetovan** [comment]
This has been rebased against the RC changes, please merge #4651 first.

**Comment by fabrixxm** [comment]
I think you should rebase also this one against last develop, sorry

**Comment by MrPetovan** [comment]
Just merge #4651 first, please?

**Comment by fabrixxm** [comment]
Sorry, I was under impression that master was merged in develop after the release.
Would be fine for you if I do that instead of merge #4651 ?

**Comment by MrPetovan** [comment]
#4651 is exactly that, plus all the conflicts resolved. Please don't do it a second time. 🙏

**Comment by annando** [comment]
I'm confused. The https://github.com/friendica/friendica/pull/4651 is now accepted, but this PR stays that long. I would like to delegate the job to @fabrixxm

**Comment by MrPetovan** [comment]
The display doesn't matter, the same commits won't be merged again.

**Comment by annando** [comment]
But I guess there is a way to make this PR showing only the _real_ changes?

**Comment by MrPetovan** [comment]
Re-doing it, probably.

**Pull request closed without merging**
