### PR TITLE
"item" is replaced by "post-view" / postupdate check added

### LINKED ISSUE #9814: 'Tag Cloud' is throwing DB error 1052 - column 'private' is ambiguous
- [X] I have searched open and closed issues for duplicates

### Bug Description
Looks like the additional feature 'Tag Cloud' is causing a database error because there is an ambiguous column 'private' in where clause. 

```
index [ERROR]: DB Error {"code":1052,"error":"Column 'private' in where clause is ambiguous","callstack":"DBA::p, TagCloud::tagadelic, TagCloud::getHTML, Widget::tagCloud, Status::content, Index::content, call_user_func, Page::initContent","params":"SELECT `name`, COUNT(`name`) AS `total` FROM `tag-search-view` LEFT JOIN `item` ON `tag-search-view`.`uri-id` = `item`.`uri-id` WHERE `tag-search-view`.`uid` = XX AND `item`.`visible` AND NOT `item`.`deleted` AND NOT `item`.`moderated` AND `private` != 1 AND `item`.`wall` AND `item`.`owner-id` = 1139 GROUP BY `name` ORDER BY `total` DESC LIMIT 50"} - {"file":"Database.php","line":662,"function":"p","uid":"3b3f6a","process_id":156257}
```
I masked the UID of the user.

### Steps to Reproduce
I don't use the feature myself. But maybe it's enough to activate it and watch the Friendica log.

1.  enable additional feature 'tag cloud'
2.  use it (I don't know how. It is just there. Isn't it?)
3.  watch your log, grep for DB errors

### Platform Info
Friendica Version:
2021.03-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

### PR DESCRIPTION
**Pull request by annando**
`item` is replaced by `post-view` in many places. Also older updat and post  updat processes have been removed that are superfluous now. Also a check is added that updates aren't possible from really old versions.

And also this PR will fix https://github.com/friendica/friendica/issues/9814

### CODE REVIEW

**Comment by AlfredSK** [comment]
Nooo. Test are failing.

**Comment by MrPetovan** [comment]
Tests are failing with the following error:

```
1) Friendica\Test\legacy\ApiTest::testApiStatusesRepeatWithId
Friendica\Network\HTTPException\ForbiddenException: 

/home/runner/work/friendica/friendica/include/api.php:2078
/home/runner/work/friendica/friendica/tests/legacy/ApiTest.php:1903
```

**Comment by annando** [comment]
@MrPetovan that's weird because there hadn't been changes at this place.

**Comment by MrPetovan** [comment]
This is the beauty of tests, they are able to catch things that you didn't expect to break. Sometimes it's just about updating the test to conform to the new way of doing stuff, but sometimes you were blindsided.

**Comment by annando** [comment]
But also the tests are sometimes failing by random - like I experienced the last few days - or that the test cases have got their problems like I saw this weekend as well. It's a mixture of these three cases. (But nonetheless mostly the tests are good to have)

**Review by MrPetovan — APPROVED** [review]

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
You'll get it right eventually! 💪

**Comment by annando** [comment]
It is a test data problem, it seems.

**Comment by annando** [comment]
Yeah, tests are finally running ...

**Comment by AlfredSK** [comment]
Huzzah! 🎉

**Review by MrPetovan — APPROVED** [review]

**Comment by AlfredSK** [comment]
New comments seem to stay now. But the comments that vanished in the last hours are still missing. They're gone. 

Oh! It's even weirder. When looking at new forum posts on the network page they still show no comments. But when I follow a notification link to the /display page the comments are displayed. Example: 
https://libranet.de/display/0b6b25a8-6960-04d3-75b4-e3f069017709
^^^^^
The same item shows no comments when scrolling through the network page (or using the forum widget).

**Pull request merged**
