### PR TITLE
Move Objects to Model

### PR DESCRIPTION
**Pull request by MrPetovan**
Related to #3878

So that everything is clear: in Model should only be static classes that interact with the DB with the same name as a database table.

In Object should be all the support classes that don't interact with any database table and shouldn't have the same name as a database table.

### CODE REVIEW

**Comment by zeroadam** [comment]
GContact!!!

**Comment by MrPetovan** [comment]
I know, it was a mistake on my part, and it's now reverted!

**Comment by zeroadam** [comment]
I thought the renaming to GlobalContact was on purpose, not a mistake! :smile:

**Comment by MrPetovan** [comment]
At the moment it seemed a good idea, but now it just is an inconvenience
for the Model naming scheme.

**Comment by MrPetovan** [comment]
Ah, good point, I'll do that tonight.

**Comment by annando** [comment]
I guess we really need some documentation for the future where to place new objects.

**Comment by MrPetovan** [comment]
This is mostly relevant for the transition from `include` to `src`, it will be less relevant afterwards.

**Comment by annando** [comment]
Even after the transition there will always be new classes. So we always will need some guidance for this.

**Comment by annando** [comment]
I had to revert it, since it created massive errors. For example in "include/conversation.php" still "use Friendica\Object\Item;" was used, although this class is now called "Post".

Additionally inside Post.php the class was still called with "Item".

I'm not sure if there are more errors, my logfile really grow really fast.

**Pull request merged**
