### PR TITLE
Bugfix App

### PR DESCRIPTION
**Pull request by nupplaphil**
Bugs because of #6641 
- started index.php with wrong flag (lost during rebase of #6673 )
- Set `BaseObject::setApp()` to late

### CODE REVIEW

**Comment by nupplaphil** [comment]
plz merge https://github.com/friendica/friendica-addons/pull/806 too

**Comment by nupplaphil** [comment]
@ all I've to sleep now .. https://friendica.philipp.info is online again with this PR-branch

Two strange behaviors so far, which I have to inspect tomorrow:
- The worker count seems to not decrease (the worker shows "normal" debug-output without errors or something)
- I can only use `$config->getCache->get('system', 'basepath')` and not only `$config->get('system', 'basepath')`, which results an empty set (I think that's some mis-behavior of the `Configuration->get()`, but I've to investigate)

**Comment by AndyHee** [comment]
It looks like this PR (or some related work) doesn't work. I get fatal errors resulting in a WSOD:

```
2019/02/18 03:56:15 [error] 1871#1871: *92114 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed t│
Stack trace:                                                                                                                                 │
#0 /var/www/friendica/src/Core/Hook.php(201): geonames_load_config(Object(Friendica\App), Object(Friendica\Core\Config\ConfigCacheLoader))   │
#1 /var/www/friendica/src/Core/Hook.php(177): Friendica\Core\Hook::callSingle(Object(Friendica\App), 'load_config', Array, Object(Friendica\C│
#2 /var/www/friendica/src/App.php(388): Friendica\Core\Hook::callAll('load_config', Object(Friendica\Core\Config\ConfigCacheLoader))         │
#3 /var/www/friendica/src/App.php(229): Friendica\App->reload()                                                                              │
#4 /var/www/friendica/index.php(25): Friendica\App->__construct(Object(Friendica\Core\Config\ConfigCache), Object(Monolog\Logger), false)    │
#5 {m" while reading response header from upstream, client: 159.69.231.139, server: friendica.hubup.pro, request: "POST /receive/public HTTP/│
```

I had to reset to `50dc31de877c3b882c27aa7a275d62e0fa1ef97a`

**Comment by AndyHee** [comment]
I thinks this merged PR that's causing the fatal error: https://github.com/friendica/friendica-addons/pull/806

**Comment by MrPetovan** [comment]
Do you have the full error message?

**Comment by AndyHee** [comment]
Please have a look here: https://hastebin.com/zebemesigo.shell.

Let me know if you need more information.

**Comment by AndyHee** [comment]
I'm running PHP 7.3.

**Comment by MrPetovan** [comment]
Both your friendica and friendica-addons repository are mismatched. However I don't recommend updating either, instead you can restore both to the last working state:
```sh
git checkout 356221b4bb06eb5798299817a6a173e786b863fb
cd addon
git checkout 50dc31de877c3b882c27aa7a275d62e0fa1ef97a
```

**Comment by AndyHee** [comment]
Thanks.

**Comment by MrPetovan** [comment]
This PR breaks a node if there's an empty `system.basepath` value in the `config` table because of the order of config cache loading. The database value trumps the value manually set in `ConfigCacheLoader.php:41` and triggers a `Basepath '' isn't usable.` exception. This empty value is set in the admin settings to auto-detect the base path and should work correctly.

@nupplaphil I seem to be unable to revert the previous PR, so this fix should be your absolute priority when you take time for Friendica.

**Comment by AndyHee** [comment]
`This PR breaks a node if there's an empty system.basepath value in the config table because of the order of config cache loading. The database value trumps the value manually set in ConfigCacheLoader.php:41 and triggers a Basepath '' isn't usable. exception. This empty value is set in the admin settings to auto-detect the base path and should work correctly.`

Thanks for the background info. Appreciated!

**Comment by AlfredSK** [comment]
Same here. Fatal server error, error 500, WSOD.

**Comment by JeroenED** [comment]
Taking myself in the loop so I know what it's safe to update again.

**Comment by AndyHee** [comment]
Hi @nupplaphil Not sure if it worked, as I still got a fatal error. Please have a look here: https://hastebin.com/urayikigex.shell

**Comment by nupplaphil** [comment]
even after latest git pull (including fix #6685 ?)

I had `system.basepath = ''` in my config table and it works for me ..

**Comment by AndyHee** [comment]
```
even after latest git pull (including fix #6685 ?)

I had system.basepath = '' in my config table and it works for me ..
```
It failed after #6685 . 

I'm on the preloaded configuration adapter, if this is related. How to I check what's in the config table?

**Comment by MrPetovan** [comment]
```sql
SELECT value FROM config WHERE key = 'basepath';
```

**Pull request merged**
