### PR TITLE
polishing of the contact-edit page

### PR DESCRIPTION
**Pull request by rabuzarus**
I was not happy with fact that in the tab bar of the single contact page (which was introduced with the last friendica version) mixes page links and action links (like hide, block and so on).

This would make the situation a little bit better.

I'm not fully satisfied with the result of this work but I think it does make the situation better than before.

It's very hard to respect all the different themes. So I would commit it rather yet before loosing motivation.

contact_action_button

### CODE REVIEW

**Comment by fabrixxm** [comment]
:+1: could you fix merge conflicts?

**Comment by annando** [comment]
I think that "repair" should be a regular menu item in the nav bar. By clicking on it you don't start an action but opens another page.

**Comment by fabrixxm** [comment]
mh.. yes, but is not a "standard view" of the contact..
the page shown on clicking "repair" is more like a dialog, to me.
I feel it like you say "repair" (which as a text is already an action), then the system has to ask you "what do you want to repair?", just like when you click on "delete", the system ask you "are you sure?"
Going further, repair form could be loaded in a modal colorbox when the user clicks on "repair"...

**Comment by annando** [comment]
I think that "repair" is the complete wrong word for the page. It shows (technical) contact details. You could do some repair with it - or you could activate "remote self" (which isn't a repair).

We really should decide between the actions like "delete" or "ignore" (they are starting actions) and displaying another page. And the displaying of pages should be in the tab bar.

**Comment by rabuzarus** [comment]
I will solve the merge conflict.

My view on the "dispute" :-) I have long thought about the thing with "repair". I have to agree to booth of you.
It dosn't feel right to load a total new page about the "action drop menu" but it even doesn't feel right to put it in the tab bar because of the things which fabio said + the people don't have to use it very often and it doesn't feel right to putt at such a prominent place. I would a prefer a little more hidden place so that you find it but not in the tab bar.

Since some time I'm thinking about that it would really perfect to have some friendica pages as overlay modals. There are some page in friendica which feel very lost as standalone page. E.g. the poke page. I think we should think about this option.

But I'm not really happy with colorbox. Colorbox does it very easy but it isn't really good when you want to theme it. Since long time I want to take some time and look if it's possible to do it better (more beautiful and responsive) with colorbox than we do it now. 

To give you my point where I have problems with colorbox:
* it doesn't seem to be able to change the size once it is open (nor is it real mobile friendly)
* I would like to have the possibility to theme it differently according to the content (e.g. photo or page) without to do this in the main.js
* Colorbox is loading images as part of it's theme

What I really would like to have is some kind of modal functionality in friendica like the one in bootstrap but I don't now all the pro and contra with respect to colorbox. And If we would decide to go this way what would be the best solution? Coding own js modals or using some kind of library (like http://github.hubspot.com/vex/docs/welcome/). If we would go this way it would be also nice to have bootstrap compatibility so if people want to write a friendica bootstrap theme don't have to rewrite that much.

OK that were my thoughts on this topic.

Ahh I want to come back to the here and now. To have it in the tab bar seems not a good solution to me. Any suggestions here? Maybe we should ask in the support forum for more input.

**Comment by fabrixxm** [comment]
> I think that "repair" is the complete wrong word for the page. It shows (technical) contact details. 
> You could do some repair with it - or you could activate "remote self" (which isn't a repair).

So I would say that "remote self" is in an inappropriate place... or instead of "repair" we could call that menu "advanced"

I fell the now called "actions" menu is like a right-click menu, were is not so unusual to find a "properties" item with the advanced settings

About the colorbox issue, I've tried to resolve the thing with the "Dialog" object in [main.js](https://github.com/friendica/friendica/blob/develop/js/main.js#L871) . A theme can overwrite the show function to use another library by, e.g., adding something like

    <script>Dialog.show = function(url) { AnotherFancyModal.load(url); };</script>

somewere in the page.

That object is used by file and image browser dialogs, but not by ACL dialog, yet

**Comment by rabuzarus** [comment]
> About the colorbox issue, I've tried to resolve the thing with the "Dialog" object in main.js .

Yes I have seen this and I'm very happy that you have implemented it. I just want to raise the discussion if we want to use something for modals which is more suitable for modals (without the points I noted above).
Note: I don't want to say it have to be done this way. I just wanted to have a discussion on this. What would be the pro and contra for each of this solutions? But I shouldn't pollute github with this. I will write something at support forum. This would be better for discussion.

Back to topic (The PR):
Should repair open in a colorbox and we leave it in  the actions menu or should it be moved to somewhere else? How should we name it?

**Comment by fabrixxm** [comment]
I'm for leave it there, and call it "advanced"

**Comment by annando** [comment]
:+1: for "advanced". In a next step we should rename the menu description for the contacts as well. it is now something like "Kontakt bearbeiten" (edit contact) which isn't really true, I think.

**Comment by rabuzarus** [comment]
BTW: 'Suggest Friend' and 'Update' does need a link 'title' as description

Any good suggestion (sry for being not that creative) ?
@tobiasd wanna join in?

**Comment by rabuzarus** [comment]
@fabrixxm 
Can I load the colorbox dialog directly in the template? And how? I would like to do it with the onclick attribute.

I tried do do it with the 'ajax-popupbox' class but it didn't work. It seems to load the content but with no width and no height.

**Comment by tobiasd** [comment]
Maybe make it simply "edit profile" -> "Profile"

**Comment by annando** [comment]
@tobiasd :+1:

**Comment by fabrixxm** [comment]
looks like adding 'ajax-popupbox' class to an 'a' attribute should work. it's used in events page template to load event detail in colorbox.

    <a href="..." class="ajax-popupbox">...</a>

should be enough.

(it works with a quick test in-browser with quattro theme. no time now to test with vier..)

and if you link to "/crepair/<id>?mode=minimal" you get the perfect content for the popup...

**Comment by annando** [comment]
@rabuzarus what do you want to put into the colorbox?

**Comment by rabuzarus** [comment]
@annando 
> Going further, repair form could be loaded in a modal colorbox when the user clicks on "repair"...

So did it so. Any concerns about this?

**Comment by rabuzarus** [comment]
@fabrixxm 

The correct address would be `crepair/ID?mode=minimal`

From the browser developer tools:
```
<a class="ajax-popupbox cboxElement" href="crepair/46?mode=minimal" title="Fortgeschrittene Kontakteinstellungen">Erweitert</a>
```

But this is the result with vier theme :-/
repair-colorbox

The content is loaded. It is there. But width and height calculation of the colorbox isn't correct

**Comment by annando** [comment]
Have it called "advanced" and let it stay in the tab bar would be my favourite :-)

**Comment by fabrixxm** [comment]
> The correct address would be crepair/ID?mode=minimal

Yes, my original post was

> and if you link to "/crepair/&lt;id&gt;?mode=minimal" [...] 

but github ate my angled brackets :-)

> The content is loaded. It is there. But width and height calculation of the colorbox isn't correct

I'll have a look

**Comment by rabuzarus** [comment]
@annando 
I really would like to have repair as advanced not in the tab bar. To use repair is (or should be) really a corner case for the common user and the tab bar a too prominent place for such a corner case.

I have thought about to have a page (and tab bar entry) with that what I have know called 'Contact Settings' and the 'Advanced Settings' (aka repair) and call it Settings in the tab bar. But then the contact profile page would look really empty (if the user doesn't really provide additional profile info - like I do ;-)  )  . And in my perception we don't need another 'whole' page with very little information.

What are your concerns about modals?

We all know that friendica does have some gui related issues. One of them is the structuring of information. At the one side there are pages with to much information (like some setting pages) and some with very little information (like e.g. poke, or contact suggestion).

If a page exists there is the problem to place it somewhere in friendica (this is not very easy for some pages). If it's real own page you have to deal with the problem that the page have to reachable in an easy way and that you have to go back to the previous page. (and this have to be all in a logical context).

Sure tab bars are perfect for doing this. But because of the limited space we should avoid putting all kind of pages in the tab bar because it is an easy way. My opinion is, the user would expect nav bar links which he/she is using very often.

In this view I find the idea of having modals very interesting. It solves the problem of how to come pack to point where you started (You only have to press the close icon and you are on the original place). I think this is a really important point, because it gives you more freedom in arranging links which guides you to a page (which should be solved -  in the case without modals - with some kind of nav).

Moreover we better can connect content, which would result without modals in a crowded and confusing page (if we would put all information in one page).

In my opinion there are 3 use cases where we should think about using modals.
1.) pages which are rarely used because they are a corner case (we have look if the content isn't to much so it would fit in a modal)
2.) actions (like e.g. poke)
3.) pages with very little content (this would include some of some of the action pages but also if we would have pages which does only provide a small information).

One issue still remains also with models. We have to think carefully about where we put the 'link' to the model so it would make sense to have it at this place

Note:
@annando I know you are very busy with the forum problem. It doesn't hurry to have an answer.

**Comment by fabrixxm** [comment]
So, what's the status of this?

**Comment by rabuzarus** [comment]
actual status of this is:
We need a decision how and where we want present 'advanced' (aka repair)

**Comment by annando** [comment]
My vote goes to a link "advanced" that is in the navigation bar and that opens the current "repair" page.

**Comment by rabuzarus** [comment]
OK I moved the repair link back to the tabbar as advanced. But I don't think it's a good solution (but I do not want to repeat myself)

@fabrixxm 
In quattro the status box does have `#contact-edit-status-wrapper { border-color: @JotToolsOverBackgroundColor;}` as outline color.
I would leave it to you as theme maintainer to give it maybe another color or colorname

**Comment by fabrixxm** [comment]
> I would leave it to you as theme maintainer to give it maybe another color or colorname

Ok

So, is this mergeable?

**Comment by rabuzarus** [comment]
From my side, yes

**Pull request merged**
