### PR TITLE
Split include/text.php to Model/FileTag class

### PR DESCRIPTION
**Pull request by zeroadam**
split functions to new FileTag class

Related to #3878

### CODE REVIEW

**Comment by zeroadam** [comment]
I found no usages of FileTag methods in Addons, so this PR stands alone.

**Comment by MrPetovan** [comment]
What even are these `file_tag_*` functions?

**Comment by zeroadam** [comment]
I don't know if it's only this, but while coding I "tested" adding a tag to a photo. I'm not sure what other "files" can be tagged this way. I assume that's what these functions are for.

**Comment by rabuzarus** [comment]
Can you please give some more love to the methods doxygen headers by adding the `@param` and the `@return` value where it is possible?

**Comment by annando** [comment]
We even have a script that adds a basic doxygen header to the files.

**Comment by zeroadam** [comment]
@rabuzarus Yes I certainly will!
@annando could you point me in the right direction for that? I've been "away" for far too long! 😁

**Comment by zeroadam** [comment]
@rabuzarus Documentation added!

**Pull request merged**
