### PR TITLE
Decouple conversation creation from rendering

### PR DESCRIPTION
**Pull request by MrPetovan**
Blocks #13245

- This allows to separately obtain a list of threads for rendering without having to deal with an already-formed HTML output

### CODE REVIEW

**Comment by annando** [comment]
So this has to be checked first before accepting https://github.com/friendica/friendica/pull/13245?

**Comment by MrPetovan** [comment]
Indeed.

**Comment by annando** [comment]
Have you ran this on your system for a day?

**Comment by MrPetovan** [comment]
Yes, all the while I was working on the rest of the moderation branch.

**Comment by annando** [comment]
Okay.

**Pull request merged**
