### PR TITLE
Small fixes and spelling

### PR DESCRIPTION
**Pull request by fabrixxm**
I'm fixing small thing I found while update translations.
Maybe I'll add some more commits :-)

### CODE REVIEW

**Comment by annando** [comment]
So we should wait with merging?

**Comment by fabrixxm** [comment]
> So we should wait with merging?
yup. give me some time to finish to translate new strings. If I find something else, I'll add a commit.
When I'm done, I'll add a comment here 👍

**Comment by fabrixxm** [comment]
Ok. Done. 👍

**Comment by tobiasd** [comment]
Will you do a PR for the IT translation work?

**Pull request merged**
