### PR TITLE
Switch to github actions

### PR DESCRIPTION
**Pull request by nupplaphil**

### CODE REVIEW

**Comment by MrPetovan** [comment]
Shouldn't the action kick in for this PR?

**Comment by nupplaphil** [comment]
yep .. I need this PR for some tests .. I'll write a comment when I'm finished :-)

**Comment by MrPetovan** [comment]
I see you removed a bunch of stuff, is this actually ready to merge?

**Comment by nupplaphil** [comment]
no, no .. The problem is I don't have a right environment for the github acitons (yet) so I do need this PR for some tests... I'll rebase it and comment with "ready" when I'm ready .. tbh the current state is that I'm wondering why it isn't working ;-)

**Comment by nupplaphil** [comment]
@tobiasd or  @MrPetovan can you check the "settings" of this repo? I do need this setting enabeld:
grafik

**Comment by MrPetovan** [comment]
I don't think I have access to the options of this repository.

**Comment by nupplaphil** [comment]
I found a way to test without a PR: https://github.com/nupplaphil/friendica/actions my own action list :) 
=> Closing until finished

**Pull request closed without merging**
