### PR TITLE
Add GPG signing for drone artifacts

### PR DESCRIPTION
**Pull request by nupplaphil**
<strike>- Replace SHA256 with SHA512</strike> (nope)
- Sign artifacts per GPG (newly created private key was added as encrypted secret at drone)

Public key can be found at https://files.friendi.ca/friendica.asc

### CODE REVIEW

**Comment by MrPetovan** [comment]
Why not jump to SHA1024? Why not SHA2048? Where's the limit?

**Comment by tobiasd** [comment]
What is the benefit of using sha512? Except that it will break the homepage layout. Preparations for quantum computers? (serious question)

**Comment by MrPetovan** [comment]
The homepage layout?

**Comment by nupplaphil** [comment]
Ah it was just because I found some repos using SHA512 instead of SHA256, so I though why not using it ;-)
But you're probably right, SHA256 is enough, there is currently no way of "collision attacks" or similar (except using quantum computers ;-) ) --> I revert it again

**Comment by tobiasd** [comment]
> The homepage layout?

The sha256 sums are listed on the homepage for the stable releases. sha512 sums are twice as long as sha256 sums and will most likely be too wide for the place they are supposed to fit in.

**Comment by MrPetovan** [comment]
To be frank @tobiasd 's reason for keeping SHA256 is better than mine.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
