### PR TITLE
[Refactoring] Replace App with AppHelper

### PR DESCRIPTION
**Pull request by Art4**
This PR replaces more usages of the `Friendica\App` class with `Friendica\AppHelper`.

### CODE REVIEW

**Comment by Art4** [comment]
There are some calls of `DI::app()` in addons that has to be removed:

- https://github.com/friendica/friendica-addons/commit/39c654da00e63a58b6a930e7d0e555bfb248b44b#r149445970
- https://github.com/friendica/friendica-addons/commit/f4110880a152a09c5dac5d5db2f3beb12f57e2b5#r149446044

**Comment by MrPetovan** [comment]
Thanks, I'll take a look.

**Comment by MrPetovan** [comment]
All three Addons PRs have been created:
- https://git.friendi.ca/friendica/friendica-addons/pulls/1570
- https://git.friendi.ca/friendica/friendica-addons/pulls/1571
- https://git.friendi.ca/friendica/friendica-addons/pulls/1572

**Comment by Art4** [comment]
I removed neary all calls for `DI::app()` except in index.php and tests folder. Refactoring of the tests will be done in a separate PR. I will now work on replacing the `App` class with `AppHelper` in the addon repository.

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
Do you have a local node you can test this branch with?

**Comment by Art4** [comment]
> Do you have a local node you can test this branch with?

I'm testing on my local machine as much as I can. The changes in this PR mostly only remove unused code. 

btw. I think a new [Refactoring] tag would be more appropriate. :wink:

**Pull request merged**
