### PR TITLE
Get rid of the "item" table

### PR DESCRIPTION
**Pull request by annando**
I know at least one person who will be glad hearing this :grin: 

We only kept the item table since in the transition phase we would otherwise deliver wrong posts (posts that had been created before the update but are sent after the update).

We now change them directly in the workerqueue, so that we can get rid of the item table.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
I've tried to delete the `item` table manually today after reading [this helpful comment about disk space savings](https://github.com/friendica/friendica/issues/10070#issuecomment-805838280) by @bkil but I got the following error:
```
MariaDB [friendica]> DROP TABLE `item`;
ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails
```
The `SHOW CREATE` or the table outputs this:
```
 CREATE TABLE `item` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `guid` varchar(255) NOT NULL DEFAULT '' COMMENT 'A unique identifier for this item',
  `uri` varchar(255) NOT NULL DEFAULT '',
  `uid` mediumint(8) unsigned NOT NULL DEFAULT 0 COMMENT 'Owner id which owns this copy of the item',
  `contact-id` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'contact.id',
  `gcontact-id` int(10) unsigned NOT NULL DEFAULT 0,
  `type` varchar(20) DEFAULT NULL COMMENT 'Deprecated',
  `wall` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'This item was posted to the wall of uid',
  `gravity` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `parent` int(10) unsigned DEFAULT NULL COMMENT 'item.id of the parent to this item if it is a reply of some form; otherwise this must be set to the id of this item',
  `parent-uri` varchar(255) NOT NULL DEFAULT '' COMMENT 'uri of the top-level parent to this item',
  `extid` varchar(255) NOT NULL DEFAULT '',
  `thr-parent` varchar(255) NOT NULL DEFAULT '' COMMENT 'If the parent of this item is not the top-level item in the conversation, the uri of the immediate parent; otherwise set to parent-uri',
  `created` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Creation timestamp.',
  `edited` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Date of last edit (default is created)',
  `commented` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Date of last comment/reply to this item',
  `received` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'datetime',
  `changed` datetime NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT 'Date that something in the conversation changed, indicating clients should fetch the conversation again',
  `owner-id` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'Link to the contact table with uid=0 of the owner of this item',
  `owner-name` varchar(255) DEFAULT NULL COMMENT 'Deprecated',
  `owner-link` varchar(255) DEFAULT NULL COMMENT 'Deprecated',
  `owner-avatar` varchar(255) DEFAULT NULL COMMENT 'Deprecated',
  `author-id` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'Link to the contact table with uid=0 of the author of this item',
  `author-name` varchar(255) DEFAULT NULL COMMENT 'Deprecated',
  `author-link` varchar(255) DEFAULT NULL COMMENT 'Deprecated',
  `author-avatar` varchar(255) DEFAULT NULL COMMENT 'Deprecated',
  `title` varchar(255) DEFAULT NULL COMMENT 'Deprecated',
  `body` mediumtext DEFAULT NULL COMMENT 'Deprecated',
  `app` varchar(255) DEFAULT NULL COMMENT 'Deprecated',
  `verb` varchar(100) DEFAULT NULL COMMENT 'Deprecated',
  `object-type` varchar(100) DEFAULT NULL COMMENT 'Deprecated',
  `object` text DEFAULT NULL COMMENT 'Deprecated',
  `target-type` varchar(100) DEFAULT NULL COMMENT 'Deprecated',
  `target` text DEFAULT NULL COMMENT 'Deprecated',
  `postopts` text DEFAULT NULL COMMENT 'Deprecated',
  `plink` varchar(255) DEFAULT NULL COMMENT 'Deprecated',
  `resource-id` varchar(32) DEFAULT NULL COMMENT 'Deprecated',
  `event-id` int(10) unsigned DEFAULT NULL COMMENT 'Used to link to the event.id',
  `tag` mediumtext DEFAULT NULL COMMENT 'Deprecated',
  `attach` mediumtext DEFAULT NULL COMMENT 'Deprecated',
  `inform` mediumtext DEFAULT NULL COMMENT 'Deprecated',
  `file` mediumtext DEFAULT NULL COMMENT 'Deprecated',
  `location` varchar(255) DEFAULT NULL COMMENT 'Deprecated',
  `coord` varchar(255) DEFAULT NULL COMMENT 'Deprecated',
  `allow_cid` mediumtext DEFAULT NULL COMMENT 'Deprecated',
  `allow_gid` mediumtext DEFAULT NULL COMMENT 'Deprecated',
  `deny_cid` mediumtext DEFAULT NULL COMMENT 'Deprecated',
  `deny_gid` mediumtext DEFAULT NULL COMMENT 'Deprecated',
  `private` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT '0=public, 1=private, 2=unlisted',
  `pubmail` tinyint(1) NOT NULL DEFAULT 0,
  `moderated` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Deprecated',
  `visible` tinyint(1) NOT NULL DEFAULT 0,
  `spam` tinyint(1) NOT NULL DEFAULT 0,
  `starred` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'item has been favourited',
  `bookmark` tinyint(1) DEFAULT NULL COMMENT 'Deprecated',
  `unseen` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'item has not been seen',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'item has been deleted',
  `origin` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'item originated at this site',
  `forum_mode` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `last-child` tinyint(1) NOT NULL DEFAULT 1,
  `mention` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'The owner of this item was mentioned in it',
  `network` char(4) NOT NULL DEFAULT '' COMMENT 'Network from where the item comes from',
  `rendered-hash` varchar(32) DEFAULT NULL COMMENT 'Deprecated',
  `rendered-html` mediumtext DEFAULT NULL COMMENT 'Deprecated',
  `global` tinyint(1) NOT NULL DEFAULT 0,
  `content-warning` varchar(255) DEFAULT NULL COMMENT 'Deprecated',
  `icid` int(10) unsigned DEFAULT NULL COMMENT 'Deprecated',
  `iaid` int(10) unsigned DEFAULT NULL COMMENT 'Deprecated',
  `uri-hash` varchar(80) DEFAULT NULL COMMENT 'Deprecated',
  `post-type` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Post type (personal note, bookmark, ...)',
  `psid` int(10) unsigned DEFAULT NULL COMMENT 'ID of the permission set of this post',
  `uri-id` int(10) unsigned DEFAULT NULL COMMENT 'Id of the item-uri table entry that contains the item uri',
  `parent-uri-id` int(10) unsigned DEFAULT NULL COMMENT 'Id of the item-uri table that contains the top-level parent uri',
  `thr-parent-id` int(10) unsigned DEFAULT NULL COMMENT 'Id of the item-uri table that contains the thread parent uri',
  `vid` smallint(5) unsigned DEFAULT NULL COMMENT 'Id of the verb table entry that contains the activity verbs',
  `causer-id` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'Link to the contact table with uid=0 of the contact that caused the item creation',
  PRIMARY KEY (`id`),
  KEY `guid` (`guid`(191)),
  KEY `uri` (`uri`(191)),
  KEY `parent` (`parent`),
  KEY `parent-uri` (`parent-uri`(191)),
  KEY `extid` (`extid`(191)),
  KEY `uid_id` (`uid`,`id`),
  KEY `uid_unseen_contactid` (`uid`,`unseen`,`contact-id`),
  KEY `deleted_changed` (`deleted`,`changed`),
  KEY `uid_wall_changed` (`uid`,`wall`,`changed`),
  KEY `uid_eventid` (`uid`,`event-id`),
  KEY `uid_contactid_id` (`uid`,`contact-id`,`id`),
  KEY `uid_thrparent` (`uid`,`thr-parent`(190)),
  KEY `uid_parenturi` (`uid`,`parent-uri`(190)),
  KEY `uid_uri` (`uid`,`uri`(190)),
  KEY `ownerid` (`owner-id`),
  KEY `uid_network_received` (`uid`,`network`,`received`),
  KEY `uid_network_commented` (`uid`,`network`,`commented`),
  KEY `resource-id` (`resource-id`),
  KEY `uid_commented` (`uid`,`commented`),
  KEY `psid_wall` (`psid`,`wall`),
  KEY `contact-id` (`contact-id`),
  KEY `uid_received` (`uid`,`received`),
  KEY `uid_contactid_received` (`uid`,`contact-id`,`received`),
  KEY `authorid_received` (`author-id`,`received`),
  KEY `mention_uid_id` (`mention`,`uid`,`id`),
  KEY `uri-id` (`uri-id`),
  KEY `parent-uri-id` (`parent-uri-id`),
  KEY `thr-parent-id` (`thr-parent-id`),
  KEY `uid_unseen_wall` (`uid`,`unseen`,`wall`),
  KEY `causer-id` (`causer-id`),
  KEY `vid` (`vid`),
  CONSTRAINT `item_ibfk_1` FOREIGN KEY (`uri-id`) REFERENCES `item-uri` (`id`) ON DELETE CASCADE,
  CONSTRAINT `item_ibfk_10` FOREIGN KEY (`contact-id`) REFERENCES `contact` (`id`) ON DELETE CASCADE,
  CONSTRAINT `item_ibfk_2` FOREIGN KEY (`parent-uri-id`) REFERENCES `item-uri` (`id`) ON DELETE CASCADE,
  CONSTRAINT `item_ibfk_3` FOREIGN KEY (`thr-parent-id`) REFERENCES `item-uri` (`id`) ON DELETE CASCADE,
  CONSTRAINT `item_ibfk_4` FOREIGN KEY (`psid`) REFERENCES `permissionset` (`id`),
  CONSTRAINT `item_ibfk_5` FOREIGN KEY (`causer-id`) REFERENCES `contact` (`id`),
  CONSTRAINT `item_ibfk_6` FOREIGN KEY (`owner-id`) REFERENCES `contact` (`id`),
  CONSTRAINT `item_ibfk_7` FOREIGN KEY (`author-id`) REFERENCES `contact` (`id`),
  CONSTRAINT `item_ibfk_8` FOREIGN KEY (`vid`) REFERENCES `verb` (`id`),
  CONSTRAINT `item_ibfk_9` FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3773514 DEFAULT CHARSET=utf8mb4 COMMENT='Structure for all posts'
```
I'm worried about the `ON DELETE CASCADE` clauses, would I risk losing data in live tables because of them? What would prevent the deletion of the table?

**Comment by annando** [comment]
Have you tried `bin/console dbstructure drop`?

**Comment by MrPetovan** [comment]
I have not, thank you for the hint.

**Comment by MrPetovan** [comment]
Result:
```
friendica$ bin/console dbstructure drop
These tables are not used for friendica and will be deleted when you execute "dbstructure drop -e":

participation
poll_result
fserver
item
gcontact
sign
gfollower
user-item
thread
queue
item_id
item-delivery-data
poll
spam
gcign
glink
friendica$ bin/console dbstructure drop -e
DROP TABLE `participation`;
DROP TABLE `poll_result`;
DROP TABLE `fserver`;
DROP TABLE `item`;

Error 0 occurred during database update:

DROP TABLE `gcontact`;
DROP TABLE `sign`;
DROP TABLE `gfollower`;
DROP TABLE `user-item`;
DROP TABLE `thread`;
DROP TABLE `queue`;
DROP TABLE `item_id`;
DROP TABLE `item-delivery-data`;
DROP TABLE `poll`;
DROP TABLE `spam`;
DROP TABLE `gcign`;
DROP TABLE `glink`;
friendica$ bin/console dbstructure drop
These tables are not used for friendica and will be deleted when you execute "dbstructure drop -e":

item
friendica$ bin/console dbstructure drop -e
DROP TABLE `item`;
friendica$
```
It looks like the erroring foreign key was maybe referencing one of the other tables?

**Comment by MrPetovan** [comment]
In any case, I've saved 6GB on the database size, this is excellent news.

**Comment by annando** [comment]
AFAIK there had been a foreign key on the `user-item` table. So we should move the item table to the end of the list.

**Pull request merged**
