### PR TITLE
Fix 'photo' attachment

### PR DESCRIPTION
**Pull request by MrPetovan**
See https://mass-trespass.uk/display/f83586ea675b8b9ea965093156425789

This PR fixes the double image issue, as well as better handling the now obsolete type=photo Twitter card.

It also adds the title and the domain URL to photo attachments.

### CODE REVIEW

**Comment by annando** [comment]
I'm unsure about the change. I think the removed code had some purpose. I have to check it this evening, I think.

**Comment by MrPetovan** [comment]
Which removed code? The change ensures there won't be two images for a photo attachment, displays the domain and the title if it exists. This change also handles the obsolete twittercard type "photo".

I didn't remove anything?

**Comment by annando** [comment]
I mean lines 581ff in ```src/Content/Text/BBCode.php```. This removed ```if (($data["type"] == "photo") && !empty($data["url"]) && !empty($data["image"])) {``` can cause that when there is a link to a photo - but without a title - then not even the link to the photo is displayed anymore.

**Comment by MrPetovan** [comment]
It's simple, really:
- If `$data['image']` isn't empty, then the image already has been displayed before, this is why we had a double image display.
- If `$data['image']` isn't empty instead, we use this to show a preview image.
- If `$data['title']` isn't empty, then the title will be displayed with the link.
- If `$data['description']` isn't empty and is different from `$data['title']`, then the description is displayed.
- If `$data['url']` isn't empty, then the domain will be shown with the link.

Whatever happens, we expect `$data['url']` to be set, I'm not even sure why I'm checking for it at the end.

**Comment by annando** [comment]
Looks like you really had got a deep look into it.

**Comment by annando** [comment]
I discovered a problem: Now posts to the connector networks don't publish pictures anymore - but only links to the pictures.

**Pull request merged**
