### PR TITLE
4419 Update the comments in src/Database/DBStructure.php from doc

### PR DESCRIPTION
**Pull request by abanink**
Note: I had to change "guessing" to 'guessing' because of the double quotes in the comment in db_parsed_url.md

### CODE REVIEW

**Comment by MrPetovan** [comment]
Closes #4419

**Comment by MrPetovan** [comment]
Very good job, thanks! Now, every time you make a change to `DBStructure.php`, you must increase the `DB_UPDATE_VERSION` (located in `boot.php:44`) constant value by one, as well as updating the `database.sql` file with your changes. For this file you don't have to do it manually, please use `mysqldump` instead.

**Comment by annando** [comment]
Please don't use ```mysqldump``` for this, but: ```bin/console dbstructure dumpsql > database.sql```

**Comment by MrPetovan** [comment]
Sure!

**Comment by MrPetovan** [comment]
Warning: On my system, these changes triggered a full alteration all the tables, including the item table. It's been 3 hours and 30 minutes and counting since my node is in maintenance mode.

**Comment by abanink** [comment]
If this is causing you trouble, and it would help, I can redo this against 2018.05-rc instead of develop.

**Comment by tobiasd** [comment]
As the 2018.05 was released, there is no need to apply this commit to the other branch.

It is a general warning that the changes you introduced cause some downtime of nodes. So that admins can prepare for it.

**Comment by MrPetovan** [comment]
11 hours 30 minutes and counting!

**Comment by tobiasd** [comment]
I think `mytop` does display the progress of long lasting tasks. On my node the update took 40mins IIRC. But my DB only has 4G in total size.

**Comment by MrPetovan** [comment]
Mine is 2.6G bzipped!

**Comment by MrPetovan** [comment]
Final time: 12 hours, 6 minutes and 54 seconds

**Comment by annando** [comment]
You should consider "dbclean".

**Comment by MrPetovan** [comment]
Someone has to test before/after the Great Database Update.

**Pull request merged**
