### PR TITLE
Allow negative contact.contat-type

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/friendica/friendica/issues/3328

### CODE REVIEW

**Comment by Alkarex** [comment]
@annando Is it not needed to add a function in update.php, right? dbstructure.php will do the change to existing system automagically, isn't it?

**Comment by Alkarex** [comment]
OK. Like so? https://github.com/friendica/friendica/pull/3329/commits/325d3afe183a397ea6688480c1b2df8e1be99dc1

**Comment by Alkarex** [comment]
Ok. Done. I would suggest to remove `define('UPDATE_VERSION' , 1217);` in update.php and use only `DB_UPDATE_VERSION`, if they are synonym.

**Comment by Hypolite** [comment]
This constant's existence is explained in `boot.php:1587`:
>// make sure that boot.php and update.php are the same release, we might be
 // updating right this very second and the correct version of the update.php
// file may not be here yet. This can happen on a very busy site.

**Comment by Hypolite** [comment]
Per https://github.com/friendica/friendica/issues/3328#issuecomment-293702693 we shouldn't store -1 for `contact-type` in the `contact` table. I approved those changes because they are technically correct, but maybe we should look at the contact storage angle instead, paging @annando to confirm.

**Comment by annando** [comment]
Technically this is okay. But @Hypolite is right. We also should have a look at the storing itself. So I suggest to leave the issue open.

**Pull request merged**
