### PR TITLE
Sent update mails to administrators only once

### LINKED ISSUE #6788: Multiple admin notification mails
### Expected behavior
When a notification mail is sent to the mail address of the admin it should be one mail.

### Actual behavior
When a notification mail is sent that mail is sent two, four, six, eight or 244 times.

### Steps to reproduce the problem
I have two admin accounts with two different mail addresses. So, I understand that each mail is sent twice. But when a user deletes his/her account I often get 4 ,6 or 8 mails about it.
Today the database structure was updated to version 1304 and I got **244** admin notification mails about the update.

This behavior has been confirmed by another node admin in our XMPP chat room. He got 50+ mails about the DB update.

### Friendica version you encountered the problem
2019.03-rc

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
10.1.38 MariaDB

### PR DESCRIPTION
**Pull request by annando**
fixes #6788  
This avoids that multiple update mails are sent - and it solves a problem with fetching the data.

### CODE REVIEW

**Comment by nupplaphil** [comment]
FollowUp #6773

**Comment by nupplaphil** [comment]
> This could have been simply solved by adding a `` GROUP BY `email` `` clause to the query, do we have a provision in `DBA::select` for this?

I started with the same question and started building a `Model\User::getByEMails($emails)` including the GROUP BY, but I think this isn't that easy because a GROUP BY forces you to see every field in the selection as part of the grouping.

**Comment by MrPetovan** [comment]
> a GROUP BY forces you to see every field in the selection as part of the grouping.

No need, with the `ANY_VALUE()` aggregation operator you can have only `email` in the `GROUP BY` and not get any complaints.

**Comment by nupplaphil** [comment]
> > a GROUP BY forces you to see every field in the selection as part of the grouping.
> 
> No need, with the `ANY_VALUE()` aggregation operator in the `SELECT` you can have only `email` in the `GROUP BY` and not get any complaints.

Aw .. I know it just from the Oracle environment, the `ANY_VALUE()` is new to me, thanks :-)

**Comment by MrPetovan** [comment]
I mean, MySQL does the `ANY_VALUE()` trick by default, but it wasn't the case with MariaDB so we had to introduce it.

**Comment by annando** [comment]
I prefer having some more work outside of the query instead of having the need of some custom query. This reduces the amount of work that is needed when we support PostgreSQL as well.

**Pull request merged**
