### PR TITLE
add composer autoloader and empty folder for friendica classes

### PR DESCRIPTION
**Pull request by fabrixxm**
This pull request is mostly to start a discussion on start develop on Friendica 4

It adds Composer, configured to load future Friendica-related classes from `friendica/` as `\Friendica` namespace (following [PSR-4](http://www.php-fig.org/psr/psr-4/) specs). `vendor/` folder is included in git, to ease deploy and release (as already discussed on friendica). As per [Composer FAQ about adding `vendor\` to VCS](https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md), `"preferred-install"` is set to `"dist"`, and any `.git` folder under `vendor/` will be ignored by git.

The autoloader is included at the start of `boot.php`.

The structure of classes under `\Friendica` has to be discussed.

A initial work could be move what's possible out of `library\`, add them to composer.json as requirements and update the core accordantly.

### CODE REVIEW

**Comment by annando** [comment]
Have you checked whether /friendica can still be called?

**Comment by fabrixxm** [comment]
No, you're right. The folder name must be changed...

Il 04 gennaio 2015 12:32:33 CET, Michael Vogel <notifications@github.com> ha scritto:
>Have you checked whether /friendica can still be called?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/friendica/friendica/pull/1278#issuecomment-68629725

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by fabrixxm** [comment]
what about `app/` ?

**Comment by annando** [comment]
I'm not sure about the meaning of this directory. That means I cannot really decide what the name stands for.

**Comment by tobiasd** [comment]
Can this be merged now?

**Comment by fabrixxm** [comment]
Absolutely no :-) I've meet @Beanow yesterday and we talked about this. He has some comments to add to this dicussion

**Comment by Beanow** [comment]
First these points. On my phone so may not be all points.

1. The PSR-4 folder should be `/src` this is industry standard.
2. The namespace should be `Friendica/Friendica` to follow `<vendor>/<package>` standard.
3. The `/vendor` folder should not be commited to git, so .gitignore this.
4. To allow install without composer we should make an automatic script that force commits `/vendor` before new stable release, to allow the dependencies to be inside the zip archives. Maybe using travis.ci.

This means all people pulling develop branch should update composer too. But people using the master can forget about completely.

**Comment by tobiasd** [comment]
If vendor needs to be force commited, why not commit it anyway and update it on a regular basis?

**Comment by Beanow** [comment]
Because this will bloat your git repository (huge filesize increase) and will cause problems with your composer.lock file. Should only commit it for pre-packaged stable versions.

**Comment by tobiasd** [comment]
Which blows up the git repository then - I'm missing one crucial point here. Just don't know which.

**Comment by Beanow** [comment]
People who pull the develop branch with git automatically, should update their cronjob to run composer too. Thats the only change for users here. So we should add documentation about this. Maybe with a bash script to do this.

**Comment by tobiasd** [comment]
Still, when the release branch is merged into master once testing is over the /vendor content is in master and hence is merged into develop. So why point 3 if with 4 it gets in there anyway?

**Comment by Beanow** [comment]
It can be removed again before merging back. Or if it is a big problem have a seperate repo that has the vendor already downloaded. If it was acceptable to install with composer it would be best never to commit it, but some users dont have shell access or wont know how.

**Comment by tobiasd** [comment]
o.O sounds ridiculous complicated for me, but I wont manage the release/master/develop branches, so I wont forget a step in the process..

**Comment by Beanow** [comment]
I think we should let something like travis.ci take care of this automatically so we *can't* forget this.

**Comment by tobiasd** [comment]
What happens with people running git stable version? So taking the big "DOWNLOAD ZIP" button and not clicking through the last tagged version zip archive?

**Comment by fabrixxm** [comment]
The idea is to not have vendor folder in develop and commit it (hopefully automatically) into master on release

**Comment by annando** [comment]
This all sounds really complicated in my ears. I really hope that there are benefits from doing it that way ...

**Comment by Beanow** [comment]
Advantage is that people automatically pulling the master as well as people using the DOWNLOAD ZIP button will be able to use Friendica without composer.

The advantage for developers is that we can finally get rid of the horrible addon and themes structure, and get much better code structure in the Friendica core.

**Comment by tobiasd** [comment]
Ok, so the folder is removed only when merging master back into devel. I got the order wrong from the other postings.

What has the vendor folder to do with addons? The idea of an addon is, that it needs core as a plattform but ships with everything else needed. Get the zip file of the addon you want, put them into a directory and be happy.

Still I don't see what the benefit there is, keeping the files in vendor out of the develop branch. Say there is an update in one of composer components and the developer updates vendor. Why not commit them? Just to keep the git-log free from entries like "updated composer components"? But instead having one entry in the log about the update and one for the removal.

**Comment by Beanow** [comment]
You do not need to commit updates in your `/vendor` because everything in that folder is either auto-generated or already a git repository. Someone else already committed this change for you. And you don't need to share these changes because everyone can do a `composer update` and will have the changes. (Composer update will internally do a `git pull` for all your dependencies).

You should not commit them because every single file in `/vendor` is already a git repository managed by someone else. There may be hundreds of files and for each of them we will keep a duplicate history *forever* if we commit them. This causes a lot of bloat in your git repository. Secondly it breaks Composer, because it expects these vendor files to be git repositories it can update automatically. If you were to pull new changes in from the friendica repo, git will see this as uncommited changes for those repositories and prevent Composer from performing these `git pull` commands on dependencies.

The *best* way of doing this would be to never commit `/vendor` at all. But that would "break" the ZIP file and sites of people who pull the master with a cronjob. Requiring them to use Composer.
So I think the best alternative is to only commit once to the master for each release and remove immediately after. This will still cause a lot of bloat and some complexity, but it is backward-compatible to how people use the Friendica repo.

A last alternative I can think of would be, *never* commit vendor in the Friendica/Friendia repo and make a new repo called Friendica/FriendicaBundle and commit stable versions + vendor in there.
People would need to switch repositories, but it would keep the main repository free of bloat and complexity.

**Comment by tobiasd** [comment]
Now the explanation makes some sense. Thanks!

**Pull request closed without merging**
