### PR TITLE
Item: New fields for author id and owner id - avatar improvement with relocation

### PR DESCRIPTION
**Pull request by annando**
The item table ans the thread table now are having two more fields. They link to the contact table with "uid=0". These contacts are automatically created. There are issues with mail contacts but I want to have a look at it at some time in the future, not now. (The whole mail handling should be revised)

The item queries are standardized a bit further. Only the item queries in the api still need to be changed. But this will be done later.

The dfrn relocation now transmit the avatar field as well and the photo and thumb field is now generated by the standard routine for that.

**Some warning:**

The adding of the new fields in the item table can take much time. On my machine this lasted more than an hour. In that time the frontend will not work correctly. We should keep this in mind for the release notes. There we should advise administrators from larger servers that they should shut down the web server and the cron process to remove some stress from the database and to avoid that item entries can't be created during that time period.

### CODE REVIEW

**Comment by fabrixxm** [comment]
Any comments?

**Comment by tobiasd** [comment]
Issue a strong warning after merging it at the developers / support forum so everyone knows it and remember to mention it in the release notes.

**Comment by annando** [comment]
I can write the warning after someone accepted the pull request :-)

**Comment by rabuzarus** [comment]
Ahhhh I have forgot this totally.
@annando can you please add the docu for this in https://github.com/friendica/friendica/blob/develop/doc/database/db_item.md
&
https://github.com/friendica/friendica/blob/develop/doc/database/db_thread.md

**Comment by annando** [comment]
Will come with the upcoming pull request.

**Pull request merged**
