### PR TITLE
[frio] Rework hovercard actions

### LINKED ISSUE #7740: [frio] Follow button affected by whether they follow me
### Expected behavior

 - I am not following a user
 - When I tap the user's avatar on mobile, the popup has the follow button (head-and-shoulders and plus)

### Actual behavior

 - I am not following a user
 - When I tap the user's avatar on mobile, the popup has the follow button only if the user is not following me

### Friendica version you encountered the problem

`This is Friendica, version 2019.12-dev that is running at the web location https://libranet.de. The database version is 1323, the post update version is 1322.`

The theme is Frio.

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #7740 
Part of #4090 

For this PR, I reworked the whole hovercard module and decided against continuing to use jSmart to maybe save milliseconds on the asynchronous hovercard requests. The new module is leaner and more straighforward and a baked-in library has been removed with extreme prejudice.

> +260 -7,339 

You're welcome.

### CODE REVIEW

**Comment by annando** [comment]
it would be great if you could find a way to call the hovercard for example with clicking on the contact avatar. This would be great for accessibility and usability for mobile devices like tablets.

**Comment by MrPetovan** [comment]
Instead of going to the remote profile then?

**Comment by AlfredSK** [comment]
Well, on mobile devices I can tap on the avatar to open the hovercard.
Apart from that I would like to see the change to a click action.

**Comment by MrPetovan** [comment]
On iOS the `hover` is inconsistent and never works on avatars, so it would be an improvement.

**Comment by annando** [comment]
I would keep the regular behaviour with the link behind the name. But the link behind the avatar is redundant. So we can use it for that action, I think.

**Comment by MrPetovan** [comment]
I'd like to ask a larger proportion of Friendica users, what forum is the best for that? Friendica Support or?

**Comment by annando** [comment]
I would suggest the support forum.

**Comment by MrPetovan** [comment]
Started a discussion: https://forum.friendi.ca/display/735a2029-125d-a8fb-7d87-1e2787515689

**Comment by annando** [comment]
How do we continue with this PR?

**Comment by MrPetovan** [comment]
A majority of people voted for a click on the avatar to bring up the hovercard, so I have to implement it now.

**Comment by MrPetovan** [comment]
Here's the result, on hover a down chevron appears to indicates the click interaction, and the hovercard eventually appears on click or tap on mobile.
friendica-click-card

**Comment by AlfredSK** [comment]
Is this ready to be merged? \*cough*

**Comment by MrPetovan** [comment]
I assumed it's going to be looked at during this week-end's hackathon, that's why I didn't push the issue after two days of inactivity.

**Comment by AlfredSK** [comment]
OK. I thought only the multi-profile-PR was kind of controversial.

**Comment by MrPetovan** [comment]
I think so too, but Michael may be saving this for this week-end when it's going to be Friendica all-day both days.

**Comment by annando** [comment]
I would hope that @nupplaphil could have a look at it, but I don't know if he has got time.

**Comment by nupplaphil** [comment]
Ok

**Comment by nupplaphil** [comment]
@MrPetovan plz rebase so we can check if travis is fixed now.
The rest looks good to me.

**Comment by MrPetovan** [comment]
Done.

**Comment by MrPetovan** [comment]
Error 502 from git.friendi.ca

**Comment by annando** [comment]
See https://forum.friendi.ca/display/e18176ef-135d-bd99-3343-f9f253421542

**Comment by AlfredSK** [comment]
Btw. git.friendi.ca is up again.
(sorry for my impatience) 😁

**Pull request merged**
