### PR TITLE
Use OCR to fetch text in images

### PR DESCRIPTION
**Pull request by annando**
Sadly people tend to put text in images without providing a picture description which is bad for accessibility. Also of course the language detection fails on such posts, when the posts don't contain any other text.

The admin has to install Tesseract OCR on the system and has to enable the detection in the configuration.

### CODE REVIEW

**Comment by MrPetovan** [comment]
I would suggest to use an addon for an optional feature based on a third-party software.

**Comment by annando** [comment]
I thought about this, but decided against it. One thing was, that I was unable to manage this whole vendor thingy in an addon. But the main problem was the better integration into the system.

**Comment by MrPetovan** [comment]
I can help you with both of these. Composer stuff is the same as with the regular Friendica setup, just in a different folder. As for the integration, this is the perfect job for a new hook.

**Comment by annando** [comment]
I changed it. But I cannot easily switch branches at the moment, so I wasn't able to test it.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
