### PR TITLE
Issue 11566: More detailled notification configuration

### LINKED ISSUE #11566: Create option to hide comment notifications on liked posts
### Is the feature request related to a problem? 
There is a notification whenever someone comments on a liked/upvoted post. Users should be able to disable these kinds of notifications

### Describe alternatives you've considered
Alternatively there could be an option to disable these notifications for single posts

### Additional context

### PR DESCRIPTION
**Pull request by annando**
Fixes #11566

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by AlfredSK** [comment]
I just pulled the latest update. My notifications are missing now. I only see one notification from 6 days ago. 🤔

Screenshot_20220605-153054

**Comment by annando** [comment]
@AlfredSK can you have a look into the notification settings?

**Comment by tobiasd** [comment]
Is it possible, that this had broken the notification about postings from certain account (not forums). So far that still worked on my node x) but I just saw a posting that I was not informed about.

**Comment by annando** [comment]
Yes. Fixed by https://github.com/friendica/friendica/pull/11609

**Pull request merged**
