### PR TITLE
Return 400 error code on malformed request.

### LINKED ISSUE #14281: Badly-formed webfinger requests should return 400
- [X] I have searched open and closed issues for duplicates

### Bug Description

It is a technicality but: according to the webfinger spec section 4.2, "If the resource parameter is absent or malformed, the WebFinger resource MUST indicate that the request is bad as per Section 10.4.1 of RFC 616."  Following that up, section 10.4.1 is a response code of 400.  In fact, Friendica returns 404.

### Steps to Reproduce

1.  request malformed URL including two equals signs:

```
curl -v "Mozilla" "https://friends.holograms.test/.well-known/webfinger?resource==acct:jem@friends.holograms.test"
```

Actual Result:

Return code is 404

Expected Result:

Return code is 400

### Platform Info

Friendica Version: 2024.06-dev

Friendica Source: git

PHP version: 8.2

SQL version: 10.11.8

### PR DESCRIPTION
**Pull request by mexon**
Fixes #14281

### CODE REVIEW

**Comment by mexon** [comment]
I guess this might well break some things.  Are people querying webfinger for terms that are not URLs or `acct` URIs for some reason?

**Comment by mexon** [comment]
> I guess this might well break some things. Are people querying webfinger for terms that are not URLs or `acct` URIs for some reason?

OK, turns out that's part of the spec too, it has to accept all URI schemes.  Modified by regex search according to the URI scheme spec, RFC 2396.

**Comment by annando** [comment]
Have you changed the target because of doubts about the impact?

**Comment by mexon** [comment]
@annando basically yes.  I assume that somewhere in the background people are hard at work on releasing 2024-06, and I wouldn't want to disrupt that unless the change is important.  This change just ticks a box on a compatibility report.  Even with my second change, it's conceivable it might disrupt something.  So I think it belongs in the future release.

**Pull request merged**
