### PR TITLE
Improve the speed for blurhash generation 

### PR DESCRIPTION
**Pull request by annando**
`clone` is much faster, especially with large pictures.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by sekretaerbaer** [comment]
After importing this commit, it was no longer possible to upload images.

**Comment by MrPetovan** [comment]
@sekretaerbaer Thank you for the report, do you have any log (Friendica, PHP, Web server) associated with these failures?

**Comment by sekretaerbaer** [comment]
@MrPetovan No unfortunately I have not found anything in the logs.

**Comment by annando** [comment]
I have the same problem, so `clone` does seem to have side effects.

**Pull request merged**
