### PR TITLE
Use OSM to render locations

### LINKED ISSUE #1705: Allow nodes to be configured to render location using openstreetmap
It isn't nice for a free software federated social software to rely on a proprietary SaaS to render locations. It would be better to use the community powered opendata providing crowdsourced planet map instead: http://www.openstreetmap.org

It should likely be the default, eventually with node configuration allowing for changing it.

### PR DESCRIPTION
**Pull request by strk**
Closes #1705 
Makes the code use a "render_location" function so to eventually add configuration to it

### CODE REVIEW

**Comment by fabrixxm** [comment]
This is a duplication of some of the work that [openstreetmap addon](https://github.com/friendica/friendica-addons/tree/master/openstreetmap) does.
I'm for remove default behavior from core and leave all to addon, or move all openstreetmap addon functionality into core and remove the  addon.

**Comment by strk** [comment]
Agreed. For sure the OSM plugin is more advanced (at least it does have some configuration).
As long as gmaps is removed from core and an OSM map can be enabled by admins I'm happy.

**Comment by strk** [comment]
Addons have no issue tracker on their own ? I saw there's only PR ?

**Comment by fabrixxm** [comment]
We are using this issue tracker also for addons

**Comment by fabrixxm** [comment]
@strk would you like to improve this patch, maybe with a default behavior that does nothing?

**Comment by strk** [comment]
How would a default doing nothing help ?
Why not merging this patch in as a first step,
then maybe move the hook calling machinery inside the "render_location"
to allow completely replacing the rendered text ? (I hadn't looked
at how those external plugins/hook work).

**Comment by annando** [comment]
I guess that there are people outside who want to use Google as a map provider. (Depending on the location, OSM is more or less accurate).

I'm fully with @fabrixxm. I would suggest that you had a look at the OSM addon and would write a Google Maps addon. Then we could remove the Google code out of the core. The addons are really easy to handle, especially when there is an existing one that nearly does the same.

**Comment by strk** [comment]
Me, writing a Google Maps addon ?
Maybe you didn't get what moved me in the first place.
I hated a free software package advertising a non-free software service.
Personally I don't plan to do any more work here. If my PR won't be merged
I'll be using the OSM plugin and eventually improve that one if needed.

**Comment by annando** [comment]
I understand why you made these changes and I really understand them. Thing is: With this change we would remove functionality that some persons would want. So I think we have to offer them a way to regain the functionality (while hoping, that OSM serves their needs as well).

It's the same reason why I invested much work in the Facebook addons. I really don't need it - but I know that there are people who use it.

**Comment by strk** [comment]
No functionality is removed. Functionality is actually _added_
as you are still taken to a map, but to a map you can _fix_ and _download_
freely.

I see your point, but have no time to spend there.
Feel free to close this PR, or adapt it if anything seems useful

**Pull request closed without merging**
