### PR TITLE
frio: Remove contacts autocomplete

### LINKED ISSUE #4923: frio: search in /contacts doesn't work for username
### Expected behavior
search for username like myname@domain.tld should find the `myusername`
Dosn't work in frio, but works in vier

### Actual behavior
only works with the users first- and lastname.

### Steps to reproduce the problem
Just use the search.

Problem with all that is, that some ☇☈☋♐⚔ people are using symbols instead of characters, then you can't find them via search and you have to scroll all of your contacts.

### tec
Friendica version: 2018-05-dev
Friendica source: git
PHP version: 7.0
SQL version: mariadb

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #4923

### CODE REVIEW

**Comment by annando** [comment]
Wouldn't it be better to improve the auto completion instead of removing it?

**Comment by MrPetovan** [comment]
Like I said in the linked issue, I already gave it a shot, and it still doesn't show as many accounts as the regular search that's working perfectly.

Furthermore, this autocomplete provides no real benefit since it already is a search field, and gives confusingly few results compared to the real search that works even worse (no enter key interaction in the search fields).

**Comment by annando** [comment]
I do like the idea behind this, but I agree that currently it confuses more than it helps. But as a reminder I would like to keep the code with some ```@todo``` telling to enable it, when eventually the search results would be identical.

**Comment by MrPetovan** [comment]
What is the idea you like? Autocomplete’s idea is to provide a mini-search page in an otherwise completely different context. Searching for contacts to mentions during post edition is a good example. Searching for contacts on the contact list page isn’t.

**Comment by annando** [comment]
It is a good preview to check whether the system will find something - and how much. (Not in the current state of course)

**Comment by MrPetovan** [comment]
The same feature is just 1 click/keypress away on the same page and with the same expected display.

**Comment by annando** [comment]
Yeah, it is one additional click and not interactive. That's a massive difference in usability. This interactive search does help in guessing how exactly the name had been.

It's the same with the system I'm working at when I'm earning my money. We do have an option to do a search while typing. We tell our customers that this will decrease performance and that they shouldn't set this. Until now, every customer activated it.

**Comment by MrPetovan** [comment]
I mean, if it was working correctly, we wouldn't be talking about it. But currently it isn't worth spending time fixing it for so little discernable gain.

**Comment by rabuzarus** [comment]
> Searching for contacts on the contact list page isn’t. It already is a search page!

Yes, but the other search reloads the page. To have a quick filter while typing the name is more comfortable

**Comment by annando** [comment]
Since it isn't working correctly at the moment, I would deactivate it and add a to-do. So we can have a look at it later.

**Comment by MrPetovan** [comment]
Cancelled by #5210

**Pull request closed without merging**
