### PR TITLE
Merge `2024.09-rc` into `develop`

### PR DESCRIPTION
**Pull request by Art4**
This PR merges the `2024.09-rc` into `develop`.

### CODE REVIEW

**Comment by Art4** [comment]
@MrPetovan @nupplaphil I'm not sure how to fix the failing woodpecker code_standards_check workflow, see https://ci.friendi.ca/repos/2/pipeline/2872/14

The check step uses the `friendicaci/php-cs` image with PHP 8.4, but I cannot find any information about this image. Where does it come from and how can I check it?

@annando Please take a look at the commits ae2b6e3bb7284189d9d0503448538d557391a247 and b1d78e34dbb0c31815b0f38d483285ce3373f968, if this changes fixed the PHPStan errors from upstream in a correct way.

**Comment by nupplaphil** [comment]
Ups... My fault with the php-cs check, I updated it yesterday, will fix it at evening

**Comment by Art4** [comment]
@nupplaphil As alternative we could update PHP-CS-Fixer. Is the code for the docker images publicly available? I'd like to know why we need a special docker image only to check the code style.

**Comment by nupplaphil** [comment]
> @nupplaphil As alternative we could update PHP-CS-Fixer. Is the code for the docker images publicly available? I'd like to know why we need a special docker image only to check the code style.

https://git.friendi.ca/friendica/friendica-docker-ci

I centralized all CI container into this repository

Everyone can change, yet currently I'm the only owner of the https://hub.docker.com/?namespace=friendicaci so I'm the only one who can push new container for the `friendicaci` namespace.

I'd love to have more than me, but there was no one with Docker experience when I created them

**Comment by Art4** [comment]
Thank you. Do you know why I cannot see any docker images on https://hub.docker.com/?namespace=friendicaci ?

Personally I would tend to keep the docker code in the main repository but thats ok too I think. If some days I have an activated account on git.friendi.ca I could help you maintaining the repo. :smile:

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
