### PR TITLE
Move mod/register to Module\Register

### LINKED ISSUE #6334: Fatal error and warnings after last git pull
Three issues found in PHP log after PR #6333 (probably related to a previous PR).

- [ ] fatal error in DBA.php
````
PHP Fatal error:  Uncaught Error: Call to undefined function Friendica\Database\get_app() in /var/www/html/libranet/src/Database/DBA.php:391
Stack trace:
#0 /var/www/html/libranet/src/Database/DBA.php(285): Friendica\Database\DBA::p('SELECT 1')
#1 /var/www/html/libranet/src/App/Mode.php(63): Friendica\Database\DBA::connected()
#2 /var/www/html/libranet/src/App.php(306): Friendica\App\Mode->determine('/var/www/html/l...')
#3 /var/www/html/libranet/src/App.php(184): Friendica\App->reload()
#4 /var/www/html/libranet/index.php(11): Friendica\App->__construct('/var/www/html/l...', false)
#5 {main}
  thrown in /var/www/html/libranet/src/Database/DBA.php on line 391
````

- [ ] warning in settings.config.php
````
PHP Warning:  Use of undefined constant REGISTER_CLOSED - assumed 'REGISTER_CLOSED' (this will throw an Error in a
future version of PHP) in /var/www/html/libranet/config/settings.config.php on line 22
````

- [ ] warning in items.php
````
PHP Warning:  preg_replace(): Compilation failed: missing ) at offset 82 in /var/www/html/libranet/include/items.php on line
207
````

### Friendica version you encountered the problem
2018.12-rc 

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #4090

It is one of those PR when I went the extra mile to make sure that we won't have any more problems with the "REGISTER_*" constants. This meant *cough* moving the whole register module to `src/` *cough*.

Related Addon PR: https://github.com/friendica/friendica-addons/pull/786

### CODE REVIEW

**Comment by MrPetovan** [comment]
This now fixes a previously unreported bug with infinite scroll where the network filter wouldn't be honored because the infinite scroll URL was wrongly escaped.

**Comment by JeroenED** [comment]
This will break many nodes (including mine) as REGISTER_* is in many node_configurations as a constant. I would suggest pushing to develop instead of 2018.12-rc. Or do I see something wrong?

**Comment by MrPetovan** [comment]
Conflicts fixed.

**Comment by JeroenED** [comment]
Just to make sure I'm understanding correctly: the REGISTER_* constants are staying, but in config it's better to use the same constants as strings as they have always been translated and translation now translates to the module variables?

**Comment by MrPetovan** [comment]
There are two distinct uses of `REGISTER_*`:
1. As a node local config value `config.register_policy`. This value is either 0, 1 or 2 to determine the site's behavior, and since it isn't human-readable, instead we use `REGISTER_OPEN`, `REGISTER_APPROVE` and `REGISTER_CLOSED` constants, initially global constants but now class constants.
2. As a node info value `register_policy`. This value is either `'REGISTER_OPEN'`, `'REGISTER_APPROVE'`, `'REGISTER_INVITE'` or `'REGISTER_CLOSED'` and is only present in the output of `/friendica/json`. Friendica outputs those values based of the above config value and stores the info about remote nodes back to 0, 1 or 2 as well.

I only changed 1., while 2. stays the same: constant integer values are still converted back to string values and vice-versa when putting out the node info and probing remote nodes.

**Comment by annando** [comment]
Why have you closed this issue? I finally have got the time, since I'm ill at home.

**Comment by fabrixxm** [comment]
Yet, imho, all of this (starting with ed7bada71  in #6315) should had been merged in develop.
And why including "boot.php" in index.php had been removed?
I mean, I understand why, but maybe it's a little too much for a rc branch? Everything broke pulling now the rc...

**Comment by fabrixxm** [comment]
Yet, imho, all of this (starting with #6315) should had been merged in develop.
And why including "boot.php" in index.php had been removed?
I mean, I understand why, but maybe it's a little too much for a rc branch? Everything broke pulling now the rc...

**Comment by MrPetovan** [comment]
> Why have you closed this issue? I finally have got the time, since I'm ill at home.

RC branch name change.

**Comment by MrPetovan** [comment]
@fabrixxm Can you be more specific about the issues you encountered?

**Comment by fabrixxm** [comment]
Notice: Use of undefined constant REGISTER_CLOSED - assumed 'REGISTER_CLOSED' in /vagrant/config/settings.config.php on line 22
    Fatal error: Uncaught Error: Call to undefined function Friendica\Database\get_app() in /vagrant/src/Database/DBA.php on line 391

if I add 

```php
include __DIR__ . '/boot.php';
```

to index.php, I get

    Fatal error: Uncaught Error: Call to undefined function posted_date_widget() in /vagrant/mod/network.php on line 157

on /network, or

    Fatal error: Uncaught Error: Call to undefined function q() in /vagrant/view/theme/frio/theme.php on line 246
on /settings

looks like most of the error are from removed includes.
Again, I'm not against this, of course. Just it looks too much for a branch that should be "almost ready to be released"...

**Comment by MrPetovan** [comment]
Thanks, it sounds like it isn't ready for RC merge indeed, I'll cherry-pick the relevant commit into a branch for the RC.

**Comment by fabrixxm** [comment]
note that I have those issues running current `2019.01-rc` branch

**Comment by MrPetovan** [comment]
A lighter PR is available for the RC: #6372

**Comment by MrPetovan** [comment]
Conflicts fixed.

**Comment by annando** [comment]
I guess I would prefer having this merged after it had been running on some system for some days.

**Comment by JeroenED** [comment]
@Annando Big or Small nodes? I want to volunteer 😉

**Comment by MrPetovan** [comment]
Small node is ideal, you have to test registration under the different modes. Do you know how to checkout my branch?

**Comment by JeroenED** [comment]
So test if a new user can register from open, approve and invitation?

Checking out the branch now 😉

**Comment by MrPetovan** [comment]
And test a user can't register with closed registration policy.

**Comment by JeroenED** [comment]
Test results:
Open: No issue (jeroened1@social.jeroened.be registered)
Approval: No direct issue, however mail to admin came in multiple times (jeroened2 and jeroened3)
Closed: user cannot register, no issue
Closed  + invitation only: invitation email received with invitation code but without link to registration page, registration page unavailable.

**Comment by MrPetovan** [comment]
Thanks for the tests, can you please paste the invitation email here?

**Comment by JeroenED** [comment]
````
Ik nodig je vriendelijk uit om bij mij en andere vrienden te komen op Friendica - en ons te helpen om een beter sociaal web te bouwen.

Bezoek https://dir.libranet.de/servers voor een lijst van openbare sites waar je je kunt aansluiten. Friendica leden op andere sites kunnen allemaal met elkaar verbonden worden, en ook met leden van verschillende andere sociale netwerken.

Je zult deze uitnodigingscode moeten invullen: zaishien

Eens je geregistreerd bent kun je contact leggen met mij via mijn profielpagina op:

https://social.jeroened.be/profile/jeroened

Voor meer informatie over het Friendica project en waarom wij denken dat het belangrijk is kun je http://friendi.ca/ bezoeken
````

**Comment by annando** [comment]
Yeah, conflicts ;-)

**Comment by MrPetovan** [comment]
@JeroenED Regarding the invitation issue: the invitation config is parallel to the registration policy, here's the meaning of setting `confg.invitation_only` with the different policies:
- `Register::OPEN`: People are invited to register on this node or on any other node if `system.directory` is set. `/friendica/json` shows `REGISTRATION_INVITE`.
- `Register::APPROVAL` : People are invited to register on this node or on any other node if `system.directory` is set. `/friendica/json` shows `REGISTRATION_APPROVAL` (should be changed to `REGISTRATION_INVITE`).
- `Register::CLOSED`: People are invited to register on an other node if `system.directory` is set or told to bugger off. `/friendica/json` shows `REGISTRATION_CLOSED`.

So the email you got was right, but the `/friendica/json` output has to be fixed. Especially since the directory is using `REGISTER_APPROVAL` to show public servers while `REGISTER_INVITE` is treated as `REGISTER_CLOSED` for the purpose of the directory.

**Pull request merged**
