### PR TITLE
Fixing templates - unescaping it again

### PR DESCRIPTION
**Pull request by annando**
Follow up to https://github.com/friendica/friendica/pull/6262

### CODE REVIEW

**Comment by AlfredSK** [comment]
Thanks! There are even more places that are broken now.

Header of posts (display of location):

````
Steffen K9 🐰  	
3 days ago from libranet.de
(<a target="map" title="Halle (Saale)" href= "https://nominatim.openstreetmap.org/search?q=Halle+%28Saale%29">Halle (Saale)</a>)
````

Looks like the corresponding Addon PR needs a fix too.

Also, I just made a test installation with the latest RC code and I had some more template issues....

Selecting the timezone:

bildschirmfoto von 2018-12-20 22-27-54

Installation finished:

bildschirmfoto von 2018-12-20 22-28-36

Registering the first user (admin):

bildschirmfoto von 2018-12-20 22-33-51

The good news is the installation worked nonetheless. :-)

**Comment by AlfredSK** [comment]
And another one (advanced profile/contact info):

bildschirmfoto von 2018-12-21 00-15-49

**Comment by MrPetovan** [comment]
Thank you for the reports, they are invaluable and wouldn't have been possible without merging this in the first place.

**Comment by MrPetovan** [comment]
Part of #6208

**Pull request merged**
