### PR TITLE
 old boot.php functions replaced in /mod

### PR DESCRIPTION
**Pull request by annando**
All functions from the boot.php are removed in /mod

### CODE REVIEW

**Comment by MrPetovan** [comment]
154 files? Oh man!

Also please rebase your branch onto the latest `develop` to fix the conflicts.

**Comment by annando** [comment]
I hope that this change wasn't too early and that @nupplaphil hasn't already prepared the new class for these functions. This was some quick "search & replace" task while watching some magic show :-)

**Comment by MrPetovan** [comment]
Can you pease split this PR in three chunks with the removal of the boot.php file in the last one?

**Comment by annando** [comment]
I understand the need for splitting, since the pipeline is really struggling. Only problem: How can I split it in an easy way?

**Comment by MrPetovan** [comment]
You can reset your branch to the parent commit and keeping your changes (`git reset --soft HEAD^`) and you only add the files from a specific sub-folder (`git add src`) before committing again. This will require you to `git push --force`. Then once the PR is merged, you can add a few more folders, create a new PR, and finally the rest of the folders and the removal of the `boot.php` file.

**Comment by annando** [comment]
I'm too tired today. I will have a look at it tomorrow and then hopefully understand all steps. By now I simply want to make all the tests happy. That is some task that I can do with most of my braincells already felt asleep.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
