### PR TITLE
Babel: Support tweet URL

### PR DESCRIPTION
**Pull request by MrPetovan**
Depends on https://github.com/friendica/friendica-addons/pull/1080

Highly experimental feature, absolutely no error catching, here be dragons.

### CODE REVIEW

**Comment by annando** [comment]
Tested or untested?

**Comment by MrPetovan** [comment]
Tested with a successful case:
- A Twitter tweet URL
- The tweet exists
- The twitter addon is correctly set up

It was pivotal in solving https://github.com/friendica/friendica/pull/9915, and I may need it in the future, but since it's a debug tool I didn't want to spend that long making sure all the negative cases are gracefully handled.

**Comment by annando** [comment]
I will have a look at the open PRs this evening. At the weekend I had been busy watching the FOSDEM and needed some time to recreate.

P.S.: Is there any merge order?

**Comment by MrPetovan** [comment]
Nope, all are independent unless explicitly written (like this one depending on https://github.com/friendica/friendica-addons/pull/1080)

**Comment by MrPetovan** [comment]
Please don't forget about https://github.com/friendica/friendica-addons/pull/1080 this PR depends on.

**Pull request merged**
