### PR TITLE
Update composer

### PR DESCRIPTION
**Pull request by MrPetovan**
Someone had to do it, I did it.

I updated all the Composer dependencies, and I checked each version diff by hand.

Furthermore, I managed to update the dependencies using a standalone version of PHP 5 so that we keep using the relevant dependency versions to maintain the out of the box PHP 5 compatibility.

### CODE REVIEW

**Comment by tobiasd** [comment]
Any idea regarding the failing Travis checks?

**Comment by annando** [comment]
Don't the check fail because of the configuration of our own git server?

**Comment by annando** [comment]
Does this - in any way - affect the PHP5 compatibility?

**Comment by AlfredSK** [comment]
````fatal: unable to access 'https://git.friendi.ca/friendica/php-json-ld/': gnutls_handshake() failed: Handshake failed````
There was a discussion about this in the huge ActivityPub PR.

**Comment by MrPetovan** [comment]
> Any idea regarding the failing Travis checks?

This is because Travis server uses an obsolete version of the GNU TLS that doesn't support TLS 1.2, and the `git.friendi.ca` SSL certificate only allows TLS 1.2.

> Does this - in any way - affect the PHP5 compatibility?

I did what I could to prevent dependencies upgrade from inadvertently bumping the required PHP version. But I'm not running PHP 5, so I'll need feedback from the cave people still using it. We can revert if it goes wrong.

**Comment by annando** [comment]
AFAIK @rabuzarus is still using it, so we can merge it and he reports if something fails?

**Pull request merged**
