### PR TITLE
Bump minimum required PHP version to 7.3

### PR DESCRIPTION
**Pull request by MrPetovan**
Address https://github.com/friendica/friendica/issues/10996#issuecomment-974057500
Address https://github.com/friendica/friendica/issues/10757#issuecomment-972870356

This requirement was unknowingly introduced by @fabrixxm in #10309

### CODE REVIEW

**Comment by nupplaphil** [comment]
Are the other updates intended?

**Comment by fabrixxm** [comment]
Oh I'm sorry... should I patch to make it work on currently supported php?

**Comment by MrPetovan** [comment]
> Are the other updates intended?

What do you mean "other updates"? Do you mean the Composer dependencies updates? They are in a separate commit so yes. Since we bumped the minimum require PHP version, it also increases the PHP version we are matching the dependencies against when updating them so it justified running the `composer update` process to get dependencies more closely matching our environment.

We also are in an RC which means I run the `composer update` command before the release so I merged both occasions.

> Oh I'm sorry... should I patch to make it work on currently supported php?

I thought about that but PHP 7.2 has been unsupported for almost a year now so it's as good an incentive as another to encourage Friendica admins to upgrade.

**Comment by tobiasd** [comment]
And even Debian Oldstable has PHP7.3 support from the main package repositories 😉

**Pull request merged**
