### PR TITLE
console po2php: Use Geekwright\Po for po file parsing to catch corner case with multi-line message

### LINKED ISSUE #10832: bin/console po2php unable to extract some strings
### Bug Description

I've noticed in https://github.com/friendica/friendica-addons/pull/1183 that the `bin/console po2php` command is unable to extract the following string from the `$lng/messages.po` file.

```
#: nitter.php:99
#, php-format
msgid ""
"In an attempt to protect your privacy, links to Twitter in this posting were"
" replaced by links to the Nitter instance at %s"
msgstr ""
"A magánélet védelme érdekében az ebben a bejegyzésben lévő Twitterre mutató "
"hivatkozások a %s címen elérhető Nitter-példányára mutató hivatkozásokkal "
"lettek helyettesítve."
```

### Steps to Reproduce

1. fetch the current `$lng/messages.po` file from transifex
2. run `bin/console po2php $filename` be happy to read the success message
3. have a look at the produced `$lng/strings.php` file and miss that string entirely.

One can try this with the `addon/nitter/lang/de/messages.po`.

Actual Result:

String gets discarded.

Expected Result:

Translated string being added to the `strings.php` file.

### Platform Info

Friendica Version: 2021-12-dev ac9e5df6142fbf387a01c55f121247a0cc0baa20

Friendica Source: git 

PHP version: PHP 7.4.24 (cli)

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #10832 

@tobiasd Do you want me to regenerate all the strings files for all the languages or do you have a nifty loop script for that?

### CODE REVIEW

**Comment by annando** [comment]
@MrPetovan the checks are not happy ...

**Comment by MrPetovan** [comment]
Thanks for the tip, an extra comma in `composer.json` 😒

**Comment by annando** [comment]
Have you tested the output of that script?

**Comment by MrPetovan** [comment]
Several times during my works, first on the nitter addon and comparing with the previous output, then on the French translation in the core.

**Comment by tobiasd** [comment]
Thanks for the fix :)

**Pull request merged**
