### PR TITLE
Update htconfig.md

### PR DESCRIPTION
**Pull request by ffrek**
Just one small typo wiit is now with.

### CODE REVIEW

**Comment by tobiasd** [comment]
:+1:  If you want to have this _bugfix to the documentation_ in the upcoming release, you should make a new pull request against the **3.5rc** branch.

**Comment by annando** [comment]
@ffrek I will accept this pull request by sunday evening so it would be in the 3.5.1 version and not in the upcoming 3.5.

**Comment by ben-utzer** [comment]
No problem, it is just a typo, so nothing important. ;-)

Seems I did use the wrong account. :-)

**Comment by ben-utzer** [comment]
ok, did it again for the current RC.

**Comment by tobiasd** [comment]
I will close this PR then as the other was merged into the RC branch.

**Pull request closed without merging**
