### PR TITLE
And another weird date format

### PR DESCRIPTION
**Pull request by annando**
A never ending story :-)

### CODE REVIEW

**Review by MrPetovan — CHANGES_REQUESTED** [review]
Can you please provide an example of date string for each pattern you created so that I can write tests for this method?

**Comment by annando** [comment]
These are the ones that I used to code it:
- `Mo, 19 Sep 2022 14:51:00 +0200`
- `2020-11-21T12:00:13.745339ZZ`
- `2016-09-09T13:32:00ZZ`
- `2021-09-09T16:19:00ZZ`
- `Sun, 10/03/2021 - 12:41`
- `Mon, 09/12/2022 - 09:02`
- `4:30 PM, Sep 13, 2022`
- `August 27, 2022 - 21:00`
- `2021-09-19T14:06:03&#x2B;00:00`

**Comment by MrPetovan** [comment]
The last one is actually `2021-09-19T14:06:03+00:00` after entity decode which looks like a correct ISO date.

**Review by MrPetovan — APPROVED** [review]

**Comment by annando** [comment]
@MrPetovan Problem only is that for some weird reason the transmitter hasn't done that.

**Comment by MrPetovan** [comment]
Ugh.

**Pull request merged**
