### PR TITLE
Generalize the Compose ACL to the whole site

### LINKED ISSUE #7308: Setting permissions on posts needs more secure workflow
If you start a new post, where you want set the permission e.G. that only one or several persons can see that post, you start with this default selection and your using the search field to find the contacts you want to give permissions,, you end up writing a public post: visible for all of your contacts :(

00_temp

The workaround to not send to all your contacts, you first click on "visible for everybody" (to clean all other selections) and then you select the persons you want to give the permission.

I know this is a tricky part, but we need to solve that, because new users will have their problems to understand in the beginning and even advanced users (like me) are stumbling across that obstacle, because im not using it very often. There are 2 solutions in my mind, but maybe you have better ones?

**Solution 1** could be to add in the same line with the button "Visible to everybody" another button "Clear all permissions" (both bottons of the same size!)

**Solution 2** could be that as soon you are initially changing the permissions, the default permission gets removed and you get a visual feedback, like a red line that your default permissions are removed now. 

**Another little bug** is, that when you once used the search field on the permission window and you deleted your typed words, you won't get back the initial list of contacts and groups. You have to keep al of them in your mind.

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #7308 

Finally, the permission workflow is now unified across Friendica's modules and themes by using tags input fields. It now shows the expected permissions clearer than ever.

Tested on all themes in the network and events pages.

Pre-requisite to keep working on #7777 where permissions are needed for custom profile fields.

### CODE REVIEW

**Comment by annando** [comment]
Wow, looks like a lot of work. I just have two questions in advance:
1. Does this contain the check for the "pubmail" value like I suggested?
2. Is the window the permission window one that was already available as an option to Frio? If yes, could you quickly apply changes, if users do have problems with the new system or something important is missing?

**Comment by MrPetovan** [comment]
1. No.
2. Yes over the next three days.

**Comment by MrPetovan** [comment]
Wow, that’s it? Weee!

Please make an announcements for everyone to report issues with the new permission system.

**Comment by annando** [comment]
I would like to delegate that job to you :-) I have to prepare some offline stuff for the weekend.

**Comment by MrPetovan** [comment]
Fair enough!

**Comment by AlfredSK** [comment]
Please look at...
https://github.com/friendica/friendica/issues/7676#issuecomment-559680658

**Pull request merged**
