### PR TITLE
Improved handling of incoming posts / new activity relay

### PR DESCRIPTION
**Pull request by annando**
This PR contains several improvements for the processing and acceptance of incoming messages.

Also during the test it was clear that we need to improve the way that we relay incoming activitites for our posts. 

During that process it was possible to get rid of the "conversation" table that was one of the largest tables but served little purpose for that size.

This relaying of incoming posts is just the first step. We should decide upon the future way here in some upcoming discussion.

This PR also contains code to cover https://github.com/friendica/friendica/issues/11776

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]
I have no idea what's going on here, is this PR final or are you actively debugging with it and planning to add more changes?

**Comment by annando** [comment]
This code is running on my system now for a day (except the part I just added with processing the replies via worker). It is already really huge, so I don't want to add more stuff to it.

Means: I think it is stable enough, but surely there will be some upcoming PRs to change some stuff. (like the performance issue)

**Comment by annando** [comment]
I just added a decoupler so that the receiver is now separated from the processor via a worker task. My expectation is that this should harmonize the load of the system.

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
@annando You accidentally nuked the Item Source admin module when you removed the `conversation` table as it was entirely relying on it. Now that I want to consult an item source, what table am I supposed to query? In this PR you introduced the `post-activity` table but it's empty result for the related `uri-id` I'm searching on.

What am I supposed to do?

**Comment by annando** [comment]
The `conversation` table was a huge waste of space with barely no use, so it was removed. However, for debug reason we could possibly store all received sources in that table.

**Comment by MrPetovan** [comment]
Thankfully it was a public post, so I was able to get the source from the remote server directly, but for private posts I'd be out of luck.

**Comment by annando** [comment]
Yes. But since the `conversation` table was one of the largest tables in the whole system and was mostly only used for debugging purposes, there was not much sense in keeping it.

But it shouldn't be much of a deal to add some configuration here: https://github.com/friendica/friendica/blob/develop/src/Model/Item.php#L1333

**Comment by MrPetovan** [comment]
I don't understand what needs to be changed, isn't it already there?

**Comment by annando** [comment]
We currently only store raw data that needs to be relayed. We could add a configuration to store it at any time.

**Comment by MrPetovan** [comment]
I am not comfortable enough with that part of the code to make it happen, but this means that the Item Source page is useless for the time being.

**Comment by annando** [comment]
See PR https://github.com/friendica/friendica/pull/12140. When this is activated, the source page will fully work again.

**Pull request merged**
