### PR TITLE
Move languagedetect to vendor

### PR DESCRIPTION
**Pull request by MrPetovan**
This is a redux of #3743

The difference is that we don't use the PEAR repository to install Text_LanguageDetect but the GitHub repository. There are two main reasons motivating the change:
- The PEAR repository for Text_LanguageDetect is currently unmaintained, while the GitHub repo received updates more recently.
- PEAR interpolates some variables in the library's files during installation, which is incompatible with our current (wrong) way of committing all the dependencies in the `vendor` folder.

This PR also updates some minor versions of the dependencies.

### CODE REVIEW

**Comment by annando** [comment]
What about the add-on that is using the library? Do you have to touch this as well?

**Comment by MrPetovan** [comment]
Yep, PR incoming.

**Comment by annando** [comment]
So let's see what crashes this time :-)

**Comment by tobiasd** [comment]
> So let's see what crashes this time :-)

I was greeted by an internal error 500 this morning and checked out the state before this merge. Will try to investigate further after the boot process completed later.

**Comment by tobiasd** [comment]
Ok, it was a "false" alarm. But an update for my unofficial addon for typography will follow :-)

**Comment by Quix0r** [comment]
There is a left-over in `src/Model/Item.php`, line 28 and 1094.

**Comment by MrPetovan** [comment]
The goal of this PR wasn't to get rid of LanguageDetect.

**Comment by MrPetovan** [comment]
Ah drat, can you check your `composer.lock` and your `vendor/composer/autoload_classmap.php` files for `Text_LanguageDetect`?

**Comment by Quix0r** [comment]
`composer.lock` says `Archive_Tar`. But nothing in `./vendor/` directory.

**Comment by Quix0r** [comment]
Ah, difference. In `composer.json` there is pear/Text_LanguageDetect` but since `composer.lock` is around any changes to `composer.json` is **ignored**. You should `./bin/composer.phar update`.

**Comment by MrPetovan** [comment]
Are you running `develop` or `master`? You shouldn't have to run `bin/composer.phar update`.

**Comment by Quix0r** [comment]
`develop` as I also develop on it (smaller rewrites etc).

**Comment by Quix0r** [comment]
Getting this now:
````
  [InvalidArgumentException]                                                                                                  
  Could not find a matching version of package npm/moment. Check the package spelling, your version constraint and that the   
  package is available in a stability which matches your minimum-stability (stable).                                          
````

**Comment by MrPetovan** [comment]
I suggest:
```git checkout -- composer.json composer.lock
bin/composer.phar install```

**Comment by Quix0r** [comment]
That doesn't install `Text_LanguageDetect` here.

**Comment by MrPetovan** [comment]
Please try removing the `vendor` folder and paste the output of `bin/composer.phar install` here?

**Comment by Quix0r** [comment]
And as I said before, `composer.lock` is around, then that file rules (as it locks to specific versions/commit ids) and all changes in `composer.json` is being **ignored**.

Okay, will paste it.

**Comment by Quix0r** [comment]
````
$ ./bin/composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 39 installs, 0 updates, 0 removals
  - Installing fxp/composer-asset-plugin (v1.4.2): Loading from cache
  - Installing asika/simple-console (1.0.3): Loading from cache
  - Installing bower-asset/chart-js (v2.7.1): Loading from cache
  - Installing bower-asset/base64 (1.0.1): Loading from cache
  - Installing bower-asset/perfect-scrollbar (0.6.16): Loading from cache
  - Installing bower-asset/vue (v2.5.16): Loading from cache
  - Installing rapidwebltd/rw-file-cache (v1.2.5): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing rapidwebltd/rw-file-cache-psr-6 (v1.0.0): Loading from cache
  - Installing paragonie/random_compat (v2.0.11): Loading from cache
  - Installing paragonie/sodium_compat (v1.6.0): Loading from cache
  - Installing paragonie/constant_time_encoding (v1.0.2): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.0): Loading from cache
  - Installing paragonie/certainty (v1.0.2): Loading from cache
  - Installing divineomega/password_exposed (v2.5.1): Loading from cache
  - Installing ezyang/htmlpurifier (v4.7.0): Loading from cache
  - Installing league/html-to-markdown (4.4.1): Loading from cache
  - Installing lightopenid/lightopenid (dev-master 9d42dc2): Loading from cache
  - Installing michelf/php-markdown (1.8.0): Loading from cache
  - Installing mobiledetect/mobiledetectlib (2.8.30): Loading from cache
  - Installing npm-asset/cropperjs (1.2.2): Loading from cache
  - Installing npm-asset/moment (2.20.1): Loading from cache
  - Installing npm-asset/jquery (2.2.4): Loading from cache
  - Installing npm-asset/fullcalendar (3.8.2): Loading from cache
  - Installing npm-asset/jgrowl (1.4.6): Loading from cache
  - Installing npm-asset/jquery-colorbox (1.6.4): Loading from cache
  - Installing npm-asset/php-date-formatter (1.3.4): Loading from cache
  - Installing npm-asset/jquery-mousewheel (3.1.13): Loading from cache
  - Installing npm-asset/jquery-datetimepicker (2.5.17): Loading from cache
  - Installing pear/console_getopt (v1.4.1): Loading from cache
  - Installing pear/pear_exception (v1.0.0): Loading from cache
  - Installing pear/pear-core-minimal (v1.10.3): Loading from cache
  - Installing pear/text_highlighter (dev-master 2ccac2d): Loading from cache
  - Installing pear-pear.php.net/archive_tar (1.4.3): Loading from cache
  - Installing seld/cli-prompt (1.0.3): Loading from cache
  - Installing smarty/smarty (v3.1.31): Loading from cache
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
paragonie/sodium_compat suggests installing ext-libsodium (PHP < 7.0: Better performance, password hashing (Argon2i), secure memory management (memzero), and better security.)
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
Generating optimized autoload files
````

**Comment by MrPetovan** [comment]
This is weird, the upstream `composer.json` features `pear/Text_LanguageDetect` so `git checkout --` should restore it if you modified it, unless you committed the removal on your local branch.

Please paste your `composer.json` and `composer.lock` and/or compare them with the version in this repository.

**Comment by Quix0r** [comment]
Jee! There is a difference! :-(

````
$ git diff upstream/develop composer.*
diff --git a/composer.lock b/composer.lock
index f294c16ef..bc0eba771 100644
--- a/composer.lock
+++ b/composer.lock
@@ -1761,18 +1761,13 @@
             "time": "2018-01-27T08:24:15+00:00"
         },
         {
-            "name": "pear/text_languagedetect",
-            "version": "v1.0.0",
-            "source": {
-                "type": "git",
-                "url": "https://github.com/pear/Text_LanguageDetect.git",
-                "reference": "bb9ff6f4970f686fac59081e916b456021fe7ba6"
-            },
+            "name": "pear-pear.php.net/Archive_Tar",
+            "version": "1.4.3",
             "dist": {
-                "type": "zip",
-                "url": "https://api.github.com/repos/pear/Text_LanguageDetect/zipball/bb9ff6f4970f686fac59081e916b456021fe7ba6",
-                "reference": "bb9ff6f4970f686fac59081e916b456021fe7ba6",
-                "shasum": ""
+                "type": "file",
+                "url": "https://pear.php.net/get/Archive_Tar-1.4.3.tgz",
+                "reference": null,
+                "shasum": null
             },
             "require-dev": {
                 "phpunit/phpunit": "*"
````

**Comment by MrPetovan** [comment]
You may have to rebase your changes onto friendica/friendica:develop then, you may be missing more than that.

**Comment by Quix0r** [comment]
````
$ git remote -v
origin  git@github.com:Quix0r/friendica.git (fetch)
origin  git@github.com:Quix0r/friendica.git (push)
upstream        git@github.com:friendica/friendica.git (fetch)
upstream        git@github.com:friendica/friendica.git (push)
$ git rebase -S upstream/develop
Current branch develop is up to date.
$
````
Already there. Okay, I check if more has been accidentally changed by me.

**Comment by Quix0r** [comment]
Wow, not much changes compared to `upstream` (**this** repository) ...

**Comment by Quix0r** [comment]
Thank you for helping me. :-) I was to sure that I did not touch that file.

**Pull request merged**
