### PR TITLE
Add license headers :-)

### PR DESCRIPTION
**Pull request by nupplaphil**
FollowUp #8256

### CODE REVIEW

**Comment by MrPetovan** [comment]
Please tell me you used a script for that task.

**Comment by MrPetovan** [comment]
I guess you won the trophy of the most lines added to the project this year.

**Comment by nupplaphil** [comment]
> Please tell me you used a script for that task.

I used 3 different ways:
- Find all files, starting with `<?php EOL EOL namespace` and add it in between
- Find all files, starting with `<?php EOL /** EOL * @file EOL */` and replace it
- Find all files, which are not using the Copyright header of step 1 and 2 and I added them by hand (a lot of `mod` files and `Protocol` classes, which weren't using a common pattern for header comments :-) )

**Comment by annando** [comment]
I guess you just do this for the statistics :-)

**Comment by nupplaphil** [comment]
Of course :D Since I'm not able to add things without introducing bugs, I rather add things where I (hopefully ... ^^) doesn't harm the system...

**Pull request merged**
