### PR TITLE
count unread forum items for forumlist widget (ping.php)

### PR DESCRIPTION
**Pull request by rabuzarus**
This is similar to https://github.com/friendica/friendica/pull/2048

It displays (and updates) unread forum items in the forumlist_widget.

@annando can you have a look at the sql query if I haven't miss something?

### CODE REVIEW

**Comment by tobiasd** [comment]
I don't think the unread counts are correct. For me the numbers look more like "post in that forum in total" but not the unread. Also when I click on a forum, next time the counters are displayed the number of the recently visited forum stream is reset to the initial number.

**Comment by rabuzarus** [comment]
@annando wrote me a prv message with this problem. He will have a look at it
I would say the query needs a 'AND item.unseen' in the WHERE condition. But it's hard to test for me because my test instance is a very small one with very few data

**Comment by tobiasd** [comment]
That additional condition for the WHERE looks good, but I need a unread posting to a forum to test it properly. So far the counters are not displayed when new postings arrive and the notification on the user groups pops up.

**Comment by annando** [comment]
Wait some minutes more. The pull request is on its way.

**Pull request merged**
