### PR TITLE
Hide semaphore warning

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/friendica/friendica/issues/3553
https://github.com/friendica/friendica/pull/3551

### CODE REVIEW

**Comment by Alkarex** [comment]
There is probably a cleaner approach, but here is a quick fix. I think there are cases when the semaphore is released without having being acquired. I have not investigated further.

**Comment by annando** [comment]
I guess one could check the type of the semaphore variable instead. I guess that would be a cleaner approach. Could you extend your PR to this?

**Comment by Alkarex** [comment]
I could propose the following:

```php
if (function_exists('sem_get')) {
	if (empty(self::$semaphore[$fn_name])) {
		return false;
	} else {
		$rid = self::$semaphore[$fn_name];
		self::$semaphore[$fn_name] = 0;
		return @sem_release($rid);
	}
}
```

**Comment by annando** [comment]
I realized that the error occurs when an unlock was done with a previous lock. I fixed that with this PR: https://github.com/friendica/friendica/pull/3555

**Comment by Alkarex** [comment]
👍 
I think my proposition just above would still add a good safety net. Tell me.

**Comment by annando** [comment]
I guess we need two checks:

1. Is it a resource: There we could use the function ```is_resource``` (I would prefer this over the ```empty``` function)
2. If it needs to be unlocked.

**Comment by Alkarex** [comment]
Sorry for the delay. I will do as you want, but I would think it is good as it is. Indeed, I do not think there is a case when we call this function and do not want to do our best to release the semaphore.
Furthermore, calling `is_resource()` does not guarantee that `sem_release()` will work: for instance, the resource could have been released prior to calling `is_resource()`.
`empty()` or `isset()` is still needed in the case when `self::$semaphore[$fn_name]` might not exist.
So I think `is_resource()` is superfluous, but I will happily add it if you think it is better :-)

**Comment by Alkarex** [comment]
I have just made a minor change in the order of instructions https://github.com/friendica/friendica/pull/3554/commits/84972623f766a280a5b2901f3bac9dc9b0334a0b

**Comment by annando** [comment]
It's a really good idea, setting the semaphore variable to an invalid value. This really prevents the double unlocking problem! It's much better than any idea I had for this problem.

But: I know I'm a nitpicker, but I really would prefer ```unset``` instead of setting it to zero. And then you could check for ```isset```. We are doing that ```unset``` and ```isset``` at several places of the code, so I really would vote for doing the same here as well.

**Comment by Alkarex** [comment]
Ok :-) I have just made an update with `unset` https://github.com/friendica/friendica/pull/3554/commits/080da4777d65f62a4f1a21fe7a23891454ee8e75
I have kept `empty()` which does the same as `isset` but also checks for e.g. 0, false, null... which would be invalid.

**Pull request merged**
