### PR TITLE
add simple option for HTTPS in .htaccess

### PR DESCRIPTION
**Pull request by nerdoc**
people have it easier to just uncomment 2 lines if they want such an important feature

### CODE REVIEW

**Comment by rabuzarus** [comment]
> people have it easier to just uncomment 2 lines if they want such an important feature

but your lines are already uncommented ;-)

**Comment by nerdoc** [comment]
AARGH. forgot. wait a minute ;-)

**Comment by fabrixxm** [comment]
mh.. this was meged in master, be aware...

**Comment by annando** [comment]
@fabrixxm sh...t I hadn't checked that. What do we do? Reverting it?

**Comment by nerdoc** [comment]
Oh, sorry. My fault again. didn't know - should I do a PR to another branch?

**Comment by tobiasd** [comment]
yes the develop branch would have been perfect.

**Comment by nerdoc** [comment]
Then I'd suggest revert the change and I make a PR to develop.

**Comment by fabrixxm** [comment]
I would leave this here. Next release will be already in master..

**Pull request merged**
