### PR TITLE
Mentions are now having an own class

### PR DESCRIPTION
**Pull request by annando**
See discussion here: http://helpers.pyxis.uberspace.de/display/4029d2ca54574ee24551034582986871

### CODE REVIEW

**Comment by fabrixxm** [comment]
while you are there, why not a "tag" class to tags? :-)

**Comment by annando** [comment]
Done. BTW: We have to check against several themes if there isn't any interference. I saw that "Quattro" does have a "mention" class in the CSS and I haven't checked at all if a "tag" class exists there as well.

**Comment by rabuzarus** [comment]
I think we don't need the userinfo class in php. I think it would be better to extend the event listener at class "mention"

**Comment by annando** [comment]
Wouldn't it be easier to always have the "userinfo" where we want to use the hovercard? This would be better extendable. (I'm planning to add some class to the "likes" as well and there "mention" isn't the right word.

**Comment by rabuzarus** [comment]
sure it would be the easiest way. But I have thought that it would be maybe much cleaner to say have a event listener at userinfo, mention and so on and so on. To make the elements more unique. This would give us more flexibility.
It is more just a feeling to don't hardcode to much stuff in core.

Since it's more like a feeling to don't have something in core I would like to ping @fabrixxm  and would like to have a third opinion

**Comment by annando** [comment]
My idea is to have two classes - one for the hovercard and the other for the design.

**Comment by rabuzarus** [comment]
where would be the difference? I mean between design and hovercard. I would say we have one element with which we want to do something. So we have to identify it so we can apply different stuff we want to do with it.

My problem is a little bit that until now the theme decides where a hovercard appear. In my opinion this should be as flexible as possible. A theme could be changed easily, core is much harder. And we should minimalize the usage of css html js in php.

What do you want to do, when you say css and hovercard?

**Comment by annando** [comment]
I would like to have exactly one marker for the hovercard. This could be a class name like "userinfo" - this could be as well an attribute especially for this purpose like:
````
...<a href="...." hovercard="http://path.to/profile/username">...</a>
````

But I would like to not have masses of it - this would only make sense if the functionality would differ.

BTW: As long as the HTML is generated by the themes I don't see a possibility that the core could decide where to place a hovercard. But we could decide to kick all other themes, once that frio is done.

**Comment by annando** [comment]
@fabrixxm @tobiasd What is your opinion about this? Should we have multiple css classes that would be used to indicate that there is a hovercard or should we use exactly one css class for this?

**Comment by tobiasd** [comment]
The hovercard is this Frio new way to handle the avatar menus? The themes look is nothing for me hence I did not have a deeper look into it, sorry ;-) When you started to implement mouse over automatic action in vier I stopped following the development of vier as well as I really hate it when something happens to a page just by moving the mouse somewhere.

**Comment by annando** [comment]
@tobiasd The question is of technical nature how we should solve this.

**Comment by rabuzarus** [comment]
I would say if @fabrixxm and @tobiasd don't say something about this I would merge it

**Comment by tobiasd** [comment]
I have no preference in the number of CSS classes - naturally 42 but that is a bit much ;-)

**Pull request merged**
