### PR TITLE
Item activities are now stored in a separate table

### PR DESCRIPTION
**Pull request by annando**
This should help reducing the needed database space. In some following PR I will add some script that checks and cleans up the content of the item table. This will be a preparation for removing the old item fields.

### CODE REVIEW

**Comment by annando** [comment]
I'm currently have some issue. Please wait. And I don't know why the test fails.

**Comment by annando** [comment]
This PR here changed a lot, I tested removing likes and did some additional checks and from my mind I would say that it fixes https://github.com/friendica/friendica/issues/5321 as well.

But: For a technical reason it will work only with newly added likes or after the whole database has been transformed.

**Comment by MrPetovan** [comment]
Tests are failing.

**Comment by annando** [comment]
I know. They also failed for simply changing the language files: https://github.com/friendica/friendica/pull/5329

So I conclude that the tests itself are failing. But: I'm currently searching for another bug, so its best not to merge it at the moment.

**Comment by annando** [comment]
My internal tests now work. I checked sending, receiving, relaying and deleting of likes.

**Comment by MrPetovan** [comment]
There's a Fatal Error in `src/Model/Item.php` about an `isset()` call.

**Comment by annando** [comment]
There are several ```isset``` in the code. Can you be more specific?

**Comment by MrPetovan** [comment]
The last test's PHPUnit log says line 106 of `src/Model/Item.php` but there's no `isset()` at this position in your branch...

**Comment by annando** [comment]
Possibly it is fixed due to my last changes?

**Comment by annando** [comment]
I changed some code in that area. Hopefully now that check shouldn't complain any more.

**Comment by annando** [comment]
Cool, all tests are running again!

**Pull request merged**
