### PR TITLE
Escape get_app() calls

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes parts of #6334
Part of #6208 
Redux of #6336 for the RC

### CODE REVIEW

**Comment by annando** [comment]
Possibly a dumb question but: Why is it needed? Doesn't it work the other way as well? What benefit so we have this way?

**Comment by MrPetovan** [comment]
What do you mean "the other way"?

When you declare a file to be in a namespace, any unescaped function name will be assumed to belong to this namespace. I don't know why it was working before, but it wasn't the expected behavior. Global functions/classes names should be escaped in a namespace context.

I realize now that most escaping in this PR is unnecessary because `get_app()` is called in non-namespaced files but it is transparent, meaning that it won't fail if it's escaped anyway.

**Comment by annando** [comment]
Wouldn't that mean that we had to use this ```\functionname``` everywhere where we call some PHP function as well? Or is this rule only valid for our own functions when they aren't namespace functions? Wouldn't we then have to do this with functions like ```q``` as well?

**Comment by MrPetovan** [comment]
In theory, it should be done to all global functions, whether their are PHP functions or custom ones. In practice, it seems to mostly work out without strict escaping. The reason for this PR is that someone got a Fatal Error with `get_app()`.

**Comment by annando** [comment]
There's currently a conflict here.

**Comment by MrPetovan** [comment]
Fixed.

**Pull request merged**
