### PR TITLE
Cleanup L10n namespace

### PR DESCRIPTION
**Pull request by nupplaphil**
- Move `L10n::t()` calls to `DI::l10n()->t()` calls
- Move `L10n::tt()` calls to `DI::l10n()->tt()` calls
- Move `L10n::withLang()` calls to `DI::l10n()->withLang()` calls
- Move `L10n::getDay()` calls to `DI::l10n()->getDay()` calls
- Move `L10n::getCurrentLang()` calls to `DI::l10n()->getCurrentLang()` calls
- Move `L10n::getDayShort()` calls to `DI::l10n()->getDayShort()` calls
- Move `L10n::getPokeVerbs()` calls to `DI::l10n()->getPokeVerbs()` calls
- Move `L10n` class from L10n subdir to Core (replacing old wrapper) 

=> Successfully checked `message.po` regeneration (new file included)

Needs https://github.com/friendica/friendica-addons/pull/947 as well

@MrPetovan - checked whole namespace:
Bildschirmfoto vom 2020-01-18 22-36-25

- Checked without regex and colons as well (just class and the one static method left)

### CODE REVIEW

**Comment by nupplaphil** [comment]
Ok something is wrong after the move, there are superfluous namespace-parts. I'll close it until I checked it

**Comment by annando** [comment]
I must confess that instead of refactoring refactored stuff that had been refactored before, I would prefer having a focus on the stuff still sitting in `/mod` and `include`.

**Comment by nupplaphil** [comment]
I know.. I just try to reduce the ways we currently can access classes.. All three ways are used all over the codebase.. 

Next time I'll touch mod/include stuff :)

**Comment by nupplaphil** [comment]
Btw @annando is VSC now working with the `DI::` stuff??

**Comment by annando** [comment]
Well, when we had three different ways, it was because you introduced the two other ways before :-)

**Comment by nupplaphil** [comment]
Ok, ok, got me ^^ .. At least I revert one way ..

**Comment by MrPetovan** [comment]
`L10n::detectLanguage` tests are failing.

**Comment by nupplaphil** [comment]
At least .. Checked with PHPStorm integrity checks "missing classes" ..

**Comment by nupplaphil** [comment]
> `L10n::detectLanguage` tests are failing.

Fixed with 8138b05 
=> For safety I switched languages in the profile setting as well

**Pull request merged**
