### PR TITLE
Restructured "manage" functionality, added count parameters

### PR DESCRIPTION
**Pull request by annando**
I realized that the counter for notifications on the "manage" page hadn't been in sync with the numbers that are returned by the "ping" module. While trying to fix the problem, I started to improve the code of that module.

In the end I realized that the numbers can be out of sync until both functionalities eventually are using the same class to calculate their numbers. Since this would be too much for the RC phase, I stopped there.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Can't this be pushed after the release, especially if it doesn't fix the problem you were intending on fixing?

**Comment by annando** [comment]
it is just some code and performance improvement. Of course this can be pushed.

**Comment by MrPetovan** [comment]
Then let's push it, we are too close to a release to introduce additional non-bugfix changes. This RC has seen a lot of them already, and someone needs to crack the whip.

**Comment by MrPetovan** [comment]
I've changed the base branch of this PR so that it isn't automatically closed when we remove the RC branch on release.

**Pull request merged**
