### PR TITLE
Remove Phpunit/Dbunit

### LINKED ISSUE #6429: Composer: DBUnit is abandoned and no longer maintained
Composer install is throwing a warning about phpunit/dbunit.
`Package phpunit/dbunit is abandoned, you should avoid using it. No replacement was suggested.`

See here: https://packagist.org/packages/phpunit/dbunit

> PHPUnit extension for database interaction testing
> This package is abandoned and no longer maintained. No replacement package was suggested.

And here: https://github.com/sebastianbergmann/dbunit/issues/217

### PR DESCRIPTION
**Pull request by nupplaphil**
<strike>- Introduce own Yaml-to-SQL class</strike>
- Introduce new way of MySQL-DB-tests (per rollback)
- Remove dependency phpunit/dbunit
<strike>- Introduce new dev-dependency for YAML-ready (Symfony YAML reader)</strike>

Fixes #6429 
FollowUp #7417 
Improves #6101 as well ;-)

Further details see https://github.com/friendica/friendica/pull/7441#issuecomment-515786026

### CODE REVIEW

**Comment by annando** [comment]
How does this rollback mechanism work? Please consider that we use transactions at some parts of the code.

**Comment by MrPetovan** [comment]
Does it have to be Yaml?

**Comment by nupplaphil** [comment]
> Does it have to be Yaml?

Done ;-)

**Comment by nupplaphil** [comment]
> How does this rollback mechanism work? Please consider that we use transactions at some parts of the code.

I override `Database` with `StaticDatabase`. Here I add the followed functions:
- I override `PDO` with `ExtendedPDO`, which is capable of nested transactions
- I use `ExtendedPDO` for all `DBA` connections because of the initialized `StaticDatabase`

Each test-case has the following process:
- Start with a `beginTransaction()` which is the outer transaction
- After it, I load the DB-fixture (`api.fixture.php`) - we can load as much fixture as we need
- Than I start all tests (which can include `beginTransaction`, which will start a nested transaction)
- After it, I make a "rollback" for EVERY transaction which does a cleanup for everything

I investigated a little bit and it is the fastest way to use MySQL during phpunit tests. More fast is just mocking the whole database, which is quite complicated for API ;-)

The reason that we "just" improve 5 minutes overall time is the `@runInSeparateProcess` annotation in tests, which FORCES php to completely recreate the whole PHP-environment.
This annotation is needed f.e. when calling `header()`, because this would kill the whole PHP-unit run at all, or if we every call `kill()` or similar commands.

**Pull request merged**
