### PR TITLE
Updated relation status string

### PR DESCRIPTION
**Pull request by JeroenED**
I didn't like the how the current relation status was displayed. I changed it in a way I like it more.

**Old string**: Dating (my girl) for 2 years
**New string**: Dating with my girl for 2 years

Follow-up to: #7347
Tested: social.jeroened.be (with no name, no howlong and no both)

### CODE REVIEW

**Comment by nupplaphil** [comment]
Does the syntax work with other languages too? So we don't create sentences like `Dating my girl with for 2 years`? Just asking :)

**Comment by JeroenED** [comment]
@nupplaphil That would be an issue. I'll look into it.

**Comment by JeroenED** [comment]
@nupplaphil this should be OK now. Thanks for noting me.

**Comment by JeroenED** [comment]
Ready to merge

**Comment by MrPetovan** [comment]
The problem that I see is that these translation strings assume the existence of a present participle in all the languages we support, which I wouldn't be so sure of it.

The ideal, of course, is to have four separate translation strings for each choice:
- `{Status}`
- `{Status} (with) {Person}`
- `{Status} for {How Long}`
- `{Status} (with) {Person} for {How Long}`

This way translators have the most room to maneuver, instead of having to compose with an English-centric construction.

**Comment by JeroenED** [comment]
@MrPetovan It's still 5am in New York? I caught these 😉 and there are 4 separate translation strings.

**Comment by MrPetovan** [comment]
Except the translation strings I suggest wouldn't have the status dynamic. The list of these translation strings would be literally:
- `Dating`
- `Dating %s` ("with" is unnecessary)
- `Dating for %s`
- `Dating %1$s for %2$s`
- `Has crush`
- `Has crush on %s` ("with" is uncalled for)
- `Has crush for %s`
- `Has crush on %1$s for %2$s`
- `Engaged`
- `Engaged to %s` (more correct than "with")
- `Engaged for %s`
- `Engaged to %1$s for %2$s`
- ...

**Comment by JeroenED** [comment]
So, wjat do you suggest for dynamical strings? I want to script it (like if status ends with ed use to, if status contains has use on,  ...) I really don't think literals are a solution or we should also update the morechoice addon having these the translations as another key.

**Comment by JeroenED** [comment]
I already have an idea to solve it in mind. It requires however to first merge #7347 as I'll have to change the marital statuses again.

Solution is as follows:
* I create a static function which will return an array of the marital statuses (I'll create a additional file src/Util/ContactSelector.php for this as I don't see another related file)
* The array of marital statuses will be expanded with another element containing the translation string for the status.
```
Now:
'Has crush'            => L10n::t('Has crush')

Becomes:
'Has crush'            => [ L10n::t('Has crush'),  L10n::t('Has crush to') ]
```
* The comboselector in the edit profile will use arraykey 0
* The marital status in profile view will use arraykey 1

I think this will be the cleanest solution?

**Comment by MrPetovan** [comment]
Again, this assumes an identical phrasing construction across all languages we support, which is unlikely. Maybe in Chinese we would need a construction like this: "for 2 years Emma Watson has been a crush of mine", which you can't reliably express with the dynamic strings you suggested.

And yes, the `morechoice` addon would need to be updated.

My own personal opinion is that this field should be left completely user-defined or straight up removed in favor of the freeform profile description field. If you aren't speaking the language the profile description is written in, I don't know what business you have knowing their translated relationship status. I can only see vectors of harassment out of this.

**Comment by JeroenED** [comment]
Ok. I'll try to find out a way that is less intrusive and is also acceptable to me. I guess it'll require some time.

**Comment by JeroenED** [comment]
https://social.jeroened.be/display/cd9f100a-685d-2a12-904b-56f765048999

**Comment by MrPetovan** [comment]
Will be rendered obsolete by #7777

**Comment by annando** [comment]
This PR is slightly stale. What do we do with it?

**Comment by MrPetovan** [comment]
See my previous comment, but you can close it earlier if you feel like it.

**Comment by annando** [comment]
We can postpone it as well. I would like to see a answer from @JeroenED

**Comment by MrPetovan** [comment]
I understand, but his answer will be irrelevant when the custom profile fields PR will be merged because he will be able to write whatever he wants in his profile without affecting what anyone else can write on theirs.

**Comment by JeroenED** [comment]
My answer is to close it. I'm currently too busy with other things.

**Comment by MrPetovan** [comment]
Thanks for stopping by!

**Pull request closed without merging**
