### PR TITLE
Transmit push subscriptions

### PR DESCRIPTION
**Pull request by annando**
The PHP version in the composer is increased to 7.2 to fetch the needed composer package.

For this new composer package we need the `gmp` PHP package. Do we need to check for this or doesn't it matter since the composer does tell you to about it?

I'm not totally sure if this will work with every possible client since I don't know yet if we have to transmit a payload at all.

### CODE REVIEW

**Comment by nupplaphil** [comment]
if we would update to 7.2, you really would do me a favor in case of testing :X .. Because there's no easy possibility to add tests for 7.0 and 8.0 .. they are really, really incompatible :D

**Comment by nupplaphil** [comment]
you need to update the PHP version here as well:
https://github.com/friendica/friendica/blob/414f20c529a8547ce05e9dd79c34f1dc2fe6f467/composer.json#L16

**Review by MrPetovan — APPROVED** [review]

**Review by MrPetovan — COMMENTED** [review]
The PHP GMP extension doesn't seem to be a hard dependency for any package, if it is for our use we have to add it to the main composer.json file.

**Comment by annando** [comment]
It seems to be used for one of the dependencies - or possibly it **had been** used for the older packages before I updated the minimal version. I cannot check this at the moment.

**Comment by tobiasd** [comment]
> The PHP version in the composer is increased to 7.2 to fetch the needed composer package.

Could you add a note about this into the CHANGELOG file? Just so I don't forget this ;-)

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
