### PR TITLE
Fix external link inconsistency part 1: Remove insecure target="_blank" attributes

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #8323

This PR removes all `target="_blank"` from the project. It is a security and a usability feature. Like I said in the corresponding issue thread, since we currently don't have a good definition of what constitutes an external link or not, leading to an inconsistent behavior, I'd rather remove the security risk and revert to a sane default behavior first before anyone takes a stab at a centralized link function.

### CODE REVIEW

**Comment by annando** [comment]
I really, really, really would like to discuss this with the users before merging it.

**Comment by MrPetovan** [comment]
There are two parts to this issue. The current security vulnerability with all our `target="_blank"` links, and the inconsistent behaviors between links.

If the second part wasn't existing, the first part could be simply solved by adding `rel="noopener  noreferrer"` to all current `target="_blank"` links. But I believe it would be putting a band aid on an otherwise gushing wound.

Similarly, if the first part wasn't existing, we could take the time to poll users on the expected behavior, and implement the decided behavior. I'm not interested in that part because of my opinion on the subject.

I will not force-merged this PR, but I meant it as a nudge to either go with what I'm suggesting, which isn't arguably wrong, it empowers users and clients alike to handle links like they want instead of half-badly like it is now. Or to go with a specific definition of internal/external links that takes OWA into account and that I have no specific idea about what it would look like.

**Comment by annando** [comment]
It would be possible to temporarily add `rel="noopener noreferrer"` to the links and then discuss about this topic with the users. I think that the user experience is to mostly stay on the system and open external links in a new page. This - in fact - is a behaviour that every other social network system is doing that way. Breaking this convention confuses users very much.

**Comment by MrPetovan** [comment]
Here's the core of this PR motivation: are users more confused by the current inconsistencies or would they be more confused by my tabula rasa solution?

**Comment by annando** [comment]
Currently it *mostly* works like expected from users like the original poster of the related issue. So changing it completely would be confusing. And that's why a discussion would be good.

**Comment by MrPetovan** [comment]
Replaced by #8337

**Pull request closed without merging**
