### PR TITLE
Space before t

### PR DESCRIPTION
**Pull request by rebeka-catalina**
Added whitespaces between comma and t()

### CODE REVIEW

**Comment by annando** [comment]
I guess that @Hypolite will notice the other missing spaces in the parameter lists. :-)

**Comment by Hypolite** [comment]
Merging this with my eyes closed, hopefully @quix0r will pass over this and I'll pick all the missing spaces up.

**Comment by rebeka-catalina** [comment]
Oh - conflicting stuff :-/ Sorry, the action to put a whitespace there happens in both PRs :-/

**Comment by Hypolite** [comment]
Thank you for your work!

**Pull request merged**
