### PR TITLE
API: Account actions

### PR DESCRIPTION
**Pull request by annando**
The API functions for account actions are now added.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]
I must admit, you've taken pretty well to the code structure we've laid out for the API calls, and all the new modules look very concise which was the goal. Thank you for your patience!

**Comment by annando** [comment]
At least I'm able to replicate code when the structure had been predefined :-)

**Comment by MrPetovan** [comment]
And it means you aren't too old for this yet!

**Comment by annando** [comment]
@MrPetovan that's a good notice, since I just had birthday :-)

**Comment by MrPetovan** [comment]
Herzlichen Glückwunsch zum Geburtstag !

**Pull request merged**
