### PR TITLE
Move TwitterOAuth to composer Part 1

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #4116

### CODE REVIEW

**Comment by annando** [comment]
Since this will be another breaking event, I would suggest that we prepare our users some time before. This should be done so that users of all timezones have sufficient time to react.

**Comment by MrPetovan** [comment]
This isn't a breaking PR anymore, it just improves the display of the addon readme display in the admin setting page.

**Comment by annando** [comment]
Why have you reworked this?

**Comment by MrPetovan** [comment]
For simplicity, because the breaking change isn't worth it.

**Pull request merged**
