### PR TITLE
the "save" button is now 'follow' when searching for tags

### PR DESCRIPTION
**Pull request by rabuzarus**

### CODE REVIEW

**Comment by annando** [comment]
Is it only used in "Frio"? Is there some difference in other themes?

And a related question: Should we activate the tag following (and commenting on every public item) in general? I would vote for it.

**Comment by rabuzarus** [comment]
> Is it only used in "Frio"? Is there some difference in other themes?

No. Frio does use the `$mode` variable to display different icons. On other themes the button text does change according to the searched content (`$save_label`).

> And a related question: Should we activate the tag following (and commenting on every public item) in general? I would vote for it.

I don't understand what you mean. Where would we activate the tag following?

**Comment by annando** [comment]
The tag following is currently only active, when ```$a->config['system']['comment_public'] = true;``` is active in the ```.htconfig.php```. (Because only in this case users can interact)

I would like to remove that switch soon, since I added it mostly to not confuse users in the meantime of the development phase.

**Comment by rabuzarus** [comment]
Ahhh OK. Didn't know this.
I'm for removing it :-) You are right. To many options (and different behavior) is confusiong.

I din't take care of this option in this PR. Should I add a `$a->config['system']['comment_public'] ` check?

**Comment by annando** [comment]
No, leave it as this. I'm for removing the config when no one is reporting any issues for some days.

**Comment by MrPetovan** [comment]
Follow-up to #4186

**Pull request merged**
