### PR TITLE
Improve the ignore behaviour

### PR DESCRIPTION
**Pull request by annando**
The "ignore" behaviour is now changed in a way that acts more like other systems. Posts and comments from ignored contacts are now hidden. Also there will be no notifications.

### CODE REVIEW

**Review by MrPetovan — CHANGES_REQUESTED** [review]
Is there a way not to have ignored accounts' posts in the Network stream but being able to access their conversation in the Display module? For now both are governed by the same `Model\Post:: selectViewForUser` method even though the context is different.

Additionally, have you tried the new Ignore button in the vier theme?

**Comment by annando** [comment]
I tried the ignore button and it worked. I guess to make it really work you have to force reload the JS. Concerning the display of ignored accounts. I wouldn't want to include them on the "display" page since would contradict the ignoring. But I'm thinking about be9ing able to display posts from blocked and ignored contacts on their contact page, so that you can have a look why you blocked/ignored them.

**Comment by MrPetovan** [comment]
The scenario is this: You replied in a conversation, then you decide for whatever reason to ignore/block the top-level author. If you receive replies in this conversation but not from the ignored/blocked account, you will receive notifications but the link will show a 404 error because the top-level author is ignored.

Ignored/Blocked content should be available when it's specifically requested, showing 404 errors doesn't help anyone.

**Comment by annando** [comment]
We now check for the parent author as well and suppress notifications if we blocked that contact as well. I think that when we decided to block that contact, then we don't want to see anything from them ever again.

**Comment by MrPetovan** [comment]
So you read my remark, and decided to make the problem even worse? Blocking/Ignoring works well in the conversation streams, but please leave `/display` and a few other pages out of it. There are more reasons beyond notifications to be able to voluntarily access content even tangentially associated with blocked or ignored contacts.

What about the contact Conversation page? Their Post and Reply pages? These should also be accessible no matter the block/ignore status because they are out of the way. They do require a voluntary action to be accessed, unlike the Network/Community Page streams where unwanted content can spring on you because they are aggregated.

We need two different ways to query content, one excluding ignored/blocked accounts in the conversations streams, and one that doesn't for all the rest.

**Comment by annando** [comment]
The contacts page is definitely different, since you deliberately chose to view content from that person. But I see the network and the display page as similar. When I blocked someone, then I don't want to see their content popping up between comments from people that I want to read.

But: This surely is a developing task. Means: Most likely there will be future PRs that are adjusting the behaviour.

**Comment by MrPetovan** [comment]
The problem is those 404 errors when the top-level author, owner or causer (?) is ignored or blocked.

But I'll follow your example, let's say I want to check what an ignored account is up to. I go to their Contact page, navigate to "Posts and Replies", and I can see they posted a reply in a conversation I can't see yet. So I click on "View context", and suddenly the comment that I was seeing because I wanted to doesn't appear anymore because I wouldn't want to see it?

**Comment by annando** [comment]
Like I said: it is a developing task. And I wouldn't want to do it all in a single PR. I prefer doing it in steps. Otherwise the PR will take weeks and will get larger and larger.

**Comment by MrPetovan** [comment]
I don't like this, I feel like we're moving a step backwards regarding users' agency, but I don't feel confident enough to decouple the different contexts myself.

**Review by MrPetovan — APPROVED** [review]

**Comment by annando** [comment]
Since I haven't changed anything regarding blocking, the user experience is now improved since you won't have got any notifications anymore that lead to 404s. More or less this PR just changed the behaviour for ignored contacts and added the option to ignore contacts from the posts.

**Comment by SpcCw** [comment]
I like how ignored contacts are collapsed in threads but not removed completely but yes,I also would prefer seeing their top-level posts in /display if I want to, I agree with MrPetovan here.

Anyway I came here with a different question for @annando : was reshare/boost behavior changed by this? I ignore some people because they like weird stuff but still we have meaningful conversations sometimes. Recently I see posts reshared by these people on my Network page.

Are posts reshared by ignored contacts supposed to be seen?

**Pull request merged**
