### PR TITLE
[frio] Update style.php defaults with Facebook colors

### PR DESCRIPTION
**Pull request by copiis**
The Facebook colors as standard for Frio.
To mitigate the withdrawal symptoms of people leaving Facebook.

### CODE REVIEW

**Comment by AndyHee** [comment]
I appreciate this new theme! It's good and surely will be of value to some former Facebook users.

My question here: _Should this theme be set as default?_  Do we really want a Facebook clone as the default theme for Friendica?

**Comment by annando** [comment]
I would prefer having another colour scheme instead.

**Comment by copiis** [comment]
Humans are creatures of habit and if someone breaks loose from Facebook then he should not be shocked by something completely different. In terms of functionality, Friendica is best compared to Facebook, just as Mastodon very similar to Twitter is.
I think people coming from Facebook are very influenced. Of course everyone prefers their own favorite color, it's not about what the favorite color of an individual is, I just want that Friendica grows and prospers. This can be better achieved if not just the feel but also the look is right.
I do not find it reprehensible to use the Facebook Blue, the Friendica logo already contains the blue.
The color scheme can be changed anytime, if you have settled in at Friendica and if you no longer feel comfortable with it.

**Comment by annando** [comment]
I think it's up to @rabuzarus to decide, since it is his theme, but I really would prefer having a choice between the existing colours and these ones.

**Comment by AndyHee** [comment]
> What speaks against it?

At the moment these changes merely replace one colour scheme for another. An _enhancement_ arguably would be adding a new theme (e.g "Facebook-Colour-Simulation"). Replacing an existing scheme should be merely done in case of a _bug_ i.e. there is some wrong with it that is beyond personal taste and preference.

I agree there is value in an additional theme that simulates the Facebook colour scheme precisely for the reason you outline above. However making such a new Facebook colour scheme the default scheme is fundamentally wrong in my opinion for the following two reason:

1. It may create false expectations for new uses who have migrated from Facebook. In psychological terms, it may reinforce believes that users will get a Facebook-like experience here. This is highly problematic as it will inevitably result in disappointment and may decrease the chance of sticking with Friendica. This is fundamentally different from someone who has willing opted for a Facebook look-a-like scheme, by actively changing the settings herself at some point.

2. It may also upset or disturb seasoned open-source enthusiasts who had chosen not to use Facebook, but now find themself using a platform that now tries to look like Facebook. 

Overall nothing can be gained from making Friendica look like Facebook by default. Histories of technological inventions clearly tell us that technologies which mimicking existing technologies are usually not very successful, but those that are considerably different from those had been around might have a slim chance.

**Comment by AndyHee** [comment]
On a side note, I actually find [708fa0](https://www.color-hex.com/color/708fa0) quite good; there is a certain element of simple elegance, calmness and neutrality to it. But then again this is purely my personal taste.

**Comment by rabuzarus** [comment]
To keep it short. I would't like to change frio's default colors scheme to look like facebook. While I'm not happy with frio's actual default color scheme Friendica should have its own color branding. For the rest I'm going with @AndyHee arguments

**Comment by rabuzarus** [comment]
My opinion:
* we need to to have another GOOD default color scheme (the present default scheme bases on the humhub color scheme and don't have a good usability -> link color is too bright)
* for other possible future schemes: We can add some, but I would rather vote for having extended schemes which make extensive use of the `schemename.css` (like https://github.com/friendica/friendica/blob/develop/view/theme/frio/scheme/love-music.css) than having 20 different schemes which diver only in the panel or link color. This is something users can (and should) do by her/his own.
* we should provide a mechanism to save/export/import own color schemes

**Comment by JeroenED** [comment]
When #6722 is merged following string can be used to set this theme.

```JSON
{"nav_bg":"#3b5998","nav_icon_color":"#ffffff","link_color":"#365899","background_color":"#e9ebee","background_image":"","background_image_option":"repeat","contentbg_transp":"100"}
```

**Comment by MrPetovan** [comment]
Superseded by #6722

**Pull request closed without merging**
