### PR TITLE
Issue #2792

### PR DESCRIPTION
**Pull request by Hypolite**
Fix Issue #2792 

Not sure about the following condition to know if the current user is among the reactions:

`if((local_user()) && (local_user() == $item['uid']) && ($item['self']))`

It seems to work on as expected on my single-user instance, but I'm not exactly sure about the meaning of `uid` and `self`.

### CODE REVIEW

**Comment by annando** [comment]
For me the condition looks fine. The "uid" contains the user that owns the item. And "self" just tells if the item was created by the user that owns the item.

Now the nasty part: Could you add your changes to the other (maintained) themes as well?

Thanks!

**Comment by Hypolite** [comment]
> Could you add your changes to the other (maintained) themes as well?

Yes but I won't accept any liability for ugly design. Also I see way more themes in the theme folder than in the active theme list in the admin, is it because they all are deprecated?

**Comment by tobiasd** [comment]
Yes. The supported themes are the ones where the file `unsupported` is missing. They are still in the repository so users using them wont suddenly have lost their theme after an update, but new features wont arrive there.

**Comment by Hypolite** [comment]
It's done. Phew!

**Pull request merged**
