### PR TITLE
API: Next bunch of functions transformed

### PR DESCRIPTION
**Pull request by annando**
Some more API functions have been removed from the old place.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
Has this PR become slightly more complicated because of #11005? @nupplaphil

**Comment by annando** [comment]
I haven't looked at what @nupplaphil had changed in his PR because I won't understand it anyway :grin: 

I now had a quick glance at the sheer number of changed files. Since my development server is also my productive server, I guess I will wait some days before merging, so that possible side effects of the PR can be ironed out.

**Comment by nupplaphil** [comment]
If I've done it right, you should only need modifying the `post()` and `content()` method syntax, the rest should be compatible...

**Comment by nupplaphil** [comment]
I do have more time next week, so hopefully I'll fix all regressions shortly after finding them ..

**Comment by nupplaphil** [comment]
@annando - I merged the branch for you to check if I'm right :D and as I already hoped --> it was just a matter of some method syntax modifications :-)

**Comment by MrPetovan** [comment]
`Photo\Delete` and `Photoalbum\Delete` API test failures are addressed in #11037 and #11038.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
