### PR TITLE
Attached picture from OStatus posts are now displayed

### PR DESCRIPTION
**Pull request by annando**
This is looking much more better than the simple image icon like before.

### CODE REVIEW

**Comment by tobiasd** [comment]
When the image is attached to an entry that is collapsed by the content filter, the attached image is displayed nevertheless. Can this be changed?

**Comment by annando** [comment]
Does this happen with Mastodon? The regular nsfw filter shouldn't interfere.

**Comment by tobiasd** [comment]
> Does this happen with Mastodon? The regular nsfw filter shouldn't
> interfere.

Yes, the posting I've seen this with was from Mastodon and not GS.

**Comment by tobiasd** [comment]
Additionally with some Mastodon postings, the attached image (jpg file) is not detected.

**Pull request merged**
