### PR TITLE
Issue 8321: Follow items now work again

### LINKED ISSUE #8321: Follow Thread is broken
### Expected behavior
When I select 'Follow Thread' from the ~~action~~ •••more menu I should get notifications about new comments.

### Actual behavior
When I select 'Follow Thread' from the ~~action~~ •••more menu I don't get notifications about new comments. Either the 'Follow Thread' function is broken or the notifications for those threads don't work.

### Steps to reproduce the problem
Select a thread where comments are expected. Use 'Follow Thread' from the ~~action~~ •••more menu. Wait until comments arrived.

### Friendica version you encountered the problem
2020.03-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

### PR DESCRIPTION
**Pull request by annando**
fixes #8321

We are now using the same function that we use for "likes" and attend messages as well.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Will it also solve the unfollow issue?

**Comment by annando** [comment]
Which unfollow issue? You cannot unfollow right now - but this is prepared now.

**Comment by MrPetovan** [comment]
The "Ignore thread" that seems to be broken as well, I thought it could be the same root issue.

**Comment by annando** [comment]
This is a very different structured stuff. Is there an issue number for it?

**Comment by MrPetovan** [comment]
Not yet, it's a support forum reply at the moment.

**Pull request merged**
