### PR TITLE
Use profile.about for profile description

### LINKED ISSUE #8251: Use profile.about instead of profile.pdesc for profile description
I just realized that the profile field "about" is one of the fields that had been moved to the custom profile fields. I think this should be exchanged with the field "pdesc". "pdesc" is only a varchar(255) while "about" is a text field.

Formerly we transmitted the content in the "about" field for example in the "summary" field of the AP profile data. We now use the content of "pdesc" for that, that is much too short for that purpose and doesn't allow line feeds.

On other systems (Mastodon, Pleroma, Diaspora, GNU Social) the "summary" field is always a longer text field. It is used for a longer self description. We should also use a longer field for that and instead move the content of the "pdesc" field to the custom profile fields.

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #8251 
Follow-up to #8156
Part of #7817

This PR is particular because it requires an update for users on develop nodes, but it won't be needed for users on stable nodes.

Meaning that stable users will have their profiles migrated normally, but without an additional update routine, the develop users will lose the content of their `profile.pdesc` field in the database limbo, never to be accessed again.

And this additional work will be absolutely useless for people upgrading from stable to stable version.

Should we just do an announcement on the forums or should we add a piece of code that will only be relevant for node that have been running the develop branch between January 24th and the moment this PR will be merged?

### CODE REVIEW

**Comment by AlfredSK** [comment]
Ok. What information is then displayed under the user's large avatar on the wall/profile page? Until now the content of the title/description field is displayed there.

**Comment by AlfredSK** [comment]
> the develop users will lose the content of their profile.pdesc field in the database limbo, never to be accessed again.

That's unacceptable. Losing the data must not be an option.

**Comment by MrPetovan** [comment]
> Ok. What information is then displayed under the user's large avatar on the wall/profile page? Until now the content of the title/description field is displayed there.

The `about` field will now be displayed. It's a full BBCode-enabled field instead of a 255 characters limited line with no formatting.

**Comment by AlfredSK** [comment]
M'kay. :-) Thank you.

> That's unacceptable. Losing the data must not be an option.

Now that I read my comment again I feel bad because it sounds pretty harsh. I'm sorry about that. To explain my point, I had a somewhat unpleasant experience with the transition of the profile data lately. A user had stored a lot of information in his (old) profile fields and he lost some data when the profiles were converted to the new form. Luckily, I was able to rescue the data from an old database backup. Phew! ;-) 
I hope it is understandable that I am not eager to repeat that experience.

**Comment by MrPetovan** [comment]
Absolutely and I'm sorry you had to deal with that. The migration process wasn't meant to make anyone lose data so I understand your frustration. This time is different, I know exactly what data would disappear from the display. It wouldn't be "lost" as much as "hidden" because of the field change.

Do you have any details on the actual data loss that forced you to dig into your backups?

**Comment by AlfredSK** [comment]
He used the 'likes', 'film', 'music' ... fields to store huge lists of movies, bands and so on. The lost data was stored in the 'Hobbies/Interests' field. That field was empty after the migration.
I didn't experienced that myself. My own 'Hobbies/Interests' field has been migrated successfully.

Maybe the issue had something to do with the format of the data. After I rescued it from the DB backup I saw that it was in some DOS format with weird line breaks (in vi displayed as ^M\).

Here is the thread.... https://libranet.de/display/0b6b25a8-155e-2f26-6b56-45b856586089 (there is a link in that comment where you can download the data).

**Comment by MrPetovan** [comment]
Thanks, I remember now. This is a very specific issue I probably won't be able to reproduce. The release notes will have to be clear about making a backup of the profile table before the update.

**Comment by annando** [comment]
Isn't the original "about" content still be stored in the additional fields? So users could do some cut&paste there easily.

**Comment by MrPetovan** [comment]
The problem is the following:

Users on 2019.12 stable or develop **before** January 24th:
- `profile.pdesc` set
- `profile.about` set

Users on develop **after** January 24th but **before** this PR is merged:
- `profile.pdesc` kept as a basic field
- `profile.about` cleared and transformed into a custom field

Users on stable 2020.03 or switching to develop **after** this PR is merged:
- `profile.pdesc` cleared and transformed into a custom field
- `profile.about` kept as a basic field

Users that were on develop **between** January 24th and when this PR is merged:
- `profile.pdesc` set but now unused <= **This is the problem**
- `profile.about` still cleared but now used as a basic field
- Separate about custom field

**Comment by annando** [comment]
So this is really only when someone edited "pdesc". BTW: You could update the "about" field in profile with the "about" field in the "self" contact when the profile field is empty. This should be a safe way.

**Comment by MrPetovan** [comment]
It isn't a matter of knowing what to do to mitigate this problem in general, but whether it should be part of this PR and forever recorded in the code even though it doesn't concern users that are on stable at all. I don't think it should, but we still need to do something to avoid apparent data loss like @AlfredSK emphasized. Hence my proposition of a one-time SQL query admins that were on develop after January 24th will have to run.

**Comment by AlfredSK** [comment]
> Hence my proposition of a one-time SQL query admins that were on develop after January 24th will have to run.

I'm fine with that.

**Comment by MrPetovan** [comment]
Thanks, this PR is ready now. The release notes will be a little more verbose than usual.

**Comment by tobiasd** [comment]
And, where is this SQL call documented?

**Comment by AlfredSK** [comment]
``UPDATE `profile` SET `about` = `pdesc`, `pdesc` = NULL WHERE `about` IS NULL AND `pdesc` IS NOT NULL;``

https://forum.friendi.ca/display/735a2029-165e-42bb-889c-fef460943985

**Pull request merged**
