### PR TITLE
move config to its own class (with legacy support)

### PR DESCRIPTION
**Pull request by rabuzarus**

### CODE REVIEW

**Comment by fabrixxm** [comment]
while return "false" on unset config is the legacy way that function worked,
as could result in some bugs, can't the new implementation returns "null" as value for unset config?
it feels more correct, imho:

    what's the value of the setted config "enable_this" ? -> false
    what's the value of the unsetted config "enable_that" ? -> null

and maybe could be usefull an optional parameter to define the value to return for the config if is unset:

```php
$title = Config::get("myaddon", "title", "Default title")

# with Config::get defined as:
public static function get($family, $key, $default_value=null, $instore=false)
```

to maintain legacy compatibility, we can do something like

```php
function get_config($family, $key, $instore=false) {
    $v  = Config::get($family, $key, $instore);
    if (is_null($v)) $v=false;
    return $v;
 }
```

**Comment by fabrixxm** [comment]
and while I'm here, looking at the code "$instore" isn't the best name for the paramenter,
should be something like "$refresh" or "$notcached"

if true, config value is reloaded from db, instead of rely of cached value in $a->config

**Comment by fabrixxm** [comment]
Any comments about the `$default_value` argument?
I got the idea from the `get()` method on dictionaries in python ( http://www.tutorialspoint.com/python/dictionary_get.htm )
It could simplify some very repetitive code

```php
$val = Config::get("myaddon", "title");
if (is_null($val)) $val = "No title yet";
```
vs.
```php
$val = Config::get("myaddon", "title", "No title yet");
```
(while the former will remain valid)

**Comment by rabuzarus** [comment]
I would really would get this merged first. If somebody want's to extend this he/she could do it in the suggested way above.
This shouldn't sound harsh, I just don't understand it. It would be easier for @fabrixxm to implement this since he does have a concrete vision

**Comment by fabrixxm** [comment]
Oook

**Comment by fabrixxm** [comment]
there is a small problem here..
files `Config.php` and `config.php` are the same on some toys OS...

**Comment by rabuzarus** [comment]
:-(
how to deal with this issue ?

**Comment by fabrixxm** [comment]
The best would be to rename the Config class
Like Conf and PConf (just to keep things the same...)

**Comment by fabrixxm** [comment]
or move the classes in a namespace like
`\Utils\Config` and `\Utils\PConfig`
with the files become
`include\Utils\Config.php` and `include\Utils\PConfig.php`

(I'm for this solution)

**Comment by fabrixxm** [comment]
(or using `Core `as namespace, looks more logical)

**Comment by rabuzarus** [comment]
@fabrixxm can you do this? because you are more familiar with the whole namespace logic.

**Pull request merged**
