### PR TITLE
Post update script to move old content from the item table

### PR DESCRIPTION
**Pull request by annando**
It will process 10,000 items per worker task. I will watch the conversion on my systems and then will possibly adjust this value. On my system the 10,000 items are processed in less than 3 minutes.

### CODE REVIEW

**Comment by tobiasd** [comment]
This increased the LOAD on my system from 0.5-ish to 3.5-ish knocking out the background process. A warning to the support or admin forum would have been nice.

**Comment by annando** [comment]
On my system the load hadn't increased significantly.

**Comment by tobiasd** [comment]
Lets assume, that your node has significantly more RAM then an RasPi.

It's now converting since 7 hours and has 30% of the row `count(*)` from item now in item-content. Count in item-content is raising in steps of 1000 it seems, so this should not be newly arriving comments. Not sure how to better measure the progress. LOAD is stable at 3.5-ish.

**Comment by annando** [comment]
I'm currently using this script to measure the progress: ```select count(*) as rest from `item` where icid is null;select count(*) as converted from `item` where not icid is null; select count(*) as content from `item-content`;```

**Comment by MrPetovan** [comment]
@annando  I'm waking up only now, but is there a specific reason why there's a `icid` in the `item` table rather than a `iid` in the `item-content` table?

**Comment by annando** [comment]
There are N entries in the item table for 1 entry in the item-content table.

**Comment by MrPetovan** [comment]
I thought the `user-item` table was supposed to be the N part?

**Comment by MrPetovan** [comment]
What do you mean by "structure data"?

**Comment by annando** [comment]
Everything that isn't content- or user specific. And mostly fields that are used in indexes.

**Comment by MrPetovan** [comment]
Ultimately, `item` rows will be unique, right? With a 1 to 1 with `item-content`?

**Comment by annando** [comment]
Yeah. But the way to this will be longer.

**Comment by MrPetovan** [comment]
As long as you hold the cap!

**Comment by tobiasd** [comment]
I think it's done, after a day at high LOAD the system is down to normal values again. Your query still shows 1500 items as *rest*.

**Comment by annando** [comment]
Please update to the latest code. Then set the "post_update_version" code to something before 1274 - possibly 1273. Then the post update should start again and should touch the rest - hopefully.

**Comment by annando** [comment]
BTW: I'm currently unhappy with the results. I hoped that my backups would be significantly smaller - but they are nearly identical.

**Comment by MrPetovan** [comment]
Are you going to change the structure/process? I'm still holding on the update.

**Comment by annando** [comment]
See my just edited comment. I think we are on a good way, but we aren't at the finish line yet. I guess that when I possibly will add some additional side table, I will just start another update process.

**Comment by MrPetovan** [comment]
Will this another update process take into account the intermediate structure or the `master` branch structure as well?

**Comment by annando** [comment]
It will work in a way so that it works for the people who are on develop as well as for the people on master. How? I don't know by now. But there will surely be a way. Since this idea just spawned in my mind, I hadn't thought it through.

But this really should help saving data. For an activity for example, we only need a side table with a single integer value that tells us if the author is liking, disliking, attending or not attending something. All the other fields in the content table needn't to be filled for this.

This also means that we can get rid of several fields in the item-content table like "object" or "target".

**Comment by MrPetovan** [comment]
The problem, as usual, is retrieving data about multiple item types at the same time, like on the network page. Please don't over-optimize, small text/integer fields are fine even if they aren't used for a specific case, but text/blob fields (body, source, rendered-html) should indeed be unique for each item.

**Comment by annando** [comment]
Due to the now existing abstraction layer (which seems to work fine) we can easily split the data into separate tables, according to their item type. This unique storage is what has now be done in the ```item-content``` table.

I just looked in my database, there is one third starting posts, one third comments and one third activities. I think it does make sense to transfer the activities to a dedicated place.

**Comment by tobiasd** [comment]
We chatted a bit over this at yesterdays LUG meeting. On smaller nodes this seems to have the opposite effect regarding the needed disk space while on larger nodes the result was a significant lower (in the order of 25% IIRC) disk usage Which I guess is to be expected as smaller nodes wont have that many multiple contacts as larger nodes have.

**Pull request merged**
