### PR TITLE
Optimize tables on a daily base that are written very often

### PR DESCRIPTION
**Pull request by annando**
The optimization should only last some seconds but is very helpful because these tables are written and deleted very often.

### CODE REVIEW

**Comment by Keith2** [comment]
This could cause problems on the public server theshi.re which has a 11GB photo table.
Would be better if this was optional.

**Comment by annando** [comment]
@Keith2 Could you check the speed on your system? It took one minute on my system with a photo table that has nearly 1 Gig.

But I guess you are right. I shouldn't add the photo table by default. The other ones shouldn't be a problem, aren't they?

**Comment by annando** [comment]
BTW: Do you know other tables that haven't got many entries but are written very often?

**Comment by Keith2** [comment]
11 minutes to optimize the photo table, data length unchanged, saved 1.5M on the index.
retriever_resource is another table that can be looked at, it may not exist as it is created by an addon. Perhaps with a separate option.
There already is an option to optimize the item table in expire.php, it would be better to have the optimizations in one place.

**Comment by annando** [comment]
I totally rewrote the functionality. The system will now optimize all tables that are smaller than a definable size. (That is 100 MB per default) So it will optimize even tables from an addon.

**Comment by annando** [comment]
The admin settings for this pull request are accidentally pushed in the pull request https://github.com/friendica/friendica/pull/2106.

But this no problem as long as both are accepted.

**Comment by Keith2** [comment]
Will optimize_max_tablesize accept s value of -1, for those who wish to disable this?
For InnoDB tables I prefer to do optmizations etc without using mysql's optimze (recreate+analyze is used for InnoDB instead).
Using pt-online-schema-change from percona-toolkit which is not supposed to be blocking.

**Comment by annando** [comment]
Yeah, -1 will work. I will document it.

**Comment by annando** [comment]
@tobiasd Are there concerns for not merging it?

**Comment by tobiasd** [comment]
Yes I was not sure if all concerns were solved

**Comment by annando** [comment]
I think so. It can be disabled and there is a setting for it.

**Pull request merged**
