### PR TITLE
Fix overly strict return value for terminateFriendship methods

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #10844

@copiis Once you pull this, please try to unfollow your Twitter contact again and report any error.

### CODE REVIEW

**Comment by ghost** [comment]
> Part of #10844
> 
> @copiis Once you pull this, please try to unfollow your Twitter contact again and report any error.

Just did a git pull.

There is no change, the attempt to delete Twitter contacts ends with the message "This network does not currently support unfollowing." Twitter contacts are still there and marked as followed.

Trying to unfollow RSS / Atom feeds redirects on a white error 500 page and the feed is still subscribed.

**Comment by MrPetovan** [comment]
Thank you, are you sure you pulled the correct branch? I've removed the `This network does not currently support unfollowing.` message from the code so it shouldn't appear.

**Comment by annando** [comment]
@MrPetovan can you fix the check? I guess that @copiis hadn't fetched that specific branch but had just updated to the latest "develop" branch.

**Comment by MrPetovan** [comment]
That's what I suppose to, and yes, I'll run the damn xgettext script.

**Comment by MrPetovan** [comment]
@copiis Please pull `develop` now and try to unfollow a Twitter contact again.

**Comment by ghost** [comment]
No change, Twitter contact cannot be deleted and the popup with the text "This network does not currently support unfollowing." is also still there.

**Comment by MrPetovan** [comment]
Grmbl.

**Pull request merged**
