### PR TITLE
Issue 11130: Fix API access via web clients / improve method handling

### LINKED ISSUE #11130: Halcyon don't work anymore with RC
In the current RC the web client [Halcyon](https://github.com/halcyon-suite) doesn't work anymore. The client does send an `OPTIONS` command and is expected to receive a list of allowed methods - but it fails with error 500 it seems. But it doesn't work either when temporarily fixing it by directly using the `header` command instead of the exception. I guess that this is the case because the execution is stopped before the access control header are sent.

i can't figure it out, so I hope that @nupplaphil can fix it.

### PR DESCRIPTION
**Pull request by annando**
This fixes #11130. Also the access to the http method had been improved.

### CODE REVIEW

**Comment by annando** [comment]
Some tests are failing. The question is why ...

**Comment by nupplaphil** [comment]
I think I found a less invasive solution, give me some minutes ..

**Review by MrPetovan — APPROVED** [review]

**Comment by nupplaphil** [comment]
@annando - plz have a look at #11135 - this will reduce your stresslevel with these tests *gg*

**Comment by annando** [comment]
@nupplaphil I personally prefer having the HTTP method as some class variable since we use it at many different places. So possibly we should mix our both PRs.

**Comment by nupplaphil** [comment]
I cherry pick it :-)

**Review by MrPetovan — APPROVED** [review]

**Comment by nupplaphil** [comment]
replaced by #11135

**Pull request closed without merging**
