### PR TITLE
Restructure Security classes

### LINKED ISSUE #8796: Composer error message
After last gut pull I get this error message every time I run the command  `bin/composer.phar install --no-dev`

```
Generating optimized autoload files
Deprecation Notice: Class Text_LanguageDetect_ISO639Test located in ./vendor/pear/text_languagedetect/tests/Text_LanguageDetect_ISO639Test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Text_LanguageDetectTest located in ./vendor/pear/text_languagedetect/tests/Text_LanguageDetectTest.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Friendica\Util\PidFile located in ./src/Util/Pidfile.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class OAuthException located in ./library/OAuth1.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class OAuthConsumer located in ./library/OAuth1.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class OAuthToken located in ./library/OAuth1.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class OAuthSignatureMethod located in ./library/OAuth1.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class OAuthSignatureMethod_HMAC_SHA1 located in ./library/OAuth1.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class OAuthSignatureMethod_PLAINTEXT located in ./library/OAuth1.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class OAuthSignatureMethod_RSA_SHA1 located in ./library/OAuth1.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class OAuthRequest located in ./library/OAuth1.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class OAuthServer located in ./library/OAuth1.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class OAuthDataStore located in ./library/OAuth1.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class OAuthUtil located in ./library/OAuth1.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class ASNValue located in ./library/ASNValue.class.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class ASN_BASE located in ./library/asn1.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///patch/to/tze/friendica/installation/htdocs/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
```

### Friendica version you encountered the problem
1. git 2020.06-rc
2. php7.4
3. MariaDB 5.5.5-10.1.44-MariaDB-0+deb9u1

### PR DESCRIPTION
**Pull request by nupplaphil**
Some quick cleanups so we get rid of the composer messages.

And the `library` path is gone ;-)

Needs https://github.com/friendica/friendica-addons/pull/1026 as well

### CODE REVIEW

**Comment by annando** [comment]
I guess this is one of these "please let it run on your system for a few days and observe all PHP error logs"-pull requests ;-)

Where exactly are these functions used?

**Comment by nupplaphil** [comment]
> I guess this is one of these "please let it run on your system for a few days and observe all PHP error logs"-pull requests ;-)

Yes, you're probably right ;-)
But tbh I just moved functionality, I didn't change anything (nevertheless I test the branch on my local node)

> Where exactly are these functions used?

Based on #9325 

A list of all OAuth1 depdenencies in Friendica:

**Addons** (oauth-client)
-  https://github.com/friendica/friendica-addons/blob/develop/statusnet/library/twitteroauth.php
-  https://github.com/friendica/friendica-addons/blob/develop/tumblr/library/tumblroauth.php

**Core** (FKOAuth1 / oauth-server)
-  https://github.com/friendica/friendica/blob/develop/include/api.php

**Comment by annando** [comment]
Do you have the Twitter addon enabled?

**Comment by nupplaphil** [comment]
Yes

I successfully deleted and readded my account :-)

**Comment by MrPetovan** [comment]
Related to #4116

**Pull request merged**
