### PR TITLE
Fix translation strings

### PR DESCRIPTION
**Pull request by MrPetovan**
Follow-up to #4312

Restores `util/extract.php`.
Fix uncapturable strings.

This one is for @tobiasd !

No changes in addons if anyone was wondering.

### CODE REVIEW

**Comment by tobiasd** [comment]
Running `util/run_xgettext.sh` returns a warning about an empty message id in `mod/contacts.php:555`

       $lost_contact = (($contact['archive'] && $contact['term-date'] > NULL_DATE && $contact['term-date'] < datetime_converL10n::t('', '', 'now')) ? L10n::t('Communications lost with this contact!') : '');

But the string is extracted as I would expect. The warning is new to mee though.

Ping @fabrixxm

**Comment by fabrixxm** [comment]
Well, if that's the line the gettext reports, it's different from the one in source
https://github.com/friendica/friendica/blob/develop/mod/contacts.php#L555

    datetime_converL10n::t('', '', 'now'))

does not exists. looks like it found the `t(` in `datetime_convert(` and decided it was the translation function.

**Comment by fabrixxm** [comment]
And I'm missing something but util/extract.php could be removed?
It extracts to strings.php, while we should be using Xgettext and .po workflow

**Comment by tobiasd** [comment]
On Thu, 25 Jan 2018 07:34:50 +0000 (UTC)
fabrixxm <notifications@github.com> wrote:

> It extracts to strings.php, while we should be using Xgettext and .po
> workflow

Yes, that is the way I'm regenerating the messages.po files.

**Comment by MrPetovan** [comment]
Wait, I fixed `util/extract.php` for nothing? 🤦

**Comment by tobiasd** [comment]
No, it's good to have to tools shipped with the code working :-)

**Comment by MrPetovan** [comment]
But if nobody uses it? How is xgettext picking up my crazy `' . "\x28" . '` constructs?

**Comment by MrPetovan** [comment]
It looks fine in the `.po` file, I still think we should scrap `util/extract.php` as it complicates translation strings and apparently doesn't capture as many strings.

**Pull request merged**
