### PR TITLE
[frio] Prevent more action menu to be clipped by the post box

### LINKED ISSUE #8264: Frio: Align the network icons
### Expected behavior
I know that's kind of nitpicking but small things are important, too. :-) I think the network icons in the top corner of posts and comments should be horizontally aligned.
The position looks better in the post. I think it is too near to the border of the background "card" in the comments.

### Actual behavior
Since we removed the drop down menu it is more obvious that the icons are not horizontally aligned.

### Steps to reproduce the problem

Bildschirmfoto von 2020-02-09 20-07-02

### Friendica version you encountered the problem
2020.03-dev

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #8264 

- Address https://friendica.mrpetovan.com/display/0b6b25a8-615e-3dda-937e-21e937937450
- Move external link back to the post top right
- Prevent more action menu to become semi-transparent on post mouseout
- Top level post menu shows below link to prevent shenanigans at the top of the page (nav bar hiding the menu), comment post menu shows above link to prevent shenanigans at the bottom of the page.

friendica-more-links-fix
friendica-more-links-fix-comment
Please note the activity links are semi-transparent while the open menu isn't.

### CODE REVIEW

**Comment by nupplaphil** [comment]
puuh .. frontend stuff .. Looks Good To Me, but I cannot "really" imagine, what the changes will be except of the both screenshots you already added ^^ ... I'm a backend guy ;-)

**Comment by AlfredSK** [comment]
Does it also address the menu cutoff when you have a one line post w/o any comments?

**Comment by MrPetovan** [comment]
Yes, see first screenshot, the menu goes below the post box and would have been clipped before the fix.

**Comment by AlfredSK** [comment]
Ah! The grey on grey confused me. :-) Great!

**Comment by annando** [comment]
Could you have a look at it with Firefox? Chrome looks nice, but Firefox is performing a line feed.

**Comment by MrPetovan** [comment]
Confirmed, the position absolute is interpreted differently, I may have to anchor it on a fixed position in the post action bar like the previous dropdown menu was, likely on the right.

**Comment by annando** [comment]
BTW: I guess from a user perspective's point of view the plink should be the link at the posting date (since there we also describe the origin of the post) while the symbol that is now used for the plink is more often used to open the same content in a new windows.

So possibly we should exchange these both links?

**Comment by annando** [comment]
When you anchor it, please keep in mind that there can also be the checkbox for multiple selections.

It could also be possible to set the whole menubar to "absolute".

**Comment by MrPetovan** [comment]
That's an interesting idea, thanks. I'm afraid about what it would do to the reactions below (X likes this, X shared this, etc...)

**Pull request merged**
