### PR TITLE
corrected change

### PR DESCRIPTION
**Pull request by gerhard6380**
overseen plus signs

### CODE REVIEW

**Comment by gerhard6380** [comment]
sorry, I should not change code late in the evening when I am already tired.

**Comment by annando** [comment]
You should test it before :)

**Comment by strk** [comment]
Tests should be automatic !

**Comment by tobiasd** [comment]
There is a util to spot such things ;-) "typo.php" in the /util directory.

**Comment by strk** [comment]
@tobiasd would you consider enabling travis-ci.org builds for this repository to at least run that `typo.php` ? Would be a start

**Comment by tobiasd** [comment]
They seem to rely on github, as we want to move away, this seems to be contra productive.

**Comment by tobiasd** [comment]
Thanks for fixing @gerhard6380 ;-)

**Comment by strk** [comment]
@tobiasd good point, how about just focusing on a `make check` rule ? Then the travis config would be easy as any other software config (I suggest looking at Drone - drone.io - which also supports gitea.io for moving away)

**Comment by tobiasd** [comment]
drone says "Coming Soon" in big letters to me but already has a shiny price tag(?) looks strange to my. But maybe their page is not working correctly. According to their github page it uses docker - that never seems to work here, but your experience might be different.

**Comment by strk** [comment]
Don't look at drone.io, but rather at github.com/drone/drone

**Pull request merged**
