### PR TITLE
Fix the problem that the post update never stopped on larger systems

### PR DESCRIPTION
**Pull request by annando**
See here: https://forum.friendi.ca/display/0b6b25a8-1662-30dc-3b3d-823780768991

### CODE REVIEW

**Review by MrPetovan — COMMENTED** [review]
Wouldn't it be better to store the maximum ID to process when the update function is first called (the config value wouldn't exist) and then stop when the process reaches this ID?

On smaller systems, this condition may potentially miss up to 100 items to actually process.

**Comment by annando** [comment]
We are always fetching 1000 items. When we have got less than 1000, we are done.

**Comment by MrPetovan** [comment]
I don't get it. It just mean you have less than 1000 left to process.

**Comment by annando** [comment]
`$rows` contains the number of rows that had just been processed. They are the result of the query above where we set a limit of 1000. So when `$rows` is 1000, then there are rows left. Is it less than that, then we are done.

**Comment by MrPetovan** [comment]
Ok, but this isn't the value you used in the condition? Also the code standard check is failing.

**Comment by annando** [comment]
In the condition I'm using the value `1000`, but the check is for `100` just as a safeguard.

The standards check is currently failing since I haven't updated my system to the latest version.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
