### PR TITLE
New table "post-thread-user", removed tabled "user-item"

### PR DESCRIPTION
**Pull request by annando**
The table "user-item" is now completely replaced by the tables "post-user" and "post-thread-user".

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]
This diff is too big for me to understand the possible consequences, I leave it to you, and given my recent difficulties I'll update my node to the next stable.

**Comment by annando** [comment]
@MrPetovan the problems that you experienced had (partially) been caused by a fault in the update mechanism. I guess you can try again.

Concerning the stability: I'm running on this and I'm monitoring all logs to ensure that it works as expected.

**Comment by MrPetovan** [comment]
All right, trying again.

**Comment by MrPetovan** [comment]
After the pull, immediate flux of `"Table 'friendica.post-thread-user' doesn't exist"` errors, no automatic update is taking place, no maintenance mode. 😞

Running `bin/console dbstructure update -f` now.

**Comment by annando** [comment]
The `update -f` could be toxic in the current situation. The pre- and update routines have to work. it is better to reset the database version with the console command.

**Comment by MrPetovan** [comment]
It still going, output so far:
```
ALTER IGNORE TABLE `item` MODIFY `type` varchar(20) COMMENT '', MODIFY `bookmark` boolean COMMENT '', MODIFY `resource-id` varchar(32) COMMENT 'Deprecated', MODIFY `uri-hash` varchar(80) COMMENT 'Deprecated';
CREATE TABLE IF NOT EXISTS `post-content` (
        `uri-id` int unsigned NOT NULL COMMENT 'Id of the item-uri table entry that contains the item uri',
        `title` varchar(255) NOT NULL DEFAULT '' COMMENT 'item title',
        `content-warning` varchar(255) NOT NULL DEFAULT '' COMMENT '',
        `body` mediumtext COMMENT 'item body content',
        `raw-body` mediumtext COMMENT 'Body without embedded media links',
        `location` varchar(255) NOT NULL DEFAULT '' COMMENT 'text location where this item originated',
        `coord` varchar(255) NOT NULL DEFAULT '' COMMENT 'longitude/latitude pair representing location where this item originated',
        `language` text COMMENT 'Language information about this post',
        `app` varchar(255) NOT NULL DEFAULT '' COMMENT 'application which generated this item',
        `rendered-hash` varchar(32) NOT NULL DEFAULT '' COMMENT '',
        `rendered-html` mediumtext COMMENT 'item.body converted to html',
        `object-type` varchar(100) NOT NULL DEFAULT '' COMMENT 'ActivityStreams object type',
        `object` text COMMENT 'JSON encoded object structure unless it is an implied object (normal post)',
        `target-type` varchar(100) NOT NULL DEFAULT '' COMMENT 'ActivityStreams target type if applicable (URI)',
        `target` text COMMENT 'JSON encoded target structure if used',
        `resource-id` varchar(32) NOT NULL DEFAULT '' COMMENT 'Used to link other tables to items, it identifies the linked resource (e.g. photo) and if set must also set resource_type',
        `plink` varchar(255) NOT NULL DEFAULT '' COMMENT 'permalink or URL to a displayable copy of the message at its source',
         PRIMARY KEY(`uri-id`),
         INDEX `plink` (`plink`(191)),
         FULLTEXT INDEX `title-content-warning-body` (`title`,`content-warning`,`body`),
        FOREIGN KEY (`uri-id`) REFERENCES `item-uri` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE
) DEFAULT COLLATE utf8mb4_general_ci COMMENT='Content for all posts';
CREATE TABLE IF NOT EXISTS `post-thread-user` (
        `uri-id` int unsigned NOT NULL COMMENT 'Id of the item-uri table entry that contains the item uri',
        `uid` mediumint unsigned NOT NULL DEFAULT 0 COMMENT 'Owner id which owns this copy of the item',
        `pinned` boolean NOT NULL DEFAULT '0' COMMENT 'The thread is pinned on the profile page',
        `starred` boolean NOT NULL DEFAULT '0' COMMENT '',
        `ignored` boolean NOT NULL DEFAULT '0' COMMENT 'Ignore updates for this thread',
        `wall` boolean NOT NULL DEFAULT '0' COMMENT 'This item was posted to the wall of uid',
        `pubmail` boolean NOT NULL DEFAULT '0' COMMENT '',
        `forum_mode` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '',
         PRIMARY KEY(`uid`,`uri-id`),
         INDEX `uid_wall` (`uid`,`wall`),
         INDEX `uid_pinned` (`uid`,`pinned`),
         INDEX `uri-id` (`uri-id`),
        FOREIGN KEY (`uri-id`) REFERENCES `item-uri` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE,
        FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON UPDATE RESTRICT ON DELETE CASCADE
) DEFAULT COLLATE utf8mb4_general_ci COMMENT='Thread related data per user';
CREATE TABLE IF NOT EXISTS `post-user` (
        `id` int unsigned NOT NULL auto_increment,
        `uri-id` int unsigned NOT NULL COMMENT 'Id of the item-uri table entry that contains the item uri',
        `uid` mediumint unsigned NOT NULL COMMENT 'Owner id which owns this copy of the item',
        `protocol` tinyint unsigned COMMENT 'Protocol used to deliver the item for this user',
        `contact-id` int unsigned NOT NULL DEFAULT 0 COMMENT 'contact.id',
        `unseen` boolean NOT NULL DEFAULT '1' COMMENT 'post has not been seen',
        `hidden` boolean NOT NULL DEFAULT '0' COMMENT 'Marker to hide the post from the user',
        `notification-type` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '',
        `origin` boolean NOT NULL DEFAULT '0' COMMENT 'item originated at this site',
        `psid` int unsigned COMMENT 'ID of the permission set of this post',
         PRIMARY KEY(`id`),
         UNIQUE INDEX `uid_uri-id` (`uid`,`uri-id`),
         INDEX `uri-id` (`uri-id`),
         INDEX `contact-id` (`contact-id`),
         INDEX `psid` (`psid`),
        FOREIGN KEY (`uri-id`) REFERENCES `item-uri` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE,
        FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON UPDATE RESTRICT ON DELETE CASCADE,
        FOREIGN KEY (`contact-id`) REFERENCES `contact` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE,
        FOREIGN KEY (`psid`) REFERENCES `permissionset` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) DEFAULT COLLATE utf8mb4_general_ci COMMENT='User specific post data';
CREATE TABLE IF NOT EXISTS `post-user-notification` (
        `uri-id` int unsigned NOT NULL COMMENT 'Id of the item-uri table entry that contains the item uri',
        `uid` mediumint unsigned NOT NULL COMMENT 'Owner id which owns this copy of the item',
        `notification-type` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '',
         PRIMARY KEY(`uid`,`uri-id`),
         INDEX `uri-id` (`uri-id`),
        FOREIGN KEY (`uri-id`) REFERENCES `item-uri` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE,
        FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON UPDATE RESTRICT ON DELETE CASCADE
) DEFAULT COLLATE utf8mb4_general_ci COMMENT='User post notifications';
```

**Comment by MrPetovan** [comment]
It's done, posts appear but without content, I'll reset my database structure version to 1394.

Edit: new posts since the end of the update have content.

**Comment by MrPetovan** [comment]
Set the `system.build` to `1394`, ran `bin/worker.php` manually, it didn't update the DB. Ran `bin/console dbstructure update`, this is the output:
```
CREATE TABLE IF NOT EXISTS `post-user` (
        `id` int unsigned NOT NULL auto_increment,
        `uri-id` int unsigned NOT NULL COMMENT 'Id of the item-uri table entry that contains the item uri',
        `uid` mediumint unsigned NOT NULL COMMENT 'Owner id which owns this copy of the item',
        `protocol` tinyint unsigned COMMENT 'Protocol used to deliver the item for this user',
        `contact-id` int unsigned NOT NULL DEFAULT 0 COMMENT 'contact.id',
        `unseen` boolean NOT NULL DEFAULT '1' COMMENT 'post has not been seen',
        `hidden` boolean NOT NULL DEFAULT '0' COMMENT 'Marker to hide the post from the user',
        `notification-type` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '',
        `origin` boolean NOT NULL DEFAULT '0' COMMENT 'item originated at this site',
        `psid` int unsigned COMMENT 'ID of the permission set of this post',
         PRIMARY KEY(`id`),
         UNIQUE INDEX `uid_uri-id` (`uid`,`uri-id`),
         INDEX `uri-id` (`uri-id`),
         INDEX `contact-id` (`contact-id`),
         INDEX `psid` (`psid`),
        FOREIGN KEY (`uri-id`) REFERENCES `item-uri` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE,
        FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON UPDATE RESTRICT ON DELETE CASCADE,
        FOREIGN KEY (`contact-id`) REFERENCES `contact` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE,
        FOREIGN KEY (`psid`) REFERENCES `permissionset` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) DEFAULT COLLATE utf8mb4_general_ci COMMENT='User specific post data';

PHP Warning:  session_write_close(): Failed to write session data using user defined save handler. (session.save_path: /var/lib/php/sessions) in Unknown on line 0
PHP Stack trace:
PHP   1. session_write_close() UNKNOWN?:0
```

The `system.build` value hasn't changed.

**Comment by MrPetovan** [comment]
New bit of information, the update fails with this:
```
2021-02-02T17:47:05Z console [ERROR]: DB Error {"code":1452,"error":"Cannot add or update a child row: a foreign key constraint fails (`friendica`.`post-user`, CONSTRAINT `post-user_ibfk_1` FOREIGN KEY (`uri-id`) REFERENCES `item-uri` (`id`) ON DELETE CASCADE)","callstack":"DBA::e, update_1395, Update::runUpdateFunction, Update::run, DatabaseStructure::doExecute, Console::execute, Console::doExecute, Console::execute","params":"INSERT INTO `post-user`(`id`, `uri-id`, `uid`, `contact-id`, `unseen`, `origin`, `psid`)\n\t\tSELECT `id`, `uri-id`, `uid`, `contact-id`, `unseen`, `origin`, `psid` FROM `item`\n\t\tON DUPLICATE KEY UPDATE `contact-id` = `item`.`contact-id`, `unseen` = `item`.`unseen`, `origin` = `item`.`origin`, `psid` = `item`.`psid`"} - {"file":"Database.php","line":765,"function":"e","uid":"d3e9e2","process_id":7610}
2021-02-02T17:47:05Z console [ERROR]: Update function ERROR. {"function":"update_1395","retval":1} - {"file":"Update.php","line":262,"function":"runUpdateFunction","uid":"d3e9e2","process_id":7610}
```

**Comment by MrPetovan** [comment]
What is the magic deletion command I need in this case?

**Comment by annando** [comment]
How is the `post-user` table looking? Does it have got an `id` field? If not please delete that table, Call `bin/console dbstructure version 1394` and then `bin/console dbstructure update` again.

Else please have a look at the database calls in `update.php` from  `update_1395` and following and call them all by hand. Please continue even if there had been an error, then report the error. And please set the system to maintenance before.

When the foreign key constraint sill persists, we can deal with it later.

**Comment by MrPetovan** [comment]
The error I reported was from the first query of the `update_1395`.

**Comment by annando** [comment]
Yeah, question is what the other queries are doing.

**Comment by MrPetovan** [comment]
There's only another query in the update and it didn't run because the first failed.

**Comment by annando** [comment]
Just execute them all by hand via the MySQL console.

**Comment by annando** [comment]
Please also execute this query: ```select count(*) from item where not `uri-id` in (select id from `item-uri`);```

It **should** return a `0`.

**Comment by MrPetovan** [comment]
`post-user` has an `id` field

## update_1395
```
> INSERT INTO `post-user`(`id`, `uri-id`, `uid`, `contact-id`, `unseen`, `origin`, `psid`)
SELECT `id`, `uri-id`, `uid`, `contact-id`, `unseen`, `origin`, `psid` FROM `item`
ON DUPLICATE KEY UPDATE `contact-id` = `item`.`contact-id`, `unseen` = `item`.`unseen`, `origin` = `item`.`origin`, `psid` = `item`.`psid`
Query OK, 1128299 rows affected (8 min 5.349 sec)
Records: 1127080  Duplicates: 2606  Warnings: 0
```

```
> INSERT INTO `post-user`(`uri-id`, `uid`, `hidden`, `notification-type`)
SELECT `uri-id`, `user-item`.`uid`, `hidden`,`notification-type` FROM `user-item`
INNER JOIN `item` ON `item`.`id` = `user-item`.`iid`
ON DUPLICATE KEY UPDATE `hidden` = `user-item`.`hidden`, `notification-type` = `user-item`.`notification-type`
Query OK, 137068 rows affected (22.250 sec)
Records: 69056  Duplicates: 68472  Warnings: 0
```
## update_1396
```
> INSERT IGNORE INTO `post-content`(`uri-id`, `title`, `content-warning`, `body`, `raw-body`,
`location`, `coord`, `language`, `app`, `rendered-hash`, `rendered-html`,
`object-type`, `object`, `target-type`, `target`, `resource-id`, `plink`)
SELECT `item-content`.`uri-id`, `item-content`.`title`, `item-content`.`content-warning`,
`item-content`.`body`, `item-content`.`raw-body`, `item-content`.`location`, `item-content`.`coord`,
`item-content`.`language`, `item-content`.`app`, `item-content`.`rendered-hash`,
`item-content`.`rendered-html`, `item-content`.`object-type`, `item-content`.`object`,
`item-content`.`target-type`, `item-content`.`target`, `item`.`resource-id`, `item-content`.`plink`
FROM `item-content` INNER JOIN `item` ON `item`.`uri-id` = `item-content`.`uri-id`
Query OK, 420530 rows affected, 65535 warnings (44 min 55.985 sec)
Records: 577584  Duplicates: 157054  Warnings: 157054
```
## Counting
```
> select count(*) from item where not `uri-id` in (select id from `item-uri`);
+----------+
| count(*) |
+----------+
|       16 |
+----------+
1 row in set (1 min 29.227 sec)
```

**Comment by MrPetovan** [comment]
Pre-update post’s contents are back, thank you.

Should I be worried about the 16?

**Comment by annando** [comment]
Yeah, this is a foreign key violation. This shouldn't happen. 

Please execute ```select `uri-id`, `uri` from item where not `uri-id` in (select id from `item-uri`);```

If the `uri-id` is not empty in this query, please execute this query:
```insert ignore into `item-uri` (id, uri) select `uri-id`, uri from item;```

Please then execute `bin/console dbstructure dryrun` so that we can check if there are any pending structure changes.

**Comment by MrPetovan** [comment]
```
> select `uri-id`, `uri` from item where not `uri-id` in (select id from `item-uri`);
+--------+----------------------------------------------------------------------------------------------------+
| uri-id | uri                                                                                                |
+--------+----------------------------------------------------------------------------------------------------+
|    738 | https://pluspora.com/objects/8d3f7540116501392f52005056264835                                      |
|    719 | https://diaspora.club/objects/3624cf00114f01392c9e5fce6fa7fff3                                     |
|    722 | https://pluspora.com/objects/0275e660117201392f4c005056264835                                      |
|    723 | https://framasphere.org/objects/8206461011750139cf622a0000053625                                   |
|    720 | https://framasphere.org/objects/dae8c43011200139cf5c2a0000053625                                   |
|    726 | https://diaspora.psyco.fr/objects/9228788011700139fddd38607759d42b                                 |
|    727 | https://joindiaspora.com/objects/aa475a0011ae013906ef002590d8e506                                  |
|    736 | https://sechat.org/objects/d5239150111e013901c9002590d8e506                                        |
|    724 | https://framasphere.org/objects/79685a4011210139cf522a0000053625                                   |
|    792 | https://pod.orkz.net/objects/302ee1f0117b0139a3de00163e3b85e3                                      |
|    725 | https://joindiaspora.com/objects/b92df3d011ae0139073d002590d8e506                                  |
|    781 | https://pod.athrandironline.com/objects/6c1c8d1011b00139e238005056a069e0                           |
|    782 | https://diasp.org/objects/7255fe701120013911ee7085c2fdcc0b                                         |
|    766 | https://pod.athrandironline.com/objects/65ac7d4011b00139e238005056a069e0                           |
|    787 | https://framasphere.org/objects/342ae55011d90139cf702a0000053625                                   |
|    835 | https://pod.geraspora.de/objects/8d3f7540116501392f52005056264835-6d3406f011740139cc9f268acd52edbf |
+--------+----------------------------------------------------------------------------------------------------+
16 rows in set (1 min 55.094 sec)
```
and then
```
> insert ignore into `item-uri` (id, uri) select `uri-id`, uri from item;
Query OK, 16 rows affected, 65535 warnings (1 min 15.531 sec)
Records: 1075114  Duplicates: 1075098  Warnings: 1075098
```
```
$ bin/console dbstructure dryrun

$
```

**Comment by annando** [comment]
That's weird. There is a foreign key on the item table for the `uri-id`. So it shouldn't be possible in any way that there is a missing entry.

**Comment by MrPetovan** [comment]
Final call:
```
$ bin/console dbstructure update
CREATE TABLE IF NOT EXISTS `post-user` (
        `id` int unsigned NOT NULL auto_increment,
        `uri-id` int unsigned NOT NULL COMMENT 'Id of the item-uri table entry that contains the item uri',
        `uid` mediumint unsigned NOT NULL COMMENT 'Owner id which owns this copy of the item',
        `protocol` tinyint unsigned COMMENT 'Protocol used to deliver the item for this user',
        `contact-id` int unsigned NOT NULL DEFAULT 0 COMMENT 'contact.id',
        `unseen` boolean NOT NULL DEFAULT '1' COMMENT 'post has not been seen',
        `hidden` boolean NOT NULL DEFAULT '0' COMMENT 'Marker to hide the post from the user',
        `notification-type` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '',
        `origin` boolean NOT NULL DEFAULT '0' COMMENT 'item originated at this site',
        `psid` int unsigned COMMENT 'ID of the permission set of this post',
         PRIMARY KEY(`id`),
         UNIQUE INDEX `uid_uri-id` (`uid`,`uri-id`),
         INDEX `uri-id` (`uri-id`),
         INDEX `contact-id` (`contact-id`),
         INDEX `psid` (`psid`),
        FOREIGN KEY (`uri-id`) REFERENCES `item-uri` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE,
        FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON UPDATE RESTRICT ON DELETE CASCADE,
        FOREIGN KEY (`contact-id`) REFERENCES `contact` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE,
        FOREIGN KEY (`psid`) REFERENCES `permissionset` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) DEFAULT COLLATE utf8mb4_general_ci COMMENT='User specific post data';

PHP Warning:  session_write_close(): Failed to write session data using user defined save handler. (session.save_path: /var/lib/php/sessions) in Unknown on line 0
PHP Stack trace:
PHP   1. session_write_close() UNKNOWN?:0

$ bin/console config system build
system.build => 1397
```
Everything seems to be in order now.

**Comment by annando** [comment]
Great. So your system is ready for my next PR where the `thread` table is replaced by two other tables :grin:

**Pull request merged**
