### PR TITLE
Reworked delivery and notifier process - changed OStatus behaviour

### PR DESCRIPTION
**Pull request by annando**
notifier.php and delivery.php contained redundant code. The functionality now mostly moved to delivery.php. The notifier.php is cleaned.

This was mainly done to be able to change the OStatus behaviour. In difference to the previous behaviour the system now behaves like this:

* When you comment a Friendica post then your comment will be sent to your OStatus followers as well
* When you comment an OStatus post then your comment will be sent to your Friendica followers as well

The Friendica comment will only be accepted by the remote Friendica server if the OStatus post is present there as well.

Additionally the pull request contains some preparations for native repeated posts in OStatus. This is not ready by now and will be finished in an upcoming pull request.

Additionally there is some test code for session management without using the database since I had some locking issues with it.

### CODE REVIEW

**Comment by annando** [comment]
What is missing on this pull request?

**Comment by tobiasd** [comment]
the ok from @fabrixxm

**Comment by fabrixxm** [comment]
uhm... ok?

**Comment by annando** [comment]
@tobiasd it seemed as if @fabrixxm said "ok" :-)

**Pull request merged**
