### PR TITLE
Integrate perfect-scrollbar to make tests happy

### PR DESCRIPTION
**Pull request by annando**
We hopefully will soon find a better way. But this is a fast solution and will (hopefully) make the tests happy.

### CODE REVIEW

**Comment by annando** [comment]
Ah okay.

**Comment by MrPetovan** [comment]
Closes #8578

**Comment by AlfredSK** [comment]
Hint: The lock file isn't up to date anymore.
`Warning: The lock file is not up to date with the latest changes in composer.json.`

Unfortunately, my upstream repo is a local Gitea instance. So I cannot push an updated file to GitHub.

**Comment by MrPetovan** [comment]
Ah yes, I didn't check that the composer.lock had been updated through Composer (the hash would have changed) instead of a manual edit.

**Comment by annando** [comment]
Sorry, this hack was a little bit too fast, I guess. What do I have to do to clean this?

**Comment by MrPetovan** [comment]
Just run `bin/composer.phar update --lock` and commit the updated `composer.lock` file. There should be no other change than a hash change. If there's dependencies update, you need to add more parameters to the call to prevent it.

**Comment by annando** [comment]
Done

**Pull request merged**
