### PR TITLE
Remove obsolete OExchange module and reference

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #4090 (kind of)

Protocol is obsolete, module is obsolete, and that's one fewer `item_post()` call to manage when we start migrating `mod/item.php`.

### CODE REVIEW

**Comment by annando** [comment]
The XML functionality is a very fragile part. Have you tested it for some hour on your machine, including checks for fatal errors in that time?

**Comment by MrPetovan** [comment]
This was a protocol for posting links from OExchange-enabled websites, it was meant as a universal sharer. This is unrelated to any current federation.

**Comment by annando** [comment]
I just referred to the change in `XML::fromArray(...)` not to the OExchange functionality itself.

**Comment by MrPetovan** [comment]
Ah, yes, I tested it. That’s why I left some `$dummy` variables.

**Comment by annando** [comment]
Please have got a look at the merge conflicts.

**Comment by MrPetovan** [comment]
Of course.

**Comment by MrPetovan** [comment]
Conflicts fixed.

**Review by annando — APPROVED** [review]

**Pull request merged**
