### PR TITLE
Added option to stay on the local machine when clicking on a contact link

### PR DESCRIPTION
**Pull request by annando**
See the discussion here: https://forum.friendi.ca/display/85a863ed-185f-74ae-b020-796600800814

Friendica's behaviour of being redirect to a remote system is always confusing new users. So now there is a user option to change that behaviour.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Closes #2803

**Comment by MrPetovan** [comment]
Is there a place on the contact page where we still expose the remote profile link with remote auth?

**Comment by annando** [comment]
Yes, the avatar picture.

**Comment by hoergen** [comment]
This feature should get more attention because, if you go to your /contact page , select a contact and then the contact profile you'll see the url of the users home server (profile url) BUT if you click on that external url you'll end up on your own server. That is still a bug.

Even if you have selected "stay local" you should be able to follow printed urls.

**Pull request merged**
