### PR TITLE
[frio] Increasing view width for desktop view

### PR DESCRIPTION
**Pull request by Hypolite**
Lately, I've been frustrated with a couple of width-related points on the frio theme:
- There is a large blank space on the right of the screen
- Shared items have large left and right margins which compresses the shared content

This PR aims at solving both those issues. The changes aren't groundbreaking, but they saves a few scrolls when going through the stream.

Before:
screen shot 2016-09-28 at 11 17 48 am

After:
screen shot 2016-09-28 at 11 18 56 am

A couple of notes regarding the increased width of the center column:
- The bootstrap grid has 12 divisions, however so far on desktop frio only used 10 of them (3 left + 10 center), and the right space wasn't preserved for the right aside, which is displayed on the left column under the left aside. I just reclaimed the missing 2 divisions.
- Even when resizing the browser to extreme width, the content doesn't become unreadable with the change because the parent container has a fixed width.

### CODE REVIEW

**Comment by Hypolite** [comment]
Sorry for the merge conflict, it is due to my previous mistakes of submitting pull requests against `master` instead of `develop`.

**Comment by tobiasd** [comment]
HAve you started your branch on the master or on the develop branch? If you want to merge into develop you have to start in develop. They will be united though eventually over the weekend or so.

Best is start on develop and then make the PR against develop as well.

**Comment by Hypolite** [comment]
I initially forked the `master` branch of the `friendica/friendica` repo, and I started working on a branch of it. I'll get it right eventually!

I assume that the `develop` branch will need a merge from `master` because of my previous mistaken pull requests anyway, right?

**Comment by rabuzarus** [comment]
@Hypolite as author of frio I would not accept this PR. I have chosen  the width of the network stream for a particular reason. Readability. Because of being unsatisfied with to much width wich makes it hard for me to read longer posts (because I always slip on the line) was one of the many reason to start a new theme. The width of the stream based on the width what twitter uses as stream width. I'm very interest to leave the stream and aside width how they are. I experimented a lot to have a good balance between the elements (stream, aside, font size) to have a good readability (under the premise not to change too much in the bootstrap framework)

Some notes for other PR's :
To avoid much work wich wouldn't accepted I would suggest to discuss fundamental changes in the friendica developer forum. So we avoid wasting develop time (which can be very frustrating).

Another motivation for Frio is to have a beautiful theme with a good UX. Many parts are missing in the Frio theme. On the one hand it is because of the lack of time but on the other hand it is also because I have no good I idea how to implement it in a real good looking way with a good UX (e.g. the single photo view - ). The philosophy behind Frio is to implement something because it fits the whole Frio/UX concept.
This is something I recognized as a mistake at some other friendica themes. We add something because we have it in the core but we have no real idea about the UX as a whole. But we implement it nonetheless. Someone could fix it later.
I would avoid this for Frio

**Comment by Hypolite** [comment]
Ho @rabuzarus and thanks for commenting.

I'm all for readability myself. This PR was submitted as a way to increase readability. The 505px width makes sense for Twitter because the posts are limited to 140 chars and because the retweet aren't further embedded in this width. Not sure it makes as much sense with longer posts.

My real gripe was with the share margins. With the original margin both outside the shared content and inside, the final content width is 325px, which is not great for content wrapping. I tried to play with the margins, and then I noticed the center column could use a width increase without becoming overly wide on large screens and without taking up space used for anything else.

Since I submitted this issue, I realized that post images take more vertical space ehn the center column is bigger, which defeats the initial point of saving vertical scrolls. I actually don't mind leaving the center column as is (I'm not a UX expert), but the share margins have to change, they're hurting readability right now.

And don't worry about developing time, this was a 2-minute change I didn't think warranted a full-blown issue. Obviously I was wrong but nothing valuable was lost.

**Comment by rabuzarus** [comment]
@Hypolite 
>  I actually don't mind leaving the center column as is

Im glad for that. You are right. With saying that twitter only use 140 characters but the most friendica comments doesn't have more characters. So you have to deal with different requirements. The blessing and the curse of friendica are its universality. This makes it hard for GUI developers. After starting Frio development I spent 2 weeks with comparing the other social networks and I tried a lot of width/font size combinations to get something which fits in the most cases. Sure you are right for very long articles the width is to small but this are not the most common posts.

> My real gripe was with the share margins.
I can understand it. The share margins aren't a good solution. This was something as a result from inspiration through facebook and how they present their shared content. But I'm not very happy with it.

Some thoughts according to shared content:
At the present state a shared post is visually presented as a post in a post. Other themes use a horizontal line to make clear where the where the shared posts starts and ends (with some margins). Frio uses facebooks concept of frame (with margins). Both concepts aren't ideal. We need some good (-looking) solution how to we present this. Of how we make it distinguishable that the one is the post and the other the the shared content. Something which is a pleasure for the eyes without being annoying. I'm very open for new ideas and new concepts.
I'm no fundamentalist if you want lower the margins. But this shouldn't be the end of ideas which we have for presenting shared post in Frio.

BTW: we also need a good concept how to present event posts. They are really ugly and not that good noticeably

**Comment by tobiasd** [comment]
> I'm all for readability myself. This PR was submitted as a way to increase readability. The 505px width makes sense for Twitter because the posts are limited to 140 chars and because the retweet aren't further embedded in this width.

Readability is not so much the margins or the whitespace, it is still somewhat 60 to 80 characters in a well readable font.

As I said, there will be some merging over the weekend most likely and the develop branch will most likely win in conflics.

**Comment by Hypolite** [comment]
> Readability is not so much the margins or the whitespace, it is still somewhat 60 to 80 characters in a well readable font.

Agreed, but too few characters on a line also affects the readability, and that's what I was trying to fix by removing the embedded content huge margins.

**Pull request closed without merging**
