### PR TITLE
First support for user header banner image

### PR DESCRIPTION
**Pull request by annando**
This PR adds the functionality to provide user banners. By now we propagate a fixed one. We cannot upload an individual banner by now. Also it is not displayed anywhere in Friendica, except via the API. Via the API we also provide a default banner for Diaspora accounts who don't support these banners.

### CODE REVIEW

**Comment by annando** [comment]
@nupplaphil something is wrong here with the tests.

Ediit: Seems to be fixed

**Comment by MrPetovan** [comment]
I would like to crop and resize the picture before we merge this PR, to that end [I asked about the common expected ratios in the issue](https://github.com/friendica/friendica/issues/10847#issuecomment-1008183039). Additionally, I don't think it should be merged in the RC branch as it is a work in progress of a new feature.

**Comment by annando** [comment]
There are several small improvements to the picture handling there. Also I deactivated the default picture handling for the user account. So only in the API you will now see the headers.

**Comment by nupplaphil** [comment]
@MrPetovan  - Do you have any doubts about this PR? At least the changes are looking good to me

**Comment by annando** [comment]
I'm running my system with these changes all the time - and I have no problems at all.

**Comment by nupplaphil** [comment]
aaaand we're done ;-)

**Comment by MrPetovan** [comment]
I didn't receive any feedback about the header image size, so I didn't follow up.

**Comment by nupplaphil** [comment]
ups, sry @MrPetovan

**Pull request merged**
