### PR TITLE
Synchronize contacts with the directory server

### PR DESCRIPTION
**Pull request by annando**
There is now a new option to fetch new contacts from a directory server. This is another step towards removing the "Poco"-functionality.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Ah, I realized you added an admin setting without adding its default value in `static/settings.config.php`.

**Comment by annando** [comment]
There are several options on the "Site" page that don't have a default value there - in fact a quick search had found not a single entry. I'm not sure how our policy is here. I guess it had been to enter all settings there that can be set manually by configuration file?

We should talk about this - and handle this - in a different issue.

**Comment by MrPetovan** [comment]
There are two default configuration files:
- `static/defaults.config.php` holds all the config keys that don't have a UI to be set.
- `static/settings.config.php` holds all the config keys that have a UI to be set.

**Comment by annando** [comment]
I suggest that we create an issue for this task for this milestone. This is an ideal task for the RC phase to go through the settings on the "site" page.

**Pull request merged**
