### PR TITLE
added some more minimalism, added annotations, removed some blank lines

### PR DESCRIPTION
**Pull request by hoergen**

### CODE REVIEW

**Comment by hoergen** [comment]
As I heard there is an understandment, that we use tabs instead of blanks in friendica. I started using tabs but didn't delete the "wrong" blanks.
What should I do now? Using tabs or using blanks?

**Comment by MrPetovan** [comment]
For PHP files please use tabs. For CSS files we haven't agreed on a standard, multiple CSS files in the project are using different indentation (tabs, 2/3/4 spaces), so I'll just ask you to pick one and stick with it please.

**Comment by annando** [comment]
@MrPetovan Is there any style guide for CSS files that we could adopt?

**Comment by MrPetovan** [comment]
There are, it's just a matter of picking which one we want:
- WordPress CSS Coding Standards: https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/
- Drupal CSS Coding Standards: https://www.drupal.org/docs/develop/standards/css/css-formatting-guidelines
- Google's CSS Coding Standards: https://google.github.io/styleguide/htmlcssguide.html#CSS
- Twitter/Bootstrap/GitHub's Mark Otto CSS Coding Standards: http://codeguide.co/#css
- MediaWiki CSS Coding Standards: https://www.mediawiki.org/wiki/Manual:Coding_conventions/CSS

I didn't read all of these in details but I assume they are fairly similar in general.

**Comment by MrPetovan** [comment]
Related to #3968

**Pull request merged**
