### PR TITLE
The widgets in the sidebar are now deflated by standard

### PR DESCRIPTION
**Pull request by annando**
The only exception is the group list, since this is used constantly.

### CODE REVIEW

**Comment by AlfredSK** [comment]
Hmm. I'm not sure if I like that change. What is the purpose?

Personally, I use the groups widget very seldom. But I use the forum and the saves folders widget a lot. For my personal use case the changed behavior doesn't seem to be an improvement.

**Comment by annando** [comment]
I think it looks less cluttered. We can - however - create some setting where we define which widgets are open or closed.

**Comment by MrPetovan** [comment]
This is unpolished and needs to be reverted and discussed deeper.

**Comment by annando** [comment]
I would like to have a setting for this or a way to remember the state. Surely we can store the state in some JS cookie?

**Comment by MrPetovan** [comment]
Yes but widgets must be open by default and there must be a clear visual indication they can be toggled.

**Comment by AlfredSK** [comment]
...and it should remember the open/closed state on page reload. Then I could like it. :-)

**Pull request merged**
