### PR TITLE
Foreign keys added

### PR DESCRIPTION
**Pull request by annando**
We now use foreign keys whenever possible. There is a pre-update to clear the database.

The table definitions had to be moved a little bit because of the relationship between the tables.

### CODE REVIEW

**Comment by annando** [comment]
Moving the creation of foreign keys at the end is a completely separate task. This would mean a restructuring of the `DBStructure` class.

**Comment by MrPetovan** [comment]
I just meant for the SQL dump file, not for the DB structure file.

**Comment by annando** [comment]
The dump file is created by the `DBStructure` class.

**Comment by MrPetovan** [comment]
Oof. Ok.

**Comment by AlfredSK** [comment]
@annando How intense is this db update? Does it enable maintenance mode or does it render the node unusable for some time?

Regards,
a careful admin :-)

**Comment by annando** [comment]
I guess it should be less than an hour.

**Comment by MrPetovan** [comment]
I have updated my node this morning from a long while ago, and it's been unavailable for 4 hours and counting. Currently updating the photo table.

**Comment by MrPetovan** [comment]
Final time is 8h45 to update database from version 1362 to 1364.

**Comment by AlfredSK** [comment]
Thanks! libranet.de is already on 1363. The update from 1362 to 1363 was super fast. 
The update on the forum node to 1364 was also very fast. But the database is tiny compared to libranet.de. :-) I think I should announce a downtime for that update.
Thank you!

**Comment by annando** [comment]
Yeah, the photo table stuff takes hours. Squeet.me took about 3 or 4 hours. But the foreign key thingy is comparably fast.

**Comment by AlfredSK** [comment]
Ok. My photo table isn't that big (in MB) because I use the filesystem as storage backend.

**Comment by AlfredSK** [comment]
Hmm. Update took **3 minutes**.

At first I got a mail that something went wrong. This...

```
DB Error {"code":1452,"error":"Cannot add or update a child row: a foreign key constraint fails (`friendica`.`#sql-29cc67_4d275f`, CONSTRAINT `#sql-29cc67_4d275f_ibfk_1` FOREIGN KEY (`iid`) REFERENCES `item` (`id`) ON DELETE CASCADE)","callstack":"DBA::e, DBStructure::update, Update::run, Update::check","params":"ALTER IGNORE TABLE `user-item` ADD FOREIGN KEY (`iid`) REFERENCES `item` (`id`) ON UPDATE RESTRICT ON DELETE CASCADE, ADD FOREIGN KEY (`uid`) REFERENCES `user` (`uid`) ON UPDATE RESTRICT ON DELETE CASCADE; "} - {"file":"Database.php","line":769,"function":"e","uid":"1a1cf4","process_id":4144004}
```

One minute later the success mail arrived.

When I manually run the update with `-f` I get no output. The db version is on 1364 now.

**Comment by annando** [comment]
I guess that two update processes ran parallel. I had this problem at squeet.me.

**Pull request merged**
