### PR TITLE
Set the newest resharer as owner of a thread

### PR DESCRIPTION
**Pull request by annando**
With this change the newest resharer is displayed as thread owner. Only contacts of this specific user are taken. And it isn't done for own posts and for Diaspora posts since there the reshares work differently.

### CODE REVIEW

**Comment by MrPetovan** [comment]
What does this mean for the display of a reshared post?

**Comment by annando** [comment]
It's now looking this way:
Bildschirmfoto 2019-04-03 um 21 18 48

**Comment by MrPetovan** [comment]
But only for AP reshares so far, right? Thanks for keeping the "via X" label. Not sure if modifying the created date on the fly would change the order of display in the network page, however.

**Comment by annando** [comment]
It's not for Diaspora, since Diaspora reshares are working differently. But it works for AP and Twitter.

This creation date thing is for choosing the best resharer. It has nothing to do with the display order.

**Comment by MrPetovan** [comment]
Ah, fair enough, I didn't see the comparison done of the created time.

**Pull request merged**
