### PR TITLE
added new spring theme

### PR DESCRIPTION
**Pull request by davidspring**
I hope I did this right. I will post a related new issue with a summary of the file and line changes I made.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Your PR looks good, but you're basically asking the Core Friendica theme to take over the theme maintenance for all current and future features.

@tobiasd Don't we have a separate repository for community-contributed themes?

**Comment by davidspring** [comment]
I am willing to maintain this theme as long as I am alive. In fact, I did list myself as the maintainer of this theme. 

However, it is very similar to the Vier theme. The only real difference is in the five CSS files. 

How is the Vier theme maintained? 

What I was hoping is that this theme could be added as a third option. Right now, only Frio and Vier are shown as options. 

But if that is not possible, then a listing in some themes repository would also work.

**Comment by MrPetovan** [comment]
> How is the Vier theme maintained?

Very sparingly at the moment, most of the work goes to frio. Only new templates receive backports to vier, but no improvements have been contributed in a while.

**Comment by davidspring** [comment]
I understand. There is not very much to the Vier theme. The templates for Vier and Spring theme are identical except for one word in one template that needed to be be changed from **vier** to **spring**. I am confident that I can easily maintain the spring theme. While I am not very good with PHP, I spent more than 20 years teaching courses in CSS and the CSS I am using for the five spring theme CSS files is very basic.

**Comment by MrPetovan** [comment]
Please submit your theme to the official Friendica community themes repository: https://git.friendi.ca/friendica/themes-community

**Comment by foss-** [comment]
This PR can probably be closed as it is not actionable?

**Pull request closed without merging**
