### PR TITLE
Image handling reworked, new image formats added

### LINKED ISSUE #903: webp support
Any plans on supporting Google's opensourceed webp image format?
https://developers.google.com/speed/webp/

ImageMagick and Facebook now support webp. Chrome and Opera browsers do as well, but not yet Firefox, IE, Safari. Phtoshop doesn't yet either and so some FB users have complained about not being able to edit pics downloaded from FB when using Opera or Chrome but I suppose there could always be a right-click option to download images in other formats.

### LINKED ISSUE #8768: Add correct Webp handling
### Expected behavior
Webp is a kind of video format that can replace gif. Friendica seems to convert those videos to JPEG. 

Friendica should not convert the Webp at all. Either keep it as a video file, proxy it locally as is or load it as remote content. 

### Actual behavior
Webp is converted to a statical image. 

### Steps to reproduce the problem
See here: https://social.yl.ms/display/ab868b8b-1e89-45c6-8959-272afb8a3230

Go to original post to see animated image. 

### Friendica version you encountered the problem
Current dev

### Friendica source (git, zip)
Git

### PHP version
Same as before 

### SQL version
Same as before. 

Can someone confirm that this is not working on her/his node?

### PR DESCRIPTION
**Pull request by annando**
Fixes https://github.com/friendica/friendica/issues/903 and fixes https://github.com/friendica/friendica/issues/8768

This PR contains an overwhaul of the whole image hadling. WebP and BMP are added, AVIF is prepared. Also some bugs are fixed. For example with Imagick we used the wrong command for the image quality, which meant that pictures hadn't been compressed.

Also it fixes a problem with both Bluesky and Twitter. For some days I experienced problems with both systems with the picture upload. Both systems hadn't displayed the pictures, but displayed a white image only. This only happened, when the image handling had done via Imagick and not the GD-Lib. Since Imagick is also much slower, we now only use that library when needed. Means for animated GIF and WebP.

This PR is running on my system for sveral days now (spme time before the start of the RC phase).

The PR https://git.friendi.ca/friendica/friendica-addons/pulls/1465 belongs to this PR.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Does it mean we are now depending on both GD and ImageMagick instead of either?

**Comment by annando** [comment]
No. This behaviour hadn't changed. We can still only use GD - but then animated GIF and WebP won't work.

**Comment by MrPetovan** [comment]
Is this documented anywhere in the installation documentation/wizard?

**Comment by annando** [comment]
Yeah, see Install.md in the section "Requirements":

> Curl, GD, GMP, PDO, mbstrings, MySQLi, hash, xml, zip, IntlChar and OpenSSL extensions

And in the section "Optional":

> PHP ImageMagick extension (php-imagick) for animated GIF support.

**Comment by tobiasd** [comment]
>> PHP ImageMagick extension (php-imagick) for animated GIF support.

Could you make "animated GIF and WebP support" out of it?

**Comment by annando** [comment]
@tobiasd done

**Comment by lapo-luchini** [comment]
> AVIF is prepared

Yay! Can't wait for that!

… but why BMP? The most uncompressed format on the globe. 😇

**Comment by annando** [comment]
@lapo-luchini I had a look at the image types that are supported by PHP: https://www.php.net/manual/en/function.image-type-to-mime-type.php Then I had a look at all image types that are supported by the common browsers and added them.

Concerning AVIF: Due to our minimum requirements we can't process it at the moment. But on capable systems (PHP 8.1 and newer) we can read it and will output it as WebP.

**Comment by AlfredSK** [comment]
This PR seems to produce some PHP warnings. Reported them in the 'PHP Warnings' issue.

**Comment by annando** [comment]
@AlfredSK I can't reproduce it here. How often does this happen?

**Comment by AlfredSK** [comment]
There's also a fatal error ([exception](https://github.com/friendica/friendica/issues/13763#issuecomment-1949934404)) I reported in the PHP error issue. Maybe this is causing the issue. Looks like there is a malformed image URL or the actual domain part is stripped by Friendica. Don't know.

This is my PHP error log from the moment I pulled from GitHub this morning...

```
[17-Feb-2024 09:50:38 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 09:50:39 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 09:50:49 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 09:51:19 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 09:51:20 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 09:51:29 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 09:52:00 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 09:52:01 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 09:52:10 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 09:52:38 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 09:52:46 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 09:52:47 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 09:52:56 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 09:54:46 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 09:57:00 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 10:00:26 UTC] PHP Warning:  preg_match_all(): Null byte in regex in /var/www/html/libranet/src/Object/Image.php on line 103
[17-Feb-2024 10:00:26 UTC] PHP Warning:  preg_match_all(): Null byte in regex in /var/www/html/libranet/src/Object/Image.php on line 103
[17-Feb-2024 10:23:54 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 10:33:12 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 10:33:48 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 10:41:14 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
[17-Feb-2024 10:47:11 UTC] PHP Warning:  unpack(): Type A: not enough input, need 4, have 0 in /var/www/html/libranet/src/Object/Image.php on line 118
```

**Comment by annando** [comment]
The fatal error in fact is unrelated - but we should fix that as well.

**Pull request merged**
