### PR TITLE
Fix the preview mode setting

### LINKED ISSUE #13649: The preview mode for images cannot be changed
- [x] I have searched open and closed issues for duplicates

### Bug Description

The preview mode is permanently set to "no image". If a different selection is made, this will not be applied

grafik

### Platform Info

Friendica Version: 2023-09-RC 

Friendica Source: git

PHP version: 8.1

SQL version: 10.5

https://github.com/friendica/friendica/pull/13646

### PR DESCRIPTION
**Pull request by annando**
This fixes the issue that this setting had been assumed of being a boolean one.
Fixes #13649

### CODE REVIEW

**Comment by AlfredSK** [comment]
Tested. Fixes the preview mode but the field for 'browser update in seconds' still doesn't work. It's always showing 0.001 seconds and cannot be changed.
@annando can you have a look at this as well, please?

**Comment by loma-one** [comment]
Another note: "No preview" generates a WSOD
no log

**Comment by annando** [comment]
@AlfredSK done.
@loma-one Where do you experience the WSOD?

**Comment by loma-one** [comment]
On the /network /profile /community  page

**Comment by annando** [comment]
@loma-one Hmm, that should be unrelated to this PR. Sadly I cannot reproduce it.

**Comment by loma-one** [comment]
I had not tried the "no preview" function before. It is therefore possible that this is an old error that has only just been noticed. 

Close the error here. I will post a new issue for this problem.

Do you have an account on Libranet or loma? You can recreate it there
grafik

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
