### PR TITLE
Seperate blocks in /admin/features.

### PR DESCRIPTION
**Pull request by astifter**
Its hard to distinguish between blocks of settings in the features page. Its
useful to clearly mark the blocks belonging together.

### CODE REVIEW

**Comment by tobiasd** [comment]
What about the other themes? Some CSS work needed there as well?

**Comment by astifter** [comment]
duepontezero and smoothly still need some work, thanks for pointing that out.

**Comment by tobiasd** [comment]
If it is the same for each theme, then maybe you can do the changes in `view/global.css`.

**Comment by astifter** [comment]
I have looked over the other themes and done what I can.

**Comment by astifter** [comment]
Seperate settings boxes work everywhere now. (And clean up whitespace in vier/style.css.)

**Comment by astifter** [comment]
@MrPetovan My branch distinguish_settings_blocks has 3 commits, it seems you just cherry-pick'ed the first one, was this by accident or on purpose?

**Comment by MrPetovan** [comment]
No, I squashed all three commits into one for clarity.

**Pull request merged**
