### PR TITLE
Remove nested <link> tag in poke object creation in mod/poke

### LINKED ISSUE #3158: Dev: unify the behavior of link elements in socialactivity objects
There is a different handling of presenting links in social activity objects. At the moment this does break the poking messages

e.g.:
Sender poke activity object
```
 <type>http://activitystrea.ms/schema/1.0/person</type>
 <title>Max Mustermann</type>
 <id>https://friendica.kommune4.de/contact/1145</id>
 <link>
     <link rel="alternate" type="text/html" href="https://test.kommune4.de/profile/trebor" />
     <link rel="photo" type="image/jpeg" href="https://friendica.kommune4.de/photo/6fe2fd5b8bb04da3b0159a5d15a422ea-4.jpg" />
 </link>
```
Received poke activity object
```
<type>http://activitystrea.ms/schema/1.0/person</type>
<title>Max Mustermann</type>
<id>https://friendica.kommune4.de/contact/1145</id>
<link rel="alternate" type="text/html" href="https://test.kommune4.de/profile/trebor" />
<link rel="photo" type="image/jpeg" href="https://friendica.kommune4.de/photo/6fe2fd5b8bb04da3b0159a5d15a422ea-4.jpg" />
```

You will find the discussion about this issue on https://helpers.pyxis.uberspace.de/display/4029d2ca89586e57ba58109268300550

### PR DESCRIPTION
**Pull request by MrPetovan**
Should fix #3158 

I decided to go with the removal of the nested link tags because of this code in the receiving code:
https://github.com/friendica/friendica/blob/f1c044e3b65b27a1f4e4abec84731b0f1dfd89d6/src/Protocol/DFRN.php#L2152-L2173

### CODE REVIEW

**Comment by annando** [comment]
Are you sure that this works?

**Comment by MrPetovan** [comment]
I based myself on the code itself, specifically the `foreach ($xo->link as $l) {` that loops through all `<link>` tags directly under the `<object>` root tag.

**Comment by annando** [comment]
But I'm confused by the escaping. I can't imagine that this creates some parseable XML. BTW: I just realized that this content cannot be transported via AP at the moment ;-)

**Comment by MrPetovan** [comment]
Yeah, I was wondering about the wrapping `XML::escape` as well, but I trusted @rabuzarus when he said that the double link tag was the root problem. He didn't mention any escaping issue.

**Comment by m4sk1n** [comment]
I think nobody uses poking feature on fb and there’s no similar feature on newer services, facebook messenger just encourages users to send waving hand emoji for this (it’s technically not just a message with emoji, there’s a button to wave back)

**Comment by MrPetovan** [comment]
Thanks for your input.

**Comment by MrPetovan** [comment]
Apparently this fix isn't needed.

**Pull request closed without merging**
