### PR TITLE
You shouldn't use a text variable like an array.

### PR DESCRIPTION
**Pull request by annando**
See this discussion: https://social.yl.ms/display/e18176ef1058cd38c7b45ef326465885

### CODE REVIEW

**Comment by Quix0r** [comment]
Oh, can you please use same email address in commits and here at github? then your account is being correctly linked (see above gray placeholder).

**Comment by annando** [comment]
How do I change that?

**Comment by Hypolite** [comment]
@annando It depends on the client you are using. If you're using command-line, please follow [this GitHub help page](https://help.github.com/articles/setting-your-email-in-git/).

**Comment by annando** [comment]
I found a second way - by accident ;-)

When I looked up my used mail address (since I have so many of them), I just added the one that I seemed to use locally and instantaneously all my commits where now assigned to my account.

**Comment by Quix0r** [comment]
@annando check settings of your git client, if the same email address (and maybe name, but mostly email address) is the same as here or alternatively register+confirm it here so you can claim the commits.

**Comment by tobiasd** [comment]
Check the `~/.gitconfig` and `.git/config` files, or use the `git` commands mentioned in the github help document, those set the values saved in the config files.

**Pull request merged**
