### PR TITLE
changed onKeyUp to onChange

### PR DESCRIPTION
**Pull request by JeroenED**
Because chromium mobile does not trigger a keyup event when pasting a string I changed the event to onchange because this does trigger the update making it possible to paste and save immediately. Workaround was pasting and adding/removing a space.

### CODE REVIEW

**Comment by MrPetovan** [comment]
I remember the `change` event not being triggered instantly when typing something, but instead when the form control lost focus. Is it still the case for browsers not being Chromium Mobile?

**Comment by JeroenED** [comment]
It seems this became default behavior for all browsers. Just tested with firefox mobile and the behavior is the same. I do think this behavior is more wanted. I also intended this at first but could find the right event. I apparently found it now by accident.

**Comment by MrPetovan** [comment]
It seems to still defined as such for `<input type="text">` and `<textarea>`: https://developer.mozilla.org/en-US/docs/Web/Events/change#Description

**Comment by MrPetovan** [comment]
Maybe the `input` event would be better suited? https://developer.mozilla.org/en-US/docs/Web/Events/input

**Comment by JeroenED** [comment]
I will test the different options on sunday. Just 1 question: do we want to parse the string immediately after input and have possible JSON.parse exception? Or do we want to parse it when the input loses focus?

**Comment by MrPetovan** [comment]
If you listen to an event that's constantly firing as one's typing, you have to have a delay (~500ms) to let the user finish typing before processing the input value. Basically on each event, you set (or refresh) a timer that will execute the processing function that takes whatever value there is when it is executed, not when the event was fired.

**Comment by JeroenED** [comment]
Totally forgot about this. Checking now.

**Comment by JeroenED** [comment]
I have checked and I feel more comfortable with on input. Thanks for the suggestion @hypolite.

**Pull request closed without merging**
