### PR TITLE
Escape HTML in event mapping callback

### LINKED ISSUE #12312: [frio] Arbitrary Javascript can be executed in event titles in the grid view
From @matthiasmoritz in https://github.com/friendica/friendica/issues/12311#issuecomment-1335779799

> @MrPetovan it works perfectly fine without bbcode and escaping. But when you add some inline js in the title, you can execute it in the calendar overview.
> Try it out by adding a event with the following titel: 
> `<a href="#" onclick="alert('Hi')">Click Me</a>`
> 
> In the calendar itselfe you can click on that text and js is executed.

Additional info in https://github.com/friendica/friendica/pull/12311#issuecomment-1335800579

> ya, the escaping in the detail view works fine (I guess some template magic?). But in the calendar itself the inline js is executed no matter if we escapeHtml in this methode or not.  
> click_me

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #12312 

... and a couple of usability issues I ran into testing for this issue.

Thanks to @matthiasmoritz for testing for and reporting this issue!

### CODE REVIEW

**Comment by annando** [comment]
Something at the tests doesn't seen to work out.

**Comment by MrPetovan** [comment]
The phpunit process quit before doing anything, I don't have much patience for it.

**Comment by nupplaphil** [comment]
conflicts *g*

**Review by nupplaphil — APPROVED** [review]

**Comment by MrPetovan** [comment]
Fixed.

**Comment by nupplaphil** [comment]
Merged.

**Pull request merged**
