### PR TITLE
Issue 11890: Don't use empty contexts

### LINKED ISSUE #11890: Incorrect allocation of comments and posts
- [x ] I have searched open and closed issues for duplicates

### Bug Description

I think there are big problems with assigning comments to launch posts right now. Comments on different posts are combined into one thread.

Some examples:

- [https://soc.schuerz.at/display/4edd2508-7563-1661-fcca-262595014955](https://soc.schuerz.at/display/4edd2508-7563-1661-fcca-262595014955)
- [https://soc.schuerz.at/display/4edd2508-2063-15ff-85ac-acd887530359](https://soc.schuerz.at/display/4edd2508-2063-15ff-85ac-acd887530359)
- [https://friendica.xyz/display/4edd2508-1263-15e2-3f8d-59d476483200](https://friendica.xyz/display/4edd2508-1263-15e2-3f8d-59d476483200)

### Steps to Reproduce

Comment on one of the posts and see what happens.

Actual Result:

A mixed thread is created, the initial post and comments do not fit together.

Expected Result:

The comments are assigned to the correct posts

### Platform Info

The wrong thread
falsche-Threadzuordnung

The right thread
richtiger-thread

Friendica Version:
Friendica 'Giant Rhubarb' 2022.09-rc - 1482

Friendica Source: git

PHP version: 8.0.23

### PR DESCRIPTION
**Pull request by annando**
Hopefully fixes #11890

### CODE REVIEW

**Comment by xundeenergie** [comment]
This looks, at it should fix the bug. Am I right?

But the broken postings stay broken?

**Comment by annando** [comment]
The brokens ones stay broken.

**Comment by annando** [comment]
@xundeenergie this will be fixed with PR https://github.com/friendica/friendica/pull/11894

**Comment by xundeenergie** [comment]
> The brokens ones stay broken.

Thanks for the info!

**Pull request merged**
