### PR TITLE
Issue #3878 hotfix 2

### PR DESCRIPTION
**Pull request by MrPetovan**
php-encryption has to be reverted to version 1.2 due to key length incompatibility.

Follow-up to #3888

### CODE REVIEW

**Comment by MrPetovan** [comment]
Giving 45 min for anyone to review and merge, after which I'll merge myself given the protocol-breaking status of this.

**Comment by annando** [comment]
I guess I will wait some time before updating my instance ;-)

**Comment by MrPetovan** [comment]
I don't have anymore issues after this PR.

**Comment by zeroadam** [comment]
Sorry about this. Rookie mistake. After catching up with your over night work, I realize that I had been monitoring my friendica.into-access.log and friendica.info-error.log, but had not looked into the main error.log. Though after seeing the fix, not sure I would've known how, but I could've at least brought it up to you all. I will be more careful in the future, and know more where to look for errors!

**Comment by MrPetovan** [comment]
It's okay, `develop` is there for that. it is supposed to be somewhat unstable.

**Pull request merged**
