### PR TITLE
Add page title notification count display

### PR DESCRIPTION
**Pull request by MrPetovan**
Addresses part of #8683

### CODE REVIEW

**Comment by tobiasd** [comment]
Can we have an option in the settings for this? ;-) For me the number is distracting, so I have to close the tab to not always refocus me attention to _work related stuff_

**Comment by MrPetovan** [comment]
There's already an option for this, you can disable the automatic browser update by setting `-1` as the automatic browser update delay.

**Comment by tobiasd** [comment]
Are these not two different things?

When I return to the network stream of Friendica after 3h work it is updated with new stuff and I just can scroll up from where I left it. This is something I do enjoy. But having the distraction on the open tab title with the counter being inserted drawing attention to the new notification.is something unwanted.

**Comment by MrPetovan** [comment]
Yes, it's a small behavior change, but I'm confident you'll get used to it in no time. I don't believe this temporary inconvenience warrants another user setting. Please give it a month.

**Comment by annando** [comment]
I would prefer trying it out as well. We have so many settings that I would prefer to not add too much more.

**Comment by tobiasd** [comment]
Then the solution is to close the Friendica tab which will lead to less interaction with postings... ok.

**Comment by MrPetovan** [comment]
Again, please give it a month. If you still are irremediably distracted by the tab title change in a month, we'll look into a user setting.

**Comment by tobiasd** [comment]
Because Friendica is the first service to offer this "feature" so I cannot estimate from other service experience how it will affect me? Ok, will do...

**Comment by MrPetovan** [comment]
Thank you for your patience.

**Comment by tobiasd** [comment]
Tried it, but it does not work for me. I have to close the Friendica tab.

**Comment by MrPetovan** [comment]
I'm sorry about that. We haven't been receiving additional reports that this particular feature was that disruptive which makes me reluctant to add a setting for it.

**Comment by annando** [comment]
We could make it a setting that is only available in the config file. So it doesn't confuse the users.

**Comment by MrPetovan** [comment]
How do you feel about it @tobiasd ?

**Comment by tobiasd** [comment]
As long as there is such a setting ;-) I would think it would be better on a per-user-level but I can work with the config file as well as long as it is documented. How about a per-user setting, done by the admin with the console tool?

**Pull request merged**
