### PR TITLE
Improved russian translation

### PR DESCRIPTION
**Pull request by soko1**
Complemented and improved russian translation

### CODE REVIEW

**Comment by tobiasd** [comment]
Thanks! Have you made these changes at [transifex](https://www.transifex.com/Friendica/friendica) or only in the strings.php file?

**Comment by tobiasd** [comment]
Oh, just saw your pull request should target the "develop" branch, not master.

I'll do the conversions and move your updates to Transifex if you only updated the strings.php.

**Comment by soko1** [comment]
Hi!
Sorry, but I've wrote it only into the "strings.php" file. Please, tell me what's the best practice.
Thanks.

**Comment by tobiasd** [comment]
No problem at all!

Best would be when you make yourself familiar with the Transifex service and do the translation there. From there you can ether do the conversion by yourself, or let us (me) do it. My workflow for the DE translations is

1. translate at transifex
2. download the messages.po file for use and save it into /view/de/messages.po
3. run the conversion tool in the Friendica directory ````$>php util/po2php.php view/de/messages.po```` which will generate a new strings.php from the messages.po file
4. make a new branch in git and commit the two file
5. make a pull request against the develop branch of Friendicas master repository

You can perform the entire pipe, or just deal with the first step and leave the rest for us. Transifex updates automatically the source message.po file should it change, and so ensures that the translation is done against the current string collection from the develop branch.

**Comment by soko1** [comment]
Thank you very much. 
I'll try to do it all himself :)

**Comment by tobiasd** [comment]
For the way back ````strings.php -> messages.po```` there is also a tool in ````/util```` called ````php2po.php```` the usage is similar to the po2php tool. With the messages.po file from your updated strings.php you should be able to update the translation at Transifex by uploading the messages.po file.

**Comment by soko1** [comment]
I do understand, thank you :)
Tonight I'll make it over!
Is it possible to lock the pull request?

**Pull request closed without merging**
