### PR TITLE
Suppress undefined index notice in Model\Profile

### PR DESCRIPTION
**Pull request by MrPetovan**
Addresses https://github.com/friendica/friendica/issues/6918#issuecomment-501383962
Follow-up to #7250

### CODE REVIEW

**Comment by annando** [comment]
Question: Can the missing index ```cid``` be a hint for a deeper problem? or is it intended that can be missing?

**Comment by annando** [comment]
There is also: ```Undefined index: nickname in src/Model/Profile.php on line 343```

**Comment by MrPetovan** [comment]
`Profile::load` gets called in many contexts, at least `mod/display`, `mod/Profile`, `mod/photos` and `mod/videos`. As a result, the available data in `$profile` varies wildly.

I'll look into the nickname issue as well.

**Comment by annando** [comment]
I'm currently looking at it as well. There is an index ```nick```. I guess this varies from where the profiledata is loaded.

**Comment by MrPetovan** [comment]
For example, in `mod/display.php` the variable `$a->profile` is initialized without the `nickname` field, and `$a->profile` can end up being used in `Profile::sidebar`, which would trigger the notice.

**Comment by MrPetovan** [comment]
However, if you don't get the notice on line 309 as well, this means the profile array has a `url` field but not a `nickname` field.

Anyway, I submitted a quick fix with an `empty()` check but feel free to check all the potential callers.

**Comment by MrPetovan** [comment]
Closed in favor of #7258

**Pull request closed without merging**
