### PR TITLE
Don't check if basepath is writeable / convert App.php to unix newlines

### PR DESCRIPTION
**Pull request by annando**
When the App class was moved into /src a new check was introduced that checked if the Friendica base path was usable. This check also includes if it was writeable. Friendica works in a "read-only" environment as well, so the check was changed with this pull request.

Additionally the new file App.php was changed from the DOS format into the Unix linefeed format.

### CODE REVIEW

**Comment by tobiasd** [comment]
With this PR included I get the following error

> FastCGI-stderr: Stack trace:
> FastCGI-stderr: #0 /.../index.php(22): Friendica\App->__construct('/...')
> FastCGI-stderr: #1 {main}
> FastCGI-stderr:   thrown in /.../src/App.php on line 195

**Comment by annando** [comment]
The error text is important.

**Comment by tobiasd** [comment]
> FastCGI-stderr: PHP Fatal error:  Uncaught exception 'Exception' with message 'Basepath  isn't usable.' in /.../src/App.php:195

The directory in question is read & writeable by the www-data user.

**Comment by annando** [comment]
Look for "directory_usable" in the Friendica logfile on Debug level. This should tell more.

**Comment by tobiasd** [comment]
The temp path settings are not honored it seems. Mine are `/tmp/social.diekershoff.de` but the Friendica log entries are complaining about not being able to write directly in `/tmp/itemcache` which was working with the `itemcache` located in the correct temp path.

**Comment by annando** [comment]
What is the logfile telling?

**Comment by tobiasd** [comment]
> Path "/tmp/itemcache" is not writable for user www-data

But even if it is the stuff should arrive in `/tmp/social.diekershoff.de/itemcache` as set in the settings.

**Comment by annando** [comment]
Could you create another issue for that? This issue only handled some specific part of the checks.

**Pull request merged**
