### PR TITLE
Updated composer.phar

### PR DESCRIPTION
**Pull request by Quix0r**
Updated `composer.phar` to latest 1.x version.

### CODE REVIEW

**Comment by AlfredSK** [comment]
Hmm. I'm getting this warning now:

`You are using Composer 1 which is deprecated. You should upgrade to Composer 2, see https://blog.packagist.com/deprecating-composer-1-support/`

**Comment by Quix0r** [comment]
@AlfredSK That is not because of the upgrade I guess, more because we use an out-dated `composer.phar` here.

**Comment by AlfredSK** [comment]
Well, I'm just wondering about it because there was no warning about an outdated version before the upgrade. ;-)

**Comment by Quix0r** [comment]
Ah, okay. I found this issue over there: https://github.com/composer/composer/issues/10340

**Pull request merged**
