### PR TITLE
Enclose account settings panels in separate forms

### LINKED ISSUE #11371: Unable to change notification settings without changing password at same time
- [x ] I have searched open and closed issues for duplicates

### Steps to Reproduce

1.  step one go to SETTINGS
2.  step two open NOTIFICATIONS 
3.  step three change email notification selection  and click SAVE SETTINGS 

Actual Result:  change is not saved, an error message shows indicating that passwords do not match and that name is too short 

Expected Result: settings would be saved without having to change password .

Work around: Open PASSWORD CHANGE and enter same STRING for old password and new password. 

Open BASIC INFORMATION and enter full name in the FULL NAME field (auto-populated with handle) 

Open NOTIFICATIONS and change the email notification settings

Then press SAVE SETTINGS. Name and password remain the same, Notification settings are saved 

### Platform Info

Friendica Version:

Friendica Source: , version 2022.05-dev that is running at the web location https://libranet.de. The database version is 1452/1452, the post update version is 1452/1452.

PHP version: 7.4
SQL version: MariaDB 10.6

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #11371 for good, hopefully.

Backward compatibility break: I've removed two obsolete hooks, `settings_form` and `settings_post` (`addon_settings` should be used instead). These hooks aren't used in the current official addons, but they might break custom addons.

### CODE REVIEW

**Comment by tobiasd** [comment]
>  I've removed two obsolete hooks, settings_form and settings_post (addon_settings should be used instead

can you add a short note about it into the CHANGELOG file? Just so I don't oversee the break for the release notes.

**Comment by MrPetovan** [comment]
> can you add a short note about it into the CHANGELOG file? Just so I don't oversee the break for the release notes.

Done!

**Comment by annando** [comment]
The tests seem to be slightly picky ..

**Comment by MrPetovan** [comment]
It's only Codecov that was reenabled recently by a Codecov associates, the unit tests themselves pass, this PR can move forward.

**Pull request merged**
