### PR TITLE
Fix #2817 - Move translation language folder in a subfolder of view

### LINKED ISSUE #2817: Move translation language folder in a subfolder of view
This is a minor inconvenience, but it already happened a few times for me. I'm looking for a specific term in the whole Friendica codebase, and it happens to exist in the translation file of all the languages, polluting the results. I'd like to exclude the translation folder from my search, except I can't since it's the root `view` folder that also contains the default templates and the themes.

Proposed change:

- view
   - fonts
   - install
   - php
   - smarty3
   - templates
   - theme
      -vier
      -frio
      - ...
   - **lang**
      - **fr**
      - **de**
      - **...**

It's a small change that tremendously increases the readability of the Friendica folder structure.

List of affected files:
- README.translate.md
- doc/translations.md
- include\pgettext.php
- include\text.php
- util\README
- util\make_credits.py
- util\typo.php

I'm ready to do the change as soon as I have a few approvals.

### PR DESCRIPTION
**Pull request by Hypolite**
Fix #2817.

Disclaimer: I have not been able to test this change yet. On paper it looks good, but you never know.

### CODE REVIEW

**Comment by tobiasd** [comment]
The settings (admin panel and user settings) need to be reworked a bit. They now show "lang".

**Comment by Hypolite** [comment]
On it.

**Comment by tobiasd** [comment]
I have the solution alreay.. In `get_avaiable_languages` the array index needs to be shifted.

**Comment by Hypolite** [comment]
Nice, it saved me some time.

**Pull request merged**
