### PR TITLE
Fix Api\Friendica\Photo|album\Delete endpoints

### LINKED ISSUE #11023: API "api/friendica/photo/delete" doesn't work
- [ Y ] I have searched open and closed issues for duplicates

### Bug Description

`api/friendica/photo/delete` fails to delete photos.

### Steps to Reproduce

1.  Upload a photo
2.  Issue a `api/friendica/photo/delete` to delete it.

E.g. `curl -s -X POST 'https://friends.deko.cloud/api/friendica/photo/delete.json?photo_id=1461045591619d3c028bc7f129095950' -u usr:pass`

Actual Result:

The photo isn't deleted. Error "no photo id" is returned despite it was passed.
API returns HTML even if called as `api/friendica/photo/delete.json`:
```
<html>
	<head>
		<title>Bad Request</title>
	</head>
	<body>
		<h1>Bad Request</h1>
		<p>no photo_id specified</p>
		</body>
</html>
```

Expected Result:

The photo is deleted.

Friendica Version: current develop.

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #11023 

Setting the `null` value in `BaseApi::getRequest` prevents the request key to be taken into account since no type check can be performed.

### CODE REVIEW

**Comment by nupplaphil** [comment]
Did it really work this way? After fixing this part of the bug, I got this one:
```console
Friendica\Database\DatabaseException : Unknown column 'type' in 'where clause'
 /vagrant/src/Database/Database.php:661
 /vagrant/src/Database/Database.php:1419
 /vagrant/src/Database/DBA.php:492
 /vagrant/src/Model/Post.php:327
 /vagrant/src/Model/Post.php:342
 /vagrant/src/Model/Item.php:255
 /vagrant/src/Module/Api/Friendica/Photo/Delete.php:79
 /vagrant/src/Module/Api/Friendica/Photo/Delete.php:40
 /vagrant/src/BaseModule.php:218
 /vagrant/src/Module/BaseApi.php:97
 /vagrant/tests/src/Module/Api/Friendica/Photo/DeleteTest.php:54
```

I had to remove the `'type' => 'photo'` at `Delete.php` because there is neither a key `type`, nor is there a corresponding key with a value `photo` at this view

**Comment by MrPetovan** [comment]
I believe it hasn't worked as intended since the introduction of the `getRequest` call with a `null` value, I can't guarantee the rest of the API method works.

**Comment by MrPetovan** [comment]
I'll leave @nupplaphil the hard job to fix the test. This time the authentication isn't recognized so API tests are failing because `App->isLoggedIn()` returns false.

**Comment by nupplaphil** [comment]
I found a global way to fix this issue :)

**Comment by MrPetovan** [comment]
This smaller scale PR now includes @nupplaphil 's relevant changes from #11044 and @annando 's [suggestion about the nonexistant field](https://github.com/friendica/friendica/pull/11044#commitcomment-61006436).

**Review by annando — APPROVED** [review]

**Pull request merged**
