### PR TITLE
Event details do not render correctly 

### LINKED ISSUE #12308: event details do not render correctly
### Bug Description

If you open details of an Event by clicking in the calendar item, text decorations are not renderd correct.

### Steps to Reproduce
1. Ceate a Event and use linebreaks and decorations in the description
2. click on the calendar item
Actual Result:

Description is not displayed correct.

### Screenshots

smarty_linebreaks_events

### Platform Info

Friendica Version:

Friendica Source: official/dev

PHP version: 7.4

SQL version: unknown

### PR DESCRIPTION
**Pull request by matthiasmoritz**
doubel encoding issue
fixes #12308

### CODE REVIEW

**Comment by MrPetovan** [comment]
Thank you for looking into it, while you're at it, can you please verify the other `BBCode::convertForUriId` calls are required? Can you also please verify the `Strings::escapeHtml` are necessary?

**Comment by matthiasmoritz** [comment]
@MrPetovan it works perfectly fine without bbcode and escaping. But when you add some inline js in the title, you can execute it in the caledar overview.
Try it out by adding a event with the following titel: 
`<a href="#" onclick="alert('Hi')">Click Me</a>`

In the calendar itselfe you can click on that text and js is executed.

**Review by MrPetovan — DISMISSED** [review]
Here we go! 😄

**Comment by MrPetovan** [comment]
Ah wait, I just saw your comment. Inline JS isn't allowed in any field. `BBCode::convert*` methods should make short work of it, but `Strings::escapeHTML` should also be able to take care of it for a fraction of the computing cost.

**Comment by matthiasmoritz** [comment]
ya, the escaping in the detail view works fine (I guess some template magic?). But in the calendar itself the inline js is executed no matter if we escapeHtml in this methode or not.  
click_me
I have no Idea how to fix that.

**Comment by MrPetovan** [comment]
Oh, ok. Would you like to look into this additional issue?

**Comment by MrPetovan** [comment]
It's ok, I'll create a separate issue for this.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
