### PR TITLE
Fix new private message recipient input

### LINKED ISSUE #8999: Submitting of new PM fails
### Expected behavior
When creating a completely new PM the auto-completion list at the TO field should vanish after selecting the desired recipient from the list. Submitting the message should work.

### Actual behavior
The auto-completion list doesn't vanish after selecting the recipient. You can only ignore this obstacle or hit ESC to close the list. Although the name of the recipient is visible now in the TO field submitting the PM fails with 'no recipient selected'.

### Steps to reproduce the problem
Go to /message.
Click on `+` to start new PM thread.
When the cursor is in TO field start typing to get the auto-completion list.
Try to select a recipient.
Try to submit the message.

### Friendica version you encountered the problem
2020.09-dev

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #8999 

It turns out it wasn't theme-specific, all themes were equally affected, and it's concerning we haven't had more user reports about not being able to send private messages. This confirms my belief we should do away with them and instead provide a specific view for private regular posts.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Ah, interesting. Indeed, the pre-filled recipient input would have still worked, only the freeform one didn't.

**Comment by MrPetovan** [comment]
My point is that we are able to "emulate" the private message feature with regular posts with restricted ACL. So the overall feature would still exist, just not with a completely separate data structure and templates anymore.

**Comment by tobiasd** [comment]
DMs are working fine in vier, as you have the list of contacts who can receive DMs to scroll through and pick the contact. I had not checked duepunto TBH ;)

**Comment by annando** [comment]
You have tested this on all themes?

**Comment by MrPetovan** [comment]
Yes, as you can see by the deletion of most theme-specific private message templates.

**Pull request merged**
