### PR TITLE
Use imports in quattro CSS

### PR DESCRIPTION
**Pull request by astifter**
Quattro has 3 styles, the differ only in the color of some elements. Use imports from a single CSS to reduce code complexity.

### CODE REVIEW

**Comment by astifter** [comment]
Oh, this branch is not clean. Contains stuff from PR #5345, should I fix that or does that work for you?

**Comment by tobiasd** [comment]
quattro uses `lessc` to compile the CSS files from the less files. Will recompile the style files from the sources break your changes?

**Comment by tobiasd** [comment]
Also your changes seem to have broken quattro on my node (using Firefox) totally when using one of the color schemes.

**Comment by tobiasd** [comment]
This needs to be reverted.

**Pull request merged**
