### PR TITLE
fix undeclared variables or wrong variable names (/include) - part 1

### PR DESCRIPTION
**Pull request by rabuzarus**
Some variables were not declared. Some variables were not available. And some variables were did have a typo.
This PR fixes this issue for the files in the `/include` directory.

There is one variable where I was unsure how to deal with it. Have a look at `/include/items.php` and the `$no_photos` parameter. The only impact of this variable would be in `function add_page_info_data()` where it would abort the processing. But `function add_page_info_data()` don't get `$no_photos` as a parameter.
The question is: Should `$no_photos` be added as a parameter or should we solve this in another function?

Note:
By adding missing variables the code should be fixed but it could have an impact on how the code will work. Keep this in mind when reviewing the PR.

### CODE REVIEW

**Comment by MrPetovan** [comment]
I think you should add the parameter to `add_page_info_data()`, after all it is expecting it.

**Comment by MrPetovan** [comment]
There are addons using `add_page_info_data()`, please submit the according PR. Sorry for not checking before.

**Comment by rabuzarus** [comment]
Why? The default value of for the parameter `$no_photos` is false. And the addons don't make use of `$no_photos`

**Comment by MrPetovan** [comment]
Related to #4176

**Pull request merged**
