### PR TITLE
[frio] Remove frame around recent photos. (#5496)

### PR DESCRIPTION
**Pull request by astifter**
Also layout file properly.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Hey, long time no see, good to see you back! Sorry if I merged frio-related PRs too hastily, I wasn't sure you were going to show up any time soon.

**Comment by astifter** [comment]
@rabuzarus Sorry about that. What is needed to remove photos-content-wrapper from the style.css? 

Some changes I have made lead to images/albums/recent below /photos/ being now rendered from photo_album.tpl. Is this enough?

**Comment by rabuzarus** [comment]
@MrPetovan It was totally OK to merge these PR's ;-) I'll be away again in a few hours. Bicycle tour part two. The only PR we need to discuss is https://github.com/friendica/friendica/pull/5286

@astifter 
> What is needed to remove photos-content-wrapper from the style.css?

I'll leave in an hour. So I can't have a deep look into it. You need make sure that all pages of the `photos` module have an own frio template (with the `generic-page-wrapper` in it).

**Comment by MrPetovan** [comment]
Have fun!

**Comment by astifter** [comment]
@rabuzarus Have fun indeed! And thanks for the feedback. Take care!
@MrPetovan Since probably nobody says this: thanks for all the work and feedback!

**Comment by MrPetovan** [comment]
Thanks, I appreciate it! I will be much less available over the next three weeks, PR approval rate will probably suffer!

**Pull request merged**
