### PR TITLE
[Frio] Match back-to-top arrow to schemes

### PR DESCRIPTION
**Pull request by vinzv**
_Note: I consider this as some kind of draft for discussion. I'm not convinced by the scroll-to-top concept at all and not really happy with the coloring. But I was curious to find out how this would work._

This PR replaces the unicode arrow by an SVG mask in CSS. This makes coloring by scheme variables possible. Per default it uses the navbar icon's colors. As requested in #9249 it's with a cut out arrow shape which let's content behind it glimpse through:

This is how it looks like:
- Frio Light and Traditional: color unchanged
- Frio Dark (blue accent): 

- Frio Dark (red accent):

- Frio Black (blue accent):

### CODE REVIEW

**Comment by MrPetovan** [comment]
This looks awesome!

**Review by MrPetovan — APPROVED** [review]

**Comment by foss-** [comment]
To move this foward: can we use [this icon](https://www.svgrepo.com/svg/43073/up-arrow)? It is CC0 licensed, looks much lighter, is less distracting and provides better readability if there is text behind that icon.

Double check CC0 is compatible with AGPL, which seems to be the case.

**Comment by MrPetovan** [comment]
I looked at this PR, and unfortunately the CSS `mask` property isn't well-supported across browsers (see https://caniuse.com/css-masks) so we can't accept this solution however elegant it is.

**Comment by foss-** [comment]
Maybe use new icon and apply link color in all themes. This would still solve the original problem to 1. use more modern icon 2. use color which better fits the various theme options. Link color would still fit better than the pale grey currently in use I guess.

**Comment by MrPetovan** [comment]
I'm not sure how to use the modern icon without the CSS mask but the current button colors can be changed.

**Comment by MrPetovan** [comment]
Superseded by #9726

**Pull request closed without merging**
