### PR TITLE
i18n ru intval bug

### PR DESCRIPTION
**Pull request by Alkarex**
Should fix:

> Got error 'PHP message: PHP Warning:  A non-numeric value encountered in /.../view/lang/ru/strings.php on line 5

PHP 7.2.5 / Ubuntu 18.04 LTS

### CODE REVIEW

**Comment by tobiasd** [comment]
I'm not sure this will help much. The strings.php file will be recreated once there is a new translation at Transifex. So the question is, why the line was not added to the strings file the last time it was recreated.

**Comment by tobiasd** [comment]
Consistently no of the other translation files have that line. The generation process of the strings file (console po2php) needs to be fixed.

**Comment by Alkarex** [comment]
Ok, and the tests fail only for PHP 7.1. There seems to be something strange there...

**Comment by tobiasd** [comment]
Regarding the testing, see #5066

**Comment by Alkarex** [comment]
https://github.com/friendica/friendica/pull/5072/commits/f980516545f4146c0e5017f940c7353670ece2d4

**Comment by tobiasd** [comment]
Do you like to run something like

    for i in view/lang/*/messages.po
      bin/console po2php $i
    end

to recreate the strings.php files for all the languages to add the new line everywhere? (it is fish syntax, your shell might need a different one)

**Comment by Alkarex** [comment]
Done

**Comment by tobiasd** [comment]
Thanks!

**Pull request merged**
