### PR TITLE
Possible fix for issue 4013

### PR DESCRIPTION
**Pull request by annando**
This *could* fix issue https://github.com/friendica/friendica/issues/4013

### CODE REVIEW

**Comment by MrPetovan** [comment]
This won't fix the issue for top-level posts, though, will it?

The function you just changed is the issue: it assumes that all the connection of a Free Love page should be bi-directional, and "fix" them in a function supposed to check for post permission.

I'm going to change my page type at once since I'm not sure we should change this error-correcting behavior.

**Comment by annando** [comment]
I was unsure if I should remove the whole code.

**Comment by MrPetovan** [comment]
I don't know enough about the intention behind the Free Love page type and if it actually needs to be fixed afterwards in certain cases, but as a general rule I don't think we should change the relationship status in a permission checking function.

**Comment by annando** [comment]
Okay, I removed it.

**Comment by annando** [comment]
I would like to keep it shortly before the release. It is easier to undo when the code is still visible.

**Comment by MrPetovan** [comment]
I hear you, but the way you would know if you need to revert it would still be the same, comment or not. What would change only is the way you would revert the deletion, and meanwhile the code stays clean.

**Comment by annando** [comment]
During the develop phase I don't see a huge problem in not having the code totally clean and the retrieval will be easier.

**Comment by MrPetovan** [comment]
You know I'm going to tease you about it when it will be included in the 3.6 release, right?

**Comment by annando** [comment]
I really count on you for doing so! You know, I can concentrate and focus like a squirrel - so any help is appreciated.

**Pull request merged**
