### PR TITLE
[frio] Add new asynchronous submission of modal form

### LINKED ISSUE #4599: frio: Submit posts asynchronously in the modal (aka don't jump to top of timeline after re-sharing a post)
**Currently**
When sharing a post an overlay is shown. That's great but as soon as the "Share" button is pressed users find themselves at the top of their stream.

**Expected**
Without the technical background I can see no good reason UI wise to do this. Users loose their place in the feed and reading and sharing becomes a very frustrating thing up to the point where users will not share posts, they'd like to share, because they are tired of scrolling back down and searching for their position where they last were before sharing a post.
Request: why not share the post and stay at the exact position in the stream/feed?

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #4599

This is it, my masterpiece, my magnum opus. I don't think I will have as much impact on Friendica and its users than with this PR. After this I can pack and leave, my work will be done (I won't).

While testing this feature, I may have let an exhilarated laugh out even though I was alone in my living room.

The best news? This works for new posts, shares and edit. It puts the Compose page to shame, and I will have to find it additional uses like drafts, scheduling or something because it has been rendered completely obsolete by this marvel of engineering.

Am I rediscovering Asynchronous Javascript and XML in 2020? Maybe, but it feels goooooood!

### CODE REVIEW

**Comment by valvin1** [comment]
Impatient to test it 😃

**Comment by nupplaphil** [comment]
Nice work :) I"m curious how it will work! Changes are looking good to me. So here we go :)

**Comment by AlfredSK** [comment]
Great! So we finally found our frontend-developer? :-)

**Comment by MrPetovan** [comment]
Oh you realized that just now?

**Comment by nupplaphil** [comment]
ALL HAIL TO @MrPetovan , OUR NEW FRONTEND DEV!!!!!11111eleveneleven
I'll instantly assign all UI-issues to you :D

**Comment by MrPetovan** [comment]
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,..................,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@(****/@@@@@@*/................................**@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@*********...........................................*(@@@@@@@@@@@@@@@@@
@@@@@@@#**********,..............................................(&@@@@@@@@@@@@@
@@@@@@*************,.................................................@@@@@@@@@@@
@@@@@****************,.................................................%@@@@@@@@
@@@#******************,..................................................&@@@@@@
@@&********************,...................................................@@@@@
@#**********************.....................................................@@@
@/**********************,....................................................*@@
@************************......................................................@
&.,*********************,......................................................(
...,*******************,........................................................
.....,***************,..,/(####(/,...............*(#####(*......................
.........,,,***,,,...,(%%%%%%%%%%%%#,........,/#%%%%%%%%%%%#/,..................
...................,#%%%%%%%%%%%%%%%%#,....,/%%%%%%%%%%%%%%%%%/,................
...................#%(,,...........,(%#,.../%#*,...........,*#%/................
................................................................................
................................................................................
................................................................................
................................................................................
@.....................................,,,,,....................................(
@&..............................,*#%%%%%%%%%%#/,..............................(@
@@@...........................,(%%%%%%%%%%%%%%%%#*...........................(@@
@@@@.........................*%%#(//**,,,,,**/(#%%(,........................@@@@
@@@@@#.......................,....................,,.......................@@@@@
@@@@@@@(.................................................................@@@@@@@
@@@@@@@@@%............................................................*@@@@@@@@@
@@@@@@@@@@@@.,......................................................@@@@@@@@@@@@
@@@@@@@@@@@@@@@(.................................................@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@#/.........................................&@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@**.............................*@@@@@@@@@@@@@@@@@@@@@@@@
```

**Comment by MrPetovan** [comment]
THIS IS AWESOOOOOOME!

Why didn't I do that earlier, seriously, how misled were I about issue priorities?

This PR gives the concept of dog-fooding a new perspective.

**Pull request merged**
