### PR TITLE
Add support for token strings in HTTPSignature::parseSigheader

### LINKED ISSUE #8847: HTTP Signature: Allow header values without quotes
### Expected behavior
HTTP Signature parsing should support parsing values without quotes. According to the spec, each sig-param can be _either_ a quoted-string or a token, where "token" means /[!#$%&'*+\-.^_`|~0-9A-Za-z]+/

### Actual behavior
As seen in `src/Util/HTTPSignature.php`, Friendica appears to be requiring quotes for each value in the Signature header

### Steps to reproduce the problem
- Send an ActivityPub activity to an inbox with a Signature header that doesn't use quotes for all values
- Friendica logs "Invalid HTTP signature, message will be discarded."

### Friendica version you encountered the problem
59c42a92

### Friendica source (git, zip)
git

### PHP version
7.4.7

### SQL version
10.1.30-MariaDB

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #8847

This enhancement led me to find that `Crypto::unencapsulate` could never have worked since it's been ported from Hubzilla.

I do not believe it has ever been used either.

### CODE REVIEW

**Comment by annando** [comment]
This looks fine on the first glance. However have you tested it for some time?

**Comment by MrPetovan** [comment]
I've added a test to ensure I didn't break anything that was already working. Running it I was able to catch a regular expression issue this way, and I had to refine my initial naive handling of obsolete folds of the Signature header value. I didn't change any other part of the HTTP Signature handling.

I've potentially and finally enabled encrypted signature headers but I didn't test it myself because I have no idea how to generate the cipher text and it wasn't the point of my work.

**Comment by annando** [comment]
Besides the tests have you received messages from AP systems while this coding had been active?

**Comment by MrPetovan** [comment]
No, I've broken my dev instance, just fixed it, so I'll see how it goes.

**Comment by MrPetovan** [comment]
I've since received successfully 37 items (top-level, reshare and reply) from 6 different accounts, both on Friendica and Mastodon.

**Pull request merged**
