### PR TITLE
Revert "The widgets in the sidebar are now deflated by standard"

### PR DESCRIPTION
**Pull request by MrPetovan**
Reverts friendica/friendica#8080

Multiple users have been confused by this change, we need to rethink it to make it user-friendly and better user-controllable.

### CODE REVIEW

**Comment by annando** [comment]
I would vote for inverting, but not reverting for a start.

**Comment by MrPetovan** [comment]
What does inverting mean in your message?

**Comment by tobiasd** [comment]
I think "click to close" as opposite of "click to open"?

**Comment by annando** [comment]
Yes

**Comment by MrPetovan** [comment]
Fair enough, but there are more provisions to the design as described in #8080, I still think this should be reverted while someone™️ is woking on the full solution.

**Comment by AlfredSK** [comment]
> I still think this should be reverted while someone is working on the full solution.

Yes, please. The UX isn't good enough to leave it as it is now.

**Comment by annando** [comment]
I will try having a look at it this weekend.

**Comment by MrPetovan** [comment]
Can we please revert until then? It isn't that big of a deal but it would help nodes regularly pulling from the `develop` branch.

**Comment by annando** [comment]
Can you invert it instead? I really would vote for this solution.

**Comment by MrPetovan** [comment]
That's what I expect you to do this weekend hopefully. This revert only undoes the confusion introduced by the unfinished PR.

**Comment by annando** [comment]
See here: https://github.com/friendica/friendica/pull/8092

**Comment by MrPetovan** [comment]
Closed in favor of #8092

**Pull request closed without merging**
