### PR TITLE
"item-delivery-data" is now "post-delivery-data"

### PR DESCRIPTION
**Pull request by annando**
For the conversion to the new post structure we have to use the `uri-id` for references instead of the item id.

This is a draft request since the PR #8573 has to be accepted first (because of the database version number)

### CODE REVIEW

**Comment by AlfredSK** [comment]
Oh! Another postupdate. 🎉 How many days does it take this time? 😜

**Comment by annando** [comment]
@MrPetovan the branch is merged now with the current develop branch

**Comment by MrPetovan** [comment]
We have to fix the dependency drop issue first, it's making all builds fail.

**Comment by MrPetovan** [comment]
Blocked by https://github.com/friendica/friendica/issues/8578

**Comment by annando** [comment]
And I reassured that the PR #8573 needs to be accepted first.

**Comment by annando** [comment]
Merge conflicts cleared

**Pull request merged**
