### PR TITLE
Move PConfig to DI::pConfig()

### PR DESCRIPTION
**Pull request by nupplaphil**
- Move `PConfig::load()` to `DI::pConfig()->load()`
- Move `PConfig::get()` to `DI::pConfig()->get()`
- Move `PConfig::set()` to `DI::pConfig()->set()`
- Move `PConfig::delete()` to `DI::pConfig()->delete()`
- Remove unused `use` statements & remove `PConfig` class

No more  "PConfig" references found in the whole codebase and checked for additional `use DI` statements :-)

Needs https://github.com/friendica/friendica-addons/pull/946 as well

### CODE REVIEW

**Comment by MrPetovan** [comment]
Are you **sure** there aren’t any more uses of `PConfig`?

**Comment by nupplaphil** [comment]
Bildschirmfoto vom 2020-01-18 18-13-03

**Comment by MrPetovan** [comment]
What about Match Case and no colons?

**Comment by nupplaphil** [comment]
just find the PConfig in the Model namespace and Every `PConfiguration` based class...

**Comment by nupplaphil** [comment]
The more difficult thing was to step through each class and check if the `DI::` usage is new so I do need a additional `use Friendica\DI;` statement.

**Comment by nupplaphil** [comment]
I fully understand you, and I appreciate your feedback, since some of my PRs causes troubles and you a lot of work!

**Comment by MrPetovan** [comment]
Missed one! https://github.com/friendica/friendica/commit/0b9aec4569d38f16c3310e5f7db1b1d0e04bb72d

**Comment by nupplaphil** [comment]
-.-**** I even let PHPStorm inspection run .. Did you found it by accident or do you have additional checks I may adapt too?

**Comment by MrPetovan** [comment]
I got it while I was working on my branch that I just rebased on `friendica/develop`. The inspection should have caught in PHP -> Missing classes

**Pull request merged**
