### PR TITLE
Fix unfollow for sharing-only contacts

### PR DESCRIPTION
**Pull request by MrPetovan**
- Add new `"acquaintance" relationship
- Fix searching contact when unfollowing
- Fix new relationship set after unfollowing

### CODE REVIEW

**Comment by annando** [comment]
I see the direction. Currently you had to delete the contact to end the relationship. But I have the feeling that there could be several hidden obstacles. Have you checked at the different protocols what does happen when content arrives from an "acquaintance"? And what happens when contact request arrive from an "acquaintance"? Does the system creates a new contact entry or does it changes the relationship automatically? Currently when we are already following someone and the other one does now wants to follow us as well, the relationship is changed automatically (AFAIK). What is happening now?

Additionally when you search for persons, the system tells the relationship. This function needs to be updated as well. And what happens when you want to (re-)connect this contact?

Before accepting this PR, I guess we had to have a look at the complete code where the relations are currently used if there are placed that need to be changed.

**Comment by MrPetovan** [comment]
Since I don't have enough remote accounts nor time to test all of these, I'll guess I'll just change the unfollow behavior for sharing-only contacts then. from changing the relationship status to removing the contact

**Comment by annando** [comment]
I would like to have a closer look at it in the next release when we will have more time to see the possible issues with this.

**Comment by annando** [comment]
When you write something that removes the contact, please use the ```Contact``` functions  ```terminateFriendship``` and ```remove```.

P.S.: for the next version we should probably create a function ```delete``` that combines these two calls.

P.P.S.: For the future I would like to have the "follow" and "unfollow" behaviour like other networks are doing - instead of deleting the contact.

**Comment by tobiasd** [comment]
> P.P.S.: For the future I would like to have the "follow" and
> "unfollow" behaviour like other networks are doing - instead of
> deleting the contact.

Hopefully this does not include the removal of the ability to not accept new followers before they are actual contacts. Having the ability to accept or discard an introduction is a great feature for me.

**Comment by annando** [comment]
This is unrelated.

**Comment by tobiasd** [comment]
> This is unrelated.

Ok, then I'm relieved.

**Comment by MrPetovan** [comment]
> For the future I would like to have the "follow" and "unfollow" behaviour like other networks are doing - instead of deleting the contact.

Me too, having only a single row in the contact table for each local or remote contact, and a separate `user-contact` table to manage the relationships, including blocking/ignoring without following like you did already.

**Comment by annando** [comment]
This "user-contact" thingy would be nice - but much work. I already thought about this as well. Problem is with feeds where you have to be in control of every field.

**Comment by MrPetovan** [comment]
What's the issue with feeds specifically?

**Comment by annando** [comment]
On feeds you should be able to define data like the avatar or the name, which is overwritten automatically on every other network type. So possibly we should move to using this "user-contact" table for regular network types and an own contact entry for feeds. That's possibly. But I guess I will start something like this earliest next year.

**Pull request closed without merging**
