### PR TITLE
Threads are now always enabled.

### PR DESCRIPTION
**Pull request by annando**
We discussed about this on the Hackathon.

### CODE REVIEW

**Comment by MrPetovan** [comment]
One of the best features of Friendica! I was wondering if we should disable it selectively for protocols that don't support them like Diaspora posts? D* users always reply to the top-level posts anyway.

**Comment by annando** [comment]
The Diaspora protocol supports this threading. Only their frontend doesn't.

**Comment by MrPetovan** [comment]
That’s what I meant, store threading but display flat list for Diaspora top-level posts to match their frontend.

**Comment by annando** [comment]
When a Friendica user responds in a Diaspora on a specific comment, it will be shown at the correct place at another Friendica instance. That's the same with likes on comments or (in the future) even dislikes. Diaspora doesn't support it - but will transmit it.

**Comment by MrPetovan** [comment]
I guess you're right, I'm trying to iron out the remaining threading inconsistencies but it's because of inconsistent data from Diaspora, so there's nothing much we can do on our end.

**Pull request merged**
