### PR TITLE
Issue 8546: Added option to not use prepared statements

### PR DESCRIPTION
**Pull request by annando**
This possibly helps with issue https://github.com/friendica/friendica/issues/8546

There is a new experimental database configuration parameter that disables the usage of prepared statements: `emulate_prepares`

it is used this way:
```
        'database' => [
                'hostname' => 'localhost',
                'username' => 'user',
                'password' => 'totallysecurepassword',
                'database' => 'database',
                'charset' => 'utf8mb4',
                'emulate_prepares' => true,
        ],
```

This is nearly untested and added more to debug the problem than to be the final solution.

### CODE REVIEW

**Comment by annando** [comment]
No, it mustn't. That value has the very ugly side effect that the result set then only contains strings and `NULL` values. All integer and boolean values are converted to strings as well - and this is ugly and can have ugly side effects.

This new setting emulates the behaviour as if that value was set.

**Comment by MrPetovan** [comment]
I have enabled it on my server, but I still get `Prepared statement needs to be re-prepared` errors when querying views.

**Comment by annando** [comment]
Meh ...

**Comment by MrPetovan** [comment]
I'd like to revert this PR since it introduces unneeded complexity that doesn't solve anything. And like you said, it was for debug, so I expect no hard feeling removing it.

**Comment by annando** [comment]
Are you sure you configured it correctly? We aren't using prepared statements at all when my coding was right. This is something I would like to have a look at before reverting it.

**Comment by MrPetovan** [comment]
I believe statements are still prepared even if there are no parameters or `query()` is used. I verified the value of the flag in the Database class to make sure. Maybe it has to do with `PDO::ATTR_EMULATE_PREPARES` being explicitly set to `false`.

**Comment by annando** [comment]
How does this `Prepared statement needs to be re-prepared` appear? Is it as `DB Error` in the Friendica log or somewhere else?

**Comment by annando** [comment]
BTW: What does `mysqltuner.pl` suggest?

**Comment by MrPetovan** [comment]
It's been repeatedly suggesting stuff that made my server unstable and randomly drop queries, so it's grounded now.

**Comment by MrPetovan** [comment]
> How does this `Prepared statement needs to be re-prepared` appear? Is it as `DB Error` in the Friendica log or somewhere else?

It doesn't appear until I manually dump the `Database->error` member.

**Comment by annando** [comment]
I'm using `mysqltuner.pl` to suggest settings. Then I have a look at the setting to make sure what it does - then I change it. Question is, if the system suggests something for that specific value.

**Comment by annando** [comment]
Could you check if Friendica itself is generating error messages as well? How does this error manifest itself?

**Comment by MrPetovan** [comment]
I manually edit `src/Database/Database.php` to display the eventual error protected by an `if ($table == 'owner-view'){` to avoid too many side-effects.

**Pull request merged**
