### PR TITLE
Security Hotfix Release

### PR DESCRIPTION
**Pull request by MrPetovan**
Included the main security fix:
- https://github.com/nupplaphil/friendica/commit/053075533292b3cca26aed582e504c8f7fa8c7cc

Forum fixes:
- https://github.com/friendica/friendica/pull/12539
- https://github.com/friendica/friendica/pull/12540
- https://github.com/friendica/friendica/pull/12655

Worker moderation:
- https://github.com/friendica/friendica/pull/12615

We still need to name the release.

### CODE REVIEW

**Comment by nupplaphil** [comment]
Don't know why two checks are skipped.. seems like a woodpecker bug, rest looks good

**Review by nupplaphil — APPROVED** [review]

**Comment by MrPetovan** [comment]
The license check fails because we still use 2022 in the modified files.

**Review by annando — APPROVED** [review]
From my point of view it looks okay. But we should test it at least at some system for a day or so, I think.

**Comment by MrPetovan** [comment]
Both my own nodes are too far ahead for this.

**Comment by nupplaphil** [comment]
Can you start a local instance and do some particular regression tests?

**Comment by AlfredSK** [comment]
When someone tells me if there's a branch to checkout from stable I can test it.

**Comment by MrPetovan** [comment]
There is! Although you have to import my remote:
```
git remote add MrPetovan https://github.com/MrPetovan/friendica
git fetch MrPetovan
git checkout MrPetovan/stable
```
This will put your repository in a detached HEAD mode pointing at the latest commit in my `stable` branch where you won't be able to use `git pull` anymore.

If I had more commits to my branch, you can update your repository again with
```
git fetch MrPetovan
git checkout MrPetovan/stable
```
Once we merge my branch into the main repository, you can tear down the temporary structure like this:
```
git checkout stable
git pull
git remote remove MrPetovan
```

**Comment by AlfredSK** [comment]
```
root@librabox2 ~/html/libranet
 # sudo -u www-data git status                    
HEAD detached at MrPetovan/stable
```
Ok. Let's see.

**Comment by MrPetovan** [comment]
Please test forum interactions to make sure they still work.

**Comment by AlfredSK** [comment]
Posted something to a local forum. Interacted from another Friendica node and Misskey. Seems to be ok.
Posted something to our helpers forum. And interacted with some forum posts. Looks ok, too.

**Comment by nupplaphil** [comment]
@tobiasd - Can you create hotfix release notes?

**Comment by AlfredSK** [comment]
> git remove MrPetovan

I guess it should be `git remote rm MrPetovan`, right?

**Comment by MrPetovan** [comment]
Yes, sorry.

**Pull request merged**
