### PR TITLE
[frio] Word Wrap for long words in comments

### PR DESCRIPTION
**Pull request by JonnyTischbein**
Credits to @MrPetovan in Issue #5851

Fixing long words my adding word wrap in comments.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Can you please add the same CSS property in the vier theme please?

**Comment by JonnyTischbein** [comment]
I missed something. Still not working in `Firefox 62.0.3 (64-bit)`
I reloaded and it was gone and know what happend..

**Comment by AlfredSK** [comment]
This went terribly wrong:

bildschirmfoto von 2018-10-09 21-00-06

All lines are wrapped in the middle of words. Happens in posts and comments.
Please fix or revert. Thank you.

**Comment by MrPetovan** [comment]
Fair enough, reverting.

**Pull request merged**
