### PR TITLE
The poller is now the worker and we have a "scripts" folder

### PR DESCRIPTION
**Pull request by annando**
Hopefully this will not affect the ongoing changes from @MrPetovan 

All executable scripts are now moved out of the ```include``` folder.

Additionally all occurrences of "poller.php" are renamed to "worker.php" since the scripts doesn't do any polling for some time now.

### CODE REVIEW

**Comment by tobiasd** [comment]
Mean everybody has to change their cron jobs?

**Comment by annando** [comment]
Yeah, this will be fun :-)

**Comment by AlfredSK** [comment]
Oh! The cronjob has to be changed to meet the new path and file name. Right? So, I better disable my nightly cronjob for git-pulling from develop to be able to make both changes at once.

**Comment by MrPetovan** [comment]
Yay! This makes way better sense, I can't believe I managed to talk you into actually doing it 😋

**Comment by MrPetovan** [comment]
Pulling back from merging until @AlfredSK is ready.

**Comment by AlfredSK** [comment]
😂 cronjob for updates disabled. Good night.

**Comment by zeroadam** [comment]
Should there be a support forum post about this?

**Comment by annando** [comment]
You have the job.

**Pull request merged**
