### PR TITLE
Made Connectors on new composer popup more visible

### PR DESCRIPTION
**Pull request by hoergen**
Used green background color to show that "Connetors" are clickable

### CODE REVIEW

**Comment by MrPetovan** [comment]
The green color has a specific meaning in interfaces and may not play well with some custom themes out there, what was the problem exactly?

**Comment by hoergen** [comment]
I made the Connectors section as well green because the original version looked like normal text and wasn't pointed out as a additional clickable option.
Now it as recognizable as an option with sub options.

**Comment by hoergen** [comment]
Maybe you didn't notice: This is a change for the plusminus scheme for frio only. That don't touch other themes and schemes.

**Comment by MrPetovan** [comment]
I guess in this specific context, I don't want to argue that strongly.

**Pull request merged**
