### PR TITLE
API: New classes for OAuth and basic auth

### PR DESCRIPTION
**Pull request by annando**
As discussed in PR https://github.com/friendica/friendica/pull/10371 the authentication processes for OAuth and Basic Auth are now split into two separate classes.

Also the login function is replaced by the scope check.

### CODE REVIEW

**Comment by annando** [comment]
One of the checks failed, but only because of some network problem with the drone server itself. A restart would fix this.

**Review by MrPetovan — APPROVED** [review]
I have change requests but I'm going to integrate them myself in the PR it is supporting.

**Comment by Extarys** [comment]
Nice! A quick question though: the generated tokens doesn't look like they expire at all and you need a database call on every request to verify the token. Someone getting a token would get access to the user's account (within the scope of the token) for an unlimited amount of time or until the user decide to delete old tokens from the UI somehow.

Or maybe I just missed it...

As a quick fix I would add an `expire_on` field to the token that is 2 weeks from now, or make a hard check inside the code where you calculate `created_at + time_till_expire < now()`.

The advantage of the first fix is the client or user can select how much time they want to stay logged in. You would still need to verify each token in the database though as you have no idea if it was revoked by the user.

Eventually, to avoid users being constantly logged out by expired tokens, the api will need to send a refresh token with the auth token. When the auth token is expired, the refresh token is automatically sent in exchange for a new auth token. You then don't need to verify each access token in the database, only the refresh token on every refresh which could be every hour or 10 minutes depending on the server's need.

The refresh token is sent once to the client after a user logged in alongside the access token. The refresh token will be sent back to the server every time the client sees the access token is about to expire or has expire. The server should keep track of all refresh tokens and validate it before sending a new access token as the user can remove "devices"/deactivate refresh tokens/revoke them (choose the terminology you prefer XD).

**Comment by annando** [comment]
@Extarys there is currently no refresh since it seems as if Mastodon doesn't do it as well. But of course it would be better to refresh it from time to time. I also had the feeling as if Pleroma is expiring the tokens. It would be interesting to see if the clients can handle it. Do you have a link to a specification that explains how this works? If possible I would like to do the whole work without third party libraries since they often come with a lot of stuff that isn't needed at all.

**Comment by Extarys** [comment]
Try this: https://www.oauth.com/

Note that you do not have to implement everything 100%. Implement what is needed only and gradually. The oauth specs are mainly a "guideline" from what I gathered. 
There is a lot of stuff there, keep in mind a company created those so of course they make it seem big so you buy a auth0 subscription hahaha

**Pull request merged**
