### PR TITLE
[API] Provide post/contact search

### PR DESCRIPTION
**Pull request by MrPetovan**
Addresses #7889

This should add post URL/user profile URL search to the two relevant API endpoints:
- `api/search` and `api/search/tweets` for posts
- `api/users/search` for users

### CODE REVIEW

**Comment by MrPetovan** [comment]
Now it's fixed and tested.

**Comment by stom79** [comment]
@MrPetovan Just tested.

`api/users/search` when passing the URL of a message works like a charm :)

`api/users/search` works for accounts by passing username@instance

PS: `api/users/search`  doesn't seem to work with account URLs but that's not an issue, as I can do that with the other endpoint.

Thanks a lot. Cross-account actions will work with Friendica and people will be able to follow and interact with other instances :+1:

**Comment by annando** [comment]
@stom79 I'm looking forward that we add more and more endpoints, so that Friendica can use the full power of Fedilab. I guess @MrPetovan will be busy in the next time :grin:

**Comment by stom79** [comment]
Yes :)
I just noticed that I never handled correctly mentions in replies for Friendica :( 
I used `attentions` json array from the "status" object, I guess it is only available for GNU?

**Comment by stom79** [comment]
@MrPetovan Do you think it would be possible to attach mentions to statuses like for Mastodon? 
https://docs.joinmastodon.org/entities/mention

**Comment by MrPetovan** [comment]
> PS: `api/users/search` doesn't seem to work with account URLs but that's not an issue, as I can do that with the other endpoint.

This isn't expected, are you sure the Friendica node knows about the profile whose URL you tried?

**Comment by stom79** [comment]
> This isn't expected, are you sure the Friendica node knows about the profile whose URL you tried?

OK, it's that. I thought that passing the URL will resolved the account.

**Comment by MrPetovan** [comment]
We aren't doing that as of yet, but it's a good suggestion.

**Pull request merged**
