### PR TITLE
lang handling for #2752

### PR DESCRIPTION
**Pull request by tobiasd**

### CODE REVIEW

**Comment by annando** [comment]
Could you explain a little bit what this is doing?

**Comment by Hypolite** [comment]
For starters, it fixes #2752. User language is not automatically updated every 12 hours.

Secondly, it reworks the way Friendica identifies the user's preferred language based on the Accept-Language header so that I won't have the Friendica's interface in french wherever I go although my preferred language is english in my browser.

Thirdly, it initializes new registered user accounts with their browser preferred language.

And quartly, it initializes new admin created user accounts with the system default language.

**Comment by Kulak** [comment]
I went to <https://squeet.me/friendica>.  It reports version:


My laptop is in United States and set to display English.   Instead on Safari the web page displayed in

    Dies ist Friendica, Version 3.5.2-dev die unter folgender Webadresse zu finden ist https://squeet.me

On Safari I could not find Accept-Encoding request header.

On Chrome I got:

   Это Friendica, версия 3.5.2-dev работает на веб-узле https://squeet.me

(That's Russian).  At least I can read Russian.

Chrome reported request headers:

```
GET /friendica HTTP/1.1
Host: squeet.me
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
DNT: 1
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,ru;q=0.6
Cookie: PHPSESSID=6ao3kmd5cr4n6bcg3k8jv1p4a3

```

**Comment by Hypolite** [comment]
Thanks for the report, could you move your comment to the issue #2752 ? This is a merged pull request we can't reopen while the issue can be discussed more.

**Comment by Kulak** [comment]
I have moved the issue description to issue #2752 as per request.

**Pull request merged**
