### PR TITLE
Use short form array syntax everywhere

### PR DESCRIPTION
**Pull request by MrPetovan**
BECAUSE I CAN!

This is a nearly impactless PR, the only functional change is in `util/po2php.php` where I had to manually change how we generate arrays in the `string.php` files.

### CODE REVIEW

**Comment by tobiasd** [comment]
> This is a nearly impactless PR, the only functional change is in
> `util/po2php.php` where I had to manually change how we generate
> arrays in the `string.php` files.

But you tested the po2php mechanism and it still works? ;-)

**Comment by MrPetovan** [comment]
That's where you come in, how do I test it?

**Comment by tobiasd** [comment]
You can compile the French translation from the messages.po file and see if it still works.

    $> php util/po2php.php view/lang/fr/messages.po 
    $> php -l view/lang/fr/strings.php

If this does not throw a syntax error, then you can try and load the FR translated interface in Friendica.

**Comment by MrPetovan** [comment]
There are no differences between the generated file and the one I changed directly in this PR 🎉

**Comment by MrPetovan** [comment]
Changing language doesn't work at the moment, but it is unrelated to this PR.

**Comment by MrPetovan** [comment]
Fixed the language selection, tested it successfully with this PR.

**Comment by MrPetovan** [comment]
Can someone please merge this, I've had to rebase it 4 times to fix conflicts since I opened it because @zeroadam keeps deleting files in `include`!

**Comment by MrPetovan** [comment]
For once, I did a straightforward PR that doesn’t require manual review, sorry you started doing this.

**Comment by annando** [comment]
I will always have a look at every code line at PRs - this is my standard. :)

**Comment by zeroadam** [comment]
Sorry about that! I will pause any further work until this is merged. Rebasing can be a giant pain!!

**Comment by MrPetovan** [comment]
Please continue, it’s only blocking me, I’m reluctant to make any new changes before this is merged.

**Comment by annando** [comment]
@zeroadam if you review it, I could press the magic button. I just want to have a second pair of eyes that looked at the changes.

**Comment by zeroadam** [comment]
👍

**Comment by annando** [comment]
A:
> And what had you done this evening?

B:
> I reviewed a single pull request.

**Comment by zeroadam** [comment]
@annando hahhah..

I was reviewing, though it was taking quite some time. Saved by the bell!

**Comment by MrPetovan** [comment]
Thanks!

**Comment by annando** [comment]
@zeroadam Sorry, I haven't seen that you started it as well.

**Comment by annando** [comment]
@MrPetovan You owe me one :)

**Comment by MrPetovan** [comment]
I already reviewed all of @Quix0r formatting PR, and I'll review all of your item changes PR, so I think I'm good! 😄

Sorry for the ordeal though.

**Comment by zeroadam** [comment]
No worries!!

**Pull request merged**
