### PR TITLE
The friend contact block wasn't displayed in the profile

### PR DESCRIPTION
**Pull request by annando**
Additionally the text.php was cleaned up. Two function were removed that are part of the PHP core for all supported versions.

### CODE REVIEW

**Comment by tobiasd** [comment]
What are all these other code mods?

**Comment by AlfredSK** [comment]
Okay. Just wanted to create an issue. But there is a pull request already. :-D

**Comment by annando** [comment]
The other code parts were some code cleaning.

**Comment by tobiasd** [comment]
Ok, with that description it makes sense ;-)

**Pull request merged**
