### PR TITLE
[Frio] Mobile info hover button for hover card

### PR DESCRIPTION
**Pull request by anubis2814**
On the desktop, when you see someone’s profile name, if you hover over it, it will give you an info popup with interactions.  You can also click on it and it will take you to their profile page on their platform, rendering the hover option useless on a mobile device.  I added an extra button for mobile only, that allows you to click/hover on it and get the popup leaving the name for click only.
Ps I did nothing with l10n on this one so if it gives issues it is that whatever formatting issue that happened last time.

### CODE REVIEW

**Comment by MrPetovan** [comment]
There already is a clickable control for mobile interfaces on the profile picture, I'm not sure there's a need for an additional link.

**Comment by anubis2814** [comment]
I've been using the mobile feature for several years now and had no idea til you just told me right now.  There is nothing that gives it any indication that you can or should click on it.  If there is a way to make the user think to press it to try it out then yes my button isn't needed, but if I didn't know about it, I bet very few casual users know about it either.  Any ideas on how to get the user to press the image to discover it?

**Comment by MrPetovan** [comment]
Unfortunately not, I added this feature for myself so I know it exists, but I don't know how to visually convey this piece of information. Maybe we should have it work this way for the display name in mobile view as well.

**Comment by anubis2814** [comment]
Oh it does, if you press and hold an app menu pops up and when you leave that menu the hovercard is there. but since click is "go to site profile" and hover is hover card, and hover and click are essentially the same thing on the phone its not that useful.  Unless we want to add the go to their profile site inside the hovercard instead of when clicking on it.

**Comment by MrPetovan** [comment]
The way it works, the hovercard shows if you tap once on the profile picture, but not on the display name where it leads you to the profile page of the contact (either local or remote depending on the node's settings). This is regardless of the media (desktop or mobile). Maybe there's a way of having the mobile view only need a tap on both the profile picture and display name to show the hovercard.

**Comment by anubis2814** [comment]
That still makes it hard to go to the person's profile page which I like having.  Which is why unless we can make the profile picture a more noticeable thing to click on and try out, another button, in my option is only way unless we want to scrap the go to profile site option entirely, or we could put that button in the hovercard.

**Comment by MrPetovan** [comment]
When you tap on the profile picture or display name in the hovercard, you're taken to the profile page.

**Comment by anubis2814** [comment]
Clicking on the name or image in the hover takes you to their friendica profile in the hovercard, not their profile on their site(something I also didn't know about til today..  I'd like to have that feature too still.  Its not a terrible option to remove from the main post name, and instead put it in the hovercard.

**Comment by MrPetovan** [comment]
Huh, I thought the hovercard links depended on the "Stay Local" setting like the post links.

**Comment by anubis2814** [comment]
https://friendica.myportal.social/photo/209098763264970e22cd00b921694440-0.jpg
Here is how it looks, mobile app only, doesn't exist on the desktop. If you can think of a way to get people to think to click on the image, this would be ideal. But a simple info button I believe is much more intuitive and more likely for people to discover.

**Comment by MrPetovan** [comment]
Thanks for the screenshot, it doesn’t look too bad, but I’m afraid the size makes it hard to hit on a mobile interface, I’d rather we found a way to always show the hovercard on display name tap on mobile.

**Comment by anubis2814** [comment]
I've clicked on it and it works just fine.  Are you considering getting rid of the option to go directly to the person's profile on the instance? or maybe putting that option in the hovercard itself instead of when clicked? I can do that, we'd just need to figure out what icon would be best for it in the hovercard.

**Comment by anubis2814** [comment]
Maybe that icon used on the top right of the post to go to the original post on the instance?

**Comment by anubis2814** [comment]
https://friendica.myportal.social/photo/616215811164978058d771b302137343-0.jpg Something along these lines. Then click or hover differences wont matter, it will just activate the popup, and you can click on that other link to do what clicking on the name used to do.

**Pull request closed without merging**
