### PR TITLE
Issue 6521: Don't send notifications for deleted items

### LINKED ISSUE #6521: Notifications for comments on locally deleted postings
### Expected behavior
If I delete ( local removal ) a posting from my stream ( /netwokr ) I don't want to receive notfications about comments on such a posting.

### Actual behavior
I get notified about comments on deleted postings.

### Steps to reproduce the problem
Like or comment a posting or a comment under a posting, that you 'follow' it and reveive notifications.
Then delete the posting and wait until somebody comments it.

### Friendica version you encountered the problem
 Friendica 'The Tazmans Flax-lily' 2019.01 - 1295

### Friendica source (git, zip)
git

### PHP version
PHP 7.2.14

### SQL version
mysql  Ver 15.1 Distrib 10.1.37-MariaDB

### PR DESCRIPTION
**Pull request by annando**
This hopefully fixes #6521

### CODE REVIEW

**Comment by MrPetovan** [comment]
Next step is deleting existing notifications on delete notice.

**Comment by annando** [comment]
What do you mean?

**Comment by MrPetovan** [comment]
- Post arrives.
- Notification is created, shows in the notification list.
- Post deletion notice is received and processed.
- Notification still exists, clicking on it shows 404 error page.

**Comment by annando** [comment]
Ah, no I understand. Best is to file an issue for the next release.

**Comment by MrPetovan** [comment]
Of course.

**Pull request merged**
