### PR TITLE
Moved .htconfig.php file & extracted Install business logic

### PR DESCRIPTION
**Pull request by nupplaphil**
Based on #4844 , I restarted with the changes.

This PR will change the following things:
- moved `htconfig.php` and `.htconfig.php` from the top-level directory to a `config/` directory.
- extracted the whole business logic from `mod/install.php` to a new Class `Core/Install.php`

Both changes are on the one hand for a better handling/working with Friendica and on the other hand a preparation for a second PR, I will create (=> auto-install function, described in https://github.com/friendica/friendica/pull/4844#issuecomment-382611072 )

### CODE REVIEW

**Comment by MrPetovan** [comment]
In advance, dear patch notes writers and Friendica Support denizens, I'm sorry.

**Comment by tobiasd** [comment]
F**k this should be done automatically. I'm for reverting this RP!

**Comment by AlfredSK** [comment]
...ASAP. There are admins running a cron job to pull from develop.

**Comment by annando** [comment]
BTW: I think it would be enough if the system looked for the config file in both places and to place a huge warning in the admin interface to move it manually to the new place when it was in the old one.

**Comment by nupplaphil** [comment]
..oh..

I'm sorry I thought the manual way is better rather than automatic as discussed in the initial PR.

My first change included to automatically move the .htconfig.php in case it is found in the top-level directory when visiting Frienidica.

Would that help?

**Comment by nupplaphil** [comment]
Or just add the warning in case? I think the automatic way wouldn't interfere the normal usage.

**Comment by annando** [comment]
Automatically moving is bad since there are installations where the wb process don't have write access to the folder.

**Comment by MrPetovan** [comment]
> BTW: I think it would be enough if the system looked for the config file in both places and to place a huge warning in the admin interface to move it manually to the new place when it was in the old one.

Sounds like we should require the `.htconfig.php` file from a single location in the `App` class then, to be able to pull this off.

**Comment by MrPetovan** [comment]
> I'm sorry I thought the manual way is better rather than automatic as discussed in the initial PR.

It's not your fault, it's mine, your intention was good even if the implementation wasn't ideal, and I couldn't come up with a better way of doing it. I guess we'll have a transition period then.

**Comment by nupplaphil** [comment]
Shall I help you with the solution as you wrote in https://github.com/friendica/friendica/issues/4886#issuecomment-383304047 or better let it be and just wait for the change? I'm no longer sure..

**Comment by MrPetovan** [comment]
I’m going to do it #4889, and then remerge your PR once it’s done.

**Pull request merged**
