### PR TITLE
Improve links

### PR DESCRIPTION
**Pull request by xundeenergie**
Linked websites will open on first link in _blank, klick on picture opens in same tab and the provider-link below the link will also open in same tab. 

This commit adds consistent behaviour for linked urls

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]
Thank you for your work!

**Comment by MrPetovan** [comment]
Test is failing because PHP CS configuration is obsolete, merging anyway.

**Comment by nupplaphil** [comment]
@MrPetovan - The tests are not obsolete. This error appears in cases the current feature-branch isn't after the base-branch, so the git diff produces unexpected results :)

**Comment by MrPetovan** [comment]
Aaaaah.

**Pull request merged**
