### PR TITLE
updated RU translations

### PR DESCRIPTION
**Pull request by tobiasd**

### CODE REVIEW

**Comment by SpcCw** [comment]
Not sure it it is ok to ask it here but I don't see new string "in reply to" (https://github.com/friendica/friendica/pull/13527) in Transifex. Will it be added later or am I looking in wrong places?

**Comment by MrPetovan** [comment]
It probably hasn't been added yet. We've had several new translation strings added to the RC, and someone™ needs to manually import them in Transifex.

**Comment by tobiasd** [comment]
Thanks for the reminder xD I've updated the source URLs for the core and addons on transifex The system should pick up the new `messages.po` source files soon.

**Comment by SpcCw** [comment]
Thanks, the strings show up in Transifex now!

**Pull request merged**
