### PR TITLE
Issue1329

### PR DESCRIPTION
**Pull request by silke**
Please check! This adds a setting to the admin settings. It modifies the sender information for email notifications: The "from" field now is the sitename. The email address system notifications come from are now customizable. If empty it should stay noreply@example.org as before.

### CODE REVIEW

**Comment by tobiasd** [comment]
In mod/admin.php when you build the array for the email field you can set the input field type to "email" thus modern browsers will check if the input is a valid email address (see [mod/install.php](https://github.com/friendica/friendica/blob/develop/mod/install.php#L238) for example.

Also I'm surprised that a construct like

    "Failed updating '$table_name': " . $db->error

works, but that is magic of the different quotation marks I guess?

**Comment by silke** [comment]
Like this?

**Comment by annando** [comment]
Looks good.

**Comment by tobiasd** [comment]
yes

**Comment by silke** [comment]
Yay! Thanks for your feedback! That was fun!

**Comment by Beanow** [comment]
@tobiasd yes PHP allows variables in double quote strings, but not single quotes. You can use more complex variable names or operations using curly brackets too like for example `"Hello {$a->config['foo']}!"` should work fine.

**Pull request merged**
