### PR TITLE
[frio] Added content warning button

### PR DESCRIPTION
**Pull request by anubis2814**
I added a content warning button on posts, compose and comments.  It is the fa-eye icon.  It generates [abstract][/abstract].  I think if we want more people used to mastodon coming over here we need to make that more easily available.  I only did this for frio, I did not do this for vier as while I could do this for comments, initial posts used a different method I didn't feel like learning, and CW for comments are mostly pointless when its not available for original post.   I also believe that vier exists as a lightweight bare bones theme while frio is much more robust so going without a CW isn't terrible.   Someone else may be able to add it to vier in the future.  If you don't like it or there is a better option please reject this.
Also fixed a l10n code entry for emoji button.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Adding a feature to only one of the themes is fine, as long as you don't fiddle with new modules that have new templates. As usual, if you add a `L10n->t()` call, you need to run `bin/run_xgettext.sh` from your Friendica root and commit the resulting changes to the `/view/lang/C/messages.po` file.

**Comment by anubis2814** [comment]
Hmmm, it looks like the git push didn't add that :/ I'll try to change it manually

**Comment by anubis2814** [comment]
So I'm looking through the c/messages.po and there are no changes after running bin/run_gettext.sh other than the date run
I do get this readout 
Friendica version 2023.09-dev
Extract strings to /home/anubis2814/friendica/bin/../view/lang/C/messages.po..
Reading file 585/1004...xgettext: warning: msgid 'Error' is used without plural and with plural.
                   ./src/Module/Moderation/Item/Source.php:87: Here is the occurrence without plural.
                   /home/anubis2814/friendica/bin/../view/lang/C/messages.po:6432: Here is the occurrence with plural.
                   Workaround: If the msgid is a sentence, change the wording of the sentence; otherwise, use contexts for disambiguation.
Reading file 1004/1004...                                            
Interpolate metadata..
Done.
Any idea why it wouldn't pick up my l10n changes?

**Comment by MrPetovan** [comment]
Your L10n changes were in fact picked up. There's a weird line length difference with the Continuous Integration check but it's not a functional difference.

**Review by MrPetovan — APPROVED** [review]

**Comment by tobiasd** [comment]
I would have preferred calling the button "abstract" and not mis-use the wrong label that Mastodon is using for the summary field of postings.

**Comment by MrPetovan** [comment]
I understand the intent but the "abstract" feature is a little obscure and we aren't the best at documentation, so I believe it's fine in this context.

**Comment by annando** [comment]
I would have voted for something else as well, since it is an abstract. It can be used for example when posting to some connector network with a limited character amount for an abstract instead of the post. Also for ActivityPub it is transmitted in the field that is meant for the abstract.

**Comment by anubis2814** [comment]
My personal view, which is why I made this, is that Friendica has 15K users while Mastodon has upwards of 10M and are expecting certain features ready to go for them if they move to a different platform.  Abstract does have more features but we need to meet the user where they are.  Also it pops up abstract.  We could label it as "Abstract or content warning" so people look more into what abstract is, but we are a tiny drop in the fediverse sea and people have certain expectations when they come over here and we want them to stay without having to dig for certain features they are used to.  I didn't fully know what abstract did until recently and I've been on this platform since 2018

**Pull request merged**
