### PR TITLE
The "thread" table isn't used anymore 

### PR DESCRIPTION
**Pull request by annando**
Also some preparations had been done to replace the "item" table.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by AlfredSK** [comment]
Could it be that you forgot to raise the database version number?

**Comment by MrPetovan** [comment]
Ha, I knew it was missing something! Is it triggering errors?

**Comment by AlfredSK** [comment]
No. But I'm not sure about the side effects. I updated a small ~~instance~~ node to check it out first. I was wondering why I didn't get a notification mail about the structure update. I checked the `dbstructure update -f` command. It doesn't show any output. So I guess it is working.

**Comment by AlfredSK** [comment]
Or is it right because we only remove a table?

**Comment by MrPetovan** [comment]
Oh, it definitely could be that. We don't remove tables through the dbstructure update.

**Comment by annando** [comment]
Yeah, we don't need to increase the number because no action is required.

**Pull request merged**
