### PR TITLE
Prevent double location display in vcard

### LINKED ISSUE #9163: double country and region in profile
### Expected behavior
When I fill in only "country" and "region", only the `<span>`s with the classes `country-name` and `region` should be filled in the profile.

### Actual behavior
The `<span>` with class `street-address` is also filled with "region and country name".

### Steps to reproduce the problem
Fill the form like this in /settings/profile:
20200814-friendica-location-form
Result:
20200814-friendica-location-result

### Friendica version you encountered the problem
version: 2020.09-rc
database version: 1367 
post update version: 1350
theme: Frio V.0.8.5

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #9163

### CODE REVIEW

**Comment by annando** [comment]
For contacts the location data is only held in the field "location". I guess that removing these lines will remove the display of location data for all contacts.

**Comment by MrPetovan** [comment]
Ah, I see. I guess the alternative will be radical.

**Comment by annando** [comment]
The "self" contact also contains a "location" field. So we could display "location" all the time, I think.

**Comment by MrPetovan** [comment]
Now we exclusively rely on it to the exception of `address` that never gets included in location.

**Pull request merged**
