### PR TITLE
port of reds event attendance feature

### PR DESCRIPTION
**Pull request by rabuzarus**
On the base of the port of reds consensus feature (see https://github.com/friendica/friendica/issues/1699) I deleted the the code for the consensus. So the reds code for attending an event remains.

I have a sample implementation for the vier theme but it needs to get adjusted to looking nice. Because of missing icons in other themes I didn't tried an sample implementation for other themes. I would leave this task to the theme developers who know it better how the feature should look like.

PS: If someone is interested in the whole consensus feature then he/she should look at https://github.com/friendica/friendica/issues/1699 . It is working but the database part is still missing.

### CODE REVIEW

**Comment by annando** [comment]
Have you checked the behaviour with OStatus and Diaspora? Means: Will attendance messages be transferred to other networks? (I think they shouldn't).

**Comment by tobiasd** [comment]
What about Hubzilla? I think there being able to set the attent status should work - no? Do'n't know if Diaspora has an events feature. But also the bridged networks should not be feeded with such notes IMO.

**Comment by annando** [comment]
The Diaspora protocol won't enable us to pass these messages through their network.

**Comment by tobiasd** [comment]
:-( ok

**Comment by rabuzarus** [comment]
I thought https://github.com/friendica/friendica/pull/1929/files#diff-596c196123cc398db427de8df5e6364eR310 disables it for other networks. But I should test it. Are there any easy possibilities to test it? My test instance don't have an url in the format https://subdomain.domainname.de

**Comment by annando** [comment]
Question is: What happens when you do a post in Friendica that gets federated to OStatus and Diaspora and someone from Friendica replies to it with these new values. This shouldn't be transferred to Diaspora. AFAIK RedMatrix is doing that, but I really don't like that behavior.

**Comment by redmatrix** [comment]
It's essentially an activitystream. The thing about activities is they devolve to comments on networks that don't actively "process" that activity. There's nothing wrong with receiving a comment on a Diaspora site saying Bob is attending George's event. We normally don't filter things to the Diaspora network. That is called censorship. The only things we currently block are post and comment edits because there's no mechanism for the Diaspora protocol to receive these; though I may convert them to activities and send them as comments also - so that no information is actually lost going across the network boundary. It's merely degraded into a form which can be processed by that network (e.g. a comment).

**Comment by rabuzarus** [comment]
@annando: there are also some other minor issues.
Can you leave the PR open. The next days I will have no time but maybe at the weekend

**Comment by rabuzarus** [comment]
I have some questions: 
* Does the attendance activities to be considered in https://github.com/friendica/friendica/blob/develop/object/Conversation.php#L111 and https://github.com/friendica/friendica/blob/develop/object/Item.php#L449  ?
* Is there already a decision in the question how to treat automated messages in other networks? (BTW the friendica OStatus implementation does filter this messages already but in diaspora the status  messages appear)

**Comment by annando** [comment]
Concerning the first point: I guess it doesn't need to be considered there.
Concerning the second point: In the discussion there was no clear direction. So I think we should do it like we do with likes on comments or dislikes when they are transferred to Diaspora: They are discarded.

If you don't find the right place I can do it in an upcoming pull request.

**Comment by rabuzarus** [comment]
concerning the right place: i would say https://github.com/friendica/friendica/blob/master/include/delivery.php#L523 and https://github.com/friendica/friendica/blob/master/include/notifier.php#L905 .

There is one thing left where I don't know how to deal with. At this state I have no implementation for the notification page (mod/notifications.php). I'm not sure if adding the conditions for 3 new activity states would be a good solution (because it would contain masses of code duplication and there is already enough duplicated code in this file). The easiest way would to write the duplicated code in a new function (but I haven't look through the code if it's really exact the same code which is duplicated) but maybe there should be more rewrite and needs discussion on UX-Watchdogs.

In my opinion likes, dislike & attendance states should also appear in the notification navbar popup. Additionally I think the notification page (notifications.php) should also display old notifications (something like a notification history). Next to this we have to ask if the existing tabs are self-explanatory and if they are a good choice. In my opinion diasporas notification page is more interesting than friendicas.
But all this this is a really big task and needs much discussion at other places and people with skills.

But to come back to my point. I don't know how to deal with the notifications.php. Just Copy&Paste?

**Comment by annando** [comment]
I don't like duplicated code. This is something we really have to avoid. There are already too much duplicates in the code by now.

**Comment by rabuzarus** [comment]
The delivery to diaspora should now ignore the attendance states.
I would move the implementation of event attendance notifications (mod/notifications.php) to a later date (because 1. since it should not only an extension by copy & paste it needs time and 2. since it would also affect other code/features a separate PR seems to be better for understanding and testing). If someone else want to do this he/she is welcome.

**Comment by annando** [comment]
@fabrixxm @tobiasd I would like to accept this pull request now. Please keep in mind that we have to change the other themes as well.

**Comment by tobiasd** [comment]
I'd say if the supported core themes are supported by this new feature we can merge this. duepunto, frost(mobile), quattro,, and vier--which are currently supported?

**Comment by annando** [comment]
At the moment the changes are only done in "Vier".

**Comment by tobiasd** [comment]
Have you tried with quattro? As it does not need images for action buttons, it should be working quickly. But for the other themes images for the buttons would be needed right?

**Comment by rabuzarus** [comment]
quattro has to be changed. At the moment there are no changes in the default templates (/view/themes/tpl). I haven't implemented because I have no clue about what would be a good default (e.g. class names). This is also true for the other themes. I'm not really happy with the look of this feature in vier. Personally I would putt it right align next to social action buttons (e.gl like/dislike share star and so on) and therefor put the language display in the next line. But this decision is up to the theme developers because they know best how their theme should look and act like

**Comment by tobiasd** [comment]
I'll add a new issue then to add this to the supported themes for the 3.4.3 milestone.

**Comment by tobiasd** [comment]
playing around with it, when I attend an event and then click on maybe attend, the status is deleted but not updated, so I need to reclick the button. Can this be done with one click only?

**Comment by tobiasd** [comment]
There is a problem for the translation in the case that more then one contacts are attending (or not). @fabrixxm could you have a look?

**Pull request merged**
