### PR TITLE
Remove "fcontact" from suggestions

### PR DESCRIPTION
**Pull request by annando**
The fcontact table isn't used anymore for contact suggestions.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by nupplaphil** [comment]
@annando I got some really strange behaviors since this PR with my develop branch.
After one successful update, all other updates are not working.
```console
root@friendica:/vagrant# mysql friendica < database.sql
root@friendica:/vagrant# bin/console dbstructure update

root@friendica:/vagrant# bin/console dbstructure update
ALTER IGNORE TABLE `intro` DROP INDEX `suggest-cid`; 

Error 1553 occurred during database update:
Cannot drop index 'suggest-cid': needed in a foreign key constraint
Errors encountered performing database changes: ALTER IGNORE TABLE `intro` DROP INDEX `suggest-cid`; <br />

root@friendica:/vagrant# bin/console dbstructure update -f -o
ALTER IGNORE TABLE `intro` DROP INDEX `suggest-cid`; 

Error 1553 occurred during database update:
Cannot drop index 'suggest-cid': needed in a foreign key constraint
Errors encountered performing database changes: ALTER IGNORE TABLE `intro` DROP INDEX `suggest-cid`; <br />

```

The `system.build` is stuck at `1438`

**Comment by annando** [comment]
@nupplaphil is fixed with https://github.com/friendica/friendica/pull/10895

**Comment by nupplaphil** [comment]
@annando .. But how o_O .. Your PR fixes a behavior, the above seems to falsely try dropping an index

**Comment by MrPetovan** [comment]
Black magic.

**Pull request merged**
