### PR TITLE
Issue 9520: Fix resharer hovercard

### LINKED ISSUE #9520: Hovercard displays wrong details of poster in reshares
### Bug Description

In reshared posts, the hovercard over a poster's detail is displaced incorrectly. The original poster's details are not displayed but the resharer's details' instead. 

This apparently only happens when the 'Display the resharer' option is enabled.

See here: https://forum.friendi.ca/display/85a863ed-655f-aa93-9a3b-0c0611331859

### Steps to Reproduce

Enable the above option is Settings/ Display and look for reshared posts.

### Platform Info

Friendica Version: 2020.12-dev, apparently (can't be reproduced on stable).

### PR DESCRIPTION
**Pull request by annando**
Fixes https://github.com/friendica/friendica/issues/9520

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]
That was easy.

**Comment by annando** [comment]
It took me some minutes longer because I had searched at the wrong place. But indeed it had been some 30 minutes or so.

**Comment by tiotrom** [comment]
Should this also apply to the contacts in your list? The side left panel and in the contacts page? perhaps? Thanks for fixing it btw!

**Comment by MrPetovan** [comment]
What's the problem with the left side panel and in the contacts page?

**Comment by tiotrom** [comment]
When "stay local" is enabled, and I click my contact's names/avatar in the left side panel or on the contacts' page, it redirects not locally, but to the original instance. Like I mentioned here https://venera.social/display/85a863ed-645f-aaa8-60bb-a53659333725 . Shouldn't these also redirect locally?

**Comment by MrPetovan** [comment]
Probably, but it doesn't have anything to do with this particular PR, please open a separate issue.

**Comment by tiotrom** [comment]
Ok sorry. I will

**Comment by MrPetovan** [comment]
It's okay, thank you for contributing!

**Pull request merged**
