### PR TITLE
[PHP-CS] Moving the php-cs-fixer dependency to the right place

### PR DESCRIPTION
**Pull request by nupplaphil**
FollowUp #13824
Should help with #14376 

I totally oversaw #13824 
@teddy15 updated the dependency of php-cs-fixer at the root-directory of Friendica.
But I created a specific folder at `/bin/dev/php-cs-fixer` for the tool.

I separated it from the rest because I do want to use just the tool without any other dependencies at the CI pipeline. That's why I "fixed" the binary-path again with https://git.friendi.ca/friendica/friendica-docker-ci/pulls/17 (now I know, why the path changed :) )

### CODE REVIEW

**Comment by nupplaphil** [comment]
I'll have a look at the license check later ;-)

**Comment by annando** [comment]
@nupplaphil I guess you want to fix the license check in this PR?

**Comment by tobiasd** [comment]
As the switch to REUSE is overthrowing that license check completely anyhow... maybe we can ignore that check?

**Comment by nupplaphil** [comment]
> @nupplaphil I guess you want to fix the license check in this PR?

No, not in this PR, I will wait for @tobiasd work..maybe we can deactivate it for now.

**Comment by tobiasd** [comment]
> maybe we can ignore that check?

makes sense for me

**Comment by annando** [comment]
@nupplaphil there's now a conflict.

**Pull request merged**
