### PR TITLE
Auto-Test for messages.po update

### PR DESCRIPTION
**Pull request by nupplaphil**
This one is for @tobiasd  :-)

It adds an auto-test for the `messages.po` and will fail if the `messages.po` is out of date.

Steps of the auto-test
- Checkout latest sources
- executes `bin/run_xgettest.sh` (with a new `sort` statement after the `find` for deterministic updates)
- Diff skips changed timestamp and changes in comments (like changed line-numbers of because of code-changes)
- If there's something left inside the diff, the auto-test failed :-)

### CODE REVIEW

**Comment by nupplaphil** [comment]
ok, the timestamp will always change :D .. maybe I'll find a better way ;-)

**Comment by MrPetovan** [comment]
Not only the timestamp, but messages can be shuffled around, the line numbers in the comments may change even though no message was changed.

**Comment by nupplaphil** [comment]
Just added a sort after the find and got rid of the random changes :)

**Comment by MrPetovan** [comment]
Ooooh, that's a good start, but again, line changes will commit a new messages.po everytime an unrelated line is added or removed before a translation string in any file.

**Comment by nupplaphil** [comment]
OK what about the current version :-)
- Added `sort` to `find`, so changes are now deterministic
- Diff skips the changed timestamp
- Diff skips changes in comments (like changed line-numbers ;) )

And the test fails instead of "auto-committing" changes. I think this is way more transparent

**Comment by nupplaphil** [comment]
https://github.com/friendica/friendica/pull/10138/commits/fcc3d028a9128e2844b6e8ea8ea64502630d322a is without new messages.po = failure
https://github.com/friendica/friendica/pull/10138/commits/8f36da9dafb3025e841616a6e49015fcbda8c3c0 is with new messages.po = no failure :-)

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
