### PR TITLE
Fix wrong authenticate() parameter type in mod/removeme

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes https://forum.friendi.ca/display/a8e4f565165a6766621259c277073049

### CODE REVIEW

**Comment by ben-utzer** [comment]
Most likely, as I do pr every 10h, this one here broke something on my end.

**Comment by MrPetovan** [comment]
This one is more likely to have broken something seriously: #4312

Please check your Friendica/Web Server error log.

**Comment by annando** [comment]
@ben-utzer are you on the "develop" branch in the addons as well?

**Comment by ben-utzer** [comment]
yeah great, I did not even know there is a development branch in addons. :-(

Sorry and thanks, it works again.

**Pull request merged**
