### PR TITLE
Frio: provide own group template + some restructuring in group.php

### PR DESCRIPTION
**Pull request by rabuzarus**
This PR provides an own group module template for Frio.
I had to restructure some things in `mod/group.php`. The old template data for the groups module was provided through `function micropro()`. From my point of view this was a very bad solution because it didn't provide very much information about the contacts (e.g. in the default view the user did see only the contact avatar. To distinguish contacts was very hard if many contacts does use the default avatar picture). Now the group template data is provided through `function _contact_detail_for_template()` and the theme developer gets more information about the contact.

I extended the default `view/templates/groupeditor.tpl` which should present the contacts (and group members)  as before.

In Frio there are now two buttons to switch between two different `view-modes`.

### CODE REVIEW

**Comment by Hypolite** [comment]
I finally tested it, and while it's pretty great, I feel it misses an acknowledgment when you just clicked on the add/remove icon. One way of doing it is to change the icon to the expected state immediately, before the ajax display update completes, or if you don't want to do that, at least replace the action icon by a loading icon of your choice as soon as you click on it.

Otherwise, I got a bunch of smarty PHP notices about undefined index in the `photo_menu` part of `contact_template.tpl`.

I solved them by adding `isset()` in front of all the tests like this:

````
{{if isset($contact.photo_menu.pm)      && $contact.photo_menu.pm     }}<button type="button" class="contact-action-link btn-link" onclick="addToModal('{{$contact.photo_menu.pm.1}}')" data-toggle="tooltip" title="{{$contact.photo_menu.pm.0}}"><i class="fa fa-envelope" aria-hidden="true"></i></button>{{/if}}
{{if isset($contact.photo_menu.poke)    && $contact.photo_menu.poke   }}<button type="button" class="contact-action-link btn-link" onclick="addToModal('{{$contact.photo_menu.poke.1}}')" data-toggle="tooltip" title="{{$contact.photo_menu.poke.0}}"><i class="fa fa-heartbeat" aria-hidden="true"></i></button>{{/if}}
{{if isset($contact.photo_menu.network) && $contact.photo_menu.network}}<a class="contact-action-link btn-link" href="{{$contact.photo_menu.network.1}}" data-toggle="tooltip" title="{{$contact.photo_menu.network.0}}"><i class="fa fa-cloud" aria-hidden="true"></i></a>{{/if}}
{{if isset($contact.photo_menu.edit)    && $contact.photo_menu.edit   }}<a class="contact-action-link btn-link" href="{{$contact.photo_menu.edit.1}}" data-toggle="tooltip" title="{{$contact.photo_menu.edit.0}}"><i class="fa fa-user" aria-hidden="true"></i></a>{{/if}}
{{if isset($contact.photo_menu.drop)    && $contact.photo_menu.drop   }}<button type="button" class="contact-action-link btn-link" onclick="addToModal('{{$contact.photo_menu.drop.1}}')" data-toggle="tooltip" title="{{$contact.photo_menu.drop.0}}"><i class="fa fa-user-times" aria-hidden="true"></i></button>{{/if}}
{{if isset($contact.photo_menu.follow)  && $contact.photo_menu.follow }}<a class="contact-action-link btn-link" href="{{$contact.photo_menu.follow.1}}" data-toggle="tooltip" title="{{$contact.photo_menu.follow.0}}"><i class="fa fa-user-plus" aria-hidden="true"></i></a>{{/if}}
{{if isset($contact.photo_menu.hide)    && $contact.photo_menu.hide   }}<a class="contact-action-link btn-link" href="{{$contact.photo_menu.hide.1}}" data-toggle="tooltip" title="{{$contact.photo_menu.hide.0}}"><i class="fa fa-times" aria-hidden="true"></i></a>{{/if}}
````

**Comment by rabuzarus** [comment]
Thank you for testing. I will have a look

**Comment by rabuzarus** [comment]
I hope the smarty warning are gone. This seems to happen if a variable isn't declared. But somehow not every time. This is really annoying. The `{{if}}` condition should check if a variable is available or not. Otherwise we would need to set all variables to `false` in php :-/

There are some other little issues, which I get not resolved but which are hopefully not recognizable. 
- I had to change photo menu button from `pull-right` to `media-right`. Now the distance between the photo-menu avatar and the opened photo-menu dropdown isn't the same like for all other dropdowns.
- I would like to have something like `text-overflow: ellipsis;` for `.contact-entry-desc` content (except for the `.contact-entry-name` if it is not the group module in short mode view). I don't get `text-overflow: ellipsis;` to work. Nowhere. I guess we would need to set the correct div to `overflow: hidden` then there is a very high probability that the photo-menu dropdown wouldn't work anymore

**Comment by Hypolite** [comment]
I just tested, I didn't get the smarty errors again and the fading animation is enough for me, although the reordering of contacts slightly startled me.

As for ellipsis, per [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow):
> This property only affects content that is overflowing a block container element in its inline progression direction (not text overflowing at the bottom of a box, for example). Text can overflow when it is prevented from wrapping (e.g., due to ‘white-space: nowrap’) or a single word being too long to fit.

**Comment by rabuzarus** [comment]
I just did some tests. But I didn't get `ellipsis`to work. I guess the reason is the `width` of the bootstrap `media` class. But to change here some css would need more experience.
Yes, I also think about if the reordering of the contacts is a good idea. But at the moment I have no time for more big investigations. I would suggest to move all improvement tasks (if they are not critical) to the future.

**Comment by rabuzarus** [comment]
Argh.... https://github.com/twbs/bootstrap/issues/15958 :-/

**Pull request merged**
