### PR TITLE
Process id with GUID (Suggestion)

### PR DESCRIPTION
**Pull request by nupplaphil**
Follow up to #5359 

Like I said in https://github.com/friendica/friendica/pull/5359#issuecomment-404287027 , I'd prefer a fixed-length process ID.
Therefore I modified the GUID a little bit and used it for the process ID.

It's just a suggestion and @annando has to say if it's OK for him.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Waiting for @annando 's review.

**Comment by nupplaphil** [comment]
one day, I'll write a PR and adhere all code-standards...

**Comment by annando** [comment]
I'm still thinking that it's overcomplicating things. The function to create the guid has to ensure that the created guid is really world wide unique. The other functions only has to generate some random noise so that you can easily trace processes in the log file.
 
Currently that function generates text like ```log:22463:00:5b461e0d245c1``` - in fact only the ```log:``` and ```:22463:``` are important here. The ```:00:``` is just some filler and ```:5b461e0d245c1``` is random noise.

So I guess best would be, if we at first create the trailing text (```log:22463:```) and then are calling the ```createGUID``` function without a trailing text and with a given length so that the whole string is 26 characters long.

**Comment by MrPetovan** [comment]
Did you mean to reopen this PR?

**Comment by nupplaphil** [comment]
Yes, I'll simplify my changes and add it here :)

**Comment by annando** [comment]
Sorry for me being so nitpicking - @MrPetovan already knows this side of me, but does also know how to convince me :grin:

**Comment by nupplaphil** [comment]
Ah no problem :-)

I'm not THAT familiar with PHP so I take every feedback and try to improve the code and my skills ;-)

**Comment by nupplaphil** [comment]
I'm closing this PR.

Because I'm currently working on the change of the Process model itself and therefor I don't want to mix it :-)

**Pull request closed without merging**
