### PR TITLE
WIP: fix activate share-button on nonfollowers

### LINKED ISSUE #12923: [2023-03rc] "Like" on posts of non-followers randomly misbehaving?
Hard to catch this one, leaving it here in case anyone else hits it. After seeing my home instance updated to 2023-03rc, adding "likes" to accounts of non-followers "randomly" behaves weird again. So far tested on mobile (web ui, current fedilab), always same approach - interact with a post that floats by in a public timeline and is sent by someone you don't follow.

- Sometimes, fedilab will again throw a red "an error has occured" message. This doesn't necessarily seem to affect whether or not the "like" is added to this particular post - in some cases it will work, in some it won't.
- Same way using the web ui in a mobile browser. While tapping on thumbs-up on a post of a follower, this will toggle within a short while and add my name to "... has liked this". For posts of non-followers, tapping on the thumb-up will in some cases do nothing, in some cases take much longer to show some effect than for posts of people I follow (in some cases I reloaded the page to see the status has - not - been updated).

Not sure this makes sense or is a real issue. Will add some more info once it gets clearer.

### PR DESCRIPTION
**Pull request by xundeenergie**
I don't know, if this really resolves the problem... but it looks like, it does.

fixes #12923

### CODE REVIEW

**Comment by xundeenergie** [comment]
No, it only fixes a part...

**Comment by xundeenergie** [comment]
Where is $item defined? 
How can i find out, what $item contains?

**Comment by MrPetovan** [comment]
This is where `$item` is defined: https://github.com/friendica/friendica/blob/60c6ab08c13090d4c58edbfb9782620e372e3f81/src/Object/Post.php#L469

**Comment by MrPetovan** [comment]
You can also use Smarty to reveal its contents: `{{$item|var_dump}}`

**Comment by MrPetovan** [comment]
Did you mean to close this?

**Comment by xundeenergie** [comment]
oh no... deleted it accidentially...

**Pull request closed without merging**
