### PR TITLE
Automatically adjust feed poll frequencies

### PR DESCRIPTION
**Pull request by annando**
With this PR we detect the frequency in which a feed creates posts. According to this the priority is set. This currently runs on my two systems and I will gain some experience before declaring this PR ready.

### CODE REVIEW

**Comment by annando** [comment]
I think that the PR is now ready to be reviewed and hopefully be accepted. I used it today on both pirati.ca and squeet.me and as far as it seems everything worked well.

**Comment by annando** [comment]
BTW: Can you check why the tests aren't running anymore? Or can @nupplaphil have a look?

**Comment by MrPetovan** [comment]
On any PR? Not just drafts?

**Comment by annando** [comment]
Yes, on any.

**Comment by nupplaphil** [comment]
I'll take a look tomorrow. On a first sight, it seems travis is working per se. It's just the connection to github which isn't working.

**Pull request merged**
