### PR TITLE
Avoid thread completion on activities

### PR DESCRIPTION
**Pull request by annando**
The system has got the option to complete threads when it receives only the comment of a follower. This should be limited to comments only, not to activities like "like".

### CODE REVIEW

**Comment by MrPetovan** [comment]
Why not? I enjoyed receiving the conversations coming from my follow's likes. For me, it has the same feature of discovering content from trusted sources than with comments.

I've seen several of my mutual contacts interact with threads I liked, I assumed because they received it thanks to the like.

Was there any discussion for this change?

**Comment by annando** [comment]
I had the feeling as if in the past the system had behaved that way, so that this PR would reintroduce the old state. But of course it's no problem to change the already existing configuration for the completion to some option field.

**Comment by MrPetovan** [comment]
Should I make the change on line 650?

**Comment by annando** [comment]
We will need a change in the existing configuration value which currently is a boolean value.

**Comment by annando** [comment]
There is the boolean config variable `accept_only_sharer`. Every ocurrence has to be replaced with a new configuration that has got with three options. Then the programming in this PR (in line 650) can be controlled by this new configuration as well.

**Comment by tobiasd** [comment]
Once there was an option to not perform thread completion on threads not started by the accounts on a node, to not waste resources on unwanted conversations. This functionality seems to be removed. Was it on purpose?

**Pull request merged**
