### PR TITLE
updating date of security.txt validity

### PR DESCRIPTION
**Pull request by tobiasd**
The Friendica release plan is roughly March, June, September, December. With
this patch the information in the security.txt are vailid for the two planed
releases after the 2021.09 release.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Thank you for doing this!

**Comment by tobiasd** [comment]
I think I'll put it in my notes about doing the release to increase the date of validity so it lasts approx two releases after the one just in preparation.

**Comment by MrPetovan** [comment]
Good idea, by any chance have you published these personal release notes anywhere in case you aren't available to do a release?

**Comment by tobiasd** [comment]
Not yet I think. I'll have to convert the notes from German and remove some outdated stuff first.

**Pull request merged**
