### PR TITLE
The "attach" field is replaced by the "post-media" table

### PR DESCRIPTION
**Pull request by annando**
This is another preparation for replacing the "item" table. Eventually the whole field should be removed from the code and a post update should transfer the old content in the new structure.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
Same test errors only on PHP 7.2, I'm puzzled.

**Comment by annando** [comment]
What do we do about it?

**Comment by MrPetovan** [comment]
If only @nupplaphil was available!

**Comment by annando** [comment]
@MrPetovan I would suggest ignoring the PHP 7.2 errors. This seems to be a database issue with the PHP 7.2 image, see the enhanced test results.

**Review by MrPetovan — APPROVED** [review]

**Comment by annando** [comment]
This is a known error, see here: https://stackoverflow.com/questions/64677836/sqlstatehy000-general-error-1835-malformed-communication-packet-on-laravel and the issue: https://jira.mariadb.org/browse/MDEV-24121

**Comment by MrPetovan** [comment]
Thank you for looking into it!

**Pull request merged**
