### PR TITLE
Move jGrowl to Composer

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #4265

Nothing to report, drop-in move.

### CODE REVIEW

**Comment by MrPetovan** [comment]
They're simple enough, that's why I'm able to string them. And they don't conflict with the datetime move!

**Comment by tobiasd** [comment]
Another set of conflicts

**Comment by MrPetovan** [comment]
I'll wait for you to merge this one before resolving the other conflict since it's going to create another conflict.

**Comment by tobiasd** [comment]
ok

**Pull request merged**
