### PR TITLE
Road to Router Part 4: Move $apps out of App

### PR DESCRIPTION
**Pull request by MrPetovan**
Follow-up to #5979
Follow-up to #5987
Follow-up to #5988

This one is a short and sweet one. We removed two globals from App and we even remove a module that wasn't used!

### CODE REVIEW

**Comment by rabuzarus** [comment]
> and we even remove a module that wasn't used!

sure? I use it :-)

**Comment by rabuzarus** [comment]
bildschirmfoto von 2018-10-22 14-46-24

**Comment by MrPetovan** [comment]
I don't believe you! The same feature is actually implemented in the Admin panel.

**Comment by MrPetovan** [comment]
Teaser: I have a Road to Router Part 5 ready about the Pager, but I'm already three PRs ahead so I'm going to take a short break until they all are merged in order.

**Comment by tobiasd** [comment]
I'm using the `/apps` overview on a regular basis removing it would be very uncomfortable, somewhat breaking the apps class of addons.

**Comment by MrPetovan** [comment]
What are you using it for? It displays the same list as in the Admin panel?

**Comment by tobiasd** [comment]
The admin panel does not display any apps. It displays the activated addons so you can disable them again. But the `/apps` page provides links to the  actual working apps that are activated.

**Comment by tobiasd** [comment]
>     D mod/apps.php (30)

Why that? Any reason why disrupt the app class of addons (IRC e.g.)?

**Comment by annando** [comment]
Since there are already two persons using this, I suggest adding it again.

**Comment by MrPetovan** [comment]
Isn't the same list is available with actual links in the Admin, panel "Addon feature"?

**Comment by MrPetovan** [comment]
I restored the `/apps` module, and I improved the code some more because I just can't stop doing it.

**Comment by tobiasd** [comment]
Not sure if it is caused by this PR but since the last automatic pull this night all the apps have stopped working for me. Will try to investigate later if your changes have caused this or not.

**Comment by MrPetovan** [comment]
I'd say #5979 would be the culprit if any.

**Comment by MrPetovan** [comment]
Turns out #5981 was the culprit and @fabrixxm opened and closed an issue for this: #6010

**Comment by annando** [comment]
Could you have a look at that notice?
```PHP Notice:  Undefined variable: lang in /var/www/virtual/pirati.ca/htdocs/view/php/default.php on line 2```

I guess it was introduced with this PR.

**Pull request merged**
