### PR TITLE
Move current_theme() to App

### LINKED ISSUE #4946: mobile_theme isn't set in table pconfig
On the forum node (3.6 master) I have set vier as system theme. If I create a new account and then change the user's theme to frio it only works in desktop mode. On mobile devices vier is still in use. **The reason is in table pconfig 'mobile_theme = ---' isn't set for the UID of the new account.** In fact the entry for mobile_theme is missing completely. I had to add it manually to the DB to make it work.

### Expected behavior
When setting a theme in settings display it should also work on mobile devices.

### Actual behavior
The system theme is used instead.

### Steps to reproduce the problem
Set system theme to vier. Register a new account. Login and change the user setting display/theme to frio. Take a smartphone and look at the profile page of the new user.

### Friendica version you encountered the problem
3.6 master

### Friendica source (git, zip)
git

### PHP version
7.0

### SQL version
10.0 MariaDB

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #4946

Additionally, this is the first of many PRs to extract global functions from `boot.php` until there's nothing left.

Nothing.

Don't forget about https://github.com/friendica/friendica-addons/pull/595 when merging.

### CODE REVIEW

**Comment by annando** [comment]
Think of the upcoming feature freeze.

**Comment by MrPetovan** [comment]
I do, this was for fixing a practical issue, I'm not going to dabble into grand code refactoring any time soon.

**Comment by annando** [comment]
This "this is the first of many PRs" slightly frightened me :-)

**Comment by MrPetovan** [comment]
Ha ha, don't worry, it'll take some time.

**Pull request merged**
