### PR TITLE
Proposing Many English Language Corrections

### PR DESCRIPTION
**Pull request by miqrogroove**
The en-us translation quality is quite poor and needs many corrections.  I have proposed corrections to the most awkward phrases throughout.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Thanks for your work, however the `messages.po` are automatically generated by exporting from [our Transifex project](https://www.transifex.com/Friendica/friendica/). Please create an account over there to add your corrections to the translated strings. You will be automatically credited when we export the language files.

**Comment by miqrogroove** [comment]
Done.

**Comment by rabuzarus** [comment]
I would say this should rather be fixed in the source code strings

**Comment by tobiasd** [comment]
It's done in #5204 

@miqrogroove If you like, you can push changes from Transifex to the repository yourself, but I check translation updates there on a regular basis, so you don't have to. The important thing is, that changes are done at Transifex as well, because otherwise they will possible get lost once new work was done there.

The `messages.po` file needs to be converted to the associated `strings.php` file with the CLI console command `bin/console po2php view/lang/en-us/messages.po` and then both files should be committed to the repository.

**Pull request closed without merging**
