### PR TITLE
[frio] Use all available space for post interaction buttons (mobile)

### LINKED ISSUE #12582: [frio][mobile] Increase size of common controls on mobile devices
Using Friendica with Mastodon client apps works well for basic use cases but misses some functionality that's Friendica specific and available in the Web client. This, too, mostly works well on mobile devices but some of the core controls ("like", "comment", "share", "bookmark" are quite small on these screens and aren't really suitable for touch-driven operation. Increasing size of these controls really would ease using Friendica in auch environments and reduce the need or desire to use mobile apps instead.

### PR DESCRIPTION
**Pull request by damianwajer**
| Before         | After     | After (with dislike button) |
|--------------|-----------|------------|
| before-01 | after-01      | after-02        |

loader

## Changes
- Full-width post interaction row with evenly distributed buttons
- Absolutely positioned loader to prevent buttons movement

Related: https://github.com/friendica/friendica/issues/12835

### CODE REVIEW

**Comment by MrPetovan** [comment]
Thank you for the screenshot, what about the conditionally-displayed Share button? Would it just push other buttons around when it appears?

**Comment by damianwajer** [comment]
> what about the conditionally-displayed Share button

More dense, but all buttons will be in one row:

All buttons – nested

Unfortunately, it can be a bit jumpy:
- [Video example 1](https://user-images.githubusercontent.com/8630866/220984564-4c0c595d-4266-41ab-b574-49001479416d.mp4)
- [Video example 2](https://user-images.githubusercontent.com/8630866/220984520-2d37aa4e-d6a2-4670-96bb-f89ace29942e.mp4)

Maybe it's better to move "Share via" to the "More" dropdown?

Dropdown with Share via

**Comment by MrPetovan** [comment]
I'd rather not put it in a sub-menu. The problem is that this button depends on the availability of a browser feature that we can only check with Javascript. Currently the button only shows when we determine the feature is enabled, maybe in this version we should disable it instead, so that it's always visible and doesn't make the justified design jump?

**Comment by damianwajer** [comment]
> I'd rather not put it in a sub-menu

Why not? It's already there in the desktop version (or wider screens to be precise), so I guess it makes sense to be consistent. I don't think it's the most common action for users interacting with posts, so it's justified to put it in the "More" list (that's just my assumption, I could be wrong). Many applications do this as well, so it's a common pattern (Fedilab, Tusky, Facebook, Twitter, etc.).

> Currently the button only shows when we determine the feature is enabled

I think it's the case for a separate PR, but it could be improved using the progressive enhancement approach, for example:
1. Always show the "Share via" button (inline or in the dropdown).
2. Implement the most basic action for "Share via": open a canonical URL like a regular link, or show canonical link inline as text to be selected and copied manually, or using JS prompt: `prompt("Copy to clipboard:", "URL");`.
3. If device supports `Navigator.clipboard`, copy link to the clipboard automatically (this would require some notification with "Link copied" message).
4. If the device supports `Navigator.share`, use it instead of the above (best case scenario).

Anyway, even with feature detection and progressive enhancement, I think it's worth considering moving "Share via" to the dropdown to declutter the post actions view (it will make existing items larger and easier to click, which is the main motivation behind this PR and the original problem it's trying to solve).

**Comment by MrPetovan** [comment]
I'm now reluctant to use Twitter as an example but the Share button is next to the main action button on the tweet display, shown here with the "More" menu opened.
Screen Shot 2023-02-23 at 19 26 47

I like your idea about the progressive enhancement but it feels cumbersome to me to implement, seeing that I'm only moderating proficient in frontend development.

**Comment by damianwajer** [comment]
In the example you provided, it's also a dropdown (or bottom sheet depending on platform), but with different actions. 
If you don't want to move "Share via" to the "More" dropdown, like on desktop, maybe we could move it to the "Share" dropdown for now? It already contains the "Reshare" and "Quote Share" actions, and "Share via" fits the context of "Share".

I'm in favor of moving, mainly to reduce the number of actions visible at once. It feels like having 7 actions on mobile is too many, and not all of them are equally important or frequently used (Like, Dislike, Comment, Share, Share via, More, Checkbox).

**Comment by MrPetovan** [comment]
Sure, a common Share dropdown with "Share", "Quote Share" and "Share via..." sounds good.

**Comment by foss-** [comment]
+1 for reducing the 7 default interaction icons by moving one to a sub menu
+1 for moving share via
+1 adding it to share dropdown

**Comment by damianwajer** [comment]
I have some doubts that this is better than the "More" dropdown because of consistency with desktop version, but since you both agree and no one else is participating, let's do it :)

Side note: I think there should be no space before the "…", but this is existing text and I am not familiar with the translations Friendica yet.

share-via

**Comment by MrPetovan** [comment]
Thank you, we can revisit the location later, the important part was to remove it from the main action bar.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
