### PR TITLE
frio:fix jot - posts with images were not available on wall

### PR DESCRIPTION
**Pull request by rabuzarus**
This should fix https://github.com/friendica/friendica/issues/2687

I hope that it doesn't introduce other regressions.

### CODE REVIEW

**Comment by annando** [comment]
Just because I'm curious: How does this fix the problems?

**Comment by rabuzarus** [comment]
If you activate the browser it provides a hidden input with `type="image"`. If a user submits the post `type=image` (fbrowser) gets submitted and not the `type="wall"` from the text edit section. Puhhh  :-D

**Comment by rabuzarus** [comment]
So the `<form>` needs to be closed before the fbrowser section starts. Litte regression is that the user can't switch from browser to preview to get a preview

**Comment by annando** [comment]
Memo to myself: I should check whether we could set the "type" value directly in the code. This should be the better solution.

**Pull request merged**
