### PR TITLE
Fix/FollowUp ACLFormatter

### PR DESCRIPTION
**Pull request by nupplaphil**
FollowUp #7787  #7765 

- Add nullable to expand() function again
- Add angle bracket support to toString()
- Fix travis test

### CODE REVIEW

**Comment by nupplaphil** [comment]
Travis has green lights again :)

Plz merge https://github.com/friendica/friendica-addons/pull/908 too

**Comment by nupplaphil** [comment]
@annando I added `["<214>"]` as possible value, but `["<wrong>"]` would stay as invalid value and would return an empty string. Is this correct?

**Comment by MrPetovan** [comment]
Yes.

**Comment by nupplaphil** [comment]
Fixes #7781 as well

**Pull request merged**
