### PR TITLE
[frio] Limit thread indentation level to 7 (at thread level 9)

### LINKED ISSUE #13693: [frio] Threads with many comment levels - indentation not capped at 7
- [x ] I have searched open and closed issues for duplicates

### Bug Description

There is a  display problem in threads with many levels of comments. Even with 'Smart Threading', the text becomes so narrow that it is hard to read. With a lot of comment levels, the text even slips outside the background box.

Happens on **desktop**. On mobile it's not ideal (looks pretty narrow, too. but much better) but the cap at level 7 seems to work.

### Discussion in Support Group

https://forum.friendi.ca/display/0b6b25a8-1065-6c38-9d28-b43199453613

### Steps to Reproduce

You need a thread with a lot of comments in many levels like this: https://venera.social/display/9ca7ab3e-49d138c622fc6c9c-66e47cbd

**Actual Result:**

In higher comment levels the text gets so narrow that it is hard to read. With a lot of comment levels, the text even slips outside the background box.

**Expected Result:**

The indentation should be capped at level 7. 

### Screenshots

grafik

grafik

### Platform Info

Friendica Version:
2023.09-rc

Friendica Source: 
git

PHP version:
8.1

SQL version:
MariaDB 10.6

Browser:
Firefox 120 on Linux desktop

### PR DESCRIPTION
**Pull request by MrPetovan**
Fix #13693 

This PR is for maximum thread indentation at 5, but it can easily be amended if we want maximum thread indentation at 7 (at thread level 9)

### CODE REVIEW

**Comment by annando** [comment]
I'm slightly confused. How does removing the `else` does help here?

**Comment by MrPetovan** [comment]
There are indentation provisions in the CSS stylesheet for thread levels 1 through 7. Removing the `else` allows the `thread_level_X` class to go beyond 7, at which point they don't get the indentation from the CSS anymore.

**Comment by annando** [comment]
Wouldn't it be better to change the CSS attributes for `thread_level_7`? One might want to apply different rules than the margin there as well in the future.

**Comment by MrPetovan** [comment]
I just went for the simpler solution using the incremental numbered class system we already had to fix a debilitating display bug. It can be revisited when we need to do something else with it.

**Comment by MrPetovan** [comment]
PR updated according to https://github.com/friendica/friendica/issues/13693#issuecomment-1847833560

**Pull request merged**
