### PR TITLE
Alternate solution for pull request 3124

### PR DESCRIPTION
**Pull request by annando**
This is an alternate solution to the pull request https://github.com/friendica/friendica/pull/3124

It introduces a new function that does an escaping for database queries on a whole array. As a new option it can add quotation signs and converts boolean values in "true" and "false".

### CODE REVIEW

**Comment by mexon** [comment]
Ooh, shiny, thanks very much for doing that!  Tested and it's working great.

Nitpick: there's a typo "quoatation" there twice.

**Comment by annando** [comment]
@mexon fixed.

**Comment by mexon** [comment]
👏

**Comment by mexon** [comment]
Uh @annando, I think this broke stuff.  In the below error messages, guid is a string that just happens to consist of all digits.  So it gets interpreted as a number and makes everything sad.  My best guess for fixing it is supplying an extra argument that's a map from field name to data type to override your defaults.  But before I try doing that, thought I'd get your opinion.

2017-02-01 13:10:39@log5891de4e846d32.71547402  [NORMAL]:dba.php:290:q  dba: INSERT INTO `item` (`gravity`, `type`, `wall`, `guid`, `uri`, `extid`, `author-name`, `author-link`, `author-avatar`, `owner-name`, `owner-link`, `owner-avatar`, `created`, `edited`, `commented`, `received`, `changed`, `title`, `location`, `coord`, `last-child`, `visible`, `deleted`, `parent-uri`, `verb`, `object-type`, `object`, `target-type`, `target`, `plink`, `allow_cid`, `allow_gid`, `deny_cid`, `deny_gid`, `private`, `bookmark`, `body`, `tag`, `attach`, `app`, `origin`, `network`, `postopts`, `resource-id`, `event-id`, `inform`, `file`, `contact-id`, `gcontact-id`, `author-id`, `owner-id`, `thr-parent`, `global`, `rendered-html`, `rendered-hash`) VALUES (0, 'remote', 0, 000000001958917e1426664031341717, 'urn:X-dfrn::0:000000001958917e1426664031341717', '', '', '', '', '', '', '', '2017-02-01 06:20:04', '2017-02-01 06:20:04', '2017-02-01 06:20:04', '2017-02-01 06:20:04', '2017-02-01 06:20:04', '', '', '', 0, 1, 0, 'urn:X-dfrn::0:000000001958917e1426664031341717', '', '', '', '', '', 'http:///display/000000001958917e1426664031341717', '', '', '', '', 0, 0, '', '', '', '', 0, 'dfrn', '', '', 0, '', '', 0, 6, 0, 0, 'urn:X-dfrn::0:000000001958917e1426664031341717', true, '', 'd41d8cd98f00b204e9800998ecf8427e') returned false.
Illegal double '000000001958917e1426664031341717' value found during parsing

**Comment by annando** [comment]
@mexon that's nice in a weird meaning ;-) I will dig into it. That means, i can't use ````is_numeric```` for the checks. I should have known better ;-)

**Pull request merged**
