### PR TITLE
Update use of PasswordExposed API

### PR DESCRIPTION
**Pull request by mexon**
It seems this library has changed its API, and the previous console command for changing passwords doesn't work.  This brings it up to date so that the command works again.

### CODE REVIEW

**Comment by mexon** [comment]
Oh actually, I see other people are working on this area.  I'm not completely sure this patch is based on the latest dependencies.  Closing.

**Comment by MrPetovan** [comment]
Why did you retract your PR? I recently bumped the version `password_exposed` without checking for backward breaking changes. Your changes might be warranted.

**Comment by annando** [comment]
Yeah, from my point of view this change is needed.

**Comment by mexon** [comment]
Ah right.  This was a "works for me" patch, but I wasn't completely sure my testing was on an up-to-date develop branch, or that I had properly run composer.  I saw recent changes from @MrPetovan related to upgrading Guzzle.  I never actually tracked down the specific Guzzle version number that introduced the change.  And I ran out of weekend time, so I decided to just let things settle down in that area before trying again.  Reopening.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
