### PR TITLE
Deprecate RINO1 function, implements RINO2, remove unused crypro functions

### PR DESCRIPTION
**Pull request by fabrixxm**
This patch remove RINO encrypt as a fix to #1655.
Nodes should use (valid) https to encrypt communication, if this patch is merged.

For every delivery, RINO is requested if enabled locally and "1" is returned if enabled remotely.
This allow to disable and/or version RINO crypto: with this patch, rino is always set to 0 when delivery first requests is send, and 0 is always returned to first delivery requests.

If anyone wants to write a better crypto algorithm for RINO, we could use RINO parameter in request as RINO version.

### CODE REVIEW

**Comment by fabrixxm** [comment]
Last commit brings back RINO 1 as fallback for old nodes. By default RINO 2 is used, with crypto functions from https://github.com/defuse/php-encryption

**Comment by annando** [comment]
You are fast! Have you tested it between different servers?

**Comment by fabrixxm** [comment]
I tested it between same code on same server, under two different subfolders.
I want to test it against "master" code (and I think I need to re-add the check for "mcrypt_encrypt")

**Comment by annando** [comment]
Maybe we should hide the new stuff under a config value that can only be set in .htconfig.php by now? Then we could do save field tests in the upcoming release without risking a communication problem?

**Comment by fabrixxm** [comment]
oki

**Comment by fabrixxm** [comment]
Last commit adds a settings in admin/site to select RINO version (disabled / RINO1 / RINO2 )
On communication, lower common version is used.
tested also between "master" code with rino enabled and node with RINO2

**Comment by mama21mama** [comment]
as active this

**Comment by annando** [comment]
@fabrixxm From my point of view it seems to look fine? @tobiasd and you have tested today. Please tell if there are any obstacles.

**Comment by fabrixxm** [comment]
I'm running it on my server and Tobias on his. Looks like communications works as usual

**Comment by tobiasd** [comment]
I don't see nothing anormal behaviour so far. But I think we should watch/test it for some time longer.

**Comment by annando** [comment]
Do we want to test it some time longer? Or should we accept the pull request now?

**Comment by tobiasd** [comment]
It seems to be working fine for me

**Comment by fabrixxm** [comment]
:+1:

**Pull request merged**
