### PR TITLE
New custom profile fields feature 

### LINKED ISSUE #7817: New custom profile field feature
Offshoot of #7777
Closes #8153

This feature is intended to replace the multiple profile feature to make it easier to use and overall less confusing. instead of multiple full profiles that can be assigned to contacts, users can create custom profile fields beyond the basic public ones that can each be visible to contacts, groups or hidden from specific contacts and groups.

A migration script will convert the existing multiple profiles into custom profile fields with the adequate permission set according to their current visibility.

Task list:
- [x] Display of the basic public profile fields.
- [x] Conditional display of the custom profile fields
- [x] Migration script from multiple profiles to custom profile fields
- [x] "View profile as" feature
- [x] Cross-theme ACL selector (related to #7308)
- [x] Fix birthdate input, storage and display
- [x] Profile field management screen:
    - [x] creation
    - [x] update
    - [x] deletion
    - [x] reordering
- [x] Document feature
- [x] Remove `mod/profperm`
- [x] Deprecate `contact.profile-id`
- [x] Remove `ContactSelector::profileAssign`
- [x] Update User account export
- [x] Update user account import
- [x] Update API

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #7817
Redo of #7777 
Part of #4090 

This is it, three months and a release later, I'm proud to present you with the much awaited custom profile field feature meant to replace the multiple profiles one.

## A few screenshots ##

Custom profile settings:
friendica-custom-fields-permissions

friendica-custom-fields-reorder

My profile viewed as a random contact:
friendica-custom-fields-profile-hypolite

My profile viewed as Claes Wallin:
friendica-custom-fields-profile-claes

But wait a minute, why is this a Draft PR?

## The roadblock ##

I created a `Database\PostUpdate` method to migrate existing profiles (default and multiple) to the new custom fields feature, but it doesn't seem to be ever called and I don't know why. I know I can trigger it manually but my point is to test the seamless migration expected during the next release.

Did I do something wrong?

### CODE REVIEW

**Comment by AlfredSK** [comment]
Public number of fingers. Aha. 😆

**Comment by MrPetovan** [comment]
And now of course I'm in merge conflict hell with @nupplaphil 's necessary work

**Comment by nupplaphil** [comment]
#8142 is the last one for now :X .. Sorry ... At least it should be 1:1 replacements `Class::method()` to `DI::class()->method()` :((

**Comment by MrPetovan** [comment]
> #8142 is the last one for now :X .. Sorry ... At least it should be 1:1 replacements `Class::method()` to `DI::class()->method()` :((

It's fine, it's just going to be merged after this. I spent a full hour of my time merging conflicts and I believe you would have an easier time fixing yours after this is merged.

**Comment by MrPetovan** [comment]
I just realized I forgot about the API which is still trying to retrieve the now deprecated profile fields.

**Pull request closed without merging**
