### PR TITLE
[TASK] Automatic installation: Install theme

### PR DESCRIPTION
**Pull request by M-arcus**
Resolves https://github.com/friendica/friendica/issues/5033

### CODE REVIEW

**Comment by tobiasd** [comment]
The bugfix should be directed at the `2018.05-rc` branch, not the `develop`. Could you please change the merge target.

**Comment by M-arcus** [comment]
@tobiasd Changed the target branch

**Comment by MrPetovan** [comment]
No, it doesn't seem to be changing anything.

**Comment by MrPetovan** [comment]
Ha, interesting. Oh well.

**Pull request merged**
