### PR TITLE
The conversation functionality moved to a class

### PR DESCRIPTION
**Pull request by annando**
See https://github.com/friendica/friendica/pull/10750

### CODE REVIEW

**Comment by nupplaphil** [comment]
@annando doesn't work as expected :-/ .. Didn't thought it's a fixed enum, I'll try again ^^

**Comment by annando** [comment]
@nupplaphil the rule is currently not configurable, so I removed it. See here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2559

**Comment by MrPetovan** [comment]
This worked!

**Comment by annando** [comment]
We should merge this soon to prevent future merge conflicts ...

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
