### PR TITLE
Update PHP versions and add PHP 8.2 for testing

### PR DESCRIPTION
**Pull request by toddy15**
This is a suggestion for your CI pipelines to include PHP 8.2 for testing.

### CODE REVIEW

**Comment by toddy15** [comment]
... ah, it's not that easy, of course. The build fails because the docker image does not have a tag for the new PHP version for 8.0 and 8.1, and for PHP 8.2 there's the whole image missing. I assume that the images are pulled from https://hub.docker.com/u/friendicaci, correct?

@nupplaphil, could you update the docker images? I can see you've done it the last time, so I guess you have access to friendicaci on the docker hub. :smile:

Regards,
Tobias

**Comment by MrPetovan** [comment]
Errors from Woodpecker:
```
Error response from daemon: manifest for friendicaci/php8.0:php8.0.29 not found: manifest unknown: manifest unknown
```
```
Error response from daemon: manifest for friendicaci/php8.1:php8.1.20 not found: manifest unknown: manifest unknown
```
```
Error response from daemon: pull access denied for friendicaci/php8.2, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by nupplaphil** [comment]
New Docker images pushed, changes are documented - see https://github.com/friendica/friendica-docker-ci/pull/11

**Comment by MrPetovan** [comment]
Still the error
```
Error response from daemon: pull access denied for friendicaci/php8.2, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by toddy15** [comment]
Yes, the image for PHP 8.2 is missing on docker hub -- @nupplaphil, did you already push that?

**Comment by nupplaphil** [comment]
I accidentally pushed it to the wrong namespace, fixed it *g*

**Comment by MrPetovan** [comment]
The linked PR hasn't been merged, maybe the "pushed" part of @nupplaphil only applies to his local git

**Comment by toddy15** [comment]
It just appeared on docker hub a few seconds ago. Thanks a lot!

**Comment by MrPetovan** [comment]
The checks are marked as successful even though it's still ongoing in Woodpecker?

**Comment by MrPetovan** [comment]
Oops, pressed the wrong button, we still should be fine.

**Comment by nupplaphil** [comment]
> The checks are marked as successful even though it's still ongoing in Woodpecker?

yepp .. this is a known issue
-> the first successful test of a test-matrix sends a success to GitHub ..  I hope this will be fixed once we moved to gitea -.-***

**Comment by nupplaphil** [comment]
murphys law --> PHP 8.2 introduced some deprecation/changes, which make PHPUnit fail ;-)
--> I'm on a fixup

**Pull request merged**
