### PR TITLE
Always use utf8mb4 from now on

### PR DESCRIPTION
**Pull request by annando**
See the discussion here: https://github.com/friendica/friendica/pull/3326

This pull request updates the database to a collation with the charset "utf8mb4".

### CODE REVIEW

**Comment by annando** [comment]
This is the most general one :-)

And it is said that it has a higher performance than ```utf8mb4_unicode_ci```: https://dev.mysql.com/doc/refman/5.7/en/charset-unicode-sets.html

> For any Unicode character set, operations performed using the xxx_general_ci collation are faster than those for the xxx_unicode_ci collation. For example, comparisons for the utf8_general_ci collation are faster, but slightly less correct, than comparisons for utf8_unicode_ci.

**Comment by AlfredSK** [comment]
Hmm. I switched my collations manually to utf8mb4_unicode_ci some month ago. I'm not a database pro but what I've read before I did so was that utf8mb4_unicode_ci is the recommended way to go.
http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
What does the change to utf8mb4_general_ci means for my database? Will this PR alter the structure of my database again?

**Comment by tobiasd** [comment]
There seems to be a problem with [utf8mb4_general_ci](https://friendica.xyz/display/adf174d51058f1d207a3c2f512519381) with MySQL 5.1.

**Comment by AlfredSK** [comment]
As far as I know utf8mb4 was introduced with MySQL 5.5. It is not available in MySQL 5.1.

**Comment by tobiasd** [comment]
Ok, as 5.5 is the minimal requirement for Friendica, it is unfortunate but okish. We just need to remember mentioning it in the release notes.

**Comment by annando** [comment]
MySQL 5.5 was introduced more than 6 years ago. So I think we really can now say that this is the minimal requirement.

**Comment by tobiasd** [comment]
We have said so long ago. But if you change something that really hard relies on this (and I think this is the first issue of that sort) it would be nice to explicitly tell so ;-)

**Comment by annando** [comment]
We have to tell that especially when the master gets updated.

**Pull request merged**
