### PR TITLE
Scrape: Always take the first alias

### PR DESCRIPTION
**Pull request by annando**
This functionality is used to fetch data about profiles. OStatus are having several ways to be addressed. One is the format http://server.tld/username - the other is http://server.tld/user/(number). Newer releases of GNU Social seemed to have added aliases like http://server.tld/index.php/username as well - which we don't need.

This is a small change so that we will always get the alias in the format "http://server.tld/user/(number)".

### CODE REVIEW

**Comment by redmatrix** [comment]
Was testing related stuff this morning - and a salmon was rejected because I used $host/user/nnn in an activityobject and GS didn't recognise it - because it wasn't the account uri - which was officially $host/index.php/user/nnn . So it's a bit more complicated. I'm thinking you have to use whatever value is listed in the webfinger profile entry and ignore all the aliases.

**Comment by annando** [comment]
@redmatrix Hmm ... sounds like a lot of fun. I guess I have to have a deeper look at it.

**Comment by annando** [comment]
I did some changes to the mechanism. "probe_url" does now work as well when the profile url contains an "index.php".

I opened an issue for GNU Social about this: https://git.gnu.io/gnu/gnu-social/issues/176 which is still unanswered. But this doesn't matter since this pull request will make things better in any way. So I think that it should be merged.

**Comment by redmatrix** [comment]
I've asked for clarification of the "one true profile URL" from the person who has been doing the recent webfinger work (mmn) because I suspect the requirement for index.php may depend on the presence of the clean_urls setting. A recent change was made in GNU-social where salmons might be rejected if they didn't reference the "one true" accounturi and it wasn't from a connection. I did look at the value it was expecting to find and this contained index.php  on my test site - but this was with clean urls turned off. I suspect that this check may need extending on the GNU-Social side to examine the entire array of possible aliases because we have no way of knowing the state of the clean_urls setting from a remote site. I'll try to find out more and let you know if anything needs changing.

**Comment by annando** [comment]
@redmatrix Thanks! I'm running a GNU Social server as well. How is the setting named there? Then I maybe could test.

**Comment by redmatrix** [comment]
Have a look at plugins/OStatus/actions/usersalmon.php around line 69 for "The owner of this salmon endpoint was not in the context of the carried slap." The line number might be a bit off because I've had to add a lot of debug logging statements. It's basically looking at $this->target->getUri();

On my test site printing this returned 'https://st.macgirvin.com/index.php/user/1'

Also note that I believe this check was only added in the last few weeks.

**Comment by annando** [comment]
I will update the alias and the url value in the ostatus.php to the correct values when we receive messages. Currently I'm doing some development there that should ensure that we always use the correct address.

@tobiasd I would suggest accepting this pull request. I will do the further work in another pull request.

**Comment by annando** [comment]
@redmatrix I'm now taking the alias from the feed - see the changes in Scrape.php in the pull request https://github.com/friendica/friendica/pull/2427

**Pull request merged**
