### PR TITLE
Improved notification messages

### PR DESCRIPTION
**Pull request by annando**
This is slight improvement to the notifications. It fixes https://github.com/friendica/friendica/issues/6757, fixes https://github.com/friendica/friendica/issues/6418 and fixes https://github.com/friendica/friendica/issues/6205

It also adds the first characters of the post to the notification. Also it removes the URLs from the notification text, since this is converted to plain text later on.

P.S.: I'm still unsure if we should some text to the notifications to separate being tagged on a post that one already interacted with in comparison to being tagged on a post you hadn't interacted with before.

P.P.S.: Should "replied to you" have priority before "tagged you"?

### CODE REVIEW

**Comment by MrPetovan** [comment]
> P.P.S.: Should "replied to you" have priority before "tagged you"?

Yes, it's more specific.

**Comment by annando** [comment]
Okay, will change that.

**Comment by annando** [comment]
Okay, done.

**Comment by MrPetovan** [comment]
I just received the following notification:
> **Claes Wallin (韋嘉誠) SE HK** tagged you on your post "I'm rewatching Pierce Brosnan's James #Bond …"

Even though it was a direct reply on my top-level post. I was expecting:

> **Claes Wallin (韋嘉誠) SE HK**  replied to your post "I'm rewatching Pierce Brosnan's James #Bond …"

**Comment by MrPetovan** [comment]
By the way, this is a great improvement!

**Comment by tobiasd** [comment]
I got two notifications about a comment by one of my contacts who had "commented on my posting ..." (for the same posting). They wrote one comment and one like. The like I think should not be called a comment.

**Comment by annando** [comment]
@MrPetovan the "replied to your ..." is done only for comments, since first level comments are often not a comment to the original post but some ongoing discussion between people who don't use the threaded comments. (For example comments from Diaspora are always "flat")

@tobiasd this shouldn't happen. I have to have a look at it.

**Pull request merged**
