### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by tek-aevl**
added border to the left side of comment and/or replies... to give a visual effect to who responded to who.. looks decent from browser edit, maybe if the color would fit the theme..

### CODE REVIEW

**Comment by tek-aevl** [comment]
if this looks dumb, that wasn't the goal., I tested it again and saw a bug that breaks more than it's worth.

**Comment by tek-aevl** [comment]
Screenshot 2023-06-10 020849

**Comment by MrPetovan** [comment]
Is it an actual screenshot of your changes in action?

**Comment by tek-aevl** [comment]
Yes. If there was a way to make it not show on the main post part. I was guessing as to the location of the change.

**Comment by MrPetovan** [comment]
Got it, please reopen this PR when you’ve solved the display issue.

**Pull request closed without merging**
