### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by urbalazs**

### CODE REVIEW

**Comment by MrPetovan** [comment]
Thank you, I can't remember what's the policy for typos in the source strings, I thought we agreed to fix the typos in the translated strings in Transifex to avoid undoing all the existing translations that were done using the wrong source string?

@tobiasd

**Comment by tobiasd** [comment]
In this case it is a string only the admins of the nodes will see (if ever), hence I'm fine with fixing it in the source. But the xgettext script needs to be run, to extract the updated string (and make the test happy).

**Review by MrPetovan — CHANGES_REQUESTED** [review]
@urbalazs Please run `bin/run_xgettext.sh` from the Friendica root folder and commit the produced changes.

**Comment by tobiasd** [comment]
I'm merging this and re-create the translation file afterwards.

**Pull request merged**
