### PR TITLE
New function to recursively delete data

### PR DESCRIPTION
**Pull request by annando**
There is a new function to safely delete data including all dependencies.

Example:
```

$table = "item";
$condition = array("id" => 4711);
dba::delete($table, $condition);
```
This will not only delete this item entry but also depending entries in other tables. If this item entry is a thread starter then the whole thread is deleted.

This is a function that will help here: https://github.com/friendica/friendica/issues/3409

### CODE REVIEW

**Comment by Hypolite** [comment]
I suggest we do that in a background process, since I expect the performance penalty for any removal to be quite significant.

**Comment by annando** [comment]
I don't want to split this process, I would like to keep it in a single transaction for the data integrity. But I agree that such a delete process is normally a background job.

**Comment by Hypolite** [comment]
For my peace of mind, could you please time an item deletion from the timeline with and without this feature activated? Maybe it isn't such a big deal since the DB structure is stored in a static array anyway,

**Comment by annando** [comment]
I do understand your concerns. Deletion from the timeline is no problem since we don't delete there. We simply set a flag. The deletion is done in the background.

But I think I can find ways to reduce the queries to speed up the process.

**Comment by annando** [comment]
The sql commands for the deletion of an comment are now looking like this:
```
DELETE FROM `item` WHERE `id` IN (15216544);
DELETE FROM `item` WHERE `parent` IN (15216544);
DELETE FROM `item_id` WHERE `iid` IN (15216544);
DELETE FROM `notify` WHERE `parent` IN (15216544);
DELETE FROM `notify-threads` WHERE `master-parent-item` IN (15216544);
DELETE FROM `sign` WHERE `iid` IN (15216544);
DELETE FROM `term` WHERE `oid` IN (15216544);
DELETE FROM `thread` WHERE `iid` IN (15216544);
```

Deleting a whole thread looks like this:
```
DELETE FROM `item` WHERE `id` IN ('15216125', '15216369', '15216544', '15216545', '15216546', '15216547', '15216739', '15216818', '15219820', '15220531', '15220532', '15220534', '15220535', '15220537', '15220538', '15220539', '15220540', '15220541', '15220545', '15220797', '15220820', '15287352', '15289267', '15289268', '15289269', '15289270', '15289272', '15289274', '15289276', '15289361', '15289379', '15289470', '15289497', '15289535', '15289662', '15289995', '15290069', '15290074', '15290113', '15290209', '15290473', '15290478', '15290641', '15290643', '15290927', '15291232', '15291408', '15292410');
DELETE FROM `item` WHERE `parent` IN ('15216369', '15216544', '15216545', '15216546', '15216547', '15216739', '15216818', '15219820', '15220531', '15220532', '15220534', '15220535', '15220537', '15220538', '15220539', '15220540', '15220541', '15220545', '15220797', '15220820', '15287352', '15289267', '15289268', '15289269', '15289270', '15289272', '15289274', '15289276', '15289361', '15289379', '15289470', '15289497', '15289535', '15289662', '15289995', '15290069', '15290074', '15290113', '15290209', '15290473', '15290478', '15290641', '15290643', '15290927', '15291232', '15291408', '15292410');
DELETE FROM `item_id` WHERE `iid` IN ('15216369', '15216544', '15216545', '15216546', '15216547', '15216739', '15216818', '15219820', '15220531', '15220532', '15220534', '15220535', '15220537', '15220538', '15220539', '15220540', '15220541', '15220545', '15220797', '15220820', '15287352', '15289267', '15289268', '15289269', '15289270', '15289272', '15289274', '15289276', '15289361', '15289379', '15289470', '15289497', '15289535', '15289662', '15289995', '15290069', '15290074', '15290113', '15290209', '15290473', '15290478', '15290641', '15290643', '15290927', '15291232', '15291408', '15292410', '15216125');
DELETE FROM `notify` WHERE `parent` IN ('15216369', '15216544', '15216545', '15216546', '15216547', '15216739', '15216818', '15219820', '15220531', '15220532', '15220534', '15220535', '15220537', '15220538', '15220539', '15220540', '15220541', '15220545', '15220797', '15220820', '15287352', '15289267', '15289268', '15289269', '15289270', '15289272', '15289274', '15289276', '15289361', '15289379', '15289470', '15289497', '15289535', '15289662', '15289995', '15290069', '15290074', '15290113', '15290209', '15290473', '15290478', '15290641', '15290643', '15290927', '15291232', '15291408', '15292410');
DELETE FROM `notify` WHERE `id` IN ('328139', '328140', '328141', '328142', '328143', '328145', '328148');
DELETE FROM `notify-threads` WHERE `master-parent-item` IN ('15216369', '15216544', '15216545', '15216546', '15216547', '15216739', '15216818', '15219820', '15220531', '15220532', '15220534', '15220535', '15220537', '15220538', '15220539', '15220540', '15220541', '15220545', '15220797', '15220820', '15287352', '15289267', '15289268', '15289269', '15289270', '15289272', '15289274', '15289276', '15289361', '15289379', '15289470', '15289497', '15289535', '15289662', '15289995', '15290069', '15290074', '15290113', '15290209', '15290473', '15290478', '15290641', '15290643', '15290927', '15291232', '15291408', '15292410', '15216125');
DELETE FROM `notify-threads` WHERE `notify-id` IN ('328139', '328140', '328141', '328142', '328143', '328145', '328148');
DELETE FROM `sign` WHERE `iid` IN ('15216369', '15216544', '15216545', '15216546', '15216547', '15216739', '15216818', '15219820', '15220531', '15220532', '15220534', '15220535', '15220537', '15220538', '15220539', '15220540', '15220541', '15220545', '15220797', '15220820', '15287352', '15289267', '15289268', '15289269', '15289270', '15289272', '15289274', '15289276', '15289361', '15289379', '15289470', '15289497', '15289535', '15289662', '15289995', '15290069', '15290074', '15290113', '15290209', '15290473', '15290478', '15290641', '15290643', '15290927', '15291232', '15291408', '15292410', '15216125');
DELETE FROM `term` WHERE `oid` IN ('15216369', '15216544', '15216545', '15216546', '15216547', '15216739', '15216818', '15219820', '15220531', '15220532', '15220534', '15220535', '15220537', '15220538', '15220539', '15220540', '15220541', '15220545', '15220797', '15220820', '15287352', '15289267', '15289268', '15289269', '15289270', '15289272', '15289274', '15289276', '15289361', '15289379', '15289470', '15289497', '15289535', '15289662', '15289995', '15290069', '15290074', '15290113', '15290209', '15290473', '15290478', '15290641', '15290643', '15290927', '15291232', '15291408', '15292410', '15216125');
DELETE FROM `thread` WHERE `iid` IN ('15216369', '15216544', '15216545', '15216546', '15216547', '15216739', '15216818', '15219820', '15220531', '15220532', '15220534', '15220535', '15220537', '15220538', '15220539', '15220540', '15220541', '15220545', '15220797', '15220820', '15287352', '15289267', '15289268', '15289269', '15289270', '15289272', '15289274', '15289276', '15289361', '15289379', '15289470', '15289497', '15289535', '15289662', '15289995', '15290069', '15290074', '15290113', '15290209', '15290473', '15290478', '15290641', '15290643', '15290927', '15291232', '15291408', '15292410', '15216125');

This is a limited number of queries. Only missing indexes could be a problem, I think.

I'm currently doing some more tests on more complex tasks - like deleting a contact or user. I will tell when I'm sure that it works on this as well.

**Comment by annando** [comment]
I worked on it the whole day. Now I think it is working great. I simulated the deletion of my biggest user and had no issues with it.

@Hypolite concerning the "do that in a background process": See "include/remove_contact.php". At the front end the contact entry is removed, then "remove_contact.php" is called in the background. The "delete" function can work even when the deleted table entry is already removed. Even then the related entries are removed.

**Pull request merged**
