### PR TITLE
Replace references of mod/subthread with item/{id}/follow

### LINKED ISSUE #9872: Friendica api return various document type and responses
- [x] I have searched open and closed issues for duplicates

### Bug Description

API endpoint for friendica currently doesn't return either a json value or a standardized response.

### Steps to Reproduce

1.  Like a post, subscribe to a thread or star a post
2. Check the response in the Network tab

Actual Result:

#### Returns

--------------
200

HTML Page

#### Returns

--------------
200

```
{status: 'OK'}
```

#### Returns

--------------
200

1 (or) 0

Expected Result:

A valid json response containing the status of the request and the current state of the action

```
{
    status: 'ok',
    post_id: '17',
    verb: 'like',
    state: 1
}
```

### Platform Info

Friendica Version:

2021.03-dev

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #9872 
Part of #4090

I'm revisiting all the local API modules relating to item manipulation (follow thread, like, star, ignore, etc...) according to the feedback in #9872 and I will submit a separate PR for each module because they all are independent.

### CODE REVIEW

**Comment by annando** [comment]
In the future I would like to get rid of the `item`.`id` field and would prefer working with the `uri-id` only. This is already realized in the Mastodon API part.

**Comment by MrPetovan** [comment]
I hear you, let's do that in another PR when everything is normalized.

**Comment by annando** [comment]
I just wanted to prevent that we forget about this when adding stuff to the Mastodon part.

**Comment by MrPetovan** [comment]
Fair enough.

**Comment by annando** [comment]
I guess we will have a conflict after accepting every single of these PR? :grimacing:

**Comment by MrPetovan** [comment]
Yup! But it was easy to review, right?

**Comment by annando** [comment]
Yeah, review is better - but it's more work for you. And it reminds me of the work, where we very often have got merge conflicts in some parts like the translation files because we work with several people at the same code at the same time.

**Comment by MrPetovan** [comment]
It's okay, I can deal with slightly more work to merge the conflicts.

**Comment by annando** [comment]
And the last conflict!

**Comment by MrPetovan** [comment]
It's fixed.

**Pull request merged**
