### PR TITLE
Updating develop with my mistaken PRs

### PR DESCRIPTION
**Pull request by Hypolite**
This PR is just a reminder that the develop branch isn't up-to-date because of my first few mistaken PRs against master.

### CODE REVIEW

**Comment by tobiasd** [comment]
develop will be merged into master and then master in develop this should get your commits then in develop. But you should check after the mergers if we overlooked one of your things when solving the merge conflicts.

**Comment by Hypolite** [comment]
The merge conflict is only on translation strings, it shouldn't be a problem.

I'm just impatient to have my PRs finally on my instance since I'm on the `develop` branch. 😋

**Comment by annando** [comment]
Can we now close this PR?

**Comment by Hypolite** [comment]
Yup.

**Pull request closed without merging**
