### PR TITLE
Redux horizontal masonry, height allocation feature with ensured dimensions

### LINKED ISSUE #13455: [frio] Render placeholders for embedded images to prevent timeline from jumping around
Sometimes, in timelines heavy with images (and network connections that are a bit slower), Friendica in "frio" theme will load posts first and then apparently populate them with images if there are any to display. Though this works reasonably well, it's a bit annoying at times: In example, while adding a comment somewhere in the page, reloading and displaying images above will almost immediately lead to your page "jumping" and you losing track of where you were actually typing. Not a real bug, merely an inconvenience; maybe it would be possible to pre-render placeholders for images to be loaded beforehand in order to avoid this behaviour?

### PR DESCRIPTION
**Pull request by MrPetovan**
Redux of #13463 
Closes https://github.com/friendica/friendica/issues/13455 (again)

@annando See what was needed from my standpoint to maintain both features and be able to reliably pick between them? 😄

### CODE REVIEW

**Comment by MrPetovan** [comment]
I have checked out this branch on my main node, I'll keep monitoring for a few days.

**Comment by MrPetovan** [comment]
No issues so far on my production node, I believe we can go forward with the merge on `develop`.

**Comment by Raroun** [comment]
@MrPetovan 
I guess it is related to this PR.
After a git pull, Images are now displayed with big empty spaces:

Bildschirmfoto 2023-10-04 um 12 49 42

Bildschirmfoto 2023-10-04 um 12 51 29

**Comment by MrPetovan** [comment]
@Raroun As usual, on the develop branch, if the CSS changes, you have to clear your browser's cache manually. People upgrading on the `stable` branch will not have the same issue as we are cache-busting based on the current version string.

**Comment by Raroun** [comment]
Thank you very much.
Ill try to not forget it again - sorry about that :)

**Comment by MrPetovan** [comment]
In the office I used to go, the software Quality Assurance block had a poster reading "If you see something, clear your cache" to parody the New York City Police Department slogan "If you see something, say something".

**Pull request merged**
