### PR TITLE
Add optional GitHub Action for PHP tests

### PR DESCRIPTION
**Pull request by Art4**
This PR reverts commit [f1e268ee0a10cfd801b3ad0cef3aa8b98caf39f5](https://github.com/friendica/friendica/commit/f1e268ee0a10cfd801b3ad0cef3aa8b98caf39f5) from #10251 and allows running the CI Pipeline with Github Actions. The pipeline has to be triggered manually.

Refs https://github.com/friendica/friendica/pull/14529#issuecomment-2465057372 and https://github.com/friendica/friendica/pull/14523#issuecomment-2460797185

### CODE REVIEW

**Comment by Art4** [comment]
I cannot get the pipeline run because of some errors with mariadb, see https://github.com/Art4/friendica/actions/runs/11724292576/job/32657882187

<details><summary>Details</summary>

```
Service container mariadb failed.
  /usr/bin/docker logs --details d498a314d0445e5cfce693c0d5655a337b0e4d024e9a774fa2c1c86d97821469
   2024-11-07 13:47:43+00:00 [Warn] [Entrypoint]: /sys/fs/cgroup///memory.pressure not writable, functionality unavailable to MariaDB
   2024-11-07 13:47:43+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.5.2+maria~ubu2404 started.
  Warning: 07 13:47:43 0 [Warning] mariadbd: io_uring_queue_init() failed with errno 95
  Warning: 07 13:47:43 0 [Warning] InnoDB: liburing disabled: falling back to innodb_use_native_aio=OFF
   2024-11-07 13:47:43+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
   2024-11-07 13:47:43+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.5.2+maria~ubu2404 started.
   2024-11-07 13:47:43+00:00 [Note] [Entrypoint]: Initializing database files
   2024-11-07 13:47:44 0 [Note] Starting MariaDB 11.5.2-MariaDB-ubu2404 source revision ea75a0b6009b0251e83193cd38c3974e36b65e06 server_uid 72+4ASMvYxproTQgRqIDplDA1XA= as process 92
   2024-11-07 13:47:44 0 [Note] InnoDB: Compressed tables use zlib 1.3
   2024-11-07 13:47:44 0 [Note] InnoDB: Number of transaction pools: 1
   2024-11-07 13:47:44 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
   2024-11-07 13:47:44 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
  Warning: 07 13:47:44 0 [Warning] mariadbd: io_uring_queue_init() failed with errno 95
  Warning: 07 13:47:44 0 [Warning] InnoDB: liburing disabled: falling back to innodb_use_native_aio=OFF
   2024-11-07 13:47:44 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
   2024-11-07 13:47:44 0 [Note] InnoDB: Completed initialization of buffer pool
   2024-11-07 13:47:44 0 [Note] InnoDB: File system buffers for log disabled (block size=4096 bytes)
   2024-11-07 13:47:44 0 [Note] InnoDB: End of log at LSN=46316
   2024-11-07 13:47:44 0 [Note] InnoDB: Opened 3 undo tablespaces
   2024-11-07 13:47:44 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
   2024-11-07 13:47:44 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
   2024-11-07 13:47:44 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
   2024-11-07 13:47:44 0 [Note] InnoDB: log sequence number 46316; transaction id 14
   2024-11-07 13:47:44 0 [Note] Plugin 'FEEDBACK' is disabled.
   2024-11-07 13:47:44 0 [Note] Plugin 'wsrep-provider' is disabled.
   2024-11-07 13:47:46 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
   2024-11-07 13:47:46 0 [Note] mariadbd: ready for connections.
   Version: '11.5.2-MariaDB-ubu2404'  socket: '/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
   2024-11-07 13:47:47 0 [Note] mariadbd (initiated by: unknown): Normal shutdown
   2024-11-07 13:47:47 0 [Note] InnoDB: FTS optimize thread exiting.
   2024-11-07 13:47:47 0 [Note] InnoDB: Starting shutdown...
   2024-11-07 13:47:47 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
   2024-11-07 13:47:47 0 [Note] InnoDB: Buffer pool(s) dump completed at 241107 13:47:47
   2024-11-07 13:47:48 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
   2024-11-07 13:47:48 0 [Note] InnoDB: Shutdown completed; log sequence number 47891; transaction id 15
   2024-11-07 13:47:48 0 [Note] mariadbd: Shutdown complete
   
   2024-11-07 13:47:48 0 [Note] Starting MariaDB 11.5.2-MariaDB-ubu2404 source revision ea75a0b6009b0251e83193cd38c3974e36b65e06 server_uid 72+4ASMvYxproTQgRqIDplDA1XA= as process 1
   2024-11-07 13:47:48 0 [Note] InnoDB: Compressed tables use zlib 1.3
   2024-11-07 13:47:48 0 [Note] InnoDB: Number of transaction pools: 1
   2024-11-07 13:47:48 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
   2024-11-07 13:47:48 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
  Warning: 07 13:47:48 0 [Warning] mariadbd: io_uring_queue_init() failed with errno 95
  Warning: 07 13:47:48 0 [Warning] InnoDB: liburing disabled: falling back to innodb_use_native_aio=OFF
   2024-11-07 13:47:48 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
   2024-11-07 13:47:48 0 [Note] InnoDB: Completed initialization of buffer pool
   2024-11-07 13:47:48 0 [Note] InnoDB: File system buffers for log disabled (block size=4096 bytes)
   2024-11-07 13:47:48 0 [Note] InnoDB: End of log at LSN=47891
   2024-11-07 13:47:48 0 [Note] InnoDB: Opened 3 undo tablespaces
   2024-11-07 13:47:48 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
   2024-11-07 13:47:48 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
   2024-11-07 13:47:48 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
   2024-11-07 13:47:48 0 [Note] InnoDB: log sequence number 47891; transaction id 15
   2024-11-07 13:47:48 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
   2024-11-07 13:47:48 0 [Note] Plugin 'FEEDBACK' is disabled.
   2024-11-07 13:47:48 0 [Note] Plugin 'wsrep-provider' is disabled.
   2024-11-07 13:47:48 0 [Note] InnoDB: Buffer pool(s) load completed at 241107 13:47:48
   2024-11-07 13:47:50 0 [Note] Server socket created on IP: '0.0.0.0'.
   2024-11-07 13:47:50 0 [Note] Server socket created on IP: '::'.
   2024-11-07 13:47:50 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
   2024-11-07 13:47:50 0 [Note] mariadbd: ready for connections.
   Version: '11.5.2-MariaDB-ubu2404'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
   2024-11-07 13:47:44+00:00 [Note] [Entrypoint]: Database files initialized
   2024-11-07 13:47:44+00:00 [Note] [Entrypoint]: Starting temporary server
   2024-11-07 13:47:44+00:00 [Note] [Entrypoint]: Waiting for server startup
   2024-11-07 13:47:47+00:00 [Note] [Entrypoint]: Temporary server started.
   2024-11-07 13:47:47+00:00 [Note] [Entrypoint]: Creating database test
   2024-11-07 13:47:47+00:00 [Note] [Entrypoint]: Creating user test
   2024-11-07 13:47:47+00:00 [Note] [Entrypoint]: Giving user test access to schema test
   2024-11-07 13:47:47+00:00 [Note] [Entrypoint]: Securing system users (equivalent to running mysql_secure_installation)
   
   2024-11-07 13:47:47+00:00 [Note] [Entrypoint]: Stopping temporary server
   2024-11-07 13:47:48+00:00 [Note] [Entrypoint]: Temporary server stopped
   
   2024-11-07 13:47:48+00:00 [Note] [Entrypoint]: MariaDB init process done. Ready for start up.
   
  Error: Failed to initialize container mariadb:latest
Error: One or more containers failed to start.
```

</details> 

It seems like mariadb successfully started and simply shut down again before any tests has started.

Does anybody has a clue how to fix this?

**Comment by nupplaphil** [comment]
Hi, wouldn't it be easier for you to get access to the woodpecker server instead of re-activating github as a second CI ?
I know, I'm no more that responsive :-( , but the reason, we switched, was to ultimative get rid of github at all.

I could think about a fallback that merging of PRs "just" execute the file-creation and not the whole PR-check. So at least the files are up2date all the time.

The reason, my server (opensocial.at)I is included in the CI-pipeline, is because of the high amount of resource usage during execution (spanning up 4-5 mariadbs in parallel & phpunit-executions).

**Comment by Art4** [comment]
> Hi, wouldn't it be easier for you to get access to the woodpecker server instead of re-activating github as a second CI ? 

I can not help with the woodpecker server, but I can help to enable a second CI server as a fallback. By that I mean that creating this PR is easier for me.

> I know, I'm no more that responsive :-( , but the reason, we switched, was to ultimative get rid of github at all.

I understand and support this view. But in cases like this where a CI server is down for days we should keep an alternative. The same would be true if Github Actions would be down for days, we would start looking for an alternative. As long as the code is on github we could also keep Github Actions as a backup CI.

> I could think about a fallback that merging of PRs "just" execute the file-creation and not the whole PR-check. So at least the files are up2date all the time.
> 
> The reason, my server (opensocial.at)I is included in the CI-pipeline, is because of the high amount of resource usage during execution (spanning up 4-5 mariadbs in parallel & phpunit-executions).

I'm looking into this issue and I'm sure we can improve some of the tests in the CI. i.e. unit tests should be running without mariadb.

**Comment by annando** [comment]
@nupplaphil we really have to see how to stabilize the pipeline and to remove the "single point of failure" situation. It would be great having a second person that could monitor the pipeline. But having a fallback pipeline solution sounds like a good solution to me as well.

**Comment by Art4** [comment]
@MrPetovan Is there a problem with the woodpecker CI server atm? Should I finalize this PR?

**Comment by MrPetovan** [comment]
Yes, this isn't sustainable at the moment.

**Comment by Art4** [comment]
OK, I'll try my best.

**Comment by Art4** [comment]
@MrPetovan Sorry, I'm not able to reactivate the old tests with Github Actions because of an error with mariadb and docker. Maybe @nupplaphil can take a look?

**Comment by bmillwood** [comment]
> @MrPetovan Sorry, I'm not able to reactivate the old tests with Github Actions because of an error with mariadb and docker. Maybe @nupplaphil can take a look?

See https://stackoverflow.com/a/76942538/812053 , although in my tests it only got me a little bit further: https://github.com/bmillwood/friendica/actions/runs/12450543834/job/34757483556?pr=1

**Comment by Art4** [comment]
> > @MrPetovan Sorry, I'm not able to reactivate the old tests with Github Actions because of an error with mariadb and docker. Maybe @nupplaphil can take a look?
> 
> See https://stackoverflow.com/a/76942538/812053 , although in my tests it only got me a little bit further: https://github.com/bmillwood/friendica/actions/runs/12450543834/job/34757483556?pr=1

Thank you very much! :+1: This works and I have resolved all other problems.

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
Very nice work once again!

**Pull request merged**
