### PR TITLE
[frio] Make accordions keyboard actionable

### LINKED ISSUE #10978: [frio] Screen Reader Accessibility Part 4: Make addon setting panels behave like core setting panels
@pvagner

> I have discovered one more since that time:
Under Settings -> Addons each addon can expose its settings. For example on my instance I do have settings for these addons: Language filter, Markdown, Secure mail, Start page...
Settings panels for individual addons are collapsed by default and clicking the heading reveals corresponding panel with the settings. These headings are not keyboard actionable.
I would expect these to work in a similar way how subsections such as general, policies, workers and similar are expanded / collapsed within the administration.

Source: https://github.com/friendica/friendica/issues/1743#issuecomment-966935772

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #10978 

When you try to make something accessible, it benefits everyone, and this time was no different. While working on making the settings panel through the site keyboard actionable, I also improved the overall UX of the addons and connectors settings page.

Necessary addon pendant: https://github.com/friendica/friendica-addons/pull/1210

### CODE REVIEW

**Comment by MrPetovan** [comment]
This PR breaks the compatibility with several addons that are currently marked as "Unsupported". Should we remove them from the official repository?

**Comment by tobiasd** [comment]
Are all _Unsupported_ addons affected?

**Comment by MrPetovan** [comment]
The affected unsupported addons are:
- blogger
- buffer
- notimeline
- xmpp

**Comment by tobiasd** [comment]
I've created two pull requests for the deprecated addons

https://github.com/friendica/friendica-addons/pull/1213
https://git.friendi.ca/friendica/deprecated-addons/pulls/3

and the resources have been removed from transifex.

**Comment by annando** [comment]
@MrPetovan do you have a look at the conflict?

**Comment by MrPetovan** [comment]
I am not notified every time another PR gets merged before this one, producing a new conflict with the translation file. I’ll refresh it shortly.

**Comment by MrPetovan** [comment]
Done.

**Pull request merged**
