### PR TITLE
New option to permit crawlers

### PR DESCRIPTION
**Pull request by annando**
When the option
````

$a->config['system']['permit_crawling'] = true;
````
is set in the .htconfig.php then a not logged in user can only perform one search per minute. This should prevent crawlers from blocking the system.

This addresses the issue https://github.com/friendica/friendica/issues/1924

### CODE REVIEW

**Comment by tobiasd** [comment]
Can you compile a list of all the hidden .htconfig options?

**Comment by annando** [comment]
Where should I put it? In the wiki?

**Comment by tobiasd** [comment]
why not /doc/adminconfig.md or so, linked in from the home.md file in the admin section.

**Comment by annando** [comment]
You are the master :)

**Comment by tobiasd** [comment]
na, just thinking if github (or any other central point) should fail it would be great to distribute this information. or say we switch to @fabrixxm project addon for hosting the code, the wiki might be different and this way we don't need to care about that information to be re-setup :-)

**Comment by annando** [comment]
Done.

**Pull request merged**
