### PR TITLE
use perfect-scrollbars for nav-notifications-menu (and in vier aside)

### PR DESCRIPTION
**Pull request by rabuzarus**
Integrating perfect scrollbar. So js scrollbars can used at places where traditional scrollbars would break the design of the theme. This scrollbars are themeable according to the needs of the theme developers.

At the present time they are used for nav-notifications-menu and for vier aside.

@fabrixxm 
Can you please have a look. I know very little about js. It works but I'm not sure if I implemented it in the correct way

### CODE REVIEW

**Comment by tobiasd** [comment]
can you add an hint from where the lib was loaded in case one tries to update it? I think we should make it a habit for 3rd party stuff.

**Comment by annando** [comment]
I'm not a friend of JS scrollbars. Can you post a link to a screenshot?

**Comment by rabuzarus** [comment]
Sure
Vier:
js-scroll-vier1
js-scroll-vier2

Quattro:
js-scroll-quattro

Vier without:
scroll-vier-normal

The pro for js scrollbars is to me:
* they are slim
* they are themeable through css (thinking about a dark desktop theme which would break the look of a light vier plus theme)
* they only appear on hover (this is especial a plus for the vier aside bar where normal scrollbars capture space and reduce the very limited available width of the sidesbar - next to the fact that left & right padding and margin doesn't look visually like the same (e.g. have a look at the picture at hcard profile pic )

**Comment by rabuzarus** [comment]
@tobiasd 
is the original README OK as a hint?

**Comment by annando** [comment]
But we had scrollbars there before. Where is the opportunity of having JS-controlled scrollbars?

**Comment by tobiasd** [comment]
yes, the original README is fine, I would even be happy if the use lib contains the URL from where it comes from.

**Comment by rabuzarus** [comment]
see my pro points under the pictures:

the most things are visually arguments:
* So scrollbars doesn't break the look of the theme all the time 
because:
* they are themeable to the themes general design (so they haven't have to look like a foreign object > think about a red desktop theme, with standard desktop scrollbars you would have red scrollbars in the theme)
* they only appear on hover (so they only visible when you need them and don't visually disturb all the time (I think this especial a visual benefit for vier aside) 
* the padding distance in right and left is visually the same (like I said above, have a look at the above picture with hcard profile pic -> the standard desktop scrollbar acts visually as a border. So the space from the left border to profilepicture seems not the same like the space from profilepicture to the scrollbar. )

**Comment by fabrixxm** [comment]
I'm ok with this if:
- is not used to scroll the main content of the page. having a standard scrollbar on the right of the window is an expected behavior by the user, that know how use it and know that indicate there is more content to see.
- it degrade gracefully. friendica is quite JS-dependant, it doesn't work with js disabled,but if the browser for some reasons doesn't support js scrollbar, standard scrollbar must be avaiable
- it has standard keyboard support for scrolling. again, do not break user experience

(I didn't tried the code, so my 2nd & 3th points could be the default for the library)

**Comment by annando** [comment]
What i would like to check is if it couldn't be done via CSS.

**Comment by fabrixxm** [comment]
It can't.
CSS scrollbar styling was supported only in some older IE version, with not standard properties.
Maybe you can hide/show scrollbars on mouseover in pure CSS... but keeping same right padding with and without scrollbar could be difficult, because every system has different width for scrollbars

**Comment by annando** [comment]
Hmm ... I'm still unsure. From an UI point of view the UI elements should always be depending on the operating system that is used so that users can identify the elements easily. Maybe that's the reason why you can't change them via CSS.

I would like to have see what the others are thinking about this.

**Comment by rabuzarus** [comment]
My opinion is that the right scrollbar is part of the browser (so it is a desktop element -> standard scrollbar). All stuff in that browser window belongs to the website and should have a look & feel which is consistent with the webpage (theme).
Often traditional desktop elements would break look & feel of the webpage designing elements. 

E.g. look at the github text input field at the bottom of this comments - The text input field, the comment nav-tabs and the buttons have a design which follows the github design and not the design of the desktop.

**Pull request merged**
