### PR TITLE
fix copyright header in 3rd party lib used by frio

### PR DESCRIPTION
**Pull request by tobiasd**
Followup to #12221 which had a failing license check for this file

### CODE REVIEW

**Comment by tobiasd** [comment]
Wrong turn @nupplaphil the file needs to be removed from the license check (or the check needs to be refined).

Also we might want to switch the LICENSE notation to the [REUSE](https://reuse.software/) method proposed by FSFE. It would also make the license check easier, as we'd have to check about the REUSE compliance which is a ready made tool and not our current check against a template for our header.

**Comment by nupplaphil** [comment]
Aaaahh thanks @tobiasd for the hint wit REUSE, I'll take a look.

The current check is really basic (diff to a known header) and as u all already see not that helpful.

At least I thought we are all thinking about the license, even if the check isn't right at every place ;-)

**Comment by tobiasd** [comment]
I would do the replacement of the header information for REUSE compliance; which will be a process anyway.

**Comment by nupplaphil** [comment]
Not necessarily, there's a helper script available to fetch authors based on commits and add the right headers as far as I can see

**Comment by tobiasd** [comment]
Still, I think we should do it step by step. I tried and there are some edge cases in our files that the helper script wont convert properly ;-) I'd like to do it for the 2023.03 release and plan / discuss some things before in the developers forum.

**Pull request closed without merging**
