### PR TITLE
Checks if the database variable is initialized

### PR DESCRIPTION
**Pull request by annando**
This could - or could not - fix this issue: https://f.haeder.net/display/adbba6c61959dd2488d4b9d861387437

### CODE REVIEW

**Comment by annando** [comment]
I'm experiencing strange things with this PR. The poller often returns the message 'Database is uninitialized!' - which didn't happen during my tests.

**Comment by tobiasd** [comment]
So, revert it? Or are you looking for an improvement?

**Comment by annando** [comment]
I'm currently testing an improvement. I rewrote the database class so that it is now a complete static class. Possibly new PHP versions are having problems with classes that contain both class types.

**Comment by annando** [comment]
I will wait for another one or two hours. When there are no errors anymore, I will provide a PR.

**Comment by AlfredSK** [comment]
> The poller often returns the message 'Database is uninitialized!'...
How often do you get this? I've checked my logfile. I don't see such errors.

**Comment by annando** [comment]
I got it with every poller run. This is now solved with the new PR.

**Comment by Quix0r** [comment]
Getting this now for every `CREATE TABLE IF NOT EXISTS`: `Error 0 occurred during database update:`

**Pull request merged**
