### PR TITLE
Remove default post permission modal window

### LINKED ISSUE #8425: Remove modal window for default permission selection in user settings
From https://friendica.mrpetovan.com/display/85a863ed-755e-6e09-00d0-a12012608719 (French Support Forum)

The permission selector used to take a full screen height which warranted the use of a confusing modal window that doesn't immediately save in the user settings. However now the permission selector height is reasonable and can be included as is in the page.

Not sure if the modal window is used in all themes, I'll look into it.

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #8425

### CODE REVIEW

**Comment by annando** [comment]
You changed the heading number for the settings. Does this change also changes all the other settings pages?

**Comment by MrPetovan** [comment]
No, just the Account settings page.

**Comment by annando** [comment]
Can you unify the appearance?

**Comment by MrPetovan** [comment]
It wasn't really the point of this PR but I guess so.

**Comment by MrPetovan** [comment]
Actually, there's much more to it than just the headers, I'm going to create a separate issue.

**Comment by MrPetovan** [comment]
This PR has been simplified to the stated goal.

**Comment by annando** [comment]
Thanks!

**Pull request merged**
