### PR TITLE
Bugfix: Only accept postings from anyone when the relay is configured

### PR DESCRIPTION
**Pull request by annando**
See here: https://friendica.kommune4.de/display/4029d2ca53589cbac43e6c8851614093

### CODE REVIEW

**Comment by rabuzarus** [comment]
The code looks good and should work.

But like I wrote in the support forum. I'm not sure if the fault is completely on our side. Shouldn't the relay server in a way that the user don't get any posts from the relay server if `subscribe` is set to `false`?

From my interpretation of https://github.com/jaywink/social-relay/blob/master/docs/relays.md it should stop. 

> If a previously subscribing node wants to stop subscribing, it MUST either remove the .well-known/x-social-relay file or set subscribe to false.

I just asking because if there is a bug in the social relay I would like to inform @jaywink and would not do a git pull so we have the chance to debug it

**Comment by annando** [comment]
I think that both is correct. The relay shouldn't send these items and additionally the server shouldn't accept the postings.

**Comment by jaywink** [comment]
@rabuzarus you're correct, the relay should not be sending anything if `subscribe: false`. However, it could take an hour for all the relays to read any change in preference, so hundreds of posts could still be delivered before the change is noticed.

I'm not sure what the code wants to do however - doesn't Friendica accept any public content normally? I mean a Diaspora node could be sending some directly, if for example the author shares with a Friendica user. It doesn't require the Friendica user to follow/share back, for example.

Let me know if you find a relay bombing public content to a Friendica node that has set `subscribe: false` over an hour ago. Maybe the `x-social-relay` document can't be parsed or something.

**Comment by rabuzarus** [comment]
@jaywink I have explicit set `subscribe` to `false` two days ago. But even without this "explicit" settings in the friendica config the setting should have been set to `false` because I haven't set `subscribe` to `true` (Maybe I did so some long time ago for some short testing. But I can't remember. Subscribe is definitely `false` in the `well_known/x-social-relay` since 4 days)

A week ago I did a test with with adding `https://relay.iliketoast.net` to friendicas relay server settings (but without enabling `subscribe` because I didn't want to get the public posts.  It should just federate my public posts to the relay). Six days ago I removed the config line with the relay-server and four days ago I inserted a config line with explicit `subscribe` `false` (like I said subscribe was in the `well_known/x-social-relay` already set to false because I haven't set it to `true` in the friendica configs).

Aren't you the owner of this relay? Maybe you can have a look if all works the way it should (my server https://friendica.kommune4.de).

@annando Is there anything I can do from my side. Something like inserting a logger command (I don't want to set the log to debug or data because there would be so much other stuff with these settings).

At the moment it is just an assumption that the social relay is the source of this problem. Can I grab somewhere that it is the iliketoast relay?

**Comment by jaywink** [comment]
@rabuzarus what exactly is the problem you are seeing? I can't say related to the way Friendica sends posts or creates the social-relay doc, since I have zero knowledge of Friendica. But yes I am the relay dev and relay.iliketoast.net maintainer, so if you are for some reason seeing content being sent by that particular relay in your logs, then something is wrong.

I checked your `x-social-relay` doc and it is indeed set to `false` for the subscription part. Actually the JSON doesn't validate since `scope` can't be empty. Kinda silly but anyway it means the relay will delete any cached subscription, which I can confirm has happened, since relay.iliketoast.net has no subscription record for your node at all.

Thus, and confirmed by relay logs, there should be no content delivered from this relay to your node. Do you have log entries proving otherwise? For example from the web server, showing `/receive/public` connections from `relay.iliketoast.net`?

**Comment by rabuzarus** [comment]
> Kinda silly but anyway it means the relay will delete any cached subscription, which I can confirm has happened, since relay.iliketoast.net has no subscription record for your node at all.
Thus, and confirmed by relay logs, there should be no content delivered from this relay to your node. 

Cool this is what I wanted to know.

> Do you have log entries proving otherwise? For example from the web server, showing /receive/public connections from relay.iliketoast.net?

Puh this was a little bit difficult on the limited possibilities of a shared host. But you if your the IP of relay.iliketoast.net is really 46.4.94.47 nothing comes from it.

Thanks a lot @jaywink for taking the time to help.

@annando 
to don't pollute the PR comment section anymore I will use the original friendica support thread for further discussion

**Pull request merged**
