### PR TITLE
Urgent bugfix: Non existing field / double "network" in field list

### PR DESCRIPTION
**Pull request by annando**
While I created the next PR (replacing "fetch_first" with "selectFirst") I realized two bugs that effectively killed the communication between Friendica servers.

One resulted in an empty network, the other one created an SQL error because of an field that hadn't existed at all in the database.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Fixes #5247

**Comment by annando** [comment]
Sorry for the two errors. Hopefully not too much people had fetched this version.

**Comment by rabuzarus** [comment]
@annando 
> 	heluecht 2018-06-19: from my point of view this whole code part is useless.
	It just renders the body message of technical posts (Like, dislike, ...).
	But: The body isn't visible at all. So we do this stuff just because we can.
	Even if these messages were visible, this would only mean that something went wrong.
	During the further steps of the database restructuring I would like to address this issue.

What do you mean with "The body isn't visible at all."?

**Comment by MrPetovan** [comment]
Activity items’ body isn’t displayed anywhere in Friendica.

**Comment by rabuzarus** [comment]
What about "@MrPetovan tagged @annando with #fixed" ?
or "@rabuzarus poked @MrPetovan "?

**Comment by MrPetovan** [comment]
These aren’t activities (like, dislike, attendyes, attendno, attendmaybe).

**Comment by rabuzarus** [comment]
ahh ok. sry

**Comment by AlfredSK** [comment]
I didn't pull this PR yet. But for the record: I cannot communicate even with contacts on my own node. I posted the issue to the helpers forum but the post didn't arrive there.
I checked my logs but couldn't find something obvious.
Mayday! It started some hours after the problem where Michael posted that script in the admins forum.
On my home and network page everything looks okay. But posts, comments, likes are not displayed on the receiving side.
Tobias seems to have the same issue.

**Comment by annando** [comment]
Please pull this PR immediately. Then everything will work again.

**Pull request merged**
