### PR TITLE
Issue 3157: No fulltext anymore

### PR DESCRIPTION
**Pull request by annando**
See issue: https://github.com/friendica/friendica/issues/3157

No one disagreed to keep the old code, so we remove it completely.

### CODE REVIEW

**Comment by Hypolite** [comment]
Remind me why we dropped the fulltext search?

**Comment by annando** [comment]
The code in dbstructure.php never had created these indexes, they only existed on older installations. Additionally it worked only halfway.

**Comment by Hypolite** [comment]
It's too bad, the search currently is a mess, it takes tens of seconds for the most basic searches on my 6-months old single-user instance. 😕

**Comment by annando** [comment]
Problem is that our current database structure doesn't work well with fulltext indexes. We can try again when we changed our database.

**Comment by Hypolite** [comment]
Gotcha, what needs to be changed exactly?

**Comment by annando** [comment]
We have to change the redundant storage of our items. This is a major change. Before we can change that, we need a central item class that handles the whole item storage.

**Comment by Hypolite** [comment]
Ok, thanks for the elaboration.

**Pull request merged**
