### PR TITLE
Move local_user - Part 1

### PR DESCRIPTION
**Pull request by nupplaphil**
Because there are a lot of usages of `local_user()`, this is the first part of the move.
I set the `local_user()` to deprecated and replaced a lot of code.

Additionally, I found some improvements:
- Replaced a lot of `System::baseUrl()` with `$a->getBaseURL()`
- Added `App $a` to the constructor of `Friendica\Object\Post`
- Added `App $a` to the constructor of `Friendica\Object\Thread`

If you like, I can cherry pick the additional improvements to another PR.

### CODE REVIEW

**Comment by nupplaphil** [comment]
btw. my node is now running this branch ;-)

**Comment by annando** [comment]
Yes, I know that there is a reason for that, but why in the world has it got to be such a long function name like ```Session::user()->getUid()```? Possibly this is completely okay from a theoretical point of view - but I really, really, really find it really, really, really hard to type.

Why not something like ```Session::uid()```?

**Comment by nupplaphil** [comment]
Hm .. The overall target is that at https://github.com/friendica/friendica/blob/e8891e9ba4f72d75c2325917d57ffc808cab7e99/src/Core/Authentication.php#L72-L82 we can create something like `Session::createUser($user_record);` which will create a `User()` instance which holds every specific value of a Session-User. 

So we do know which elements a user has. Because it took me a while to find the way back from `$a->user['nickname'] to where it is defined.

I think that the new `Session\User` and `App->user[]` and `$_SESSION['uid']` is a mix of the same purpose created in different ways and used in different ways - which makes it hard to maintain and to use in my believe.

The more I think about it, the more I'm for a `Friendica\Object\User` class which is initialized after the login with the help of the `$user_record` and temporary persisted/reloadable in the `$_SESSION`. The question is where/how we hold this instance... It's not a pure `$_SESSION[]` variable so for me `Session::uid()` would be a semantically wrong place. Because `Session` is a more generic way how we can use `$_SESSION` variables rather than holding specific information about the Session itself...

I'm sorry that it's hard to write @annando :-( .. But I don't know how to combine semantically correctness with easiness to write .. At least we can make something like `SessionUser::uid()`, but that's normally against the purpose of a class .. Because than I would have a `SessionUser::init($user_record)` which is a statically workaround for `new SessionUser($user_record)`.

If we need `Session::user()->getUid()` more than 2-3 times, we could use a variable like
```php
$uid = Session::user()->getUid();
```
so we don't have to write it every time ..

**Comment by nupplaphil** [comment]
So at Authentication, we would make something like:

```php
$user = new Friendica\Object\User($user_record);
Session::set($user);
```

So instead of `$a->user['nickname']` we would have `Session::user()->getNickname()` or `$_SESSION['uid']` would become `'Session::user()->getUid()`. So in fact there is just one access path to informations about the current user ..

**Comment by annando** [comment]
Replacing ```$a->user['nickname'];``` with ```Session::user()->getNickname();``` doesn't make much sense, since that array is just the user array. And this would mean that we had to create around 45 functions to fetch all data from that array.

Concerning this "semantically correctness" I really hope for some solution that is usable as well. Please keep in mind that many developers aren't full time coders or (like me) aren't used to this way of thinking.

**Comment by nupplaphil** [comment]
I'm sorry, it was a little bit late and maybe I was a little bit too dogmatic about this topic..

Let's have a look if an easy solution is possible, otherwise I better don't change it at all :-)

**Comment by nupplaphil** [comment]
It was a little bit too late and I was a little bit too dogmatic. 

My overall target is that we try to make the codebase more comprehensible - especially for developer who don't have a lot of free time .. f.e. what I see behind `Session::user()->getUid()` is `Give me the UID of the user of the current session`. That's what I mean with semantically correctness. `Session::uid()` would be `Give me the UID of the current Session' which is maybe misleading for others to read.

I'll make another try ...

**Comment by MrPetovan** [comment]
Why not directly `Session::user()->uid` or `Session::user()['uid']`?

**Comment by nupplaphil** [comment]
For two reasons
- public fields are hard to manage and breaks the encapsulation (f.e. everybody in the code could do something like `Session::user()->uid = null` or `Session::user()[] = []`).
- It's impossible to mock them (you can just mock methods, f.e. `uid()`) so it avoids clean testing

My new idea would be:
```php
$user = new Friendica\Object\User($user_data); // Holding all business logic about the current user
Session\User::load($user); //Loads the instance to static access class
$uid = Session\User::uid()
```

**Comment by annando** [comment]
Concerning this ```Session\User::get('nickname');``` we should consider that the data is fetched from the database - and we fetch it a several places. So it would be a bad idea to add any functionality or data mocking at that place. Instead we had to make it much more deeper in the database encapsulation.

Concerning the comprehensiveness of the code: This is why we are using the doxygen headers. So - for the sake of improving the simplicity of the code - we can use shorter function name when the documentation is done correctly. (Of course it mustn't be misleading).

BTW: This ```Session\User::uid()``` looks like some compromise.

**Pull request closed without merging**
