### PR TITLE
Ensure query parameters are URL encoded in Arguments

### LINKED ISSUE #9164: Hashtag parameter isn't encoded on search moudule if the user visits the next page
### Actual behavior
if you are searching for a hashtag - lets say 'friendica' - you will get the following url `https://yourserver.com/search?q=%23friendica`. But if you visit the next (second) page of the results the hashtag sign isn't encoded and you will get as url `https://yourserver.com/search?q=#friendica&page=2` and would fail to load the results.

The correct url shoutd be: `https://yourserver.com/search?q=%23friendica&page=2` 

### Steps to reproduce the problem
Search for a hashtag and jump to the next page

### Friendica version you encountered the problem
2020.09-rc

### PHP version
PHP 7.4

### SQL version
MariaDB 10.3

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #9164 and potentially #9165 

I... got carried away.

The result is a housekeeping-heavy PR with many deletion (including a global function in `boot.php`, yay!).

### CODE REVIEW

**Comment by MrPetovan** [comment]
Aaaand we're back to cryptic tests errors:
```
1) Friendica\Test\ApiTest::testApiCallWithUninplementedApi
PHPUnit_Framework_Exception: PHP Fatal error:  Uncaught PDOException: You cannot serialize or unserialize PDO instances in Standard input code:533
Stack trace:
#0 [internal function]: PDO->__sleep()
#1 Standard input code(533): serialize(Array)
#2 Standard input code(1055): __phpunit_run_isolated_test()
#3 {main}
  thrown in Standard input code on line 533

Fatal error: Uncaught PDOException: You cannot serialize or unserialize PDO instances in Standard input code on line 533

PDOException: You cannot serialize or unserialize PDO instances in Standard input code on line 533

Call Stack:
    0.0036    1124064   1. {main}() Standard input code:0
    0.0738   15727672   2. __phpunit_run_isolated_test() Standard input code:1055
    4.8998   26143712   3. serialize() Standard input code:533
    4.8999   26169640   4. Friendica\Test\Util\Database\ExtendedPDO->__sleep() Standard input code:533
```
I feel like we've been through this already @nupplaphil but I can't remember the origin.

Running tests locally doesn't help:
```
PHP Fatal error:  Uncaught PDOException: You cannot serialize or unserialize PDO instances in C:\Windows\Temp\PHPFC25.tmp:267
Stack trace:
#0 [internal function]: PDO->__sleep()
#1 C:\Windows\Temp\PHPFC25.tmp(267): serialize(Array)
#2 C:\Windows\Temp\PHPFC25.tmp(679): __phpunit_run_isolated_test()
#3 {main}
  thrown in C:\Windows\Temp\PHPFC25.tmp on line 267
Fatal error: Uncaught PDOException: You cannot serialize or unserialize PDO instances in C:\Windows\Temp\PHPFC25.tmp:267
Stack trace:
#0 [internal function]: PDO->__sleep()
#1 C:\Windows\Temp\PHPFC25.tmp(267): serialize(Array)
#2 C:\Windows\Temp\PHPFC25.tmp(679): __phpunit_run_isolated_test()
#3 {main}
  thrown in C:\Windows\Temp\PHPFC25.tmp on line 267
```

**Comment by nupplaphil** [comment]
<strike>You've to disable the `@runInSeparateProcess` for the specific test cases and therefore execute each failed test per hand (otherwise the global instance cache can possibly brick the following tests in the same process)

If you remove the annotation, this is the "real" error:
```console
Cannot modify header information - headers already sent by (output started at /vagrant/vendor/phpunit/phpunit/src/Util/Printer.php:110)
 /vagrant/include/api.php:389
 /vagrant/tests/include/ApiTest.php:498
```
</strike>

The "new" error just happens because it isn't running as isolated process anymore .. Forget it ^^

**Comment by nupplaphil** [comment]
@MrPetovan fixed it :-)

You indeed have to remove `@runInSeparateProcess`, but than you also need to temporary remove the called `header()` lines in PHP, because the separate process is therefore necessary to be able to use the header command in tests (because otherwise the `header()` command will end the whole test process, not only the particular test). And after removing the `header()` commands and removing the annotation, I found that for invalid requests, the "default" request changed from empty to "home" ;-)

btw. to make testing more comfortable (so not altering it like I described it), we would need to encapsulate the whole "header()" and "exit()" commands in a specific - non-static - class. This class will than be able to get mocked and instead of calling the commands, it could return the header & html and we can assert both :-)

**Comment by MrPetovan** [comment]
Thank you, but how did you commit to my own Friendica fork? 😲

In any case, the tests weren't wrong, the code was, the Arguments isn't supposed to determine the module. We have a route for empty command so we don't have to pre-select it in Arguments.

**Comment by MrPetovan** [comment]
Fails again 😞

**Comment by nupplaphil** [comment]
> Thank you, but how did you commit to my own Friendica fork? astonished
>
https://code.mendhak.com/update-fork-pull-request/
> When someone submits a pull request to your repository, it is actually possible to update their pull request by pushing commits to their fork.

**Comment by MrPetovan** [comment]
I just saw the "Allow edits by maintainers" checkbox I keep checked.

**Comment by MrPetovan** [comment]
This PR is now ready to merge.

**Comment by nupplaphil** [comment]
oups .. now there's a conflict after the APITest changes.. @MrPetovan one rebase plz :-) After it I'll merge it ;-)

just one last question: because of deprecating `q=`, are there any troubles with the `.htaccess` or nginx proxy configs possible?

**Comment by MrPetovan** [comment]
It is a partial deprecation, we still support it inbound, but we don't generate any links with it anymore. So legacy rewrite configuration will still work.

**Pull request merged**
