### PR TITLE
Move Content-Type check before JSON decode in ActivityPub\Processor::fetchMissingActivity

### LINKED ISSUE #13969: Invalid JSON data (false positive)
- [x ] I have searched open and closed issues for duplicates

### Bug Description

I have a log entry complaining about an invalid JSON data, where the data is no JSON but HTML and the content-type states data is text/html.

It seems as if the content-type is not handled properly.

grafik

This is the activity in the timeline:

grafik

### Platform Info

Friendica Version: 2024.03-rc

Friendica Source: docker image

### PR DESCRIPTION
**Pull request by MrPetovan**
Fix #13969

### CODE REVIEW

**Comment by annando** [comment]
I had chosen that order deliberately to be able to easily check, if a system returns the default JSON content type. Moving this check some lines higher means that the results for this log entry won't be usable any more for this purpose. Also in this order we can see if someone returns valid data but with a wrong content type.

**Comment by MrPetovan** [comment]
I don't think it matters since we stop the process when the content-type is wrong no matter what. It's enough to report to the relevant project, even if they output JSON that we won't use anyway. On the other hand it saves us the JSON decoding of potentially wrong type data input.

**Comment by annando** [comment]
When someone reports that they can't import posts from some exotic system, I would at first ask for this log entry. But when we move this, then this log entry will be so  flooded, that it doesn't help anymore. I would like to have a dedicated log entry for JSON that isn't reported as the correct JSON, since this could give several interesting hints.

**Comment by MrPetovan** [comment]
I don't understand your idea. Here are the different cases:
1. Server sends JSON under an accepted Content-Type
2. Server sends non-JSON under an accepted Content-Type
3. Server sends JSON under a non-accepted Content-Type
4. Server sends non-JSON under a non-accepted Content-Type

Here's the outcome before and after this PR:

| JSON  | Content-Type | Before PR  | After PR |
| ------------- | ------------- | ------------- | ------------- |
| Yes  | Accepted | OK | OK |
| No  | Accepted | PHP Error + "Invalid JSON data" | PHP Error + "Invalid JSON data" |
| Yes  | Rejected | "Unexpected content type" | "Unexpected content type" |
| No  | Rejected | PHP Error + "Invalid JSON data" | **"Unexpected content type"**

This PR only changes the outcome of the last case, it doesn't change anything else, especially not the frequency of log entries.

**Comment by annando** [comment]
Before the change, the "unexpected content type" would only appear when a remote system transmitted some JSON, but did something wrong with the content type. This could indicate either an attack or some bad configured remote system. Normally you wouldn't have got much of these entries in your log. We have got the log message `Unexpected content type` in exactly that writing at three places, so that we can easily scan for this situation.

**Comment by MrPetovan** [comment]
The new order also indicates bad remote system configuration without having to store a full HTML page because of the JSON decode error.

**Comment by annando** [comment]
We call this functionality in the media class as well, when we probe for URL in posts. So it is very expected to have a non JSON payload here. For example yesterday I had more than 5,000 hits there:
```
$ cat friendica.log.1 | grep -a 'Invalid JSON data'.*fetchMissingActivity | wc -l
5505
```
See what is returned by the other message:
```
$ cat friendica.log.1 | grep -a 'Unexpected content type' | wc -l
108
```
This mostly (75 entries) is originated by one service that mirrors Tweets and is using the wrong content type. I wouldn't be able to find these entries amongst the more than 5,000 other hits.

**Comment by MrPetovan** [comment]
Every single line of `Invalid JSON data` stores several kB of irrelevant data in your log (and anyone else's), there has got to be a better way to do this. A HEAD request when probing for example?

On the other hand the `Unexpected content type` error just comes with the original URL and the response content type, so you still would be able to sort through them to pick up outliers even if there were thousands of them.

**Comment by MrPetovan** [comment]
Supersede by https://github.com/friendica/friendica/pull/13975

**Pull request closed without merging**
