### PR TITLE
Expire remote items

### PR DESCRIPTION
**Pull request by annando**
There is now a possibility to expire remote items (means items from other users and/or servers) after a centrally defined time.

In one of the next PRs a frontend could be added, plus some other changes to the existing expiry functionality.

### CODE REVIEW

**Comment by tobiasd** [comment]
It's a global setting which overrules per-account settings about the expiration right?

**Comment by annando** [comment]
Partly. It doesn't override the settings for expiring the own items. This is left untouched. In a future PR I will remove the expiring of remote items from the user settings since this is a pure administrator decision in my eyes.

BTW: External items that are marked or filed are never removed with this functionality.

**Comment by rabuzarus** [comment]
@annando 
Please add `@param integer $stage` for the `function remove_orphans()` doxygen header.
And it would be really helpful to add a description to the doxygen header what the individual stages (1-8) mean/do

**Comment by annando** [comment]
@rabuzarus Done

**Pull request merged**
