### PR TITLE
Forums now are working with AP as well

### PR DESCRIPTION
**Pull request by annando**
It even works (mostly) with comments from Pleroma and Mastodon. And it should be possible with users from these systems to start forum postings as well.

### CODE REVIEW

**Comment by MrPetovan** [comment]
`git.friendi.ca` is unreachable, should I ring Utzer?

**Comment by annando** [comment]
@MrPetovan do so.

**Comment by annando** [comment]
Is it possible to trigger another check?

**Comment by MrPetovan** [comment]
Yes, from Travis, you must sign in with GitHub and there's a button to restart the whole build or individual jobs.

**Pull request merged**
