### PR TITLE
Experimental feature to enter a custom creation date

### LINKED ISSUE #11410: Ability to post in the past
It would be nice to have ability to set post date in the past. 

It is good for migrating people or (for example) "timelines" with pictures of kids.

### PR DESCRIPTION
**Pull request by annando**
Closes #11410

### CODE REVIEW

**Comment by MrPetovan** [comment]
Why didn't you re-use the `scheduled_at` time field? I feel like it's doing the same thing.

**Comment by annando** [comment]
You mean some double use? Like "when the date is prior to now then it is the creation date, otherwise it is the scheduled date"? I hid it intentionally behind some config setting, so that we can experiment with it and can discover all side effects and possible improvements before going into the public with it.

**Comment by MrPetovan** [comment]
Yeah, that's what I meant, and got it about the trial period.

**Comment by annando** [comment]
We should ask the users if this concept sounds confusing or logically.

**Comment by MrPetovan** [comment]
As a user, it makes sense to me that there should be only one date field for the creation date, and if it's in the future, the post should be hidden until the publication date, no matter how it is implemented in the backend.

**Comment by AlfredSK** [comment]
This probably broke the compose page. Frio -> compose button -> middle button click (open in new tab) and introduced a PHP notice.

**Comment by tobiasd** [comment]
Is this feature available via the API @annando ? As parameter for the usual posting creation endpoint or so?

**Comment by annando** [comment]
Not now

**Pull request merged**
