### PR TITLE
Backport NBSP BBCode.  This allows code blocks to look like code blocks and retain their indentation.

### PR DESCRIPTION
**Pull request by beardyunixer**

### CODE REVIEW

**Comment by annando** [comment]
Thanks for the fix. This behaviour always bothered me.

But since it is meant especially for code blocks, wouldn't it be better to do it in a callback function? See here for an example: https://github.com/friendica/friendica/blob/develop/include/bbcode.php#L743

Additionally please check how the system behaves with more than two spaces. I have the feeling that this might not work. Then you could additionally replace ````"&nbsp; "```` with ````"$nbsp;&nbsp:"```` and wrap it in a loop like this one: https://github.com/friendica/friendica/blob/develop/include/bbcode.php#L806-L809

Now something different: Do you know how to work with branches in git? This mostly helps in keeping the commits clean, since you can create a separate branch for every single issue. If you know it, please ignore the following lines, then it is just some documentation for other developers who are new to this stuff.

My regular workflow for coding is like the following:

* ````git checkout develop```` (Making sure that I'm starting in the develop branch)
* ````git fetch upstream; git merge upstream/develop```` (fetch and merge all changes into our own repository)
* ````git checkout -b new-branch-name```` (Create a new branch - for example "nbsp-in-code-block" or "issue-4711")
* coding like always
* After the commits are done, you push it into the repository with ````git push origin new-branch-name````
* If you found out that you started with some stuff that was already fixed, you delete your branch with ````git branch -D new-branch-name````
* If you are working on several issues at a time, you change between them with ````git checkout another-branch-name````
* If you want to see which of your branches were merged you use this command: ````git branch --merged````
* If your branch was accepted, you delete it with ````git branch -d new-branch-name````
* The final step is then to remove your merged branches from here: https://github.com/beardyunixer/friendica/branches

**Comment by beardyunixer** [comment]
I have a problem with Christmas, not branches.  I've messed up merges between branches while being distracted by a houseful.  Historically, nobody really cared much if the commits were messy, so I just left it there.  I'll close this, rebase, and open a new pull request tonight using a callback instead.

**Comment by annando** [comment]
You needn't to close this pull request. You are right that no one cares about commits. My hint was just to improve your future workflow (this workflow had helped me very much)

**Comment by Quix0r** [comment]
Remote delete of branch is also possible: `git push origin :some-branch` (no space after : !)

**Pull request closed without merging**
