### PR TITLE
Frio with treadview

### PR DESCRIPTION
**Pull request by xundeenergie**
I created a few modifications, based on the light colorscheme for frio (including the accenture-color-chooser), which shows Lines on the left of threaded conversations.

in violett
grafik

and blue
grafik

And it also works for mobile clients:
grafik

You see, the thread-lines are corresponding with the accenture-color of the theme.

### CODE REVIEW

**Review by tobiasd — CHANGES_REQUESTED** [review]
This PR has to go into the develop branch, not into the stable one. Could you please change the target.

**Comment by xundeenergie** [comment]
I hope, the change to develop worked.

**Comment by xundeenergie** [comment]
The relevant changes are only

- view/theme/frio/scheme/threadview.php
- view/theme/frio/scheme/threadview.css

**Comment by tobiasd** [comment]
You need to rebase your changes on the develop branch - sorry for me forgetting to mention this.

**Comment by MrPetovan** [comment]
This is good work, but I'm not convinced it should be added to Friendica Core. We've worked to reduce the spread of the schemes for frio down to generic ones.

Beyond that, I'm not personally convinced these lines increase the thread hierarchy legibility. It still is a nice CSS exercise.

**Comment by loma-one** [comment]
Personally, I find this suggestion very interesting. In discussions with multiple threads, it is sometimes very difficult to find the origin. A visual aid can be a good help here.
The visual aid should only be in the threads, not on the original post.

**Comment by MrPetovan** [comment]
I don't mind a visual aid, I just don't think this is the one.

**Comment by xundeenergie** [comment]
in pleroma they did a very good work for orientation.

Here is "Antwort auf" a link to the comment, where this one is the answer.
grafik

if you hover over "Antwort auf" you can see this:
grafik

And something like such a link in friendica-postings, is what i additionally want for better orientation in threads.

**Comment by MrPetovan** [comment]
I feel like this can work for size-limited posts, but Friendica allows long posts and replies, which makes this particular visual indicator awkward for us.

**Comment by xundeenergie** [comment]
ok... just show the first 3, 4 lines should be ok.

maybe only the link alone could be a proper idea.

**Comment by xundeenergie** [comment]
Thats very sad... i use this modification (it's not more than a colorscheme) of frio since many days.
And it is really disannoying... every conversation is more understandable, who answered whom... 

But... if you can find it in git.friendi.ca.

I will make a pullrequest to community-Themes.

**Pull request closed without merging**
