### PR TITLE
Remove unused, unneeded or redundant item fields

### PR DESCRIPTION
**Pull request by annando**
This PR is one in a longer list. In the process of splitting the item table, there is some stuff that should be removed because we don't need it there.

This is some work in progress that could last some days and will possibly touch many files. To prevent conflicts, I will create a PR from time to time.

### CODE REVIEW

**Comment by MrPetovan** [comment]
This looks good. Not for my uptime, but it isn't important. Just tell me when you're done with this PR.

**Comment by annando** [comment]
The test tool is confusing me. I would like to make it smile ... I did just a last test. After this I'm done.

**Comment by MrPetovan** [comment]
You have to fix those first:
```
There were 3 errors:
1) Friendica\Test\ApiTest::testApiStatusShow
TypeError: Argument 1 passed to Friendica\Test\ApiTest::assertStatus() must be of the type array, null given, called in /home/travis/build/friendica/friendica/tests/ApiTest.php on line 1239
/home/travis/build/friendica/friendica/tests/ApiTest.php:105
/home/travis/build/friendica/friendica/tests/ApiTest.php:1239

2) Friendica\Test\ApiTest::testApiStatusShowWithXml
PHPUnit_Framework_Exception: Argument #2 (No Value) of PHPUnit_Framework_Assert::assertStringStartsWith() must be a string
/home/travis/build/friendica/friendica/tests/ApiTest.php:134
/home/travis/build/friendica/friendica/tests/ApiTest.php:1249

3) Friendica\Test\ApiTest::testApiStatusShowWithRaw
TypeError: Argument 1 passed to Friendica\Test\ApiTest::assertStatus() must be of the type array, null given, called in /home/travis/build/friendica/friendica/tests/ApiTest.php on line 1258
/home/travis/build/friendica/friendica/tests/ApiTest.php:105
/home/travis/build/friendica/friendica/tests/ApiTest.php:1258
```

**Comment by annando** [comment]
Since I never worked with test tools in my life, I'm currently in blind flight ;-) I have a feeling why the tool is complaining. In some minutes we will know more.

**Comment by annando** [comment]
I'm giving up on the test tool.

**Comment by MrPetovan** [comment]
Calling @rudloff to the rescue.

**Comment by annando** [comment]
Really final state: Someone else has to fix the dataset of the test tool. The contact entries are wrong. Every contact needs a public contact with "uid=0". The adding of the "pid" in the userinfo created this problem. This is not a bug in the API, but the test tool.

**Comment by Rudloff** [comment]
I'll be honest, I'm not sure I understand how all the user fields work (espcially the various IDs).
If someone contributes a more complete and realistic dataset, I can help adapt the tests afterward.

As for the current PR, this seems to fix the tests:
```diff
diff --git a/tests/datasets/api.yml b/tests/datasets/api.yml
index ae1fd3242..9cacab714 100644
--- a/tests/datasets/api.yml
+++ b/tests/datasets/api.yml
@@ -65,7 +65,7 @@ item:
         visible: true
         contact-id: 42
         author-id: 42
-        owner-id: 42
+        owner-id: 45
         uid: 42
         verb: http://activitystrea.ms/schema/1.0/post
         unseen: true
@@ -83,7 +83,7 @@ item:
         visible: true
         contact-id: 42
         author-id: 42
-        owner-id: 42
+        owner-id: 45
         uid: 42
         verb: http://activitystrea.ms/schema/1.0/post
         unseen: false
```

(I'm not sure why though, a contact with ID 45 and UID 0 is not in the dataset, but is created automatically somehow?)

**Comment by annando** [comment]
The contacts with the uid=0 are created automatically for each unique value of "nurl". They are the so called "public contacts". The "owner-id" and "author-id" refer to these fields. They replace the three fields "author-link", "author-name" and "author-avatar" with just an id field.

**Comment by annando** [comment]
Yeah, it worked!

BTW: Thanks for the tests, since they helped, finding bugs I made in this PR.

**Comment by Rudloff** [comment]
> BTW: Thanks for the tests, since they helped, finding bugs I made in this PR.

That's great, I was afraid they were only making things more complicated for you.

**Comment by annando** [comment]
Of course they made things more complicated, but they also solved a problem we possibly hadn't found spontaneously. And as long as we can rely on you for fixing stuff like this, everything is fine.

**Pull request merged**
