### PR TITLE
Update.md: be more precise about items to copy

### PR DESCRIPTION
**Pull request by guzzisti**
This PR is related to this discussion: https://friendica.vrije-mens.org/display/6c36e370-705e-832a-6edf-39b894098049

I've updated the instructions to mention all folders that eventually need to be copied to the new friendica directory.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Thank you for your work!

**Comment by annando** [comment]
Why is the "photo" folder omitted from the description?

**Comment by guzzisti** [comment]
There is no `photo` folder on my newly created instance and i can't find another setting where this could come from but maybe i missed something.

**Comment by MrPetovan** [comment]
I couldn't find any mention to `/photo` in the code except in the cronjobs to clear the image cache.

**Pull request merged**
