### PR TITLE
Issue 2772: Pending contacts should now be displayed

### PR DESCRIPTION
**Pull request by annando**
See issue https://github.com/friendica/friendica/issues/2772

### CODE REVIEW

**Comment by rabuzarus** [comment]
like I said in the former PR: I don't understand why we should have pending contacts displayed in the contact block (identity.php and text.php). It is a connection request but no real accepted contact.

The issue with the pending contact was that their comments wasn't available anymore (in comments of public forums and the comments of posts from people with whom we are already connected)

**Comment by annando** [comment]
Yeah, I guess you are right. I just did some copy and paste (without thinking) for this pull request while watching a documentation on TV ;-)

**Comment by rabuzarus** [comment]
:-)

**Comment by annando** [comment]
Done.

**Comment by rabuzarus** [comment]
Sry @annando I have some more questions. But it's better to ask now.

You know I'm not very familiar with the protocol stuff. So maybe I'm totally wrong. But should we generate a atom feed (in `public static function feed()`) for pending contacts? What would it change? Can this introduce privacy issues?

In the api you changed code e.g. in `function api_get_user()` I don't use the api so I don't have any knowledge of the intended behavior. But the variable for the query is `$countfriends` but a pending contact isn't a friend at this time. At this place it doesn't matter because this code part is commented out. But it will maybe the input of a rewrite to enable this code part again.

But what I wan't to say is. Since I'm not that familiar with some of the code parts can you please double check (if it does make sense at this point and if we won't leak unnecessary or false infos) if we need to include the pending contacts in all of the changed queries .

If you give me your OK after checking I will merge it

**Comment by annando** [comment]
Concerning the counting of contacts in the API, I guess you are right.

Concerning the feed: Like on the network page otherwise the feed would miss entries. But the first check wasn't necessary.

**Comment by rabuzarus** [comment]
According to https://github.com/friendica/friendica/pull/2748/commits/c1555b623a2993c65a3dfde1a5f8294fb919bf99 woudln't it make more sense to rather have `not pending` in `function best_link_url()` than `not blocked`?

My thoughts about this:
If block a user (a user whicht whom I connected to) it does mean that I don't want to have his/her posts in my stream. But it doesn't mean that I don't want to authenticate with `/redir` on his/her instance

**Comment by annando** [comment]
My thoughts were that if we block someone we want to cut the connection in some way. This would include cutting the remote authentication. But to avoid long discussions I will change it back.

**Comment by rabuzarus** [comment]
I also don't want to discuss very long about this (I don't block any people). Just to explain my thoughts: If a user really wants to cut the connection that much he/she should rather delete the contact (it would be the same)

**Comment by tobiasd** [comment]
Are the docs about blocking synced with the behavior?

**Comment by annando** [comment]
Are there docs?

**Comment by tobiasd** [comment]
yes, you might want to read pirati.ca/help

**Pull request merged**
