### PR TITLE
NPF functionality added

### LINKED ISSUE #11551: Tumblr crossposting is broken?
Starting late April, Tumblr connector seems to have broken for my account. Tested on loma.ml, been debugging that with the local admin without too much effect gained. Seems it's only limited to my account but for that one, it's apparently unfixable? No weird insights in the log files, posts just don't seem to go through. Already did reset the full Tumblr addon configuration (including the app registration on Tumblrs side) without things getting noticeably better. Any way to debug that?

(Finding all along the way: Tried to add a new Tumblr blog to my account there to check whether it's something specific to my _blog_, I noticed that, though, by then I can choose the newly added blog from the drop-down in Friendica connector configuration dialog but this will never be remembered - as soon as I reload the settings page after saving that, it's always set back to the "main" blog.)

### PR DESCRIPTION
**Pull request by annando**
Tumblr is using NPF ("[Neue Post Format](https://www.tumblr.com/docs/npf)") for their posts. We now support it. This PR is needed for PR https://git.friendi.ca/friendica/friendica-addons/pulls/1364 which fixes https://github.com/friendica/friendica/issues/11551

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by loma-one** [comment]
**Instance 1** PHP 7.4, SQL 10.4: White page after (re-)authentication. Instance can no longer be called up (white page). Addon marked as *bak. Instance accessible again.

```
[Fri Apr 07 10:25:07.608372 2023] [proxy_fcgi:error] [pid 13473:tid 140108879623936] [client 2003:e5:1743:bd00:9b68:5902:f7dd:9731:56540] AH01071: Got error 'PHP message: PHP Notice:  Trying to get property 'user' of non-object in /var/www/html/friendica/addon/tumblr/tumblr.php on line 222PHP message: PHP Notice:  Trying to get property 'blogs' of non-object in /var/www/html/friendica/addon/tumblr/tumblr.php on line 222PHP message: PHP Warning:  array_map(): Expected parameter 2 to be an array, null given in /var/www/html/friendica/addon/tumblr/tumblr.php on line 222', referer: https://loma.ml/settings
```

```
[Fri Apr 07 10:25:12.680824 2023] [proxy_fcgi:error] [pid 14571:tid 140107503875840] [client 2003:e5:1743:bd00:9b68:5902:f7dd:9731:37610] AH01071: Got error 'PHP message: PHP Notice:  session_start(): A session had already been started - ignoring in /var/www/html/friendica/addon/tumblr/tumblr.php on line 91PHP message: PHP Notice:  Undefined index: oauth_token in /var/www/html/friendica/addon/tumblr/library/tumblroauth.php on line 106PHP message: PHP Notice:  Undefined index: oauth_token_secret in /var/www/html/friendica/addon/tumblr/library/tumblroauth.php on line 106PHP message: PHP Notice:  Undefined index: oauth_token in /var/www/html/friendica/addon/tumblr/tumblr.php on line 112PHP message: PHP Notice:  Undefined index: oauth_token_secret in /var/www/html/friendica/addon/tumblr/tumblr.php on line 113', referer: https://loma.ml/settings/connectors
```

```
[Fri Apr 07 10:38:59.501224 2023] [proxy_fcgi:error] [pid 23445:tid 140108955219712] [client 2a01:4f9:4a:3793:0:10:0:e16a:45860] AH01071: Got error 'PHP message: PHP Warning:  include(/var/www/html/friendica/addon/advancedcontentfilter/vendor/composer/../nikic/fast-route/src/Route.php): failed to open stream: No such file or directory in /var/www/html/friendica/vendor/composer/ClassLoader.php on line 444PHP message: PHP Warning:  include(): Failed opening '/var/www/html/friendica/addon/advancedcontentfilter/vendor/composer/../nikic/fast-route/src/Route.php' for inclusion (include_path='.:/usr/share/php:/var/www/html/friendica/include:/var/www/html/friendica/library:/var/www/html/friendica') in /var/www/html/friendica/vendor/composer/ClassLoader.php on line 444'
```

```
[Fri Apr 07 11:05:03.037216 2023] [proxy_fcgi:error] [pid 4436:tid 140107436766976] [client 2003:e5:1743:bd00:9b68:5902:f7dd:9731:56340] AH01071: Got error 'PHP message: PHP Notice:  Undefined index: connector in /var/www/html/friendica/src/Module/Settings/Connectors.php on line 153PHP message: PHP Notice:  Undefined index: connector in /var/www/html/friendica/src/Module/Settings/Connectors.php on line 154PHP message: PHP Notice:  Undefined index: title in /var/www/html/friendica/src/Module/Settings/Connectors.php on line 155PHP message: PHP Notice:  Undefined index: connector in /var/www/html/friendica/src/Module/Settings/Connectors.php on line 158', referer: https://loma.ml/settings
```

---

**Instance 2** PHP 8.0, SQL 10.4: (Re-)Authentication successful but no posts are sent to Trumblr.

```
[Fri Apr 07 12:27:45.524954 2023] [proxy_fcgi:error] [pid 23135:tid 139918743426816] [client 2003:e5:1743:bd00:9b68:5902:f7dd:9731:38902] AH01071: Got error 'PHP message: PHP Notice:  session_start(): Ignoring session_start() because a session is already active in /var/www/html/friend/addon/tumblr/tumblr.php on line 97PHP message: PHP Warning:  Undefined variable $o in /var/www/html/friend/addon/tumblr/tumblr.php on line 143', referer: https://dis-le.de/
```

```
[Fri Apr 07 12:30:16.861939 2023] [proxy_fcgi:error] [pid 27225:tid 139919825561344] [client 2003:e5:1743:bd00:9b68:5902:f7dd:9731:50616] AH01071: Got error 'PHP message: PHP Notice:  session_start(): Ignoring session_start() because a session is already active in /var/www/html/friend/addon/tumblr/tumblr.php on line 149', referer: https://www.tumblr.com/
```

**Comment by annando** [comment]
Please set the log level to "info", create a post and have a look for entries with `tumblr.php` in it. The one from the second instance are not a problem. The error from the first instance appears to me as if the addon isn't updated, since there is no `array_map` in the new addon anymore.

**Comment by loma-one** [comment]
**Instanz 1: Log**

```
2023-04-08T05:20:35Z worker [NOTICE]: Missing data, connection is not established {"uid":1,"page":"","worker_id":"2af73fb","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":475,"function":"tumblr_connection","request-id":"6430f9a329367","uid":"8d47cd","process_id":30223}
2023-04-08T05:20:35Z worker [NOTICE]: Missing data, post will not be send to Tumblr. {"uid":1,"page":"","id":7137606,"worker_id":"2af73fb","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":434,"function":"tumblr_send_npf","request-id":"6430f9a329367","uid":"8d47cd","process_id":30223}
```
image

---

**Instanz 2**
Immediately after activating the addon, I only get a white page. No difference whether I download the addon fresh from the repro or use the updated files. 

image

---

**Instanz: Opensocial.at**
withdrawing the API authorisation for opensocial.at means that the page https://opensocial.at/settings/connectors can no longer be accessed.

---

**Instanz: libranet**
Post will not be sent to tumblr.

**Comment by annando** [comment]
The `"page":""` is the important part. Can you select the page again and have a look at the logs?

For the WSOD: Do you see anything in the logs?

**Comment by loma-one** [comment]
**Instanz 1 Log** No further references with `"page":""`

```2023-04-08T05:20:35Z worker [NOTICE]: Missing data, connection is not established {"uid":1,"page":"","worker_id":"2af73fb","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":475,"function":"tumblr_connection","request-id":"6430f9a329367","uid":"8d47cd","process_id":30223}
2023-04-08T05:20:35Z worker [NOTICE]: Missing data, post will not be send to Tumblr. {"uid":1,"page":"","id":7137606,"worker_id":"2af73fb","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":434,"function":"tumblr_send_npf","request-id":"6430f9a329367","uid":"8d47cd","process_id":30223}
```

---

**Instanz 2:**
WSOD: The logs don't give me a clue. 

Is there a way to specifically reset an addon? I suspect a similar situation to opensocial.at. 
Here, too, I have removed the API authorisation on tumblr.

**Comment by annando** [comment]
There should be an entry with `[ERROR]` in the log. It's preferable that we find the solution without manipulating data, since others could experience the same.

**Comment by annando** [comment]
Pull request is done: https://git.friendi.ca/friendica/friendica-addons/pulls/1366

**Comment by loma-one** [comment]
Instanz 2: WSOD
No ERROR message pointing to tumblr as the source of the problem.

**Comment by loma-one** [comment]
I had activated and connected Tumblr on another instance. This instance is only a few days old. But I suspect that this does not help any further

```
2023-04-08T12:18:43Z worker [ERROR]: Uncaught exception in worker execution {"class":"GuzzleHttp\\Exception\\InvalidArgumentException","message":"json_encode error: Malformed UTF-8 characters, possibly incorrectly encoded","code":0,"file":"/var/www/html/friend/vendor/guzzlehttp/guzzle/src/functions.php:328","trace":"#0 /var/www/html/friend/vendor/guzzlehttp/guzzle/src/Client.php(397): GuzzleHttp\\json_encode()\n#1 /var/www/html/friend/vendor/guzzlehttp/guzzle/src/Client.php(346): GuzzleHttp\\Client->applyOptions()\n#2 /var/www/html/friend/vendor/guzzlehttp/guzzle/src/Client.php(162): GuzzleHttp\\Client->transfer()\n#3 /var/www/html/friend/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\\Client->requestAsync()\n#4 /var/www/html/friend/vendor/guzzlehttp/guzzle/src/Client.php(95): GuzzleHttp\\Client->request()\n#5 /var/www/html/friend/addon/tumblr/tumblr.php(517): GuzzleHttp\\Client->__call()\n#6 /var/www/html/friend/addon/tumblr/tumblr.php(417): tumblr_post()\n#7 /var/www/html/friend/src/Core/Hook.php(222): tumblr_send()\n#8 /var/www/html/friend/src/Worker/ForkHook.php(31): Friendica\\Core\\Hook::callSingle()\n#9 [internal function]: Friendica\\Worker\\ForkHook::execute()\n#10 /var/www/html/friend/src/Core/Worker.php(572): call_user_func_array()\n#11 /var/www/html/friend/src/Core/Worker.php(386): Friendica\\Core\\Worker::execFunction()\n#12 /var/www/html/friend/src/Core/Worker.php(121): Friendica\\Core\\Worker::execute()\n#13 /var/www/html/friend/bin/worker.php(83): Friendica\\Core\\Worker::processQueue()\n#14 {main}","previous":null,"worker_id":"99a3412","worker_cmd":"ForkHook"} - {"file":"Worker.php","line":577,"function":"execFunction","request-id":"64315ba2e85bf","uid":"c29642","process_id":1535637}
```

After recording the Pull request https://git.friendi.ca/friendica/friendica-addons/pulls/1366

```
2023-04-08T17:22:20Z worker [NOTICE]: Post failed {"code":404,"message":"Client error: `POST https://api.tumblr.com/v2/blog/www.tumblr.com/posts` resulted in a `404 Not Found` response:\n{\"meta\":{\"status\":404,\"msg\":\"Not Found\"},\"response\":[],\"errors\":[{\"title\":\"Not Found\",\"code\":0,\"detail\":\"Something flubb (truncated...)\n","worker_id":"5eaa79e","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":531,"function":"tumblr_post","request-id":"6431a2cbd10e7","uid":"33626e","process_id":1549611}
2023-04-08T17:22:20Z worker [NOTICE]: error {"blog":"www.tumblr.com","params":{"content":[{"type":"text","text":"Test Tumblr"}],"state":"published","date":"2023-04-08T17:22:17Z","tags":"","is_private":false,"interactability_reblog":"everyone"},"result":{"meta":{"status":404,"msg":"Not Found"},"response":[],"errors":[{"title":"Not Found","code":0,"detail":"Something flubbed. Try again."}]},"worker_id":"5eaa79e","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":467,"function":"tumblr_send_npf","request-id":"6431a2cbd10e7","uid":"33626e","process_id":1549611}
```

```
2023-04-08T17:22:20Z worker [NOTICE]: Post failed {"code":404,"message":"Client error: `POST https://api.tumblr.com/v2/blog/www.tumblr.com/post` resulted in a `404 Not Found` response:\n{\"meta\":{\"status\":404,\"msg\":\"Not Found\"},\"response\":[],\"errors\":[{\"title\":\"Not Found\",\"code\":0,\"detail\":\"Tumblr went thu (truncated...)\n","worker_id":"5eaa79e","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":531,"function":"tumblr_post","request-id":"6431a2cbd10e7","uid":"33626e","process_id":1549611}
2023-04-08T17:22:20Z worker [NOTICE]: error {"blog":"www.tumblr.com","params":{"state":"published","tags":"","tweet":"off","format":"html","type":"text","title":"","body":"Test Tumblr"},"result":{"meta":{"status":404,"msg":"Not Found"},"response":[],"errors":[{"title":"Not Found","code":0,"detail":"Tumblr went thud. Try again."}]},"worker_id":"5eaa79e","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":431,"function":"tumblr_send","request-id":"6431a2cbd10e7","uid":"33626e","process_id":1549611}
```

**Comment by annando** [comment]
Please save the user settings again. There had been a bug with the selected blog.

**Comment by annando** [comment]
After PR https://git.friendi.ca/friendica/friendica-addons/pulls/1367 is integrated in the system, please save user settings once more. We now are using the UUID field to address the blog.

Are there any more issues?

**Comment by loma-one** [comment]
**Instanz 1: Log**
Pull > Addon updated > addon deactivated / activated > Reauthentication of the tumblr connection

```
2023-04-09T05:51:58Z index [NOTICE]: E_NOTICE: session_start(): Ignoring session_start() because a session is already active {"code":8,"message":"session_start(): Ignoring session_start() because a session is already active","file":"/var/www/html/friend/addon/tumblr/tumblr.php","line":98} - {"file":null,"line":null,"function":"session_start","request-id":"6432527e9d6e9","uid":"9bbaf4","process_id":20622}
```

```
2023-04-09T05:52:05Z index [NOTICE]: E_NOTICE: session_start(): Ignoring session_start() because a session is already active {"code":8,"message":"session_start(): Ignoring session_start() because a session is already active","file":"/var/www/html/friend/addon/tumblr/tumblr.php","line":150} - {"file":null,"line":null,"function":"session_start","request-id":"6432528596366","uid":"c79105","process_id":11154}
```

Sent message does not arrive at tumblr.

Connected to **another** tumblr account
addon deactivated / activated > Reauthentication of the tumblr connection (another account).
Connection with other accounts is confirmed

```
2023-04-09T06:10:02Z worker [NOTICE]: Post failed {"code":404,"message":"Client error: `POST https://api.tumblr.com/v2/blog/www.tumblr.com/blog/view/lomaml/posts` resulted in a `404 Not Found` response:\n{\"meta\":{\"status\":404,\"msg\":\"Not Found\"},\"response\":[],\"errors\":[{\"title\":\"Not Found\",\"code\":0,\"detail\":\"Hit a glitch. T (truncated...)\n","worker_id":"5d2b46e","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":528,"function":"tumblr_post","request-id":"643256b703f6f","uid":"3995ba","process_id":2038}
2023-04-09T06:10:02Z worker [NOTICE]: error {"blog":"www.tumblr.com/blog/view/lomaml","params":{"content":[{"type":"text","text":"Test Tumblr"}],"state":"published","date":"2023-04-09T06:09:58Z","tags":"","is_private":false,"interactability_reblog":"everyone"},"result":{"meta":{"status":404,"msg":"Not Found"},"response":[],"errors":[{"title":"Not Found","code":0,"detail":"Hit a glitch. Try again."}]},"worker_id":"5d2b46e","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":464,"function":"tumblr_send_npf","request-id":"643256b703f6f","uid":"3995ba","process_id":2038}
```

```
2023-04-09T06:10:02Z worker [NOTICE]: Post failed {"code":404,"message":"Client error: `POST https://api.tumblr.com/v2/blog/www.tumblr.com/blog/view/lomaml/post` resulted in a `404 Not Found` response:\n{\"meta\":{\"status\":404,\"msg\":\"Not Found\"},\"response\":[],\"errors\":[{\"title\":\"Not Found\",\"code\":0,\"detail\":\"Unknown error.  (truncated...)\n","worker_id":"5d2b46e","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":528,"function":"tumblr_post","request-id":"643256b703f6f","uid":"3995ba","process_id":2038}
2023-04-09T06:10:02Z worker [NOTICE]: error {"blog":"www.tumblr.com/blog/view/lomaml","params":{"state":"published","tags":"","tweet":"off","format":"html","type":"text","title":"","body":"Test Tumblr"},"result":{"meta":{"status":404,"msg":"Not Found"},"response":[],"errors":[{"title":"Not Found","code":0,"detail":"Unknown error. Try again."}]},"worker_id":"5d2b46e","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line"
```

---

**Instanz 2**
The addon still cannot be activated (WSOD)

**Comment by annando** [comment]
Concerning the first one: Please update the user settings by saving it as a user. Then the value in the "blog" will be some UUID.

For the second one I'm clueless when there isn't any `[ERROR]` message in the log. At which exact point in the process the WSOD appears?

**Comment by loma-one** [comment]
**Instanz 1**

```
2023-04-10T07:36:45Z worker [NOTICE]: Post failed {"code":404,"message":"Client error: `POST https://api.tumblr.com/v2/blog/www.tumblr.com/blog/view/lomaml/posts` resulted in a `404 Not Found` response:\n{\"meta\":{\"status\":404,\"msg\":\"Not Found\"},\"response\":[],\"errors\":[{\"title\":\"Not Found\",\"code\":0,\"detail\":\"Got an error. T (truncated...)\n","worker_id":"b2b584f","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":528,"function":"tumblr_post","request-id":"6433bc8cc6691","uid":"467a7a","process_id":8031}
```

```
2023-04-10T07:36:45Z worker [NOTICE]: error {"blog":"www.tumblr.com/blog/view/lomaml","params":{"content":[{"type":"text","text":"Test tumblr"},{"type":"image","media":[{"type":"image/jpeg","url":"https://dis-le.de/photo/761776711564204d7fd2e1b362751160-0.jpg","width":1080,"height":1080},{"type":"image/jpeg","url":"https://dis-le.de/photo/761776711564204d7fd2e1b362751160-1.jpg","width":640,"height":640},{"type":"image/jpeg","url":"https://dis-le.de/photo/761776711564204d7fd2e1b362751160-2.jpg","width":320,"height":320}]}],"state":"published","date":"2023-04-10T07:18:27Z","tags":"","is_private":false,"interactability_reblog":"everyone"},"result":{"meta":{"status":404,"msg":"Not Found"},"response":[],"errors":[{"title":"Not Found","code":0,"detail":"Got an error. Try again."}]},"worker_id":"b2b584f","worker_cmd":"ForkHook"} - {"file":"tumblr.php","line":464,"function":"tumblr_send_npf","request-id":"6433bc8cc6691","uid":"467a7a","process_id":8031}
```

```
2023-04-10T07:36:45Z worker [ERROR]: Uncaught exception in worker execution {"class":"GuzzleHttp\\Exception\\InvalidArgumentException","message":"json_encode error: Malformed UTF-8 characters, possibly incorrectly encoded","code":0,"file":"/var/www/html/friend/vendor/guzzlehttp/guzzle/src/functions.php:328","trace":"#0 /var/www/html/friend/vendor/guzzlehttp/guzzle/src/Client.php(397): GuzzleHttp\\json_encode()\n#1 /var/www/html/friend/vendor/guzzlehttp/guzzle/src/Client.php(346): GuzzleHttp\\Client->applyOptions()\n#2 /var/www/html/friend/vendor/guzzlehttp/guzzle/src/Client.php(162): GuzzleHttp\\Client->transfer()\n#3 /var/www/html/friend/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\\Client->requestAsync()\n#4 /var/www/html/friend/vendor/guzzlehttp/guzzle/src/Client.php(95): GuzzleHttp\\Client->request()\n#5 /var/www/html/friend/addon/tumblr/tumblr.php(522): GuzzleHttp\\Client->__call()\n#6 /var/www/html/friend/addon/tumblr/tumblr.php(422): tumblr_post()\n#7 /var/www/html/friend/src/Core/Hook.php(222): tumblr_send()\n#8 /var/www/html/friend/src/Worker/ForkHook.php(31): Friendica\\Core\\Hook::callSingle()\n#9 [internal function]: Friendica\\Worker\\ForkHook::execute()\n#10 /var/www/html/friend/src/Core/Worker.php(572): call_user_func_array()\n#11 /var/www/html/friend/src/Core/Worker.php(386): Friendica\\Core\\Worker::execFunction()\n#12 /var/www/html/friend/src/Core/Worker.php(121): Friendica\\Core\\Worker::execute()\n#13 /var/www/html/friend/bin/worker.php(83): Friendica\\Core\\Worker::processQueue()\n#14 {main}","previous":null,"worker_id":"b2b584f","worker_cmd":"ForkHook"} - {"file":"Worker.php","line":577,"function":"execFunction","request-id":"6433bc8cc6691","uid":"467a7a","process_id":8031}
```

---

On another instance under my control, a post to tumblr succeeded. 
This instance uses the same pull stand and the same API OAuth Consumer Key & Secret as instance 1.
```
2023-04-10T07:12:27Z index [INFO]: Start Update {"fields":{"rendered-html":"Test tumblr","rendered-hash":"cf50490c3a1dee7a392eff73112c7712"},"condition":{"id":81480},"uid":2,"callstack":"Item::insert (200), item_insert (79), item_post (83), Compose::post (228), BaseModule::run (700), App::runFrontend (52)"} - {"file":"Post.php","line":523,"function":"update","request-id":"6433b6dbc2e54","uid":"3fe0ce","process_id":1649055}
```

---


**Instanz 2**

```
2023-04-10T07:20:27Z index [CRITICAL]: Uncaught Exception ParseError: "syntax error, unexpected '|', expecting '{'" at /var/www/html/friendica/addon/tumblr/tumblr.php line 469 {"exception":"ParseError: syntax error, unexpected '|', expecting '{' in /var/www/html/friendica/addon/tumblr/tumblr.php:469\nStack trace:\n#0 /var/www/html/friendica/src/Module/Admin/Addons/Index.php(50): Friendica\\Core\\Addon::install()\n#1 /var/www/html/friendica/src/BaseModule.php(244): Friendica\\Module\\Admin\\Addons\\Index->content()\n#2 /var/www/html/friendica/src/App.php(700): Friendica\\BaseModule->run()\n#3 /var/www/html/friendica/index.php(52): Friendica\\App->runFrontend()\n#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"6433b8bbc752a","uid":"f4d66f","process_id":4754}```

**Comment by annando** [comment]
The pull request https://git.friendi.ca/friendica/friendica-addons/pulls/1369 will automatically correct wrong page settings. On your first example the blog name `www.tumblr.com/blog/view/lomami` isn't correct. This should be fixed, when the user updates their Tumblr connector settings. But with the new PR this will be done automatically.

The second issue really looks like there is something wrong on that system. This `ParseError: syntax error, unexpected '|', expecting '{' ` is a typical error when there is something wrong in the syntax. This file seems to be changed.

**Comment by loma-one** [comment]
**Instanz 1**
I got the addon from your repro. The following message

```
2023-04-10T10:55:22Z index [NOTICE]: E_NOTICE: session_start(): Ignoring session_start() because a session is already active {"code":8,"message":"session_start(): Ignoring session_start() because a session is already active","file":"/var/www/html/friend/addon/tumblr/tumblr.php","line":143} - {"file":null,"line":null,"function":"session_start","request-id":"6433eb1ab8aa0","uid":"5a7746","process_id":427}
```

```
2023-04-10T10:55:22Z index [WARNING]: E_WARNING: Undefined array key "request_token" {"code":2,"message":"Undefined array key \"request_token\"","file":"/var/www/html/friend/addon/tumblr/tumblr.php","line":157} - {"file":"tumblr.php","line":157,"function":"tumblr_callback","request-id":"6433eb1ab8aa0","uid":"5a7746","process_id":427}
```

```
2023-04-10T10:55:22Z index [WARNING]: E_WARNING: Undefined array key "request_token_secret" {"code":2,"message":"Undefined array key \"request_token_secret\"","file":"/var/www/html/friend/addon/tumblr/tumblr.php","line":157} - {"file":"tumblr.php","line":157,"function":"tumblr_callback","request-id":"6433eb1ab8aa0","uid":"5a7746","process_id":427}
```

```
2023-04-10T10:55:22Z index [WARNING]: E_WARNING: Undefined array key "oauth_token" {"code":2,"message":"Undefined array key \"oauth_token\"","file":"/var/www/html/friend/addon/tumblr/library/tumblroauth.php","line":149} - {"file":"tumblroauth.php","line":149,"function":"getAccessToken","request-id":"6433eb1ab8aa0","uid":"5a7746","process_id":427}
```

```
2023-04-10T10:55:22Z index [WARNING]: E_WARNING: Undefined array key "oauth_token_secret" {"code":2,"message":"Undefined array key \"oauth_token_secret\"","file":"/var/www/html/friend/addon/tumblr/library/tumblroauth.php","line":149} - {"file":"tumblroauth.php","line":149,"function":"getAccessToken","request-id":"6433eb1ab8aa0","uid":"5a7746","process_id":427}
```

**Instanz 2**

With the change to the RC, I had gotten the data fresh from the repro. Does it make sense to repeat this again or does the error lie deeper in the system?

**Comment by annando** [comment]
The code of the first instance can't be the current one. The log says
> Undefined array key \"request_token\"","file":"/var/www/html/friend/addon/tumblr/tumblr.php","line":157

But line 157 look this way:

https://git.friendi.ca/friendica/friendica-addons/src/branch/2023.03-rc/tumblr/tumblr.php#L157

And concerning the log messages concerning tumblroauth.php: The file only has got 108 lines: https://git.friendi.ca/friendica/friendica-addons/src/branch/2023.03-rc/tumblr/library/tumblroauth.php

But the log says much higher line numbers:
> Undefined array key \"oauth_token\"","file":"/var/www/html/friend/addon/tumblr/library/tumblroauth.php","line":149

**Comment by loma-one** [comment]
**Instanz 1**
The last pull led to the desired result. Many thanks 👍

**Instanz 2**
Here I will reload the repro on RC again. Please consider the problem solved.

**Pull request merged**
