### PR TITLE
Remove conditional declaration of OAuthException

### LINKED ISSUE #4377: PHP fatal error on settings/connectors
I get a PHP fatal error and an error 500 (whitepage) on settings/connectors with current develop.

```PHP Fatal error: Cannot declare class OAuthConsumer, because the name is already in use in /var/www/html/libranet/library/OAuth1.php on line 12```

Core and addons pulled from develop. Composer install ran successfully.

Discussion here: https://forum.friendi.ca/display/a8e4f565155a733f2fc8b00964618359

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #4377

*sigh*

I believe this is the parting shot of this horribly obsolete library we unfortunately depend on for everything.

### CODE REVIEW

**Comment by annando** [comment]
This seems to have fixed the API issue as well.

**Comment by zeroadam** [comment]
👍😁

**Comment by annando** [comment]
I don't understand the origin of the problem and the solution to fix it, but I'm happy that it is done.

**Comment by MrPetovan** [comment]
Post-mortem: `class_exists()` triggers an autoload call when the class doesn't exist. The wrong flow goes like this:
1. Request for `OAuthConsumer` class.
2. Autoload correctly includes `library/OAuth1.php`.
3. Before any class from the file can be declared, there's a request for `OAuthException` through `class_exists()`.
4. Autoload correctly includes `library/OAuth1.php`, load all the classes inside.
5. The first include resumes, the `OAuthConsumer` class already has been declared in 4., triggering a Fatal Error.

This error is the origin of "Files SHOULD either declare symbols (classes, functions, constants, etc.) or cause side-effects (e.g. generate output, change .ini settings, etc.) but SHOULD NOT do both." in [the PSR-1 standard](https://www.php-fig.org/psr/psr-1/).

**Pull request merged**
