### PR TITLE
Domain-driven-design implementation 4th iteration

### PR DESCRIPTION
**Pull request by MrPetovan**
Redux of #8065 

This is an alternative to #8045 with which I'm more comfortable, allow me to walk you through it.

Here are the basic concepts:
- **Model**: An active object matching a database table.
- **Collection**: An inert array-like object of Models.
- **Entity**: A construct-once, read-only object. Mastodon entities are here. Constructors are tailored to require specific Friendica data and initialize the entity members accordingly. No more static factories.
- **Factory**: An Entity constructor wrapper to avoid repeating the same data gathering and to allow testability apparently.
- **Repository**: A factory for Models.

The advantages of this approach:
- No more redundancy in instantiating Entities. Duplicated code is grouped into Factory methods.
- Active objects allow clear syntax `$Object->action()`.
- Type safety everywhere. Models and Collections allow to tailor expected parameters and avoid surprises.

The drawbacks of this approach:
- Still not sure how to do `n-m` relationships with added data. For now this is left to the existing static `Contact` class but maybe there's a way to tie it to Models and Collections without circular dependencies?

### CODE REVIEW

**Comment by MrPetovan** [comment]
I replaced the `@method` in my code (not `DI.php` though) but I can't replace the `@property` in the `BaseModel` class hierarchy since I'm using `__get()` to verify the model's data integrity.

**Comment by nupplaphil** [comment]
I'm currently replacing the `DI::` classes which I'll push maybe tonight.

**Comment by nupplaphil** [comment]
> I replaced the `@method` in my code (not `DI.php` though) but I can't replace the `@property` in the `BaseModel` class hierarchy since I'm using `__get()` to verify the model's data integrity.

The only "workaround" using `__get()` would be using explicit getter, like `getId()`, but I know you don't like it ;-)

**Comment by MrPetovan** [comment]
If I can get rid of `__get` and `__set`, it looks better by the minute.

**Comment by nupplaphil** [comment]
> If I can get rid of `__get` and `__set`, it looks better by the minute.

This would need removing every `@property int $myField` annotations and replacing it with a `public function getMyField()` method.

**Comment by MrPetovan** [comment]
The problem we have is that some database fields are using minus sign (`-`) in their name as as such can't be directly translated to a property name, which requires more transformations. Leaving as is for the moment.

**Comment by nupplaphil** [comment]
Here we go :)

**Comment by nupplaphil** [comment]
Btw using `$intro->{contact-id}` seems a workaround using `-` too.. I think it isn't meant to have `-` in variables :)

**Comment by MrPetovan** [comment]
It works in our setup because `__get($name)` can accept `-` in `$name` and it checks an array key, but you can't declare a `contact-id` property that I know of.

**Comment by nupplaphil** [comment]
Btw that's why there's a general convention in my company about DB :
- DB names are all upper case
- only letters and underlines are allowed for naming
- use a product specific prefix

We had this kind of discussion too (Java ORM mapper vs DB fields) ^^

**Comment by MrPetovan** [comment]
> * only letters and underlines are allowed for naming

This isn't a rare convention, using `-` in MySQL field names also requires special care like systematic backtick wrapping when explicitly mentioned. I was surprised to find such field names when I discovered Friendica's schema.

**Comment by annando** [comment]
I find `-` more beautiful than `_`. And in fact we always have to wrap the fields in backticks, since we cannot always be sure if field names could be reserved words (in the future).

**Comment by MrPetovan** [comment]
It is more aesthetic to me as well, but it also prevents us from having 1:1 correspondence between field names and object property names. I'm not discussing systematic escaping either, I would enable it even with character-safe field names, but the technical limitation still remains and doesn't warrant the aesthetic choice for me.

**Pull request merged**
