### PR TITLE
Further unused tables to be dropped

### PR DESCRIPTION
**Pull request by annando**
I just discovered some more unused tables that can be deleted.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
There are more changes than just the tables, are you sure it isn't part of something bigger?

**Comment by MrPetovan** [comment]
Nevermind, it includes https://github.com/friendica/friendica/pull/10130

**Comment by AlfredSK** [comment]
Is there a reason why these tables are not offered for dropping when I run `dbstructure drop`?

**Comment by AlfredSK** [comment]
Ok. Looks like this is because they simply do not exist on newer nodes. :-D

**Comment by annando** [comment]
Yeah, these are really ancient tables.

**Pull request merged**
