### PR TITLE
New "post-user" structure, new update  functionality

### PR DESCRIPTION
**Pull request by annando**
The primary key of the "post-user" table has been changed. This enabled us to more easily replace the item table.

Also the item update mechanism had been simplified.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
After updating to this, the database structure update failed and I haven't received any new posts since. I've tried to run `bin/console dbstructure update` and it takes a long time but it doesn't seem to go to the end. Debug log doesn't show anything specific to the update.

**Comment by AlfredSK** [comment]
Geez. After pulling this my database is doing some heavy and long running queries, the PHP-FPM pool is hitting the limit and Apache is hitting the max request worker sever limit.

This is one of the long running queries stopping over 250 other queries from being processed:
``INSERT INTO `post-user`(`id`, `uri-id`, `uid`, `contact-id`, `unseen`, `origin`, `psid`) SELECT `id`, `uri-id`, `uid`, `contact-id`, `unseen`, .......``

My Friendica log looks like this....

```
......
2021-01-29T18:37:11Z index [ERROR]: DB Error {"code":1205,"error":"Lock wait timeout exceeded; try restarting transaction","callstack":"DBA::insert, User::insert, Item::insert, Diaspora::receiveStatusMessage, Diaspora::dispatch, Diaspora::dispatchPublic, Receive::receivePublic, Receive::post","params":"INSERT IGNORE INTO `post-user` (`uri-id`, `uid`, `protocol`, `contact-id`, `origin`, `psid`, `unseen`) VALUES (41887387, 0, 2, 164, 0, 0, 0)"} - {"file":"Database.php","line":765,"function":"e","uid":"e10598","process_id":3942151}
2021-01-29T18:37:12Z index [ERROR]: DB Error {"code":1205,"error":"Lock wait timeout exceeded; try restarting transaction","callstack":"DBA::insert, User::insert, Item::insert, DFRN::processEntry, DFRN::import, dfrn_dispatch_public, dfrn_notify_post, LegacyModule::runModuleFunction","params":"INSERT IGNORE INTO `post-user` (`uri-id`, `uid`, `protocol`, `contact-id`, `origin`, `psid`, `unseen`) VALUES (41887297, 0, 8, 22856, 0, 0, 0)"} - {"file":"Database.php","line":765,"function":"e","uid":"7d9af4","process_id":3943343}
2021-01-29T18:37:12Z index [ERROR]: DB Error {"code":1205,"error":"Lock wait timeout exceeded; try restarting transaction","callstack":"DBA::insert, User::insert, Item::insert, DFRN::processEntry, DFRN::import, dfrn_dispatch_private, dfrn_notify_post, LegacyModule::runModuleFunction","params":"INSERT IGNORE INTO `post-user` (`uri-id`, `uid`, `protocol`, `contact-id`, `origin`, `psid`) VALUES (41887297, 2766, 8, 469165, 0, 0)"} - {"file":"Database.php","line":765,"function":"e","uid":"86e69e","process_id":3942069}
2021-01-29T18:37:12Z index [ERROR]: DB Error {"code":1205,"error":"Lock wait timeout exceeded; try restarting transaction","callstack":"DBA::insert, User::insert, Item::insert, Processor::postItem, Receiver::processActivity, Receiver::processInbox, Inbox::rawContent, call_user_func","params":"INSERT IGNORE INTO `post-user` (`uri-id`, `uid`, `protocol`, `contact-id`, `origin`, `psid`, `unseen`) VALUES (41887391, 0, 0, 123, 0, 0, 0)"} - {"file":"Database.php","line":765,"function":"e","uid":"98dd1b","process_id":3942693}
2021-01-29T18:37:12Z index [ERROR]: DB Error {"code":1205,"error":"Lock wait timeout exceeded; try restarting transaction","callstack":"DBA::insert, User::insert, Item::insert, DFRN::processEntry, DFRN::import, dfrn_dispatch_private, dfrn_notify_post, LegacyModule::runModuleFunction","params":"INSERT IGNORE INTO `post-user` (`uri-id`, `uid`, `protocol`, `contact-id`, `origin`, `psid`) VALUES (41887297, 3330, 8, 582845, 0, 0)"} - {"file":"Database.php","line":765,"function":"e","uid":"64f617","process_id":3940003}
2021-01-29T18:37:12Z worker [ERROR]: DB Error {"code":1205,"error":"Lock wait timeout exceeded; try restarting transaction","callstack":"DBA::update, OnePoll::updateContact, OnePoll::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"UPDATE `contact` SET `failed` = 0, `last-update` = '2021-01-29 18:33:08', `success_update` = '2021-01-29 18:33:08' WHERE (`rel` = 1 AND `nurl` = 'http:\/\/aerzteblatt.de\/rss\/news.asp?_lnsXts=20180622072907')"} - {"file":"Database.php","line":765,"function":"e","uid":"656b99","process_id":3934479}
........
```

**Comment by AlfredSK** [comment]
Looks like the dbstructure update was processed. No error when I run the dbstructure update manually (with or w/o -f) on console. Also no pending postupdates when I run the command manually. But still, this is killing the server.

This also happens with maintenance mode enabled.

**Comment by AlfredSK** [comment]
Okay. Looks like after 1.5 hours the madness has come to an end. I will watch what happens...

Edit: Hmm. There was a forum post about the expected issues. But I couldn't read it because of the issues. Catch 22. :-)

**Comment by annando** [comment]
The system should have gone into maintenance while updating. I guess I have to check why this wasn't the case.

**Comment by MrPetovan** [comment]
I've had the same error messages as @AlfredSK and 7 hours later no post has reached my node, I just checked out the previous commit before the `post-user` table was introduced but I'm afraid that my node will be out of commission for goodness knows how long.

**Comment by annando** [comment]
@MrPetovan it should be no problem to use the current commit and then manually enforce the maintenance mode and run the update. Possibly you should reset your database version prior to this by calling `bin/console dbstructure version 1394`.

**Comment by MrPetovan** [comment]
Posts have finally started coming in after the checkout. I'll try `develop` again during the night.

**Comment by MrPetovan** [comment]
Now I have a lot of these errors:
```
2021-01-30T16:05:29Z index [ERROR]: DB Error {"code":1062,"error":"Duplicate entry '3537020' for key 'PRIMARY'","callstack":"DBA::insert, Item::insert, Processor::postItem, Receiver::processActivity, Receiver::processInbox, Inbox::rawContent, call_user_func, Module::run","params":"INSERT INTO `item` (`thr-parent`, `gravity`, `network`, `author-id`, `owner-id`, `private`, `uri`, `created`, `edited`, `guid`, `uri-id`, `uid`, `post-type`, `contact-id`, `parent-uri`, `parent-uri-id`, `thr-parent-id`, `wall`, `extid`, `received`, `changed`, `commented`, `visible`, `deleted`, `origin`, `resource-id`, `event-id`, `global`, `vid`, `psid`, `id`) VALUES ('https:\/\/mastodon.xyz\/users\/lightone\/statuses\/105645521375955008', 0, 'apub', 79559, 79559, 0, 'https:\/\/mastodon.xyz\/users\/lightone\/statuses\/105645521375955008', '2021-01-30 16:05:26', '2021-01-30 16:05:26', '47cb7c42-e949f97cb80086b4-253d184a', 2742443, 1, 69, 127565, 'https:\/\/mastodon.xyz\/users\/lightone\/statuses\/105645521375955008', 2742443, 2742443, 0, '', '2021-01-30 16:05:29', '2021-01-30 16:05:26', '2021-01-30 16:05:26', 1, 0, 0, '', 0, 0, 8, 0, 3537020)"} - {"file":"Database.php","line":765,"function":"e","uid":"8e8c74","process_id":11011}
```
Items are spooled, retried but it still fails.

Also these:
```
2021-01-30T16:06:38Z index [NOTICE]: Post-User is already inserted - aborting {"uid":0,"uri-id":2742445} - {"file":"Item.php","line":1126,"function":"insert","uid":"ee3417","process_id":11166}
```

**Comment by MrPetovan** [comment]
I have reverted to the previous commit again, and I've been able to receive posts again. Something is wrong with this PR.

**Comment by AlfredSK** [comment]
Hmm. Sorry to hear that. In my case sending and receiving posts seem to work now after the node survived the initial issues.

**Pull request merged**
