### PR TITLE
Workaround for Bugs in Class dba

### PR DESCRIPTION
**Pull request by miqrogroove**
This really ought to be addressed through the weaknesses of /include/dba.php but I will open a separate issue for that.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Follow-up to #5263

**Comment by annando** [comment]
It's not really a bug of the dba class, but of the MySQLi driver we are using there. The PDO driver can work that way. Since we mostly shouldn't use direct SQL queries, but "select" and "selectFirst", there is no need to invest much time into it.

**Comment by miqrogroove** [comment]
Looks like integers are already implemented for the mysqli.  The only problem I see there is with BLOB being the default type, which is a rather strange assumption.

**Comment by annando** [comment]
I created that class - but I'm no PHP coder. At work I'm using some very different language. So if you find some improvements, please tell.

**Pull request merged**
