### PR TITLE
Ensure $categories is set in mod/item

### PR DESCRIPTION
**Pull request by MrPetovan**
- Address https://github.com/friendica/friendica/issues/8473#issuecomment-639052328

### CODE REVIEW

**Comment by annando** [comment]
I guess that the origin of the problem lies within the `Item` class and should be fixed there. Possibly this is an indicator for a larger problem.

**Comment by MrPetovan** [comment]
Ok.

**Comment by annando** [comment]
I made many changes to the `Item` class lately. So I'm sure I broke it there. We have to check if we fill this field at all.

**Comment by MrPetovan** [comment]
Maybe not, but I'd like to fix the Fatal Error first before investigating further.

**Comment by annando** [comment]
After a small glance, I have the feeling as if it is caused by the `verb` handling. So I guess I will have a look at it later. Means: I would remove this check later on when I found the real cause.

**Pull request merged**
