### PR TITLE
Add module class routing

### PR DESCRIPTION
**Pull request by MrPetovan**
Kickstarts #4090

Allows develop to start moving module files to Module classes.

### CODE REVIEW

**Comment by annando** [comment]
Concerning the base module: I'm asking myself which way is better concerning performance:
* No base module and checking if class method exists and only calls it then.
* Having the base module and a method but (nearly) always not having all methods inherited.

**Comment by MrPetovan** [comment]
I think the difference is negligible unfavoring the first case and the second case I implemented is easier to read.

**Comment by annando** [comment]
Concerning the class name: Which name will have the class for the file ".well-known"? What about "statistics.json" or "dfrn_confirm"?

**Comment by MrPetovan** [comment]
For now they will have to stay in `mod` until we properly move the routing mechanism to `App` where we will be able to add special cases.

**Comment by MrPetovan** [comment]
Ultimately almost all index.php lines will be moved to App as well.

**Comment by annando** [comment]
We won't have a chance to use something like some kind of translation table, since we always have to consider that a path could belong to an addon. So we need something that is fully automatic.

**Comment by MrPetovan** [comment]
There are two main issues with addons:
1. Adding their autoloader to Friendica
2. Adding their modules to Friendica

Currently, 1. is easily solved with a custom namespace `Friendica\Addon` pointing at `addon`. 2. is trickier with an automated system, but if we make the enabled addons register their modules within `App` at startup, then we just have to look through them before resorting to the automatic module finder.

**Pull request merged**
