### PR TITLE
Decoupling is deactivated by default now

### PR DESCRIPTION
**Pull request by annando**
It seems as if this leads to endless loops.

### CODE REVIEW

**Comment by AlfredSK** [comment]
I'm sorry to inform you but this PR made the situation on my node even worse. Load went up from 80% to 100%. Worker.php processes and 10000 qps on the database are killing the server.

**Comment by tobiasd** [comment]
@annando revealed to me that a deactivated decoupled receiver and a high value for the new recursion depths parameter would simulate the system that was before introducing the changes (high value at the recursion depths will wait longer until the front-end will pass the receiving part into a worker job).

**Comment by AlfredSK** [comment]
Thanks. I had set a low value. Changed it to 30 now.

**Comment by Quix0r** [comment]
As usual, have you tried `nice --adjustment=19 ./bin/daemon.php start` or `renice 19 $(pidof php)` if the daemon is already running?

**Comment by AlfredSK** [comment]
I don't use the daemon. Just the cron job.

**Comment by tobiasd** [comment]
I'm on 64894f9d6f436bbfc439538a6743e497f87af22c and right now, my node seems to be in quiet waters again. I did reduce the number of parallel allowed workers and put the cron started worker on a slightly higher nice value then the other jobs run on the system (you can adjust the value using `mc`.

System LOAD is now stable within working parameters, though higher then before.

**Comment by AlfredSK** [comment]
After today's pull, reducing workers from 35 to 20, increasing max_recursion_depth to 50, and extending the cron interval from 3 to 6 minutes, I'm cautiously optimistic. The load is currently down from 80% to 30%. Let's see if it stays that way.

To be followed here if interested:
https://munin.libranet.de/system-day.html
https://munin.libranet.de/mysql-day.html

**Pull request merged**
