### PR TITLE
Update EN-GB Translation Core + Create EN-US Translation core

### PR DESCRIPTION
**Pull request by AndyHee**

### CODE REVIEW

**Comment by AndyHee** [comment]
US English core is now 100%.

**Comment by Hypolite** [comment]
> This commit contained the wrong file. It was corrected by this subsequent update: 379a01a

No worries, GitHub tracks every subsequent commit in the same branch.

Out of curiosity, did you change any of the en-US translations?

**Comment by AndyHee** [comment]
I had accidentally uploaded the wrong file. The en-US translation is completely new. I created this on the basis of the en-GB version that contained some major re-phrasing (for consistency and simplification) and merely corrected the spelling for -ize and -o- . So now we have two reasonably well-developed English localizations. :-)

**Comment by tobiasd** [comment]
Thanks <3

**Comment by Hypolite** [comment]
@AndyHee This is amazing, thank you so much!

**Pull request merged**
