### PR TITLE
Salmon move to src

### PR DESCRIPTION
**Pull request by zeroadam**
Salmon class, update function name and function calls. Some standards as well.

### CODE REVIEW

**Comment by zeroadam** [comment]
@MrPetovan I finally made sure to rename function name in the way I know you'd want!
@annando I searched everywhere including addons for all occurrences of salmon not just include/salmon, to avoid my past missteps!

**Comment by MrPetovan** [comment]
Thanks for improving your process! I'd like to ask you that you commit all the formatting changes together before you make any other changes so that I can choose the relevant commits for review instead of having to look for the meaningful changes in a sea of formatting changes.

**Comment by zeroadam** [comment]
Yeah, sorry about that. I didn't split this one up as I had been in my last several PR's. Sometimes I get carried away as I'm seeing red squiggles through the files!

**Comment by MrPetovan** [comment]
I'm the same way, that's why I know what to ask from you! 😄

**Pull request merged**
