### PR TITLE
"selectForUser" and "selectFirstForUser" is now moved to Post

### PR DESCRIPTION
**Pull request by annando**
Also the `inArray` function is moved to `toArray` to make it identical to the `DBA` class.

### CODE REVIEW

**Comment by annando** [comment]
Tests are currently failing. I will have a look at it tomorrow.

**Comment by annando** [comment]
Tests are now okay.

**Review by MrPetovan — APPROVED** [review]

**Comment by annando** [comment]
PR https://github.com/friendica/friendica-addons/pull/1068 has to be merged as well.

**Comment by annando** [comment]
P.S.: @MrPetovan This had been a quick review!

**Comment by MrPetovan** [comment]
I think I started reviewing while the tests were still failing.

**Pull request merged**
