### PR TITLE
Quoted posts from Twitter now contain media again

### PR DESCRIPTION
**Pull request by annando**
Fixes https://github.com/friendica/friendica/pull/11981#issuecomment-1273794937

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by loma-one** [comment]
Pictures or video will not be distributed.

Origin instance
https://dis-le.de/display/50619573-1363-44f6-8fc9-891685608047
image

Recipient instance
image
image

**Comment by annando** [comment]
Can you provide a link with a post where it had been working? I'm currently in the "had this worked before?" stage :thinking:

**Comment by loma-one** [comment]
With the exception of Twitter, all redirects seem to work. With Twitter as the source, I have never been able to distribute a post with an image or video attachment.

**Comment by annando** [comment]
Twitter is different than posts from federated networks. For analysis purposes I need some old quoted twitter post with pictures.

**Comment by loma-one** [comment]
Since I just recently (1 weeks) switched to RC, I unfortunately can't provide any examples.

**Comment by MrPetovan** [comment]
I didn't update recently so I can provide a reference example. How do I get this display with the quoted Twitter post?

**Comment by annando** [comment]
This evening I will check if I need more information or if I can resolve this on my own.

**Pull request merged**
