### PR TITLE
Fr translation fix

### PR DESCRIPTION
**Pull request by Hypolite**
Just an accent fix in the french translation.

### CODE REVIEW

**Comment by tobiasd** [comment]
Do you have an account at transifex as well to upload the messages.po file there to have the changes there as well? Or should I update the file there?

**Comment by Hypolite** [comment]
I don't, where do I sign up?

**Comment by tobiasd** [comment]
Here https://www.transifex.com/projects/p/friendica/ and then join the French language team (and any other team you want to ).

**Comment by Hypolite** [comment]
Thanks, it's done!

**Pull request merged**
