### PR TITLE
Issue 8371: Use the permissionset for public items

### LINKED ISSUE #8371: Photos uploaded in comments get no permissions
### Expected behavior

- I make a public comment to a public post.
- I attach a photo.
- The photo is public.

### Actual behavior

- The photo has no permissions.

If I go to the photo and click Permissions, it says it is public, and if I submit at that point, it becomes actually public.

> Looks like the image does not get any permission set - not even the public one. It looks like 'public' but in fact it is somehow set to 'none'.

https://libranet.de/display/0b6b25a8-125e-5f4d-0f94-670912314070

### Friendica version you encountered the problem

`Friendica, version 2020.03-dev that is running at the web location https://libranet.de. The database version is 1335, the post update version is 1329.`

### PR DESCRIPTION
**Pull request by annando**
This now really fixes #8371

### CODE REVIEW

**Comment by MrPetovan** [comment]
This is madness. I checked the permissionset join, it's a LEFT JOIN, so with psid = 0 all the table fields would simply be NULL, which would denote a public item. This comes from the fact that we have no reason to separate NULL values from empty string in those fields. The solution to this "problem" isn't to create a row with empty fields per user in the `permissionset` table. It's to treat NULL as empty values for the purpose of permissions.

**Comment by annando** [comment]
`null` is a sign for uninitialized data, for data that hadn't been found. This does not only impact the picture situation, this also could impact the comment distribution, so that we possibly had to code several workarounds.

There is only one reason that the permissionset join is currently not an inner join: We are doing the transformation to this in a post update functionality. The long term goal is to make it an inner join as well, since permissions are always needed. And it is safer to not show some data than to accidentally expose something.

In fact I'm thinking about reverting some of my previous changes, since it pointed us to this problem.

**Comment by MrPetovan** [comment]
Yes, but again, for permissions in the current state of the codebase it doesn't matter if permissions are empty string or null, we don't have separate use cases for either. It isn't like we had a unique allowed string where if empty, it would mean no one is allowed, which would be different from a NULL value meaning public.

In our case, both empty string and null mean the same thing.

**Comment by MrPetovan** [comment]
Replaced by #8435

**Pull request closed without merging**
