### PR TITLE
2020.09.1 Changelog

### PR DESCRIPTION
**Pull request by tobiasd**

### CODE REVIEW

**Comment by MrPetovan** [comment]
I thought we were using a dash for hotfix version numbers, like this: `2020.09-1`. Is there a specific reason we are using the dot now or did I imagine the dash?

**Comment by nupplaphil** [comment]
Plz use a dash for hf version like before, otherwise I do have to alter the docker script again ^^..

**Comment by AlfredSK** [comment]
Yup. We used to use a dash: `2020.07-1-1355`

**Comment by tobiasd** [comment]
I think the dash has problems with the admin overview :) but I can change this before the release

**Pull request merged**
