### PR TITLE
Fix: The acl lookup now works in multi threaded posts as well

### PR DESCRIPTION
**Pull request by MrPetovan**
Port of #4587 for the develop branch

### CODE REVIEW

**Comment by annando** [comment]
Normally we apply the RC changes to the dev with some GIT magic after the release. I would like to continue to do so. Of course we will get some conflicts - but we should treat them at that time.

**Comment by MrPetovan** [comment]
I know exactly who will resolve the conflicts when the time comes, so I was just getting ahead.

**Comment by annando** [comment]
Hopefully most of the bugfixes should be no problem. It would be great if you would take over the job, since you should know the changed parts the best.

**Comment by MrPetovan** [comment]
> It would be great if you would take over the job

My last comment wasn't a joke, I really didn't think anyone else but me would have merged the RC branch back into the `develop` branch!

**Comment by MrPetovan** [comment]
Yes, I moved a lot of stuff around that got changed in parallel in the RC branch. Like I said twice now, I was expecting it and I was ready to do it before anyone talked about it!

**Comment by annando** [comment]
Thanks for doing so!

**Comment by MrPetovan** [comment]
Believe it or not, I look forward to it!

**Comment by annando** [comment]
You are weird, I like it :grinning:

**Comment by MrPetovan** [comment]
My girlfriend says the same exact thing. 🤔

**Comment by annando** [comment]
Hopefully with the second part as well :-)

**Pull request closed without merging**
