### PR TITLE
Do not cache Contact::getDetailsByURL result if it doesn't come from the DB

### PR DESCRIPTION
**Pull request by MrPetovan**
- Address https://github.com/friendica/friendica/issues/8000#issuecomment-592169621

### CODE REVIEW

**Comment by annando** [comment]
Can you check why the tests are failing? This seems to be unrelated to this PR, but confusing anyway.

**Comment by MrPetovan** [comment]
> There were 377 errors:
> 377 x `Undefined index: MYSQL_PASSWORD`

Help @nupplaphil !

**Comment by nupplaphil** [comment]
Seems like this env initialization doesn't work anymore with empty vars:
https://github.com/friendica/friendica/blob/79803a6546dd251f6fee557434816a39bc1fb7ce/.travis.yml#L14

Seems like a travis "change".

**Comment by nupplaphil** [comment]
plz rebase after #8348

**Comment by MrPetovan** [comment]
Restarting the test build instead.

**Comment by nupplaphil** [comment]
Hmm .. Ok I think I should have known that .. Merging "just" means to add the commit to the branch .. But the travis-fix commit is chronological after the commits you want to merge in this PR, even if it's already merged ...

**Comment by MrPetovan** [comment]
Apparently it doesn't work, rebasing instead.

**Comment by MrPetovan** [comment]
Well, I'm stupid and I shot myself in the foot.

**Comment by nupplaphil** [comment]
> Well, I'm stupid and I shot myself in the foot.

Please don't :face_with_head_bandage:

**Pull request merged**
