### PR TITLE
Separate JSON output of contact lists in message_recipient template

### LINKED ISSUE #13026: Private Messages flaw
- [ X] I have searched open and closed issues for duplicates

### Bug Description

Composing private Messages don´t work in Friedica 2023.04

### Steps to Reproduce

1.  Open Private Messages
2.  Try to create a ne private Message via the "+" Button

Actual Result:

It won´t work you get a 550 Error. 

Error Messages provided from other admins:
```
TypeError: Cannot access offset of type string on string in /var/www/html/view/smarty3/compiled/67/5d/4e/675d4ecb09a737a51110c0f1840ef4487aa1be4e_2.file.message_recipient.tpl.php:32
Stack trace:
#0 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_644553cc4d1d03_80577142()
#1 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#2 /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()
#3 /var/www/html/vendor/smarty/sm
```
It worked seamless in the lates pull of 2023.03.RC
It seeams that thias is Php 8.0 related (not sure)

Expected Result:

You could create a new private message.

### Platform Info

Friendica Version: 2023.04

### PR DESCRIPTION
**Pull request by MrPetovan**
Fix #13026

### CODE REVIEW

**Comment by tobiasd** [comment]
Should we do a 2023.4.1 hotfix release for this commit?

**Comment by annando** [comment]
I guess this would be a good idea. I had been away yesterday, so I only had a short glimpse at it. But this causes a WSOD, doesn't it?

**Comment by MrPetovan** [comment]
Yes it does, for PHP 8.0+, although I've received report the fix might not be complete: https://anonsys.net/display/bf69967c-8264-461b-00b0-642397481096

**Comment by annando** [comment]
Okay, so we might want to wait until it really works.

**Comment by MrPetovan** [comment]
@annando Do you run PHP 8.1+ and would be able to look into this? The issue revolves around the way we pass the contact list to the `acl/message_recipients.tpl`  template in `ACL::getMessageContactSelectHTML`.

**Comment by annando** [comment]
I'm running 8.0

**Comment by MrPetovan** [comment]
Sorry, PHP 8.0 seems to be enough.

**Comment by AlfredSK** [comment]
> Yes it does, for PHP 8.0+, although I've received report the fix might not be complete: https://anonsys.net/display/bf69967c-8264-461b-00b0-642397481096

Hmm. I'm running mordor.social on develop and PHP 8.1. Everything is fine here.

**Comment by MrPetovan** [comment]
@tobiasd Can we please perform a 2023.04 hot fix release with the current `develop` as soon as possible?

**Comment by tobiasd** [comment]
If the problems with the DMs is fixed, sure. Addons (Tumblr) as well?

**Comment by MrPetovan** [comment]
Yes please.

**Comment by MrPetovan** [comment]
For the hotfix release, please merge from `develop` for both the core and addons.

**Pull request merged**
