### PR TITLE
Changed tooltip from #4965

### PR DESCRIPTION
**Pull request by Quix0r**
This PR changes the tooltip messages from #4965 .

### CODE REVIEW

**Comment by MrPetovan** [comment]
Can you please fix the tooltip vertical position as well?

**Comment by Quix0r** [comment]
Isn't this theme-depending? Sorry, I don't know where to look for.

**Comment by MrPetovan** [comment]
Never mind, it's:
- theme related
- depending on questionable CSS anyway

**Comment by tobiasd** [comment]
Somehow the strings from the addons got mixed into the master messages.po file with this. @Quix0r the directory you have your addon repository in is called `addons` right not simply `addon`?

**Comment by Quix0r** [comment]
`addons`

**Pull request merged**
