### PR TITLE
Add license check & Fix CI CHANGED_FILES

### PR DESCRIPTION
**Pull request by nupplaphil**
Adds a new CI task "license check" because I always forget to add it .. ;-)

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by nupplaphil** [comment]
I found a general bug when retrieving changed files .. I'll have to fix it first
(the license check shouldn't pass because I added a typo at `OptionsTest.php` :D )

**Comment by nupplaphil** [comment]
Fixed! :-)

**Comment by nupplaphil** [comment]
At least .. it works now .. wasn't that easy because of a lot of bash magic

**Comment by nupplaphil** [comment]
Done, I'm out now :D 
All licenses are now added and so we're ready for the release now ;-) ;-)

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
