### PR TITLE
Some more performance measuring for database stuff

### PR DESCRIPTION
**Pull request by annando**
Now the timestamp stuff is counted for some other database related actions as well.

### CODE REVIEW

**Comment by MrPetovan** [comment]
This will flood the rendertime output with every single fetch operation. Instead, you have to enclose the whole loop. A more accurate way would be to track statements creation and closing. In pseudo-code:
```php
class dba {
  ...
  function p() {
    ...
    $a->start_timestamp('database', $stmt_id);
    ...
  }

  function close($stmt) {
    ...
    $a->save_timestamp('database', $stmt_id);
    ...
  }
  ...
}
```
The statement ID might have to be generated and tacked on the Statement object.

**Comment by annando** [comment]
No, we have to make the timestamp very atomic. A begin and and end must never contain another timestamp. Just imagine that between a ```p``` and a ```close``` is some network probing of contacts. We - for example - checked 100 contacts and had several timeouts, so the sum of the probing was (for example) 500 seconds. The ```p``` query and the ```close``` only took 0.05 seconds in total, but now the system would state that the database action had taken 500.05 seconds.

And no, it wouldn't flood the rendertime for several reasons. At first, we only display single values above 0.001 seconds. Second: we sum the values. So even if we did 100 close commands, only a single line would be displayed for it.

**Comment by MrPetovan** [comment]
Ha, you're right. I don't understand the "we sum the values" though, if there's a loop with 10,000 `dba::fetch` but none of them take more than 0.001s, nothing would be shown at all, right? But in the full database timing, it would show 10 seconds?

**Comment by annando** [comment]
See this code:
```
$callstack = System::callstack();

if (!isset($this->callstack[$value][$callstack])) {
        // Prevent ugly E_NOTICE
        $this->callstack[$value][$callstack] = 0;
}
$this->callstack[$value][$callstack] += (float) $duration;
```

**Comment by MrPetovan** [comment]
So the same exact call stack will be accrued, not duplicated. Interesting.

**Pull request merged**
