### PR TITLE
Issue 14231: Automatically add the relay owner as contact person

### LINKED ISSUE #14231: Obligation to name a contact person for relay accounts
### Describe the feature you'd like

Relay accounts are unfortunately developing into a new plague in the Fediverse. Not only hashtags, but also words are being fished for and re-shared. 

Often no contact person is named or made transparent as to which hashtags and words are being searched for and shared. There is currently no way to tell the bot that you don't want to be shared.

This all seems very intrusive and puts Friendica in a bad light. This is a pity because the function is a wonderful tool in responsible hands.

It would therefore be good if there was a mandatory field that was obligatory and named a contact person who could be contacted.

General wish: All relay operators should undertake to make transparent how the relay works, which search terms are used and how you can protect yourself from unwanted sharing.

### PR DESCRIPTION
**Pull request by annando**
Fixes #14231

From now on you can only setup relay accounts as a sub account of your main account. Also thr address (either the handle or the url) must be part of the "about" text. Otherwise it is added automatically.

### CODE REVIEW

**Comment by SpcCw** [comment]
@annando what will happen with existing standalone relay accounts? I'd hate to see them bricked now or later.

**Comment by annando** [comment]
They will continue to exist unless you apply changes to the profile in the account settings, I guess.

**Comment by annando** [comment]
It should be possible to create a delegation to your main account to solve this issue.

**Comment by SpcCw** [comment]
If delegates (not parent users) work then it shouldn't be a problem. In my case I have some accounts set to relay mode now which have their own emails so parent user can't be selected but delegation is set up.

I don't mind this change but want to be sure I will have some backup path of restoring relay mode if it switches for some reason.

**Comment by annando** [comment]
Currently it only works with parent users.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
