### PR TITLE
Issue 10491: Possibility for simple shortening added

### LINKED ISSUE #10491: Twitter addon post trimming is unusable
Working with the 2021.07 stable release.

The addon should trim posts only on character count (260) . Not on paragraphs or empty lines. 
This behavior makes the addon unusable.

I wrote this post in Friendica 
01_temp

And on Twitter it shows
00_temp

### PR DESCRIPTION
**Pull request by annando**
Fixes #10491

Now it is possible to deactivate the text shortening that shortens after a line feed. When deactivated the shortening will always be at the maximum character limit.

### CODE REVIEW

**Comment by annando** [comment]
@nupplaphil something is wrong with the tests.

**Comment by MrPetovan** [comment]
This PR doesn't look right, there is some remote deletion code mixed with the simple shortening.

Additionally, aren't "Simple shortening" and "Intelligent shortening" mutually exclusive?

**Comment by annando** [comment]
@MrPetovan yeah, I mixed some experimental stuff with the intended code. The two options aren't excluding each other. The existing one is for detecting which link to take and the other one is for deciding when to cut the text.

**Comment by MrPetovan** [comment]
This really isn't obvious with the current setting names. 😅

**Comment by MrPetovan** [comment]
I simplified your branch, between the multiple partial reverts and the merge from develop, it had 3 times the number of commits it should have had.

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
