### PR TITLE
Add content type check before webfinger to probe feeds earlier

### LINKED ISSUE #8807: Mastodon rss feeds can't be added as contacts.
### Expected behavior

Mastodon RSS feed added as a contact so I can mirror its content.

### Actual behavior

Mastodon RSS feed isn't added as a contact, Message: The network type couldn't be detected. Contact can't be added.

### Steps to reproduce the problem

Try to add a Mastodon RSS as a contact (feed). It doesn't work.
If you probe the direction (changed for example):
```
Array
(
    [name] => https://example.com/users/user.rss
    [nick] => https://example.com/users/user.rss
    [guid] => 
    [url] => https://example.com/users/user.rss
    [addr] => user@example.com
    [alias] => 
    [photo] => https://myinstance.ex/images/person-300.jpg
    [account-type] => 
    [community] => 
    [keywords] => 
    [location] => 
    [about] => 
    [hide] => 
    [batch] => 
    [notify] => 
    [poll] => 
    [request] => 
    [confirm] => 
    [poco] => 
    [following] => 
    [followers] => 
    [inbox] => 
    [outbox] => 
    [sharedinbox] => 
    [priority] => 0
    [network] => unkn
    [pubkey] => 
    [baseurl] => https://example.com
)
```

### Friendica version you encountered the problem

2020.03

### Friendica source (git, zip)

git

### PHP version

PHP 7.4.7

### SQL version

mysql  Ver 15.1 Distrib 10.3.17-MariaDB, for Linux (x86_64) using readline 5.1

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #8807

The problem of this specific probe is that Mastodon servers offer webfinger, but it can't return any meaningful data for Mastodon User RSS feeds.

The new probe flow first retrieve the remote page if it's a fully-formed URL, checks the content-type for RSS and Atom feeds, which skips the webfinger probe entirely.

There is a slight performance hit for probing fully-formed profile URLs on Webfinger-enabled hosts as we first retrieve the profile page for nothing.

### CODE REVIEW

**Comment by annando** [comment]
This check could potentially lead to a situation where a link is falsely detected as feed although the webfinger probe would have a different result. Also it adds this additional network request that will significantly reduce the probing speed since fetching profile data will take some time on the remote system. Also it puts additional load on the remote systems for a constellation that is rather the exception than the normal situation.

**Comment by MrPetovan** [comment]
I agree with the performance hit, but how would a link be falsely detected as feed if its content type is either `application/rss+xml` or `application/atom+xml` ?

**Comment by annando** [comment]
It's more a theoretical think with the feed. It is possible that some weird implementation is returning a feed at the profile address (and only return a JSON when requested). To avoid this, I would like to check at the end of the processing.

And the performance stuff is really a thing.

**Comment by MrPetovan** [comment]
> It is possible that some weird implementation is returning a feed at the profile address (and only return a JSON when requested)

So it would be some software that:
- Has profile URLs output XML feed by default
- Doesn't provide Webfinger
- Output AP objects when content-type is provided

This is a (remote) possibility, but it doesn't justify supporting the current Mastodon edge case where:
- The feed URL is different from the profile URL
- The server provides Webfinger
- Its result is wrong when querying with the feed URL

I believe we'll handle your hypothetical software when and if it shows up, in the mean time I'd prefer if we supported actual cases.

**Comment by annando** [comment]
I create an alternate solution that doesn't increase the number of network requests: https://github.com/friendica/friendica/pull/8813

**Comment by MrPetovan** [comment]
Replaced by #8813

**Pull request closed without merging**
