### PR TITLE
Activities are now displayed as Emojis

### PR DESCRIPTION
**Pull request by annando**
When enabled, activities (like, displike, reshares) are now displayed as emojis. also we now display emoji reactions from systems like Misskey or Pleroma.

grafik
grafik
grafik
grafik

Also there is no memory issue any more displaying higher numbers:
grafik

We can now also display the viewer counts of Peertube videos:
grafik

### CODE REVIEW

**Comment by tobiasd** [comment]
part of #12805

**Comment by annando** [comment]
I don't think that it closes this issue. This just changes the way it is displayed.

**Comment by tobiasd** [comment]
You are right, I thought the issue was about the display of the reactions...

**Comment by loma-one** [comment]
A really nice feature. Many thanks for it! :tada: 
There seems to be small error. The post was liked 6 times. After a like was passed from the misskey, all likes disappeared.

Stable
Screenshot 2023-02-18 at 15-46-15 (1) ˈloma Contact

dev
Screenshot 2023-02-18 at 15-46-28 dr-e 🛡️

**Comment by annando** [comment]
Please deactivate the config value. I guess then you will also only see one like and 3 reshares. The distribution of activities is flaky.

**Comment by SpcCw** [comment]
This feature is really nice!

I understand this is work in progress. I noticed that when this mode is enabled it is impossible to see who liked or reshared the post on mobile - this information displays as hovering tip and the most mobile devices don't allow to hover. Is this planned to be added before release?

**Comment by MrPetovan** [comment]
We used to have a link button you could press when there were too many likes/reshares that would list all the account names and profile URLs, we should bring it back for this feature.

**Comment by AlfredSK** [comment]
I think I have seen this behavior on other systems: you can click/tap the icons to make the tooltip to appear.

**Comment by annando** [comment]
I see this PR as the first step towards a new way working with activities. My long term plan is to have a single rows that both displays the numbers of activities (like, reshare, emojis, ...) and does perform this activity when pressed. Because of this I haven't put the display of the actors behind some clickable link.

Are there any options on mobiles that we could use for this that isn't a simple click?

**Comment by AlfredSK** [comment]
Here on GitHub a short tap performs the action, a long tap only brings up the tooltip.

**Comment by annando** [comment]
Do we find someone who could implement this?

**Comment by AlfredSK** [comment]
Another idea from Misskey: there is something in the more menu (…). A menu item called "reactions". It opens a modal (popup window) with a list of all reactions/activities.

**Comment by MrPetovan** [comment]
> Do we find someone who could implement this?

It was existing on Friendica for Likes, Dislikes and Reshares, it shouldn't be hard to revive/adapt.

**Comment by annando** [comment]
I referred to this "a long tap".

**Pull request merged**
