### PR TITLE
Improved handling of leading and trailing attachments

### PR DESCRIPTION
**Pull request by annando**
Audio and video attachment are added before the content, pictures are added at the end of the content. Now there is a horizontal ruler to divide the content from the media.

### CODE REVIEW

**Review by MrPetovan — APPROVED** [review]

**Comment by MrPetovan** [comment]
Video attachments are placed at the end of the post on Mastodon, and this makes for some really awkward posts on Friendica where the video introduction is after the video. I'm not sure why you went this way but it doesn't work very well for casual content. I'm guessing PeerTube posts with their titles and description would look better but this just makes any other use case counter-intuitive.

**Comment by annando** [comment]
Yeah, I had focused on Peertube here. Can you provide a link to a Mastodon post with attached video?

**Comment by MrPetovan** [comment]
A really outrageous example with a looping animation converted to video and then attached at the top:
Mastodon: https://hackers.town/@crazypedia/106014553233384956
Friendica: https://friendica.mrpetovan.com/display/4381cc58-f8d15d17c5dabc7f-03e80e9c

A regular example where the caption is expected before the video:
Mastodon: https://toot.aquilenet.fr/@MicroCheapFx/104851836966111446
Friendica: https://friendica.mrpetovan.com/display/0c8939d2-3f4a6019826e7e82-0eb0ea59

**Comment by MrPetovan** [comment]
I spotted another issue, this time with WriteFreely, the post image is duplicated as attachment:
WriteFreely: https://pencil.writefree.ly/wakest/a-memory-to-remember
Friendica: https://friendica.mrpetovan.com/display/187317ea-f418aa549c1f1c9a-5d6f8c7d

**Pull request merged**
