### PR TITLE
Issue 1218: generate $argv and $argc from $_SERVER if it wasn't defined

### PR DESCRIPTION
**Pull request by annando**
See Issue https://github.com/friendica/friendica/issues/1218

This programming should prevent situations, where $argv and $argc aren't defined.

### CODE REVIEW

**Comment by Beanow** [comment]
I think it would be better to use `$argc = count($argv);` from my original issue. Because $argc should always correspond to the $argv value. If somehow $argc was set there might be a mismatch.

**Comment by annando** [comment]
I would rather rely upon the original values instead of emulating them. You never know wether there will be changes to them in future versions. But I understand your concerns.

I would prefer that we find out wether we can always rely upon the $_SERVER array. Then I would change it globally. You are a PHP professional I guess. Maybe you could find that out? I don't want to make a change that would possibly break several installations.

**Comment by fabrixxm** [comment]
Reading docs looks like that `$_SERVER` is always present, and in our use case is populated by php itself (as we need `argc` and `argv` from command line) instead of a web server.

**Comment by annando** [comment]
Okay, I have changed it to the $_SERVER array.

**Pull request merged**
