### PR TITLE
Update jquery.js

### PR DESCRIPTION
**Pull request by StefOfficiel**
jQuery v1.11.1 => jQuery v1.11.2

### CODE REVIEW

**Comment by StefOfficiel** [comment]
The old version was v1.11.1, a new version is available v1.11.2

**Comment by tobiasd** [comment]
new stuff should go into the develop branch, not master. You can change the destination branch when requesting the pull. Can you open another pull request?

**Comment by StefOfficiel** [comment]
Oh Sorry, I do not yet mastered well enough GitHub !

**Comment by tobiasd** [comment]
On Fri, 20 Mar 2015 13:45:03 -0700
StefOfficiel <notifications@github.com> wrote:

> Oh Sorry, I do not yet mastered well enough GitHub !

No problem at all!

**Comment by fabrixxm** [comment]
Branch 'release-3.4' has been created
https://github.com/friendica/friendica/tree/release-3.4

From now until release only bugfixes will be merged. Pull requests must be done against friendica/release-3.4

**Comment by fabrixxm** [comment]
Closing this. Waiting for a new pull request against release-3.4

**Comment by StefOfficiel** [comment]
So the proposal is better in the release-3.4 rather than Develop branch ?
So if I understand correctly, I redo demand release-3.4 !

**Pull request closed without merging**
