### PR TITLE
restore THEMEPATH variable in mod/view

### PR DESCRIPTION
**Pull request by tobiasd**
Without this variable in mod/view the style.php files did not work (frio and vier)

### CODE REVIEW

**Comment by MrPetovan** [comment]
Reverts part of https://github.com/friendica/friendica/pull/6407/commits/1f46d0fe3fdac35fdc3670cb15ea3516bb1f963a in #6407

**Comment by MrPetovan** [comment]
Thanks for complying with my exasperated comment!

**Comment by tobiasd** [comment]
The `style.php` from the theme is loaded and end with an echo for the generated CSS and while generating the CSS the `THEMEPATH` is needed for e.g. theme variants.

**Comment by MrPetovan** [comment]
But the `$THEMEPATH` variable isn't declared as global, has no other assignment than in a function, so scope should be limited to the function itself, or so I thought.

**Comment by tobiasd** [comment]
Yes. But the `require` inheritets the scope of the line it is called from. So in this case, the variable is defined in the function and that scope is passed through the evaluation of the `style.php`.

**Comment by MrPetovan** [comment]
Ah, good point. I hate this implicit way of passing a variable to an included script.

**Pull request merged**
