### PR TITLE
Update messages.po

### PR DESCRIPTION
**Pull request by joaovitorwitt**
Addressing Portuguese(Brazil) translations.

### CODE REVIEW

**Comment by MrPetovan** [comment]
Thank you so much for your work! Unfortunately we use a specific workflow based on Transifex (https://explore.transifex.com/Friendica/friendica/) which means your file changes would be clobbered the next time we pull translations from Transifex.

Please register as a translator over there to save your translations through the expected process.

**Comment by joaovitorwitt** [comment]
But would the commit still display as me who contributed?

**Comment by MrPetovan** [comment]
Yes, the Transifex-generated PO file always contains the name of all the translators who contributed translations, per language. You can see this list in the current file.

Additionally, @tobiasd makes a point to mention translators when he commits these files before a release.

**Comment by tobiasd** [comment]
You wont be named for "this" commit, but you are listed in the language file you have been working on and all the translators are listed on the contributors listing in the CREDITS.txt file (updated once before the release is done).

If you want to be part of the git history as well, you can also make the PR for including the translation. But as long as the translation is not done at Transifex (it might be, that general translators can also use the upload function - not sure at the moment), it can happen that it is lost with the next translation update.

**Comment by joaovitorwitt** [comment]
I see now. I will definitely sign up there. Thank you for the information.

**Pull request closed without merging**
