### PR TITLE
Add "Remember this device" feature to two factor authentication

### LINKED ISSUE #9677: Add "Remember this device" feature to 2FA auth
See https://forum.friendi.ca/display/0b6b25a8-115f-dcce-d35c-8e1607849246

Having the device you have your 2FA app constantly asks for a 2FA token doesn't make much sense. A "Remember this device" feature would remember the first valid 2FA code entered and not ask again until the cookie expires.

### PR DESCRIPTION
**Pull request by MrPetovan**
Closes #9677 

This PR outlines the way I'd like us to use classes going forward. I've been looking into Domain Driven Design on my own in the absence of @nupplaphil to explain it, and I've come to the conclusion that it isn't really suited for Friendica given the extensiveness of the changes we would have to make to the existing codebase. As a result, I've boiled down the exact features I wanted Friendica to have moving forward to the following list:
1. Group classes by feature instead of by type. This makes closely related classes also closer in the project's file tree. I grouped all the classes for two-factor authentication, except modules since I believe it helps to see them all in the same folder.
2. Have entities with explicit properties: This makes objects intuitive to use because properties are declared. The current `BaseModel` class fails in this regard because we've added a layer of abstraction with the `BaseModel->data` and `BaseModel->originalData` properties for performance optimization.
2. Manipulate entities properties only through meaningful methods. Allowing properties to be changed arbitrarily makes troubleshooting harder. Making the properties protected allows to have complete control how they are changed.
3. Dissociate entities and database: I now believe entities shouldn't be tied to the database to keep the entity classes as simple as possible. Adding a database dependency immediately increases the cost of testing for example. The current `Introduction` model fails in this regard.
4. I've already created Repositories to retrieve and store models, and future ones will need to be adapted to use entities instead of current models.
5. Factories will be in charge of instantiating entities depending on the expected use cases. Direct entity instantiation is discouraged.

This set of expectations is way simpler than what Domain Driven Design describes, but I've yet to match them against a more complex case than the simple trusted browser case depicted in this PR. In particular I didn't have to manage entities depending on a foreign key for example.

I may try to rewrite the introduction system to make it closer to this vision.

This PR is a draft because the remember this device feature is working, but it's missing the user settings part where trusted browsers can be displayed and revoked.

### CODE REVIEW

**Comment by MrPetovan** [comment]
I've now added the trusted browser user settings page. This PR is best reviewed like a fine wine, slowly and sip by sip. Each commit is atomic to a specific change this PR makes.

**Comment by annando** [comment]
I had several beers, shoudl I review it now? 😁

**Comment by MrPetovan** [comment]
Sounds like the ideal state to review a security-related feature.

**Comment by annando** [comment]
I guess this weekend I will try having a look at this. 

BTW: I'm lacking the ability to understand abstract theoretical descriptions (one of the reasons why I never went to university), so I hope that I will understand this by looking into the code.

P.S.: Are you running this code on your system? I'm getting nervous every time I see PRs that include that much changes.

Edit: Do you know any explanation, tutorial, documentation ... that explains what a "Factory" stands for, what a "Collection" is and where is the difference between "implements" or "extends" when it comes to classes? (I refer to the difference between `abstract class BaseEntity implements \JsonSerializable` and `abstract class BaseEntity extends BaseDataTransferObject`). And I must admit that I don't even know what `abstract` stands for.

I'm lacking basic understanding of object orientated coding in general and how it is implemented in PHP. I'm in need of some documentation that does explain this stuff without much words but with many visual examples.

**Comment by MrPetovan** [comment]
I can quickly fill you in on the PHP vocabulary:
- `abstract` means that no object from that class can be instantiated. For example, `$object = new BaseEntity();` would trigger a fatal error. Abstract classes are meant as parent class-only.
- `extends` means that the class inherits from the mentioned class. A class can only inherit from a single class, and this allow the child class to use the parent classes' methods as their own, including their grand-parent classes' method, and so on.
- `implements` means that the class behaves according to the mentioned interfaces. A class can implement multiple interfaces, but unlike inheritance, all the interface methods must be explicitly written (or implemented) in the class itself.

On the design terminology:
- A `Factory` simply instantiates objects, it calls the construct method with the correct parameters. Additionally, if some parameters can have a complex default value (like a random string, a creation date, etc...), the Factory can take care of it.
- A `Collection` is a just a list of objects. It's used to formally identify a list of a specific object in the parameters of methods.

Let me know if you need more information about any or all of these topics or maybe charts! I like making charts.

**Comment by MrPetovan** [comment]
For your other question, I am running this code on my dev node, and while extensive, the changes are limited to authentication so it was easy to test for obvious mistakes in the refactoring.

**Comment by annando** [comment]
I really would like to watch some video tutorials. My way of understanding is extremely based on visual (and if appropriate hapticle) experience. Text is vanishing in my mind in the moment that I read it. (That's the problem with a short attention span)

Possibly some chart could help about the structure that objects should be placed in the folder structure - and their purpose? I'm not against advancing in the code at all. I'm just this old mule that needs to be convinced about every step it does.

**Comment by MrPetovan** [comment]
Unfortunately all of this is second nature to me so I do not have handy any visual or haptic resource you'd need to help with your understanding.

**Comment by annando** [comment]
Returning to the essential part of this PR: What is it about to do and where is the relevant part of the code?

**Comment by MrPetovan** [comment]
1. It allows to store arbitrary data in the Friendica cookie. Before this PR the Friendica cookie had a rigid structure that didn't allow to add or remove a single key from it.
2. It allows record trusted browsers. Trusted browsers are identified with a random value that is sent to them in the cookie.
3. When a browser sends one of these hash corresponding with the user trying to authenticate, we skip the two-factor authentication step.
4. A user setting page allows to track how many browsers have been trusted, the last time they have been used to authenticate, and some basic information about the device, OS and browser from the User Agent we collected initially.
5. Finally, browser trust can be revoked on a browser basis or for all the existing trusted browsers.

**Comment by annando** [comment]
I'm still thinking about if this is a good idea from a security standpoint. Is this a common method?

Also I still have to find that functionality in the code :-)

**Comment by MrPetovan** [comment]
The typical use case that I illustrated in the checkbox label is if you're browsing Friendica from the device where your two-factor authentication token app is installed. In this case it makes no sense asking for a code someone could directly get on the same device.

It doesn't change anything else since it doesn't grant authentication on its own.

> Also I still have to find that functionality in the code :-)

Which one from the five I listed?

**Comment by annando** [comment]
I meant: The PR consists of many different files - many are class definitions, changed class names, some are responsible for some frontend settings - I also saw the new part in `src/Security/Authentication.php` - but I haven't found the functionality in between. Like I said: I guess I need to take some classes in OOP before being able understanding that stuff.

**Comment by MrPetovan** [comment]
The two main parts are in `src/Security/Authentication.php` and `src/Module/Security/TwoFactor/Verify.php`:
- `Authentication.php`: During two-factor authentication decition we verify the cookie value is set and matches a trusted browser record. If it also matches the id of the user currently logging in, we skip two-factor authentication, otherwise we delete the cookie value.
- `Verify.php`: During the two-factor authentication, a checkbox allows to mark the current broswer as trusted. If checked, we create a new trusted browser record including a random string that we add to the Friendica cookie.

**Comment by annando** [comment]
Quick status update: The last days since the weekend had been really busy. Possibly this PR will have to wait until the weekend.

**Comment by MrPetovan** [comment]
Thank you for the update, it's okay, take your time.

**Comment by annando** [comment]
I just realized that the database version hadn't been increased. But this should be no problem since the has been increased by my last PR.

**Pull request merged**
