### PR TITLE
Remove Includes

### PR DESCRIPTION
**Pull request by zeroadam**
Removed references to include/config.php and include/probe.php and deleted the respective files. Follow up to #3873

### CODE REVIEW

**Comment by MrPetovan** [comment]
You deleted the wrong `probe.php`, it is supposed to be `include/probe.php`, not `mod/probe.php` ! I know this is confusing, but after this is merged, it's going to be less confusing!

**Comment by zeroadam** [comment]
argh! sorry about that

**Comment by annando** [comment]
Before we can accept this PR, we have to check the addons if they contain these includes as well.

**Comment by zeroadam** [comment]
I did a search of the addons and did not find any files with include/config or include/probe

**Comment by annando** [comment]
Thanks for your work!

Do you think that something like issue https://github.com/friendica/friendica/issues/3878 could be doable for you as well?

**Comment by zeroadam** [comment]
Very welcome! I've been wanting to contribute for some time now. I did look at #3878 not long after you opened it. I could certainly give it a shot, and coordinate with you all if I find trouble. You can certainly "assign" it to me if you'd like.

**Comment by MrPetovan** [comment]
Unfortunately, assignment only works with people set as contributors with write access to the repository, but feel free to take a stab at it, and don't hesitate to ask questions either here or on the Friendica Developers Forum (https://forum.friendi.ca/profile/developers).

**Comment by annando** [comment]
Thanks for your work!

Do you think that something like issue https://github.com/friendica/friendica/issues/3878 could be doable for you as well?

**Comment by annando** [comment]
I guess we can do some preparations, like finding the best class path and so on.

**Comment by MrPetovan** [comment]
Periodic reminder: https://ethercalc.org/friendica_classes

**Comment by annando** [comment]
Well, yeah ... documentation ...

**Pull request merged**
