### PR TITLE
Improve image upload limits desc

### PR DESCRIPTION
**Pull request by MarekBenjamin**
A first little improvement regarding [https://github.com/friendica/friendica/issues/7807](url)

Added information that the upload limit for images does not affect server side configutations for de, en-gb and en-us

### CODE REVIEW

**Comment by MarekBenjamin** [comment]
It is only a small incremental update (improvement) yet, still it is important for me to understand the process using GitHub open source collaboration, so feel free to tell me if I missed anything regarding "best practice" :-)

**Review by MrPetovan — CHANGES_REQUESTED** [review]
The files in `lang` are automatically generated from the translations done over at Transifex and your current changes would be erased next time we perform a translation import.

Please change the translation string where it appears in the actual code:

https://github.com/friendica/friendica/blob/5501f703ae261ac5dd1f10fc4e65b6630b500f0b/src/Module/Admin/Site.php#L470

And then you have to run `bin/run_xgettext.sh` which you clearly did but notice there aren't any changes in the `messages.po` file, which prevents translators from ever seeing your changed translation string.

**Comment by MarekBenjamin** [comment]
Okay, cool, learned something. Thanks. I'll do so. A remaining question still: How can I then change the German string? Or perhaps faster to answer (y/n): In the code base, we are only able to change the C = en language strings and then have to wait for external translations? :)

**Comment by MrPetovan** [comment]
> How can I then change the German string?

Once your PR has been merged, Transifex should pick up the changes within a day (@tobiasd can confirm?) and then you can yourself translate the string to German. We still translate the base strings in English because it's easier to fix the potential language/spelling mistakes in the translations than in the base strings. So we never assume that the base strings are enough, especially since there are discrepancies between British English and American English.

See: https://explore.transifex.com/Friendica/friendica/

**Comment by MarekBenjamin** [comment]
> then you can yourself translate the string to German

on https://explore.transifex.com/Friendica/friendica/ , right? :-)

**Comment by tobiasd** [comment]
Yes, they update the base files for the translation on a regular basis, usually after a day the new strings arrive for the translators.

**Pull request closed without merging**
