### PR TITLE
Prevent full page to load on save to folder modal

### LINKED ISSUE #6952: File to folder not working
## Expected behaviour

Being able to file postings to folders.

## Actual behaviour

In the current development branch I'm unable to select a folder to file a posting to.

The dialog is empty and collapsed to the border of the box (using the vier theme), or contains the navbar of the page, but otherwise no content (using the frio theme).

This happens using Firefox 60.6 (LSR) and Vivaldi 2.4 (stable channel).

## Friendica Version

2019.06-dev, commit 1c2a77c47fbc5fed030b0c82fa3f37c0361955ce

### PR DESCRIPTION
**Pull request by MrPetovan**
Fixes #6952

### CODE REVIEW

**Comment by nupplaphil** [comment]
This seems like a different behavior for the same task as `content()`.
Wouldn't be better to the `print` statement to the calling function than to use a different way?

**Comment by MrPetovan** [comment]
The original module was hastly designed and used `content()` as we now use `rawContent()` instead of using the `mode=none` query string which removes the page template as well using the `content()` method.

In the end, I chose to honor the original design instead of editing all instances of `filer/` in the javascript files.

**Comment by nupplaphil** [comment]
Sounds like a followup task after the ongoing `mod/` => `src\Module` task

**Comment by MrPetovan** [comment]
Ideally, each module should be able to select its own template (`full`, `minimal` or `none`), which means that the templating engine (that should be passed to the module through dependency injection) will have to put the page together, not the `App`. So this is likely to be the followup-followup task.

**Comment by nupplaphil** [comment]
"Sadly" I do have a fulltime job ;-) .. I'm really excited about such tasks haha...

**Pull request merged**
