### PR TITLE
Remove new lines from domain name part of autolinker regular expression in Util\Strings

### PR DESCRIPTION
**Pull request by MrPetovan**
Follow-up to #6845 and #6841 

- Fixes issue where the autolinker would include the next paragraph is a pathless URL was followed by new lines.

### CODE REVIEW

**Comment by nupplaphil** [comment]
Hm.. I think a test would be possible to add such a new line problem, wouldn't it? :-)

**Comment by MrPetovan** [comment]
Yes, but not in a single-file commit from the GitHub interface. Oooh wait.

**Comment by MrPetovan** [comment]
I just rediscovered how to add new lines in a PHP string 🙄

**Comment by MrPetovan** [comment]
@nupplaphil Hey, it's the Closure serialization issue again!
```
Fatal error: Uncaught Exception: Serialization of 'Closure' is not allowed in - on line 72
Exception: Serialization of 'Closure' is not allowed in - on line 72
Call Stack:
    0.0028     735696   1. {main}() -:0
    0.0296    5333048   2. __phpunit_run_isolated_test() -:104
    5.2220   16694664   3. serialize() -:72
```
Why is it only triggering for the tests cases I added?

**Comment by nupplaphil** [comment]
@MrPetovan 
You have to delete the two annotations again and try it locally again.
This is because of the static dependency usages. F.e. if we use the `L10n::t()` function, PHP automatically creates a global instance of `L10n` and reuses it everywhere, even for another tests. So if we want to mock `L10n::t()` instead of the global instance, we get an error "already defined".

The two annotations forces the phpunit test to use another process for the test and remove any global states/instances. But they also encapsulate these tests, which leads to uncertain failures in case of a PHP failures during tests (not the asserted failures!). 

So if you remove the annotations, these encapsulation vanish and you can see the "real" PHP error behind it. But in case you execute the `ApiTest` first and than this test, the test won't work anymore (as described above).

My next part would be to make `DBA` and after it `L10n` as dynamic instance (which are initialized as static dependencies like Config), so we can remove the annotations at all :-)

**Comment by MrPetovan** [comment]
Tests are fine, Travis choked on a wrong TLS packet from git.friendi.ca.

**Comment by nupplaphil** [comment]
@mrpetovan there's a small retry circle near every Travis test. Every collaborator can click it.

**Comment by MrPetovan** [comment]
I've been looking for the dang thing, but I can't seem to be able to find it.

**Comment by MrPetovan** [comment]
Ha, I wasn't logged in the Travis website, is it where the "Restart" button is?

**Comment by nupplaphil** [comment]
**Login**
2019-03-13 09_08_11-Build #4025 - friendica_friendica - Travis CI

**Retry Icons**
2019-03-13 09_08_36-Build #4025 - friendica_friendica - Travis CI

**Comment by MrPetovan** [comment]
Ok, so I need to be logged in first into Travis.

**Comment by nupplaphil** [comment]
yep

**Comment by MrPetovan** [comment]
Fixes #6866

**Pull request merged**
