### PR TITLE
Move video js to Composer

### PR DESCRIPTION
**Pull request by MrPetovan**
Part of #4265

This one was a pain.

The original library was self-contained and its only crime was to be in the wrong place at the wrong time.

I tried to upgrade from video.js 4 to video.js 6 because I probably could.

First of all the Bower package and the Composer package both require a build step that I wouldn't even know how to trigger. The npm package had the prized `dist` folder with the ready-to-use library, but it also imported a bunch of dependencies that are only used during the build and are bundled in the final library anyway.

Not only that, but the documentation for the version 6 is atrocious, and I couldn't find how to keep the flash fallback that was previously bundled.

I then tried to upgrade only to video.js 5 which solved the flash issue, being the last version with the swf bundled with, but I ended up with the same amount of throwaway dependencies.

I then decided to keep the version 4, but I found out that it didn't have the fluid setting to make the video size responsive.

I finally solved this issue myself by locking the 16:9 ratio but oh boy am I mad at the video.js devs right now. They awkwardly are in a situation of quasi-monopoly over the HTML5-falling-back-to-Flash Javascript library market, and yet their documentation is awful and their integration with third-party package managers is sloppy at best.

I briefly looked at alternatives (spoiler: they aren't many) but in the end it wasn't in the scope of this issue and I already had spent way too much time to dive into yet another library.

### CODE REVIEW

**Comment by fabrixxm** [comment]
What we gain using videojs instead of a plain html5 video tag?

**Comment by tobiasd** [comment]
> What we gain using videojs instead of a plain html5 video tag?

My guess would be the flash player fallback. Though I wonder why one would need such a fall back?

**Comment by annando** [comment]
What exactly is the use of the library? When it is needed? Do we have some disadvantages from not using it anymore? (I would like to drop anything concerning Flash as soon as possible)

**Comment by MrPetovan** [comment]
I don't think we need it anymore. The `<video>` tag has [94% support](https://caniuse.com/#feat=video) and video-js doesn't solve the video format compatibility issues.

**Comment by annando** [comment]
Okay, I hope that your fun during trashing code will be higher than the sadness that the work for several hours was for the drain.

**Comment by MrPetovan** [comment]
I'm always having fun trashing code. The annoying part is that I need to be home to test the responsive part of this PR.

**Pull request closed without merging**
