### PR TITLE
Automatic release artifact generation

### PR DESCRIPTION
**Pull request by nupplaphil**
This PR enables automatic artifact generation during releases, including:
- `friendica-full-{VERSION}.tar.gz`
- `friendica-full-{VERSION.tar.gz.sha256`

It is a first part of making Friendica 7.3 compatible and transpiling it back to 7.0
Nevertheless, it's helpful during releases to automatic package only files, which are needed at runtime (excluding the whole tests-directory and other dev-tools)

ToDo:
- [x] replace pull_request event with release event as last step

### CODE REVIEW

**Comment by nupplaphil** [comment]
This run https://github.com/friendica/friendica/runs/2494516849 of https://github.com/friendica/friendica/pull/10203/commits/64332c8c2b2d9a9bf543957ecd6c4540d5051ee7 proves that the release package will get created.
See output https://github.com/friendica/friendica/suites/2641644524/artifacts/57997219 f this run

The last commit "just" enables the workflow for the publish step only and adds the last `upload to release` step

@MrPetovan / @tobiasd - if we additionally use https://github.com/marketplace/actions/ftp-action , we could automatically create `SNAPSHOT` archives every "XX" minutes (with a previous check if the codebase changed of course) and upload them to https://files.friendi.ca
=> so no need to use GIT commands anymore for dev/rc deployments :)

**Comment by tobiasd** [comment]
How do we run this without github? Because the plan still is to get rid of it. For me this looks like getting deeper into it.

**Comment by MrPetovan** [comment]
I'm with @tobiasd, what you did is great and I'd like to have the assurance we can still use it when we definitely move away from GitHub.

**Comment by nupplaphil** [comment]
At least it's a "workflow", so it should work at different platforms similar.

But you're right, I'm using native Github functionality for it.
Maybe I can create a "drone" script instead for it and talk to @utzer to enable drone again :-)

**Review by MrPetovan — APPROVED** [review]

**Pull request merged**
