### PR TITLE
Creating Database class out of DBA (nearly 1:1 - copy)

### PR DESCRIPTION
**Pull request by nupplaphil**
Rebased copy of #7232

Another day, another try ...

This time, I nearly copy&pasted everything from DBA to Database without altering any comments, business logic or naming conventions.

- No Interfaces
- No inheritance
- No class normalization

What I did:
- Copied every non-static business logic to Database
- Replaced `self::` with `$this->`
- Added a constructor for initial load in Database (this should be the same code as the first 1/3 of the old DBA::connect() method)
- Reused every method signature of DBA

In fact we can now use Database in the same way as DBA except using $this-> instead of self::. And for outside, DBA:: calls are usable the same way as before.

On my local node, it works fine, next thing would be to push it to my friendica node ..

This kind of change is sadly a prerequisite for any optimiziation for the tests - The tests are becoming more and more slow and in the same way un-maintainable for complex tests..

Additional this branch got rebased and used during the whole -rc phase on https://friendica.philipp.info without any specific failures.

### CODE REVIEW

**Comment by nupplaphil** [comment]
So my next PRs should proovable reduce the test-speed - Challenge accepted ;-)

**Comment by MrPetovan** [comment]
Increase the speed, or decrease the duration, but reduce the speed isn't good!

**Comment by nupplaphil** [comment]
> 
> 
> Increase the speed, or decrease the duration, but reduce the speed isn't good!

haha .. of course, thanks ;-)

**Comment by annando** [comment]
@nupplaphil  Are you planning on separating the MySQL-class functions from the PDO-class functions? I'm asking because of PostgreSQL-support. This would then use the identical PDO class with only some slight changes. Before I start with this, I need some class structure that is ready for this stuff.

Or I advise you on my planned changes. Then you can make them.

**Comment by nupplaphil** [comment]
I'd like that you advise me what changes you want.

On the other hand, If you like, you can change them too and I advise some OOP stuff if necessary. So I can stay on a path which is maintainable by you.

**Pull request merged**
