### PR TITLE
The "item" table is now replaced

### PR DESCRIPTION
**Pull request by annando**
We now don't use the "item" table anymore.

Currently the tests fail and I want to check the system if really everything works well.

### CODE REVIEW

**Comment by annando** [comment]
@MrPetovan can you explain the errors?

**Comment by MrPetovan** [comment]
I cannot say immediately, it's an indirect error that is the sign of something else but it's been long enough since I last saw this that I can't be of immediate assistance.

**Comment by MrPetovan** [comment]
The diff is currently too big to be correctly analyzed for this test error, the best I can suggest is to create anew branch, open a PR with it, and cherry-pick commits one by one, waiting for the tests to run before the next. Then we may have a better idea about what is failing.

**Comment by annando** [comment]
I currently have the issue that the automatic update after commenting or liking doesn't work on the network page (but on "display"). I'm unsure if this is caused by this PR or by another one, since in the meantime I merged the latest changes.

**Comment by AlfredSK** [comment]
I just liked a post on network page and it showed the like immediately.

Edit: on another post it didn't work. Waited 1 minute. No auto update to show the like. Had to reload the page.

🤔

**Comment by annando** [comment]
The network update does work now.

The current situation is that I want to check the query that cleans up data. But otherwise the system now seems to work fine.

**Comment by MrPetovan** [comment]
Let's wait for 24 hours. 😅

**Comment by annando** [comment]
I just tested the query that made problems this night. So I guess you can start your review.

BTW: I have the feeling that the system is faster now. When creating the tables, I had to choose between space and performance. I now tended to performance, so the space gain is not as much as I wished. But the good thing is that the structure is now so flexible that we can easily improve the structure over time.

**Comment by MrPetovan** [comment]
I have no way of reviewing this correctly because of the size of the PR. I have to blindly trust you, and while it's made easier by the fact that you are making changes on a production node, I am bracing for the upcoming issue wave arising from such a big change.

**Review by MrPetovan — APPROVED** [review]

**Comment by AlfredSK** [comment]
Hmm... the item table. Is this database update huge or super huge? :-) Should I expect a long running update and plan the maintenance window accordingly?

**Comment by AlfredSK** [comment]
@annando Ah! I saw your forum post now. Thanks!

> The update routines will most likely take some time, possibly some hours.

**Comment by AlfredSK** [comment]
> We now don't use the "item" table anymore.

So... can we drop it then? 😬

**Comment by annando** [comment]
Sadly no. The item is still needed to deliver posts that had been created prior to the update. So during the retrial phase we mustn't do anything to this table. And afterwards we can only delete the whole content.

**Comment by AlfredSK** [comment]
`:crying_cat_face:`

**Comment by annando** [comment]
Yeah, I'm sorry. I'm currently thinking about some update routine that could alter the workerqueue entries. Then we could remove that table.

**Comment by AlfredSK** [comment]
No need to be sorry. I was just hoping that the table would become obsolete and I can get rid of that huge thing.

**Comment by annando** [comment]
@AlfredSK see https://github.com/friendica/friendica/pull/9945

**Pull request merged**
