### PR TITLE
Pass SRL instead of ZRL to the global directory URL

### PR DESCRIPTION
**Pull request by MrPetovan**
- ZRL was used alongside the dfrn_request module that doesn't exist anymore

Depends on https://git.friendi.ca/friendica/friendica-directory/pulls/87

### CODE REVIEW

**Comment by annando** [comment]
The git server currently seems to have issues, so I add my comment here as well. Why are we using a new parameter and not just performing some webfinger request at the server? This would make it compatible for all user of all versions instantaneously.

**Comment by MrPetovan** [comment]
Because we can't have the directory page load depend on remote lookups, especially with Friendica hosts where performance isn't always great with cheap/home servers.

My other solution for backward compatibility is to to the webfinger lookup during server poll and store the subscribe URL template for each server. Then we can use the zrl parameter to fetch the subscribe URL of the visitor's server from the local database and present them with the correct follow link.

But the srl parameter is faster and works with servers that the directory doesn't know about.

**Comment by MrPetovan** [comment]
However, I tried the `/xrd` endpoint on my node and it doesn't show anything, am I missing a required parameter?

**Comment by annando** [comment]
You need to perform a webfinger request. That URL is fixed.

**Pull request closed without merging**
