### PR TITLE
Storage Backend: wording of admin panel help

### PR DESCRIPTION
**Pull request by tobiasd**
Followup to #6591

### CODE REVIEW

**Comment by annando** [comment]
Isn't it some "you have to manually move the data, otherwise it only has an effect of new data"? So the "hove to" would be right?

**Comment by tobiasd** [comment]
If you don't execute the command, then the old data will stay at the old storage facility and the new data is stored with the new backend. Hence the *can*, you don't have to.

**Comment by annando** [comment]
Possibly we can clarify this?

**Comment by MrPetovan** [comment]
Maybe with "The backend used to store *new* uploaded files data"?

**Comment by tobiasd** [comment]
But old data is stored as well. I could add a sentence that old data remains in the old backend, if the move is not executed.

**Comment by MrPetovan** [comment]
Yes, it should be clear that old data still is accessible in its previous place(s) no matter the current setting value. Hence the "new" keyword.

**Pull request merged**
